// A1 · Артиклі — 10 повних уроків.
import type { A1Map } from "./_helpers";

const CAT = "Артиклі";

export const artikelA1: A1Map = {
  // 1 ===================================================================
  "bestimmter-artikel": {
    lesson: {
      slug: "bestimmter-artikel", level: "A1", category: CAT,
      titleDe: "Bestimmter Artikel", titleUk: "Означений артикль",
      goal: "Розуміти, коли вживається der/die/das, і не плутати з неозначеним.",
      explanation: [
        "<b>Означений артикль</b> (<b>der, die, das</b>) вживається, коли йдеться про <b>конкретний</b> або <b>уже відомий</b> об'єкт.",
        "Уживається з унікальними речами (<b>die Sonne, der Mond</b>), у другій згадці предмета, із загальними поняттями (<i>Die Liebe ist schön.</i>).",
        "У множині для всіх 3 родів — <b>die</b>: <i>die Männer, die Frauen, die Kinder</i>.",
        "В українській артиклів немає, тому в перекладі вони часто «зникають» — але в німецькій їх <b>обов'язково</b> ставити.",
      ],
      table: {
        headers: ["Рід / число", "Артикль", "Приклад"],
        rows: [
          ["m (Sg.)", "der", "der Mann"],
          ["f (Sg.)", "die", "die Frau"],
          ["n (Sg.)", "das", "das Kind"],
          ["Pl.", "die", "die Kinder"],
        ],
      },
      examples: [
        { de: "Der Mann liest die Zeitung.", uk: "Чоловік читає газету.", tag: "обидва конкретні" },
        { de: "Das Buch liegt auf dem Tisch.", uk: "Книга лежить на столі." },
        { de: "Die Kinder spielen im Garten.", uk: "Діти граються в саду." },
        { de: "Die Sonne scheint hell.", uk: "Сонце світить яскраво.", tag: "унікальне" },
        { de: "Wo ist der Schlüssel?", uk: "Де ключ?" },
        { de: "Die Liebe ist wichtig.", uk: "Любов важлива.", tag: "загальне поняття" },
        { de: "Heute ist der Montag.", uk: "Сьогодні понеділок." },
        { de: "Ich gehe in die Schule.", uk: "Я йду до школи." },
      ],
      tip: "Уживай <b>der/die/das</b>, коли можеш сказати «цей конкретний» або «той, що ми вже згадували».",
      mistakes: [
        { wrong: "Mann liest Zeitung.", right: "Der Mann liest die Zeitung." },
        { wrong: "Das Kinder spielen.", right: "Die Kinder spielen." },
        { wrong: "Der Sonne scheint.", right: "Die Sonne scheint." },
      ],
      exercises: {},
      nextSlug: "unbestimmter-artikel",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати 3 форми означеного артикля",
        "вибирати der/die/das згідно з родом",
        "вживати die у множині",
        "не пропускати артикль у реченні",
      ],
      ruleBox: {
        rule: "<b>der</b> (m) · <b>die</b> (f) · <b>das</b> (n) · <b>die</b> (Pl.). Уживається для конкретних, відомих або унікальних об'єктів.",
      },
      ukrainianTips: [
        "Українському «ця книга / та книга» приблизно відповідає <b>die</b>. Просте «книга на столі» — теж <b>die</b>.",
        "Унікальне (<i>сонце, місяць, земля</i>) — завжди з означеним артиклем.",
        "Перед другою згадкою предмета — <b>означений</b>: <i>Da ist ein Hund. <b>Der</b> Hund ist groß.</i>",
      ],
      languageComparison: {
        commons: ["Конкретні об'єкти — і в українській, і в німецькій."],
        diffs: ["Українська обходиться без артикля."],
        traps: ["Пропуск артикля сприймається як зламана німецька."],
      },
      summary: [
        "der · die · das · die (Pl.).",
        "Конкретний / відомий / унікальний → означений.",
        "Друга згадка → завжди означений.",
        "Множина — завжди <b>die</b>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Mann arbeitet.", options: ["Der","Die","Das","Den"], correct: 0 },
      { type: "mc", q: "___ Frau heißt Anna.", options: ["Der","Die","Das","Den"], correct: 1 },
      { type: "mc", q: "___ Kind spielt.", options: ["Der","Die","Das","Den"], correct: 2 },
      { type: "mc", q: "___ Kinder lachen.", options: ["Der","Die","Das","Den"], correct: 1 },
      { type: "gap", q: "___ Sonne scheint.", answer: "Die" },
      { type: "gap", q: "___ Buch liegt hier.", answer: "Das" },
      { type: "gap", q: "___ Schlüssel ist weg.", answer: "Der" },
      { type: "tf", q: "У множині для всіх родів — die.", correct: true },
      { type: "tf", q: "Унікальні слова (Sonne, Mond) — без артикля.", correct: false },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Mann", right: "der" },
        { left: "Frau", right: "die" },
        { left: "Kind", right: "das" },
        { left: "Kinder", right: "die" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Mann liest Buch.",
        "Der Mann liest das Buch.",
        "Das Kinder spielen.",
        "Die Kinder spielen.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Kinder spielen.", correct: ["Die Kinder spielen."] },
      { type: "order", prompt: "Склади речення:", words: ["scheint","Die","Sonne","heute"], correct: ["Die","Sonne","scheint","heute"] },
      { type: "translate", prompt: "Переклади:", uk: "Чоловік читає газету.", de: ["Der Mann liest die Zeitung."] },
      { type: "writeFree", prompt: "Напиши 3 речення з означеними артиклями.", sample: "Der Hund spielt. Die Lampe ist neu. Das Kind lacht.", explain: "Перевір артикль." },
    ],
  },

  // 2 ===================================================================
  "unbestimmter-artikel": {
    lesson: {
      slug: "unbestimmter-artikel", level: "A1", category: CAT,
      titleDe: "Unbestimmter Artikel", titleUk: "Неозначений артикль",
      goal: "Уживати <b>ein/eine</b>, коли йдеться про новий, нечітко окреслений об'єкт.",
      explanation: [
        "<b>Неозначений артикль</b> (<b>ein, eine, ein</b>) вживається, коли об'єкт <b>згадується вперше</b> або не уточнюється: <i>Da ist ein Hund.</i>",
        "Форми: <b>ein</b> для m/n, <b>eine</b> для f. У множині <b>немає</b> неозначеного артикля.",
        "Часто перекладається українським «якийсь / один»: <i>Ich kaufe ein Buch.</i> = «Я купую (якусь) книгу».",
        "Після другого згадування предмета переходимо на <b>означений</b>: <i>Ich sehe einen Mann. Der Mann ist alt.</i>",
      ],
      table: {
        headers: ["Рід", "Артикль (Nom.)", "Приклад"],
        rows: [
          ["m", "ein", "ein Mann"],
          ["f", "eine", "eine Frau"],
          ["n", "ein", "ein Kind"],
          ["Pl.", "—", "Kinder (без артикля)"],
        ],
      },
      examples: [
        { de: "Da ist ein Hund.", uk: "Там собака." },
        { de: "Ich habe eine Schwester.", uk: "У мене є сестра." },
        { de: "Wir kaufen ein Haus.", uk: "Ми купуємо дім." },
        { de: "Ein Mann wartet vor der Tür.", uk: "Якийсь чоловік чекає перед дверима." },
        { de: "Hier ist ein Brief für dich.", uk: "Ось лист для тебе." },
        { de: "Sie hat einen Bruder.", uk: "У неї є брат.", tag: "Akk. m → einen" },
        { de: "Möchten Sie eine Tasse Tee?", uk: "Хочете чашку чаю?" },
        { de: "Da spielen Kinder.", uk: "Там граються діти.", tag: "Pl. — без артикля" },
      ],
      tip: "У множині <b>немає</b> неозначеного артикля: <i>Da spielen <b>Kinder</b></i>, не <i>eine Kinder</i>.",
      mistakes: [
        { wrong: "Ich habe ein Schwester.", right: "Ich habe eine Schwester." },
        { wrong: "Eine Kinder spielen.", right: "Kinder spielen." },
        { wrong: "Da ist eine Hund.", right: "Da ist ein Hund." },
      ],
      exercises: {},
      prevSlug: "bestimmter-artikel",
      nextSlug: "der-die-das",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати форми ein/eine",
        "розрізняти першу й другу згадку",
        "не вживати неозначений у множині",
        "вживати einen в Akk. m",
      ],
      ruleBox: {
        rule: "<b>ein</b> (m/n) · <b>eine</b> (f) · <b>—</b> (Pl.). Перша згадка → неозначений, друга → означений.",
      },
      ukrainianTips: [
        "Українське «якийсь / один» = німецьке <b>ein/eine</b>.",
        "У німецькій після першої згадки про предмет ставимо <b>означений</b>: <i>Da war ein Mann. <b>Der</b> Mann sagte…</i>",
        "У множині — <b>без артикля</b>: <i>Ich kaufe Äpfel</i>, не <i>eine Äpfel</i>.",
      ],
      languageComparison: {
        commons: ["Поняття «новий vs. відомий» універсальне."],
        diffs: ["У німецькій воно виражене артиклем."],
        traps: ["Українець часто пропускає або ставить «eine Kinder»."],
      },
      summary: [
        "<b>ein/eine/ein</b> у Nom.",
        "У множині — <b>немає</b>.",
        "Перша згадка → неозначений.",
        "Akk. m → <b>einen</b>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["ein","eine","einen","der"], correct: 2, explain: "Akk. m → einen." },
      { type: "mc", q: "Sie hat ___ Schwester.", options: ["ein","eine","einen","die"], correct: 1 },
      { type: "mc", q: "Da ist ___ Hund.", options: ["ein","eine","einen","der"], correct: 0 },
      { type: "mc", q: "Wir kaufen ___ Haus.", options: ["ein","eine","einen","das"], correct: 0 },
      { type: "gap", q: "Sie hat ___ Auto. (Akk. n)", answer: "ein" },
      { type: "gap", q: "Ich brauche ___ Tasse Kaffee. (Akk. f)", answer: "eine" },
      { type: "gap", q: "Da spielen ___ Kinder. (Pl.)", answer: "—", hint: "У множині немає неозначеного." },
      { type: "tf", q: "У множині немає неозначеного артикля.", correct: true },
      { type: "tf", q: "Akkusativ m: ein → einen.", correct: true },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Mann (m)", right: "ein" },
        { left: "Frau (f)", right: "eine" },
        { left: "Kind (n)", right: "ein" },
        { left: "Bruder (Akk. m)", right: "einen" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich habe ein Schwester.",
        "Ich habe eine Schwester.",
        "Eine Kinder spielen.",
        "Kinder spielen.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich kaufe ein Tasse Tee.", correct: ["Ich kaufe eine Tasse Tee."] },
      { type: "order", prompt: "Склади:", words: ["Schwester","Ich","eine","habe"], correct: ["Ich","habe","eine","Schwester"] },
      { type: "translate", prompt: "Переклади:", uk: "У мене є собака.", de: ["Ich habe einen Hund."] },
      { type: "writeFree", prompt: "Напиши 3 речення з неозначеним артиклем.", sample: "Ich habe einen Bruder. Sie hat eine Tasche. Wir kaufen ein Haus.", explain: "Перевір ein/eine/einen." },
    ],
  },

  // 3 ===================================================================
  "der-die-das": {
    lesson: {
      slug: "der-die-das", level: "A1", category: CAT,
      titleDe: "der, die, das", titleUk: "der, die, das — три означені артиклі",
      goal: "Швидко й автоматично співвідносити артикль із родом іменника.",
      explanation: [
        "<b>der</b> — для чоловічого роду: <i>der Tisch, der Mann, der Bruder</i>.",
        "<b>die</b> — для жіночого роду: <i>die Frau, die Schule, die Tasche</i>.",
        "<b>das</b> — для середнього роду: <i>das Kind, das Buch, das Auto</i>.",
        "<b>die</b> — також для <b>множини всіх родів</b>: <i>die Männer, die Frauen, die Kinder</i>.",
        "Один артикль — одна гарантія: <b>він показує рід</b>. Слова без артикля сприймаються як «без обличчя».",
      ],
      table: {
        headers: ["Артикль", "Рід", "Приклад", "Pl."],
        rows: [
          ["der", "m", "der Tisch", "die Tische"],
          ["die", "f", "die Lampe", "die Lampen"],
          ["das", "n", "das Buch", "die Bücher"],
          ["die", "Pl.", "die Männer", "—"],
        ],
      },
      examples: [
        { de: "Der Tisch ist groß.", uk: "Стіл великий." },
        { de: "Die Lampe ist neu.", uk: "Лампа нова." },
        { de: "Das Buch liegt hier.", uk: "Книга лежить тут." },
        { de: "Die Tische sind alt.", uk: "Столи старі.", tag: "Pl." },
        { de: "Der Mann arbeitet.", uk: "Чоловік працює." },
        { de: "Die Frau spricht Deutsch.", uk: "Жінка розмовляє німецькою." },
        { de: "Das Kind schläft.", uk: "Дитина спить." },
        { de: "Die Kinder lachen.", uk: "Діти сміються." },
      ],
      tip: "Вчи кожне слово <b>тричі</b>: артикль вголос, слово, множина. <i>«Der Tisch — die Tische».</i>",
      mistakes: [
        { wrong: "Die Tisch ist groß.", right: "Der Tisch ist groß." },
        { wrong: "Der Lampe ist neu.", right: "Die Lampe ist neu." },
        { wrong: "Das Frau heißt Anna.", right: "Die Frau heißt Anna." },
      ],
      exercises: {},
      prevSlug: "unbestimmter-artikel",
      nextSlug: "ein-eine",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "автоматично казати der/die/das для знайомих слів",
        "знати, що Pl. = die",
        "не плутати артиклі",
        "впізнавати рід нових слів за артиклем",
      ],
      ruleBox: {
        rule: "<b>der</b> = m · <b>die</b> = f та Pl. · <b>das</b> = n.",
      },
      ukrainianTips: [
        "<b>der/die/das</b> — це не «той, та, те». Це <b>граматичний рід</b>. Тому вчи їх як частину слова.",
        "Якщо не знаєш роду — спробуй типове закінчення (-ung → die, -chen → das).",
        "Множина <b>зливає</b> всі роди в <b>die</b>.",
      ],
      languageComparison: {
        commons: ["Поняття роду універсальне."],
        diffs: ["У німецькій є окремий маленький слово-артикль."],
        traps: ["Український рід ≠ німецький."],
      },
      summary: [
        "<b>der</b> — m.",
        "<b>die</b> — f і Pl.",
        "<b>das</b> — n.",
        "Учи разом зі словом.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Tisch", options: ["der","die","das"], correct: 0 },
      { type: "mc", q: "___ Lampe", options: ["der","die","das"], correct: 1 },
      { type: "mc", q: "___ Buch", options: ["der","die","das"], correct: 2 },
      { type: "mc", q: "___ Tische (Pl.)", options: ["der","die","das"], correct: 1 },
      { type: "gap", q: "___ Mann", answer: "der" },
      { type: "gap", q: "___ Frau", answer: "die" },
      { type: "gap", q: "___ Kind", answer: "das" },
      { type: "gap", q: "___ Kinder", answer: "die" },
      { type: "tf", q: "Pl. для всіх родів — die.", correct: true },
      { type: "tf", q: "«das Lampe» — правильно.", correct: false, explain: "die Lampe." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Tisch", right: "der" },
        { left: "Lampe", right: "die" },
        { left: "Buch", right: "das" },
        { left: "Kinder", right: "die" },
      ]},
      { type: "multi", q: "Які з цих — die?", options: ["Tisch","Lampe","Buch","Frau","Mann","Schule"], correct: [1,3,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Die Mann arbeitet.", correct: ["Der Mann arbeitet."] },
      { type: "order", prompt: "Склади:", words: ["Lampe","Die","neu","ist"], correct: ["Die","Lampe","ist","neu"] },
      { type: "translate", prompt: "Переклади:", uk: "Книга стара.", de: ["Das Buch ist alt."] },
      { type: "writeFree", prompt: "Напиши 3 речення з der/die/das.", sample: "Der Hund läuft. Die Lampe leuchtet. Das Kind lacht.", explain: "Артикль = рід." },
    ],
  },

  // 4 ===================================================================
  "ein-eine": {
    lesson: {
      slug: "ein-eine", level: "A1", category: CAT,
      titleDe: "ein, eine", titleUk: "ein, eine — неозначені артиклі",
      goal: "Правильно вибирати ein/eine та змінювати на einen у Akkusativ m.",
      explanation: [
        "<b>ein</b> для чоловічого і середнього роду в Nominativ: <i>ein Mann, ein Kind</i>.",
        "<b>eine</b> для жіночого роду: <i>eine Frau, eine Lampe</i>.",
        "У Akkusativ <b>ein → einen</b> у чоловічому роді: <i>Ich sehe einen Mann.</i> Жіноче й середнє в Akk. <b>не змінюється</b>: <i>eine Frau, ein Kind</i>.",
        "У множині — <b>немає</b> ein-форми.",
      ],
      table: {
        headers: ["Рід", "Nominativ", "Akkusativ"],
        rows: [
          ["m", "ein", "einen"],
          ["f", "eine", "eine"],
          ["n", "ein", "ein"],
          ["Pl.", "—", "—"],
        ],
      },
      examples: [
        { de: "Ein Mann wartet.", uk: "Чоловік чекає." },
        { de: "Eine Frau singt.", uk: "Жінка співає." },
        { de: "Ein Kind spielt.", uk: "Дитина грається." },
        { de: "Ich sehe einen Mann.", uk: "Я бачу чоловіка.", tag: "Akk. m" },
        { de: "Ich kaufe eine Lampe.", uk: "Я купую лампу." },
        { de: "Sie hat ein Auto.", uk: "У неї є автомобіль." },
        { de: "Er hat einen Bruder und eine Schwester.", uk: "У нього є брат і сестра." },
        { de: "Da ist ein Haus.", uk: "Там будинок." },
      ],
      tip: "Запам'ятай <b>«einen» = Akkusativ m</b>. Це найчастіша помилка А1.",
      mistakes: [
        { wrong: "Ich habe ein Bruder.", right: "Ich habe einen Bruder." },
        { wrong: "Ich sehe ein Frau.", right: "Ich sehe eine Frau." },
        { wrong: "Da ist eine Hund.", right: "Da ist ein Hund." },
      ],
      exercises: {},
      prevSlug: "der-die-das",
      nextSlug: "artikel-singular",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "вибирати ein vs eine за родом",
        "автоматично казати einen в Akk. m",
        "розуміти, що Pl. без артикля",
        "правильно ставити неозначений артикль після haben/kaufen/sehen",
      ],
      ruleBox: {
        rule: "Nom: <b>ein/eine/ein</b>. Akk: <b>einen/eine/ein</b>. Pl: <b>—</b>.",
      },
      ukrainianTips: [
        "Заучи правило одним реченням: «<i>Ich habe <b>einen</b> Bruder, <b>eine</b> Schwester, <b>ein</b> Kind</i>».",
        "У множині завжди <b>немає</b> ein.",
        "В Akkusativ змінюється <b>лише</b> чоловічий рід: <i>einen</i>.",
      ],
      languageComparison: {
        commons: ["«Якийсь / один» — універсальна ідея."],
        diffs: ["У німецькій артикль обов'язковий."],
        traps: ["«einen Schwester» — типова помилка (правильно eine)."],
      },
      summary: [
        "ein (m/n) · eine (f).",
        "Akk. m → <b>einen</b>.",
        "f і n у Akk. — без змін.",
        "Pl. — <b>немає</b> артикля.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["ein","eine","einen","der"], correct: 2 },
      { type: "mc", q: "Sie hat ___ Schwester.", options: ["ein","eine","einen","die"], correct: 1 },
      { type: "mc", q: "Wir kaufen ___ Auto.", options: ["ein","eine","einen","das"], correct: 0 },
      { type: "mc", q: "Da ist ___ Mann.", options: ["ein","eine","einen","der"], correct: 0 },
      { type: "gap", q: "Ich sehe ___ Frau. (Akk.)", answer: "eine" },
      { type: "gap", q: "Sie hat ___ Hund. (Akk. m)", answer: "einen" },
      { type: "gap", q: "Wir haben ___ Kind. (Akk. n)", answer: "ein" },
      { type: "tf", q: "Akk. m: einen.", correct: true },
      { type: "tf", q: "У множині — «eine».", correct: false, explain: "Немає неозначеного у Pl." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Bruder (Akk.)", right: "einen" },
        { left: "Schwester (Akk.)", right: "eine" },
        { left: "Auto (Akk.)", right: "ein" },
        { left: "Mann (Nom.)", right: "ein" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich habe ein Bruder.",
        "Ich habe einen Bruder.",
        "Da ist eine Hund.",
        "Da ist ein Hund.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich kaufe ein Lampe.", correct: ["Ich kaufe eine Lampe."] },
      { type: "order", prompt: "Склади:", words: ["habe","Ich","einen","Bruder"], correct: ["Ich","habe","einen","Bruder"] },
      { type: "translate", prompt: "Переклади:", uk: "Я купую лампу.", de: ["Ich kaufe eine Lampe."] },
      { type: "writeFree", prompt: "Напиши 3 речення з ein/eine/einen.", sample: "Ich habe einen Bruder. Sie kauft eine Tasche. Wir haben ein Auto.", explain: "Перевір артиклі за родом і відмінком." },
    ],
  },

  // 5 ===================================================================
  "artikel-singular": {
    lesson: {
      slug: "artikel-singular", level: "A1", category: CAT,
      titleDe: "Artikel im Singular", titleUk: "Артиклі в однині",
      goal: "Знати повний набір артиклів однини: означений, неозначений, заперечний.",
      explanation: [
        "У однині є 3 типи артиклів: <b>означений</b> (der/die/das), <b>неозначений</b> (ein/eine/ein) і <b>заперечний</b> (kein/keine/kein).",
        "<b>kein</b> — це «жоден, ніякий», заперечення речі: <i>Ich habe <b>kein</b> Auto.</i>",
        "У Akkusativ чоловічий рід додає <b>-en</b>: einen, keinen. Жіночий і середній — без змін.",
        "Усі вони виконують одну роботу: показують рід, число й відмінок іменника.",
      ],
      table: {
        headers: ["Рід", "der/ein/kein", "Nom.", "Akk."],
        rows: [
          ["m", "der/ein/kein", "der/ein/kein Mann", "den/einen/keinen Mann"],
          ["f", "die/eine/keine", "die/eine/keine Frau", "die/eine/keine Frau"],
          ["n", "das/ein/kein", "das/ein/kein Kind", "das/ein/kein Kind"],
        ],
      },
      examples: [
        { de: "Der Mann liest ein Buch.", uk: "Чоловік читає книгу." },
        { de: "Ich habe keinen Bruder.", uk: "У мене немає брата." },
        { de: "Eine Frau wartet vor der Tür.", uk: "Жінка чекає перед дверима." },
        { de: "Das Kind spielt mit einem Hund.", uk: "Дитина грається із собакою." },
        { de: "Sie hat kein Auto.", uk: "У неї немає автомобіля." },
        { de: "Ich kaufe einen Apfel.", uk: "Я купую яблуко." },
        { de: "Hier ist keine Lampe.", uk: "Тут немає лампи." },
        { de: "Ein Buch liegt auf dem Tisch.", uk: "Книга лежить на столі." },
      ],
      tip: "Усі 3 артиклі однини відмінюються <b>за однією логікою</b>: чоловічий рід додає <b>-en</b> в Akk.",
      mistakes: [
        { wrong: "Ich habe kein Bruder.", right: "Ich habe keinen Bruder." },
        { wrong: "Ich sehe ein Mann.", right: "Ich sehe einen Mann." },
        { wrong: "Sie hat eine Auto.", right: "Sie hat ein Auto." },
      ],
      exercises: {},
      prevSlug: "ein-eine",
      nextSlug: "artikel-plural",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати три типи артиклів однини",
        "розуміти спільну логіку відмінювання",
        "уживати kein замість nicht ein",
        "правильно ставити Akk. m → -en",
      ],
      ruleBox: {
        rule: "Однина: <b>der/ein/kein</b> (m) · <b>die/eine/keine</b> (f) · <b>das/ein/kein</b> (n). Akk. m: <b>den/einen/keinen</b>.",
      },
      ukrainianTips: [
        "У німецькій <b>не</b> «nicht ein», а <b>kein</b>: <i>Ich habe kein Auto.</i>",
        "Усі три «-типи» артиклів змінюються однаково за відмінками.",
        "<b>einen ≠ einem</b>! Akk. m = <b>einen</b>, Dat. m = einem (Dat. — у наступних уроках A2).",
      ],
      languageComparison: {
        commons: ["Заперечення є в обох мовах."],
        diffs: ["У німецькій заперечення іменника — окреме слово kein."],
        traps: ["«nicht ein Bruder» — помилка. Правильно: «kein Bruder»."],
      },
      summary: [
        "3 типи артиклів: <b>der/ein/kein</b>.",
        "Усі мають форми для m/f/n.",
        "Akk. m → -<b>en</b>.",
        "Заперечення іменника = <b>kein</b>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe ___ Auto.", options: ["nicht","kein","keine","keinen"], correct: 1, explain: "n → kein." },
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["kein","keine","keinen","keinem"], correct: 2 },
      { type: "mc", q: "Sie hat ___ Schwester.", options: ["kein","keine","keinen","keinem"], correct: 1 },
      { type: "mc", q: "Ich sehe ___ Mann.", options: ["ein","eine","einen","der"], correct: 2 },
      { type: "gap", q: "Wir haben ___ Lampe. (заперечення)", answer: "keine" },
      { type: "gap", q: "Ich kaufe ___ Apfel. (Akk. m)", answer: "einen" },
      { type: "gap", q: "Hier ist ___ Hund. (заперечення, m)", answer: "kein" },
      { type: "tf", q: "Заперечення іменника — kein, а не nicht ein.", correct: true },
      { type: "tf", q: "Akk. f → keinen.", correct: false, explain: "keine." },
      { type: "match", prompt: "Зістав форму й рід:", pairs: [
        { left: "keinen", right: "Akk. m" },
        { left: "keine", right: "f / Pl." },
        { left: "kein", right: "Nom./Akk. n" },
        { left: "einen", right: "Akk. m (неозн.)" },
      ]},
      { type: "multi", q: "Виділи правильні речення:", options: [
        "Ich habe kein Bruder.",
        "Ich habe keinen Bruder.",
        "Ich sehe ein Mann.",
        "Ich sehe einen Mann.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe nicht ein Auto.", correct: ["Ich habe kein Auto."] },
      { type: "order", prompt: "Склади:", words: ["habe","Ich","Bruder","keinen"], correct: ["Ich","habe","keinen","Bruder"] },
      { type: "translate", prompt: "Переклади:", uk: "У мене немає брата.", de: ["Ich habe keinen Bruder."] },
      { type: "writeFree", prompt: "Напиши 3 речення: 1 з der/die/das, 1 з ein/eine, 1 з kein/keine.", sample: "Der Hund spielt. Ich habe einen Bruder. Ich habe kein Auto.", explain: "Перевір артиклі." },
    ],
  },

  // 6 ===================================================================
  "artikel-plural": {
    lesson: {
      slug: "artikel-plural", level: "A1", category: CAT,
      titleDe: "Artikel im Plural", titleUk: "Артиклі в множині",
      goal: "Знати, що у множині лише два варіанти: <b>die</b> або <b>keine</b>, а неозначеного артикля немає.",
      explanation: [
        "У множині для всіх 3 родів — означений артикль <b>die</b>: <i>die Männer, die Frauen, die Kinder</i>.",
        "Неозначеного артикля у множині <b>немає</b>. Замість нього — просто іменник: <i>Ich kaufe Äpfel</i>, не <i>eine Äpfel</i>.",
        "Заперечення множини — <b>keine</b>: <i>Ich habe <b>keine</b> Bücher.</i>",
        "Дієслово завжди в <b>множині</b>: <i>Die Kinder spielen</i>, <i>Die Männer arbeiten</i>.",
      ],
      table: {
        headers: ["Тип", "Pl.", "Приклад"],
        rows: [
          ["означений", "die", "die Kinder"],
          ["неозначений", "—", "Kinder"],
          ["заперечний", "keine", "keine Kinder"],
          ["присвійний", "meine/deine…", "meine Kinder"],
        ],
      },
      examples: [
        { de: "Die Kinder spielen draußen.", uk: "Діти граються надворі." },
        { de: "Ich kaufe Äpfel.", uk: "Я купую яблука.", tag: "Pl. без артикля" },
        { de: "Ich habe keine Geschwister.", uk: "У мене немає братів і сестер." },
        { de: "Die Bücher sind teuer.", uk: "Книги дорогі." },
        { de: "Meine Eltern wohnen in Lwiw.", uk: "Мої батьки живуть у Львові." },
        { de: "Hier gibt es keine Tische.", uk: "Тут немає столів." },
        { de: "Die Frauen arbeiten zusammen.", uk: "Жінки працюють разом." },
        { de: "Sie hat zwei Hunde.", uk: "У неї два собаки." },
      ],
      tip: "Якщо хочеш сказати «якісь діти / якісь книги», у німецькій просто <b>не ставимо</b> артикль: <i>Da spielen Kinder.</i>",
      mistakes: [
        { wrong: "Eine Kinder spielen.", right: "Kinder spielen." },
        { wrong: "Das Kinder sind nett.", right: "Die Kinder sind nett." },
        { wrong: "Ich habe kein Bücher.", right: "Ich habe keine Bücher." },
      ],
      exercises: {},
      prevSlug: "artikel-singular",
      nextSlug: "negativartikel-kein",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "знати, що Pl. → die / keine",
        "не вживати «eine» в множині",
        "правильно заперечувати множину",
        "узгоджувати дієслово",
      ],
      ruleBox: {
        rule: "Pl: <b>die</b> · <b>keine</b> · <b>—</b> (неозн. немає).",
      },
      ukrainianTips: [
        "Українське «(якісь) діти граються» = німецьке <b>«Kinder spielen»</b>, без артикля.",
        "У множині <b>немає</b> ein/eine.",
        "Заперечення Pl. → <b>keine</b>: <i>keine Bücher, keine Eltern</i>.",
      ],
      languageComparison: {
        commons: ["Множина існує."],
        diffs: ["У німецькій pl. = die для всіх."],
        traps: ["«eine Kinder» — типова помилка."],
      },
      summary: [
        "Pl. означений → <b>die</b>.",
        "Pl. неозначений → <b>—</b>.",
        "Pl. заперечний → <b>keine</b>.",
        "Дієслово у множині.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Kinder spielen.", options: ["Der","Die","Das","Eine"], correct: 1 },
      { type: "mc", q: "Ich habe ___ Bücher.", options: ["kein","keine","keinen","keinem"], correct: 1 },
      { type: "mc", q: "Da spielen ___ Kinder.", options: ["eine","ein","—","der"], correct: 2 },
      { type: "mc", q: "___ Männer arbeiten.", options: ["Der","Die","Das","Ein"], correct: 1 },
      { type: "gap", q: "Wir haben ___ Geschwister. (запер., Pl.)", answer: "keine" },
      { type: "gap", q: "Ich kaufe ___ Äpfel. (Pl. без артикля)", answer: "—", hint: "Pl. неозначений = немає." },
      { type: "gap", q: "___ Frauen arbeiten viel.", answer: "Die" },
      { type: "tf", q: "У множині немає неозначеного артикля.", correct: true },
      { type: "tf", q: "Pl. заперечення — «kein».", correct: false, explain: "keine." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Pl. означ.", right: "die" },
        { left: "Pl. неозн.", right: "—" },
        { left: "Pl. запер.", right: "keine" },
        { left: "Sg. m запер.", right: "keinen" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Eine Kinder spielen.",
        "Kinder spielen.",
        "Die Kinder spielen.",
        "Das Kinder spielen.",
      ], correct: [1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Kinder spielen.", correct: ["Die Kinder spielen."] },
      { type: "order", prompt: "Склади:", words: ["keine","habe","Ich","Bücher"], correct: ["Ich","habe","keine","Bücher"] },
      { type: "translate", prompt: "Переклади:", uk: "У мене немає братів і сестер.", de: ["Ich habe keine Geschwister."] },
      { type: "writeFree", prompt: "Напиши 3 речення з множиною (із die, без артикля, з keine).", sample: "Die Kinder lernen. Wir kaufen Äpfel. Ich habe keine Geschwister.", explain: "Перевір артикль." },
    ],
  },

  // 7 ===================================================================
  "negativartikel-kein": {
    lesson: {
      slug: "negativartikel-kein", level: "A1", category: CAT,
      titleDe: "Negativartikel kein", titleUk: "Заперечний артикль kein",
      goal: "Уживати <b>kein</b> для заперечення іменника замість «nicht ein».",
      explanation: [
        "<b>kein</b> заперечує іменник, який без заперечення стояв би з <b>неозначеним</b> артиклем або <b>без</b> артикля.",
        "Форми як в неозначеного + <b>k</b>: <b>kein, keine, kein, keine (Pl.)</b>.",
        "У Akkusativ чоловічий рід → <b>keinen</b>.",
        "Якщо предмет конкретний (з означеним артиклем) — заперечуємо через <b>nicht</b>: <i>Das ist <b>nicht</b> der Mann.</i>",
      ],
      table: {
        headers: ["Рід", "Nom.", "Akk."],
        rows: [
          ["m", "kein Mann", "keinen Mann"],
          ["f", "keine Frau", "keine Frau"],
          ["n", "kein Kind", "kein Kind"],
          ["Pl.", "keine Kinder", "keine Kinder"],
        ],
      },
      examples: [
        { de: "Ich habe keinen Bruder.", uk: "У мене немає брата." },
        { de: "Sie hat keine Schwester.", uk: "У неї немає сестри." },
        { de: "Wir haben kein Auto.", uk: "У нас немає автомобіля." },
        { de: "Hier sind keine Kinder.", uk: "Тут немає дітей." },
        { de: "Ich trinke keinen Kaffee.", uk: "Я не п'ю кави." },
        { de: "Sie isst kein Fleisch.", uk: "Вона не їсть м'яса." },
        { de: "Das ist nicht der Lehrer.", uk: "Це не той учитель.", tag: "конкретне → nicht" },
        { de: "Ich habe keine Zeit.", uk: "У мене немає часу." },
      ],
      tip: "Правило вибору: <b>kein</b> якщо без заперечення був би <b>ein</b> або <b>нічого</b>. <b>nicht</b> якщо був би <b>der/die/das</b>.",
      mistakes: [
        { wrong: "Ich habe nicht ein Auto.", right: "Ich habe kein Auto." },
        { wrong: "Ich habe kein Bruder.", right: "Ich habe keinen Bruder." },
        { wrong: "Das ist kein der Lehrer.", right: "Das ist nicht der Lehrer." },
      ],
      exercises: {},
      prevSlug: "artikel-plural",
      nextSlug: "artikel-genus-2",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "вибирати kein замість nicht ein",
        "правильно відмінювати: kein/keine/keinen/keine",
        "розрізняти kein vs nicht",
        "будувати негативні речення зі знайомими дієсловами",
      ],
      ruleBox: {
        rule: "<b>kein</b> заперечує іменник з ein/нічого; <b>nicht</b> — з der/die/das.",
        examples: [
          { de: "Ich habe kein Auto.", uk: "У мене немає машини." },
          { de: "Das ist nicht mein Auto.", uk: "Це не моя машина." },
        ],
      },
      ukrainianTips: [
        "Українське «у мене немає машини» — у німецькій <b>kein Auto</b>, а не <b>nicht ein Auto</b>.",
        "Заперечення <b>конкретної</b> речі («ця машина не моя») — через <b>nicht</b>.",
        "Akk. m: <b>keinen</b>. Це найчастіше тест: <i>Ich habe <b>keinen</b> Bruder</i>.",
      ],
      languageComparison: {
        commons: ["Заперечення є в обох мовах."],
        diffs: ["У німецькій два способи: kein vs nicht."],
        traps: ["«Nicht ein» — не вживають, тільки «kein»."],
      },
      summary: [
        "Заперечення іменника → <b>kein</b>.",
        "Заперечення конкретної речі → <b>nicht</b>.",
        "Akk. m: <b>keinen</b>.",
        "Pl. → <b>keine</b>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe ___ Auto.", options: ["nicht","kein","keine","keinen"], correct: 1 },
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["kein","keine","keinen","keinem"], correct: 2 },
      { type: "mc", q: "Sie hat ___ Schwester.", options: ["kein","keine","keinen","keinem"], correct: 1 },
      { type: "mc", q: "Wir haben ___ Kinder.", options: ["kein","keine","keinen","keinem"], correct: 1 },
      { type: "gap", q: "Ich trinke ___ Kaffee. (Akk. m)", answer: "keinen" },
      { type: "gap", q: "Sie isst ___ Fleisch. (Akk. n)", answer: "kein" },
      { type: "gap", q: "Ich habe ___ Zeit. (Akk. f)", answer: "keine" },
      { type: "tf", q: "«nicht ein Auto» — правильно.", correct: false, explain: "kein Auto." },
      { type: "tf", q: "Конкретні речі заперечують через nicht.", correct: true },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Bruder (Akk.)", right: "keinen" },
        { left: "Schwester (Akk.)", right: "keine" },
        { left: "Auto (Akk.)", right: "kein" },
        { left: "Kinder (Pl.)", right: "keine" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich habe nicht ein Auto.",
        "Ich habe kein Auto.",
        "Das ist nicht der Lehrer.",
        "Das ist kein der Lehrer.",
      ], correct: [1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe kein Bruder.", correct: ["Ich habe keinen Bruder."] },
      { type: "order", prompt: "Склади:", words: ["Zeit","habe","Ich","keine"], correct: ["Ich","habe","keine","Zeit"] },
      { type: "translate", prompt: "Переклади:", uk: "Я не п'ю кави.", de: ["Ich trinke keinen Kaffee."] },
      { type: "writeFree", prompt: "Напиши 3 негативних речення з kein/keine/keinen.", sample: "Ich habe keinen Bruder. Sie hat keine Zeit. Wir haben kein Auto.", explain: "Перевір форму kein." },
    ],
  },

  // 8 ===================================================================
  "artikel-genus-2": {
    lesson: {
      slug: "artikel-genus-2", level: "A1", category: CAT,
      titleDe: "Artikel und Genus", titleUk: "Артикль і рід (повторення)",
      goal: "Закріпити: артикль ідентифікує рід; для нових слів використовуй підказки за закінченням.",
      explanation: [
        "Артикль і рід — нерозривно пов'язані: побачивши <b>der</b>, ти знаєш, що слово чоловічого роду.",
        "Працюй з підказками: <b>-ung/-heit/-keit/-tion → die</b>, <b>-chen/-lein → das</b>, <b>дні/місяці → der</b>.",
        "Зверни увагу на типові пастки: <b>das Mädchen</b>, <b>der Junge</b>, <b>die Person</b>.",
        "Будь-яке нове слово вчи карткою «артикль + слово + множина».",
      ],
      table: {
        headers: ["Підказка", "Рід", "Приклад"],
        rows: [
          ["-ung, -heit, -keit, -tion", "die", "die Wohnung"],
          ["-chen, -lein", "das", "das Mädchen"],
          ["дні / місяці / пори року", "der", "der Montag"],
          ["алкоголь, погода", "der", "der Wein, der Regen"],
          ["метали, кольори-іменники", "das", "das Gold"],
          ["числа", "die", "die Eins"],
        ],
      },
      examples: [
        { de: "Die Wohnung ist hell.", uk: "Квартира світла." },
        { de: "Das Mädchen liest.", uk: "Дівчинка читає." },
        { de: "Der Montag ist mein Lieblingstag.", uk: "Понеділок — мій улюблений день." },
        { de: "Der Wein ist gut.", uk: "Вино добре." },
        { de: "Das Gold glänzt.", uk: "Золото блищить." },
        { de: "Die Eins ist meine Lieblingszahl.", uk: "Одиниця — моє улюблене число." },
        { de: "Der Regen ist stark.", uk: "Дощ сильний." },
        { de: "Die Information ist neu.", uk: "Інформація нова." },
      ],
      tip: "Якщо знаєш рід → знаєш артикль → знаєш відмінок. Це <b>фундамент</b> всієї німецької.",
      mistakes: [
        { wrong: "Das Wohnung ist hell.", right: "Die Wohnung ist hell." },
        { wrong: "Die Mädchen liest.", right: "Das Mädchen liest." },
        { wrong: "Die Montag ist heute.", right: "Der Montag ist heute." },
      ],
      exercises: {},
      prevSlug: "negativartikel-kein",
      nextSlug: "artikel-nominativ",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "повторити правила-підказки роду",
        "натренувати швидку реакцію «слово → артикль»",
        "не помилятися у класичних пастках",
        "впізнавати рід нових слів",
      ],
      ruleBox: {
        rule: "Артикль = маркер роду. Підказки за закінченням покривають 70% слів; решту вчи окремо.",
      },
      ukrainianTips: [
        "Без артикля слово вивчене не повністю.",
        "Найкорисніші правила: <b>-ung → die</b>, <b>-chen → das</b>, <b>дні → der</b>.",
        "Слова-пастки: <b>das Mädchen, der See (озеро), die See (море)</b>.",
      ],
      languageComparison: {
        commons: ["Рід є в обох мовах."],
        diffs: ["Артикль робить рід «видимим»."],
        traps: ["Не покладайся на українську інтуїцію."],
      },
      summary: [
        "Артикль = рід.",
        "Підказки: -ung/-heit/-keit/-tion → die; -chen/-lein → das.",
        "Дні/місяці → der.",
        "Пастки треба знати.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Артикль до «Wohnung»:", options: ["der","die","das"], correct: 1 },
      { type: "mc", q: "Артикль до «Mädchen»:", options: ["der","die","das"], correct: 2 },
      { type: "mc", q: "Артикль до «Montag»:", options: ["der","die","das"], correct: 0 },
      { type: "mc", q: "Артикль до «Information»:", options: ["der","die","das"], correct: 1 },
      { type: "gap", q: "___ Wein ist gut.", answer: "Der" },
      { type: "gap", q: "___ Gold glänzt.", answer: "Das" },
      { type: "gap", q: "___ Möglichkeit ist interessant.", answer: "Die" },
      { type: "tf", q: "-ung завжди die.", correct: true },
      { type: "tf", q: "-chen завжди der.", correct: false, explain: "das." },
      { type: "match", prompt: "Зістав підказку й рід:", pairs: [
        { left: "-ung", right: "die" },
        { left: "-chen", right: "das" },
        { left: "день тижня", right: "der" },
        { left: "-tion", right: "die" },
      ]},
      { type: "multi", q: "Які слова — die?", options: ["Wohnung","Montag","Information","Mädchen","Freiheit"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Wohnung ist hell.", correct: ["Die Wohnung ist hell."] },
      { type: "order", prompt: "Склади:", words: ["Mädchen","liest","Das"], correct: ["Das","Mädchen","liest"] },
      { type: "translate", prompt: "Переклади:", uk: "Понеділок важкий.", de: ["Der Montag ist anstrengend.","Der Montag ist schwer."] },
      { type: "writeFree", prompt: "Напиши 3 речення з трьома різними родами.", sample: "Der Montag beginnt. Die Wohnung ist neu. Das Mädchen lacht.", explain: "Перевір артиклі." },
    ],
  },

  // 9 ===================================================================
  "artikel-nominativ": {
    lesson: {
      slug: "artikel-nominativ", level: "A1", category: CAT,
      titleDe: "Artikel im Nominativ", titleUk: "Артиклі в Nominativ",
      goal: "Знати повну таблицю артиклів у Nominativ і питання «Wer? Was?».",
      explanation: [
        "<b>Nominativ</b> — це відмінок <b>підмета</b>: відповідає на питання <b>Wer? Was?</b>",
        "Артиклі в Nominativ: <b>der/die/das</b> · <b>ein/eine/ein</b> · <b>kein/keine/kein</b>.",
        "Множина: <b>die/—/keine</b>.",
        "Це <b>словникова</b> форма іменника — саме її ти бачиш у словнику.",
      ],
      table: {
        headers: ["Рід / число", "der-група", "ein-група", "kein-група"],
        rows: [
          ["m", "der", "ein", "kein"],
          ["f", "die", "eine", "keine"],
          ["n", "das", "ein", "kein"],
          ["Pl.", "die", "—", "keine"],
        ],
      },
      examples: [
        { de: "Der Mann arbeitet.", uk: "Чоловік працює." },
        { de: "Die Frau heißt Anna.", uk: "Жінку звати Анна." },
        { de: "Das Kind schläft.", uk: "Дитина спить." },
        { de: "Ein Auto steht hier.", uk: "Тут стоїть автомобіль." },
        { de: "Eine Lampe ist im Zimmer.", uk: "У кімнаті лампа." },
        { de: "Kein Mann ist da.", uk: "Жодного чоловіка немає." },
        { de: "Die Kinder spielen.", uk: "Діти граються." },
        { de: "Keine Bücher liegen hier.", uk: "Тут немає книг." },
      ],
      tip: "Якщо можеш поставити питання <b>Wer? Was?</b> — це Nominativ. Це «хто/що робить дію».",
      mistakes: [
        { wrong: "Den Mann arbeitet.", right: "Der Mann arbeitet." },
        { wrong: "Einen Mann wartet.", right: "Ein Mann wartet." },
        { wrong: "Das Frau heißt Anna.", right: "Die Frau heißt Anna." },
      ],
      exercises: {},
      prevSlug: "artikel-genus-2",
      nextSlug: "artikel-akkusativ",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "знати таблицю Nominativ напам'ять",
        "впізнавати підмет за артиклем",
        "не плутати з Akkusativ",
        "питати Wer? / Was?",
      ],
      ruleBox: {
        rule: "Nominativ: <b>der/ein/kein · die/eine/keine · das/ein/kein · die/—/keine</b>. Питання: <b>Wer? Was?</b>",
      },
      ukrainianTips: [
        "Nominativ = називний відмінок (хто? що?). Як в українській.",
        "У Nominativ артикль <b>не змінюється</b> — це його «базова» форма.",
        "Якщо в реченні дієслово <b>sein/heißen/werden</b> — обидва іменники в Nominativ: <i>Anna ist Studentin.</i>",
      ],
      languageComparison: {
        commons: ["Називний є в обох мовах."],
        diffs: ["У німецькій рід «вмонтований» в артикль."],
        traps: ["Не плутати «der Mann» (Nom.) і «den Mann» (Akk.)."],
      },
      summary: [
        "Nom. = підмет.",
        "Питання: Wer? Was?",
        "Базова форма артикля.",
        "sein / heißen → Nom. + Nom.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Mann arbeitet. (озн.)", options: ["Der","Den","Das","Ein"], correct: 0 },
      { type: "mc", q: "___ Frau singt. (озн.)", options: ["Der","Die","Das","Eine"], correct: 1 },
      { type: "mc", q: "___ Kind spielt. (озн.)", options: ["Der","Die","Das","Ein"], correct: 2 },
      { type: "mc", q: "Питання Nominativ —", options: ["Wen?","Wem?","Wer?","Wessen?"], correct: 2 },
      { type: "gap", q: "___ Mann ist Lehrer. (неозн.)", answer: "Ein" },
      { type: "gap", q: "___ Frau wartet. (неозн.)", answer: "Eine" },
      { type: "gap", q: "___ Mann ist da. (запер., m)", answer: "Kein" },
      { type: "tf", q: "Nominativ — це підмет.", correct: true },
      { type: "tf", q: "У Nom. чоловічий рід — den.", correct: false, explain: "der; den — це Akk." },
      { type: "match", prompt: "Зістав форму й рід (Nom.):", pairs: [
        { left: "der", right: "m" },
        { left: "die", right: "f / Pl." },
        { left: "das", right: "n" },
        { left: "ein", right: "m / n" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Den Mann arbeitet.",
        "Der Mann arbeitet.",
        "Eine Mann wartet.",
        "Ein Mann wartet.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Den Mann ist Lehrer.", correct: ["Der Mann ist Lehrer."] },
      { type: "order", prompt: "Склади:", words: ["Frau","Die","singt"], correct: ["Die","Frau","singt"] },
      { type: "translate", prompt: "Переклади:", uk: "Дитина спить.", de: ["Das Kind schläft."] },
      { type: "writeFree", prompt: "Напиши 3 речення з підметом у Nominativ (різні роди).", sample: "Der Hund läuft. Die Lampe leuchtet. Das Kind lacht.", explain: "Підмет = Nom." },
    ],
  },

  // 10 ===================================================================
  "artikel-akkusativ": {
    lesson: {
      slug: "artikel-akkusativ", level: "A1", category: CAT,
      titleDe: "Artikel im Akkusativ", titleUk: "Артиклі в Akkusativ",
      goal: "Знати, що в Akkusativ змінюється лише <b>чоловічий рід</b>: der → den, ein → einen, kein → keinen.",
      explanation: [
        "<b>Akkusativ</b> — це <b>прямий додаток</b>: відповідає на <b>Wen? Was?</b>",
        "Зміна тільки в чоловічому роді: <b>der → den</b>, <b>ein → einen</b>, <b>kein → keinen</b>.",
        "Жіночий, середній і множина — <b>як у Nom.</b>: die/eine/keine · das/ein/kein · die/—/keine.",
        "Часті дієслова з Akkusativ: <b>haben, kaufen, sehen, lesen, essen, trinken, brauchen, lieben</b>.",
      ],
      table: {
        headers: ["Рід", "Nom.", "Akk."],
        rows: [
          ["m", "der/ein/kein", "den/einen/keinen"],
          ["f", "die/eine/keine", "die/eine/keine"],
          ["n", "das/ein/kein", "das/ein/kein"],
          ["Pl.", "die/—/keine", "die/—/keine"],
        ],
      },
      examples: [
        { de: "Ich sehe den Mann.", uk: "Я бачу чоловіка.", tag: "Akk. m → den" },
        { de: "Ich habe einen Bruder.", uk: "У мене є брат." },
        { de: "Ich kaufe eine Tasche.", uk: "Я купую сумку." },
        { de: "Wir lesen das Buch.", uk: "Ми читаємо книгу." },
        { de: "Sie trinkt keinen Kaffee.", uk: "Вона не п'є кави." },
        { de: "Er liebt seine Frau.", uk: "Він любить свою дружину." },
        { de: "Ich brauche die Bücher.", uk: "Мені потрібні книги." },
        { de: "Wir essen einen Apfel.", uk: "Ми їмо яблуко." },
      ],
      tip: "Запам'ятай 4 ключові форми Akk. m: <b>den, einen, keinen, meinen</b>. Усі додають <b>-en</b>.",
      mistakes: [
        { wrong: "Ich sehe der Mann.", right: "Ich sehe den Mann." },
        { wrong: "Ich habe ein Bruder.", right: "Ich habe einen Bruder." },
        { wrong: "Wir trinken keinen Milch.", right: "Wir trinken keine Milch.", },
      ],
      exercises: {},
      prevSlug: "artikel-nominativ",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "розпізнавати Akk. за питанням Wen? Was?",
        "автоматично казати den/einen/keinen у Akk. m",
        "не плутати з Nom.",
        "вживати з частими дієсловами",
      ],
      ruleBox: {
        rule: "Akk: <b>den/einen/keinen · die/eine/keine · das/ein/kein · die/—/keine</b>. Питання: <b>Wen? Was?</b>",
      },
      ukrainianTips: [
        "Akk. ≈ український знахідний відмінок («бачу <i>кого/що?</i>»).",
        "Зміна <b>тільки</b> в m: інші роди в Akk. однакові з Nom.",
        "Заучи фразу: «<i>Ich habe <b>einen</b> Bruder</i>».",
      ],
      languageComparison: {
        commons: ["Прямий додаток є в обох мовах."],
        diffs: ["У німецькій тільки m змінює форму."],
        traps: ["«der Mann» у позиції додатка → den."],
      },
      summary: [
        "Akk. = додаток.",
        "Питання: Wen? Was?",
        "Тільки m: -<b>en</b>.",
        "f/n/Pl. = як у Nom.",
        "Дієслова: haben, kaufen, sehen, lesen, essen, brauchen.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich sehe ___ Mann.", options: ["der","den","ein","einen"], correct: 1 },
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["ein","eine","einen","der"], correct: 2 },
      { type: "mc", q: "Sie kauft ___ Tasche.", options: ["ein","eine","einen","der"], correct: 1 },
      { type: "mc", q: "Wir lesen ___ Buch.", options: ["der","den","das","ein"], correct: 2 },
      { type: "gap", q: "Ich brauche ___ Lampe. (Akk. f)", answer: "eine" },
      { type: "gap", q: "Er trinkt ___ Kaffee. (запер., Akk. m)", answer: "keinen" },
      { type: "gap", q: "Питання Akk. — ___ ? / Was?", answer: "Wen" },
      { type: "tf", q: "У Akk. жіночий рід — den.", correct: false, explain: "die." },
      { type: "tf", q: "У Akk. m: der → den.", correct: true },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "der → ?", right: "den" },
        { left: "ein → ?", right: "einen" },
        { left: "kein → ? (m)", right: "keinen" },
        { left: "die → ?", right: "die" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich sehe der Mann.",
        "Ich sehe den Mann.",
        "Ich habe einen Bruder.",
        "Ich habe ein Bruder.",
      ], correct: [1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich kaufe ein Tasche.", correct: ["Ich kaufe eine Tasche."] },
      { type: "order", prompt: "Склади:", words: ["sehe","den","Ich","Mann"], correct: ["Ich","sehe","den","Mann"] },
      { type: "translate", prompt: "Переклади:", uk: "Я купую яблуко.", de: ["Ich kaufe einen Apfel."] },
      { type: "writeFree", prompt: "Напиши 3 речення з Akkusativ (різні роди).", sample: "Ich sehe den Mann. Ich kaufe eine Tasche. Wir lesen das Buch.", explain: "Зміна тільки в m." },
    ],
  },
};
