// A1 · Відмінки — 10 повних уроків (Nominativ 4 + Akkusativ 6).
import type { A1Map } from "./_helpers";

const CAT = "Відмінки";

export const faelleA1: A1Map = {
  // ============ NOMINATIV ============
  "was-ist-nominativ": {
    lesson: {
      slug: "was-ist-nominativ", level: "A1", category: CAT,
      titleDe: "Was ist der Nominativ?",
      titleUk: "Що таке Nominativ",
      goal: "Зрозуміти, що Nominativ — це відмінок підмета й «словникова форма» іменника.",
      explanation: [
        "<b>Nominativ</b> — це відмінок <b>підмета</b> у реченні: хто або що виконує дію.",
        "Це <b>базова форма</b> іменника, яку показує словник: <i>der Tisch, die Lampe, das Buch</i>.",
        "Питання: <b>Wer? (Хто?)</b> для людей, <b>Was? (Що?)</b> для речей.",
        "Після дієслів <b>sein, heißen, werden, bleiben</b> другий іменник теж стоїть у <b>Nominativ</b>: <i>Anna ist Studentin.</i>",
      ],
      table: {
        headers: ["Рід / число", "Артикль", "Приклад"],
        rows: [
          ["m", "der/ein/kein", "Der Mann arbeitet."],
          ["f", "die/eine/keine", "Die Frau lacht."],
          ["n", "das/ein/kein", "Das Kind spielt."],
          ["Pl.", "die/—/keine", "Die Kinder spielen."],
        ],
      },
      examples: [
        { de: "Der Mann arbeitet.", uk: "Чоловік працює.", tag: "Wer arbeitet?" },
        { de: "Die Lampe ist neu.", uk: "Лампа нова.", tag: "Was ist neu?" },
        { de: "Das Kind schläft.", uk: "Дитина спить." },
        { de: "Die Kinder spielen.", uk: "Діти граються." },
        { de: "Anna ist Studentin.", uk: "Анна — студентка.", tag: "sein → Nom + Nom" },
        { de: "Er heißt Peter.", uk: "Його звати Петер." },
        { de: "Mein Bruder ist Lehrer.", uk: "Мій брат — учитель." },
        { de: "Wir sind Freunde.", uk: "Ми друзі." },
      ],
      tip: "Щоб знайти підмет, постав питання <b>Wer / Was + дієслово?</b> Відповідь у Nom.",
      mistakes: [
        { wrong: "Den Mann arbeitet.", right: "Der Mann arbeitet." },
        { wrong: "Anna ist eine Studentin.", right: "Anna ist Studentin." },
        { wrong: "Einen Tisch steht hier.", right: "Ein Tisch steht hier." },
      ],
      exercises: {},
      nextSlug: "wer-oder-was",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати, що Nom. = підмет",
        "ставити питання Wer/Was",
        "впізнавати Nom. за артиклем",
        "не плутати з Akk.",
      ],
      ruleBox: {
        rule: "Nom. = <b>підмет</b>. Питання <b>Wer? Was?</b> Артиклі: der/ein/kein · die/eine/keine · das/ein/kein · die/—/keine.",
      },
      ukrainianTips: [
        "Nominativ = називний відмінок — як в українській.",
        "Після sein/heißen/werden обидва іменники в Nom.: <i>Er ist Student.</i>",
        "Підмет — це той, хто <b>виконує дію</b>.",
      ],
      languageComparison: {
        commons: ["Називний є."],
        diffs: ["У німецькій рід «вмонтований» в артикль."],
        traps: ["den Mann ≠ Nom."],
      },
      summary: [
        "Nom. = підмет.",
        "Wer? / Was?",
        "Базова словникова форма.",
        "Sein/heißen → Nom. + Nom.",
      ],
    },
    exercises15: [
      { type: "mc", q: "У реченні «Der Mann arbeitet» підмет — це:", options: ["der Mann","arbeitet","—","Mann (без артикля)"], correct: 0 },
      { type: "mc", q: "Питання Nom. —", options: ["Wen?","Was?","Wem?","Wessen?"], correct: 1, explain: "Wer? / Was?" },
      { type: "mc", q: "___ Frau heißt Anna.", options: ["Der","Die","Das","Den"], correct: 1 },
      { type: "mc", q: "Anna ist ___ .", options: ["eine Studentin","Studentin","der Studentin","den Studentin"], correct: 1 },
      { type: "gap", q: "___ ist das? — Das ist Anna.", answer: "Wer" },
      { type: "gap", q: "___ ist das? — Das ist ein Buch.", answer: "Was" },
      { type: "gap", q: "___ Kind spielt im Garten. (озн., n)", answer: "Das" },
      { type: "tf", q: "Підмет завжди в Nom.", correct: true },
      { type: "tf", q: "Після sein другий іменник в Akk.", correct: false, explain: "У Nom." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "der", right: "Nom. m" },
        { left: "die", right: "Nom. f / Pl." },
        { left: "das", right: "Nom. n" },
        { left: "Wer?", right: "Nom. люди" },
      ]},
      { type: "multi", q: "Які речення в Nom.?", options: [
        "Der Mann arbeitet.",
        "Ich sehe den Mann.",
        "Die Frau lacht.",
        "Ich liebe die Frau.",
      ], correct: [0,2], explain: "У 2 і 4 — це Akk." },
      { type: "correct", prompt: "Виправ:", wrong: "Den Mann arbeitet.", correct: ["Der Mann arbeitet."] },
      { type: "order", prompt: "Склади:", words: ["arbeitet","Mann","Der"], correct: ["Der","Mann","arbeitet"] },
      { type: "translate", prompt: "Переклади:", uk: "Жінка — лікарка.", de: ["Die Frau ist Ärztin."] },
      { type: "writeFree", prompt: "Напиши 3 речення з підметами у Nom. (різні роди).", sample: "Der Hund läuft. Die Lampe leuchtet. Das Kind lacht.", explain: "Підмет у Nom." },
    ],
  },

  // 2 ===================================================================
  "wer-oder-was": {
    lesson: {
      slug: "wer-oder-was", level: "A1", category: CAT,
      titleDe: "Wer oder was?", titleUk: "Питання Nominativ: Wer? або Was?",
      goal: "Автоматично вибирати правильне питання за категорією іменника.",
      explanation: [
        "<b>Wer?</b> = «Хто?» — для людей і тварин (тих, на кого можемо сказати «хто»).",
        "<b>Was?</b> = «Що?» — для речей, абстрактних понять, явищ природи.",
        "Обидва питальних слова показують, що відповідь буде в <b>Nominativ</b>.",
        "Якщо в реченні <b>немає підмета</b>, який можеш знайти питанням Wer/Was — речення «зламане».",
      ],
      table: {
        headers: ["Питання", "Об'єкт", "Приклад"],
        rows: [
          ["Wer?", "людина", "Wer arbeitet? — Der Mann."],
          ["Wer?", "тварина", "Wer bellt? — Der Hund."],
          ["Was?", "річ", "Was steht hier? — Ein Tisch."],
          ["Was?", "явище", "Was passiert? — Es regnet."],
          ["Was?", "абстракт.", "Was ist wichtig? — Die Liebe."],
        ],
      },
      examples: [
        { de: "Wer ist das? — Das ist Anna.", uk: "Хто це? — Це Анна." },
        { de: "Was ist das? — Das ist ein Buch.", uk: "Що це? — Це книга." },
        { de: "Wer kommt heute?", uk: "Хто приходить сьогодні?" },
        { de: "Was steht auf dem Tisch?", uk: "Що стоїть на столі?" },
        { de: "Wer hat Hunger?", uk: "Хто голодний?" },
        { de: "Was ist neu?", uk: "Що нового?" },
        { de: "Wer arbeitet im Büro?", uk: "Хто працює в офісі?" },
        { de: "Was passiert hier?", uk: "Що тут відбувається?" },
      ],
      tip: "Перевір себе: <b>«Хто/Що + дієслово?»</b> → відповідь у Nom. Це <b>підмет</b>.",
      mistakes: [
        { wrong: "Was ist das? — Das ist Anna.", right: "Wer ist das? — Das ist Anna." },
        { wrong: "Wer ist das? — Das ist ein Buch.", right: "Was ist das? — Das ist ein Buch." },
        { wrong: "Wen kommt heute?", right: "Wer kommt heute?" },
      ],
      exercises: {},
      prevSlug: "was-ist-nominativ",
      nextSlug: "artikel-im-nominativ",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "вибирати Wer/Was за категорією",
        "розуміти, що обидва — Nom.",
        "не плутати з Wen (Akk.)",
        "будувати прості запитання",
      ],
      ruleBox: {
        rule: "<b>Wer?</b> — люди/тварини. <b>Was?</b> — речі/явища.",
      },
      ukrainianTips: [
        "Українському «Хто?» завжди = <b>Wer</b>, «Що?» = <b>Was</b>.",
        "<b>Wen?</b> — це теж «кого», але вже Akk. — не плутай!",
        "Тварин зазвичай питають <b>Wer</b>: <i>Wer bellt? — Der Hund.</i>",
      ],
      languageComparison: {
        commons: ["Хто/що в обох мовах."],
        diffs: ["У німецькій є ще Wen для Akk."],
        traps: ["Wer ↔ Wen."],
      },
      summary: [
        "Wer — Nom. люди/тварини.",
        "Was — Nom. речі/явища.",
        "Wen — Akk. люди (інший урок).",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ ist das? — Das ist mein Vater.", options: ["Wer","Was","Wen","Wie"], correct: 0 },
      { type: "mc", q: "___ ist das? — Das ist eine Lampe.", options: ["Wer","Was","Wen","Wo"], correct: 1 },
      { type: "mc", q: "___ kommt heute?", options: ["Wer","Was","Wen","Wann"], correct: 0 },
      { type: "mc", q: "___ ist neu?", options: ["Wer","Was","Wen","Wo"], correct: 1 },
      { type: "gap", q: "___ ist Lehrer? — Mein Vater.", answer: "Wer" },
      { type: "gap", q: "___ steht hier? — Ein Tisch.", answer: "Was" },
      { type: "gap", q: "___ bellt? — Der Hund.", answer: "Wer" },
      { type: "tf", q: "Wer і Was — обидва Nom.", correct: true },
      { type: "tf", q: "Was використовують для людей.", correct: false, explain: "Для речей." },
      { type: "match", prompt: "Зістав питання й відповідь:", pairs: [
        { left: "Wer kommt?", right: "Anna." },
        { left: "Was ist das?", right: "Ein Buch." },
        { left: "Wer hat Hunger?", right: "Mein Bruder." },
        { left: "Was steht hier?", right: "Ein Tisch." },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Was ist Anna?",
        "Wer ist Anna?",
        "Wer ist das? — Ein Buch.",
        "Was ist das? — Ein Buch.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Was ist das? — Das ist Anna.", correct: ["Wer ist das? — Das ist Anna."] },
      { type: "order", prompt: "Склади:", words: ["Wer","das","ist"], correct: ["Wer","ist","das"] },
      { type: "translate", prompt: "Переклади:", uk: "Хто це? Що це?", de: ["Wer ist das? Was ist das?"] },
      { type: "writeFree", prompt: "Напиши 3 запитання з Wer/Was.", sample: "Wer ist dein Lehrer? Was steht hier? Wer kommt morgen?", explain: "Wer для людей, Was для речей." },
    ],
  },

  // 3 ===================================================================
  "artikel-im-nominativ": {
    lesson: {
      slug: "artikel-im-nominativ", level: "A1", category: CAT,
      titleDe: "Artikel im Nominativ", titleUk: "Артиклі в Nominativ",
      goal: "Запам'ятати таблицю артиклів Nominativ для всіх 3 родів і множини.",
      explanation: [
        "Артиклі Nom.: означені <b>der/die/das/die</b>, неозначені <b>ein/eine/ein/—</b>, заперечні <b>kein/keine/kein/keine</b>.",
        "Це найпростіша таблиця німецької: <b>артикль не змінюється</b>, бо ми ще у «словниковій формі».",
        "Стартуй з 4 рядків: <i>der Mann · die Frau · das Kind · die Kinder</i>.",
        "Pl. для означеного — <b>die</b>; для неозначеного — <b>немає</b>; для заперечного — <b>keine</b>.",
      ],
      table: {
        headers: ["", "m", "f", "n", "Pl."],
        rows: [
          ["означ.", "der", "die", "das", "die"],
          ["неозн.", "ein", "eine", "ein", "—"],
          ["запер.", "kein", "keine", "kein", "keine"],
        ],
      },
      examples: [
        { de: "Der Mann arbeitet.", uk: "Чоловік працює." },
        { de: "Die Frau singt.", uk: "Жінка співає." },
        { de: "Das Kind lacht.", uk: "Дитина сміється." },
        { de: "Die Kinder lernen.", uk: "Діти вчаться." },
        { de: "Ein Hund läuft.", uk: "(Якийсь) пес біжить." },
        { de: "Eine Lampe steht hier.", uk: "Лампа стоїть тут." },
        { de: "Kein Mann ist da.", uk: "Жодного чоловіка немає." },
        { de: "Keine Kinder sind hier.", uk: "Дітей тут немає." },
      ],
      tip: "Запам'ятай 4-рядкову «пісню»: <b>der – die – das – die</b>. Ein-група і kein-група — за тією ж логікою.",
      mistakes: [
        { wrong: "Den Mann arbeitet.", right: "Der Mann arbeitet." },
        { wrong: "Eine Mann ist da.", right: "Ein Mann ist da." },
        { wrong: "Das Kinder lachen.", right: "Die Kinder lachen." },
      ],
      exercises: {},
      prevSlug: "wer-oder-was",
      nextSlug: "personalpron-im-nominativ",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "знати 3 ряди артиклів Nom.",
        "автоматично вибирати der/die/das",
        "розуміти Pl. як «die / — / keine»",
        "не вставляти Akk. (den) у Nom.",
      ],
      ruleBox: {
        rule: "Nom: der/die/das/die · ein/eine/ein/— · kein/keine/kein/keine.",
      },
      ukrainianTips: [
        "Це <b>основа</b>. Усі інші відмінки відштовхуються від Nom.",
        "Pl. для неозначеного — <b>немає</b>. Просто іменник без артикля.",
        "Якщо плутаєш — спочатку перевір <b>рід</b> слова.",
      ],
      languageComparison: {
        commons: ["Називний є."],
        diffs: ["Артикль обов'язковий."],
        traps: ["Pl. без артикля для неозначеного."],
      },
      summary: [
        "der/die/das/die.",
        "ein/eine/ein/—.",
        "kein/keine/kein/keine.",
        "Nom. = підмет.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Mann ist Lehrer. (озн.)", options: ["Der","Die","Das","Den"], correct: 0 },
      { type: "mc", q: "___ Frau lacht. (озн.)", options: ["Der","Die","Das","Den"], correct: 1 },
      { type: "mc", q: "___ Kind spielt. (озн.)", options: ["Der","Die","Das","Den"], correct: 2 },
      { type: "mc", q: "___ Kinder lernen. (озн.)", options: ["Der","Die","Das","Den"], correct: 1 },
      { type: "gap", q: "___ Hund läuft. (неозн., m)", answer: "Ein" },
      { type: "gap", q: "___ Lampe steht hier. (неозн., f)", answer: "Eine" },
      { type: "gap", q: "___ Mann ist da. (запер., m)", answer: "Kein" },
      { type: "tf", q: "Pl. для означеного — die.", correct: true },
      { type: "tf", q: "Pl. для неозначеного — eine.", correct: false, explain: "Немає." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "der", right: "m означ." },
        { left: "eine", right: "f неозн." },
        { left: "kein", right: "m/n запер." },
        { left: "keine", right: "f / Pl. запер." },
      ]},
      { type: "multi", q: "Які речення в правильному Nom.?", options: [
        "Den Mann arbeitet.",
        "Der Mann arbeitet.",
        "Eine Mann wartet.",
        "Ein Mann wartet.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Kinder lachen.", correct: ["Die Kinder lachen."] },
      { type: "order", prompt: "Склади:", words: ["Mann","Der","arbeitet","viel"], correct: ["Der","Mann","arbeitet","viel"] },
      { type: "translate", prompt: "Переклади:", uk: "Жоден чоловік не чекає.", de: ["Kein Mann wartet."] },
      { type: "writeFree", prompt: "Напиши 4 речення з різними артиклями Nom.", sample: "Der Mann arbeitet. Eine Frau wartet. Das Kind schläft. Keine Kinder spielen.", explain: "Перевір артиклі за родом." },
    ],
  },

  // 4 ===================================================================
  "personalpron-im-nominativ": {
    lesson: {
      slug: "personalpron-im-nominativ", level: "A1", category: CAT,
      titleDe: "Personalpronomen im Nominativ",
      titleUk: "Особові займенники в Nominativ (для відмінків)",
      goal: "Розглянути особові займенники саме <b>як підмет</b> у Nom., щоб порівняти з Akk. далі.",
      explanation: [
        "Підметом може бути не лише іменник, а й <b>особовий займенник</b>: <i>ich, du, er, sie, es, wir, ihr, sie, Sie</i>.",
        "Усі вони стоять у <b>Nominativ</b> — це найбазовіша форма.",
        "У наступних уроках побачимо, як вони змінюються в Akkusativ (mich, dich, ihn…).",
        "Узгодження з дієсловом: ich -e · du -st · er/sie/es -t · wir -en · ihr -t · sie/Sie -en.",
      ],
      table: {
        headers: ["Nominativ", "значення", "приклад"],
        rows: [
          ["ich", "я", "Ich bin Anna."],
          ["du", "ти", "Du bist nett."],
          ["er", "він", "Er kommt heute."],
          ["sie", "вона", "Sie heißt Maria."],
          ["es", "воно", "Es ist neu."],
          ["wir", "ми", "Wir lernen Deutsch."],
          ["ihr", "ви (мн.)", "Ihr seid jung."],
          ["sie / Sie", "вони / Ви ввічл.", "Sie kommen."],
        ],
      },
      examples: [
        { de: "Ich heiße Anna.", uk: "Мене звати Анна." },
        { de: "Du bist sehr nett.", uk: "Ти дуже милий." },
        { de: "Er arbeitet in Berlin.", uk: "Він працює в Берліні." },
        { de: "Sie kommt aus der Ukraine.", uk: "Вона з України." },
        { de: "Wir wohnen in Wien.", uk: "Ми живемо у Відні." },
        { de: "Ihr seid Studenten.", uk: "Ви студенти." },
        { de: "Sie sind Lehrer.", uk: "Вони вчителі." },
        { de: "Wie heißen Sie?", uk: "Як вас звати? (ввічл.)" },
      ],
      tip: "Усі ці 7 займенників — <b>Nom.</b>! У реченні вони відповідають на <b>Wer?</b>",
      mistakes: [
        { wrong: "Mich bin Anna.", right: "Ich bin Anna." },
        { wrong: "Ihn arbeitet hier.", right: "Er arbeitet hier." },
        { wrong: "Dich bist nett.", right: "Du bist nett." },
      ],
      exercises: {},
      prevSlug: "artikel-im-nominativ",
      nextSlug: "was-ist-akkusativ",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "знати, що особові — у Nom. як підмет",
        "узгоджувати дієслово",
        "готувати ґрунт для Akk.",
        "не змішувати Nom. і Akk. форми",
      ],
      ruleBox: {
        rule: "<b>ich, du, er, sie, es, wir, ihr, sie, Sie</b> — особові у Nom. Підмет → Nom.",
      },
      ukrainianTips: [
        "Українські «я, ти, він, вона, ми, ви, вони» = німецькі ich/du/er/sie/wir/ihr/sie.",
        "У Akk. вони <b>зміняться</b>: mich, dich, ihn…",
        "<b>es</b> часто перекладається українським «воно» або взагалі не перекладається (<i>Es regnet</i>).",
      ],
      languageComparison: {
        commons: ["Особові займенники універсальні."],
        diffs: ["У німецькій ich завжди з малої."],
        traps: ["ich ↔ mich."],
      },
      summary: [
        "Nom. займенники = підмет.",
        "ich/du/er/sie/es/wir/ihr/sie/Sie.",
        "Узгодити з дієсловом.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ heiße Anna.", options: ["Ich","Mich","Mir","Mein"], correct: 0 },
      { type: "mc", q: "___ bist nett.", options: ["Du","Dich","Dir","Dein"], correct: 0 },
      { type: "mc", q: "___ arbeitet hier. (про чоловіка)", options: ["Er","Ihn","Ihm","Sein"], correct: 0 },
      { type: "mc", q: "___ heißt Maria.", options: ["Er","Sie","Es","Ihr"], correct: 1 },
      { type: "gap", q: "___ regnet heute. (безособове)", answer: "Es" },
      { type: "gap", q: "___ wohnen in Wien. (ми)", answer: "Wir" },
      { type: "gap", q: "___ seid jung. (ви — мн.)", answer: "Ihr" },
      { type: "tf", q: "У Nom. — ich, du, er, sie, es…", correct: true },
      { type: "tf", q: "«mich» — це Nom. для ich.", correct: false, explain: "Це Akk." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "я", right: "ich" },
        { left: "ти", right: "du" },
        { left: "він", right: "er" },
        { left: "ми", right: "wir" },
      ]},
      { type: "multi", q: "Які займенники — Nom.?", options: ["ich","mich","du","dich","wir","uns"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Mich bin Anna.", correct: ["Ich bin Anna."] },
      { type: "order", prompt: "Склади:", words: ["Wien","wohnen","Wir","in"], correct: ["Wir","wohnen","in","Wien"] },
      { type: "translate", prompt: "Переклади:", uk: "Ви (ввічл.) розмовляєте німецькою?", de: ["Sprechen Sie Deutsch?"] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними особовими в Nom.", sample: "Ich lerne Deutsch. Du bist nett. Wir wohnen in Lwiw.", explain: "Підмет = Nom." },
    ],
  },

  // ============ AKKUSATIV ============
  // 5 ===================================================================
  "was-ist-akkusativ": {
    lesson: {
      slug: "was-ist-akkusativ", level: "A1", category: CAT,
      titleDe: "Was ist der Akkusativ?", titleUk: "Що таке Akkusativ",
      goal: "Зрозуміти Akkusativ як відмінок <b>прямого додатка</b> і питання Wen/Was.",
      explanation: [
        "<b>Akkusativ</b> — відмінок <b>прямого додатка</b>: на кого/що спрямована дія.",
        "Питання: <b>Wen?</b> (Кого?) для людей, <b>Was?</b> (Що?) для речей.",
        "Зміни у формі — <b>тільки в чоловічому роді</b>: der → den, ein → einen, kein → keinen.",
        "Жіночий, середній і множина в Akk. <b>не змінюються</b> порівняно з Nom.",
        "Дієслова з Akk.: <b>haben, kaufen, sehen, lesen, essen, trinken, brauchen, lieben, kennen</b>.",
      ],
      table: {
        headers: ["Рід", "Nom.", "Akk."],
        rows: [
          ["m", "der Mann", "den Mann"],
          ["f", "die Frau", "die Frau"],
          ["n", "das Kind", "das Kind"],
          ["Pl.", "die Kinder", "die Kinder"],
        ],
      },
      examples: [
        { de: "Ich sehe den Mann.", uk: "Я бачу чоловіка." },
        { de: "Wir kennen die Frau.", uk: "Ми знаємо жінку." },
        { de: "Sie liebt das Kind.", uk: "Вона любить дитину." },
        { de: "Ich kaufe einen Apfel.", uk: "Я купую яблуко." },
        { de: "Er trinkt einen Kaffee.", uk: "Він п'є каву." },
        { de: "Wir lesen ein Buch.", uk: "Ми читаємо книгу." },
        { de: "Hast du Zeit?", uk: "У тебе є час?" },
        { de: "Ich brauche eine Lampe.", uk: "Мені потрібна лампа." },
      ],
      tip: "Знайди дієслово й постав <b>Wen / Was + дієслово?</b> Відповідь — Akk.",
      mistakes: [
        { wrong: "Ich sehe der Mann.", right: "Ich sehe den Mann." },
        { wrong: "Ich habe ein Bruder.", right: "Ich habe einen Bruder." },
        { wrong: "Sie liebt die Kind.", right: "Sie liebt das Kind." },
      ],
      exercises: {},
      prevSlug: "personalpron-im-nominativ",
      nextSlug: "wen-oder-was",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати, що Akk. — це додаток",
        "питати Wen? Was?",
        "автоматично робити Akk. m → den/einen/keinen",
        "уживати з частими дієсловами",
      ],
      ruleBox: {
        rule: "Akk. = <b>прямий додаток</b>. <b>Wen? Was?</b> Зміна тільки в <b>m</b>: der→den, ein→einen, kein→keinen.",
      },
      ukrainianTips: [
        "Akk. ≈ український знахідний.",
        "Лише m змінюється — інші роди такі ж, як Nom.",
        "Дієслова haben, sehen, lesen, lieben → завжди Akk.",
      ],
      languageComparison: {
        commons: ["Прямий додаток універсальний."],
        diffs: ["У німецькій змінюється лише m."],
        traps: ["«ein Bruder» в Akk. → einen."],
      },
      summary: [
        "Akk. = додаток.",
        "Wen? / Was?",
        "Зміна тільки в m: -en.",
        "Дієслова: haben, sehen, lesen, lieben, brauchen.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich sehe ___ Mann.", options: ["der","den","ein","einer"], correct: 1 },
      { type: "mc", q: "Питання Akk. —", options: ["Wer?","Wen?","Wem?","Wessen?"], correct: 1, explain: "Wen? / Was?" },
      { type: "mc", q: "Wir lesen ___ Buch.", options: ["der","den","das","ein"], correct: 2 },
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["ein","eine","einen","einem"], correct: 2 },
      { type: "gap", q: "Sie liebt ___ Kind. (Akk. n)", answer: "das" },
      { type: "gap", q: "Er kauft ___ Apfel. (Akk. m, неозн.)", answer: "einen" },
      { type: "gap", q: "Wir kennen ___ Frau. (Akk. f)", answer: "die" },
      { type: "tf", q: "У Akk. f → die.", correct: true },
      { type: "tf", q: "У Akk. m → der.", correct: false, explain: "den." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Nom. der", right: "Akk. den" },
        { left: "Nom. die", right: "Akk. die" },
        { left: "Nom. das", right: "Akk. das" },
        { left: "Nom. ein (m)", right: "Akk. einen" },
      ]},
      { type: "multi", q: "Які дієслова потребують Akk.?", options: ["haben","sein","kaufen","helfen","sehen"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich sehe der Mann.", correct: ["Ich sehe den Mann."] },
      { type: "order", prompt: "Склади:", words: ["sehe","Mann","Ich","den"], correct: ["Ich","sehe","den","Mann"] },
      { type: "translate", prompt: "Переклади:", uk: "Я читаю книгу.", de: ["Ich lese das Buch.","Ich lese ein Buch."] },
      { type: "writeFree", prompt: "Напиши 3 речення з Akk. (різні роди).", sample: "Ich sehe den Mann. Ich kaufe eine Tasche. Wir lesen das Buch.", explain: "Зміна тільки в m." },
    ],
  },

  // 6 ===================================================================
  "wen-oder-was": {
    lesson: {
      slug: "wen-oder-was", level: "A1", category: CAT,
      titleDe: "Wen oder was?", titleUk: "Питання Akkusativ: Wen? Was?",
      goal: "Вибирати між Wen (Akk. для людей) і Was (Akk. для речей) і будувати запитання.",
      explanation: [
        "<b>Wen?</b> — «Кого?» — для людей у Akk.: <i>Wen siehst du?</i>",
        "<b>Was?</b> — «Що?» — для речей у Akk.: <i>Was kaufst du?</i>",
        "Відмінність від Nom.: у Nom. — Wer/Was (підмет), у Akk. — Wen/Was (додаток).",
        "У відповіді треба ставити форму Akk.: <i>— Den Mann. / — Ein Buch.</i>",
      ],
      table: {
        headers: ["Питання", "Категорія", "Приклад"],
        rows: [
          ["Wer?", "Nom. люди", "Wer kommt?"],
          ["Wen?", "Akk. люди", "Wen siehst du?"],
          ["Was?", "Nom. або Akk. речі", "Was ist das? / Was kaufst du?"],
        ],
      },
      examples: [
        { de: "Wen siehst du? — Den Mann.", uk: "Кого ти бачиш? — Чоловіка." },
        { de: "Was kaufst du? — Eine Tasche.", uk: "Що ти купуєш? — Сумку." },
        { de: "Wen besuchst du? — Meine Oma.", uk: "Кого ти навідуєш? — Свою бабусю." },
        { de: "Was liest du? — Ein Buch.", uk: "Що ти читаєш? — Книгу." },
        { de: "Wen liebst du?", uk: "Кого ти любиш?" },
        { de: "Was isst du gern?", uk: "Що ти любиш їсти?" },
        { de: "Wen rufst du an?", uk: "Кому ти телефонуєш?" },
        { de: "Was brauchst du?", uk: "Що тобі потрібно?" },
      ],
      tip: "Запам'ятай <b>пари</b>: <i>Wer ↔ Wen</i> (для людей), <i>Was</i> для речей у Nom. і Akk.",
      mistakes: [
        { wrong: "Wer siehst du?", right: "Wen siehst du?" },
        { wrong: "Wen ist das?", right: "Wer ist das? (Nom.)" },
        { wrong: "Was siehst du den Mann?", right: "Wen siehst du? — Den Mann." },
      ],
      exercises: {},
      prevSlug: "was-ist-akkusativ",
      nextSlug: "artikel-im-akkusativ",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "відрізняти Wen (Akk.) від Wer (Nom.)",
        "будувати запитання з Wen/Was",
        "відповідати у формі Akk.",
        "розпізнавати «Wer» і «Wen» на слух",
      ],
      ruleBox: {
        rule: "<b>Wen?</b> — Akk. люди. <b>Was?</b> — речі (Nom./Akk.). Відповідь у відповідному відмінку.",
      },
      ukrainianTips: [
        "Українське «кого?» = <b>Wen?</b>",
        "Дієслова з Akk. <b>підказують</b> питання: <i>sehen → wen?</i>, <i>lieben → wen?</i>",
        "Was не змінюється — те саме слово для Nom. і Akk.",
      ],
      languageComparison: {
        commons: ["«Кого/що» є."],
        diffs: ["У німецькій Wer і Wen виглядають по-різному."],
        traps: ["«Wer siehst du?» — типова помилка."],
      },
      summary: [
        "Wer (Nom.) ↔ Wen (Akk.).",
        "Was — і Nom., і Akk.",
        "Відповідь у Akk.: den/einen/keinen…",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ siehst du?", options: ["Wer","Was","Wen","Wo"], correct: 2 },
      { type: "mc", q: "___ kaufst du?", options: ["Wer","Wen","Was","Wann"], correct: 2 },
      { type: "mc", q: "___ ist das?", options: ["Wer","Wen","Was","Wo"], correct: 0, explain: "Nom., людина." },
      { type: "mc", q: "___ besuchst du heute?", options: ["Wer","Wen","Was","Wo"], correct: 1 },
      { type: "gap", q: "___ liebst du? (кого)", answer: "Wen" },
      { type: "gap", q: "___ isst du? (що)", answer: "Was" },
      { type: "gap", q: "___ kommt morgen? (хто)", answer: "Wer" },
      { type: "tf", q: "Wen — це Akk. для людей.", correct: true },
      { type: "tf", q: "Was змінюється за відмінком.", correct: false },
      { type: "match", prompt: "Зістав питання і відповідь:", pairs: [
        { left: "Wen siehst du?", right: "Den Mann." },
        { left: "Was kaufst du?", right: "Eine Tasche." },
        { left: "Wer kommt?", right: "Anna." },
        { left: "Wen besuchst du?", right: "Meine Oma." },
      ]},
      { type: "multi", q: "Які запитання правильні?", options: [
        "Wer siehst du?",
        "Wen siehst du?",
        "Wen ist das?",
        "Wer ist das?",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Wer siehst du?", correct: ["Wen siehst du?"] },
      { type: "order", prompt: "Склади:", words: ["du","kaufst","Was"], correct: ["Was","kaufst","du"] },
      { type: "translate", prompt: "Переклади:", uk: "Кого ти любиш?", de: ["Wen liebst du?"] },
      { type: "writeFree", prompt: "Напиши 3 запитання з Wen/Was.", sample: "Wen besuchst du? Was machst du? Wen liebst du?", explain: "Перевір відмінок." },
    ],
  },

  // 7 ===================================================================
  "artikel-im-akkusativ": {
    lesson: {
      slug: "artikel-im-akkusativ", level: "A1", category: CAT,
      titleDe: "Artikel im Akkusativ", titleUk: "Артиклі в Akkusativ",
      goal: "Запам'ятати повну таблицю Akk. для означених, неозначених і заперечних артиклів.",
      explanation: [
        "Akkusativ змінює <b>лише чоловічий рід</b>: <b>der → den, ein → einen, kein → keinen</b>.",
        "Жіночий: <b>die / eine / keine</b> — без змін.",
        "Середній: <b>das / ein / kein</b> — без змін.",
        "Множина: <b>die / — / keine</b> — без змін.",
        "Цей патерн повторюється для <b>присвійних</b>: meinen, deinen, seinen, ihren, unseren, euren.",
      ],
      table: {
        headers: ["", "m", "f", "n", "Pl."],
        rows: [
          ["означ.", "den", "die", "das", "die"],
          ["неозн.", "einen", "eine", "ein", "—"],
          ["запер.", "keinen", "keine", "kein", "keine"],
          ["присв. mein", "meinen", "meine", "mein", "meine"],
        ],
      },
      examples: [
        { de: "Ich sehe den Hund.", uk: "Я бачу пса." },
        { de: "Wir kennen die Frau.", uk: "Ми знаємо жінку." },
        { de: "Sie liebt das Kind.", uk: "Вона любить дитину." },
        { de: "Ich habe einen Bruder.", uk: "У мене є брат." },
        { de: "Er hat keine Zeit.", uk: "У нього немає часу." },
        { de: "Wir besuchen meinen Onkel.", uk: "Ми навідаємо мого дядька." },
        { de: "Ich brauche keinen Kaffee.", uk: "Мені не потрібна кава." },
        { de: "Sie liest die Bücher.", uk: "Вона читає книги." },
      ],
      tip: "Запам'ятай ключове правило: <b>в Akk. m додається -en</b>: <i>den, einen, keinen, meinen, deinen, seinen, ihren, unseren, euren, Ihren</i>.",
      mistakes: [
        { wrong: "Ich sehe der Hund.", right: "Ich sehe den Hund." },
        { wrong: "Ich habe ein Bruder.", right: "Ich habe einen Bruder." },
        { wrong: "Er hat kein Zeit.", right: "Er hat keine Zeit." },
      ],
      exercises: {},
      prevSlug: "wen-oder-was",
      nextSlug: "maskulinum-der-den",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "запам'ятати таблицю Akk.",
        "автоматично казати den/einen/keinen у m",
        "не змінювати f/n/Pl.",
        "застосовувати правило -en до присвійних",
      ],
      ruleBox: {
        rule: "Akk: <b>den/einen/keinen · die/eine/keine · das/ein/kein · die/—/keine</b>.",
      },
      ukrainianTips: [
        "У німецькій <b>фокус на m</b>: лише там зміна.",
        "Pl. в Akk. ідентична Nom. — це полегшує життя.",
        "<b>Присвійні</b> змінюються за тим же правилом: meinen Bruder, deinen Vater.",
      ],
      languageComparison: {
        commons: ["Прямий додаток."],
        diffs: ["Лише m змінюється."],
        traps: ["«der» у позиції додатка."],
      },
      summary: [
        "Akk. m → -en.",
        "f / n / Pl. без змін.",
        "Присвійні так само.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich sehe ___ Hund.", options: ["der","den","ein","einer"], correct: 1 },
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["ein","eine","einen","einem"], correct: 2 },
      { type: "mc", q: "Sie liebt ___ Kind.", options: ["der","den","das","dem"], correct: 2 },
      { type: "mc", q: "Wir kennen ___ Frau.", options: ["der","den","die","das"], correct: 2 },
      { type: "gap", q: "Er hat ___ Zeit. (запер., f)", answer: "keine" },
      { type: "gap", q: "Ich besuche ___ Onkel. (мого, Akk. m)", answer: "meinen" },
      { type: "gap", q: "Sie liest ___ Bücher. (озн., Pl.)", answer: "die" },
      { type: "tf", q: "Akk. f → den.", correct: false, explain: "die." },
      { type: "tf", q: "Akk. m додає -en до артикля.", correct: true },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Akk. m озн.", right: "den" },
        { left: "Akk. m неозн.", right: "einen" },
        { left: "Akk. f", right: "die / eine" },
        { left: "Akk. n", right: "das / ein" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich sehe der Mann.",
        "Ich sehe den Mann.",
        "Ich habe einen Bruder.",
        "Ich habe ein Bruder.",
      ], correct: [1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Wir besuchen mein Onkel.", correct: ["Wir besuchen meinen Onkel."] },
      { type: "order", prompt: "Склади:", words: ["habe","einen","Ich","Bruder"], correct: ["Ich","habe","einen","Bruder"] },
      { type: "translate", prompt: "Переклади:", uk: "Я бачу твого брата.", de: ["Ich sehe deinen Bruder."] },
      { type: "writeFree", prompt: "Напиши 3 речення з Akk. (m, f, n).", sample: "Ich sehe den Mann. Ich kenne die Frau. Wir lieben das Kind.", explain: "Перевір артикль за родом." },
    ],
  },

  // 8 ===================================================================
  "maskulinum-der-den": {
    lesson: {
      slug: "maskulinum-der-den", level: "A1", category: CAT,
      titleDe: "Maskulinum: der wird den", titleUk: "Чоловічий рід: der стає den",
      goal: "Закріпити: у Akk. усі m-артиклі та слова отримують <b>-en</b>.",
      explanation: [
        "Найважливіша зміна A1: у Akkusativ <b>чоловічий рід</b> отримує <b>-en</b>.",
        "Список форм: <b>den, einen, keinen, meinen, deinen, seinen, ihren, unseren, euren, Ihren</b>.",
        "Ця зміна стосується <b>тільки артикля</b> та супровідних слів — сам іменник не змінюється: <i>der Mann → den Mann</i>.",
        "Якщо помиляєшся в Akk. m — речення «звучить» неприродно для німця.",
      ],
      table: {
        headers: ["Nom. (m)", "Akk. (m)"],
        rows: [
          ["der Mann", "den Mann"],
          ["ein Mann", "einen Mann"],
          ["kein Mann", "keinen Mann"],
          ["mein Bruder", "meinen Bruder"],
          ["dein Vater", "deinen Vater"],
          ["unser Lehrer", "unseren Lehrer"],
        ],
      },
      examples: [
        { de: "Ich sehe den Mann.", uk: "Я бачу чоловіка." },
        { de: "Wir besuchen einen Freund.", uk: "Ми навідуємо друга." },
        { de: "Er hat keinen Bruder.", uk: "У нього немає брата." },
        { de: "Ich liebe meinen Vater.", uk: "Я люблю свого батька." },
        { de: "Kennst du deinen Lehrer?", uk: "Ти знаєш свого вчителя?" },
        { de: "Wir treffen unseren Onkel.", uk: "Ми зустрічаємо нашого дядька." },
        { de: "Sie kauft einen Apfel.", uk: "Вона купує яблуко." },
        { de: "Ich brauche einen Stift.", uk: "Мені потрібна ручка." },
      ],
      tip: "Уживай <b>«den/einen/keinen»</b> щоразу, коли дієслово діє на щось <b>чоловічого роду</b>.",
      mistakes: [
        { wrong: "Ich sehe der Mann.", right: "Ich sehe den Mann." },
        { wrong: "Ich habe ein Bruder.", right: "Ich habe einen Bruder." },
        { wrong: "Wir besuchen mein Onkel.", right: "Wir besuchen meinen Onkel." },
      ],
      exercises: {},
      prevSlug: "artikel-im-akkusativ",
      nextSlug: "personalpron-im-akkusativ",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "автоматично казати den/einen/keinen",
        "застосовувати -en до присвійних m",
        "розпізнавати дієслова з Akk.",
        "не плутати «der» (Nom.) і «den» (Akk.)",
      ],
      ruleBox: {
        rule: "Akk. m: <b>der → den</b>, <b>ein → einen</b>, <b>kein → keinen</b>, <b>mein/dein/sein/ihr/unser/euer/Ihr → +en</b>.",
      },
      ukrainianTips: [
        "Це <b>основна</b> помилка A1. Якщо чоловічий рід — обов'язково -en.",
        "Українське «бачу брата» = «<i>Ich sehe <b>meinen</b> Bruder</i>».",
        "Слова, які не змінюються (f, n, Pl.) виглядають як у Nom. — і це ок.",
      ],
      languageComparison: {
        commons: ["Знахідний має іншу форму від називного."],
        diffs: ["У німецькій — лише в m."],
        traps: ["der → den — найчастіша."],
      },
      summary: [
        "Akk. m → -<b>en</b>.",
        "den, einen, keinen, meinen…",
        "f / n / Pl. без змін.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich sehe ___ Mann.", options: ["der","den","ein","ein"], correct: 1 },
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["ein","eine","einen","einem"], correct: 2 },
      { type: "mc", q: "Er hat ___ Bruder.", options: ["kein","keine","keinen","keinem"], correct: 2 },
      { type: "mc", q: "Wir besuchen ___ Onkel. (нашого)", options: ["unser","unsere","unseren","unserem"], correct: 2 },
      { type: "gap", q: "Sie liebt ___ Vater. (свого)", answer: "ihren" },
      { type: "gap", q: "Ich kaufe ___ Apfel. (Akk. m)", answer: "einen" },
      { type: "gap", q: "Kennst du ___ Lehrer? (свого, Akk. m)", answer: "deinen" },
      { type: "tf", q: "Akk. m додає -en.", correct: true },
      { type: "tf", q: "Akk. n додає -en.", correct: false, explain: "Лише m." },
      { type: "match", prompt: "Зістав Nom.→Akk.:", pairs: [
        { left: "der Mann", right: "den Mann" },
        { left: "ein Bruder", right: "einen Bruder" },
        { left: "mein Vater", right: "meinen Vater" },
        { left: "unser Onkel", right: "unseren Onkel" },
      ]},
      { type: "multi", q: "Які форми Akk. m правильні?", options: ["den","der","einen","ein","keinen","kein"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Wir besuchen mein Onkel.", correct: ["Wir besuchen meinen Onkel."] },
      { type: "order", prompt: "Склади:", words: ["sehe","Mann","den","Ich"], correct: ["Ich","sehe","den","Mann"] },
      { type: "translate", prompt: "Переклади:", uk: "Я люблю свого батька.", de: ["Ich liebe meinen Vater."] },
      { type: "writeFree", prompt: "Напиши 3 речення з Akk. m (різні артиклі).", sample: "Ich sehe den Mann. Ich habe einen Bruder. Ich besuche meinen Vater.", explain: "Перевір -en у m." },
    ],
  },

  // 9 ===================================================================
  "personalpron-im-akkusativ": {
    lesson: {
      slug: "personalpron-im-akkusativ", level: "A1", category: CAT,
      titleDe: "Personalpronomen im Akkusativ",
      titleUk: "Особові займенники в Akkusativ",
      goal: "Знати всі 9 форм особових займенників у Akk. і вживати їх як прямий додаток.",
      explanation: [
        "Особові займенники у Akk. часто <b>замінюють</b> уже згаданий іменник: <i>Ich kenne <b>den Mann</b>. Ich sehe <b>ihn</b> jeden Tag.</i>",
        "Форми: <b>mich, dich, ihn, sie, es, uns, euch, sie/Sie</b>.",
        "<b>sie, es, Sie</b> у Akk. <b>не змінюються</b>.",
        "Стоїть одразу <b>після відмінюваного дієслова</b>.",
      ],
      table: {
        headers: ["Nom.", "Akk."],
        rows: [
          ["ich", "mich"],
          ["du", "dich"],
          ["er", "ihn"],
          ["sie", "sie"],
          ["es", "es"],
          ["wir", "uns"],
          ["ihr", "euch"],
          ["sie / Sie", "sie / Sie"],
        ],
      },
      examples: [
        { de: "Ich liebe dich.", uk: "Я тебе кохаю." },
        { de: "Er sieht mich oft.", uk: "Він часто мене бачить." },
        { de: "Wir kennen ihn gut.", uk: "Ми його добре знаємо." },
        { de: "Sie besucht uns morgen.", uk: "Вона завтра нас навідає." },
        { de: "Ich rufe euch an.", uk: "Я вам зателефоную." },
        { de: "Hörst du mich?", uk: "Ти мене чуєш?" },
        { de: "Ich kenne sie nicht.", uk: "Я її/їх не знаю." },
        { de: "Ich frage Sie.", uk: "Я вас (ввічл.) питаю." },
      ],
      tip: "Заучи «пісню»: <b>mich, dich, ihn, sie, es, uns, euch, sie/Sie</b>.",
      mistakes: [
        { wrong: "Ich liebe du.", right: "Ich liebe dich." },
        { wrong: "Sie kennt er.", right: "Sie kennt ihn." },
        { wrong: "Er sieht wir.", right: "Er sieht uns." },
      ],
      exercises: {},
      prevSlug: "maskulinum-der-den",
      nextSlug: "verben-mit-akkusativ-a1",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати всі Akk. форми",
        "заміняти іменник займенником",
        "ставити після дієслова",
        "впізнавати ihn vs ihm",
      ],
      ruleBox: {
        rule: "Akk: <b>mich, dich, ihn, sie, es, uns, euch, sie/Sie</b>.",
      },
      ukrainianTips: [
        "<b>ihn</b> = «його» (Akk., m).",
        "<b>sie</b> в Akk. не змінюється (так само як у Nom.).",
        "Дієслова з Akk. підказують, що далі — займенник у Akk.: <i>sehen, lieben, kennen, besuchen, hören, anrufen, fragen</i>.",
      ],
      languageComparison: {
        commons: ["Замінник іменника-додатка є."],
        diffs: ["У німецькій 5 з 9 форм змінюються."],
        traps: ["er → ihn."],
      },
      summary: [
        "mich, dich, ihn, sie, es, uns, euch, sie/Sie.",
        "Незмінні: sie, es, Sie.",
        "Після відмінюваного дієслова.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich liebe ___ . (тебе)", options: ["du","dich","dir","dein"], correct: 1 },
      { type: "mc", q: "Er sieht ___ . (мене)", options: ["ich","mich","mir","mein"], correct: 1 },
      { type: "mc", q: "Sie kennt ___ . (його)", options: ["er","ihn","ihm","sein"], correct: 1 },
      { type: "mc", q: "Wir besuchen ___ . (вас, ihr)", options: ["ihr","euch","sich","Sie"], correct: 1 },
      { type: "gap", q: "Hörst du ___? (мене)", answer: "mich" },
      { type: "gap", q: "Sie versteht ___ . (нас)", answer: "uns" },
      { type: "gap", q: "Ich frage ___ . (Вас ввічл.)", answer: "Sie" },
      { type: "tf", q: "У Akk. «er → ihn».", correct: true },
      { type: "tf", q: "У Akk. «sie» (вона) стає «ihr».", correct: false },
      { type: "match", prompt: "Зістав Nom.→Akk.:", pairs: [
        { left: "ich", right: "mich" },
        { left: "du", right: "dich" },
        { left: "er", right: "ihn" },
        { left: "wir", right: "uns" },
      ]},
      { type: "multi", q: "Які займенники не змінюються в Akk.?", options: ["sie","es","Sie","ich","du","er"], correct: [0,1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Er sieht wir.", correct: ["Er sieht uns."] },
      { type: "order", prompt: "Склади:", words: ["dich","Ich","liebe"], correct: ["Ich","liebe","dich"] },
      { type: "translate", prompt: "Переклади:", uk: "Я тебе чую.", de: ["Ich höre dich."] },
      { type: "writeFree", prompt: "Напиши 3 речення, замінюючи іменник на займенник у Akk.", sample: "Ich kenne ihn. Wir besuchen sie. Er liebt mich.", explain: "Перевір форму." },
    ],
  },

  // 10 ===================================================================
  "verben-mit-akkusativ-a1": {
    lesson: {
      slug: "verben-mit-akkusativ-a1", level: "A1", category: CAT,
      titleDe: "Verben mit Akkusativ", titleUk: "Дієслова з Akkusativ",
      goal: "Знати ключові A1 дієслова, після яких іде Akkusativ, і автоматично ставити правильний артикль.",
      explanation: [
        "Більшість дієслів дії <b>керують Akkusativ</b>. Запам'ятай головні A1: <b>haben, kaufen, sehen, lesen, essen, trinken, brauchen, lieben, kennen, besuchen, hören, anrufen, fragen, suchen, finden</b>.",
        "Після цих дієслів іменник стоїть у формі Akk.: <i>Ich habe <b>einen</b> Bruder.</i>",
        "Не плутай із дієсловами, що вимагають Dativ (helfen, danken, antworten — A2 тема).",
        "Якщо в реченні з'являється <b>прямий додаток</b> — спочатку перевір рід, потім — артикль Akk.",
      ],
      table: {
        headers: ["Дієслово", "Приклад"],
        rows: [
          ["haben", "Ich habe einen Bruder."],
          ["kaufen", "Sie kauft eine Tasche."],
          ["sehen", "Wir sehen den Film."],
          ["lesen", "Er liest ein Buch."],
          ["essen", "Ich esse einen Apfel."],
          ["trinken", "Wir trinken einen Tee."],
          ["brauchen", "Ich brauche eine Lampe."],
          ["besuchen", "Sie besucht ihre Oma."],
        ],
      },
      examples: [
        { de: "Ich habe einen Hund.", uk: "У мене є пес." },
        { de: "Wir kaufen einen Kühlschrank.", uk: "Ми купуємо холодильник." },
        { de: "Er liest die Zeitung.", uk: "Він читає газету." },
        { de: "Sie isst einen Apfel.", uk: "Вона їсть яблуко." },
        { de: "Wir trinken Kaffee.", uk: "Ми п'ємо каву.", tag: "без артикля" },
        { de: "Ich brauche keinen Stift.", uk: "Мені не потрібна ручка." },
        { de: "Anna besucht ihren Vater.", uk: "Анна навідує свого батька." },
        { de: "Wir hören die Musik.", uk: "Ми слухаємо музику." },
      ],
      tip: "Запам'ятай 10 «головних» Akk.-дієслів — і 80% речень A1 будуються правильно.",
      mistakes: [
        { wrong: "Ich habe ein Bruder.", right: "Ich habe einen Bruder." },
        { wrong: "Sie besucht ihr Vater.", right: "Sie besucht ihren Vater." },
        { wrong: "Wir sehen der Film.", right: "Wir sehen den Film." },
      ],
      exercises: {},
      prevSlug: "personalpron-im-akkusativ",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати 10+ дієслів Akk.",
        "автоматично ставити Akk. m → -en",
        "не плутати з дієсловами Dativ",
        "будувати повсякденні речення",
      ],
      ruleBox: {
        rule: "Дієслова дії (haben, kaufen, sehen, lesen, essen, trinken, brauchen, lieben, kennen, besuchen, hören, anrufen, fragen) → <b>Akkusativ</b>.",
      },
      ukrainianTips: [
        "Українські «маю, бачу, читаю, люблю» — теж знахідний відмінок.",
        "<b>brauchen</b> = потребувати (Akk.): <i>Ich brauche einen Stift</i>.",
        "Слова без чіткої кількості (Kaffee, Wasser, Brot) часто без артикля: <i>Ich trinke Kaffee.</i>",
      ],
      languageComparison: {
        commons: ["«Знахідний» збігається за логікою."],
        diffs: ["У німецькій 30+ дієслів — Akk.-керівні."],
        traps: ["helfen → Dativ (інший відмінок)."],
      },
      summary: [
        "Дієслова дії → Akk.",
        "haben, sehen, lesen, lieben…",
        "Akk. m → -en.",
        "Маса A1 речень — Akk.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe ___ Bruder.", options: ["ein","eine","einen","einem"], correct: 2 },
      { type: "mc", q: "Sie kauft ___ Tasche.", options: ["ein","eine","einen","einem"], correct: 1 },
      { type: "mc", q: "Wir sehen ___ Film.", options: ["der","den","das","ein"], correct: 1 },
      { type: "mc", q: "Er liest ___ Zeitung.", options: ["der","den","die","das"], correct: 2 },
      { type: "gap", q: "Ich esse ___ Apfel. (Akk. m)", answer: "einen" },
      { type: "gap", q: "Wir besuchen ___ Oma. (свою, Akk. f)", answer: "unsere" },
      { type: "gap", q: "Sie braucht ___ Lampe.", answer: "eine" },
      { type: "tf", q: "haben керує Akk.", correct: true },
      { type: "tf", q: "helfen керує Akk.", correct: false, explain: "Dativ." },
      { type: "match", prompt: "Зістав дієслово та приклад:", pairs: [
        { left: "haben", right: "einen Bruder" },
        { left: "lesen", right: "das Buch" },
        { left: "kaufen", right: "eine Tasche" },
        { left: "besuchen", right: "die Oma" },
      ]},
      { type: "multi", q: "Які дієслова — Akk.?", options: ["haben","kaufen","helfen","sehen","danken"], correct: [0,1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe ein Bruder.", correct: ["Ich habe einen Bruder."] },
      { type: "order", prompt: "Склади:", words: ["einen","Ich","Apfel","esse"], correct: ["Ich","esse","einen","Apfel"] },
      { type: "translate", prompt: "Переклади:", uk: "Я навідую свого брата.", de: ["Ich besuche meinen Bruder."] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними Akk.-дієсловами.", sample: "Ich habe einen Hund. Wir kaufen ein Auto. Sie liest die Zeitung.", explain: "Перевір артикль Akk." },
    ],
  },
};
