// A1 · Займенники — 12 повних уроків.
import type { A1Map } from "./_helpers";

const CAT = "Займенники";

export const pronomenA1: A1Map = {
  // 1 ===================================================================
  "personalpron-nom": {
    lesson: {
      slug: "personalpron-nom", level: "A1", category: CAT,
      titleDe: "Personalpronomen im Nominativ",
      titleUk: "Особові займенники в Nominativ",
      goal: "Знати всі 7 особових займенників у Nominativ і вживати їх як підмет.",
      explanation: [
        "<b>Особові займенники</b> у Nominativ замінюють підмет: <i>Anna → sie, der Mann → er, das Kind → es</i>.",
        "Список: <b>ich, du, er, sie, es, wir, ihr, sie/Sie</b>.",
        "<b>er</b> для всіх чоловічих іменників (не лише людей): <i>der Tisch → er ist groß</i>.",
        "<b>sie</b> — для жіночого роду (й однина, й множина): <i>die Frau / die Frauen → sie</i>.",
        "<b>es</b> — для середнього роду: <i>das Kind → es</i>.",
        "<b>Sie</b> з великої — ввічливе «Ви».",
      ],
      table: {
        headers: ["Особа", "Займенник", "Приклад"],
        rows: [
          ["1 Sg.", "ich", "Ich lerne Deutsch."],
          ["2 Sg.", "du", "Du sprichst gut."],
          ["3 Sg. m", "er", "Er ist Lehrer."],
          ["3 Sg. f", "sie", "Sie heißt Anna."],
          ["3 Sg. n", "es", "Es regnet."],
          ["1 Pl.", "wir", "Wir wohnen hier."],
          ["2 Pl.", "ihr", "Ihr seid jung."],
          ["3 Pl.", "sie", "Sie kommen heute."],
          ["ввічл.", "Sie", "Wie heißen Sie?"],
        ],
      },
      examples: [
        { de: "Ich bin Anna.", uk: "Я — Анна." },
        { de: "Du sprichst Deutsch.", uk: "Ти розмовляєш німецькою." },
        { de: "Er arbeitet in Berlin.", uk: "Він працює в Берліні." },
        { de: "Sie heißt Maria.", uk: "Її звати Марія." },
        { de: "Es ist kalt.", uk: "Холодно." },
        { de: "Wir lernen zusammen.", uk: "Ми вчимося разом." },
        { de: "Ihr seid sehr nett.", uk: "Ви (мн.) дуже милі." },
        { de: "Wie heißen Sie?", uk: "Як вас звати?", tag: "ввічл." },
      ],
      tip: "<b>sie</b> = «вона» <b>або</b> «вони». Розрізняй за дієсловом: <i>sie ist</i> = вона; <i>sie sind</i> = вони.",
      mistakes: [
        { wrong: "Mich bin Anna.", right: "Ich bin Anna." },
        { wrong: "Du sind Lehrer.", right: "Du bist Lehrer." },
        { wrong: "Ihm arbeitet hier.", right: "Er arbeitet hier." },
      ],
      exercises: {},
      nextSlug: "personalpron-akk",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати всі 7 особових займенників",
        "вживати er/sie/es згідно з родом",
        "відрізняти sie (вона) і sie (вони)",
        "ввічливо звертатися через Sie",
      ],
      ruleBox: {
        rule: "<b>ich · du · er · sie · es · wir · ihr · sie/Sie</b> — підмет у Nominativ.",
      },
      ukrainianTips: [
        "Українському «воно» відповідає <b>es</b> — лише для речей середнього роду.",
        "<b>Sie</b> (ввічл.) — завжди з великої літери; виглядає як «вони».",
        "<b>du</b> — для друзів, родини, дітей; <b>Sie</b> — для незнайомих, на роботі, у магазині.",
      ],
      languageComparison: {
        commons: ["Особові займенники є й там, і там."],
        diffs: ["У німецькій рід «зашитий» у займенник."],
        traps: ["Пропуск займенника = груба помилка."],
      },
      summary: [
        "7 особових: ich/du/er/sie/es/wir/ihr/sie/Sie.",
        "sie = «вона» або «вони» (за дієсловом).",
        "Sie з великої = ввічл.",
        "es — для речей n.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ heiße Anna.", options: ["Ich","Du","Er","Sie"], correct: 0 },
      { type: "mc", q: "___ bist sehr nett.", options: ["Ich","Du","Er","Wir"], correct: 1 },
      { type: "mc", q: "___ arbeitet in Berlin. (про чоловіка)", options: ["Ich","Du","Er","Sie"], correct: 2 },
      { type: "mc", q: "___ regnet heute.", options: ["Er","Sie","Es","Ihr"], correct: 2 },
      { type: "gap", q: "___ wohnen in Lwiw. (ми)", answer: "Wir" },
      { type: "gap", q: "___ seid jung. (ви — мн.)", answer: "Ihr" },
      { type: "gap", q: "Wie heißen ___? (ввічл.)", answer: "Sie" },
      { type: "tf", q: "«sie» може означати і «вона», і «вони».", correct: true },
      { type: "tf", q: "«Sie» з великої — це 2 ос. однини du.", correct: false, explain: "Це ввічливе Ви." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "ich", right: "1 Sg." },
        { left: "du", right: "2 Sg." },
        { left: "wir", right: "1 Pl." },
        { left: "ihr", right: "2 Pl." },
      ]},
      { type: "multi", q: "Які займенники — 3 особа?", options: ["er","du","sie","es","ich","ihr"], correct: [0,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Mich bin Anna.", correct: ["Ich bin Anna."] },
      { type: "order", prompt: "Склади:", words: ["heiße","Anna","Ich"], correct: ["Ich","heiße","Anna"] },
      { type: "translate", prompt: "Переклади:", uk: "Як Вас звати? (ввічл.)", de: ["Wie heißen Sie?"] },
      { type: "writeFree", prompt: "Напиши 3 речення з 3 різними займенниками.", sample: "Ich lerne Deutsch. Du sprichst gut. Wir wohnen in Lwiw.", explain: "Перевір узгодження." },
    ],
  },

  // 2 ===================================================================
  "personalpron-akk": {
    lesson: {
      slug: "personalpron-akk", level: "A1", category: CAT,
      titleDe: "Personalpronomen im Akkusativ",
      titleUk: "Особові займенники в Akkusativ",
      goal: "Знати форми Akk. (mich, dich, ihn, sie, es, uns, euch, sie/Sie) і вживати їх як прямий додаток.",
      explanation: [
        "У Akkusativ змінюються тільки <b>ich → mich</b>, <b>du → dich</b>, <b>er → ihn</b>, <b>wir → uns</b>, <b>ihr → euch</b>.",
        "<b>sie</b> (вона/вони), <b>es</b> (воно), <b>Sie</b> (ввічл.) — у Akk. <b>не змінюються</b>.",
        "Вживаються після дієслів з Akk.: <b>sehen, hören, lieben, besuchen, treffen, fragen, anrufen</b>.",
        "Місце займенника — одразу після відмінюваного дієслова: <i>Ich sehe <b>dich</b> jeden Tag.</i>",
      ],
      table: {
        headers: ["Nom.", "Akk."],
        rows: [
          ["ich", "mich"],
          ["du", "dich"],
          ["er", "ihn"],
          ["sie (вона)", "sie"],
          ["es", "es"],
          ["wir", "uns"],
          ["ihr", "euch"],
          ["sie (вони)", "sie"],
          ["Sie (ввічл.)", "Sie"],
        ],
      },
      examples: [
        { de: "Ich liebe dich.", uk: "Я тебе кохаю." },
        { de: "Er sieht mich.", uk: "Він мене бачить." },
        { de: "Sie kennt ihn.", uk: "Вона його знає." },
        { de: "Wir besuchen sie morgen.", uk: "Ми навідаємо її/їх завтра." },
        { de: "Ich rufe euch an.", uk: "Я вам зателефоную." },
        { de: "Hörst du mich?", uk: "Ти мене чуєш?" },
        { de: "Sie versteht uns gut.", uk: "Вона нас добре розуміє." },
        { de: "Ich frage Sie.", uk: "Я вас (ввічл.) питаю." },
      ],
      tip: "Запам'ятай як «пісню»: <b>mich, dich, ihn, sie, es, uns, euch, sie/Sie</b>.",
      mistakes: [
        { wrong: "Ich liebe du.", right: "Ich liebe dich." },
        { wrong: "Sie kennt er.", right: "Sie kennt ihn." },
        { wrong: "Er sieht wir.", right: "Er sieht uns." },
      ],
      exercises: {},
      prevSlug: "personalpron-nom",
      nextSlug: "ich-du-er-sie-es",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати всі форми Akk.",
        "вживати їх із дієсловами Akk.",
        "не плутати з Nom.",
        "ставити займенник одразу після дієслова",
      ],
      ruleBox: {
        rule: "Akk: <b>mich · dich · ihn · sie · es · uns · euch · sie/Sie</b>.",
      },
      ukrainianTips: [
        "У формі <b>ihn</b> легко плутати з <b>ihm</b> — ihn це Akk., ihm — Dat. (буде у A2).",
        "<b>sie</b> і <b>es</b> у Akk. не змінюються — це полегшує життя.",
        "Українське «телефоную тобі» = «<i>Ich rufe <b>dich</b> an</i>» — <b>Akk</b>., бо anrufen + Akk.",
      ],
      languageComparison: {
        commons: ["Прямий додаток є в обох мовах."],
        diffs: ["У німецькій тільки 5 форм реально змінюються."],
        traps: ["sie/es виглядають однаково Nom./Akk."],
      },
      summary: [
        "Змінюються: mich, dich, ihn, uns, euch.",
        "Не змінюються: sie, es, Sie.",
        "Дієслова Akk.: sehen, lieben, besuchen, hören, anrufen.",
        "Займенник одразу після дієслова.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich liebe ___ . (тебе)", options: ["du","dich","dir","dein"], correct: 1 },
      { type: "mc", q: "Er sieht ___ . (мене)", options: ["ich","mich","mir","mein"], correct: 1 },
      { type: "mc", q: "Sie kennt ___ . (його)", options: ["er","ihn","ihm","sein"], correct: 1 },
      { type: "mc", q: "Wir besuchen ___ . (її)", options: ["sie","ihr","ihn","es"], correct: 0 },
      { type: "gap", q: "Hörst du ___? (мене)", answer: "mich" },
      { type: "gap", q: "Sie versteht ___ . (нас)", answer: "uns" },
      { type: "gap", q: "Ich rufe ___ an. (вас, ihr)", answer: "euch" },
      { type: "tf", q: "У Akk. «du → dich».", correct: true },
      { type: "tf", q: "У Akk. «sie» (вона) стає «ihr».", correct: false, explain: "Лишається sie." },
      { type: "match", prompt: "Зістав Nom. і Akk.:", pairs: [
        { left: "ich", right: "mich" },
        { left: "du", right: "dich" },
        { left: "er", right: "ihn" },
        { left: "wir", right: "uns" },
      ]},
      { type: "multi", q: "Які займенники не змінюються в Akk.?", options: ["sie","es","Sie","ich","du"], correct: [0,1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Sie kennt er.", correct: ["Sie kennt ihn."] },
      { type: "order", prompt: "Склади:", words: ["liebe","dich","Ich"], correct: ["Ich","liebe","dich"] },
      { type: "translate", prompt: "Переклади:", uk: "Я вам (ввічл.) зателефоную.", de: ["Ich rufe Sie an."] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними Akk. займенниками.", sample: "Ich sehe dich. Er kennt mich. Wir besuchen sie morgen.", explain: "Перевір форму Akk." },
    ],
  },

  // 3 ===================================================================
  "ich-du-er-sie-es": {
    lesson: {
      slug: "ich-du-er-sie-es", level: "A1", category: CAT,
      titleDe: "ich, du, er, sie, es",
      titleUk: "ich, du, er, sie, es — займенники однини",
      goal: "Натренувати 5 займенників однини й узгоджувати з ними дієслово.",
      explanation: [
        "<b>ich</b> — 1 особа однини: «я». Завжди з малої (крім початку речення).",
        "<b>du</b> — 2 особа однини, дружня форма «ти». Для близьких.",
        "<b>er</b> — 3 особа однини, чоловічий рід або «він».",
        "<b>sie</b> — 3 особа однини, жіночий рід або «вона».",
        "<b>es</b> — 3 особа однини, середній рід або безособове «воно» (<i>Es regnet</i>).",
        "Кожен потребує своєї форми дієслова: <i>ich mache, du machst, er/sie/es macht</i>.",
      ],
      table: {
        headers: ["Займенник", "machen", "sein", "haben"],
        rows: [
          ["ich", "mache", "bin", "habe"],
          ["du", "machst", "bist", "hast"],
          ["er", "macht", "ist", "hat"],
          ["sie", "macht", "ist", "hat"],
          ["es", "macht", "ist", "hat"],
        ],
      },
      examples: [
        { de: "Ich mache Hausaufgaben.", uk: "Я роблю домашнє завдання." },
        { de: "Du bist mein Freund.", uk: "Ти мій друг." },
        { de: "Er hat einen Hund.", uk: "У нього є собака." },
        { de: "Sie kommt aus Italien.", uk: "Вона з Італії." },
        { de: "Es ist neu.", uk: "Воно нове." },
        { de: "Es schneit.", uk: "Сніжить.", tag: "безособове" },
        { de: "Wie heißt sie?", uk: "Як її звати?" },
        { de: "Was machst du?", uk: "Що ти робиш?" },
      ],
      tip: "Безособове <b>es</b> вживають з природними явищами: <i>Es regnet, es schneit, es ist kalt.</i>",
      mistakes: [
        { wrong: "Du macht Hausaufgaben.", right: "Du machst Hausaufgaben." },
        { wrong: "Er bin Lehrer.", right: "Er ist Lehrer." },
        { wrong: "Sie sind nett. (про одну особу)", right: "Sie ist nett." },
      ],
      exercises: {},
      prevSlug: "personalpron-akk",
      nextSlug: "wir-ihr-sie-Sie",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати 5 займенників однини",
        "узгоджувати дієслово",
        "уживати безособове es",
        "не плутати sie (вона) з sie/Sie",
      ],
      ruleBox: {
        rule: "5 займенників однини: <b>ich, du, er, sie, es</b>. Дієслово 1 ос. → -e; 2 ос. → -st; 3 ос. → -t.",
      },
      ukrainianTips: [
        "<b>ich</b> завжди з малої — на відміну від англійського «I».",
        "В українській «вона працює» = «sie arbeitet» — спільна форма для er/sie/es.",
        "Природні явища (дощ, сніг) — <b>es</b>: <i>Es regnet</i>.",
      ],
      languageComparison: {
        commons: ["Особові займенники є."],
        diffs: ["Безособове es."],
        traps: ["sie (вона) ↔ sie (вони)."],
      },
      summary: [
        "ich/du/er/sie/es.",
        "Закінчення: -e, -st, -t, -t, -t.",
        "es для природи (<i>Es regnet</i>).",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ lerne Deutsch.", options: ["Ich","Du","Er","Sie"], correct: 0 },
      { type: "mc", q: "___ bist müde.", options: ["Ich","Du","Er","Es"], correct: 1 },
      { type: "mc", q: "___ kommt aus Berlin. (про чоловіка)", options: ["Er","Sie","Es","Du"], correct: 0 },
      { type: "mc", q: "___ heißt Anna.", options: ["Er","Sie","Es","Ich"], correct: 1 },
      { type: "gap", q: "___ regnet. (безособове)", answer: "Es" },
      { type: "gap", q: "Was machst ___? (ти)", answer: "du" },
      { type: "gap", q: "Wie heißt ___? (вона)", answer: "sie" },
      { type: "tf", q: "«ich» завжди з малої.", correct: true },
      { type: "tf", q: "«es schneit» — правильно.", correct: true },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "ich", right: "bin" },
        { left: "du", right: "bist" },
        { left: "er", right: "ist" },
        { left: "es", right: "ist" },
      ]},
      { type: "multi", q: "Які форми правильні?", options: ["du machst","du macht","er macht","er machst","es ist","es bist"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Du macht Sport.", correct: ["Du machst Sport."] },
      { type: "order", prompt: "Склади:", words: ["arbeitet","Berlin","in","Er"], correct: ["Er","arbeitet","in","Berlin"] },
      { type: "translate", prompt: "Переклади:", uk: "Холодно.", de: ["Es ist kalt."] },
      { type: "writeFree", prompt: "Напиши 5 коротких речень з ich/du/er/sie/es.", sample: "Ich lerne. Du schläfst. Er arbeitet. Sie singt. Es regnet.", explain: "Кожному займеннику — своя форма." },
    ],
  },

  // 4 ===================================================================
  "wir-ihr-sie-Sie": {
    lesson: {
      slug: "wir-ihr-sie-Sie", level: "A1", category: CAT,
      titleDe: "wir, ihr, sie, Sie",
      titleUk: "wir, ihr, sie, Sie — займенники множини",
      goal: "Розрізняти 4 «множинні» займенники й уживати правильну форму дієслова.",
      explanation: [
        "<b>wir</b> — «ми». Дієслово на -en: <i>wir lernen, wir sind, wir haben</i>.",
        "<b>ihr</b> — «ви» (звертання до групи знайомих). Дієслово на -t: <i>ihr lernt, ihr seid, ihr habt</i>.",
        "<b>sie</b> — «вони». Дієслово на -en: <i>sie lernen, sie sind, sie haben</i>.",
        "<b>Sie</b> з великої — ввічливе «Ви» (одна особа або група). Форма дієслова як у sie (вони): <i>Sie lernen, Sie sind</i>.",
      ],
      table: {
        headers: ["Займенник", "machen", "sein", "haben"],
        rows: [
          ["wir", "machen", "sind", "haben"],
          ["ihr", "macht", "seid", "habt"],
          ["sie (вони)", "machen", "sind", "haben"],
          ["Sie (ввічл.)", "machen", "sind", "haben"],
        ],
      },
      examples: [
        { de: "Wir lernen Deutsch.", uk: "Ми вчимо німецьку." },
        { de: "Ihr seid sehr nett.", uk: "Ви (мн.) дуже милі." },
        { de: "Sie kommen morgen.", uk: "Вони приїдуть завтра." },
        { de: "Wie heißen Sie?", uk: "Як вас звати? (ввічл.)" },
        { de: "Wir haben zwei Kinder.", uk: "У нас двоє дітей." },
        { de: "Habt ihr Hunger?", uk: "Ви голодні?" },
        { de: "Sie arbeiten viel.", uk: "Вони багато працюють." },
        { de: "Sprechen Sie Deutsch?", uk: "Ви розмовляєте німецькою? (ввічл.)" },
      ],
      tip: "Розрізняй <b>ihr</b> (ви — друзі/група) і <b>Sie</b> (ви — ввічливо). Sie завжди з <b>великої</b>.",
      mistakes: [
        { wrong: "Wir lernt Deutsch.", right: "Wir lernen Deutsch." },
        { wrong: "Ihr seid sind hier.", right: "Ihr seid hier." },
        { wrong: "Wie heißt Sie?", right: "Wie heißen Sie?" },
      ],
      exercises: {},
      prevSlug: "ich-du-er-sie-es",
      nextSlug: "possessiv-mein-dein",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "розрізняти 4 множинні займенники",
        "вживати ihr для друзів, Sie для ввічливості",
        "узгоджувати дієслово",
        "розпізнавати sie (вони) і Sie (Ви)",
      ],
      ruleBox: {
        rule: "wir + -en · ihr + -t · sie/Sie + -en. <b>Sie</b> завжди з великої.",
      },
      ukrainianTips: [
        "Українському «ви» (до однієї людини ввічливо) = німецьке <b>Sie</b>.",
        "Українському «ви» (до групи знайомих) = німецьке <b>ihr</b>.",
        "Дієслово після <b>Sie</b> має ту саму форму, що й після sie (вони).",
      ],
      languageComparison: {
        commons: ["«Ви» ввічливе є в обох."],
        diffs: ["У німецькій воно — окремий займенник Sie."],
        traps: ["sie vs Sie — за контекстом і великою."],
      },
      summary: [
        "wir / ihr / sie / Sie.",
        "wir, sie, Sie → -en; ihr → -t.",
        "Sie завжди з великої.",
        "ihr — друзі; Sie — ввічливо.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ lernen Deutsch. (ми)", options: ["Wir","Ihr","Sie","Du"], correct: 0 },
      { type: "mc", q: "___ seid jung.", options: ["Wir","Ihr","Sie","Du"], correct: 1 },
      { type: "mc", q: "___ kommen morgen. (вони)", options: ["Wir","Ihr","Sie","Du"], correct: 2 },
      { type: "mc", q: "Wie heißen ___? (ввічл.)", options: ["du","ihr","sie","Sie"], correct: 3 },
      { type: "gap", q: "Habt ___ Hunger? (ви — друзі)", answer: "ihr" },
      { type: "gap", q: "___ sind Lehrer. (вони)", answer: "Sie", hint: "Не з великої — це 3 ос. мн." },
      { type: "gap", q: "___ haben zwei Kinder. (ми)", answer: "Wir" },
      { type: "tf", q: "«Sie» завжди з великої.", correct: true },
      { type: "tf", q: "«ihr lernt» — правильна форма.", correct: true },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "wir", right: "haben" },
        { left: "ihr", right: "habt" },
        { left: "sie", right: "haben" },
        { left: "Sie (ввічл.)", right: "haben" },
      ]},
      { type: "multi", q: "Які форми правильні?", options: ["wir lernen","wir lernt","ihr seid","ihr sind","sie sind","sie seid"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Wir lernt Deutsch.", correct: ["Wir lernen Deutsch."] },
      { type: "order", prompt: "Склади:", words: ["jung","seid","Ihr","sehr"], correct: ["Ihr","seid","sehr","jung"] },
      { type: "translate", prompt: "Переклади (ввічл.):", uk: "Ви розмовляєте німецькою?", de: ["Sprechen Sie Deutsch?"] },
      { type: "writeFree", prompt: "Напиши 3 речення з wir/ihr/Sie.", sample: "Wir wohnen in Wien. Ihr seid Studenten. Sprechen Sie Deutsch?", explain: "Перевір узгодження." },
    ],
  },

  // 5 ===================================================================
  "possessiv-mein-dein": {
    lesson: {
      slug: "possessiv-mein-dein", level: "A1", category: CAT,
      titleDe: "Possessivpronomen: mein und dein",
      titleUk: "Присвійні займенники mein і dein",
      goal: "Утворювати «мій / твій» з правильним закінченням за родом і відмінком.",
      explanation: [
        "<b>mein</b> = «мій». <b>dein</b> = «твій».",
        "Закінчення такі ж, як в <b>ein</b>: <b>mein/meine/mein</b> (Nom.) · <b>meinen/meine/mein</b> (Akk.).",
        "У множині для всіх родів: <b>meine</b> / <b>deine</b>.",
        "Завжди стоять <b>перед</b> іменником і узгоджуються з ним.",
      ],
      table: {
        headers: ["Рід", "Nom.", "Akk."],
        rows: [
          ["m", "mein Bruder", "meinen Bruder"],
          ["f", "meine Schwester", "meine Schwester"],
          ["n", "mein Kind", "mein Kind"],
          ["Pl.", "meine Kinder", "meine Kinder"],
        ],
      },
      examples: [
        { de: "Das ist mein Bruder.", uk: "Це мій брат." },
        { de: "Meine Schwester heißt Anna.", uk: "Мою сестру звати Анна." },
        { de: "Mein Kind ist klein.", uk: "Моя дитина маленька." },
        { de: "Meine Eltern wohnen in Lwiw.", uk: "Мої батьки живуть у Львові." },
        { de: "Wie heißt dein Bruder?", uk: "Як звати твого брата?" },
        { de: "Ich sehe deine Schwester.", uk: "Я бачу твою сестру." },
        { de: "Wo ist meinen Schlüssel?", uk: "Де мій ключ?", tag: "Akk. m → meinen" },
        { de: "Deine Eltern sind nett.", uk: "Твої батьки милі." },
      ],
      tip: "Закінчення mein/dein збігаються з ein/eine/ein. Якщо знаєш ein-форми → знаєш mein/dein.",
      mistakes: [
        { wrong: "Das ist meine Bruder.", right: "Das ist mein Bruder." },
        { wrong: "Ich sehe mein Schwester.", right: "Ich sehe meine Schwester." },
        { wrong: "Wo ist mein Schlüssel? (як Akk.)", right: "Wo ist mein Schlüssel? ✓ (тут Nom.); Akk: Ich sehe meinen Schlüssel." },
      ],
      exercises: {},
      prevSlug: "wir-ihr-sie-Sie",
      nextSlug: "possessiv-sein-ihr",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "відмінювати mein/dein за родом і відмінком",
        "знати, що Akk. m → -en",
        "ставити присвійний перед іменником",
        "уживати у фразах про родину",
      ],
      ruleBox: {
        rule: "mein/dein = як ein. Nom: mein/meine/mein. Akk: <b>meinen</b>/meine/mein. Pl: meine.",
      },
      ukrainianTips: [
        "Українське «мій брат» = «mein Bruder» (Nom.). «Я бачу мого брата» = «<i>Ich sehe <b>meinen</b> Bruder</i>».",
        "У множині: «мої батьки» = <b>meine</b> Eltern.",
        "<b>dein</b> вживають з du (друзі/родина); до Sie буде «Ihr» (з великої) — у наступних уроках.",
      ],
      languageComparison: {
        commons: ["Присвійні узгоджуються з іменником."],
        diffs: ["У німецькій змінюється закінчення за родом/відмінком."],
        traps: ["«meine Bruder» — типова помилка (правильно mein)."],
      },
      summary: [
        "mein/dein = як ein.",
        "Akk. m → meinen/deinen.",
        "Pl. → meine/deine.",
        "Завжди перед іменником.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das ist ___ Bruder.", options: ["mein","meine","meinen","meinem"], correct: 0 },
      { type: "mc", q: "___ Schwester ist nett.", options: ["Mein","Meine","Meinen","Meinem"], correct: 1 },
      { type: "mc", q: "Ich sehe ___ Bruder.", options: ["mein","meine","meinen","meinem"], correct: 2 },
      { type: "mc", q: "___ Eltern wohnen in Wien.", options: ["Mein","Meine","Meinen","Meinem"], correct: 1 },
      { type: "gap", q: "Wie heißt ___ Schwester? (твоя)", answer: "deine" },
      { type: "gap", q: "Das ist ___ Auto. (моє)", answer: "mein" },
      { type: "gap", q: "Ich besuche ___ Bruder. (Akk., мого)", answer: "meinen" },
      { type: "tf", q: "У Pl. для всіх родів — «meine».", correct: true },
      { type: "tf", q: "Akk. m «mein» → «meinem».", correct: false, explain: "meinen." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Bruder (Nom.)", right: "mein" },
        { left: "Schwester (Nom.)", right: "meine" },
        { left: "Bruder (Akk.)", right: "meinen" },
        { left: "Kinder (Pl.)", right: "meine" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Das ist meine Bruder.",
        "Das ist mein Bruder.",
        "Ich sehe meinen Bruder.",
        "Ich sehe mein Bruder.",
      ], correct: [1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich sehe mein Schwester.", correct: ["Ich sehe meine Schwester."] },
      { type: "order", prompt: "Склади:", words: ["Bruder","Mein","Lwiw","wohnt","in"], correct: ["Mein","Bruder","wohnt","in","Lwiw"] },
      { type: "translate", prompt: "Переклади:", uk: "Я бачу твого брата.", de: ["Ich sehe deinen Bruder."] },
      { type: "writeFree", prompt: "Напиши 3 речення про свою родину з mein/meine.", sample: "Mein Vater ist Lehrer. Meine Mutter ist Ärztin. Meine Geschwister wohnen in Wien.", explain: "Перевір закінчення." },
    ],
  },

  // 6 ===================================================================
  "possessiv-sein-ihr": {
    lesson: {
      slug: "possessiv-sein-ihr", level: "A1", category: CAT,
      titleDe: "Possessivpronomen: sein und ihr",
      titleUk: "Присвійні sein (його) і ihr (її/їх)",
      goal: "Утворювати «його / її / їхній» і не плутати <b>sein</b> з дієсловом <i>sein</i>.",
      explanation: [
        "<b>sein</b> = «його» (для er, es). <b>ihr</b> = «її» або «їхній» (для sie, sie Pl.).",
        "Закінчення такі ж: sein/seine/sein · ihr/ihre/ihr. У Akk. m: <b>seinen / ihren</b>.",
        "Не плутай <b>sein</b> (його) з дієсловом <b>sein</b> (бути): значення видно з контексту.",
        "Для ввічливого Sie присвійний — <b>Ihr</b> з великої: <i>Ihre Adresse, bitte.</i>",
      ],
      table: {
        headers: ["Особа", "Присв.", "Приклад"],
        rows: [
          ["er", "sein", "sein Bruder, seine Schwester"],
          ["es", "sein", "sein Spielzeug"],
          ["sie (вона)", "ihr", "ihr Bruder, ihre Schwester"],
          ["sie (вони)", "ihr", "ihre Eltern"],
          ["Sie (ввічл.)", "Ihr", "Ihre Adresse"],
        ],
      },
      examples: [
        { de: "Das ist sein Bruder.", uk: "Це його брат." },
        { de: "Seine Schwester heißt Anna.", uk: "Його сестра — Анна." },
        { de: "Ich sehe seinen Vater.", uk: "Я бачу його батька." },
        { de: "Das ist ihr Kind.", uk: "Це її/їхня дитина." },
        { de: "Ihre Eltern sind in Wien.", uk: "Її/їхні батьки в Відні." },
        { de: "Wie ist Ihre Adresse?", uk: "Яка ваша адреса? (ввічл.)" },
        { de: "Sein Auto ist neu.", uk: "Його автомобіль новий." },
        { de: "Ihr Hund ist groß.", uk: "Її/їхній пес великий." },
      ],
      tip: "<b>ihr</b> має 3 значення: «її», «їхній», або <i>ihr</i> (особовий — «ви, друзі»). Розрізняй за контекстом і дієсловом.",
      mistakes: [
        { wrong: "Das ist ihre Bruder.", right: "Das ist ihr Bruder." },
        { wrong: "Wie ist deine Adresse? (до незнайомого)", right: "Wie ist Ihre Adresse?" },
        { wrong: "Ich sehe sein Vater.", right: "Ich sehe seinen Vater." },
      ],
      exercises: {},
      prevSlug: "possessiv-mein-dein",
      nextSlug: "possessiv-unser-euer",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати sein (його) для er/es",
        "знати ihr для sie (вона/вони)",
        "ввічливе Ihr з великої для Sie",
        "не плутати з ein/mein",
      ],
      ruleBox: {
        rule: "Закінчення = ein. <b>sein</b> = його. <b>ihr</b> = її/їхній. <b>Ihr</b> (з великої) = Ваш (ввічл.).",
      },
      ukrainianTips: [
        "Українське «її/їхній» — обидва <b>ihr</b>. Розрізняти не треба.",
        "<b>Ihr</b> (Ваш ввічл.) <b>завжди</b> з великої — як і Sie.",
        "Дієслово <b>sein</b> (бути) — інше слово, не плутати.",
      ],
      languageComparison: {
        commons: ["Присвійні узгоджуються з предметом."],
        diffs: ["У німецькій 3 однакові «ihr»."],
        traps: ["ihr (її) ↔ ihr (ви) ↔ Ihr (Ваш)."],
      },
      summary: [
        "sein = його (er/es).",
        "ihr = її/їхній (sie).",
        "Ihr = Ваш (Sie).",
        "Закінчення як ein.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das ist ___ Bruder. (його)", options: ["sein","seine","seinen","seinem"], correct: 0 },
      { type: "mc", q: "___ Schwester heißt Anna. (його)", options: ["Sein","Seine","Seinen","Seinem"], correct: 1 },
      { type: "mc", q: "Ich sehe ___ Vater. (його, Akk.)", options: ["sein","seine","seinen","seinem"], correct: 2 },
      { type: "mc", q: "Das ist ___ Kind. (її)", options: ["sein","ihr","ihre","ihren"], correct: 1 },
      { type: "gap", q: "___ Eltern wohnen in Wien. (її)", answer: "Ihre" },
      { type: "gap", q: "Wie ist ___ Adresse? (Ваша, ввічл.)", answer: "Ihre" },
      { type: "gap", q: "Ich sehe ___ Hund. (її, Akk. m)", answer: "ihren" },
      { type: "tf", q: "«ihr Bruder» може означати «її брат» або «їхній брат».", correct: true },
      { type: "tf", q: "«Ihr» з великої — це присвійний для du.", correct: false, explain: "Для Sie." },
      { type: "match", prompt: "Зістав особу й присвійний:", pairs: [
        { left: "er", right: "sein" },
        { left: "sie (вона)", right: "ihr" },
        { left: "sie (вони)", right: "ihr" },
        { left: "Sie (ввічл.)", right: "Ihr" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Das ist ihre Bruder.",
        "Das ist ihr Bruder.",
        "Ich sehe seinen Vater.",
        "Ich sehe sein Vater.",
      ], correct: [1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Wie ist deine Adresse? (до незнайомого)", correct: ["Wie ist Ihre Adresse?"] },
      { type: "order", prompt: "Склади:", words: ["ist","Bruder","Sein","Lehrer"], correct: ["Sein","Bruder","ist","Lehrer"] },
      { type: "translate", prompt: "Переклади:", uk: "Її батьки живуть у Львові.", de: ["Ihre Eltern wohnen in Lwiw."] },
      { type: "writeFree", prompt: "Напиши 3 речення з sein/ihr/Ihr.", sample: "Sein Bruder ist Student. Ihre Schwester wohnt in Wien. Wie ist Ihre Adresse?", explain: "Перевір присвійний за особою." },
    ],
  },

  // 7 ===================================================================
  "possessiv-unser-euer": {
    lesson: {
      slug: "possessiv-unser-euer", level: "A1", category: CAT,
      titleDe: "Possessivpronomen: unser und euer",
      titleUk: "Присвійні unser (наш) і euer (ваш)",
      goal: "Утворювати «наш / ваш» і помічати випадання -e- у формах euer → eure.",
      explanation: [
        "<b>unser</b> = «наш». <b>euer</b> = «ваш» (до групи друзів — як ihr).",
        "Закінчення як в ein. У <b>euer</b> при додаванні закінчення <b>випадає -e-</b>: euer → <b>eure / euren</b>.",
        "У множині для всіх родів: <b>unsere / eure</b>.",
        "Не плутай <b>euer</b> (ваш) із <b>ihr</b> (її/їхній) і <b>Ihr</b> (ваш ввічл.).",
      ],
      table: {
        headers: ["Рід", "unser (Nom.)", "Akk.", "euer (Nom.)", "Akk."],
        rows: [
          ["m", "unser Bruder", "unseren Bruder", "euer Bruder", "euren Bruder"],
          ["f", "unsere Schwester", "unsere Schwester", "eure Schwester", "eure Schwester"],
          ["n", "unser Kind", "unser Kind", "euer Kind", "euer Kind"],
          ["Pl.", "unsere Kinder", "unsere Kinder", "eure Kinder", "eure Kinder"],
        ],
      },
      examples: [
        { de: "Unser Lehrer ist nett.", uk: "Наш учитель милий." },
        { de: "Unsere Schule ist groß.", uk: "Наша школа велика." },
        { de: "Wir lieben unsere Eltern.", uk: "Ми любимо своїх батьків." },
        { de: "Wo ist euer Hund?", uk: "Де ваш собака?" },
        { de: "Eure Wohnung ist schön.", uk: "Ваша квартира гарна." },
        { de: "Ich besuche eure Eltern.", uk: "Я навідаю ваших батьків." },
        { de: "Unser Auto ist neu.", uk: "Наш автомобіль новий." },
        { de: "Habt ihr eure Bücher dabei?", uk: "У вас із собою ваші книги?" },
      ],
      tip: "У <b>euer + закінчення</b> випадає внутрішнє <b>-e-</b>: <i>euer Bruder → eure Schwester → euren Bruder</i>.",
      mistakes: [
        { wrong: "Das ist eueres Auto.", right: "Das ist euer Auto." },
        { wrong: "Unsere Bruder ist nett.", right: "Unser Bruder ist nett." },
        { wrong: "Wo ist eures Hund?", right: "Wo ist euer Hund?" },
      ],
      exercises: {},
      prevSlug: "possessiv-sein-ihr",
      nextSlug: "reflexiv-mich-dich",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "уживати unser/euer за родом і відмінком",
        "помічати випадіння -e- у euer",
        "вживати у множині",
        "не плутати з ihr/Ihr",
      ],
      ruleBox: {
        rule: "unser = наш · euer = ваш (друзі). У <b>euer + закінчення</b> випадає <b>-e-</b>: eure, euren.",
      },
      ukrainianTips: [
        "Українське «ваш» (до групи) = <b>euer</b>; «ваш» (ввічл.) = <b>Ihr</b>.",
        "Випадіння -e- — це для зручної вимови: <i>eure</i> легше за <i>euere</i>.",
        "<b>unser</b> -e- <b>не</b> випадає: завжди <i>unsere, unseren</i>.",
      ],
      languageComparison: {
        commons: ["Присвійні узгоджуються."],
        diffs: ["Випадіння -e- у euer."],
        traps: ["«eueres» — поширена помилка."],
      },
      summary: [
        "unser / euer.",
        "euer + закінч. → випадає -e-.",
        "Pl. → unsere/eure.",
        "Akk. m → -en.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Lehrer ist nett. (наш)", options: ["Unser","Unsere","Unseren","Unserem"], correct: 0 },
      { type: "mc", q: "___ Schule ist groß. (наша)", options: ["Unser","Unsere","Unseren","Unserem"], correct: 1 },
      { type: "mc", q: "Wo ist ___ Hund? (ваш, друзі)", options: ["euer","eure","euren","euerem"], correct: 0 },
      { type: "mc", q: "Ich besuche ___ Eltern. (ваших)", options: ["euer","eure","euren","euerer"], correct: 1 },
      { type: "gap", q: "___ Wohnung ist schön. (ваша)", answer: "Eure" },
      { type: "gap", q: "Wir lieben ___ Eltern. (наших)", answer: "unsere" },
      { type: "gap", q: "Ich sehe ___ Bruder. (вашого, Akk. m)", answer: "euren" },
      { type: "tf", q: "У формі «eure» випало -e- з «euer».", correct: true },
      { type: "tf", q: "«unsere Bruder» — правильно.", correct: false, explain: "unser Bruder (m)." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Bruder (m, Nom.)", right: "euer" },
        { left: "Schwester (f, Nom.)", right: "eure" },
        { left: "Bruder (Akk. m)", right: "euren" },
        { left: "Kinder (Pl.)", right: "eure" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Eure Wohnung ist schön.",
        "Euer Wohnung ist schön.",
        "Unser Auto ist neu.",
        "Unsere Auto ist neu.",
      ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Das ist eueres Auto.", correct: ["Das ist euer Auto."] },
      { type: "order", prompt: "Склади:", words: ["Lehrer","ist","Unser","nett"], correct: ["Unser","Lehrer","ist","nett"] },
      { type: "translate", prompt: "Переклади:", uk: "Ваші діти милі.", de: ["Eure Kinder sind nett."] },
      { type: "writeFree", prompt: "Напиши 3 речення з unser/euer.", sample: "Unser Haus ist groß. Unsere Schule ist neu. Eure Eltern sind nett.", explain: "Перевір -e- у euer." },
    ],
  },

  // 8 ===================================================================
  "reflexiv-mich-dich": {
    lesson: {
      slug: "reflexiv-mich-dich", level: "A1", category: CAT,
      titleDe: "Reflexivpronomen: mich und dich",
      titleUk: "Зворотні mich і dich",
      goal: "Знати, що рефлексивні mich/dich у 1 і 2 особі однини збігаються з Akk. особових займенників.",
      explanation: [
        "Зворотні займенники Akk. для 1 і 2 особи однини: <b>mich</b> (себе для ich), <b>dich</b> (себе для du).",
        "Збігаються з Akk. форм особових: «бачу мене» = <i>mich</i>; «миє себе» (для du) = <i>dich</i>.",
        "Часті дієслова: <b>sich freuen, sich waschen, sich anziehen, sich beeilen, sich setzen</b>.",
        "Займенник стоїть одразу після відмінюваного дієслова.",
      ],
      table: {
        headers: ["Особа", "Reflexiv (Akk.)", "Приклад"],
        rows: [
          ["ich", "mich", "Ich freue mich."],
          ["du", "dich", "Du wäschst dich."],
        ],
      },
      examples: [
        { de: "Ich freue mich auf das Wochenende.", uk: "Я тішуся вихідним." },
        { de: "Du wäschst dich.", uk: "Ти миєшся." },
        { de: "Ich beeile mich.", uk: "Я поспішаю." },
        { de: "Du ziehst dich an.", uk: "Ти вдягаєшся." },
        { de: "Ich setze mich an den Tisch.", uk: "Я сідаю за стіл." },
        { de: "Du entschuldigst dich.", uk: "Ти перепрошуєш." },
        { de: "Ich interessiere mich für Musik.", uk: "Я цікавлюся музикою." },
        { de: "Wie fühlst du dich?", uk: "Як ти почуваєшся?" },
      ],
      tip: "Для 1 і 2 ос. одн. <b>немає окремої</b> рефлексивної форми — використовуємо ту саму, що й Akk. особового.",
      mistakes: [
        { wrong: "Ich freue mir.", right: "Ich freue mich." },
        { wrong: "Du wäschst sich.", right: "Du wäschst dich." },
        { wrong: "Ich freue dich.", right: "Ich freue mich." },
      ],
      exercises: {},
      prevSlug: "possessiv-unser-euer",
      nextSlug: "reflexiv-sich",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "уживати mich/dich як рефлексивні",
        "не плутати з особовими в інших значеннях",
        "ставити одразу після дієслова",
        "знати ключові A1 рефлексивні дієслова",
      ],
      ruleBox: {
        rule: "1 ос. одн. → <b>mich</b>. 2 ос. одн. → <b>dich</b>. Збігаються з Akk. особових.",
      },
      ukrainianTips: [
        "Українському «-ся» (миюся, тішуся) відповідає <b>mich/dich</b> після дієслова.",
        "У німецькій займенник <b>окремо</b> від дієслова.",
        "Не казати «ich freue mir» — Akk., не Dat.",
      ],
      languageComparison: {
        commons: ["Зворотність є."],
        diffs: ["У німецькій — окремий займенник."],
        traps: ["mir vs mich."],
      },
      summary: [
        "ich → mich.",
        "du → dich.",
        "Одразу після дієслова.",
        "Akk., не Dat.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich freue ___ .", options: ["mir","mich","sich","mein"], correct: 1 },
      { type: "mc", q: "Du wäschst ___ .", options: ["dir","dich","sich","dein"], correct: 1 },
      { type: "mc", q: "Ich beeile ___ .", options: ["mich","mir","sich","dich"], correct: 0 },
      { type: "mc", q: "Du ziehst ___ an.", options: ["dich","dir","sich","mich"], correct: 0 },
      { type: "gap", q: "Ich setze ___ . (1 ос.)", answer: "mich" },
      { type: "gap", q: "Du entschuldigst ___ . (2 ос.)", answer: "dich" },
      { type: "gap", q: "Ich interessiere ___ für Musik.", answer: "mich" },
      { type: "tf", q: "«ich freue mir» — правильна форма.", correct: false, explain: "mich, бо Akk." },
      { type: "tf", q: "У 2 ос. одн. рефлексив — dich.", correct: true },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "ich freue", right: "mich" },
        { left: "du wäschst", right: "dich" },
        { left: "ich setze", right: "mich" },
        { left: "du beeilst", right: "dich" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich freue mich.",
        "Ich freue mir.",
        "Du wäschst dich.",
        "Du wäschst sich.",
      ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Du beeilst sich.", correct: ["Du beeilst dich."] },
      { type: "order", prompt: "Склади:", words: ["mich","Ich","freue"], correct: ["Ich","freue","mich"] },
      { type: "translate", prompt: "Переклади:", uk: "Я тішуся.", de: ["Ich freue mich."] },
      { type: "writeFree", prompt: "Напиши 3 речення з mich/dich.", sample: "Ich wasche mich. Du ziehst dich an. Ich freue mich auf den Urlaub.", explain: "Перевір форму." },
    ],
  },

  // 9 ===================================================================
  "reflexiv-sich": {
    lesson: {
      slug: "reflexiv-sich", level: "A1", category: CAT,
      titleDe: "Reflexivpronomen: sich",
      titleUk: "Рефлексивне sich",
      goal: "Уживати <b>sich</b> для 3 особи (er/sie/es/sie Pl./Sie).",
      explanation: [
        "<b>sich</b> — це універсальна рефлексивна форма для 3 особи однини й множини, а також ввічливого Sie.",
        "Не плутати: «sich» <b>не</b> змінюється — одне слово для всіх трьох родів і числа: <i>er freut sich, sie freut sich, es freut sich, sie (Pl.) freuen sich</i>.",
        "Для ввічливого Sie теж <b>sich</b>: <i>Setzen Sie sich, bitte!</i>",
        "Для wir / ihr використовують <b>uns / euch</b> (як Akk. особових).",
      ],
      table: {
        headers: ["Особа", "Рефлексив"],
        rows: [
          ["ich", "mich"],
          ["du", "dich"],
          ["er/sie/es", "sich"],
          ["wir", "uns"],
          ["ihr", "euch"],
          ["sie / Sie", "sich"],
        ],
      },
      examples: [
        { de: "Er freut sich auf das Wochenende.", uk: "Він тішиться вихідним." },
        { de: "Sie wäscht sich.", uk: "Вона миється." },
        { de: "Das Kind setzt sich.", uk: "Дитина сідає." },
        { de: "Wir treffen uns im Park.", uk: "Ми зустрічаємось у парку." },
        { de: "Ihr beeilt euch.", uk: "Ви поспішаєте." },
        { de: "Sie interessieren sich für Kunst.", uk: "Вони цікавляться мистецтвом." },
        { de: "Setzen Sie sich, bitte!", uk: "Сідайте, будь ласка." },
        { de: "Er entschuldigt sich.", uk: "Він перепрошує." },
      ],
      tip: "<b>sich</b> — найважливіша форма. Запам'ятай: <b>er/sie/es/sie/Sie → sich</b>.",
      mistakes: [
        { wrong: "Er freut ihn.", right: "Er freut sich." },
        { wrong: "Sie wäscht ihre.", right: "Sie wäscht sich." },
        { wrong: "Wir treffen sich.", right: "Wir treffen uns." },
      ],
      exercises: {},
      prevSlug: "reflexiv-mich-dich",
      nextSlug: "man-pronomen",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "уживати sich для 3 особи",
        "знати uns / euch для wir / ihr",
        "не плутати sich з ihn/sie/ihre",
        "ввічливо: Setzen Sie sich!",
      ],
      ruleBox: {
        rule: "<b>sich</b> для er/sie/es/sie/Sie. Для wir → <b>uns</b>; для ihr → <b>euch</b>.",
      },
      ukrainianTips: [
        "Українське «миється/тішиться» = <b>sich</b> (для er/sie/es).",
        "Для «миємось/тішимось» = <b>uns</b>; «миєтесь» — <b>euch</b>.",
        "<b>sich</b> ніколи не змінюється — це найпростіша частина системи.",
      ],
      languageComparison: {
        commons: ["Дія на себе."],
        diffs: ["У німецькій sich — окреме слово для всієї 3 особи."],
        traps: ["sich ↔ ihn / sie / es як особові."],
      },
      summary: [
        "er/sie/es → <b>sich</b>.",
        "sie/Sie → <b>sich</b>.",
        "wir → <b>uns</b>, ihr → <b>euch</b>.",
        "sich не змінюється.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Er freut ___ .", options: ["ihn","sich","sie","es"], correct: 1 },
      { type: "mc", q: "Sie wäscht ___ . (вона)", options: ["ihre","sich","sie","ihr"], correct: 1 },
      { type: "mc", q: "Wir treffen ___ im Park.", options: ["sich","uns","wir","euch"], correct: 1 },
      { type: "mc", q: "Ihr beeilt ___ .", options: ["sich","uns","euch","ihr"], correct: 2 },
      { type: "gap", q: "Das Kind setzt ___ .", answer: "sich" },
      { type: "gap", q: "Sie (Pl.) interessieren ___ für Sport.", answer: "sich" },
      { type: "gap", q: "Setzen Sie ___, bitte!", answer: "sich" },
      { type: "tf", q: "Для er/sie/es — завжди sich.", correct: true },
      { type: "tf", q: "Для wir рефлексив — sich.", correct: false, explain: "uns." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "er", right: "sich" },
        { left: "wir", right: "uns" },
        { left: "ihr", right: "euch" },
        { left: "Sie (ввічл.)", right: "sich" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Er freut sich.",
        "Er freut ihn.",
        "Wir treffen sich.",
        "Wir treffen uns.",
      ], correct: [0,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Sie wäscht ihre.", correct: ["Sie wäscht sich."] },
      { type: "order", prompt: "Склади:", words: ["sich","Er","freut"], correct: ["Er","freut","sich"] },
      { type: "translate", prompt: "Переклади:", uk: "Сідайте, будь ласка.", de: ["Setzen Sie sich, bitte."] },
      { type: "writeFree", prompt: "Напиши 3 речення з sich/uns/euch.", sample: "Er freut sich. Wir treffen uns. Ihr beeilt euch.", explain: "Перевір рефлексив за особою." },
    ],
  },

  // 10 ===================================================================
  "man-pronomen": {
    lesson: {
      slug: "man-pronomen", level: "A1", category: CAT,
      titleDe: "man", titleUk: "man — неозначено-особовий займенник",
      goal: "Уживати <b>man</b> для загальних висловлювань («говорять, що…», «тут не можна…»).",
      explanation: [
        "<b>man</b> = неозначена особа, ≈ українське «хтось / люди / тут можна / тут говорять».",
        "Завжди з <b>3 особою однини</b> дієслова: <i>man sagt, man kann, man darf, man isst</i>.",
        "Пишеться <b>з малої</b>. Не плутай з іменником <b>der Mann</b> (чоловік, з великої й з подвоєним n).",
        "Часто з модальними дієсловами: <i>Hier darf man nicht rauchen.</i> = «Тут не можна курити.»",
      ],
      table: {
        headers: ["Приклад", "Переклад"],
        rows: [
          ["Man sagt …", "Кажуть…"],
          ["Man kann …", "Можна…"],
          ["Man darf …", "Дозволено…"],
          ["Man muss …", "Треба…"],
          ["Hier isst man Pizza.", "Тут їдять піцу."],
          ["Hier spricht man Deutsch.", "Тут розмовляють німецькою."],
        ],
      },
      examples: [
        { de: "Hier spricht man Deutsch.", uk: "Тут розмовляють німецькою." },
        { de: "Man darf hier nicht rauchen.", uk: "Тут не можна курити." },
        { de: "Was isst man in Deutschland?", uk: "Що їдять у Німеччині?" },
        { de: "Man muss viel lernen.", uk: "Треба багато вчитися." },
        { de: "Man kann hier gut Kaffee trinken.", uk: "Тут можна випити доброї кави." },
        { de: "Man sagt, das Wetter wird besser.", uk: "Кажуть, погода покращиться." },
        { de: "In Italien isst man viel Pasta.", uk: "В Італії їдять багато пасти." },
        { de: "Wie schreibt man dieses Wort?", uk: "Як пишеться це слово?" },
      ],
      tip: "<b>man</b> економить речення: замість «<i>люди в Італії їдять пасту</i>» — просто <i>In Italien isst <b>man</b> Pasta.</i>",
      mistakes: [
        { wrong: "Hier spricht Mann Deutsch.", right: "Hier spricht man Deutsch." },
        { wrong: "Man sind sehr nett.", right: "Man ist sehr nett." },
        { wrong: "Man dürfen hier nicht parken.", right: "Man darf hier nicht parken." },
      ],
      exercises: {},
      prevSlug: "reflexiv-sich",
      nextSlug: "das-als-pronomen",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "уживати man для загальних висловлювань",
        "узгоджувати з 3 ос. одн.",
        "не плутати man і Mann",
        "будувати правила/таблички",
      ],
      ruleBox: {
        rule: "<b>man</b> + дієслово в 3 ос. одн. Не плутати з <b>der Mann</b> (чоловік).",
        examples: [
          { de: "Man darf hier nicht rauchen.", uk: "Тут не можна курити." },
        ],
      },
      ukrainianTips: [
        "В українській такого займенника немає — ми кажемо «люди / тут / кажуть». У німецькій є <b>man</b>.",
        "Дієслово після man — <b>як після er/sie/es</b>: <i>man kann, man darf, man muss</i>.",
        "<b>man</b> з малої — це займенник. <b>Mann</b> з великої — чоловік.",
      ],
      languageComparison: {
        commons: ["Узагальнення є й там, і там."],
        diffs: ["У німецькій — окремий короткий займенник."],
        traps: ["man ↔ Mann."],
      },
      summary: [
        "man = неозначена особа.",
        "+ 3 ос. одн.",
        "З малої.",
        "Часто з модальними.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Hier ___ man Deutsch.", options: ["spreche","sprichst","spricht","sprechen"], correct: 2 },
      { type: "mc", q: "___ darf hier nicht rauchen.", options: ["Mann","Man","Mein","Mir"], correct: 1 },
      { type: "mc", q: "In Italien isst ___ viel Pasta.", options: ["man","Mann","mir","mich"], correct: 0 },
      { type: "mc", q: "Wie schreibt ___ dieses Wort?", options: ["Mann","man","mir","mich"], correct: 1 },
      { type: "gap", q: "Hier ___ man Pizza essen. (kann)", answer: "kann" },
      { type: "gap", q: "Man ___ viel lernen. (müssen)", answer: "muss" },
      { type: "gap", q: "Man ___ höflich sein. (sollen)", answer: "soll" },
      { type: "tf", q: "Після man дієслово в 3 ос. одн.", correct: true },
      { type: "tf", q: "«Man» пишеться з великої.", correct: false, explain: "З малої — це займенник." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "man sagt", right: "кажуть" },
        { left: "man kann", right: "можна" },
        { left: "man darf", right: "дозволено" },
        { left: "man muss", right: "треба" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Hier spricht man Deutsch.",
        "Hier sprechen man Deutsch.",
        "Man darf hier nicht rauchen.",
        "Man dürfen hier nicht rauchen.",
      ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Man sind sehr nett.", correct: ["Man ist sehr nett."] },
      { type: "order", prompt: "Склади:", words: ["man","Hier","Pizza","isst"], correct: ["Hier","isst","man","Pizza"] },
      { type: "translate", prompt: "Переклади:", uk: "Тут не можна паркуватися.", de: ["Hier darf man nicht parken."] },
      { type: "writeFree", prompt: "Напиши 3 загальних правила з man.", sample: "Hier darf man nicht rauchen. Man muss viel lernen. In Deutschland isst man viel Brot.", explain: "Перевір 3 ос. одн." },
    ],
  },

  // 11 ===================================================================
  "das-als-pronomen": {
    lesson: {
      slug: "das-als-pronomen", level: "A1", category: CAT,
      titleDe: "das als Pronomen", titleUk: "das як вказівний займенник",
      goal: "Уживати <b>das</b> як універсальне «це» для представлення речей або фактів.",
      explanation: [
        "<b>das</b> може бути не лише артиклем, а й <b>вказівним займенником</b>: «це / то».",
        "Часто на початку речення: <i>Das ist mein Bruder. Das sind meine Eltern.</i>",
        "<b>das</b> не змінюється за родом і числом: <i>Das ist <b>der</b> Mann. Das ist <b>die</b> Frau. Das sind <b>die</b> Kinder.</i>",
        "З однією річчю → <b>das ist</b>; з кількома → <b>das sind</b>.",
      ],
      table: {
        headers: ["Приклад", "Переклад"],
        rows: [
          ["Das ist mein Bruder.", "Це мій брат."],
          ["Das ist meine Schwester.", "Це моя сестра."],
          ["Das ist mein Auto.", "Це мій автомобіль."],
          ["Das sind meine Eltern.", "Це мої батьки."],
          ["Das ist interessant.", "Це цікаво."],
          ["Was ist das?", "Що це?"],
        ],
      },
      examples: [
        { de: "Das ist Anna.", uk: "Це Анна." },
        { de: "Das sind meine Freunde.", uk: "Це мої друзі." },
        { de: "Das ist mein Hund.", uk: "Це мій пес." },
        { de: "Was ist das?", uk: "Що це?" },
        { de: "Das ist falsch.", uk: "Це неправильно." },
        { de: "Das ist eine gute Idee.", uk: "Це хороша ідея." },
        { de: "Das sind die Kinder von Anna.", uk: "Це діти Анни." },
        { de: "Das ist alles.", uk: "Це все." },
      ],
      tip: "<b>das</b> на початку речення = українське <b>це</b>. Не плутай: коли <b>das</b> після іменника — це артикль.",
      mistakes: [
        { wrong: "Das sind mein Bruder.", right: "Das ist mein Bruder." },
        { wrong: "Die sind meine Eltern.", right: "Das sind meine Eltern." },
        { wrong: "Das ist meine Freunde.", right: "Das sind meine Freunde." },
      ],
      exercises: {},
      prevSlug: "man-pronomen",
      nextSlug: "wer-was-wen",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "уживати das як «це»",
        "вибирати ist / sind за числом",
        "знайомити людей через «Das ist…»",
        "ставити загальні запитання «Was ist das?»",
      ],
      ruleBox: {
        rule: "<b>das ist</b> — для одного. <b>das sind</b> — для кількох. <b>das</b> не міняється за родом.",
      },
      ukrainianTips: [
        "Українському «це» завжди відповідає <b>das</b>, незалежно від роду наступного слова.",
        "Дієслово вибираємо за <b>числом</b>: один → ist, кілька → sind.",
        "Це найзручніший спосіб <b>представити людину</b>: <i>Das ist mein Vater.</i>",
      ],
      languageComparison: {
        commons: ["«Це» універсальне для будь-якого роду."],
        diffs: ["У німецькій ми вибираємо ist/sind за числом."],
        traps: ["«Das ist meine Freunde» — типова помилка."],
      },
      summary: [
        "<b>das</b> = «це».",
        "ist (1 річ) / sind (кілька).",
        "Не змінюється за родом.",
        "Часто на початку речення.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ ist mein Bruder.", options: ["Der","Die","Das","Den"], correct: 2 },
      { type: "mc", q: "___ sind meine Eltern.", options: ["Der","Die","Das","Den"], correct: 2 },
      { type: "mc", q: "___ ist meine Schwester.", options: ["Der","Die","Das","Den"], correct: 2 },
      { type: "mc", q: "___ ist das?", options: ["Wer","Was","Wann","Wie"], correct: 1 },
      { type: "gap", q: "Das ___ meine Freunde.", answer: "sind" },
      { type: "gap", q: "Das ___ mein Hund.", answer: "ist" },
      { type: "gap", q: "___ ist alles.", answer: "Das" },
      { type: "tf", q: "Das не змінюється за родом.", correct: true },
      { type: "tf", q: "«Das sind mein Bruder» — правильно.", correct: false, explain: "Das ist mein Bruder." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Das ist", right: "1 річ" },
        { left: "Das sind", right: "кілька" },
        { left: "Was ist das?", right: "що це?" },
        { left: "Das ist alles", right: "це все" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Das ist meine Schwester.",
        "Die sind meine Freunde.",
        "Das sind meine Freunde.",
        "Das ist meine Eltern.",
      ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Das ist meine Freunde.", correct: ["Das sind meine Freunde."] },
      { type: "order", prompt: "Склади:", words: ["mein","Das","ist","Bruder"], correct: ["Das","ist","mein","Bruder"] },
      { type: "translate", prompt: "Переклади:", uk: "Це мої батьки.", de: ["Das sind meine Eltern."] },
      { type: "writeFree", prompt: "Напиши 3 «Das ist / sind …»-речення про родину/друзів.", sample: "Das ist mein Vater. Das ist meine Schwester. Das sind meine Freunde.", explain: "Перевір ist/sind." },
    ],
  },

  // 12 ===================================================================
  "wer-was-wen": {
    lesson: {
      slug: "wer-was-wen", level: "A1", category: CAT,
      titleDe: "Wer? Was? Wen?", titleUk: "Питальні займенники Wer? Was? Wen?",
      goal: "Розрізняти 3 ключові питальні займенники й вибирати правильний за відмінком.",
      explanation: [
        "<b>Wer?</b> = «Хто?» — для людей у Nominativ. <i>Wer ist das? — Das ist Anna.</i>",
        "<b>Was?</b> = «Що?» — для речей. Працює і в Nom., і в Akk. <i>Was ist das? Was machst du?</i>",
        "<b>Wen?</b> = «Кого?» — для людей у Akkusativ. <i>Wen siehst du? — Ich sehe den Mann.</i>",
        "Wer/Wen — для людей. Was — для речей у будь-якому з цих двох відмінків.",
      ],
      table: {
        headers: ["Питальний", "Значення", "Приклад"],
        rows: [
          ["Wer?", "Хто? (Nom.)", "Wer kommt heute?"],
          ["Was?", "Що? (Nom./Akk.)", "Was ist das? Was kaufst du?"],
          ["Wen?", "Кого? (Akk., люди)", "Wen siehst du?"],
        ],
      },
      examples: [
        { de: "Wer ist das?", uk: "Хто це?" },
        { de: "Was ist das?", uk: "Що це?" },
        { de: "Wen siehst du?", uk: "Кого ти бачиш?" },
        { de: "Wer arbeitet hier?", uk: "Хто тут працює?" },
        { de: "Was machst du am Wochenende?", uk: "Що ти робиш на вихідних?" },
        { de: "Wen besuchst du heute?", uk: "Кого ти сьогодні навідаєш?" },
        { de: "Wer hat Hunger?", uk: "Хто голодний?" },
        { de: "Was trinkst du?", uk: "Що ти п'єш?" },
      ],
      tip: "Запам'ятай <b>пару</b>: <b>der → wer</b> (Nom.), <b>den → wen</b> (Akk.). Закінчення -en підказує Akk.",
      mistakes: [
        { wrong: "Wer siehst du?", right: "Wen siehst du?" },
        { wrong: "Wen ist das?", right: "Wer ist das?" },
        { wrong: "Was siehst du den Mann?", right: "Wen siehst du? — Den Mann.", },
      ],
      exercises: {},
      prevSlug: "das-als-pronomen",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "відрізняти Wer / Was / Wen",
        "будувати запитання за відмінком",
        "відповідати повним реченням",
        "автоматично казати Wen для Akk.",
      ],
      ruleBox: {
        rule: "<b>Wer?</b> — Nom. люди. <b>Was?</b> — речі. <b>Wen?</b> — Akk. люди.",
      },
      ukrainianTips: [
        "Українське «хто» = <b>Wer</b>; «кого» = <b>Wen</b>; «що» = <b>Was</b>.",
        "У німецькій Wen потрібен, коли в реченні є дієслово з Akk. (sehen, lieben, kennen, besuchen).",
        "Was не змінюється за відмінком — лише за контекстом.",
      ],
      languageComparison: {
        commons: ["3 базові питання."],
        diffs: ["Wer / Wen відрізняються формально."],
        traps: ["«Wer siehst du?» — типова помилка (правильно Wen)."],
      },
      summary: [
        "Wer? — Nom., люди.",
        "Was? — речі.",
        "Wen? — Akk., люди.",
        "der ↔ wer; den ↔ wen.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ ist das? — Das ist Anna.", options: ["Wer","Was","Wen","Wie"], correct: 0 },
      { type: "mc", q: "___ ist das? — Das ist ein Buch.", options: ["Wer","Was","Wen","Wo"], correct: 1 },
      { type: "mc", q: "___ siehst du?", options: ["Wer","Was","Wen","Wie"], correct: 2, explain: "sehen + Akk → Wen." },
      { type: "mc", q: "___ kommt heute?", options: ["Wer","Was","Wen","Wo"], correct: 0 },
      { type: "gap", q: "___ besuchst du? (кого)", answer: "Wen" },
      { type: "gap", q: "___ machst du? (що)", answer: "Was" },
      { type: "gap", q: "___ ist dein Lehrer? (хто)", answer: "Wer" },
      { type: "tf", q: "Wen — це Akk. для людей.", correct: true },
      { type: "tf", q: "Was змінюється за відмінком.", correct: false, explain: "Не змінюється." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Wer", right: "Nom., люди" },
        { left: "Was", right: "речі" },
        { left: "Wen", right: "Akk., люди" },
        { left: "den", right: "Akk. m" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Wer siehst du?",
        "Wen siehst du?",
        "Wen ist das?",
        "Wer ist das?",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Wer siehst du?", correct: ["Wen siehst du?"] },
      { type: "order", prompt: "Склади:", words: ["siehst","Wen","heute","du"], correct: ["Wen","siehst","du","heute"] },
      { type: "translate", prompt: "Переклади:", uk: "Кого ти любиш?", de: ["Wen liebst du?"] },
      { type: "writeFree", prompt: "Напиши 3 запитання: одне з Wer, одне з Was, одне з Wen.", sample: "Wer ist das? Was machst du? Wen besuchst du morgen?", explain: "Перевір відмінок." },
    ],
  },
};
