// A1 · Іменники — 14 повних уроків.
import type { A1Map } from "./_helpers";

const CAT = "Іменники";

export const substantiveA1: A1Map = {
  // 1 ===================================================================
  "genus-substantive": {
    lesson: {
      slug: "genus-substantive", level: "A1", category: CAT,
      titleDe: "Genus der Substantive", titleUk: "Рід іменників",
      goal: "Зрозуміти, що в німецькій кожен іменник має рід і його обов'язково вчити разом з артиклем.",
      explanation: [
        "Кожен німецький іменник має <b>граматичний рід</b>: чоловічий (der), жіночий (die) або середній (das).",
        "Рід не завжди збігається з логікою чи з українською мовою: <b>das Mädchen</b> (дівчинка) — середній рід!",
        "Тому слово завжди вчи <b>разом з артиклем</b>: не «Tisch», а <b>der Tisch</b>.",
        "Є кілька корисних правил-підказок за закінченням і темою, але винятків багато — артикль слід запам'ятовувати.",
      ],
      table: {
        headers: ["Рід", "Артикль", "Приклад", "Переклад"],
        rows: [
          ["чоловічий", "der", "der Mann", "чоловік"],
          ["жіночий", "die", "die Frau", "жінка"],
          ["середній", "das", "das Kind", "дитина"],
          ["середній", "das", "das Mädchen", "дівчинка"],
          ["чоловічий", "der", "der Tisch", "стіл"],
          ["жіночий", "die", "die Lampe", "лампа"],
        ],
      },
      examples: [
        { de: "Der Tisch ist groß.", uk: "Стіл великий." },
        { de: "Die Lampe ist neu.", uk: "Лампа нова." },
        { de: "Das Buch liegt hier.", uk: "Книга лежить тут." },
        { de: "Der Mann arbeitet viel.", uk: "Чоловік багато працює." },
        { de: "Die Frau heißt Anna.", uk: "Жінку звати Анна." },
        { de: "Das Kind spielt im Garten.", uk: "Дитина грається в саду." },
        { de: "Das Mädchen liest ein Buch.", uk: "Дівчинка читає книгу.", tag: "das, не die!" },
        { de: "Der Kaffee ist heiß.", uk: "Кава гаряча.", tag: "der, не die!" },
      ],
      tip: "Слово <b>завжди</b> вивчай з артиклем: <i>der Tisch, die Lampe, das Buch</i>. Без артикля слово «не повне».",
      mistakes: [
        { wrong: "Die Mädchen ist nett.", right: "Das Mädchen ist nett." },
        { wrong: "Die Kaffee ist heiß.", right: "Der Kaffee ist heiß." },
        { wrong: "Das Lampe ist neu.", right: "Die Lampe ist neu." },
      ],
      exercises: {},
      nextSlug: "mask-fem-neut",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати 3 артиклі der/die/das",
        "розуміти, що рід — граматична категорія, не «логіка»",
        "вчити нові слова разом з артиклем",
        "розпізнавати рід знайомих A1 слів",
      ],
      ruleBox: {
        rule: "У німецькій 3 роди: <b>der</b> (m), <b>die</b> (f), <b>das</b> (n). Артикль — це частина слова, його завжди потрібно вчити разом.",
        examples: [
          { de: "der Tisch, die Lampe, das Buch", uk: "стіл, лампа, книга" },
        ],
      },
      ukrainianTips: [
        "Українські й німецькі роди часто <b>не збігаються</b>: <i>книга</i> — ж., але <i>das Buch</i> — с.",
        "<b>das Mädchen</b> — середній рід, бо є зменшувальний суфікс -chen.",
        "Не намагайся вгадати рід — вчи кожне слово з артиклем, наприклад через картку <i>der Tisch</i>.",
      ],
      languageComparison: {
        commons: ["Поняття роду існує і в українській."],
        diffs: ["У німецькій рід часто не збігається з українським."],
        traps: ["Кальки з української → артикль може бути не той."],
      },
      summary: [
        "Три артиклі: <b>der, die, das</b>.",
        "Артикль = частина слова.",
        "Рід може не збігатися з українським.",
        "Усі слова з -chen/-lein → <b>das</b>.",
        "Вчи карткою «артикль + слово».",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Mann ist Lehrer.", options: ["Der","Die","Das","Den"], correct: 0 },
      { type: "mc", q: "___ Frau heißt Anna.", options: ["Der","Die","Das","Den"], correct: 1 },
      { type: "mc", q: "___ Kind spielt.", options: ["Der","Die","Das","Den"], correct: 2 },
      { type: "mc", q: "___ Mädchen liest.", options: ["Der","Die","Das","Den"], correct: 2, explain: "-chen → das." },
      { type: "gap", q: "Артикль до «Tisch» — ___ .", answer: "der" },
      { type: "gap", q: "Артикль до «Lampe» — ___ .", answer: "die" },
      { type: "gap", q: "Артикль до «Buch» — ___ .", answer: "das" },
      { type: "tf", q: "У німецькій є 3 граматичні роди.", correct: true },
      { type: "tf", q: "Рід німецького іменника завжди такий, як в українській.", correct: false },
      { type: "match", prompt: "Зістав слово й артикль:", pairs: [
        { left: "Mann", right: "der" },
        { left: "Frau", right: "die" },
        { left: "Kind", right: "das" },
        { left: "Tisch", right: "der" },
      ]},
      { type: "multi", q: "Виділи всі іменники жіночого роду:", options: ["Mann","Frau","Lampe","Buch","Tisch","Tasche"], correct: [1,2,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Die Mädchen spielt.", correct: ["Das Mädchen spielt."] },
      { type: "order", prompt: "Склади речення:", words: ["groß","Tisch","Der","ist"], correct: ["Der","Tisch","ist","groß"] },
      { type: "translate", prompt: "Переклади:", uk: "Книга нова.", de: ["Das Buch ist neu."] },
      { type: "writeFree", prompt: "Напиши 3 речення з трьома різними родами (der/die/das).", sample: "Der Tisch ist alt. Die Lampe ist neu. Das Kind ist klein.", explain: "Перевір артиклі." },
    ],
  },

  // 2 ===================================================================
  "mask-fem-neut": {
    lesson: {
      slug: "mask-fem-neut", level: "A1", category: CAT,
      titleDe: "Maskulinum, Femininum, Neutrum",
      titleUk: "Чоловічий, жіночий і середній рід",
      goal: "Розрізняти три роди й знати підказки для вгадування за змістом і закінченням.",
      explanation: [
        "<b>Maskulinum (der)</b>: чоловіки за статтю, дні, місяці, пори року, погодні явища, алкогольні напої: <i>der Mann, der Montag, der Januar, der Sommer, der Regen, der Wein</i>.",
        "<b>Femininum (die)</b>: жінки за статтю, більшість дерев і квітів, числа: <i>die Frau, die Rose, die Eins</i>. Закінчення -ung, -heit, -keit, -schaft, -tion, -ie, -ik → <b>завжди die</b>.",
        "<b>Neutrum (das)</b>: малі істоти й речі (-chen, -lein), молоді тварини, метали, кольори як іменники: <i>das Kind, das Gold, das Rot</i>.",
        "Ці правила покривають ~70% слів. Решту вчи з артиклем.",
      ],
      table: {
        headers: ["Рід", "Типова тема / закінчення", "Приклади"],
        rows: [
          ["der", "чоловіки, дні, місяці, погода", "der Mann, der Montag, der Mai, der Wind"],
          ["die", "жінки; -ung, -heit, -keit, -tion", "die Frau, die Wohnung, die Freiheit, die Information"],
          ["das", "-chen, -lein, малі речі, метали", "das Mädchen, das Brötchen, das Gold"],
        ],
      },
      examples: [
        { de: "Der Montag ist mein Lieblingstag.", uk: "Понеділок — мій улюблений день." },
        { de: "Die Wohnung ist klein.", uk: "Квартира маленька.", tag: "-ung → die" },
        { de: "Das Brötchen schmeckt gut.", uk: "Булочка смачна.", tag: "-chen → das" },
        { de: "Der Januar ist kalt.", uk: "Січень холодний." },
        { de: "Die Information ist neu.", uk: "Інформація нова.", tag: "-tion → die" },
        { de: "Das Mädchen lernt Deutsch.", uk: "Дівчинка вчить німецьку." },
        { de: "Der Wein ist aus Italien.", uk: "Вино з Італії." },
        { de: "Die Möglichkeit ist interessant.", uk: "Можливість цікава.", tag: "-keit → die" },
      ],
      tip: "Запам'ятай 4 «суперзакінчення жіночого роду»: <b>-ung, -heit, -keit, -tion</b>. Вони <b>завжди</b> вимагають <b>die</b>.",
      mistakes: [
        { wrong: "Das Wohnung ist groß.", right: "Die Wohnung ist groß." },
        { wrong: "Die Brötchen schmeckt.", right: "Das Brötchen schmeckt." },
        { wrong: "Die Montag ist frei.", right: "Der Montag ist frei." },
      ],
      exercises: {},
      prevSlug: "genus-substantive",
      nextSlug: "artikel-genus",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати теми та закінчення для кожного роду",
        "автоматично визначати рід за -ung/-heit/-keit/-tion → die",
        "впізнавати -chen/-lein → das",
        "розпізнавати дні й місяці як der",
      ],
      ruleBox: {
        rule: "<b>der</b>: чоловіки, дні, місяці, пори року, погода. <b>die</b>: жінки; -ung, -heit, -keit, -schaft, -tion. <b>das</b>: -chen, -lein, метали, кольори.",
        examples: [
          { de: "der Sommer", uk: "літо (пора року → der)" },
          { de: "die Zeitung", uk: "газета (-ung → die)" },
          { de: "das Mädchen", uk: "дівчинка (-chen → das)" },
        ],
      },
      ukrainianTips: [
        "Українські й німецькі роди для тих самих слів часто різні — не покладайся на «звучить як жіночий».",
        "Слова на <b>-tion, -tät, -ie, -ik</b> запозичені з латини й завжди <b>die</b>.",
        "Пора року «зима/весна/літо/осінь» — усі чоловічого роду: <b>der Winter, der Frühling, der Sommer, der Herbst</b>.",
      ],
      languageComparison: {
        commons: ["Поняття трьох родів існує і там, і там."],
        diffs: ["Закінчення-підказки в німецькій інші."],
        traps: ["«die Brötchen» — типова помилка: правильно das."],
      },
      summary: [
        "Дні, місяці, пори року, погода → <b>der</b>.",
        "-ung, -heit, -keit, -tion → <b>die</b>.",
        "-chen, -lein → <b>das</b>.",
        "Молоді істоти, метали → <b>das</b>.",
        "Правила покривають ~70% — решту вчи з артиклем.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Який артикль для «Wohnung»?", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Який артикль для «Montag»?", options: ["der","die","das","den"], correct: 0 },
      { type: "mc", q: "Який артикль для «Mädchen»?", options: ["der","die","das","den"], correct: 2 },
      { type: "mc", q: "Який артикль для «Information»?", options: ["der","die","das","den"], correct: 1 },
      { type: "gap", q: "___ Sommer ist heiß.", answer: "Der" },
      { type: "gap", q: "___ Freiheit ist wichtig.", answer: "Die" },
      { type: "gap", q: "___ Brötchen schmeckt gut.", answer: "Das" },
      { type: "tf", q: "Усі слова на -ung — жіночого роду.", correct: true },
      { type: "tf", q: "Місяці — жіночого роду.", correct: false, explain: "der: der Januar, der Mai." },
      { type: "match", prompt: "Зістав слово й рід:", pairs: [
        { left: "Wohnung", right: "die" },
        { left: "Mädchen", right: "das" },
        { left: "Mai", right: "der" },
        { left: "Möglichkeit", right: "die" },
      ]},
      { type: "multi", q: "Виділи всі слова, які точно мають артикль die:", options: ["Wohnung","Brötchen","Information","Mai","Freiheit","Tisch"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Wohnung ist neu.", correct: ["Die Wohnung ist neu."] },
      { type: "order", prompt: "Склади речення:", words: ["klein","Wohnung","Die","ist"], correct: ["Die","Wohnung","ist","klein"] },
      { type: "translate", prompt: "Переклади:", uk: "Інформація нова.", de: ["Die Information ist neu."] },
      { type: "writeFree", prompt: "Напиши по одному реченню для der/die/das, використовуючи правила.", sample: "Der Montag ist anstrengend. Die Wohnung ist hell. Das Mädchen spielt.", explain: "Перевір артиклі за правилами." },
    ],
  },

  // 3 ===================================================================
  "artikel-genus": {
    lesson: {
      slug: "artikel-genus", level: "A1", category: CAT,
      titleDe: "Artikel und Genus", titleUk: "Артикль і рід іменника",
      goal: "Зрозуміти, як артикль показує рід, і навчитися добирати правильний артикль до іменника.",
      explanation: [
        "Артикль — це маленьке слово перед іменником, яке показує його <b>рід, число й відмінок</b>.",
        "У німецькій <b>не можна</b> сказати просто «Tisch» — потрібен артикль: <b>der Tisch</b> (стіл).",
        "Артикль міняється залежно від відмінка: <i>der Mann (Nom.) → den Mann (Akk.)</i>. Але рід залишається той самий.",
        "У множині всі три роди мають один артикль <b>die</b>: <i>die Männer, die Frauen, die Kinder</i>.",
      ],
      table: {
        headers: ["Рід", "Озн. артикль (Nom.)", "Неозн. артикль", "Приклад"],
        rows: [
          ["m", "der", "ein", "der/ein Mann"],
          ["f", "die", "eine", "die/eine Frau"],
          ["n", "das", "ein", "das/ein Kind"],
          ["Pl.", "die", "—", "die Männer"],
        ],
      },
      examples: [
        { de: "Der Mann liest die Zeitung.", uk: "Чоловік читає газету." },
        { de: "Eine Frau wartet vor der Tür.", uk: "Жінка чекає перед дверима." },
        { de: "Das Kind hat ein Buch.", uk: "Дитина має книгу." },
        { de: "Die Kinder spielen draußen.", uk: "Діти граються надворі.", tag: "Plural" },
        { de: "Ich kaufe einen Apfel.", uk: "Я купую яблуко.", tag: "Akk. m → einen" },
        { de: "Die Lampe ist neu.", uk: "Лампа нова." },
        { de: "Hast du eine Schwester?", uk: "У тебе є сестра?" },
        { de: "Das ist mein Lehrer.", uk: "Це мій учитель." },
      ],
      tip: "Артикль і іменник — <b>єдине ціле</b>. Помилка в артиклі = помилка в роді = помилка у відмінку.",
      mistakes: [
        { wrong: "Ich kaufe Tisch.", right: "Ich kaufe einen Tisch." },
        { wrong: "Das Kinder spielen.", right: "Die Kinder spielen." },
        { wrong: "Eine Mann arbeitet.", right: "Ein Mann arbeitet." },
      ],
      exercises: {},
      prevSlug: "mask-fem-neut",
      nextSlug: "pluralbildung",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати означені й неозначені артиклі для всіх 3 родів",
        "розуміти, що артикль показує рід",
        "вживати die для всіх іменників у множині",
        "не пропускати артикль перед іменниками",
      ],
      ruleBox: {
        rule: "<b>der/ein</b> (m), <b>die/eine</b> (f), <b>das/ein</b> (n). У множині — завжди <b>die</b> (озн.).",
        examples: [
          { de: "der Mann · ein Mann", uk: "чоловік" },
          { de: "die Kinder", uk: "діти (множина — die)" },
        ],
      },
      ukrainianTips: [
        "В українській артиклів немає — і виникає велика спокуса їх пропустити. У німецькій артикль <b>обов'язковий</b>.",
        "Множина має <b>один</b> артикль для всіх родів: <b>die</b>.",
        "Неозначений артикль у множині <b>не вживається</b>: <i>Kinder spielen</i> (не <i>eine Kinder</i>).",
      ],
      languageComparison: {
        commons: ["Іменник має рід."],
        diffs: ["У німецькій рід «носить» артикль."],
        traps: ["Пропуск артикля сприймається як «зламана» німецька."],
      },
      summary: [
        "Артикль показує рід, число, відмінок.",
        "<b>der/die/das</b> — означені, <b>ein/eine/ein</b> — неозначені.",
        "Множина → <b>die</b>.",
        "У множині немає неозначеного артикля.",
        "Без артикля — лише імена власні й професії після sein.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ Mann liest.", options: ["Der","Die","Das","Ein"], correct: 0 },
      { type: "mc", q: "Ich habe ___ Schwester.", options: ["ein","eine","einen","das"], correct: 1 },
      { type: "mc", q: "___ Kinder spielen.", options: ["Der","Die","Das","Ein"], correct: 1, explain: "Plural → die." },
      { type: "mc", q: "Ich kaufe ___ Apfel.", options: ["ein","eine","einen","das"], correct: 2, explain: "Akk. m → einen." },
      { type: "gap", q: "___ Lampe ist neu. (озн., f)", answer: "Die" },
      { type: "gap", q: "Sie hat ___ Bruder. (неозн., m, Akk.)", answer: "einen" },
      { type: "gap", q: "___ Kind spielt. (озн., n)", answer: "Das" },
      { type: "tf", q: "У множині для всіх родів артикль — die.", correct: true },
      { type: "tf", q: "Неозначений артикль у множині — «eine».", correct: false, explain: "У множині немає неозначеного артикля." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "der", right: "Mann" },
        { left: "die", right: "Frau" },
        { left: "das", right: "Kind" },
        { left: "die (Pl.)", right: "Kinder" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich kaufe Apfel.",
        "Ich kaufe einen Apfel.",
        "Das Kinder spielen.",
        "Die Kinder spielen.",
      ], correct: [1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Kinder lernen.", correct: ["Die Kinder lernen."] },
      { type: "order", prompt: "Склади речення:", words: ["Buch","Das","neu","ist"], correct: ["Das","Buch","ist","neu"] },
      { type: "translate", prompt: "Переклади:", uk: "У мене є брат.", de: ["Ich habe einen Bruder."] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними артиклями (der/die/das).", sample: "Der Tisch ist groß. Die Tasche ist neu. Das Buch liegt hier.", explain: "Перевір артиклі." },
    ],
  },

  // 4 ===================================================================
  pluralbildung: {
    lesson: {
      slug: "pluralbildung", level: "A1", category: CAT,
      titleDe: "Pluralbildung", titleUk: "Утворення множини",
      goal: "Знати 5 основних типів утворення множини й уживати правильну форму.",
      explanation: [
        "У німецькій множина утворюється <b>п'ятьма способами</b>. Артикль у множині — завжди <b>die</b>.",
        "<b>-e</b>: der Tisch → die Tisch<b>e</b>. Часто з умляутом: der Stuhl → die St<b>ü</b>hle.",
        "<b>-(e)n</b>: die Frau → die Frau<b>en</b>, die Lampe → die Lampe<b>n</b>. Майже всі жіночі — на -en.",
        "<b>-er</b>: das Kind → die Kind<b>er</b>. Часто з умляутом: das Buch → die B<b>ü</b>cher.",
        "<b>-s</b>: das Auto → die Auto<b>s</b>. Так роблять запозичені слова.",
        "<b>0 (нуль)</b>: das Zimmer → die Zimmer. Інколи з умляутом: der Vater → die V<b>ä</b>ter.",
      ],
      table: {
        headers: ["Тип", "Однина", "Множина", "Переклад"],
        rows: [
          ["-e", "der Tisch", "die Tische", "столи"],
          ["-e + ¨", "der Stuhl", "die Stühle", "стільці"],
          ["-(e)n", "die Frau", "die Frauen", "жінки"],
          ["-(e)n", "die Lampe", "die Lampen", "лампи"],
          ["-er + ¨", "das Buch", "die Bücher", "книги"],
          ["-s", "das Auto", "die Autos", "автомобілі"],
          ["0", "das Zimmer", "die Zimmer", "кімнати"],
        ],
      },
      examples: [
        { de: "Ich habe zwei Brüder.", uk: "У мене два брати." },
        { de: "Die Kinder spielen draußen.", uk: "Діти граються надворі." },
        { de: "Wir kaufen drei Bücher.", uk: "Ми купуємо три книги." },
        { de: "Die Frauen arbeiten zusammen.", uk: "Жінки працюють разом." },
        { de: "Die Lampen sind teuer.", uk: "Лампи дорогі." },
        { de: "Wir haben zwei Autos.", uk: "У нас два автомобілі." },
        { de: "Die Zimmer sind klein.", uk: "Кімнати маленькі." },
        { de: "Die Eltern arbeiten viel.", uk: "Батьки багато працюють." },
      ],
      tip: "Учи слово одразу <b>з артиклем і множиною</b>: <i>der Tisch, die Tische</i> · <i>das Buch, die Bücher</i>.",
      mistakes: [
        { wrong: "Ich habe zwei Bruder.", right: "Ich habe zwei Brüder." },
        { wrong: "Die Buchs sind teuer.", right: "Die Bücher sind teuer." },
        { wrong: "Die Kindern spielen.", right: "Die Kinder spielen." },
      ],
      exercises: {},
      prevSlug: "artikel-genus",
      nextSlug: "singular-plural",
    },
    extras: {
      duration: 15, premium: false,
      learningGoals: [
        "розпізнавати 5 типів утворення множини",
        "пам'ятати, що артикль множини — завжди die",
        "вчити нові слова разом із множиною",
        "правильно утворювати множину з умляутом",
      ],
      ruleBox: {
        rule: "5 типів: <b>-e · -(e)n · -er · -s · 0</b>. Артикль завжди <b>die</b>.",
        examples: [
          { de: "der Tisch → die Tische", uk: "+e" },
          { de: "die Frau → die Frauen", uk: "+en" },
          { de: "das Auto → die Autos", uk: "+s (запозичені)" },
        ],
      },
      ukrainianTips: [
        "В українській багато закінчень множини (стіл-столи, книга-книги, вікно-вікна), у німецькій теж — універсального правила немає.",
        "Жіночі іменники <b>майже завжди</b> у множині додають -en або -n.",
        "Сучасні запозичення (Auto, Hotel, Handy) — у множині <b>-s</b>.",
      ],
      languageComparison: {
        commons: ["Множина — окрема форма."],
        diffs: ["У німецькій 5 типів утворення, плюс умляут."],
        traps: ["Не плутати «die Kinder» (Nom. Pl.) і «den Kindern» (Dat. Pl.)."],
      },
      summary: [
        "5 типів: -e, -(e)n, -er, -s, 0.",
        "Артикль множини — <b>die</b>.",
        "Жіночі → -en/-n.",
        "Запозичені (-Auto-) → -s.",
        "Учи множину разом зі словом.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Plural «der Tisch» — ?", options: ["die Tischen","die Tische","die Tischs","die Tisch"], correct: 1 },
      { type: "mc", q: "Plural «das Buch» — ?", options: ["die Buchs","die Buchen","die Bücher","die Buche"], correct: 2 },
      { type: "mc", q: "Plural «die Frau» — ?", options: ["die Frauen","die Frau","die Frauer","die Frause"], correct: 0 },
      { type: "mc", q: "Plural «das Auto» — ?", options: ["die Autoe","die Auten","die Autos","die Autos."], correct: 2 },
      { type: "gap", q: "Plural «das Kind» — die ___ .", answer: "Kinder" },
      { type: "gap", q: "Plural «die Lampe» — die ___ .", answer: "Lampen" },
      { type: "gap", q: "Plural «der Bruder» — die ___ .", answer: "Brüder" },
      { type: "tf", q: "Артикль множини — завжди «die».", correct: true },
      { type: "tf", q: "Жіночі іменники у множині завжди мають -er.", correct: false, explain: "Майже завжди -en/-n." },
      { type: "match", prompt: "Зістав однину і множину:", pairs: [
        { left: "der Tisch", right: "die Tische" },
        { left: "das Buch", right: "die Bücher" },
        { left: "die Frau", right: "die Frauen" },
        { left: "das Auto", right: "die Autos" },
      ]},
      { type: "multi", q: "Виділи всі правильні форми множини:", options: ["die Kinder","die Kindern","die Lampen","die Lampens","die Bücher","die Buchs"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe zwei Bruder.", correct: ["Ich habe zwei Brüder."] },
      { type: "order", prompt: "Склади речення:", words: ["Kinder","spielen","Die","draußen"], correct: ["Die","Kinder","spielen","draußen"] },
      { type: "translate", prompt: "Переклади:", uk: "Книги дорогі.", de: ["Die Bücher sind teuer."] },
      { type: "writeFree", prompt: "Напиши 3 речення з множиною (різні типи).", sample: "Die Kinder lachen. Die Tische sind neu. Wir haben zwei Autos.", explain: "Перевір форму множини." },
    ],
  },

  // 5 ===================================================================
  "singular-plural": {
    lesson: {
      slug: "singular-plural", level: "A1", category: CAT,
      titleDe: "Singular und Plural", titleUk: "Однина і множина",
      goal: "Розрізняти однину й множину та правильно узгоджувати дієслово.",
      explanation: [
        "<b>Singular</b> — одна річ/особа: <i>der Tisch, das Kind</i>. <b>Plural</b> — більше ніж одна: <i>die Tische, die Kinder</i>.",
        "У множині <b>дієслово</b> йде у формі множини: <i>Das Kind spielt → Die Kinder spielen.</i>",
        "Деякі слова мають <b>тільки однину</b>: das Wetter, das Obst, die Milch. Інші — <b>тільки множину</b>: die Eltern, die Leute, die Ferien.",
        "Артикль у множині завжди <b>die</b>, незалежно від роду в однині.",
      ],
      table: {
        headers: ["Однина", "Множина", "Дієслово"],
        rows: [
          ["der Tisch ist neu", "die Tische sind neu", "ist → sind"],
          ["das Kind spielt", "die Kinder spielen", "spielt → spielen"],
          ["die Frau arbeitet", "die Frauen arbeiten", "arbeitet → arbeiten"],
          ["— (тільки Pl.)", "die Eltern", "— sind"],
          ["die Milch (тільки Sg.)", "—", "die Milch ist"],
        ],
      },
      examples: [
        { de: "Das Kind ist süß.", uk: "Дитина мила." },
        { de: "Die Kinder sind süß.", uk: "Діти милі." },
        { de: "Meine Eltern wohnen in Lwiw.", uk: "Мої батьки живуть у Львові.", tag: "лише Plural" },
        { de: "Die Milch ist kalt.", uk: "Молоко холодне.", tag: "лише Singular" },
        { de: "Die Ferien beginnen morgen.", uk: "Канікули починаються завтра." },
        { de: "Die Leute warten draußen.", uk: "Люди чекають надворі." },
        { de: "Der Tisch ist alt — die Tische sind alt.", uk: "Стіл старий — столи старі." },
        { de: "Wo sind die Brillen?", uk: "Де окуляри?" },
      ],
      tip: "<b>die Eltern, die Leute, die Ferien, die Geschwister</b> — завжди множина. Дієслово з ними у формі множини.",
      mistakes: [
        { wrong: "Die Kinder spielt.", right: "Die Kinder spielen." },
        { wrong: "Meine Eltern arbeitet.", right: "Meine Eltern arbeiten." },
        { wrong: "Die Milch sind kalt.", right: "Die Milch ist kalt." },
      ],
      exercises: {},
      prevSlug: "pluralbildung",
      nextSlug: "subst-endung-e",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "узгоджувати дієслово з числом іменника",
        "знати слова pluralia tantum",
        "знати слова singularia tantum",
        "не плутати однину й множину в реченні",
      ],
      ruleBox: {
        rule: "Singular → дієслово в однині. Plural → дієслово у множині (<b>-en</b> / <b>sind</b>). Артикль Pl. — завжди <b>die</b>.",
        examples: [
          { de: "Das Kind spielt. / Die Kinder spielen.", uk: "узгодження дієслова" },
        ],
      },
      ukrainianTips: [
        "<b>die Eltern, die Leute, die Ferien</b> — у німецькій завжди множина, як і в українській «батьки/люди/канікули».",
        "<b>die Milch, das Wetter, das Obst, das Gemüse</b> — лише однина: <i>Das Obst ist frisch.</i>",
        "У німецькій <b>die Brille</b> (окуляри) — однина (інакше ніж в українській!): <i>Die Brille ist neu.</i>",
      ],
      languageComparison: {
        commons: ["Однина / множина існує в обох мовах."],
        diffs: ["Деякі слова мають інше число (Brille — Sg.)."],
        traps: ["Кальки на кшталт «die Brillen sind» для одних окулярів."],
      },
      summary: [
        "Дієслово узгоджується з числом.",
        "Plural-only: Eltern, Leute, Ferien, Geschwister.",
        "Singular-only: Milch, Wetter, Obst, Gemüse.",
        "Артикль Pl. — <b>die</b>.",
        "Brille — однина!",
      ],
    },
    exercises15: [
      { type: "mc", q: "Die Kinder ___ draußen.", options: ["spielt","spielen","spielst","spiele"], correct: 1 },
      { type: "mc", q: "Meine Eltern ___ in Berlin.", options: ["wohnt","wohne","wohnen","wohnst"], correct: 2 },
      { type: "mc", q: "Die Milch ___ kalt.", options: ["sind","ist","bist","seid"], correct: 1, explain: "Milch — однина." },
      { type: "mc", q: "Die Leute ___ müde.", options: ["ist","bist","sind","seid"], correct: 2 },
      { type: "gap", q: "Die Ferien ___ schön. (sein)", answer: "sind" },
      { type: "gap", q: "Das Wetter ___ heute schlecht. (sein)", answer: "ist" },
      { type: "gap", q: "Meine Geschwister ___ in Wien. (wohnen)", answer: "wohnen" },
      { type: "tf", q: "«Die Eltern» — це множина.", correct: true },
      { type: "tf", q: "«Die Brille» в німецькій — це множина.", correct: false, explain: "Однина." },
      { type: "match", prompt: "Зістав однину з множиною:", pairs: [
        { left: "das Kind", right: "die Kinder" },
        { left: "der Tisch", right: "die Tische" },
        { left: "die Lampe", right: "die Lampen" },
        { left: "das Auto", right: "die Autos" },
      ]},
      { type: "multi", q: "Які слова — лише множина?", options: ["Eltern","Tisch","Leute","Milch","Ferien","Kind"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Die Kinder spielt.", correct: ["Die Kinder spielen."] },
      { type: "order", prompt: "Склади речення:", words: ["wohnen","in","Eltern","Meine","Lwiw"], correct: ["Meine","Eltern","wohnen","in","Lwiw"] },
      { type: "translate", prompt: "Переклади:", uk: "Канікули починаються завтра.", de: ["Die Ferien beginnen morgen."] },
      { type: "writeFree", prompt: "Напиши 3 речення: однина, множина, plural-only.", sample: "Das Kind lacht. Die Kinder lachen. Meine Eltern arbeiten.", explain: "Перевір узгодження дієслова." },
    ],
  },

  // 6 ===================================================================
  "subst-endung-e": {
    lesson: {
      slug: "subst-endung-e", level: "A1", category: CAT,
      titleDe: "Substantive mit der Endung -e",
      titleUk: "Іменники із закінченням -e",
      goal: "Знати, що більшість іменників на -e — жіночого роду, і не плутати їх з винятками.",
      explanation: [
        "Іменники, що закінчуються на <b>-e</b>, в німецькій <b>здебільшого жіночого роду</b>: <i>die Lampe, die Schule, die Sprache</i>.",
        "Їхня множина утворюється через додавання <b>-n</b>: <i>die Lampe → die Lampen, die Schule → die Schulen</i>.",
        "Винятки: <b>der Name, der Junge, der Käse, das Auge, das Ende</b> — слова не жіночого роду, але теж на -e.",
        "Правило-підказка корисне: бачиш слово на -e → з ймовірністю 80% це <b>die</b>.",
      ],
      table: {
        headers: ["Слово", "Артикль", "Множина", "Переклад"],
        rows: [
          ["Lampe", "die", "die Lampen", "лампа"],
          ["Schule", "die", "die Schulen", "школа"],
          ["Sprache", "die", "die Sprachen", "мова"],
          ["Tasche", "die", "die Taschen", "сумка"],
          ["Name", "der", "die Namen", "ім'я (виняток)"],
          ["Auge", "das", "die Augen", "око (виняток)"],
        ],
      },
      examples: [
        { de: "Die Lampe ist neu.", uk: "Лампа нова." },
        { de: "Wo ist die Tasche?", uk: "Де сумка?" },
        { de: "Die Schule beginnt um 8.", uk: "Школа починається о 8-й." },
        { de: "Ich lerne eine neue Sprache.", uk: "Я вчу нову мову." },
        { de: "Wie ist dein Name?", uk: "Як тебе звати?", tag: "виняток m" },
        { de: "Das Auge ist blau.", uk: "Око блакитне.", tag: "виняток n" },
        { de: "Die Blume ist schön.", uk: "Квітка гарна." },
        { de: "Ich brauche eine Tasse Kaffee.", uk: "Мені потрібна чашка кави." },
      ],
      tip: "Бачиш слово на <b>-e</b> → 80% це <b>die</b>. Запам'ятай 5 винятків: <i>der Name, der Junge, der Käse, das Auge, das Ende</i>.",
      mistakes: [
        { wrong: "Der Lampe ist neu.", right: "Die Lampe ist neu." },
        { wrong: "Das Schule ist groß.", right: "Die Schule ist groß." },
        { wrong: "Die Name ist Peter.", right: "Der Name ist Peter." },
      ],
      exercises: {},
      prevSlug: "singular-plural",
      nextSlug: "subst-ung-heit-keit",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "впізнавати -e як ознаку жіночого роду",
        "автоматично робити множину на -n",
        "знати 5 ключових винятків",
        "застосовувати правило до нових слів",
      ],
      ruleBox: {
        rule: "Іменники на <b>-e</b> → переважно <b>die</b>, множина <b>+n</b>. Винятки: <i>der Name, der Junge, der Käse, das Auge, das Ende</i>.",
        examples: [
          { de: "die Schule, die Lampe, die Tasche", uk: "ж. рід" },
          { de: "der Name, das Auge", uk: "винятки" },
        ],
      },
      ukrainianTips: [
        "Українські слова часто теж на -а/-я → ж. рід. Це збігається з німецькою закономірністю, тому правило легко запам'ятати.",
        "<b>der Junge</b> = «хлопець» — логічно чоловічий рід, попри -e.",
        "Множина додає лише <b>-n</b>, бо -e вже є: <i>Lampe → Lampen</i>, не <i>Lampeen</i>.",
      ],
      languageComparison: {
        commons: ["-а/-я в українській = -e в німецькій → жіночий рід."],
        diffs: ["Винятки на -e (Name, Junge, Auge) теж є."],
        traps: ["Не вгадуй сліпо — перевір винятки."],
      },
      summary: [
        "-e → переважно <b>die</b>.",
        "Множина: <b>+n</b>.",
        "5 винятків: <i>der Name, der Junge, der Käse, das Auge, das Ende</i>.",
        "Підходить для ~80% слів на -e.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Артикль до «Schule»:", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Артикль до «Lampe»:", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Артикль до «Name»:", options: ["der","die","das","den"], correct: 0, explain: "виняток." },
      { type: "mc", q: "Артикль до «Auge»:", options: ["der","die","das","den"], correct: 2, explain: "виняток." },
      { type: "gap", q: "Plural «Lampe» — die ___ .", answer: "Lampen" },
      { type: "gap", q: "Plural «Tasche» — die ___ .", answer: "Taschen" },
      { type: "gap", q: "Plural «Auge» — die ___ .", answer: "Augen" },
      { type: "tf", q: "Більшість іменників на -e — жіночого роду.", correct: true },
      { type: "tf", q: "«Der Käse» — це жіночий рід.", correct: false, explain: "Чоловічий — виняток." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Schule", right: "die" },
        { left: "Name", right: "der" },
        { left: "Auge", right: "das" },
        { left: "Tasche", right: "die" },
      ]},
      { type: "multi", q: "Які слова — жіночого роду?", options: ["Lampe","Name","Schule","Auge","Tasche"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Der Lampe ist neu.", correct: ["Die Lampe ist neu."] },
      { type: "order", prompt: "Склади речення:", words: ["ist","Schule","Die","groß"], correct: ["Die","Schule","ist","groß"] },
      { type: "translate", prompt: "Переклади:", uk: "Сумка нова.", de: ["Die Tasche ist neu."] },
      { type: "writeFree", prompt: "Напиши 3 речення з іменниками на -e (з артиклями).", sample: "Die Lampe ist hell. Meine Tasche ist groß. Die Schule beginnt um 8.", explain: "Перевір артикль." },
    ],
  },

  // 7 ===================================================================
  "subst-ung-heit-keit": {
    lesson: {
      slug: "subst-ung-heit-keit", level: "A1", category: CAT,
      titleDe: "Substantive mit -ung, -heit, -keit",
      titleUk: "Іменники з -ung, -heit, -keit",
      goal: "Автоматично визначати рід за «суперзакінченнями» жіночого роду.",
      explanation: [
        "Усі іменники з закінченнями <b>-ung, -heit, -keit, -schaft, -tion</b> — <b>завжди die</b>. Без винятків.",
        "<b>-ung</b>: die Wohnung (квартира), die Zeitung (газета), die Übung (вправа).",
        "<b>-heit / -keit</b>: die Freiheit (свобода), die Möglichkeit (можливість), die Gesundheit (здоров'я).",
        "Множина — завжди <b>+en</b>: <i>Wohnungen, Freiheiten, Möglichkeiten</i>.",
      ],
      table: {
        headers: ["Закінчення", "Слово", "Артикль", "Множина"],
        rows: [
          ["-ung", "die Wohnung", "die", "die Wohnungen"],
          ["-ung", "die Zeitung", "die", "die Zeitungen"],
          ["-heit", "die Freiheit", "die", "die Freiheiten"],
          ["-heit", "die Gesundheit", "die", "—"],
          ["-keit", "die Möglichkeit", "die", "die Möglichkeiten"],
          ["-keit", "die Freundlichkeit", "die", "—"],
        ],
      },
      examples: [
        { de: "Meine Wohnung ist klein.", uk: "Моя квартира маленька." },
        { de: "Die Zeitung liegt auf dem Tisch.", uk: "Газета лежить на столі." },
        { de: "Die Übung ist einfach.", uk: "Вправа проста." },
        { de: "Die Freiheit ist wichtig.", uk: "Свобода — важлива." },
        { de: "Die Möglichkeit ist interessant.", uk: "Можливість цікава." },
        { de: "Deine Gesundheit ist alles.", uk: "Твоє здоров'я — це все." },
        { de: "Die Information ist neu.", uk: "Інформація нова.", tag: "-tion → die" },
        { de: "Die Freundschaft ist wichtig.", uk: "Дружба важлива.", tag: "-schaft → die" },
      ],
      tip: "5 «суперзакінчень жіночого роду»: <b>-ung, -heit, -keit, -schaft, -tion</b>. Запам'ятай їх, і отримаєш сотні слів безкоштовно.",
      mistakes: [
        { wrong: "Das Wohnung ist neu.", right: "Die Wohnung ist neu." },
        { wrong: "Der Information ist wichtig.", right: "Die Information ist wichtig." },
        { wrong: "Das Möglichkeit ist gut.", right: "Die Möglichkeit ist gut." },
      ],
      exercises: {},
      prevSlug: "subst-endung-e",
      nextSlug: "subst-chen-lein",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати 5 суперзакінчень → die",
        "автоматично казати «die Wohnung», «die Übung»",
        "правильно утворювати множину на -en",
        "впізнавати ці закінчення в нових словах",
      ],
      ruleBox: {
        rule: "<b>-ung, -heit, -keit, -schaft, -tion</b> → завжди <b>die</b>. Plural → +en.",
        examples: [
          { de: "die Wohnung, die Freiheit, die Möglichkeit", uk: "100% die" },
        ],
      },
      ukrainianTips: [
        "Це найкорисніше правило A1 для роду — нуль винятків.",
        "Слова на -<b>tion</b> легко розпізнати: вони майже завжди мають український аналог: <i>Information, Situation, Diskussion</i>.",
        "Слова на -<b>schaft</b> означають збірні поняття: <i>die Freundschaft, die Mannschaft, die Wissenschaft</i>.",
      ],
      languageComparison: {
        commons: ["Деякі слова виглядають однаково (Information, Situation)."],
        diffs: ["У німецькій ці закінчення на 100% задають рід."],
        traps: ["Кальки на кшталт «das Information» — поширена помилка."],
      },
      summary: [
        "<b>-ung, -heit, -keit, -schaft, -tion</b> → die.",
        "Без винятків.",
        "Plural → +en.",
        "Найшвидший спосіб дізнатися рід.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Артикль до «Wohnung»:", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Артикль до «Freiheit»:", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Артикль до «Möglichkeit»:", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Артикль до «Information»:", options: ["der","die","das","den"], correct: 1 },
      { type: "gap", q: "___ Übung ist leicht.", answer: "Die" },
      { type: "gap", q: "___ Freundschaft ist wichtig.", answer: "Die" },
      { type: "gap", q: "Plural «Wohnung» — die ___ .", answer: "Wohnungen" },
      { type: "tf", q: "Слова на -ung — завжди die.", correct: true },
      { type: "tf", q: "Слова на -tion — чоловічого роду.", correct: false },
      { type: "match", prompt: "Зістав закінчення з родом:", pairs: [
        { left: "-ung", right: "die" },
        { left: "-heit", right: "die" },
        { left: "-keit", right: "die" },
        { left: "-tion", right: "die" },
      ]},
      { type: "multi", q: "Виділи всі слова з -ung/-heit/-keit/-tion:", options: ["Wohnung","Tisch","Freiheit","Mädchen","Möglichkeit","Information"], correct: [0,2,4,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Wohnung ist neu.", correct: ["Die Wohnung ist neu."] },
      { type: "order", prompt: "Склади речення:", words: ["wichtig","Die","Gesundheit","ist"], correct: ["Die","Gesundheit","ist","wichtig"] },
      { type: "translate", prompt: "Переклади:", uk: "Можливість цікава.", de: ["Die Möglichkeit ist interessant."] },
      { type: "writeFree", prompt: "Напиши 3 речення зі словами на -ung/-heit/-keit.", sample: "Meine Wohnung ist klein. Die Freiheit ist wichtig. Die Möglichkeit ist gut.", explain: "Артикль — завжди die." },
    ],
  },

  // 8 ===================================================================
  "subst-chen-lein": {
    lesson: {
      slug: "subst-chen-lein", level: "A1", category: CAT,
      titleDe: "Substantive mit -chen und -lein",
      titleUk: "Іменники з -chen і -lein",
      goal: "Розуміти зменшувальні суфікси -chen / -lein і знати, що такі слова — <b>завжди das</b>.",
      explanation: [
        "Зменшувальні суфікси <b>-chen</b> і <b>-lein</b> роблять річ маленькою або милою: <i>Brot → Brötchen</i>, <i>Hund → Hündchen</i>.",
        "Усі іменники з -chen / -lein — <b>завжди das</b>, навіть якщо «велика» форма іншого роду: <i>der Tisch → das Tischchen</i>.",
        "Часто з'являється <b>умляут</b>: <i>Brot → Br<b>ö</b>tchen, Hund → H<b>ü</b>ndchen, Buch → B<b>ü</b>chlein</i>.",
        "Множина = однині (<b>0 закінчення</b>): <i>das Mädchen → die Mädchen, das Brötchen → die Brötchen</i>.",
      ],
      table: {
        headers: ["Базове слово", "Зменшене", "Артикль"],
        rows: [
          ["das Brot", "das Brötchen", "das"],
          ["der Hund", "das Hündchen", "das"],
          ["das Buch", "das Büchlein", "das"],
          ["der Mann", "das Männchen", "das"],
          ["das Haus", "das Häuschen", "das"],
          ["—", "das Mädchen", "das"],
        ],
      },
      examples: [
        { de: "Ich kaufe zwei Brötchen.", uk: "Я купую дві булочки." },
        { de: "Das Mädchen spielt im Park.", uk: "Дівчинка грається в парку." },
        { de: "Das Hündchen ist süß.", uk: "Песик милий." },
        { de: "Das Häuschen ist klein.", uk: "Будиночок маленький." },
        { de: "Sie hat ein Büchlein.", uk: "У неї маленька книжечка." },
        { de: "Das Männchen ist lustig.", uk: "Чоловічок смішний." },
        { de: "Wir essen Brötchen zum Frühstück.", uk: "Ми їмо булочки на сніданок." },
        { de: "Das Kätzchen schläft.", uk: "Кошеня спить." },
      ],
      tip: "Усі слова з <b>-chen / -lein</b> — <b>das</b>, навіть для людей: <i>das Mädchen</i> (дівчинка), <i>das Fräulein</i> (панянка).",
      mistakes: [
        { wrong: "Die Mädchen ist nett.", right: "Das Mädchen ist nett." },
        { wrong: "Der Brötchen ist frisch.", right: "Das Brötchen ist frisch." },
        { wrong: "Die Häuschen sind klein.", right: "Die Häuschen sind klein. ✓ (Plural — все одно die)", },
      ],
      exercises: {},
      prevSlug: "subst-ung-heit-keit",
      nextSlug: "zusammengesetzte-subst",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "розпізнавати -chen / -lein як зменшувальні",
        "знати, що такі слова — завжди das",
        "помічати умляут у зменшеному слові",
        "не утворювати множину з додатковим закінченням",
      ],
      ruleBox: {
        rule: "<b>-chen / -lein → das</b> (без винятків). Часто з'являється умляут. Plural = Singular.",
        examples: [
          { de: "das Brötchen, das Mädchen, das Häuschen", uk: "усі das" },
        ],
      },
      ukrainianTips: [
        "Українські зменшувальні (-ик, -ик, -еня) зберігають рід базового слова, а в німецькій — <b>завжди змінюють</b> на <b>das</b>.",
        "Через це <b>das Mädchen</b> — середній рід, хоч дівчинка — жінка.",
        "У множині нічого не додаємо: <i>die Mädchen, die Brötchen</i>.",
      ],
      languageComparison: {
        commons: ["Зменшувальні суфікси існують і там, і там."],
        diffs: ["У німецькій усі зменшувальні — das."],
        traps: ["Die Mädchen у Singular — груба помилка."],
      },
      summary: [
        "-chen / -lein → <b>das</b>.",
        "Часто умляут (Brot → Brötchen).",
        "Plural = Singular.",
        "Без винятків.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Артикль до «Mädchen»:", options: ["der","die","das","den"], correct: 2 },
      { type: "mc", q: "Артикль до «Brötchen»:", options: ["der","die","das","den"], correct: 2 },
      { type: "mc", q: "Артикль до «Hündchen»:", options: ["der","die","das","den"], correct: 2 },
      { type: "mc", q: "Артикль до «Büchlein»:", options: ["der","die","das","den"], correct: 2 },
      { type: "gap", q: "___ Brötchen ist frisch.", answer: "Das" },
      { type: "gap", q: "Plural «das Mädchen» — die ___ .", answer: "Mädchen" },
      { type: "gap", q: "«Brot» + -chen + умляут → ___ .", answer: "Brötchen" },
      { type: "tf", q: "Усі слова з -chen — середнього роду.", correct: true },
      { type: "tf", q: "«Die Mädchen» в однині — правильно.", correct: false, explain: "Das Mädchen." },
      { type: "match", prompt: "Зістав базове і зменшене:", pairs: [
        { left: "Brot", right: "Brötchen" },
        { left: "Hund", right: "Hündchen" },
        { left: "Buch", right: "Büchlein" },
        { left: "Haus", right: "Häuschen" },
      ]},
      { type: "multi", q: "Які з цих слів — точно das?", options: ["Mädchen","Wohnung","Brötchen","Tisch","Häuschen"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Die Mädchen ist klein.", correct: ["Das Mädchen ist klein."] },
      { type: "order", prompt: "Склади речення:", words: ["süß","Hündchen","Das","ist"], correct: ["Das","Hündchen","ist","süß"] },
      { type: "translate", prompt: "Переклади:", uk: "Будиночок маленький.", de: ["Das Häuschen ist klein."] },
      { type: "writeFree", prompt: "Напиши 3 речення зі зменшувальними словами.", sample: "Das Mädchen lacht. Das Brötchen ist frisch. Das Hündchen schläft.", explain: "Артикль — das." },
    ],
  },

  // 9 ===================================================================
  "zusammengesetzte-subst": {
    lesson: {
      slug: "zusammengesetzte-subst", level: "A1", category: CAT,
      titleDe: "Zusammengesetzte Substantive", titleUk: "Складні іменники",
      goal: "Утворювати складні іменники й знати, що рід визначає <b>останнє</b> слово.",
      explanation: [
        "У німецькій складні іменники пишуться <b>разом</b> в одне слово: <i>Haus + Tür = Haustür</i>.",
        "<b>Рід усього слова</b> = рід <b>останнього</b> компонента: <i>die Haustür</i> (бо <i>die Tür</i>), <i>der Apfelsaft</i> (бо <i>der Saft</i>).",
        "Множина — теж за останнім словом: <i>die Haustüren</i> (як <i>die Türen</i>).",
        "Іноді між частинами вставляється <b>-s-</b> або <b>-n-</b>: <i>Geburtstag, Sonnenuntergang, Bahnhof</i>.",
      ],
      table: {
        headers: ["Частина 1", "Частина 2", "Слово", "Артикль (= ост.)"],
        rows: [
          ["Haus", "Tür", "Haustür", "die (← die Tür)"],
          ["Apfel", "Saft", "Apfelsaft", "der (← der Saft)"],
          ["Kinder", "Garten", "Kindergarten", "der (← der Garten)"],
          ["Geburt", "+s + Tag", "Geburtstag", "der (← der Tag)"],
          ["Sonne", "+n + Untergang", "Sonnenuntergang", "der"],
          ["Buch", "Laden", "Buchladen", "der (← der Laden)"],
        ],
      },
      examples: [
        { de: "Die Haustür ist offen.", uk: "Вхідні двері відчинені." },
        { de: "Ich trinke gern Apfelsaft.", uk: "Я люблю яблучний сік." },
        { de: "Mein Sohn geht in den Kindergarten.", uk: "Мій син ходить у дитсадок." },
        { de: "Heute ist mein Geburtstag.", uk: "Сьогодні мій день народження." },
        { de: "Der Bahnhof ist groß.", uk: "Вокзал великий." },
        { de: "Der Schreibtisch steht im Zimmer.", uk: "Письмовий стіл стоїть у кімнаті." },
        { de: "Ich kaufe ein Wörterbuch.", uk: "Я купую словник." },
        { de: "Die Hausaufgabe ist schwer.", uk: "Домашнє завдання важке." },
      ],
      tip: "<b>Артикль = артикль останнього слова</b>. Це найшвидший спосіб дізнатися рід.",
      mistakes: [
        { wrong: "Das Haustür ist zu.", right: "Die Haustür ist zu." },
        { wrong: "Die Apfelsaft ist kalt.", right: "Der Apfelsaft ist kalt." },
        { wrong: "Haus Tür ist offen.", right: "Die Haustür ist offen." },
      ],
      exercises: {},
      prevSlug: "subst-chen-lein",
      nextSlug: "grossschreibung",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "писати складні іменники одним словом",
        "визначати рід за останнім словом",
        "розрізняти зв'язкові -s- та -n-",
        "розуміти складні слова в текстах",
      ],
      ruleBox: {
        rule: "Складне слово пишеться <b>разом</b>. Рід і множина = за <b>останнім</b> словом.",
        examples: [
          { de: "die Haustür (← Tür)", uk: "f" },
          { de: "der Apfelsaft (← Saft)", uk: "m" },
        ],
      },
      ukrainianTips: [
        "В українській «домашнє завдання» — два слова. У німецькій — <b>die Hausaufgabe</b>, одне слово.",
        "Якщо бачиш довге німецьке слово — шукай <b>останнє</b>: воно дає рід.",
        "Зв'язкове -s- з'являється після слів типу <i>Geburt, Liebe, Universität</i>: <i>Geburtstag, Liebesbrief, Universitätsbibliothek</i>.",
      ],
      languageComparison: {
        commons: ["Складні поняття є й там, і там."],
        diffs: ["У німецькій усе пишеться як одне слово."],
        traps: ["Не вгадуй рід за першим словом."],
      },
      summary: [
        "Складні слова пишуться <b>разом</b>.",
        "Рід = за останнім словом.",
        "Множина = за останнім словом.",
        "Іноді -s-/-n- між частинами.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Який артикль у «Haustür»?", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Який артикль у «Apfelsaft»?", options: ["der","die","das","den"], correct: 0 },
      { type: "mc", q: "Який артикль у «Kindergarten»?", options: ["der","die","das","den"], correct: 0 },
      { type: "mc", q: "Який артикль у «Hausaufgabe»?", options: ["der","die","das","den"], correct: 1 },
      { type: "gap", q: "___ Geburtstag ist heute.", answer: "Der" },
      { type: "gap", q: "Plural «das Wörterbuch» — die ___ .", answer: "Wörterbücher" },
      { type: "gap", q: "Haus + Aufgabe = ___ .", answer: "Hausaufgabe" },
      { type: "tf", q: "Рід складного слова визначає перше слово.", correct: false, explain: "Останнє." },
      { type: "tf", q: "У німецькій складні слова пишуться разом.", correct: true },
      { type: "match", prompt: "Зістав слово й артикль:", pairs: [
        { left: "Haustür", right: "die" },
        { left: "Apfelsaft", right: "der" },
        { left: "Kindergarten", right: "der" },
        { left: "Hausaufgabe", right: "die" },
      ]},
      { type: "multi", q: "Які слова — складні?", options: ["Tisch","Hausaufgabe","Apfelsaft","Mann","Bahnhof"], correct: [1,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Das Haustür ist offen.", correct: ["Die Haustür ist offen."] },
      { type: "order", prompt: "Склади речення:", words: ["heute","mein","Geburtstag","Es","ist"], correct: ["Es","ist","heute","mein","Geburtstag"] },
      { type: "translate", prompt: "Переклади:", uk: "Я люблю яблучний сік.", de: ["Ich trinke gern Apfelsaft."] },
      { type: "writeFree", prompt: "Напиши 3 речення зі складними іменниками.", sample: "Mein Geburtstag ist im Mai. Die Hausaufgabe ist schwer. Der Bahnhof ist neu.", explain: "Перевір артикль за останнім словом." },
    ],
  },

  // 10 ===================================================================
  grossschreibung: {
    lesson: {
      slug: "grossschreibung", level: "A1", category: CAT,
      titleDe: "Großschreibung der Substantive", titleUk: "Великі літери в іменниках",
      goal: "Завжди писати німецькі іменники з великої літери, навіть у середині речення.",
      explanation: [
        "У німецькій <b>всі іменники</b> пишуться з <b>великої літери</b>, навіть у середині речення.",
        "Це стосується і власних, і загальних: <b>der Tisch, das Haus, die Liebe, das Lernen</b>.",
        "Дієслова, прикметники й прийменники — з <b>малої</b>: <i>laufen, schön, in, auf</i>.",
        "Якщо дієслово стає іменником (номіналізація) — велика літера: <i>Das Lernen macht Spaß.</i>",
      ],
      table: {
        headers: ["З великої", "З малої", "Приклад"],
        rows: [
          ["іменники", "—", "der Tisch, das Buch"],
          ["—", "дієслова", "lernen, gehen"],
          ["—", "прикметники", "schön, groß"],
          ["—", "прийменники", "in, auf, mit"],
          ["займенник Sie (ввічл.)", "ich, du, wir", "Wie heißen Sie?"],
          ["номіналізовані дієслова", "—", "das Lernen, das Essen"],
        ],
      },
      examples: [
        { de: "Der Mann liest ein Buch.", uk: "Чоловік читає книгу." },
        { de: "Wir kaufen Brot und Milch.", uk: "Ми купуємо хліб і молоко." },
        { de: "Das Lernen macht Spaß.", uk: "Навчання приносить задоволення.", tag: "номіналізація" },
        { de: "Wie heißen Sie?", uk: "Як вас звати?", tag: "Sie з великої" },
        { de: "Ich gehe in die Schule.", uk: "Я йду в школу." },
        { de: "Anna ist meine Schwester.", uk: "Анна — моя сестра." },
        { de: "Das Essen ist lecker.", uk: "Їжа смачна." },
        { de: "Der Hund spielt im Garten.", uk: "Пес грається в саду." },
      ],
      tip: "Якщо сумніваєшся — спробуй поставити перед словом артикль. Якщо «звучить» (<i>das Lernen, das Essen</i>) — то це іменник, пиши з великої.",
      mistakes: [
        { wrong: "ich gehe in die schule.", right: "Ich gehe in die Schule." },
        { wrong: "wir kaufen brot und milch.", right: "Wir kaufen Brot und Milch." },
        { wrong: "Wie heißen sie?", right: "Wie heißen Sie?" },
      ],
      exercises: {},
      prevSlug: "zusammengesetzte-subst",
      nextSlug: "personen-berufe",
    },
    extras: {
      duration: 8, premium: false,
      learningGoals: [
        "автоматично писати всі іменники з великої",
        "не плутати дієслова й прикметники з іменниками",
        "пам'ятати про ввічливе Sie",
        "розпізнавати номіналізацію",
      ],
      ruleBox: {
        rule: "Всі <b>іменники</b> + ввічливе <b>Sie</b> → велика літера. Дієслова, прикметники, прийменники, ich/du → мала.",
      },
      ukrainianTips: [
        "В українській з великої лише імена власні. У німецькій — <b>усі</b> іменники.",
        "<b>Sie</b> (Ви ввічл.) — завжди з великої, навіть у середині речення.",
        "<b>ich</b> — з малої (на відміну від англійського «I»).",
      ],
      languageComparison: {
        commons: ["Імена власні — велика літера в обох мовах."],
        diffs: ["У німецькій <b>всі</b> іменники з великої."],
        traps: ["Українські калькування → іменник з малої = помилка."],
      },
      summary: [
        "Іменники → <b>велика</b>.",
        "Sie (ввічл.) → велика.",
        "ich / du / wir → мала.",
        "Дієслова, прикметники → мала.",
        "Номіналізовані дієслова → велика.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Яке речення правильне?", options: [
        "ich lerne deutsch.",
        "Ich lerne Deutsch.",
        "Ich Lerne deutsch.",
        "ich lerne Deutsch.",
      ], correct: 1 },
      { type: "mc", q: "Яке речення правильне?", options: [
        "Wie heißen sie?",
        "Wie Heißen Sie?",
        "Wie heißen Sie?",
        "wie heißen Sie?",
      ], correct: 2 },
      { type: "gap", q: "Напиши з великої: ich kaufe ___ und ___ . (brot, milch)", answer: "Brot und Milch", hint: "Іменники → велика." },
      { type: "gap", q: "Напиши правильно: das ___ macht spaß. (lernen)", answer: "Lernen", hint: "Номіналізація → велика." },
      { type: "tf", q: "У німецькій усі іменники пишуться з великої.", correct: true },
      { type: "tf", q: "Слово «ich» завжди з великої.", correct: false, explain: "З малої, крім початку речення." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Schule", right: "велика" },
        { left: "gehen", right: "мала" },
        { left: "schön", right: "мала" },
        { left: "Sie (ввічл.)", right: "велика" },
      ]},
      { type: "multi", q: "Які слова мають бути з великої?", options: ["tisch","laufen","haus","schön","mädchen"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "ich gehe in die schule.", correct: ["Ich gehe in die Schule."] },
      { type: "correct", prompt: "Виправ:", wrong: "wir kaufen brot.", correct: ["Wir kaufen Brot."] },
      { type: "correct", prompt: "Виправ:", wrong: "Wie heißen sie?", correct: ["Wie heißen Sie?"] },
      { type: "order", prompt: "Склади речення:", words: ["lese","Ich","ein","Buch"], correct: ["Ich","lese","ein","Buch"] },
      { type: "translate", prompt: "Переклади:", uk: "Я купую хліб і молоко.", de: ["Ich kaufe Brot und Milch."] },
      { type: "tf", q: "У реченні «Das Essen ist lecker» слово «Essen» — іменник.", correct: true },
      { type: "writeFree", prompt: "Напиши 3 речення, пильнуючи великі літери.", sample: "Ich lerne Deutsch. Mein Bruder spielt Fußball. Das Essen ist lecker.", explain: "Усі іменники — велика." },
    ],
  },

  // 11 ===================================================================
  "personen-berufe": {
    lesson: {
      slug: "personen-berufe", level: "A1", category: CAT,
      titleDe: "Personen und Berufe", titleUk: "Назви людей і професій",
      goal: "Утворювати назви професій і національностей у чоловічій і жіночій формі.",
      explanation: [
        "Чоловічі форми професій — <b>der</b>: <i>der Lehrer, der Arzt, der Student</i>. Жіночі утворюються додаванням <b>-in</b>: <i>die Lehrer<b>in</b>, die Ärzt<b>in</b>, die Student<b>in</b></i>.",
        "Множина жіночих форм — <b>-innen</b>: <i>die Lehrerinnen, die Studentinnen</i>.",
        "Після <b>sein</b> професія йде <b>без артикля</b>: <i>Ich bin Lehrer. / Ich bin Lehrerin.</i>",
        "Те ж саме для національностей: <i>der Ukrainer / die Ukrainerin</i>, <i>der Deutsche / die Deutsche</i>.",
      ],
      table: {
        headers: ["m", "f", "Множина f", "Переклад"],
        rows: [
          ["der Lehrer", "die Lehrerin", "die Lehrerinnen", "вчитель(ка)"],
          ["der Arzt", "die Ärztin", "die Ärztinnen", "лікар(ка)"],
          ["der Student", "die Studentin", "die Studentinnen", "студент(ка)"],
          ["der Verkäufer", "die Verkäuferin", "die Verkäuferinnen", "продавець"],
          ["der Ukrainer", "die Ukrainerin", "die Ukrainerinnen", "українець/-нка"],
          ["der Deutsche*", "die Deutsche*", "die Deutschen", "німець / німкеня"],
        ],
      },
      examples: [
        { de: "Ich bin Lehrer von Beruf.", uk: "Я вчитель за фахом." },
        { de: "Meine Mutter ist Ärztin.", uk: "Моя мама — лікарка." },
        { de: "Er ist Student in Berlin.", uk: "Він студент у Берліні." },
        { de: "Sie arbeitet als Verkäuferin.", uk: "Вона працює продавчинею." },
        { de: "Anna ist Ukrainerin.", uk: "Анна — українка." },
        { de: "Mein Kollege ist Deutscher.", uk: "Мій колега — німець." },
        { de: "Die Studentinnen lernen viel.", uk: "Студентки багато вчаться." },
        { de: "Was sind Sie von Beruf?", uk: "Хто Ви за фахом?" },
      ],
      tip: "Жіноча форма = чоловіча + <b>-in</b>. Множина жіночої = <b>-innen</b> (два n!). Після <b>sein</b> — без артикля.",
      mistakes: [
        { wrong: "Ich bin eine Lehrerin.", right: "Ich bin Lehrerin." },
        { wrong: "Meine Mutter ist Arzt.", right: "Meine Mutter ist Ärztin." },
        { wrong: "Sie sind Studentin.", right: "Sie sind Studentinnen.", },
      ],
      exercises: {},
      prevSlug: "grossschreibung",
      nextSlug: "laender-nationalitaeten",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "утворювати жіночі форми професій через -in",
        "правильно множинити: -innen",
        "не ставити артикль після sein",
        "розповідати про свій фах і національність",
      ],
      ruleBox: {
        rule: "m → f: додай <b>-in</b>. Множина f: <b>-innen</b>. Після <b>sein</b> — без артикля.",
        examples: [
          { de: "der Lehrer → die Lehrerin → die Lehrerinnen", uk: "" },
        ],
      },
      ukrainianTips: [
        "В українській теж є пара чоловік/жінка (вчитель/вчителька), у німецькій правило простіше: +<b>-in</b>.",
        "У німецькій після <b>«ist + професія»</b> артикль <b>не</b> ставиться: <i>Sie ist Ärztin</i>.",
        "Множина <b>-innen</b> — два «n». Не плутай з -inen.",
      ],
      languageComparison: {
        commons: ["Жіноча форма утворюється від чоловічої."],
        diffs: ["У німецькій — універсальний суфікс -in."],
        traps: ["«Ich bin ein Lehrer» — типова помилка."],
      },
      summary: [
        "f = m + <b>-in</b>.",
        "Pl. f = -<b>innen</b>.",
        "Після sein → без артикля.",
        "Національність — за тим же правилом.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Жіноча форма «Lehrer» —", options: ["Lehrere","Lehrerin","Lehrers","Lehrerinnen"], correct: 1 },
      { type: "mc", q: "Множина «Studentin» —", options: ["Studentinnen","Studentinen","Studenten","Studentinens"], correct: 0 },
      { type: "mc", q: "Як правильно «Я лікарка»?", options: ["Ich bin eine Ärztin.","Ich bin Ärztin.","Ich bin die Ärztin.","Ich Ärztin bin."], correct: 1 },
      { type: "mc", q: "Жіноча форма «Arzt» —", options: ["Arztin","Ärztin","Arztinnen","Arzte"], correct: 1, explain: "+ умляут." },
      { type: "gap", q: "Anna ist ___ . (студентка)", answer: "Studentin" },
      { type: "gap", q: "Plural «die Lehrerin» — die ___ .", answer: "Lehrerinnen" },
      { type: "gap", q: "Mein Vater ist ___ . (вчитель)", answer: "Lehrer" },
      { type: "tf", q: "Після sein артикль перед професією не ставиться.", correct: true },
      { type: "tf", q: "Жіноча форма утворюється через -er.", correct: false, explain: "-in." },
      { type: "match", prompt: "Зістав професії:", pairs: [
        { left: "Lehrer", right: "Lehrerin" },
        { left: "Arzt", right: "Ärztin" },
        { left: "Student", right: "Studentin" },
        { left: "Ukrainer", right: "Ukrainerin" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich bin Lehrerin.",
        "Ich bin eine Lehrerin.",
        "Er ist Student.",
        "Er ist ein Student.",
      ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Meine Mutter ist Arzt.", correct: ["Meine Mutter ist Ärztin."] },
      { type: "order", prompt: "Склади речення:", words: ["von","Lehrer","Beruf","bin","Ich"], correct: ["Ich","bin","Lehrer","von","Beruf"] },
      { type: "translate", prompt: "Переклади:", uk: "Вона працює лікаркою.", de: ["Sie arbeitet als Ärztin."] },
      { type: "writeFree", prompt: "Напиши 3 речення про професії членів родини.", sample: "Mein Vater ist Lehrer. Meine Mutter ist Ärztin. Mein Bruder ist Student.", explain: "Без артикля після sein." },
    ],
  },

  // 12 ===================================================================
  "laender-nationalitaeten": {
    lesson: {
      slug: "laender-nationalitaeten", level: "A1", category: CAT,
      titleDe: "Länder und Nationalitäten", titleUk: "Країни і національності",
      goal: "Називати країну, національність і мову — без помилок і без зайвих артиклів.",
      explanation: [
        "Більшість країн — <b>середнього роду без артикля</b>: <i>Deutschland, Österreich, Frankreich, Italien, die Ukraine*</i>.",
        "Винятки <b>з артиклем</b>: <b>die Ukraine, die Schweiz, die Türkei, der Iran, die USA (Pl.)</b>.",
        "Національність: <b>der Deutsche / die Deutsche</b>, <b>der Ukrainer / die Ukrainerin</b>. Мова: <i>Deutsch, Ukrainisch</i> — без артикля.",
        "«Я з …»: <b>aus + Land</b>. З країною без артикля: <i>aus Deutschland</i>. З артиклем: <i>aus der Ukraine, aus der Schweiz</i>.",
      ],
      table: {
        headers: ["Країна", "Артикль", "Він", "Вона", "Мова"],
        rows: [
          ["Deutschland", "—", "der Deutsche", "die Deutsche", "Deutsch"],
          ["Österreich", "—", "der Österreicher", "die Österreicherin", "Deutsch"],
          ["Ukraine", "die", "der Ukrainer", "die Ukrainerin", "Ukrainisch"],
          ["Schweiz", "die", "der Schweizer", "die Schweizerin", "Deutsch/Französisch/…"],
          ["Frankreich", "—", "der Franzose", "die Französin", "Französisch"],
          ["Italien", "—", "der Italiener", "die Italienerin", "Italienisch"],
        ],
      },
      examples: [
        { de: "Ich komme aus der Ukraine.", uk: "Я з України.", tag: "die Ukraine → aus der" },
        { de: "Er kommt aus Deutschland.", uk: "Він з Німеччини." },
        { de: "Anna ist Ukrainerin und spricht Ukrainisch.", uk: "Анна — українка і розмовляє українською." },
        { de: "Wir wohnen in Österreich.", uk: "Ми живемо в Австрії." },
        { de: "Sie ist Schweizerin.", uk: "Вона швейцарка." },
        { de: "Mein Freund kommt aus Italien.", uk: "Мій друг з Італії." },
        { de: "Ich lerne Deutsch.", uk: "Я вчу німецьку." },
        { de: "Sprichst du Französisch?", uk: "Ти розмовляєш французькою?" },
      ],
      tip: "Назви мов і національностей пиши <b>з великої</b>, бо це іменники: <i>Ich lerne Deutsch. Sie ist Ukrainerin.</i>",
      mistakes: [
        { wrong: "Ich komme aus die Ukraine.", right: "Ich komme aus der Ukraine." },
        { wrong: "Ich komme aus dem Deutschland.", right: "Ich komme aus Deutschland." },
        { wrong: "Ich lerne deutsch.", right: "Ich lerne Deutsch." },
      ],
      exercises: {},
      prevSlug: "personen-berufe",
      nextSlug: "haeufige-pluralformen",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати країни без артикля й з артиклем",
        "правильно вживати aus + країна",
        "розрізняти національність і мову",
        "писати національність і мову з великої",
      ],
      ruleBox: {
        rule: "Більшість країн — <b>без артикля</b>. Винятки: die Ukraine, die Schweiz, die Türkei, der Iran, die USA. Після <b>aus</b>: <i>aus Deutschland</i>, але <i>aus der Ukraine</i>.",
      },
      ukrainianTips: [
        "Українською «з України» — у німецькій <b>aus der Ukraine</b>. Артикль обов'язковий.",
        "Не плутай <b>національність</b> (Ukrainerin) і <b>мову</b> (Ukrainisch).",
        "Мову пиши з <b>великої</b>: <i>Ich lerne Deutsch</i>, не <i>deutsch</i>.",
      ],
      languageComparison: {
        commons: ["Концепція країни/мови/національності однакова."],
        diffs: ["У німецькій декілька країн потребують артикля."],
        traps: ["«aus die Ukraine» — типова українська помилка."],
      },
      summary: [
        "Більшість країн — без артикля.",
        "<b>die</b>: Ukraine, Schweiz, Türkei. <b>der</b>: Iran. <b>die</b>: USA (Pl.).",
        "Жіноча національність = -in.",
        "Мова і національність — велика літера.",
        "aus + країна → з України = <i>aus der Ukraine</i>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich komme aus ___ Ukraine.", options: ["—","der","die","das"], correct: 1 },
      { type: "mc", q: "Er kommt aus ___ Deutschland.", options: ["—","der","die","das"], correct: 0 },
      { type: "mc", q: "Sie ist ___ und spricht Ukrainisch.", options: ["Ukrainer","Ukrainerin","Ukraine","Ukrainisch"], correct: 1 },
      { type: "mc", q: "Wir wohnen in ___ Schweiz.", options: ["—","der","die","das"], correct: 1 },
      { type: "gap", q: "Ich lerne ___ . (німецька)", answer: "Deutsch" },
      { type: "gap", q: "Sie ist ___ . (швейцарка)", answer: "Schweizerin" },
      { type: "gap", q: "Er kommt aus ___ Türkei.", answer: "der" },
      { type: "tf", q: "Назви мов пишуть з малої літери.", correct: false, explain: "З великої — це іменники." },
      { type: "tf", q: "«die Ukraine» вживається з артиклем.", correct: true },
      { type: "match", prompt: "Зістав країну й національність (f):", pairs: [
        { left: "Deutschland", right: "Deutsche" },
        { left: "Ukraine", right: "Ukrainerin" },
        { left: "Frankreich", right: "Französin" },
        { left: "Italien", right: "Italienerin" },
      ]},
      { type: "multi", q: "Які країни потребують артикля?", options: ["Ukraine","Deutschland","Schweiz","Italien","Türkei"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich komme aus die Ukraine.", correct: ["Ich komme aus der Ukraine."] },
      { type: "order", prompt: "Склади речення:", words: ["aus","komme","der","Ich","Ukraine"], correct: ["Ich","komme","aus","der","Ukraine"] },
      { type: "translate", prompt: "Переклади:", uk: "Я з України і розмовляю українською.", de: ["Ich komme aus der Ukraine und spreche Ukrainisch."] },
      { type: "writeFree", prompt: "Напиши 3 речення про себе: звідки, національність, мови.", sample: "Ich komme aus der Ukraine. Ich bin Ukrainerin. Ich spreche Ukrainisch und Deutsch.", explain: "Перевір артикль перед країною та велику літеру для мови." },
    ],
  },

  // 13 ===================================================================
  "haeufige-pluralformen": {
    lesson: {
      slug: "haeufige-pluralformen", level: "A1", category: CAT,
      titleDe: "Häufige Pluralformen", titleUk: "Поширені форми множини",
      goal: "Запам'ятати множину 30 найважливіших A1 іменників.",
      explanation: [
        "У німецькій немає одного правила множини — треба вивчити форми разом зі словом.",
        "Для A1 досить запам'ятати ~30 високочастотних іменників: родина, дім, школа, їжа, місто, час.",
        "Звертай увагу на <b>умляут</b>: Mann → M<b>ä</b>nner, Buch → B<b>ü</b>cher, Vater → V<b>ä</b>ter.",
        "Запозичення зазвичай мають <b>-s</b>: Auto → Autos, Hotel → Hotels, Handy → Handys.",
      ],
      table: {
        headers: ["Однина", "Множина", "Тип"],
        rows: [
          ["der Mann", "die Männer", "-er + ¨"],
          ["die Frau", "die Frauen", "-en"],
          ["das Kind", "die Kinder", "-er"],
          ["der Vater", "die Väter", "¨"],
          ["die Mutter", "die Mütter", "¨"],
          ["das Buch", "die Bücher", "-er + ¨"],
          ["der Tisch", "die Tische", "-e"],
          ["das Haus", "die Häuser", "-er + ¨"],
          ["die Stadt", "die Städte", "-e + ¨"],
          ["das Auto", "die Autos", "-s"],
        ],
      },
      examples: [
        { de: "Ich habe zwei Brüder.", uk: "У мене два брати." },
        { de: "Die Kinder spielen.", uk: "Діти граються." },
        { de: "Wir kaufen drei Bücher.", uk: "Ми купуємо три книги." },
        { de: "Die Städte in Deutschland sind schön.", uk: "Міста в Німеччині гарні." },
        { de: "Meine Eltern haben zwei Autos.", uk: "Мої батьки мають два автомобілі." },
        { de: "Die Häuser sind alt.", uk: "Будинки старі." },
        { de: "Die Männer arbeiten.", uk: "Чоловіки працюють." },
        { de: "Die Mütter sind müde.", uk: "Мами втомлені." },
      ],
      tip: "Картка має містити <b>3 поля</b>: артикль, слово, множина. Без цих трьох — слово вивчене не повністю.",
      mistakes: [
        { wrong: "Ich habe zwei Bruder.", right: "Ich habe zwei Brüder." },
        { wrong: "Die Häuser ist alt.", right: "Die Häuser sind alt." },
        { wrong: "Die Mans arbeiten.", right: "Die Männer arbeiten." },
      ],
      exercises: {},
      prevSlug: "laender-nationalitaeten",
      nextSlug: "typische-ausnahmen",
    },
    extras: {
      duration: 12, premium: false,
      learningGoals: [
        "знати множину 30 ключових A1 іменників",
        "помічати умляут",
        "розрізняти -s (запозичення) і -er/-e (питомі)",
        "узгоджувати дієслово з множиною",
      ],
      ruleBox: {
        rule: "Учи слово з артиклем <b>і</b> множиною. Запам'ятай 30 високочастотних форм A1.",
      },
      ukrainianTips: [
        "Множина — це не «логіка», а пам'ять. Поясни собі через схожість: Bruder → Brüder ≈ «брат → брати».",
        "Слова <b>die Mutter, die Tochter, der Vater, der Bruder</b> у множині лише додають <b>умляут</b>: <i>Mütter, Töchter, Väter, Brüder</i>.",
        "Технічні запозичення (Auto, Hotel, Handy, Kino) → <b>-s</b>.",
      ],
      languageComparison: {
        commons: ["Множина — окрема форма."],
        diffs: ["У німецькій 5+ типів утворення."],
        traps: ["Без множини «слово не вивчене»."],
      },
      summary: [
        "Учи слово з артиклем і множиною.",
        "Помічай умляут.",
        "Запозичення → -s.",
        "Жіночі → майже завжди -en/-n.",
        "Plural артикль завжди <b>die</b>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Plural «der Mann» —", options: ["die Manner","die Männer","die Mans","die Mannen"], correct: 1 },
      { type: "mc", q: "Plural «das Haus» —", options: ["die Hauser","die Häuser","die Hause","die Haus"], correct: 1 },
      { type: "mc", q: "Plural «die Stadt» —", options: ["die Stadten","die Städte","die Stadts","die Städten"], correct: 1 },
      { type: "mc", q: "Plural «der Vater» —", options: ["die Vater","die Väter","die Vaters","die Vateren"], correct: 1 },
      { type: "gap", q: "Plural «das Kind» — die ___ .", answer: "Kinder" },
      { type: "gap", q: "Plural «die Mutter» — die ___ .", answer: "Mütter" },
      { type: "gap", q: "Plural «das Auto» — die ___ .", answer: "Autos" },
      { type: "tf", q: "Слово «Bruder» у множині — Brüder.", correct: true },
      { type: "tf", q: "Plural «Buch» — die Buchs.", correct: false, explain: "die Bücher." },
      { type: "match", prompt: "Зістав:", pairs: [
        { left: "Mann", right: "Männer" },
        { left: "Buch", right: "Bücher" },
        { left: "Auto", right: "Autos" },
        { left: "Frau", right: "Frauen" },
      ]},
      { type: "multi", q: "Які з форм правильні?", options: ["die Kinder","die Kindern","die Häuser","die Hauser","die Männer","die Mans"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe zwei Bruder.", correct: ["Ich habe zwei Brüder."] },
      { type: "order", prompt: "Склади речення:", words: ["sind","Häuser","Die","alt"], correct: ["Die","Häuser","sind","alt"] },
      { type: "translate", prompt: "Переклади:", uk: "Міста гарні.", de: ["Die Städte sind schön."] },
      { type: "writeFree", prompt: "Напиши 3 речення з множиною різних типів.", sample: "Die Kinder lachen. Die Bücher sind neu. Wir haben zwei Autos.", explain: "Перевір умляут і артикль." },
    ],
  },

  // 14 ===================================================================
  "typische-ausnahmen": {
    lesson: {
      slug: "typische-ausnahmen", level: "A1", category: CAT,
      titleDe: "Typische Ausnahmen", titleUk: "Типові винятки",
      goal: "Знати найчастіші A1 винятки, щоб не помилятися в роді й множині.",
      explanation: [
        "Деякі слова порушують правила за змістом або закінченням. Їх потрібно <b>вивчити окремо</b>.",
        "<b>das Mädchen</b> (дівчинка) — середній рід через -chen, хоча йдеться про дівчину.",
        "<b>die Person</b> — жіночий рід для будь-якої особи: <i>Diese Person ist nett</i>, навіть про чоловіка.",
        "<b>der See</b> (озеро) ≠ <b>die See</b> (море). Артикль міняє значення.",
        "<b>das Restaurant, das Hotel, das Café</b> — усі середнього роду, попри французьке походження.",
        "Слова pluralia tantum: <b>die Eltern, die Leute, die Ferien, die Geschwister</b> — лише множина.",
      ],
      table: {
        headers: ["Слово", "Артикль", "Множина", "Особливість"],
        rows: [
          ["Mädchen", "das", "die Mädchen", "-chen → das"],
          ["Person", "die", "die Personen", "завжди die"],
          ["See (озеро)", "der", "die Seen", "der ≠ die!"],
          ["See (море)", "die", "die Seen", "die ≠ der!"],
          ["Restaurant", "das", "die Restaurants", "das + -s"],
          ["Eltern", "die (Pl.)", "—", "тільки множина"],
        ],
      },
      examples: [
        { de: "Das Mädchen ist nett.", uk: "Дівчинка мила." },
        { de: "Diese Person spricht Deutsch.", uk: "Ця особа розмовляє німецькою." },
        { de: "Der See ist tief.", uk: "Озеро глибоке." },
        { de: "Die See ist kalt.", uk: "Море холодне." },
        { de: "Das Restaurant ist neu.", uk: "Ресторан новий." },
        { de: "Meine Eltern wohnen in Wien.", uk: "Мої батьки живуть у Відні." },
        { de: "Die Leute sind freundlich.", uk: "Люди привітні." },
        { de: "Die Ferien beginnen morgen.", uk: "Канікули починаються завтра." },
      ],
      tip: "Винятки <b>не пробуй вивести логічно</b> — зроби з них окрему «червону» карту й переглядай частіше.",
      mistakes: [
        { wrong: "Die Mädchen ist klein.", right: "Das Mädchen ist klein." },
        { wrong: "Der Person ist nett.", right: "Die Person ist nett." },
        { wrong: "Meine Eltern wohnt in Wien.", right: "Meine Eltern wohnen in Wien." },
      ],
      exercises: {},
      prevSlug: "haeufige-pluralformen",
    },
    extras: {
      duration: 10, premium: false,
      learningGoals: [
        "знати головні A1 винятки",
        "не плутати der See / die See",
        "пам'ятати pluralia tantum",
        "узгоджувати дієслово з винятковими словами",
      ],
      ruleBox: {
        rule: "Винятки треба <b>запам'ятати</b>: das Mädchen, die Person, der/die See, das Restaurant; <b>Pl.-only</b>: Eltern, Leute, Ferien, Geschwister.",
      },
      ukrainianTips: [
        "Українське «дівчинка» — ж. рід, німецьке <b>das Mädchen</b> — с. рід через -chen.",
        "Українське «озеро» / «море» — для них у німецькій <b>der See</b> / <b>die See</b>: один корінь, різні артиклі!",
        "<b>die Eltern</b> = батьки, лише множина — дієслово завжди в множині.",
      ],
      languageComparison: {
        commons: ["Винятки існують в обох мовах."],
        diffs: ["Перелік A1 винятків треба знати."],
        traps: ["Логіка не допоможе — лише пам'ять."],
      },
      summary: [
        "<b>das Mädchen</b> — с. рід.",
        "<b>die Person</b> — завжди die.",
        "<b>der See</b> ≠ <b>die See</b>.",
        "<b>Eltern, Leute, Ferien, Geschwister</b> — лише множина.",
        "Винятки вчи окремо.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Артикль до «Mädchen»:", options: ["der","die","das","den"], correct: 2 },
      { type: "mc", q: "Артикль до «Person»:", options: ["der","die","das","den"], correct: 1 },
      { type: "mc", q: "Артикль до «See» (озеро):", options: ["der","die","das","den"], correct: 0 },
      { type: "mc", q: "Артикль до «See» (море):", options: ["der","die","das","den"], correct: 1 },
      { type: "gap", q: "___ Eltern wohnen in Wien.", answer: "Meine", hint: "Pl.-only слово." },
      { type: "gap", q: "___ Ferien beginnen morgen.", answer: "Die" },
      { type: "gap", q: "___ Restaurant ist neu.", answer: "Das" },
      { type: "tf", q: "«die Eltern» — це лише множина.", correct: true },
      { type: "tf", q: "«das Mädchen» — це жіночий рід.", correct: false },
      { type: "match", prompt: "Зістав слово й артикль:", pairs: [
        { left: "Mädchen", right: "das" },
        { left: "Person", right: "die" },
        { left: "See (озеро)", right: "der" },
        { left: "Restaurant", right: "das" },
      ]},
      { type: "multi", q: "Які слова — лише множина?", options: ["Eltern","Tisch","Leute","Ferien","Mädchen"], correct: [0,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Der Person ist nett.", correct: ["Die Person ist nett."] },
      { type: "order", prompt: "Склади речення:", words: ["nett","Person","Diese","ist"], correct: ["Diese","Person","ist","nett"] },
      { type: "translate", prompt: "Переклади:", uk: "Мої батьки живуть у Відні.", de: ["Meine Eltern wohnen in Wien."] },
      { type: "writeFree", prompt: "Напиши 3 речення з винятковими словами.", sample: "Das Mädchen lacht. Die Person ist freundlich. Meine Eltern arbeiten viel.", explain: "Перевір артиклі й узгодження дієслова." },
    ],
  },
};
