// A1 · Дієслова — 8 повних уроків.
// praesens — лишається в lesson.ts + lessonExtensions.ts (там уже 15 вправ).
// Тут додаємо/перевизначаємо 7 нових + добиваємо extras+15 для modalverben і trennbare.

import type { A1Map } from "./_helpers";

const CAT = "Дієслова";

export const verbenA1: A1Map = {
  // =====================================================================
  "regelmaessige-verben": {
    lesson: {
      slug: "regelmaessige-verben",
      level: "A1",
      category: CAT,
      titleDe: "Regelmäßige Verben",
      titleUk: "Правильні дієслова",
      goal: "Утворювати Präsens усіх правильних (слабких) дієслів за єдиним шаблоном «основа + закінчення».",
      explanation: [
        "<b>Правильні</b> (слабкі) дієслова — найбільша і найпростіша група. Їхній корінь не змінюється: lernen → ich lerne, du lernst, er lernt.",
        "Формула проста: береш <b>основу</b> (інфінітив без -en) і додаєш закінчення особи: <b>-e, -st, -t, -en, -t, -en</b>.",
        "Якщо основа закінчується на <b>-t, -d, -chn, -ffn</b> — додаємо <b>-e-</b> для зручної вимови: du arbeit<b>e</b>st, er find<b>e</b>t, es öffn<b>e</b>t.",
        "Якщо основа закінчується на <b>-s, -ss, -ß, -z, -x</b> — у 2 особі однини закінчення <b>тільки -t</b>: du heißt, du tanzt.",
      ],
      table: {
        headers: ["", "machen", "wohnen", "arbeiten", "heißen"],
        rows: [
          ["ich", "mache", "wohne", "arbeite", "heiße"],
          ["du", "machst", "wohnst", "arbeitest", "heißt"],
          ["er/sie/es", "macht", "wohnt", "arbeitet", "heißt"],
          ["wir", "machen", "wohnen", "arbeiten", "heißen"],
          ["ihr", "macht", "wohnt", "arbeitet", "heißt"],
          ["sie/Sie", "machen", "wohnen", "arbeiten", "heißen"],
        ],
      },
      examples: [
        { de: "Ich lerne jeden Tag Deutsch.", uk: "Я вчу німецьку щодня." },
        { de: "Wir wohnen in Berlin.", uk: "Ми живемо в Берліні." },
        { de: "Du arbeitest viel.", uk: "Ти багато працюєш.", tag: "-e- перед -st" },
        { de: "Wie heißt du?", uk: "Як тебе звати?", tag: "-ß → -t" },
        { de: "Anna kauft Brot und Käse.", uk: "Анна купує хліб і сир." },
        { de: "Die Kinder spielen im Park.", uk: "Діти граються в парку." },
        { de: "Ihr macht eine Pause.", uk: "Ви робите перерву." },
        { de: "Er öffnet die Tür.", uk: "Він відчиняє двері.", tag: "-ffn → -et" },
      ],
      tip: "Запам'ятай 6 закінчень як «пісню»: <b>-e, -st, -t, -en, -t, -en</b>. Вони підходять до 90% дієслів A1.",
      mistakes: [
        { wrong: "Du arbeitst viel.", right: "Du arbeitest viel." },
        { wrong: "Er machts Hausaufgaben.", right: "Er macht Hausaufgaben." },
        { wrong: "Wir wohnt in Wien.", right: "Wir wohnen in Wien." },
      ],
      exercises: {},
      prevSlug: "praesens",
      nextSlug: "unregelmaessige-verben",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "впевнено додавати закінчення -e/-st/-t/-en до будь-якого правильного дієслова",
        "вставляти -e- після основ на -t, -d, -chn",
        "правильно обробляти основи на -s, -ß, -z у 2 особі однини",
        "розповідати про щоденні дії: вчитися, працювати, жити, купувати",
      ],
      ruleBox: {
        rule: "<b>Основа + закінчення</b>: ich -e · du -st · er/sie/es -t · wir -en · ihr -t · sie/Sie -en. Основа на -t/-d → перед закінченням додаємо <b>-e-</b>.",
        examples: [
          { de: "ich mache, du machst, er macht", uk: "робити (без особливостей)" },
          { de: "du arbeitest, er arbeitet", uk: "працювати (-e-)" },
        ],
      },
      ukrainianTips: [
        "В українській «я роблю / ти робиш» — закінчення теж змінюється, але у німецькій <b>обов'язково</b> писати займенник: <i>ich mache</i>, не просто <i>mache</i>.",
        "Не плутай <b>du arbeitest</b> з <b>du arbeitst</b> — без -e- слово неможливо вимовити.",
        "У німецькій <b>heißen</b> (зватися) — це звичайне правильне дієслово, але через -ß друга особа: <i>du heißt</i>, а не <i>du heißst</i>.",
      ],
      languageComparison: {
        commons: ["Дієслово змінюється за особами в обох мовах."],
        diffs: ["У німецькій лише 4 унікальні форми, але порядок слів суворіший — дієслово на 2 місці."],
        traps: ["Українська може опускати займенник («працюю»), німецька — ні (<i>ich arbeite</i>)."],
      },
      summary: [
        "Слабкі дієслова <b>не міняють корінь</b>.",
        "Закінчення: -e, -st, -t, -en, -t, -en.",
        "Основа на -t/-d → -e- перед закінченням.",
        "Основа на -s/-ß/-z → <b>du</b>-форма має лише -t.",
        "Дієслово завжди на 2 місці у простому реченні.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ Deutsch.", options: ["lerne","lernst","lernt","lernen"], correct: 0, explain: "ich → -e." },
      { type: "mc", q: "Du ___ in Köln.", options: ["wohne","wohnst","wohnt","wohnen"], correct: 1, explain: "du → -st." },
      { type: "mc", q: "Er ___ einen Apfel.", options: ["kaufe","kaufst","kauft","kaufen"], correct: 2 },
      { type: "mc", q: "Wir ___ Tee.", options: ["trinke","trinkst","trinkt","trinken"], correct: 3, explain: "wir → -en." },
      { type: "tf", q: "У 1 особі однини закінчення завжди -e.", correct: true },
      { type: "gap", q: "Du ___ viel. (arbeiten)", answer: "arbeitest", hint: "Основа на -t → -e- перед -st." },
      { type: "gap", q: "Er ___ die Tür. (öffnen)", answer: "öffnet", hint: "Основа на -ffn → -et." },
      { type: "gap", q: "Wie ___ du? (heißen)", answer: "heißt", hint: "Основа на -ß → лише -t." },
      { type: "gap", q: "Ihr ___ Brot. (kaufen)", answer: "kauft" },
      { type: "match", prompt: "Зістав займенник із формою дієслова «machen»:", pairs: [
        { left: "ich", right: "mache" },
        { left: "du", right: "machst" },
        { left: "wir", right: "machen" },
        { left: "ihr", right: "macht" },
      ]},
      { type: "tf", q: "У формі «du tanzst» закінчення правильне.", correct: false, explain: "Основа на -z → лише -t: du tanzt." },
      { type: "correct", prompt: "Виправ помилку:", wrong: "Wir wohnt in Berlin.", correct: ["Wir wohnen in Berlin."], explain: "wir → -en." },
      { type: "order", prompt: "Склади речення:", words: ["jeden","Tag","Anna","Deutsch","lernt"], correct: ["Anna","lernt","jeden","Tag","Deutsch"], explain: "Дієслово на 2 місці." },
      { type: "translate", prompt: "Переклади німецькою:", uk: "Ти багато працюєш.", de: ["Du arbeitest viel."] },
      { type: "writeFree", prompt: "Напиши 3 речення про себе у Präsens (де живеш, що вчиш, що любиш).", sample: "Ich wohne in Lwiw. Ich lerne Deutsch. Ich liebe Musik.", explain: "Перевір: займенник + дієслово з -e/-st/-t." },
    ],
  },

  // =====================================================================
  "unregelmaessige-verben": {
    lesson: {
      slug: "unregelmaessige-verben",
      level: "A1",
      category: CAT,
      titleDe: "Unregelmäßige Verben",
      titleUk: "Неправильні дієслова",
      goal: "Розпізнавати сильні дієслова та правильно змінювати кореневу голосну у 2 і 3 особі однини.",
      explanation: [
        "<b>Неправильні</b> (сильні) дієслова мають ту саму систему закінчень, але у <b>2 і 3 особі однини</b> змінюють кореневу голосну.",
        "Три головні зміни: <b>a → ä</b> (fahren → du fährst), <b>e → i</b> (sprechen → du sprichst), <b>e → ie</b> (lesen → du liest).",
        "У 1 особі однини, у множині та формі sie/Sie корінь <b>не змінюється</b>: ich fahre, wir fahren, sie fahren.",
        "Список найважливіших A1 сильних дієслів: <b>fahren, schlafen, tragen, laufen, lesen, sehen, sprechen, essen, geben, nehmen, treffen, helfen, fallen, vergessen</b>.",
      ],
      table: {
        headers: ["", "fahren (a→ä)", "sprechen (e→i)", "lesen (e→ie)", "nehmen"],
        rows: [
          ["ich", "fahre", "spreche", "lese", "nehme"],
          ["du", "fährst", "sprichst", "liest", "nimmst"],
          ["er/sie/es", "fährt", "spricht", "liest", "nimmt"],
          ["wir", "fahren", "sprechen", "lesen", "nehmen"],
          ["ihr", "fahrt", "sprecht", "lest", "nehmt"],
          ["sie/Sie", "fahren", "sprechen", "lesen", "nehmen"],
        ],
      },
      examples: [
        { de: "Du fährst nach München.", uk: "Ти їдеш до Мюнхена.", tag: "a → ä" },
        { de: "Er liest gerne Bücher.", uk: "Він любить читати книги.", tag: "e → ie" },
        { de: "Anna spricht Ukrainisch und Deutsch.", uk: "Анна розмовляє українською і німецькою.", tag: "e → i" },
        { de: "Was isst du gern?", uk: "Що ти любиш їсти?", tag: "essen" },
        { de: "Er nimmt den Bus.", uk: "Він їде автобусом.", tag: "nehmen" },
        { de: "Sie schläft bis 9 Uhr.", uk: "Вона спить до 9-ї." },
        { de: "Ich helfe dir gern.", uk: "Я залюбки тобі допоможу.", tag: "1 ос. — без змін" },
        { de: "Wir treffen Freunde am Samstag.", uk: "У суботу ми зустрічаємось із друзями." },
      ],
      tip: "У <b>nehmen</b> зміна особлива: e → i + подвоюється m: ich nehme → du <b>nimm</b>st, er <b>nimm</b>t.",
      mistakes: [
        { wrong: "Du fahrst nach Wien.", right: "Du fährst nach Wien." },
        { wrong: "Er liest ein Buch — ich liest auch.", right: "Er liest ein Buch — ich lese auch." },
        { wrong: "Du nehmst den Bus.", right: "Du nimmst den Bus." },
      ],
      exercises: {},
      prevSlug: "regelmaessige-verben",
      nextSlug: "sein-haben",
    },
    extras: {
      duration: 15,
      premium: false,
      learningGoals: [
        "відрізняти сильні дієслова від слабких",
        "змінювати голосну a→ä, e→i, e→ie у du/er/sie/es",
        "правильно вживати nehmen, lesen, sprechen, fahren",
        "розповідати про їжу, транспорт, читання, мови",
      ],
      ruleBox: {
        rule: "Зміна кореневої голосної <b>тільки у du і er/sie/es</b>: a → ä · e → i · e → ie. У множині й 1 ос. одн. — без змін.",
        examples: [
          { de: "ich fahre — du fährst — er fährt — wir fahren", uk: "fahren (a→ä)" },
          { de: "ich lese — du liest — er liest", uk: "lesen (e→ie)" },
        ],
      },
      ukrainianTips: [
        "В українській корінь теж може змінюватися (іти → йду), але <b>не за тим самим правилом</b>. Не намагайся вгадати — вчи список сильних дієслів.",
        "У 1 особі однини сильне дієслово виглядає як звичайне слабке: <i>ich fahre</i>, <i>ich lese</i>. Помилки починаються з du/er.",
        "<b>nehmen</b> — найхитріше A1-дієслово: запам'ятай вираз «<i>ich nehme — du nimmst — er nimmt</i>».",
      ],
      languageComparison: {
        commons: ["Як і в українській, корінь може змінюватися — це треба запам'ятовувати окремо."],
        diffs: ["У німецькій зміна суворо в 2 і 3 особі однини, а не в інших формах."],
        traps: ["Не казати «ich fährt» — у 1 ос. одн. голосна <b>не</b> змінюється."],
      },
      summary: [
        "Зміна кореня <b>тільки</b> у du, er/sie/es.",
        "<b>a → ä</b>: fahren, schlafen, tragen, laufen, fallen.",
        "<b>e → i</b>: sprechen, essen, geben, helfen, treffen, nehmen.",
        "<b>e → ie</b>: lesen, sehen, empfehlen.",
        "<b>nehmen</b> — особливе: ich nehme → du nimmst.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Du ___ schnell. (fahren)", options: ["fahre","fahrst","fährst","fährest"], correct: 2, explain: "a → ä + -st." },
      { type: "mc", q: "Er ___ ein Buch. (lesen)", options: ["lese","lest","liest","list"], correct: 2, explain: "e → ie." },
      { type: "mc", q: "Anna ___ Deutsch. (sprechen)", options: ["spreche","sprecht","spricht","sprichst"], correct: 2 },
      { type: "mc", q: "Was ___ du gern? (essen)", options: ["isst","esst","essen","ist"], correct: 0, explain: "du isst — e → i." },
      { type: "tf", q: "У 1 особі однини сильне дієслово змінює корінь.", correct: false, explain: "Ні, лише у du/er/sie/es." },
      { type: "gap", q: "Er ___ den Bus. (nehmen)", answer: "nimmt", hint: "e → i + подвоєння m." },
      { type: "gap", q: "Du ___ bis 8 Uhr. (schlafen)", answer: "schläfst", hint: "a → ä." },
      { type: "gap", q: "Sie ___ einen Film. (sehen, 3 Sg.)", answer: "sieht" },
      { type: "gap", q: "Ihr ___ Pizza. (essen)", answer: "esst", hint: "У ihr-форми корінь без змін." },
      { type: "match", prompt: "Зістав інфінітив із формою «er»:", pairs: [
        { left: "fahren", right: "fährt" },
        { left: "lesen", right: "liest" },
        { left: "sprechen", right: "spricht" },
        { left: "nehmen", right: "nimmt" },
      ]},
      { type: "multi", q: "Виділи всі правильні форми (можуть бути кілька):", options: ["du fährst","du fahrst","er liest","er lest","ich nimme","ich nehme"], correct: [0,2,5], explain: "ich nehme (без змін у 1 ос. одн.)." },
      { type: "correct", prompt: "Виправ помилку:", wrong: "Du nehmst den Zug.", correct: ["Du nimmst den Zug."] },
      { type: "order", prompt: "Склади речення:", words: ["liest","Buch","ein","Er","abends"], correct: ["Er","liest","abends","ein","Buch"] },
      { type: "translate", prompt: "Переклади:", uk: "Він говорить німецькою дуже добре.", de: ["Er spricht sehr gut Deutsch.","Er spricht Deutsch sehr gut."] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними сильними дієсловами (наприклад про їжу, дорогу, читання).", sample: "Ich esse gern Pasta. Mein Bruder fährt nach Wien. Anna liest ein Buch.", explain: "Перевір, що зміна голосної є тільки в du/er/sie/es." },
    ],
  },

  // =====================================================================
  "sein-haben": {
    lesson: {
      slug: "sein-haben",
      level: "A1",
      category: CAT,
      titleDe: "sein und haben",
      titleUk: "Дієслова sein і haben",
      goal: "Відмінювати найважливіші дієслова німецької — sein (бути) і haben (мати).",
      explanation: [
        "<b>sein</b> = «бути». Уживається, щоб назвати ім'я, професію, національність, вік, стан: <i>Ich bin Anna. Er ist Lehrer. Wir sind müde.</i>",
        "<b>haben</b> = «мати». Уживається для володіння, родини, віку, опису: <i>Ich habe zwei Brüder. Sie hat braune Augen.</i>",
        "Обидва дієслова <b>неправильні</b> й мають унікальні форми — їх потрібно <b>вивчити напам'ять</b>.",
        "У німецькій вік виражається через <b>sein</b>: <i>Ich bin 25 (Jahre alt).</i> — не через «мати», як в українській «мені 25».",
      ],
      table: {
        headers: ["", "sein (бути)", "haben (мати)"],
        rows: [
          ["ich", "bin", "habe"],
          ["du", "bist", "hast"],
          ["er/sie/es", "ist", "hat"],
          ["wir", "sind", "haben"],
          ["ihr", "seid", "habt"],
          ["sie/Sie", "sind", "haben"],
        ],
      },
      examples: [
        { de: "Ich bin Anna. Ich komme aus Lwiw.", uk: "Я — Анна. Я з Львова." },
        { de: "Du bist sehr nett.", uk: "Ти дуже милий/мила." },
        { de: "Er ist Arzt von Beruf.", uk: "Він лікар за фахом." },
        { de: "Wir sind müde nach der Arbeit.", uk: "Ми втомилися після роботи." },
        { de: "Ich habe einen Bruder und eine Schwester.", uk: "У мене є брат і сестра." },
        { de: "Sie hat lange braune Haare.", uk: "У неї довге каштанове волосся." },
        { de: "Habt ihr Hunger?", uk: "Ви голодні?", tag: "Hunger haben" },
        { de: "Wie alt bist du? — Ich bin 28.", uk: "Скільки тобі років? — Мені 28.", tag: "вік → sein" },
      ],
      tip: "Сталі вирази з <b>haben</b>: Hunger haben, Durst haben, Angst haben, Recht haben, Zeit haben — українською часто перекладаються як «бути» чи «бути в».",
      mistakes: [
        { wrong: "Ich habe 25 Jahre.", right: "Ich bin 25 Jahre alt." },
        { wrong: "Du bin Lehrer.", right: "Du bist Lehrer." },
        { wrong: "Wir habt Zeit.", right: "Wir haben Zeit." },
      ],
      exercises: {},
      prevSlug: "unregelmaessige-verben",
      nextSlug: "modalverben",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "знати всі форми sein і haben напам'ять",
        "представляти себе: ім'я, вік, професія, національність",
        "описувати сім'ю та зовнішність через haben",
        "уникати кальки «мені 20 років» → «ich habe 20»",
      ],
      ruleBox: {
        rule: "<b>sein</b>: ich bin · du bist · er ist · wir sind · ihr seid · sie sind. <b>haben</b>: ich habe · du hast · er hat · wir haben · ihr habt · sie haben.",
        examples: [
          { de: "Ich bin Studentin.", uk: "Я — студентка." },
          { de: "Ich habe Zeit.", uk: "У мене є час." },
        ],
      },
      ukrainianTips: [
        "Українське «я є вчителем» — рідкісне. Німецьке <b>«ich bin Lehrer»</b> — звичайна форма, артикль не ставиться.",
        "Вік: німецькою через <b>sein</b> (<i>ich bin 30</i>), а не через haben.",
        "Сімейні відносини: завжди <b>haben</b> + неозначений артикль: <i>Ich habe <b>einen</b> Bruder, <b>eine</b> Schwester, <b>ein</b> Kind</i>.",
      ],
      languageComparison: {
        commons: ["sein/haben — найвживаніші дієслова й тут, і в українській."],
        diffs: ["Вік: німецькою «бути N років», українською «мати N років».", "Перед професією артикль не ставиться: <i>Er ist Arzt.</i>"],
        traps: ["«Ich habe Hunger» — «я голодний», не «я маю голод»."],
      },
      summary: [
        "<b>sein</b> = бути (ich bin, du bist, er ist…).",
        "<b>haben</b> = мати (ich habe, du hast, er hat…).",
        "Професія / національність → sein, <b>без артикля</b>.",
        "Вік → sein: <i>ich bin 25</i>.",
        "Hunger/Durst/Angst/Zeit → завжди з haben.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ aus der Ukraine.", options: ["bin","bist","ist","sind"], correct: 0 },
      { type: "mc", q: "Du ___ sehr freundlich.", options: ["bin","bist","ist","seid"], correct: 1 },
      { type: "mc", q: "Wir ___ Studenten.", options: ["bin","bist","sind","seid"], correct: 2 },
      { type: "mc", q: "Ihr ___ Hunger?", options: ["hat","habt","habe","hast"], correct: 1 },
      { type: "gap", q: "Er ___ zwei Kinder. (haben)", answer: "hat" },
      { type: "gap", q: "Sie (Pl.) ___ aus Berlin. (sein)", answer: "sind" },
      { type: "gap", q: "Wie alt ___ du? (sein)", answer: "bist" },
      { type: "tf", q: "Вік у німецькій виражається через haben: «ich habe 30 Jahre».", correct: false, explain: "Через sein: ich bin 30." },
      { type: "tf", q: "У реченні «Er ist Lehrer» артикль не потрібен.", correct: true },
      { type: "match", prompt: "Зістав займенник із формою haben:", pairs: [
        { left: "ich", right: "habe" },
        { left: "du", right: "hast" },
        { left: "er", right: "hat" },
        { left: "wir", right: "haben" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe 22 Jahre.", correct: ["Ich bin 22.","Ich bin 22 Jahre alt."] },
      { type: "correct", prompt: "Виправ:", wrong: "Du bin müde.", correct: ["Du bist müde."] },
      { type: "order", prompt: "Склади речення:", words: ["habe","Bruder","einen","Ich"], correct: ["Ich","habe","einen","Bruder"] },
      { type: "translate", prompt: "Переклади:", uk: "У мене є сестра і собака.", de: ["Ich habe eine Schwester und einen Hund."] },
      { type: "writeFree", prompt: "Напиши 3 речення про себе: ім'я, вік, родина (sein + haben).", sample: "Ich bin Olena. Ich bin 27 Jahre alt. Ich habe einen Bruder.", explain: "Sein для опису, haben для володіння." },
    ],
  },

  // =====================================================================
  modalverben: {
    // lesson вже у lessons.ts — тут лише extras + 15
    extras: {
      duration: 18,
      premium: false,
      learningGoals: [
        "розрізняти 6 модальних дієслів: können, müssen, dürfen, sollen, wollen, möchten",
        "правильно будувати рамкову конструкцію: модальне на 2 місці, Infinitiv у кінці",
        "не плутати nicht müssen (не обов'язково) і nicht dürfen (заборонено)",
        "ввічливо просити з möchten",
      ],
      ruleBox: {
        rule: "<b>Модальне дієслово (Position 2) + … + Infinitiv (Satzende)</b>. В 1 і 3 особі однини закінчення немає: <i>ich kann · er kann</i>.",
        examples: [
          { de: "Ich kann gut Deutsch sprechen.", uk: "Я добре вмію розмовляти німецькою." },
          { de: "Hier darf man nicht rauchen.", uk: "Тут не можна курити." },
        ],
      },
      ukrainianTips: [
        "В українській «мушу йти», «можу прийти» — модальне і смислове дієслово поряд. У німецькій <b>Infinitiv іде в кінець</b>: <i>Ich muss <b>gehen</b></i>, <i>Ich kann <b>kommen</b></i>.",
        "<b>nicht müssen</b> ≠ заборона! Це «не обов'язково». Заборона = <b>nicht dürfen</b>: <i>Du darfst nicht rauchen.</i>",
        "<b>möchten</b> — це ввічлива форма «хотів би». Використовуй у магазинах, ресторанах: <i>Ich möchte einen Kaffee.</i>",
      ],
      languageComparison: {
        commons: ["І там, і там модальні слова виражають бажання, обов'язок, дозвіл."],
        diffs: ["У німецькій смислове дієслово завжди йде <b>в кінці</b> у формі Infinitiv."],
        traps: ["«Я мушу не йти» ≠ «ich muss nicht gehen» (це «мені не треба йти»). Заборона: «ich darf nicht gehen»."],
      },
      summary: [
        "6 модальних: <b>können, müssen, dürfen, sollen, wollen, möchten</b>.",
        "В 1 і 3 ос. одн. — <b>без закінчення</b>.",
        "Інфінітив смислового дієслова — <b>в кінці</b>.",
        "<b>möchten</b> — ввічлива форма «хотів би».",
        "<b>nicht dürfen</b> = заборона; <b>nicht müssen</b> = необов'язково.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ gut schwimmen.", options: ["kann","muss","darf","will"], correct: 0 },
      { type: "mc", q: "Du ___ jetzt nach Hause gehen.", options: ["kannst","musst","darfst","willst"], correct: 1 },
      { type: "mc", q: "Hier ___ man nicht parken.", options: ["kann","muss","darf","will"], correct: 2, explain: "Заборона → nicht dürfen." },
      { type: "mc", q: "Ich ___ einen Kaffee, bitte.", options: ["kann","muss","möchte","soll"], correct: 2, explain: "Ввічливе бажання → möchte." },
      { type: "gap", q: "Er ___ Deutsch lernen. (wollen)", answer: "will" },
      { type: "gap", q: "Wir ___ um 8 Uhr aufstehen. (müssen)", answer: "müssen" },
      { type: "gap", q: "___ ich Ihnen helfen? (können)", answer: "Kann" },
      { type: "tf", q: "В 1 і 3 особі однини модальні дієслова не мають закінчення.", correct: true },
      { type: "tf", q: "«Du musst nicht kommen» означає «тобі заборонено приходити».", correct: false, explain: "Це «тобі необов'язково приходити»." },
      { type: "match", prompt: "Зістав значення:", pairs: [
        { left: "können", right: "вміти, могти" },
        { left: "müssen", right: "мусити" },
        { left: "dürfen", right: "мати дозвіл" },
        { left: "möchten", right: "хотів би" },
      ]},
      { type: "multi", q: "Виділи всі правильні речення:", options: [
        "Ich kann sprechen Deutsch.",
        "Ich kann Deutsch sprechen.",
        "Er muss arbeitet.",
        "Er muss arbeiten.",
        "Wir möchten ein Pizza.",
      ], correct: [1,3], explain: "Infinitiv у кінці; möchten + Akk: eine Pizza." },
      { type: "correct", prompt: "Виправ:", wrong: "Er kannt gut singen.", correct: ["Er kann gut singen."] },
      { type: "order", prompt: "Склади речення:", words: ["nach","Berlin","Ich","will","fahren"], correct: ["Ich","will","nach","Berlin","fahren"] },
      { type: "translate", prompt: "Переклади:", uk: "Тут не можна курити.", de: ["Hier darf man nicht rauchen.","Man darf hier nicht rauchen."] },
      { type: "writeFree", prompt: "Напиши 3 речення з 3 різними модальними дієсловами про свій день.", sample: "Ich muss früh aufstehen. Ich kann gut kochen. Am Abend möchte ich einen Film sehen.", explain: "Перевір: модальне на 2 місці, Infinitiv у кінці." },
    ],
  },

  // =====================================================================
  trennbare: {
    // lesson уже у lessons.ts — тут extras + 15
    extras: {
      duration: 15,
      premium: false,
      learningGoals: [
        "розпізнавати відокремлювані префікси за наголосом",
        "правильно ставити префікс у кінець у Präsens",
        "будувати Perfekt: префікс + ge + основа + t/en",
        "зʼєднувати дієслово в підрядному реченні",
      ],
      ruleBox: {
        rule: "У головному реченні відокремлюваний префікс <b>стоїть у кінці</b>: <i>Ich stehe um 7 Uhr <b>auf</b>.</i> У Perfekt — <b>auf<u>ge</u>standen</b>. У підрядному — знову разом: <i>…, weil ich aufstehe</i>.",
        examples: [
          { de: "Ich rufe dich morgen an.", uk: "Я тобі завтра зателефоную." },
          { de: "Sie ist früh aufgestanden.", uk: "Вона рано встала." },
        ],
      },
      ukrainianTips: [
        "В українській «прийти, зайти, вийти» — префікс приклеєний. У німецькій він <b>летить у кінець</b>: <i>Ich komme um 8 Uhr an.</i>",
        "Якщо префікс <b>наголошений</b> (<b>ʼauf</b>stehen, <b>ʼan</b>rufen) — він відокремлюється. Якщо ненаголошений (be-, ver-, ent-) — ні.",
        "У Perfekt <b>-ge-</b> ставиться між префіксом і основою: aufgestanden, eingekauft, mitgenommen.",
      ],
      languageComparison: {
        commons: ["Префікси і там, і там додають значення (вгору, всередину, з кимось)."],
        diffs: ["У німецькій вони фізично відокремлюються від дієслова в реченні."],
        traps: ["Не плутати: <b>be</b>kommen ≠ kommen + be. «bekommen» = отримувати, префікс не відокремлюється."],
      },
      summary: [
        "Найчастіші: <b>auf-, an-, ab-, aus-, ein-, mit-, vor-, zu-, weg-, fern-</b>.",
        "Префікс <b>наголошений</b> → відокремлюється.",
        "У Präsens / Imperativ → у кінці речення.",
        "У Perfekt → <b>префікс + ge + основа + t/en</b>.",
        "У підрядному реченні (weil, dass) — знову одне слово.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ um 7 Uhr ___.", options: ["stehe / auf","aufstehe / —","stehe auf / —","auf / stehe"], correct: 0 },
      { type: "mc", q: "Wann ___ der Film ___?", options: ["fängt / an","anfängt / —","fängt an / —","an / fängt"], correct: 0 },
      { type: "mc", q: "Bitte ___ die Tür ___! (zumachen)", options: ["zumach / —","mach / zu","mache zu / —","zu / mache"], correct: 1 },
      { type: "gap", q: "Er ___ um 6 ___. (aufstehen) — перша частина", answer: "steht" },
      { type: "gap", q: "Er steht um 6 ___. (aufstehen) — префікс", answer: "auf" },
      { type: "gap", q: "Sie ist früh ___. (aufstehen, Partizip II)", answer: "aufgestanden" },
      { type: "gap", q: "Ich ___ heute ein ___. (einkaufen) — перша частина", answer: "kaufe" },
      { type: "tf", q: "У підрядному реченні префікс знову з'єднується з дієсловом.", correct: true, explain: "…, weil ich aufstehe." },
      { type: "tf", q: "Префікс «be-» відокремлюється.", correct: false, explain: "be- ненаголошений → не відокремлюється." },
      { type: "match", prompt: "Зістав інфінітив із значенням:", pairs: [
        { left: "aufstehen", right: "вставати" },
        { left: "einkaufen", right: "робити покупки" },
        { left: "anrufen", right: "телефонувати" },
        { left: "mitkommen", right: "піти разом" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich rufe dich morgen an.",
        "Ich anrufe dich morgen.",
        "Wann fängt der Film an?",
        "Wann anfängt der Film?",
      ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Er aufsteht um 6 Uhr.", correct: ["Er steht um 6 Uhr auf."] },
      { type: "order", prompt: "Склади речення:", words: ["früh","stehe","Ich","auf"], correct: ["Ich","stehe","früh","auf"] },
      { type: "translate", prompt: "Переклади:", uk: "Я тобі завтра зателефоную.", de: ["Ich rufe dich morgen an."] },
      { type: "writeFree", prompt: "Опиши свій ранок 3 реченнями з відокремлюваними дієсловами (aufstehen, anziehen, mitnehmen).", sample: "Ich stehe um 7 Uhr auf. Ich ziehe mich schnell an. Ich nehme mein Buch mit.", explain: "Перевір: префікс — у кінці речення." },
    ],
  },

  // =====================================================================
  "reflexive-basis": {
    lesson: {
      slug: "reflexive-basis",
      level: "A1",
      category: CAT,
      titleDe: "Reflexive Verben: Grundlagen",
      titleUk: "Основи зворотних дієслів",
      goal: "Розуміти, коли потрібен зворотний займенник, і правильно його ставити в Akkusativ.",
      explanation: [
        "<b>Зворотні дієслова</b> описують дію, яка повертається до самого субʼєкта: <i>sich waschen</i> — мити себе, <i>sich freuen</i> — радіти.",
        "У словнику вони позначаються як <b>sich + Infinitiv</b>: <i>sich freuen, sich interessieren, sich erinnern</i>.",
        "Зворотний займенник у Akkusativ стоїть одразу після дієслова (Position 3): <i>Ich freue <b>mich</b>. Du wäschst <b>dich</b>.</i>",
        "У 3 особі однини, множині та для Sie — завжди <b>sich</b>: <i>Er freut sich. Wir freuen uns. Sie (Sie) freut sich / freuen sich.</i>",
      ],
      table: {
        headers: ["Pronomen", "Reflexivpronomen (Akk.)", "Beispiel"],
        rows: [
          ["ich", "mich", "Ich freue mich."],
          ["du", "dich", "Du wäschst dich."],
          ["er/sie/es", "sich", "Er freut sich."],
          ["wir", "uns", "Wir setzen uns."],
          ["ihr", "euch", "Ihr beeilt euch."],
          ["sie/Sie", "sich", "Sie interessieren sich für Musik."],
        ],
      },
      examples: [
        { de: "Ich freue mich auf das Wochenende.", uk: "Я тішуся, що буде вихідний." },
        { de: "Du wäschst dich morgens.", uk: "Ти миєшся вранці." },
        { de: "Er interessiert sich für Sport.", uk: "Він цікавиться спортом." },
        { de: "Wir setzen uns an den Tisch.", uk: "Ми сідаємо за стіл." },
        { de: "Beeilt euch, der Bus kommt!", uk: "Поспішайте, автобус їде!" },
        { de: "Sie erinnert sich an Berlin.", uk: "Вона згадує Берлін." },
        { de: "Ich entschuldige mich.", uk: "Я перепрошую." },
        { de: "Wie fühlst du dich heute?", uk: "Як ти себе сьогодні почуваєш?" },
      ],
      tip: "Зворотний займенник Akk. збігається з особовим у Akk. (mich, dich, uns, euch). Тільки 3 особа і Sie має <b>окрему</b> форму — <b>sich</b>.",
      mistakes: [
        { wrong: "Ich freue mir.", right: "Ich freue mich." },
        { wrong: "Er interessiert ihn für Musik.", right: "Er interessiert sich für Musik." },
        { wrong: "Wir setzen wir an den Tisch.", right: "Wir setzen uns an den Tisch." },
      ],
      exercises: {},
      prevSlug: "trennbare",
      nextSlug: "imperativ-basis",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "розпізнавати зворотні дієслова за поміткою «sich»",
        "ставити правильний рефлексивний займенник у Akkusativ",
        "будувати речення в усіх 6 особах",
        "уживати найважливіші A1 зворотні дієслова",
      ],
      ruleBox: {
        rule: "Zwortні займенники (Akk.): <b>mich, dich, sich, uns, euch, sich</b>. Стоять одразу після відмінюваного дієслова.",
        examples: [
          { de: "Ich freue mich.", uk: "Я радію." },
          { de: "Er wäscht sich.", uk: "Він миється." },
        ],
      },
      ukrainianTips: [
        "В українській «-ся» приліплюється до дієслова. У німецькій — це <b>окреме слово</b> після дієслова.",
        "Не завжди українське «-ся» = німецьке sich: <i>сміятися</i> = <b>lachen</b> (без sich), а <i>радіти</i> = <b>sich freuen</b> (з sich).",
        "У 3 особі й Sie — завжди <b>sich</b>, не «ihn/sie/sie»: <i>Er freut sich</i>, а не <i>er freut ihn</i>.",
      ],
      languageComparison: {
        commons: ["Концепція «дія на себе» однакова."],
        diffs: ["У німецькій займенник окремий і має різні форми за особами."],
        traps: ["Список зворотних дієслів у двох мовах не збігається — вчити окремо."],
      },
      summary: [
        "Список: <b>mich, dich, sich, uns, euch, sich</b>.",
        "Дієслово словник: <i>sich + Infinitiv</i>.",
        "Займенник одразу після дієслова.",
        "У 3 ос. і Sie — завжди <b>sich</b>.",
        "Українське «-ся» ≠ автоматично sich.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich freue ___ auf das Wochenende.", options: ["mir","mich","sich","uns"], correct: 1 },
      { type: "mc", q: "Er interessiert ___ für Musik.", options: ["ihn","sich","ihm","es"], correct: 1 },
      { type: "mc", q: "Wir setzen ___ an den Tisch.", options: ["uns","wir","sich","euch"], correct: 0 },
      { type: "mc", q: "Beeilt ___, bitte!", options: ["dich","euch","sich","uns"], correct: 1 },
      { type: "gap", q: "Du wäschst ___ . (sich waschen)", answer: "dich" },
      { type: "gap", q: "Sie (Pl.) freuen ___ . ", answer: "sich" },
      { type: "gap", q: "Ich entschuldige ___ .", answer: "mich" },
      { type: "tf", q: "У 3 особі однини зворотний займенник — sich.", correct: true },
      { type: "tf", q: "Wir-форма має рефлексивний займенник «wir».", correct: false, explain: "Це «uns»." },
      { type: "match", prompt: "Зістав займенник із рефлексивним:", pairs: [
        { left: "ich", right: "mich" },
        { left: "du", right: "dich" },
        { left: "wir", right: "uns" },
        { left: "ihr", right: "euch" },
      ]},
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich freue mich.",
        "Ich freue mir.",
        "Er wäscht sich.",
        "Er wäscht ihn.",
      ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Wir interessieren wir für Kunst.", correct: ["Wir interessieren uns für Kunst."] },
      { type: "order", prompt: "Склади речення:", words: ["mich","Ich","gut","fühle"], correct: ["Ich","fühle","mich","gut"] },
      { type: "translate", prompt: "Переклади:", uk: "Він цікавиться футболом.", de: ["Er interessiert sich für Fußball."] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними зворотними дієсловами (sich freuen, sich waschen, sich interessieren).", sample: "Ich freue mich auf den Urlaub. Mein Bruder wäscht sich. Anna interessiert sich für Kunst.", explain: "Перевір рефлексивний займенник." },
    ],
  },

  // =====================================================================
  "imperativ-basis": {
    lesson: {
      slug: "imperativ-basis",
      level: "A1",
      category: CAT,
      titleDe: "Imperativ: Grundlagen",
      titleUk: "Основи наказового способу",
      goal: "Утворювати накази й прохання для du, ihr і Sie на базовому рівні.",
      explanation: [
        "<b>Imperativ</b> — форма для прохань, наказів, порад: <i>Komm! Hilf mir! Sprechen Sie bitte langsamer.</i>",
        "<b>du-форма</b>: основа дієслова <b>без -st</b>, займенник опускається: <i>du kommst → Komm!</i>, <i>du lernst → Lern Deutsch!</i>",
        "<b>ihr-форма</b>: збігається з формою ihr у Präsens, без займенника: <i>ihr kommt → Kommt!</i>, <i>ihr lest → Lest!</i>",
        "<b>Sie-форма</b>: дієслово + Sie: <i>Kommen Sie! Sprechen Sie bitte langsam!</i>",
        "Сильні дієслова з <b>e → i/ie</b> зберігають зміну в du-формі: <i>du sprichst → Sprich!</i>, <i>du liest → Lies!</i> Сильні з <b>a → ä</b> у Imperativ <b>без умляуту</b>: <i>du fährst → Fahr!</i>",
      ],
      table: {
        headers: ["Інфінітив", "du", "ihr", "Sie"],
        rows: [
          ["machen", "Mach!", "Macht!", "Machen Sie!"],
          ["kommen", "Komm!", "Kommt!", "Kommen Sie!"],
          ["sprechen", "Sprich!", "Sprecht!", "Sprechen Sie!"],
          ["lesen", "Lies!", "Lest!", "Lesen Sie!"],
          ["fahren", "Fahr!", "Fahrt!", "Fahren Sie!"],
          ["sein", "Sei!", "Seid!", "Seien Sie!"],
        ],
      },
      examples: [
        { de: "Komm her, bitte!", uk: "Іди сюди, будь ласка!" },
        { de: "Sprich langsam!", uk: "Розмовляй повільно!", tag: "e → i зберігається" },
        { de: "Lies das Buch!", uk: "Прочитай книгу!", tag: "e → ie зберігається" },
        { de: "Fahr vorsichtig!", uk: "Їдь обережно!", tag: "a → a (без умляуту)" },
        { de: "Kommt schnell!", uk: "Швидко йдіть сюди!", tag: "ihr" },
        { de: "Nehmen Sie Platz, bitte.", uk: "Сідайте, будь ласка.", tag: "Sie" },
        { de: "Seid leise im Klassenzimmer!", uk: "Тихо в класі!", tag: "sein → ihr" },
        { de: "Mach bitte das Fenster auf!", uk: "Відчини, будь ласка, вікно!", tag: "trennbar" },
      ],
      tip: "Слово <b>bitte</b> робить наказ ввічливим: <i>Komm bitte!</i> або <i>Bitte komm!</i> Без bitte звучить різко.",
      mistakes: [
        { wrong: "Du komm her!", right: "Komm her!" },
        { wrong: "Sprech langsam!", right: "Sprich langsam!" },
        { wrong: "Fährst vorsichtig!", right: "Fahr vorsichtig!" },
      ],
      exercises: {},
      prevSlug: "reflexive-basis",
      nextSlug: "perfekt",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "будувати du/ihr/Sie-форми для звичайних дієслів",
        "зберігати зміну e → i/ie у du-формі сильних дієслів",
        "не вживати умляут у du-формі при a → ä",
        "додавати bitte для ввічливості",
      ],
      ruleBox: {
        rule: "<b>du</b>: основа без -st. <b>ihr</b>: як у Präsens. <b>Sie</b>: Infinitiv + Sie. У du-формі зміна e→i/ie <b>зберігається</b>, але a→ä <b>знімається</b>.",
        examples: [
          { de: "Komm! / Kommt! / Kommen Sie!", uk: "Іди / йдіть / йдіть (вв.)" },
          { de: "Sprich! / Sprecht! / Sprechen Sie!", uk: "Розмовляй!" },
        ],
      },
      ukrainianTips: [
        "В українській наказ часто = окрема форма («іди!», «прочитай!»). У німецькій — <b>основа дієслова</b>, без займенника.",
        "Ввічлива форма <b>Sie</b> — це звичайний інфінітив + Sie: <i>Kommen Sie bitte!</i> Не плутати з du.",
        "Сильні з a→ä в Imperativ <b>не</b> мають умляуту: <i>Fahr!</i>, а не <i>Fähr!</i>",
      ],
      languageComparison: {
        commons: ["Прохання можна казати різко або з «будь ласка»."],
        diffs: ["У німецькій 3 окремі форми залежно від адресата (du/ihr/Sie)."],
        traps: ["Не казати «Du komm!» — займенник опускається."],
      },
      summary: [
        "<b>du</b> = основа без -st, без займенника.",
        "<b>ihr</b> = форма Präsens без займенника.",
        "<b>Sie</b> = Infinitiv + Sie.",
        "e → i/ie у du <b>зберігається</b>; a → ä <b>знімається</b>.",
        "<b>bitte</b> робить наказ ввічливим.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Як буде Imperativ du від «kommen»?", options: ["Kommst!","Komm!","Du komm!","Kommen!"], correct: 1 },
      { type: "mc", q: "Як буде Imperativ du від «sprechen»?", options: ["Sprech!","Sprich!","Sprichst!","Sprechst!"], correct: 1, explain: "e → i зберігається." },
      { type: "mc", q: "Як буде Imperativ Sie від «nehmen»?", options: ["Nimm Sie!","Nehmen Sie!","Nimmst Sie!","Nehmt Sie!"], correct: 1 },
      { type: "mc", q: "Як буде Imperativ du від «fahren»?", options: ["Fähr!","Fahr!","Fahrst!","Fahrt!"], correct: 1, explain: "a → ä знімається." },
      { type: "gap", q: "___ leise! (ihr, sein)", answer: "Seid" },
      { type: "gap", q: "___ das Fenster auf! (du, aufmachen) — перша частина", answer: "Mach" },
      { type: "gap", q: "___ Sie bitte langsam! (sprechen)", answer: "Sprechen" },
      { type: "tf", q: "У формі «Du komm!» займенник правильно лишити.", correct: false, explain: "Займенник опускається: Komm!" },
      { type: "tf", q: "У сильних дієслів a→ä в Imperativ умляут зберігається.", correct: false, explain: "Знімається: Fahr! Schlaf!" },
      { type: "match", prompt: "Зістав інфінітив із du-формою:", pairs: [
        { left: "lesen", right: "Lies!" },
        { left: "essen", right: "Iss!" },
        { left: "geben", right: "Gib!" },
        { left: "schlafen", right: "Schlaf!" },
      ]},
      { type: "multi", q: "Виділи правильні du-форми:", options: [
        "Komm!",
        "Du kommst!",
        "Sprich!",
        "Sprech!",
        "Lies!",
        "Liest!",
      ], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Fähr vorsichtig!", correct: ["Fahr vorsichtig!"] },
      { type: "order", prompt: "Склади ввічливе прохання:", words: ["bitte","mir","Helfen","Sie"], correct: ["Helfen","Sie","mir","bitte"] },
      { type: "translate", prompt: "Переклади (ввічливо, Sie):", uk: "Сідайте, будь ласка.", de: ["Nehmen Sie bitte Platz.","Setzen Sie sich bitte."] },
      { type: "writeFree", prompt: "Напиши 3 короткі прохання: одне для du, одне для ihr, одне для Sie.", sample: "Komm bitte schnell! Macht die Tür zu! Sprechen Sie bitte lauter.", explain: "Перевір: без займенника для du/ihr, з Sie для ввічливості." },
    ],
  },

  // =====================================================================
  // praesens — extras+15 уже в lessonExtensions.ts; не дублюємо.
};
