// C1 · Verben — 14 повних уроків (konjunktiv1 уже покритий базовим модулем lessonExtensions).
import type { C1Map } from "./_helpers";
const CAT = "Дієслова";

export const verbenC1: C1Map = {
  "konjunktiv2-komplex": {
    lesson: {
      slug: "konjunktiv2-komplex", level: "C1", category: CAT,
      titleDe: "Konjunktiv II in komplexen Aussagen", titleUk: "Konjunktiv II у складних умовних конструкціях",
      goal: "Використовувати Konjunktiv II у багатоскладових реченнях: подвійні умови, докір, ввічливість, гіпотези про минуле.",
      explanation: [
        "На C1 <b>Konjunktiv II</b> виходить за межі простого «wenn…». Він виражає <b>дипломатичну дистанцію</b>, обережні припущення, докір, самокритику та контрфактичні аналізи.",
        "У формальному стилі часто вживається <b>würde + Infinitiv</b> замість архаїчних форм (<i>würde tragen</i> замість <i>trüge</i>), однак від <i>haben, sein, werden</i> і модальних <b>краще залишати класичну форму</b> (<i>hätte, wäre, würde, könnte, müsste, sollte, dürfte, möchte</i>).",
        "У <b>складних умовах</b> часто поєднуються два рівні: <i>Wenn ich es damals gewusst hätte, würde ich heute anders handeln</i> — минула умова + теперішній наслідок (mixed conditional).",
        "З <b>модальними</b>: <i>hätte + Inf + Modal-Inf</i> для минулого (<i>Er hätte kommen können</i>). Для теперішнього — <i>könnte/müsste/sollte + Inf</i>.",
        "Часті функції: <b>ввічливе прохання</b> (<i>Könnten Sie…?</i>), <b>обережна гіпотеза</b> (<i>Das dürfte stimmen</i>), <b>докір</b> (<i>Du hättest fragen sollen</i>), <b>нереальне порівняння</b> (<i>als ob / als wäre</i>).",
      ],
      table: {
        headers: ["Функція", "Приклад", "Переклад"],
        rows: [
          ["Ввічливість", "Ich hätte gerne einen Kaffee.", "Я б хотів каву."],
          ["Обережна гіпотеза", "Das dürfte teuer sein.", "Це, ймовірно, дорого."],
          ["Змішана умова", "Wenn ich studiert hätte, hätte ich jetzt einen besseren Job.", "Якби я вчився, зараз мав би кращу роботу."],
          ["Als ob", "Er tut so, als ob er alles wüsste.", "Він робить вигляд, ніби все знає."],
          ["Докір минулого", "Sie hätte mich informieren müssen.", "Вона мала б мене поінформувати."],
        ],
      },
      examples: [
        { de: "Wenn ich mehr Zeit hätte, würde ich Klavier lernen.", uk: "Якби я мав більше часу, вчив би фортепіано." },
        { de: "Hätten Sie einen Moment für mich?", uk: "Чи не знайшлося б у вас хвилини для мене?" },
        { de: "Er sieht aus, als hätte er die ganze Nacht gearbeitet.", uk: "Він виглядає так, ніби працював цілу ніч." },
        { de: "Ohne deine Hilfe wäre das Projekt gescheitert.", uk: "Без твоєї допомоги проєкт би провалився." },
        { de: "Wir sollten das noch einmal überdenken.", uk: "Нам варто ще раз це обміркувати." },
        { de: "Das könnte ein Missverständnis sein.", uk: "Це, можливо, непорозуміння." },
        { de: "Ich an deiner Stelle hätte anders reagiert.", uk: "Я на твоєму місці відреагував би інакше." },
        { de: "Wäre es möglich, den Termin zu verschieben?", uk: "Чи можливо перенести зустріч?" },
      ],
      tip: "Формальний стиль → <b>würde + Inf</b> для більшості дієслів; <b>hätte/wäre/könnte/müsste/sollte/dürfte</b> — завжди в класичній формі.",
      mistakes: [
        { wrong: "Wenn ich würde Zeit haben, würde ich kommen.", right: "Wenn ich Zeit hätte, würde ich kommen." },
        { wrong: "Er tut, als ob er weiß alles.", right: "Er tut, als ob er alles wüsste." },
        { wrong: "Du hättest gefragt sollen.", right: "Du hättest fragen sollen." },
      ],
      exercises: {}, prevSlug: "konjunktiv1", nextSlug: "passiv-alle-zeiten",
    },
    extras: {
      duration: 25, premium: true,
      learningGoals: [
        "розрізняти класичний K.II і würde-конструкцію",
        "будувати змішані умови (минуле + теперішнє)",
        "виражати ввічливість, обережну гіпотезу, докір",
        "правильно вживати als ob / als wäre",
      ],
      ruleBox: {
        rule: "<b>haben/sein/werden + модальні → класична форма</b> (hätte, wäre, würde, könnte…). Інші дієслова у формальному тексті → <b>würde + Infinitiv</b>.",
      },
      ukrainianTips: [
        "«Я б хотів» = <b>ich hätte gern / ich möchte</b>, а не <i>ich würde wollen</i>.",
        "«Ніби» + минуле = <b>als ob + K.II Vergangenheit</b>: <i>als ob er es gesehen hätte</i>.",
        "У ввічливих проханнях завжди <b>Könnten/Würden Sie…?</b>, ніколи не <i>Können/Werden Sie…?</i>",
      ],
      languageComparison: {
        diffs: ["У німецькій ввічливість формується <b>граматично</b> (K.II), а не тільки інтонацією або «будь ласка»."],
        traps: ["«Als ob» + Indikativ звучить розмовно; у C1-письмі — тільки K.II."],
      },
      summary: [
        "K.II = нереальність + ввічливість + обережність.",
        "Формальний стиль: würde + Inf; винятки — haben/sein/werden/Modalverben.",
        "Змішана умова: минула умова → теперішній наслідок.",
        "«Als ob / als wäre» → завжди K.II.",
        "Докір минулого: hätte(n) + Inf + sollen/müssen/dürfen.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Wenn ich Zeit ___, würde ich kommen.", options: ["hätte","würde haben","habe","hatte"], correct: 0 },
      { type: "mc", q: "___ Sie mir bitte helfen?", options: ["Können","Könnten","Konnten","Würden können"], correct: 1, explain: "Ввічливість → K.II." },
      { type: "mc", q: "Er tut so, als ob er alles ___.", options: ["weiß","wüsste","würde wissen","gewusst hätte"], correct: 1 },
      { type: "mc", q: "Wenn ich früher studiert hätte, ___ ich jetzt mehr Chancen.", options: ["habe","hätte","hätte gehabt","würde haben"], correct: 1, explain: "Змішана умова: минуле → теперішнє." },
      { type: "gap", q: "Ich ___ gerne einen Tee. (haben – K.II)", answer: "hätte" },
      { type: "gap", q: "Das ___ ein Missverständnis sein. (können – обережно)", answer: "könnte" },
      { type: "gap", q: "Du ___ mich anrufen sollen! (haben)", answer: "hättest" },
      { type: "gap", q: "___ es Ihnen etwas ausmachen zu warten? (werden – ввічл.)", answer: "Würde" },
      { type: "tf", q: "«würde sein» — рекомендована форма у формальному стилі.", correct: false, explain: "Від sein → <b>wäre</b>, не würde sein." },
      { type: "tf", q: "Після «als ob» у C1-письмі стоїть Konjunktiv II.", correct: true },
      { type: "match", prompt: "Функція → форма:", pairs: [
        { left: "ввічливе прохання", right: "Könnten Sie…?" },
        { left: "докір у минулому", right: "Du hättest… sollen" },
        { left: "обережна гіпотеза", right: "Das dürfte…" },
        { left: "нереальне порівняння", right: "als ob… wüsste" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Wenn ich würde reich sein, würde ich reisen.", correct: ["Wenn ich reich wäre, würde ich reisen."] },
      { type: "multi", q: "Виділи форми Konjunktiv II:", options: ["hätte","hat","wäre","war","könnte","kann","würde gehen"], correct: [0,2,4,6] },
      { type: "order", prompt: "Склади речення:",
        words: ["hätte","gewusst","ich","wenn","das","würde","anders","handeln","ich"],
        correct: ["Wenn","ich","das","gewusst","hätte,","würde","ich","anders","handeln"] },
      { type: "translate", prompt: "Переклади ввічливо:", uk: "Чи не могли б Ви мені допомогти?", de: ["Könnten Sie mir bitte helfen?","Würden Sie mir bitte helfen?"] },
    ],
  },

  "passiv-alle-zeiten": {
    lesson: {
      slug: "passiv-alle-zeiten", level: "C1", category: CAT,
      titleDe: "Passiv in allen Zeitformen", titleUk: "Пасив у всіх часових формах",
      goal: "Впевнено утворювати та розпізнавати Vorgangs- і Zustandspassiv у всіх часах, включно з Futur II.",
      explanation: [
        "<b>Vorgangspassiv</b> (пасив дії): <b>werden + Partizip II</b> — акцент на процесі.",
        "<b>Zustandspassiv</b> (пасив стану): <b>sein + Partizip II</b> — акцент на результаті: <i>Die Tür ist geschlossen</i> (стан) vs <i>Die Tür wird geschlossen</i> (дія).",
        "У Perfekt/Plusquamperfekt Vorgangspassiv <i>werden</i> перетворюється на <b>worden</b> (без ge-): <i>ist gebaut worden</i>.",
        "У Futur I Passiv: <b>wird + P II + werden</b>; у Futur II Passiv: <b>wird + P II + worden sein</b>.",
        "Аґенс: <b>von + Dat.</b> (особа/діяч), <b>durch + Akk.</b> (засіб/причина).",
      ],
      table: {
        headers: ["Час", "Vorgangspassiv", "Zustandspassiv"],
        rows: [
          ["Präsens", "wird gemacht", "ist gemacht"],
          ["Präteritum", "wurde gemacht", "war gemacht"],
          ["Perfekt", "ist gemacht worden", "ist gemacht gewesen"],
          ["Plusquamperfekt", "war gemacht worden", "war gemacht gewesen"],
          ["Futur I", "wird gemacht werden", "wird gemacht sein"],
          ["Futur II", "wird gemacht worden sein", "—"],
        ],
      },
      examples: [
        { de: "Das Haus wird renoviert.", uk: "Будинок ремонтують." },
        { de: "Der Vertrag wurde gestern unterschrieben.", uk: "Договір підписали вчора." },
        { de: "Das Museum ist im 19. Jahrhundert gebaut worden.", uk: "Музей побудований у 19 ст." },
        { de: "Der Fehler war schon behoben worden, bevor wir kamen.", uk: "Помилку виправили ще до нашого приходу." },
        { de: "Die Ergebnisse werden nächste Woche veröffentlicht werden.", uk: "Результати оприлюднять наступного тижня." },
        { de: "Bis Ende des Jahres wird das Projekt abgeschlossen worden sein.", uk: "До кінця року проєкт буде завершено." },
        { de: "Die Tür ist geschlossen.", uk: "Двері зачинені (стан)." },
        { de: "Der Text wurde vom Professor korrigiert.", uk: "Текст перевірив професор." },
      ],
      tip: "У Perfekt Passiv допоміжне завжди <b>sein</b>: <i>ist … worden</i>, а не <i>hat … worden</i>.",
      mistakes: [
        { wrong: "Das Haus hat gebaut worden.", right: "Das Haus ist gebaut worden." },
        { wrong: "Es wird gemacht geworden.", right: "Es wird gemacht werden." },
        { wrong: "Die Tür wird geschlossen (маючи на увазі стан).", right: "Die Tür ist geschlossen." },
      ],
      exercises: {}, prevSlug: "konjunktiv2-komplex", nextSlug: "passiv-modalverben-c1",
    },
    extras: {
      duration: 25, premium: true,
      learningGoals: ["утворювати Passiv у 6 часах","розрізняти Vorgangs- і Zustandspassiv","правильно вживати von/durch","розпізнавати Futur II Passiv"],
      ruleBox: { rule: "<b>Vorgangspassiv = werden + P II</b>; у Perfekt/Plusq. <i>werden → worden</i>. <b>Zustandspassiv = sein + P II</b>." },
      ukrainianTips: [
        "Українська рідко розрізняє «дію» і «стан» окремими формами — у німецькій це <b>дві різні конструкції</b>.",
        "«Було зроблено» ≈ <b>war gemacht (worden)</b>; «є зроблено» ≈ <b>ist gemacht</b>.",
      ],
      languageComparison: {
        diffs: ["Українська часто передає пасив активною формою з невизначеним підметом («роблять»); німецька — окремою конструкцією."],
        traps: ["Zustandspassiv не має Futur II."],
      },
      summary: [
        "Vorgangspassiv: werden + P II.",
        "Zustandspassiv: sein + P II.",
        "Perfekt: <b>ist … worden</b>.",
        "Futur II: <b>wird … worden sein</b>.",
        "Аґенс: von (діяч) / durch (засіб).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das Haus ___ gebaut worden.", options: ["hat","ist","war","wird"], correct: 1 },
      { type: "mc", q: "Der Brief ___ morgen geschrieben werden.", options: ["wird","würde","ist","wurde"], correct: 0 },
      { type: "mc", q: "Die Tür ___ geschlossen. (стан)", options: ["wird","ist","wurde","worden"], correct: 1 },
      { type: "mc", q: "Bis Ende der Woche ___ alles erledigt worden sein.", options: ["ist","wird","war","werden"], correct: 1, explain: "Futur II Passiv." },
      { type: "gap", q: "Der Vertrag ___ gestern unterschrieben. (Prät. Passiv)", answer: "wurde" },
      { type: "gap", q: "Das Museum ist im 19. Jh. gebaut ___.", answer: "worden" },
      { type: "gap", q: "Der Text wurde ___ Professor korrigiert.", answer: "vom" },
      { type: "gap", q: "Die Stadt wurde ___ einen Sturm zerstört.", answer: "durch" },
      { type: "tf", q: "Perfekt Passiv допоміжне — «haben».", correct: false, explain: "Тільки sein." },
      { type: "tf", q: "«Die Tür ist geschlossen» — Zustandspassiv.", correct: true },
      { type: "match", prompt: "Час → форма:", pairs: [
        { left: "Präsens Vg.", right: "wird gemacht" },
        { left: "Perfekt Vg.", right: "ist gemacht worden" },
        { left: "Präteritum Zg.", right: "war gemacht" },
        { left: "Futur II Vg.", right: "wird gemacht worden sein" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das Haus hat gebaut worden.", correct: ["Das Haus ist gebaut worden."] },
      { type: "multi", q: "Виділи форми Vorgangspassiv:", options: ["wird gemacht","ist gemacht","ist gemacht worden","war zerstört","wurde gebaut","hat gemacht"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:", words: ["gebaut","worden","ist","Haus","im","19.","Jh.","das"], correct: ["Das","Haus","ist","im","19.","Jh.","gebaut","worden"] },
      { type: "translate", prompt: "Переклади (Vorgangspassiv, Perfekt):", uk: "Договір підписали вчора.", de: ["Der Vertrag ist gestern unterschrieben worden."] },
    ],
  },

  "passiv-modalverben-c1": {
    lesson: {
      slug: "passiv-modalverben-c1", level: "C1", category: CAT,
      titleDe: "Passiv mit Modalverben", titleUk: "Пасив із модальними дієсловами",
      goal: "Утворювати пасив із модальними у теперішньому, минулому та K.II.",
      explanation: [
        "Формула: <b>Modalverb + P II + werden</b>. Модальне змінюється; <i>werden</i> — інфінітив у кінці.",
        "Präteritum: <b>musste/konnte/sollte… + P II + werden</b>. Perfekt із модальним у пасиві на C1 частіше замінюють на Präteritum або K.II.",
        "K.II: <b>müsste/könnte/sollte + P II + werden</b>: <i>Das müsste gemacht werden</i>.",
        "K.II минулого: <b>hätte + P II + werden + müssen/können/sollen</b>: <i>Das hätte gemacht werden müssen</i>.",
      ],
      table: {
        headers: ["Час", "Формула", "Приклад"],
        rows: [
          ["Präsens", "Modal + P II + werden", "Das muss gemacht werden."],
          ["Präteritum", "Modal(Prät.) + P II + werden", "Das musste gemacht werden."],
          ["K.II", "Modal(K.II) + P II + werden", "Das müsste gemacht werden."],
          ["K.II Verg.", "hätte + P II + werden + Modal", "Das hätte gemacht werden müssen."],
        ],
      },
      examples: [
        { de: "Der Antrag muss unterschrieben werden.", uk: "Заяву треба підписати." },
        { de: "Die Regeln sollten respektiert werden.", uk: "Правил слід дотримуватися." },
        { de: "Der Fehler konnte nicht behoben werden.", uk: "Помилку не можна було виправити." },
        { de: "Das Problem müsste sofort gelöst werden.", uk: "Проблему треба було б негайно вирішити." },
        { de: "Der Termin hätte verschoben werden können.", uk: "Зустріч можна було б перенести." },
        { de: "Die Arbeit hätte längst erledigt werden müssen.", uk: "Роботу давно треба було виконати." },
        { de: "Es darf nicht geraucht werden.", uk: "Тут не можна курити." },
        { de: "Solche Fehler dürften nicht wieder gemacht werden.", uk: "Такі помилки не мали б повторюватися." },
      ],
      tip: "Порядок у кінці: <b>Partizip II — werden — (Modal-Infinitiv)</b>.",
      mistakes: [
        { wrong: "Das muss werden gemacht.", right: "Das muss gemacht werden." },
        { wrong: "Das hätte gemacht müssen werden.", right: "Das hätte gemacht werden müssen." },
      ],
      exercises: {}, prevSlug: "passiv-alle-zeiten", nextSlug: "passiversatz",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["будувати пасив із модальними у 4 формах","коректно розташовувати P II + werden + Modal","розуміти K.II минулого з модальним у пасиві"],
      ruleBox: { rule: "<b>Modal + P II + werden</b>. У K.II Vergangenheit: <b>hätte + P II + werden + Modal</b>." },
      ukrainianTips: ["Українське «треба зробити» = <b>muss gemacht werden</b>, не <i>muss zu machen</i>."],
      summary: [
        "Präsens: Modal + P II + werden.",
        "Prät.: Modal(Prät.) + P II + werden.",
        "K.II Verg.: hätte + P II + werden + Modal.",
        "Kein Perfekt-Ersatz für Passiv+Modal у розмовному стилі.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das ___ sofort gemacht werden.", options: ["muss","wird","hat","ist"], correct: 0 },
      { type: "mc", q: "Der Fehler ___ nicht behoben werden.", options: ["konnte","kann worden","ist","war"], correct: 0 },
      { type: "mc", q: "Das hätte längst erledigt werden ___.", options: ["müssen","gemusst","musste","muss"], correct: 0 },
      { type: "mc", q: "Es ___ hier nicht geraucht werden.", options: ["darf","wird","hat","ist"], correct: 0 },
      { type: "gap", q: "Der Antrag muss unterschrieben ___.", answer: "werden" },
      { type: "gap", q: "Die Regeln sollten respektiert ___.", answer: "werden" },
      { type: "gap", q: "Das Problem ___ sofort gelöst werden. (müssen K.II)", answer: "müsste" },
      { type: "gap", q: "Das hätte gemacht ___ können.", answer: "werden" },
      { type: "tf", q: "Порядок: Modal + werden + P II.", correct: false, explain: "P II йде першим, потім werden." },
      { type: "tf", q: "K.II Vergangenheit: hätte + P II + werden + Modal.", correct: true },
      { type: "match", prompt: "Форма → значення:", pairs: [
        { left: "muss gemacht werden", right: "необхідність зараз" },
        { left: "musste gemacht werden", right: "необхідність у минулому" },
        { left: "müsste gemacht werden", right: "рекомендація/ідеал" },
        { left: "hätte gemacht werden müssen", right: "докір за минуле" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das muss werden gemacht.", correct: ["Das muss gemacht werden."] },
      { type: "multi", q: "Виділи коректні пасивно-модальні форми:", options: ["muss gemacht werden","muss werden gemacht","hätte gemacht werden können","hätte können gemacht werden","sollte gelesen werden"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:", words: ["werden","müssen","hätte","gemacht","das","längst"], correct: ["Das","hätte","längst","gemacht","werden","müssen"] },
      { type: "translate", prompt: "Переклади:", uk: "Це треба було зробити давно.", de: ["Das hätte längst gemacht werden müssen."] },
    ],
  },

  "passiversatz": {
    lesson: {
      slug: "passiversatz", level: "C1", category: CAT,
      titleDe: "Passiversatzformen", titleUk: "Passiversatz — альтернативи пасиву",
      goal: "Замінювати пасив семантично еквівалентними конструкціями: sich lassen, sein + zu + Inf, -bar/-lich, man.",
      explanation: [
        "На C1 замість <i>werden</i>-пасиву часто вживають <b>Passiversatz</b> — легші, стилістично різноманітніші конструкції з тим самим значенням.",
        "<b>sich lassen + Infinitiv</b> = «можна щось зробити»: <i>Das Problem lässt sich lösen</i> = «Проблему можна вирішити».",
        "<b>sein + zu + Infinitiv</b> = «треба / можна зробити»: <i>Das ist zu erledigen</i>.",
        "<b>Прикметники на -bar / -lich</b>: <i>lösbar, machbar, verständlich, unlesbar</i>.",
        "<b>man</b> + активне речення — розмовна альтернатива: <i>Man kann das machen</i>.",
      ],
      table: {
        headers: ["Пасив", "Passiversatz"],
        rows: [
          ["Das kann gemacht werden.", "Das lässt sich machen."],
          ["Das muss erledigt werden.", "Das ist zu erledigen."],
          ["Das kann verstanden werden.", "Das ist verständlich."],
          ["Es kann gemacht werden.", "Man kann es machen."],
        ],
      },
      examples: [
        { de: "Das lässt sich leicht erklären.", uk: "Це легко пояснити." },
        { de: "Der Text ist gut zu verstehen.", uk: "Текст добре зрозуміти." },
        { de: "Diese Software ist frei verfügbar.", uk: "Це ПЗ вільно доступне." },
        { de: "Solche Fehler sind vermeidbar.", uk: "Таких помилок можна уникнути." },
        { de: "Der Vertrag ist noch heute zu unterzeichnen.", uk: "Договір треба підписати ще сьогодні." },
        { de: "Man sollte das nicht unterschätzen.", uk: "Цього не варто недооцінювати." },
        { de: "Das Ergebnis lässt sich nicht ändern.", uk: "Результат неможливо змінити." },
        { de: "Die Aufgabe ist machbar.", uk: "Завдання здійсненне." },
      ],
      tip: "<b>lassen sich</b> ≈ «можна»; <b>sein + zu + Inf</b> ≈ «треба/можна» (контекст); <b>-bar</b> ≈ «-ний, здатний».",
      mistakes: [
        { wrong: "Das lässt sich zu machen.", right: "Das lässt sich machen." },
        { wrong: "Das ist zu machen werden.", right: "Das ist zu machen." },
      ],
      exercises: {}, prevSlug: "passiv-modalverben-c1", nextSlug: "funktionsverbgefuege",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["утворювати 4 типи Passiversatz","перефразовувати werden-Passiv","стилістично вибирати конструкцію"],
      ruleBox: { rule: "<b>sich lassen + Inf</b> · <b>sein + zu + Inf</b> · <b>-bar/-lich</b> · <b>man + Aktiv</b> — усі замінюють werden-Passiv." },
      summary: [
        "sich lassen + Inf = можна.",
        "sein + zu + Inf = треба/можна.",
        "-bar/-lich = здатність.",
        "man = розмовна альтернатива.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das Problem ___ sich lösen.", options: ["ist","lässt","wird","hat"], correct: 1 },
      { type: "mc", q: "Der Text ist gut ___ verstehen.", options: ["um","zu","für","auf"], correct: 1 },
      { type: "mc", q: "Solche Fehler sind ___.", options: ["vermeiden","vermeidbar","vermeidet","vermeidend"], correct: 1 },
      { type: "mc", q: "___ kann das nicht ändern.", options: ["Es","Das","Man","Sich"], correct: 2 },
      { type: "gap", q: "Das lässt ___ leicht erklären.", answer: "sich" },
      { type: "gap", q: "Der Vertrag ist noch heute zu ___.", answer: "unterzeichnen" },
      { type: "gap", q: "Diese Aufgabe ist mach___.", answer: "bar" },
      { type: "gap", q: "___ sollte das nicht unterschätzen.", answer: "Man" },
      { type: "tf", q: "«sich lassen + Inf» ≈ «можна».", correct: true },
      { type: "tf", q: "«sein + zu + Inf» — тільки пасивне значення.", correct: false, explain: "Може означати і «треба», і «можна»." },
      { type: "match", prompt: "Passiv → Passiversatz:", pairs: [
        { left: "kann gemacht werden", right: "lässt sich machen" },
        { left: "muss erledigt werden", right: "ist zu erledigen" },
        { left: "kann verstanden werden", right: "ist verständlich" },
        { left: "kann gelöst werden", right: "ist lösbar" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das lässt sich zu machen.", correct: ["Das lässt sich machen."] },
      { type: "multi", q: "Виділи форми Passiversatz:", options: ["lässt sich lösen","ist zu erledigen","wird gemacht","machbar","hat gemacht"], correct: [0,1,3] },
      { type: "order", prompt: "Склади речення:", words: ["lösen","sich","lässt","leicht","das","Problem"], correct: ["Das","Problem","lässt","sich","leicht","lösen"] },
      { type: "translate", prompt: "Переклади через Passiversatz:", uk: "Це легко пояснити.", de: ["Das lässt sich leicht erklären.","Das ist leicht zu erklären."] },
    ],
  },

  "funktionsverbgefuege": {
    lesson: {
      slug: "funktionsverbgefuege", level: "C1", category: CAT,
      titleDe: "Funktionsverbgefüge (FVG)", titleUk: "Функційні дієслівно-іменникові конструкції (FVG)",
      goal: "Розпізнавати й активно вживати сталі FVG офіційного стилю (Entscheidung treffen, in Kraft treten…).",
      explanation: [
        "<b>FVG</b> = функційне дієслово + іменник (часто з прийменником). Значення несе іменник, дієслово втрачає власне значення й виконує лише граматичну функцію.",
        "Типово вживається в <b>офіційному, юридичному, науковому стилі</b>. Часто має простий дієслівний еквівалент: <i>eine Entscheidung treffen = entscheiden</i>.",
        "Найчастіші функційні дієслова: <b>bringen, kommen, stehen, stellen, geben, nehmen, treten, treffen, leisten, finden, halten</b>.",
        "Часто фіксований <b>артикль</b> і <b>прийменник</b>: <i>zur Sprache bringen</i>, <i>in Frage kommen</i>, <i>zur Verfügung stehen</i>.",
      ],
      table: {
        headers: ["FVG", "Значення", "Дієслівний еквівалент"],
        rows: [
          ["eine Entscheidung treffen", "прийняти рішення", "entscheiden"],
          ["in Kraft treten", "набути чинності", "gültig werden"],
          ["zur Verfügung stehen", "бути в розпорядженні", "verfügbar sein"],
          ["Rücksicht nehmen (auf)", "зважати", "berücksichtigen"],
          ["Kritik üben (an)", "критикувати", "kritisieren"],
          ["in Frage kommen", "розглядатися", "möglich sein"],
        ],
      },
      examples: [
        { de: "Die Regierung hat eine wichtige Entscheidung getroffen.", uk: "Уряд прийняв важливе рішення." },
        { de: "Das Gesetz tritt am 1. Januar in Kraft.", uk: "Закон набуває чинності 1 січня." },
        { de: "Ich stehe Ihnen jederzeit zur Verfügung.", uk: "Я завжди у вашому розпорядженні." },
        { de: "Wir müssen auf die Umwelt Rücksicht nehmen.", uk: "Ми маємо враховувати довкілля." },
        { de: "Die Presse übte scharfe Kritik an der Reform.", uk: "Преса гостро критикувала реформу." },
        { de: "Diese Option kommt nicht in Frage.", uk: "Цей варіант не розглядається." },
        { de: "Der Vertrag kommt morgen zum Abschluss.", uk: "Договір буде укладено завтра." },
        { de: "Sie brachte das Thema zur Sprache.", uk: "Вона порушила цю тему." },
      ],
      tip: "У FVG зазвичай <b>не можна замінити артикль</b> і <b>не можна додати прикметник</b> між дієсловом і іменником без зміни змісту.",
      mistakes: [
        { wrong: "Ich mache eine Entscheidung.", right: "Ich treffe eine Entscheidung." },
        { wrong: "Das Gesetz kommt in Kraft.", right: "Das Gesetz tritt in Kraft." },
      ],
      exercises: {}, prevSlug: "passiversatz", nextSlug: "verben-feste-praep-c1",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["впізнавати FVG","замінювати FVG простими дієсловами","правильно вибирати функційне дієслово","доречно вживати у формальному стилі"],
      ruleBox: { rule: "FVG = <b>функційне дієслово + іменник (± прийменник)</b>. Значення дає іменник, дієслово — лише граматичне." },
      ukrainianTips: ["Українська часто передає FVG простим дієсловом: <i>eine Entscheidung treffen</i> → «вирішити»."],
      summary: [
        "FVG типове для офіційного стилю.",
        "Артикль і прийменник — фіксовані.",
        "Часте функційне дієслово: treffen, treten, kommen, stehen, bringen, nehmen.",
        "Майже завжди є простий синонім-дієслово.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Eine Entscheidung ___.", options: ["machen","treffen","tun","haben"], correct: 1 },
      { type: "mc", q: "Das Gesetz ___ in Kraft.", options: ["kommt","tritt","geht","steht"], correct: 1 },
      { type: "mc", q: "Ich stehe Ihnen zur ___.", options: ["Verfügung","Antwort","Frage","Zeit"], correct: 0 },
      { type: "mc", q: "Diese Option ___ nicht in Frage.", options: ["kommt","geht","ist","macht"], correct: 0 },
      { type: "gap", q: "Kritik ___ an der Reform. (üben, Prät.)", answer: "übte" },
      { type: "gap", q: "Rücksicht ___ auf die Kinder! (nehmen, Imp.)", answer: "nimm" },
      { type: "gap", q: "Sie brachte das Thema zur ___.", answer: "Sprache" },
      { type: "gap", q: "Der Vertrag kommt zum ___.", answer: "Abschluss" },
      { type: "tf", q: "У FVG значення несе дієслово.", correct: false, explain: "Значення несе іменник." },
      { type: "tf", q: "«in Kraft treten» = «набути чинності».", correct: true },
      { type: "match", prompt: "FVG → синонім:", pairs: [
        { left: "Entscheidung treffen", right: "entscheiden" },
        { left: "Kritik üben", right: "kritisieren" },
        { left: "Rücksicht nehmen", right: "berücksichtigen" },
        { left: "zur Verfügung stehen", right: "verfügbar sein" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich mache eine Entscheidung.", correct: ["Ich treffe eine Entscheidung."] },
      { type: "multi", q: "Виділи FVG:", options: ["eine Entscheidung treffen","in Kraft treten","ein Buch lesen","Rücksicht nehmen","zur Sprache bringen","Kaffee trinken"], correct: [0,1,3,4] },
      { type: "order", prompt: "Склади речення:", words: ["getroffen","Entscheidung","eine","hat","wichtige","die","Regierung"], correct: ["Die","Regierung","hat","eine","wichtige","Entscheidung","getroffen"] },
      { type: "translate", prompt: "Переклади через FVG:", uk: "Уряд прийняв рішення.", de: ["Die Regierung hat eine Entscheidung getroffen."] },
    ],
  },

  "verben-feste-praep-c1": {
    lesson: {
      slug: "verben-feste-praep-c1", level: "C1", category: CAT,
      titleDe: "Verben mit festen Präpositionen", titleUk: "Дієслова зі сталими прийменниками (C1)",
      goal: "Володіти корпусом ~40 C1-дієслів зі сталими прийменниками та відповідними відмінками.",
      explanation: [
        "Багато дієслів вимагають <b>сталого прийменника</b> з фіксованим відмінком: <i>sich beschäftigen mit + Dat.</i>, <i>bestehen auf + Dat.</i>, <i>hinweisen auf + Akk.</i>",
        "На C1 корпус розширюється абстрактними дієсловами: <i>abhängen von, verzichten auf, sich bemühen um, sich einigen auf, protestieren gegen…</i>",
        "У складнопідрядних вживається <b>Präpositionaladverb</b>: <i>darauf, darüber, damit, dafür</i>: <i>Ich freue mich <b>darauf</b>, dass du kommst</i>.",
        "У питанні — <b>wo(r) + Präp.</b>: <i>Worauf wartest du? Womit beschäftigst du dich?</i>",
      ],
      table: {
        headers: ["Дієслово", "Präp. + Fall", "Приклад"],
        rows: [
          ["sich beschäftigen", "mit + Dat.", "Ich beschäftige mich mit dem Thema."],
          ["bestehen", "auf + Dat.", "Er besteht auf seinem Recht."],
          ["hinweisen", "auf + Akk.", "Sie wies auf das Problem hin."],
          ["verzichten", "auf + Akk.", "Ich verzichte auf den Urlaub."],
          ["abhängen", "von + Dat.", "Das hängt vom Wetter ab."],
          ["sich bemühen", "um + Akk.", "Wir bemühen uns um eine Lösung."],
          ["protestieren", "gegen + Akk.", "Sie protestieren gegen das Gesetz."],
        ],
      },
      examples: [
        { de: "Ich beschäftige mich intensiv mit der Frage.", uk: "Я активно займаюся цим питанням." },
        { de: "Er besteht auf seinem Standpunkt.", uk: "Він наполягає на своїй позиції." },
        { de: "Sie wies auf mögliche Risiken hin.", uk: "Вона вказала на можливі ризики." },
        { de: "Wir verzichten auf weitere Diskussionen.", uk: "Ми відмовляємось від подальших дискусій." },
        { de: "Alles hängt von deiner Entscheidung ab.", uk: "Усе залежить від твого рішення." },
        { de: "Sie einigten sich auf einen Kompromiss.", uk: "Вони домовились про компроміс." },
        { de: "Ich freue mich darauf, dass du kommst.", uk: "Я тішуся тому, що ти прийдеш." },
        { de: "Worauf wartest du eigentlich?", uk: "Чого ти, власне, чекаєш?" },
      ],
      tip: "Запам'ятовуй дієслово <b>разом із прийменником і відмінком</b>: <i>bestehen auf (Dat.)</i>, а не просто «bestehen».",
      mistakes: [
        { wrong: "Er besteht auf seinen Recht.", right: "Er besteht auf seinem Recht." },
        { wrong: "Ich freue mich, dass du kommst.", right: "Ich freue mich darauf, dass du kommst." },
      ],
      exercises: {}, prevSlug: "funktionsverbgefuege", nextSlug: "komplexe-infinitivkonstruktionen",
    },
    extras: {
      duration: 25, premium: true,
      learningGoals: ["знати ~40 C1-дієслів із фіксованими прийменниками","правильно вибирати відмінок","будувати da(r)- і wo(r)-форми"],
      ruleBox: { rule: "Дієслово + <b>стала Präp. + фікс. відмінок</b>. У підрядному з dass — <b>da(r) + Präp.</b> у головному." },
      ukrainianTips: ["Український прийменник рідко збігається з німецьким: «залежати від» = <b>abhängen von + Dat.</b>, але «наполягати на» = <b>bestehen auf + Dat.</b>"],
      summary: [
        "Запам'ятовувати дієслово + Präp. + Fall як єдине ціле.",
        "У підрядному — da(r)-форма в головному.",
        "У питанні — wo(r)-форма.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich beschäftige mich ___ dem Thema.", options: ["mit","für","über","auf"], correct: 0 },
      { type: "mc", q: "Er besteht ___ seinem Recht.", options: ["auf","an","über","für"], correct: 0 },
      { type: "mc", q: "Wir verzichten ___ den Urlaub.", options: ["auf","zu","für","an"], correct: 0 },
      { type: "mc", q: "Alles hängt ___ dem Wetter ab.", options: ["von","auf","mit","an"], correct: 0 },
      { type: "gap", q: "Sie wies ___ das Problem hin.", answer: "auf" },
      { type: "gap", q: "Wir bemühen uns ___ eine Lösung.", answer: "um" },
      { type: "gap", q: "Sie protestieren ___ das Gesetz.", answer: "gegen" },
      { type: "gap", q: "Ich freue mich ___, dass du kommst.", answer: "darauf" },
      { type: "tf", q: "«bestehen auf» вимагає Dat.", correct: true },
      { type: "tf", q: "«hinweisen auf» вимагає Dat.", correct: false, explain: "Akk." },
      { type: "match", prompt: "Дієслово → Präp.+Fall:", pairs: [
        { left: "abhängen", right: "von + Dat." },
        { left: "verzichten", right: "auf + Akk." },
        { left: "sich bemühen", right: "um + Akk." },
        { left: "bestehen", right: "auf + Dat." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Er besteht auf seinen Recht.", correct: ["Er besteht auf seinem Recht."] },
      { type: "multi", q: "Виділи da(r)-форми:", options: ["darauf","damit","dafür","daran","dazu","darüber"], correct: [0,1,2,3,4,5] },
      { type: "order", prompt: "Склади речення:", words: ["ab","hängt","Wetter","dem","alles","von"], correct: ["Alles","hängt","von","dem","Wetter","ab"] },
      { type: "translate", prompt: "Переклади:", uk: "Це залежить від тебе.", de: ["Das hängt von dir ab."] },
    ],
  },

  "komplexe-infinitivkonstruktionen": {
    lesson: {
      slug: "komplexe-infinitivkonstruktionen", level: "C1", category: CAT,
      titleDe: "Komplexe Infinitivkonstruktionen", titleUk: "Складні інфінітивні конструкції",
      goal: "Будувати складні речення з um…zu, ohne…zu, (an)statt…zu, а також розширені інфінітивні звороти.",
      explanation: [
        "<b>um … zu + Inf</b> = «щоб» (мета, той самий підмет): <i>Ich lerne Deutsch, um in Berlin zu studieren</i>.",
        "<b>ohne … zu + Inf</b> = «не роблячи чогось»: <i>Er ging, ohne zu grüßen</i>.",
        "<b>(an)statt … zu + Inf</b> = «замість того щоб»: <i>Statt zu arbeiten, spielte er</i>.",
        "Якщо підмети різні → замість um…zu вживають <b>damit</b>: <i>Ich helfe dir, damit du fertig wirst</i>.",
        "На C1 інфінітивні звороти можуть містити модальні: <i>Er hofft, den Test bestehen zu können</i>; та бути в минулому: <i>Er behauptet, alles verstanden zu haben</i>.",
      ],
      table: {
        headers: ["Конструкція", "Значення", "Приклад"],
        rows: [
          ["um … zu", "мета", "Ich lerne, um zu bestehen."],
          ["ohne … zu", "супровід (заперечно)", "Er ging, ohne zu grüßen."],
          ["(an)statt … zu", "замість", "Statt zu lesen, schlief er."],
          ["damit", "мета (різні підмети)", "Ich rufe an, damit du kommst."],
          ["Inf. Perf.", "минуле дія", "Er behauptet, es gesehen zu haben."],
        ],
      },
      examples: [
        { de: "Ich fahre nach Wien, um Deutsch zu lernen.", uk: "Я їду до Відня, щоб вчити німецьку." },
        { de: "Sie ging weg, ohne ein Wort zu sagen.", uk: "Вона пішла, не сказавши ні слова." },
        { de: "Statt zu jammern, sollte er handeln.", uk: "Замість того щоб скаржитись, він мав би діяти." },
        { de: "Ich helfe dir, damit du pünktlich fertig wirst.", uk: "Я допоможу, щоб ти встиг." },
        { de: "Er hofft, den Vertrag unterschreiben zu können.", uk: "Він сподівається, що зможе підписати договір." },
        { de: "Sie behauptet, den Film schon gesehen zu haben.", uk: "Вона стверджує, що вже бачила фільм." },
        { de: "Ohne gefragt zu werden, gab er seine Meinung ab.", uk: "Не будучи запитаним, він висловив думку." },
        { de: "Anstatt zu diskutieren, arbeiteten sie.", uk: "Замість обговорювати, вони працювали." },
      ],
      tip: "«um…zu» = той самий підмет; різні підмети → <b>damit</b>. Інфінітив завжди з <b>zu</b>.",
      mistakes: [
        { wrong: "Ich helfe, um du fertig wirst.", right: "Ich helfe, damit du fertig wirst." },
        { wrong: "Er ging ohne grüßen.", right: "Er ging, ohne zu grüßen." },
      ],
      exercises: {}, prevSlug: "verben-feste-praep-c1", nextSlug: "modalpartizip",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["розрізняти um…zu / damit","будувати ohne…zu, statt…zu","вживати Infinitiv Perfekt","поєднувати з модальними"],
      ruleBox: { rule: "<b>um/ohne/statt … zu + Inf</b> — підмет однаковий. Різні підмети → <b>damit</b>. Минуле в інфінітиві: <b>P II + zu haben/sein</b>." },
      summary: [
        "um…zu = мета.",
        "ohne…zu = супровідне заперечення.",
        "statt…zu = альтернатива.",
        "damit — при різних підметах.",
        "Inf. Perf.: P II + zu haben/sein.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich lerne Deutsch, ___ in Wien zu studieren.", options: ["damit","um","ohne","statt"], correct: 1 },
      { type: "mc", q: "Er ging, ___ ein Wort zu sagen.", options: ["um","damit","ohne","statt"], correct: 2 },
      { type: "mc", q: "___ zu arbeiten, spielte er.", options: ["Um","Ohne","Statt","Damit"], correct: 2 },
      { type: "mc", q: "Ich helfe, ___ du pünktlich bist.", options: ["um","damit","ohne","zu"], correct: 1, explain: "Різні підмети." },
      { type: "gap", q: "Er behauptet, den Film schon gesehen ___ haben.", answer: "zu" },
      { type: "gap", q: "Sie hofft, kommen ___ können.", answer: "zu" },
      { type: "gap", q: "___ zu jammern, sollte er handeln.", answer: "Statt" },
      { type: "gap", q: "Ich fahre nach Berlin, ___ meine Familie zu besuchen.", answer: "um" },
      { type: "tf", q: "«um…zu» вимагає різних підметів.", correct: false, explain: "Однакових." },
      { type: "tf", q: "«damit» вживають при різних підметах.", correct: true },
      { type: "match", prompt: "Конструкція → значення:", pairs: [
        { left: "um…zu", right: "мета (той самий підмет)" },
        { left: "damit", right: "мета (різні підмети)" },
        { left: "ohne…zu", right: "супровід (заперечення)" },
        { left: "statt…zu", right: "альтернатива" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich helfe, um du fertig wirst.", correct: ["Ich helfe, damit du fertig wirst."] },
      { type: "multi", q: "Виділи правильні інфінітивні звороти:", options: ["um zu lernen","um zu lerne","ohne zu grüßen","statt arbeiten","damit zu kommen"], correct: [0,2] },
      { type: "order", prompt: "Склади речення:", words: ["zu","um","lernen","fahre","Wien","nach","ich","Deutsch"], correct: ["Ich","fahre","nach","Wien,","um","Deutsch","zu","lernen"] },
      { type: "translate", prompt: "Переклади:", uk: "Замість того щоб спати, він працював.", de: ["Statt zu schlafen, arbeitete er."] },
    ],
  },

  "modalpartizip": {
    lesson: {
      slug: "modalpartizip", level: "C1", category: CAT,
      titleDe: "Modalpartizip (Gerundivum)", titleUk: "Modalpartizip — конструкція zu + Partizip I",
      goal: "Утворювати та розуміти конструкцію <i>zu + Partizip I</i> у ролі прикметника (Gerundivum).",
      explanation: [
        "<b>Modalpartizip</b> (гербіативний дієприкметник, Gerundivum) = <b>zu + Partizip I</b>. Використовується як прикметник перед іменником і має <b>пасивне модальне значення</b> «якийсь має бути / може бути зроблено».",
        "Формула: <i>zu</i> + основа + <i>-end</i> + прикметникова відміна: <i>die zu lösende Aufgabe</i> = «завдання, яке треба вирішити».",
        "Еквівалент: <i>die Aufgabe, die gelöst werden muss/kann</i>. Modalpartizip — коротша і <b>формальна</b> версія.",
        "Часто у наукових, юридичних, технічних текстах: <i>die zu prüfenden Dokumente, das zu erwartende Ergebnis</i>.",
      ],
      table: {
        headers: ["Modalpartizip", "Розгорнута форма"],
        rows: [
          ["die zu lösende Aufgabe", "die Aufgabe, die gelöst werden muss"],
          ["die zu erwartenden Ergebnisse", "die Ergebnisse, die erwartet werden können"],
          ["ein nicht zu unterschätzendes Problem", "ein Problem, das nicht unterschätzt werden darf"],
          ["die zu prüfenden Dokumente", "die Dokumente, die geprüft werden müssen"],
        ],
      },
      examples: [
        { de: "Die zu lösende Aufgabe ist komplex.", uk: "Завдання, яке треба вирішити, складне." },
        { de: "Die zu erwartenden Ergebnisse sind vielversprechend.", uk: "Очікувані результати обнадійливі." },
        { de: "Ein nicht zu unterschätzendes Risiko.", uk: "Ризик, який не можна недооцінювати." },
        { de: "Die zu unterzeichnenden Verträge liegen bereit.", uk: "Договори, які треба підписати, готові." },
        { de: "Das noch zu bezahlende Honorar.", uk: "Гонорар, який ще треба оплатити." },
        { de: "Die zu berücksichtigenden Faktoren sind zahlreich.", uk: "Факторів, які слід врахувати, багато." },
        { de: "Der zu entwickelnde Prototyp.", uk: "Прототип, який має бути розроблений." },
        { de: "Die kaum zu übersehende Warnung.", uk: "Попередження, яке важко не помітити." },
      ],
      tip: "Modalpartizip = <b>«якийсь до-роб-люваний»</b>: пасив + модальність. Пиши <b>злитно</b>: <i>zu + основа + end</i>.",
      mistakes: [
        { wrong: "die lösen zu Aufgabe", right: "die zu lösende Aufgabe" },
        { wrong: "die zu lösendend Aufgabe", right: "die zu lösende Aufgabe" },
      ],
      exercises: {}, prevSlug: "komplexe-infinitivkonstruktionen", nextSlug: "partizip-satzverkuerzung",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["утворювати Modalpartizip","розуміти пасивно-модальне значення","перефразовувати через relativsätze","коректно відмінювати як прикметник"],
      ruleBox: { rule: "<b>zu + Verbstamm + -end + Adjektivendung</b> = «має/може бути зроблено»." },
      summary: [
        "Modalpartizip = zu + P I.",
        "Значення: пасив + модальність (müssen/können).",
        "Часто у формальних текстах.",
        "Еквівалент: relativsatz із werden + P II + müssen/können.",
      ],
    },
    exercises15: [
      { type: "mc", q: "die zu ___ Aufgabe", options: ["lösen","lösend","lösende","gelöst"], correct: 2 },
      { type: "mc", q: "die zu erwartenden ___", options: ["Ergebnis","Ergebnisse","Ergebnissen","Ergebnisses"], correct: 1 },
      { type: "mc", q: "«die zu lösende Aufgabe» = die Aufgabe, die ___ werden muss.", options: ["löst","lösen","gelöst","zu lösen"], correct: 2 },
      { type: "mc", q: "ein nicht zu ___ Problem", options: ["unterschätzen","unterschätzt","unterschätzende","unterschätzendes"], correct: 3 },
      { type: "gap", q: "die zu prüfen___ Dokumente", answer: "den" },
      { type: "gap", q: "das zu erwartend___ Ergebnis (Nom. sg. n.)", answer: "e" },
      { type: "gap", q: "die zu ___den Verträge (unterzeichnen)", answer: "unterzeichnen" },
      { type: "gap", q: "Modalpartizip: zu + основа + ___", answer: "end" },
      { type: "tf", q: "Modalpartizip має активне значення.", correct: false, explain: "Пасивне." },
      { type: "tf", q: "«die zu lösende Aufgabe» ≈ «die Aufgabe, die gelöst werden muss».", correct: true },
      { type: "match", prompt: "Modalpartizip → значення:", pairs: [
        { left: "die zu lösende Aufgabe", right: "має бути вирішена" },
        { left: "die zu erwartenden Ergebnisse", right: "можна очікувати" },
        { left: "nicht zu unterschätzend", right: "не можна недооцінювати" },
        { left: "zu prüfende Unterlagen", right: "треба перевірити" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "die lösen zu Aufgabe", correct: ["die zu lösende Aufgabe"] },
      { type: "multi", q: "Виділи Modalpartizip:", options: ["die zu lösende Aufgabe","die gelöste Aufgabe","die lösende Person","die zu prüfenden Akten","der prüfende Beamte"], correct: [0,3] },
      { type: "order", prompt: "Склади фразу:", words: ["Aufgabe","zu","die","lösende","komplexe"], correct: ["die","zu","lösende","komplexe","Aufgabe"] },
      { type: "translate", prompt: "Переклади через Modalpartizip:", uk: "Завдання, яке треба вирішити.", de: ["die zu lösende Aufgabe"] },
    ],
  },

  "partizip-satzverkuerzung": {
    lesson: {
      slug: "partizip-satzverkuerzung", level: "C1", category: CAT,
      titleDe: "Partizip I und II als Satzverkürzung", titleUk: "Partizip I/II як скорочення підрядного",
      goal: "Скорочувати підрядні речення через Partizip I / II у ролі дієприкметникових зворотів.",
      explanation: [
        "<b>Partizip I</b> (Präsens): <i>основа + -end</i>. Значення — <b>активне, одночасне</b>: <i>lachend = сміючись</i>.",
        "<b>Partizip II</b>: значення — <b>пасивне або передминуле</b>: <i>gebaut = побудований</i>.",
        "Обидва можуть замінювати підрядне: <i>Der Mann, der lacht, → Der lachende Mann</i>; <i>Das Haus, das gebaut wurde, → Das gebaute Haus</i>.",
        "У <b>дієприкметниковому звороті</b> Partizip стоїть у кінці, кома відокремлює зворот: <i>In Berlin angekommen, rief er sofort an</i>.",
      ],
      table: {
        headers: ["Форма", "Значення", "Приклад"],
        rows: [
          ["Partizip I", "актив, одночасно", "der lachende Mann"],
          ["Partizip II", "пасив або передминуле", "das gebaute Haus"],
          ["Adverb. Partizip I", "супровідна дія", "Lachend ging er weg."],
          ["Adverb. Partizip II", "перед. дія / пасив", "In Wien angekommen, …"],
        ],
      },
      examples: [
        { de: "Der lächelnde Junge winkte uns zu.", uk: "Хлопчик, що всміхався, махнув нам." },
        { de: "Das renovierte Haus sieht super aus.", uk: "Відремонтований будинок виглядає чудово." },
        { de: "Von allen bewundert, gewann sie den Preis.", uk: "Усіма захоплена, вона виграла приз." },
        { de: "Am Flughafen angekommen, rief er ein Taxi.", uk: "Приїхавши в аеропорт, він викликав таксі." },
        { de: "Die vom Sturm zerstörten Häuser wurden neu gebaut.", uk: "Будинки, зруйновані бурею, відбудували." },
        { de: "Lachend erzählte er die Geschichte.", uk: "Сміючись, він розповів історію." },
        { de: "Der von uns diskutierte Vorschlag ist interessant.", uk: "Пропозиція, яку ми обговорювали, цікава." },
        { de: "Kaum angekommen, musste er weiterreisen.", uk: "Ледве прибувши, він мусив їхати далі." },
      ],
      tip: "P I = <b>активна одночасність</b>; P II = <b>пасив/передминуле</b>. У звороті кома обов'язкова.",
      mistakes: [
        { wrong: "Angekommt in Berlin, …", right: "In Berlin angekommen, …" },
        { wrong: "Der lachte Mann", right: "Der lachende Mann" },
      ],
      exercises: {}, prevSlug: "modalpartizip", nextSlug: "nominalisierung-c1",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["утворювати P I / P II","розуміти активне vs пасивне значення","скорочувати relativsätze","будувати дієприкметникові звороти"],
      ruleBox: { rule: "<b>P I = основа + -end</b> (актив); <b>P II</b> = класична форма (пасив / передминуле). Обидва відмінюються як прикметники." },
      summary: [
        "P I → активне, одночасне.",
        "P II → пасивне або передминуле.",
        "Заміна relativsatz → компактніше.",
        "Зворот у кінці підрядного, кома обов'язкова.",
      ],
    },
    exercises15: [
      { type: "mc", q: "der ___ Junge (lachen)", options: ["gelacht","lachte","lachende","lachend"], correct: 2 },
      { type: "mc", q: "das ___ Haus (renovieren)", options: ["renovierende","renovierte","renoviert","renovieren"], correct: 1 },
      { type: "mc", q: "In Berlin ___, rief er an.", options: ["ankommen","angekommen","angekommt","kommend"], correct: 1 },
      { type: "mc", q: "«der Mann, der lacht» = «der ___ Mann»", options: ["gelachte","lachende","lachte","lacht"], correct: 1 },
      { type: "gap", q: "das vom Sturm zerstört___ Haus (Nom.)", answer: "e" },
      { type: "gap", q: "___ ging er weg. (lachen — adverbial P I)", answer: "Lachend" },
      { type: "gap", q: "Am Flughafen ___, rief er ein Taxi. (ankommen — P II)", answer: "angekommen" },
      { type: "gap", q: "der von uns ___ Vorschlag (diskutieren, P II)", answer: "diskutierte" },
      { type: "tf", q: "Partizip I має пасивне значення.", correct: false },
      { type: "tf", q: "Partizip II може виражати передминулу дію в звороті.", correct: true },
      { type: "match", prompt: "Форма → значення:", pairs: [
        { left: "der lachende Mann", right: "актив, одночасно" },
        { left: "das gebaute Haus", right: "пасив, результат" },
        { left: "In Wien angekommen", right: "передминула дія" },
        { left: "lachend erzählen", right: "супровідна дія" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Der lachte Mann winkte.", correct: ["Der lachende Mann winkte."] },
      { type: "multi", q: "Виділи Partizip I:", options: ["lachend","gelacht","lächelnd","gebaut","kommend","gegangen"], correct: [0,2,4] },
      { type: "order", prompt: "Склади зворот:", words: ["angekommen","Berlin","in","er","rief","an"], correct: ["In","Berlin","angekommen,","rief","er","an"] },
      { type: "translate", prompt: "Скороти relativsatz:", uk: "Будинок, який відремонтували, чудовий.", de: ["Das renovierte Haus ist super."] },
    ],
  },

  "nominalisierung-c1": {
    lesson: {
      slug: "nominalisierung-c1", level: "C1", category: CAT,
      titleDe: "Nominalisierung von Verben", titleUk: "Номіналізація дієслів",
      goal: "Перетворювати дієслівні речення на іменникові конструкції — стиль академічних і офіційних текстів.",
      explanation: [
        "<b>Номіналізація</b> = перетворення дієслова на іменник для економії, абстракції та формальності.",
        "Способи: <b>subst. Infinitiv</b> (<i>das Lesen</i>), <b>-ung</b> (<i>Erklärung</i>), <b>-tion/-ation</b> (<i>Diskussion, Präsentation</i>), <b>-nis</b> (<i>Ergebnis</i>), <b>кореневі</b> (<i>der Kauf, der Flug</i>).",
        "Підрядні часто перефразовують у іменникову групу: <i>Nachdem er angekommen war, → Nach seiner Ankunft…</i>",
        "У наукових текстах номіналізація <b>стискає</b> зміст: <i>bei der Bewertung der Ergebnisse</i> замість <i>wenn wir die Ergebnisse bewerten</i>.",
      ],
      table: {
        headers: ["Дієслово", "Nomen", "Тип"],
        rows: [
          ["lesen", "das Lesen / die Lektüre", "Infinitiv / Nomen"],
          ["erklären", "die Erklärung", "-ung"],
          ["diskutieren", "die Diskussion", "-ion"],
          ["ankommen", "die Ankunft", "кореневе"],
          ["entscheiden", "die Entscheidung", "-ung"],
          ["ergeben", "das Ergebnis", "-nis"],
        ],
      },
      examples: [
        { de: "Das Lesen von Fachliteratur ist wichtig.", uk: "Читання фахової літератури важливе." },
        { de: "Nach der Ankunft in Berlin begann die Konferenz.", uk: "Після прибуття в Берлін почалася конференція." },
        { de: "Die Erklärung des Phänomens war überzeugend.", uk: "Пояснення явища було переконливе." },
        { de: "Bei der Bewertung der Daten wurde ein Fehler entdeckt.", uk: "Під час оцінки даних виявили помилку." },
        { de: "Nach eingehender Diskussion wurde entschieden.", uk: "Після ґрунтовної дискусії було вирішено." },
        { de: "Die Umsetzung der Reform dauert Jahre.", uk: "Впровадження реформи триває роками." },
        { de: "Das Verstehen komplexer Texte erfordert Übung.", uk: "Розуміння складних текстів потребує практики." },
        { de: "Vor der Unterzeichnung des Vertrags…", uk: "Перед підписанням договору…" },
      ],
      tip: "Пиши «економно»: замість <i>Nachdem wir das gemacht haben</i> — <b>Nach der Durchführung</b>. Але не перевантажуй — 2–3 номіналізації на речення максимум.",
      mistakes: [
        { wrong: "Die Erklärungen des Problems…", right: "Die Erklärung des Problems…" },
        { wrong: "Nach ankommen in Berlin…", right: "Nach der Ankunft in Berlin…" },
      ],
      exercises: {}, prevSlug: "partizip-satzverkuerzung", nextSlug: "verben-indirekte-rede",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["утворювати іменники від дієслів різними суфіксами","перефразовувати підрядне через іменникову групу","доречно вживати у формальному стилі"],
      ruleBox: { rule: "<b>Verb → Nomen</b> через -ung/-tion/-nis/-Infinitiv/корінь. Підрядне <i>nachdem…</i> → <i>nach + Dat.</i>" },
      summary: [
        "Номіналізація = компактність + формальність.",
        "Головні суфікси: -ung, -tion, -nis.",
        "Підрядне часто → прийменник + іменник.",
        "Не перевантажуй: 2–3 nomens/речення.",
      ],
    },
    exercises15: [
      { type: "mc", q: "«diskutieren» → das/die ___", options: ["Diskussion","Diskutierung","Diskutation","Disput"], correct: 0 },
      { type: "mc", q: "«entscheiden» → die ___", options: ["Entscheid","Entscheidung","Entscheidnis","Entscheidation"], correct: 1 },
      { type: "mc", q: "«ankommen» → die ___", options: ["Ankommung","Ankunft","Angekomm","Ankommenheit"], correct: 1 },
      { type: "mc", q: "«ergeben» → das ___", options: ["Ergebung","Ergebnis","Ergebnung","Erge"], correct: 1 },
      { type: "gap", q: "«erklären» → die ___", answer: "Erklärung" },
      { type: "gap", q: "«umsetzen» → die ___", answer: "Umsetzung" },
      { type: "gap", q: "«fliegen» → der ___", answer: "Flug" },
      { type: "gap", q: "«unterzeichnen» → die ___", answer: "Unterzeichnung" },
      { type: "tf", q: "Суфікс -ung майже завжди дає рід die.", correct: true },
      { type: "tf", q: "Nominalisierung використовується переважно в розмовному стилі.", correct: false },
      { type: "match", prompt: "Verb → Nomen:", pairs: [
        { left: "lesen", right: "Lektüre" },
        { left: "prüfen", right: "Prüfung" },
        { left: "kaufen", right: "Kauf" },
        { left: "erkennen", right: "Erkenntnis" },
      ]},
      { type: "correct", prompt: "Перефразуй у формальний стиль:", wrong: "Nachdem wir angekommen sind, begann die Sitzung.", correct: ["Nach unserer Ankunft begann die Sitzung."] },
      { type: "multi", q: "Виділи номіналізації:", options: ["die Erklärung","erklären","die Diskussion","diskutieren","das Lesen","lesen"], correct: [0,2,4] },
      { type: "order", prompt: "Склади:", words: ["Ankunft","Berlin","der","in","nach","begann","Konferenz","die"], correct: ["Nach","der","Ankunft","in","Berlin","begann","die","Konferenz"] },
      { type: "translate", prompt: "Номіналізуй:", uk: "Перед підписанням договору…", de: ["Vor der Unterzeichnung des Vertrags…"] },
    ],
  },

  "verben-indirekte-rede": {
    lesson: {
      slug: "verben-indirekte-rede", level: "C1", category: CAT,
      titleDe: "Verben der indirekten Rede", titleUk: "Дієслова непрямої мови",
      goal: "Володіти багатим репертуаром дієслів введення чужого висловлювання: sagen, behaupten, betonen, einräumen…",
      explanation: [
        "У формальних текстах чуже висловлювання вводять <b>різними дієсловами</b>, які передають ставлення автора: нейтральне, критичне, схвальне, обережне.",
        "Нейтральні: <i>sagen, äußern, erklären, feststellen, berichten, mitteilen</i>.",
        "Впевнені/переконливі: <i>betonen, hervorheben, unterstreichen, versichern, beharren</i>.",
        "Обережні/сумнівні: <i>vermuten, andeuten, meinen, glauben, annehmen</i>.",
        "Критичні: <i>behaupten, kritisieren, bemängeln, einwenden, bestreiten</i>.",
        "Погоджувальні: <i>einräumen, zustimmen, bestätigen, zugeben</i>.",
        "Часто поєднуються з <b>Konjunktiv I</b>: <i>Er behauptet, er sei unschuldig</i>.",
      ],
      table: {
        headers: ["Група", "Дієслово", "Приклад"],
        rows: [
          ["Нейтр.", "erklären", "Er erklärte, er sei müde."],
          ["Впевн.", "betonen", "Sie betonte, das sei wichtig."],
          ["Крит.", "behaupten", "Er behauptet, er habe recht."],
          ["Погод.", "einräumen", "Er räumte ein, einen Fehler gemacht zu haben."],
          ["Сумнів.", "vermuten", "Man vermutet, es sei ein Unfall gewesen."],
        ],
      },
      examples: [
        { de: "Der Autor betont, die Ergebnisse seien signifikant.", uk: "Автор наголошує, що результати значущі." },
        { de: "Die Zeugin räumte ein, sie habe sich geirrt.", uk: "Свідок визнала, що помилилась." },
        { de: "Kritiker bemängeln, das Konzept sei unklar.", uk: "Критики зауважують, що концепція неясна." },
        { de: "Der Sprecher versicherte, alle Regeln würden eingehalten.", uk: "Речник запевнив, що всі правила дотримуються." },
        { de: "Man vermutet, der Täter sei geflohen.", uk: "Припускають, що злочинець утік." },
        { de: "Er bestreitet, davon gewusst zu haben.", uk: "Він заперечує, що знав про це." },
        { de: "Die Studie legt nahe, dass es einen Zusammenhang gibt.", uk: "Дослідження вказує на зв'язок." },
        { de: "Der Minister deutete an, es werde Reformen geben.", uk: "Міністр натякнув, що будуть реформи." },
      ],
      tip: "Вибір дієслова передає <b>ставлення автора</b>: <i>behaupten</i> — сумнів; <i>einräumen</i> — поступка; <i>betonen</i> — впевненість.",
      mistakes: [
        { wrong: "Er sagt, er ist krank. (у офіц. тексті)", right: "Er sagt, er sei krank." },
        { wrong: "Sie räumte ein, dass sie hat sich geirrt.", right: "Sie räumte ein, dass sie sich geirrt habe." },
      ],
      exercises: {}, prevSlug: "nominalisierung-c1", nextSlug: "bedeutung-aehnlicher-verben-c1",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["класифікувати дієслова введення","вибирати дієслово за ставленням автора","поєднувати з K.I / K.II","розуміти семантичні нюанси"],
      ruleBox: { rule: "Дієслово введення + <b>Konjunktiv I</b> (або K.II при збігу форм). Вибір дієслова = ставлення автора." },
      summary: [
        "5 груп: нейтральні, впевнені, критичні, погоджувальні, сумнівні.",
        "K.I у 3 ос. одн.; K.II — коли форма = Indikativ.",
        "«behaupten» ≠ «sagen»: перше містить сумнів.",
        "«einräumen» = поступитись, визнати.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Він упевнено підкреслює → er ___", options: ["vermutet","betont","behauptet","bestreitet"], correct: 1 },
      { type: "mc", q: "Він визнає помилку → er ___", options: ["betont","räumt ein","bestreitet","behauptet"], correct: 1 },
      { type: "mc", q: "Він заперечує → er ___", options: ["bestätigt","bestreitet","betont","erklärt"], correct: 1 },
      { type: "mc", q: "Автор сумнівно припускає → er ___", options: ["betont","behauptet","vermutet","versichert"], correct: 2 },
      { type: "gap", q: "Sie betonte, das ___ wichtig. (sein K.I)", answer: "sei" },
      { type: "gap", q: "Er räumte ein, er ___ sich geirrt. (haben K.I)", answer: "habe" },
      { type: "gap", q: "Man vermutet, der Täter ___ geflohen. (sein K.I)", answer: "sei" },
      { type: "gap", q: "Er ___, davon gewusst zu haben. (bestreiten Präs.)", answer: "bestreitet" },
      { type: "tf", q: "«behaupten» = нейтральне «sagen».", correct: false, explain: "Містить відтінок сумніву." },
      { type: "tf", q: "«einräumen» = визнати, поступитись.", correct: true },
      { type: "match", prompt: "Дієслово → значення:", pairs: [
        { left: "betonen", right: "підкреслювати" },
        { left: "einräumen", right: "визнавати" },
        { left: "bestreiten", right: "заперечувати" },
        { left: "andeuten", right: "натякати" },
      ]},
      { type: "correct", prompt: "Виправ (офіц. стиль):", wrong: "Er sagt, er ist krank.", correct: ["Er sagt, er sei krank."] },
      { type: "multi", q: "Виділи дієслова введення чужої мови:", options: ["betonen","essen","behaupten","einräumen","fahren","vermuten"], correct: [0,2,3,5] },
      { type: "order", prompt: "Склади:", words: ["ein","er","einen","habe","Fehler","gemacht","räumte"], correct: ["Er","räumte","ein,","er","habe","einen","Fehler","gemacht"] },
      { type: "translate", prompt: "Переклади:", uk: "Автор наголошує, що результати важливі.", de: ["Der Autor betont, die Ergebnisse seien wichtig."] },
    ],
  },

  "bedeutung-aehnlicher-verben-c1": {
    lesson: {
      slug: "bedeutung-aehnlicher-verben-c1", level: "C1", category: CAT,
      titleDe: "Bedeutungsunterschiede ähnlicher Verben", titleUk: "Значеннєві відмінності схожих дієслів (C1)",
      goal: "Розрізняти близькі за значенням C1-дієслова: erkennen/erfahren, ändern/verändern, erwarten/hoffen…",
      explanation: [
        "На C1 багато дієслів мають тонкі стилістичні або семантичні відмінності. Помилка у виборі — типова ознака рівня B2.",
        "<b>erkennen</b> = впізнавати (за ознакою); <b>erfahren</b> = дізнаватися (нова інформація).",
        "<b>ändern</b> = змінити (частково, свідомо); <b>verändern</b> = змінити (глибоко, часто без волі).",
        "<b>erwarten</b> = очікувати (об'єктивно); <b>hoffen</b> = сподіватися (суб'єктивно).",
        "<b>brauchen</b> = потребувати (речі); <b>benötigen</b> = формально те саме; <b>bedürfen (+ Gen.)</b> — офіц.",
        "<b>fortsetzen</b> = продовжити (перериване); <b>weitermachen</b> = розмовне; <b>fortfahren</b> = продовжити (мову/дію).",
      ],
      table: {
        headers: ["Пара", "Різниця", "Приклад"],
        rows: [
          ["erkennen / erfahren", "впізн. / дізн.", "Ich erkannte ihn / Ich erfuhr die Wahrheit."],
          ["ändern / verändern", "част. / глибоко", "Ich ändere den Plan / Das verändert alles."],
          ["erwarten / hoffen", "об'єкт. / суб'єкт.", "Wir erwarten Regen / Ich hoffe auf Sonne."],
          ["brauchen / benötigen", "нейтр. / формально", "Ich brauche Hilfe / Wir benötigen Unterstützung."],
        ],
      },
      examples: [
        { de: "Ich habe ihn an der Stimme erkannt.", uk: "Я впізнав його за голосом." },
        { de: "Ich habe erst gestern von seinem Umzug erfahren.", uk: "Я дізнався про його переїзд тільки вчора." },
        { de: "Wir müssen den Plan ändern.", uk: "Ми маємо змінити план." },
        { de: "Der Krieg hat das Land völlig verändert.", uk: "Війна повністю змінила країну." },
        { de: "Wir erwarten die Ergebnisse morgen.", uk: "Ми очікуємо результати завтра." },
        { de: "Ich hoffe, dass alles gut wird.", uk: "Я сподіваюся, що все буде добре." },
        { de: "Diese Frage bedarf einer sorgfältigen Prüfung.", uk: "Це питання потребує ретельного розгляду." },
        { de: "Wir setzten die Diskussion nach der Pause fort.", uk: "Ми продовжили дискусію після перерви." },
      ],
      tip: "Запам'ятовуй такі пари <b>у контексті</b>, а не окремо — контекст показує, який відтінок підходить.",
      mistakes: [
        { wrong: "Ich erfahre ihn an der Stimme.", right: "Ich erkenne ihn an der Stimme." },
        { wrong: "Wir hoffen die Ergebnisse morgen.", right: "Wir erwarten die Ergebnisse morgen." },
      ],
      exercises: {}, prevSlug: "verben-indirekte-rede", nextSlug: "verbvalenz",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["розрізняти 5+ пар схожих дієслів","вибирати правильне за контекстом","знати стилістичні реєстри","уникати типових B2-помилок"],
      ruleBox: { rule: "Пари схожих дієслів рідко взаємозамінні — <b>вирішальні: контекст + реєстр + глибина зміни</b>." },
      summary: [
        "erkennen ≠ erfahren.",
        "ändern ≠ verändern (глибина).",
        "erwarten ≠ hoffen (об'єктивність).",
        "brauchen < benötigen < bedürfen (формальність).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Я впізнав його за голосом → Ich habe ihn ___.", options: ["erfahren","erkannt","gewusst","gemerkt"], correct: 1 },
      { type: "mc", q: "Я дізнався правду → Ich habe die Wahrheit ___.", options: ["erkannt","erfahren","gewusst","erfahrt"], correct: 1 },
      { type: "mc", q: "Війна повністю змінила країну → hat das Land ___.", options: ["geändert","verändert","gewechselt","umgeändert"], correct: 1 },
      { type: "mc", q: "Ми очікуємо результати → Wir ___ die Ergebnisse.", options: ["hoffen","erwarten","erhoffen","warten"], correct: 1 },
      { type: "gap", q: "Ich ___ auf gutes Wetter. (сподіватись)", answer: "hoffe" },
      { type: "gap", q: "Wir ___ Unterstützung. (формально «потребуємо»)", answer: "benötigen" },
      { type: "gap", q: "Wir setzten die Diskussion ___ .", answer: "fort" },
      { type: "gap", q: "Diese Frage ___ einer Prüfung. (bedürfen)", answer: "bedarf" },
      { type: "tf", q: "«verändern» глибше, ніж «ändern».", correct: true },
      { type: "tf", q: "«hoffen» і «erwarten» повністю синонімічні.", correct: false },
      { type: "match", prompt: "Дієслово → значення:", pairs: [
        { left: "erkennen", right: "впізнавати" },
        { left: "erfahren", right: "дізнаватися" },
        { left: "ändern", right: "змінити (частково)" },
        { left: "verändern", right: "змінити (глибоко)" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich erfahre ihn an der Stimme.", correct: ["Ich erkenne ihn an der Stimme."] },
      { type: "multi", q: "Виділи формальні синоніми «brauchen»:", options: ["benötigen","bedürfen","haben","kriegen","erfordern"], correct: [0,1,4] },
      { type: "order", prompt: "Склади:", words: ["Land","völlig","hat","verändert","der","Krieg","das"], correct: ["Der","Krieg","hat","das","Land","völlig","verändert"] },
      { type: "translate", prompt: "Переклади:", uk: "Я сподіваюся, що все буде добре.", de: ["Ich hoffe, dass alles gut wird."] },
    ],
  },

  "verbvalenz": {
    lesson: {
      slug: "verbvalenz", level: "C1", category: CAT,
      titleDe: "Verbvalenz", titleUk: "Валентність дієслова",
      goal: "Аналізувати, скільки і яких доповнень (Ergänzungen) вимагає дієслово, і будувати з ними правильні речення.",
      explanation: [
        "<b>Valenz</b> = здатність дієслова відкривати «місця» для обов'язкових доповнень (Ergänzungen).",
        "<b>Нуль-валентні</b>: <i>es regnet, es schneit</i> — не мають підмета-агенса.",
        "<b>Одновалентні</b>: <i>schlafen, lachen</i> — тільки підмет.",
        "<b>Двовалентні</b>: <i>lesen (etw.), helfen (jdm.), warten (auf etw.)</i> — підмет + 1 доповнення.",
        "<b>Тривалентні</b>: <i>geben (jdm. etw.), stellen (etw. auf etw.)</i> — підмет + 2 доповнення.",
        "Доповнення бувають: Nom-, Akk-, Dat-, Gen-, Präp-, Situativ-, Direktiv-.",
      ],
      table: {
        headers: ["Валентність", "Приклад", "Схема"],
        rows: [
          ["1", "Sie schläft.", "N"],
          ["2 (Akk)", "Er liest ein Buch.", "N + A"],
          ["2 (Dat)", "Ich helfe dir.", "N + D"],
          ["2 (Präp)", "Ich warte auf dich.", "N + P(auf+A)"],
          ["3", "Er gibt ihr das Buch.", "N + D + A"],
          ["3 (Präp)", "Sie legt das Buch auf den Tisch.", "N + A + P(auf+A)"],
        ],
      },
      examples: [
        { de: "Es regnet stark.", uk: "Сильно дощить." },
        { de: "Das Kind schläft ruhig.", uk: "Дитина спокійно спить." },
        { de: "Ich lese ein spannendes Buch.", uk: "Я читаю захопливу книгу." },
        { de: "Kannst du mir helfen?", uk: "Можеш мені допомогти?" },
        { de: "Wir warten auf den Zug.", uk: "Ми чекаємо на потяг." },
        { de: "Er gab dem Kind einen Apfel.", uk: "Він дав дитині яблуко." },
        { de: "Sie legte das Buch auf den Tisch.", uk: "Вона поклала книгу на стіл." },
        { de: "Der Lehrer erklärt uns die Regel.", uk: "Вчитель пояснює нам правило." },
      ],
      tip: "Валентність слова треба знати <b>разом із відмінком/прийменником</b>: <i>helfen + Dat.</i>, <i>fragen + Akk.</i>",
      mistakes: [
        { wrong: "Ich helfe dich.", right: "Ich helfe dir." },
        { wrong: "Sie legt das Buch auf dem Tisch. (рух)", right: "Sie legt das Buch auf den Tisch." },
      ],
      exercises: {}, prevSlug: "bedeutung-aehnlicher-verben-c1", nextSlug: "verben-wissenschaft",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["визначати валентність дієслова","обирати правильний відмінок доповнення","розрізняти Akk- і Dat-об'єкти","поєднувати з Präp-доповненнями"],
      ruleBox: { rule: "Валентність = <b>к-сть обов'язкових доповнень</b>. Тип доповнення (Akk/Dat/Präp) — <b>фіксований для кожного дієслова</b>." },
      summary: [
        "0-, 1-, 2-, 3-валентні дієслова.",
        "Типи Ergänzung: N/A/D/G/P/Sit/Dir.",
        "helfen + Dat., fragen + Akk. — вивчати парою.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich helfe ___.", options: ["dich","dir","dein","du"], correct: 1 },
      { type: "mc", q: "Er fragt ___.", options: ["mir","mich","meiner","mein"], correct: 1 },
      { type: "mc", q: "Sie wartet ___ den Bus.", options: ["auf","für","an","zu"], correct: 0 },
      { type: "mc", q: "Er gibt ___ das Buch.", options: ["die Frau","der Frau","den Frau","dem Frau"], correct: 1 },
      { type: "gap", q: "«schlafen» — валентність: ___", answer: "1" },
      { type: "gap", q: "«geben» — валентність: ___", answer: "3" },
      { type: "gap", q: "«warten» вимагає прийменник ___", answer: "auf" },
      { type: "gap", q: "«helfen» вимагає відмінок ___", answer: "Dat" },
      { type: "tf", q: "«es regnet» — 0-валентне.", correct: true },
      { type: "tf", q: "«fragen» вимагає Dat.", correct: false },
      { type: "match", prompt: "Дієслово → тип доповнення:", pairs: [
        { left: "helfen", right: "Dat" },
        { left: "fragen", right: "Akk" },
        { left: "warten", right: "auf + Akk" },
        { left: "geben", right: "Dat + Akk" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich helfe dich.", correct: ["Ich helfe dir."] },
      { type: "multi", q: "Виділи 3-валентні дієслова:", options: ["geben","schlafen","legen","lesen","zeigen"], correct: [0,2,4] },
      { type: "order", prompt: "Склади:", words: ["Buch","dem","der","Kind","gab","ein","Vater"], correct: ["Der","Vater","gab","dem","Kind","ein","Buch"] },
      { type: "translate", prompt: "Переклади:", uk: "Він дав їй книгу.", de: ["Er gab ihr ein Buch."] },
    ],
  },

  "verben-wissenschaft": {
    lesson: {
      slug: "verben-wissenschaft", level: "C1", category: CAT,
      titleDe: "Verben in wissenschaftlichen Texten", titleUk: "Дієслова в наукових текстах",
      goal: "Володіти набором дієслів академічного стилю: darstellen, untersuchen, belegen, argumentieren…",
      explanation: [
        "Академічна німецька уникає розмовних дієслів (<i>machen, tun, sagen</i>) і надає перевагу <b>точним, стилістично нейтральним</b>.",
        "Опис/презентація: <i>darstellen, beschreiben, aufzeigen, erläutern, veranschaulichen</i>.",
        "Дослідження: <i>untersuchen, analysieren, überprüfen, erforschen, ermitteln</i>.",
        "Аргументація: <i>argumentieren, belegen, nachweisen, begründen, widerlegen, in Frage stellen</i>.",
        "Висновок: <i>schlussfolgern, resümieren, zusammenfassen, festhalten</i>.",
        "Часто в пасиві або з <b>man</b>: <i>Es wird gezeigt, dass… / Man kann feststellen…</i>",
      ],
      table: {
        headers: ["Функція", "Дієслово", "Приклад"],
        rows: [
          ["опис", "darstellen", "Die Studie stellt die Ergebnisse dar."],
          ["досл.", "untersuchen", "Wir untersuchen den Einfluss."],
          ["доказ", "belegen", "Die Daten belegen die These."],
          ["спрост.", "widerlegen", "Die Studie widerlegt die Annahme."],
          ["висн.", "schlussfolgern", "Daraus lässt sich schlussfolgern, dass…"],
        ],
      },
      examples: [
        { de: "Die Studie untersucht den Zusammenhang zwischen A und B.", uk: "Дослідження вивчає зв'язок між А і Б." },
        { de: "Die Ergebnisse belegen die aufgestellte Hypothese.", uk: "Результати підтверджують висунуту гіпотезу." },
        { de: "Der Autor argumentiert, dass…", uk: "Автор аргументує, що…" },
        { de: "Es lässt sich feststellen, dass die Methode wirksam ist.", uk: "Можна констатувати, що метод є ефективним." },
        { de: "Die Daten widerlegen die frühere Annahme.", uk: "Дані спростовують попередню гіпотезу." },
        { de: "Im Folgenden wird die Methode erläutert.", uk: "Далі буде роз'яснено метод." },
        { de: "Zusammenfassend lässt sich sagen, dass…", uk: "Підсумовуючи, можна сказати, що…" },
        { de: "Die Untersuchung zeigt einen deutlichen Trend auf.", uk: "Дослідження виявляє чіткий тренд." },
      ],
      tip: "Уникай <i>machen/tun</i> в наукових текстах — заміни на конкретне дієслово: <i>eine Untersuchung durchführen</i>, <i>eine Analyse vornehmen</i>.",
      mistakes: [
        { wrong: "Die Studie macht den Zusammenhang.", right: "Die Studie untersucht den Zusammenhang." },
        { wrong: "Der Autor sagt, dass…", right: "Der Autor argumentiert / stellt fest, dass…" },
      ],
      exercises: {}, prevSlug: "verbvalenz",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["використовувати 15+ академічних дієслів","замінювати machen/sagen точнішими формами","будувати нейтральні наукові речення","поєднувати з пасивом/man/lässt sich"],
      ruleBox: { rule: "Академічний стиль: <b>точні дієслова + пасив/man/lässt sich</b>. Уникати machen/tun/sagen." },
      summary: [
        "5 функціональних груп: опис, дослідження, аргументація, спростування, висновок.",
        "Часті пасивні конструкції: es wird gezeigt/festgestellt.",
        "«lässt sich + Inf» = «можна» (наук. стиль).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Наукове «досліджувати» → ___.", options: ["machen","untersuchen","tun","haben"], correct: 1 },
      { type: "mc", q: "«підтверджувати гіпотезу» → ___", options: ["belegen","zeigen","sagen","machen"], correct: 0 },
      { type: "mc", q: "«спростовувати» → ___", options: ["bestätigen","widerlegen","erklären","zeigen"], correct: 1 },
      { type: "mc", q: "«робити висновок» → ___", options: ["denken","meinen","schlussfolgern","sagen"], correct: 2 },
      { type: "gap", q: "Die Daten ___ die These. (доказ)", answer: "belegen" },
      { type: "gap", q: "Es lässt sich ___, dass die Methode wirksam ist. (констатувати)", answer: "feststellen" },
      { type: "gap", q: "Der Autor ___, dass A B beeinflusst. (аргументує)", answer: "argumentiert" },
      { type: "gap", q: "Im Folgenden ___ die Methode erläutert. (пасив)", answer: "wird" },
      { type: "tf", q: "У науковому стилі краще писати «Der Autor sagt».", correct: false, explain: "Точніше: argumentiert / stellt fest." },
      { type: "tf", q: "«lässt sich feststellen» — типовий науковий зворот.", correct: true },
      { type: "match", prompt: "Функція → дієслово:", pairs: [
        { left: "опис", right: "darstellen" },
        { left: "дослідження", right: "untersuchen" },
        { left: "доказ", right: "belegen" },
        { left: "спростування", right: "widerlegen" },
      ]},
      { type: "correct", prompt: "Заміни розмовне на академічне:", wrong: "Die Studie macht den Zusammenhang.", correct: ["Die Studie untersucht den Zusammenhang."] },
      { type: "multi", q: "Виділи академічні дієслова:", options: ["untersuchen","machen","belegen","tun","argumentieren","sagen"], correct: [0,2,4] },
      { type: "order", prompt: "Склади:", words: ["Zusammenhang","untersucht","den","Studie","die"], correct: ["Die","Studie","untersucht","den","Zusammenhang"] },
      { type: "translate", prompt: "Переклади науково:", uk: "Дослідження підтверджує гіпотезу.", de: ["Die Studie belegt die Hypothese."] },
    ],
  },
};
