// B1 · Genitiv — 6 повних уроків.
import type { B1Map } from "./_helpers";
const CAT = "Відмінки · Genitiv";

const baseExtras = (rule: string, tips: string[], summary: string[]) => ({
  duration: 14, premium: true, ruleBox: { rule }, ukrainianTips: tips, summary,
});

export const genitivB1: B1Map = {
  "was-ist-genitiv": {
    lesson: {
      slug: "was-ist-genitiv", level: "B1", category: CAT,
      titleDe: "Was ist der Genitiv?", titleUk: "Що таке Genitiv?",
      goal: "Зрозуміти, що таке Genitiv, на яке питання відповідає й коли вживається.",
      explanation: [
        "<b>Genitiv</b> — родовий відмінок. Відповідає на питання <b>Wessen?</b> (Чий? Кого? Чого?).",
        "Виражає <b>належність</b>, <b>відношення</b> або <b>частину чого-небудь</b>: <i>das Auto <b>des Vaters</b></i> = «машина батька».",
        "Уживається в письмових/офіційних текстах. У розмові часто заміняється на <b>von + Dativ</b>: <i>das Auto von dem Vater</i>.",
        "Також обов'язковий після певних <b>прийменників</b> (wegen, trotz, während, statt) і деяких <b>дієслів</b>/<b>прикметників</b>.",
      ],
      table: {
        headers: ["Рід", "Артикль (Gen.)", "Закінчення іменника"],
        rows: [
          ["m / n", "des", "-s / -es"],
          ["f", "der", "—"],
          ["Pl.", "der", "—"],
        ],
      },
      examples: [
        { de: "Das ist das Auto des Vaters.", uk: "Це машина батька." },
        { de: "Wessen Buch ist das?", uk: "Чия це книга?" },
        { de: "Das Buch der Lehrerin liegt hier.", uk: "Книга вчительки лежить тут." },
        { de: "Die Spielzeuge der Kinder sind neu.", uk: "Іграшки дітей нові." },
        { de: "Wegen des Regens bleiben wir.", uk: "Через дощ ми лишаємося." },
        { de: "Trotz der Kälte gehen wir spazieren.", uk: "Незважаючи на холод, ми йдемо гуляти." },
        { de: "Anstatt des Buches kaufte sie eine Zeitschrift.", uk: "Замість книги вона купила журнал." },
        { de: "Während des Films aßen wir Popcorn.", uk: "Під час фільму ми їли попкорн." },
      ],
      tip: "Питання Genitiv — <b>Wessen?</b> (чий, кого, чого).",
      mistakes: [
        { wrong: "das Auto den Vater", right: "das Auto des Vaters" },
        { wrong: "wegen den Regen", right: "wegen des Regens" },
      ],
      exercises: {}, nextSlug: "artikel-genitiv",
    },
    extras: baseExtras(
      "Genitiv = «чий/чого». <b>des/der/des/der</b>. m/n іменники + <b>-s/-es</b>.",
      ["Українські «батька / мами / книги» = Genitiv.", "Розмовно → von + Dativ."],
      ["Wessen? — питання Gen.", "Належність / належність частини.", "Прийменники wegen, trotz, während, statt."],
    ),
    exercises15: [
      { type: "mc", q: "Яке питання — Genitiv?", options: ["Wem?","Wen?","Wessen?","Was?"], correct: 2 },
      { type: "mc", q: "Das Auto ___ Vaters.", options: ["der","des","den","dem"], correct: 1 },
      { type: "mc", q: "Das Buch ___ Lehrerin.", options: ["des","der","den","dem"], correct: 1 },
      { type: "gap", q: "Die Spielzeuge ___ Kinder. (Pl.)", answer: "der" },
      { type: "gap", q: "Wegen ___ Regens bleiben wir. (der Regen)", answer: "des" },
      { type: "gap", q: "Trotz ___ Kälte gehen wir. (die Kälte)", answer: "der" },
      { type: "tf", q: "У Genitiv m/n іменник часто отримує -s або -es.", correct: true },
      { type: "tf", q: "Genitiv ніколи не вживається в офіційних текстах.", correct: false },
      { type: "match", prompt: "Рід → артикль Gen.:", pairs: [
        { left: "der Mann", right: "des Mannes" }, { left: "die Frau", right: "der Frau" },
        { left: "das Kind", right: "des Kindes" }, { left: "die Kinder", right: "der Kinder" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das Auto den Vaters.",
        correct: ["Das Auto des Vaters."] },
      { type: "correct", prompt: "Виправ:", wrong: "wegen den Regen",
        correct: ["wegen des Regens"] },
      { type: "multi", q: "Які речення — у Gen.?", options: [
        "Das Auto des Vaters.","Das Auto dem Vater.","Wegen des Regens.","Wegen dem Regen."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["ist","Auto","das","Vaters","des"], correct: ["das","ist","das","Auto","des","Vaters"], explain: "Без початкового «Das ist»." },
      { type: "translate", prompt: "Переклади:", uk: "Це книга вчительки.",
        de: ["Das ist das Buch der Lehrerin."] },
      { type: "translate", prompt: "Переклади (розмовно з von):", uk: "машина батька",
        de: ["das Auto von dem Vater","das Auto vom Vater"] },
      { type: "writeFree", prompt: "Напиши 3 речення з Gen.",
        sample: "Das ist die Tasche meiner Mutter. Wegen des schlechten Wetters bleiben wir zu Hause. Trotz der vielen Aufgaben gehe ich heute ins Kino." },
    ],
  },

  "artikel-genitiv": {
    lesson: {
      slug: "artikel-genitiv", level: "B1", category: CAT,
      titleDe: "Artikel im Genitiv", titleUk: "Артиклі в Genitiv",
      goal: "Знати всі форми означеного, неозначеного й нульового артикля в Genitiv, а також закінчення іменника.",
      explanation: [
        "Означений артикль у Gen.: <b>des (m), der (f), des (n), der (Pl.)</b>.",
        "Неозначений: <b>eines / einer / eines / — (Pl. немає)</b>.",
        "Присвійний: за тим самим зразком, що й неозначений: <b>meines / meiner / meines / meiner</b>.",
        "<b>Маск./нейтр. іменники в Gen. отримують -s або -es</b>: односкладові й закриті склади → <i>-es</i> (<i>des Mannes, des Kindes</i>), решта → <i>-s</i> (<i>des Lehrers, des Autos</i>).",
        "Жіночий рід і Plural — <b>без закінчення</b>.",
      ],
      table: {
        headers: ["", "m", "f", "n", "Pl."],
        rows: [
          ["der/die/das", "des Mannes", "der Frau", "des Kindes", "der Kinder"],
          ["ein/eine/ein", "eines Mannes", "einer Frau", "eines Kindes", "—"],
          ["mein/meine/mein", "meines Mannes", "meiner Frau", "meines Kindes", "meiner Kinder"],
        ],
      },
      examples: [
        { de: "das Auto des Mannes", uk: "машина чоловіка" },
        { de: "die Tasche der Frau", uk: "сумка жінки" },
        { de: "das Spielzeug des Kindes", uk: "іграшка дитини" },
        { de: "die Bücher der Kinder", uk: "книги дітей" },
        { de: "das Haus eines Freundes", uk: "будинок (одного) друга" },
        { de: "das Auto meines Vaters", uk: "машина мого батька" },
        { de: "der Titel des Buches", uk: "назва книги" },
        { de: "die Farbe der Augen", uk: "колір очей" },
      ],
      tip: "m/n → -s/-es; f/Pl. → без закінчення. Артикль завжди <b>-es / -er</b>.",
      mistakes: [
        { wrong: "des Mann", right: "des Mannes" },
        { wrong: "der Frauen Buch", right: "das Buch der Frauen" },
      ],
      exercises: {}, prevSlug: "was-ist-genitiv", nextSlug: "n-deklination-genitiv",
    },
    extras: baseExtras(
      "des/der/des/der + іменник (m/n: -s/-es; f/Pl.: 0).",
      ["Один склад → -es: des Mannes. Більше складів → -s: des Lehrers."],
      ["m/n: des + -s/-es.", "f/Pl.: der без закінчення.", "Присв./неозн.: -es/-er — як артикль."],
    ),
    exercises15: [
      { type: "mc", q: "Genitiv від <i>der Mann</i>:", options: ["dem Mann","den Mann","des Mannes","der Mann"], correct: 2 },
      { type: "mc", q: "Genitiv від <i>die Frau</i>:", options: ["der Frau","den Frau","des Frau","die Frau"], correct: 0 },
      { type: "mc", q: "Genitiv від <i>das Kind</i>:", options: ["dem Kind","des Kindes","der Kindes","das Kind"], correct: 1 },
      { type: "mc", q: "Genitiv від <i>die Kinder</i>:", options: ["der Kindern","den Kinder","der Kinder","des Kinder"], correct: 2 },
      { type: "gap", q: "das Buch ___ Lehrers (m).", answer: "des" },
      { type: "gap", q: "das Auto ___ Mutter (f).", answer: "der" },
      { type: "gap", q: "das Spielzeug ___ Kindes (n).", answer: "des" },
      { type: "gap", q: "die Tasche ___ Frauen (Pl.).", answer: "der" },
      { type: "tf", q: "У жіночому роді в Gen. іменник отримує -s.", correct: false },
      { type: "tf", q: "des Mannes — правильна форма Genitiv.", correct: true },
      { type: "match", prompt: "Рід → артикль Gen.:", pairs: [
        { left: "m", right: "des" }, { left: "f", right: "der" },
        { left: "n", right: "des" }, { left: "Pl.", right: "der" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "das Auto des Mann.", correct: ["das Auto des Mannes."] },
      { type: "multi", q: "Які форми правильні?",
        options: ["des Mannes","der Mannes","der Frau","des Frau","des Kindes"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "сумка моєї матері",
        de: ["die Tasche meiner Mutter"] },
      { type: "translate", prompt: "Переклади:", uk: "колір її очей",
        de: ["die Farbe ihrer Augen"] },
      { type: "writeFree", prompt: "Напиши 3 словосполучення з Gen.",
        sample: "das Auto meines Bruders, die Bücher der Schüler, das Haus eines Freundes" },
    ],
  },

  "n-deklination-genitiv": {
    lesson: {
      slug: "n-deklination-genitiv", level: "B1", category: CAT,
      titleDe: "n-Deklination im Genitiv", titleUk: "n-відмінювання у Genitiv",
      goal: "Правильно відмінювати «слабкі» іменники чоловічого роду (n-Deklination) в усіх відмінках, включно з Genitiv.",
      explanation: [
        "Іменники <b>n-Deklination</b> — це <b>чоловічі</b> іменники, які отримують <b>-n або -en у всіх відмінках, крім Nominativ Singular</b>.",
        "Сюди належать: <i>der Student, der Mensch, der Junge, der Kollege, der Herr, der Nachbar, der Tourist, der Polizist, der Präsident</i> та ін.",
        "У <b>Genitiv однини</b> зазвичай немає додаткового -s: <i>des Studenten</i> (а не <i>des Studentens</i>). Виняток: <b>der Herr</b> → <i>des Herrn</i> (Sg.) / <i>der Herren</i> (Pl.) і <b>der Name → des Namens</b>, <b>das Herz → des Herzens</b>.",
      ],
      table: {
        headers: ["", "Nom.", "Akk.", "Dat.", "Gen."],
        rows: [
          ["Sg.", "der Student", "den Studenten", "dem Studenten", "des Studenten"],
          ["Pl.", "die Studenten", "die Studenten", "den Studenten", "der Studenten"],
          ["Sg. (Herr)", "der Herr", "den Herrn", "dem Herrn", "des Herrn"],
          ["Sg. (Name)", "der Name", "den Namen", "dem Namen", "des Namens"],
        ],
      },
      examples: [
        { de: "Das ist das Buch des Studenten.", uk: "Це книга студента." },
        { de: "Wir helfen dem Studenten.", uk: "Ми допомагаємо студенту." },
        { de: "Ich sehe den Studenten.", uk: "Я бачу студента." },
        { de: "Das Auto des Herrn ist neu.", uk: "Машина пана нова." },
        { de: "Wie ist der Name des Kunden?", uk: "Яке ім'я клієнта?" },
        { de: "Wir kennen den Nachbarn.", uk: "Ми знаємо сусіда." },
        { de: "Die Meinung des Präsidenten ist wichtig.", uk: "Думка президента важлива." },
        { de: "Die Reise des Touristen war lang.", uk: "Подорож туриста була довга." },
      ],
      tip: "<b>Усі відмінки крім Nom. Sg.</b> отримують <b>-n / -en</b>. <i>Name, Herz</i> у Gen. — додатково <b>-s</b>.",
      mistakes: [
        { wrong: "Ich kenne den Student.", right: "Ich kenne den Studenten." },
        { wrong: "das Buch des Studentens", right: "das Buch des Studenten" },
      ],
      exercises: {}, prevSlug: "artikel-genitiv", nextSlug: "praep-genitiv-b1",
    },
    extras: baseExtras(
      "n-Deklination: <b>-n/-en у всіх відмінках, крім Nom. Sg.</b> Винятки: Name → -ns, Herr → -n/-en.",
      ["Списки слів n-Deklination треба вивчити.", "У Gen. немає додаткового -s, окрім <i>Name, Herz, Glaube</i>."],
      ["-n/-en усюди, крім Nom. Sg.", "Без додаткового -s (крім Name/Herz/Glaube)."],
    ),
    exercises15: [
      { type: "mc", q: "Gen. від <i>der Student</i>:",
        options: ["des Students","des Studentens","des Studenten","der Student"], correct: 2 },
      { type: "mc", q: "Akk. від <i>der Junge</i>:",
        options: ["den Junge","den Jungen","dem Jungen","des Jungen"], correct: 1 },
      { type: "mc", q: "Gen. від <i>der Herr</i> (Sg.):",
        options: ["des Herrs","des Herren","des Herrn","der Herr"], correct: 2 },
      { type: "gap", q: "Wir helfen dem ___. (der Student)", answer: "Studenten" },
      { type: "gap", q: "Das Buch des ___. (der Kollege)", answer: "Kollegen" },
      { type: "gap", q: "Der Name des ___. (der Kunde)", answer: "Kunden" },
      { type: "tf", q: "У n-Deklination -s у Gen. майже завжди додається.", correct: false },
      { type: "tf", q: "<i>der Name</i> у Gen. = <i>des Namens</i>.", correct: true },
      { type: "match", prompt: "Іменник → Gen. (Sg.):", pairs: [
        { left: "der Student", right: "des Studenten" },
        { left: "der Herr", right: "des Herrn" },
        { left: "der Name", right: "des Namens" },
        { left: "der Mensch", right: "des Menschen" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich sehe den Student.",
        correct: ["Ich sehe den Studenten."] },
      { type: "correct", prompt: "Виправ:", wrong: "das Buch des Studentens",
        correct: ["das Buch des Studenten"] },
      { type: "multi", q: "Які форми n-Deklination правильні?",
        options: ["den Jungen","den Junge","dem Studenten","dem Student","des Kollegen"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "ім'я клієнта",
        de: ["der Name des Kunden"] },
      { type: "translate", prompt: "Переклади:", uk: "Я бачу пана.",
        de: ["Ich sehe den Herrn."] },
      { type: "writeFree", prompt: "Напиши 2 речення з n-Deklination (Gen.).",
        sample: "Die Meinung des Präsidenten ist umstritten. Das Auto unseres Nachbarn ist immer sauber." },
    ],
  },

  "praep-genitiv-b1": {
    lesson: {
      slug: "praep-genitiv-b1", level: "B1", category: CAT,
      titleDe: "Präpositionen mit Genitiv", titleUk: "Прийменники з Genitiv",
      goal: "Уживати найважливіші прийменники з Genitiv: wegen, trotz, während, statt, aufgrund, innerhalb, außerhalb.",
      explanation: [
        "Прийменники з Genitiv типові для <b>письмових</b> і <b>офіційних</b> текстів. У розмові часто замінюються Dativ-конструкціями.",
        "Найважливіші: <b>wegen</b> (через/зважаючи), <b>trotz</b> (попри), <b>während</b> (під час), <b>statt/anstatt</b> (замість), <b>aufgrund</b> (на підставі), <b>innerhalb</b> (у межах), <b>außerhalb</b> (поза межами).",
        "У розмові: <i>wegen dem Regen</i> поряд із літ. <i>wegen des Regens</i>.",
      ],
      table: {
        headers: ["Prep.", "Значення", "Приклад"],
        rows: [
          ["wegen", "через", "wegen des Regens"],
          ["trotz", "попри", "trotz der Kälte"],
          ["während", "під час", "während des Films"],
          ["statt / anstatt", "замість", "statt des Buches"],
          ["aufgrund", "на підставі", "aufgrund der Ergebnisse"],
          ["innerhalb", "у межах", "innerhalb der Stadt"],
          ["außerhalb", "поза межами", "außerhalb der Saison"],
        ],
      },
      examples: [
        { de: "Wegen des Regens bleiben wir zu Hause.", uk: "Через дощ ми лишаємося вдома." },
        { de: "Trotz der Kälte spielen die Kinder draußen.", uk: "Попри холод діти граються надворі." },
        { de: "Während des Films war es still.", uk: "Під час фільму було тихо." },
        { de: "Statt des Autos nahmen wir das Rad.", uk: "Замість машини ми взяли велосипед." },
        { de: "Aufgrund der Studie verbietet man Plastik.", uk: "На підставі дослідження пластик забороняють." },
        { de: "Innerhalb einer Woche antworte ich.", uk: "У межах тижня я відповім." },
        { de: "Außerhalb der Stadt ist die Luft besser.", uk: "За межами міста повітря краще." },
        { de: "Anstatt des Kaffees trank er Tee.", uk: "Замість кави він пив чай." },
      ],
      tip: "У розмові — часто <i>wegen + Dativ</i>: <b>wegen dem Regen</b>. Літературно — <b>wegen des Regens</b>.",
      mistakes: [
        { wrong: "wegen den Regen", right: "wegen des Regens" },
        { wrong: "trotz dem Wetter", right: "trotz des Wetters" },
      ],
      exercises: {}, prevSlug: "n-deklination-genitiv", nextSlug: "genitiv-namen",
    },
    extras: baseExtras(
      "Літ. <b>wegen/trotz/während/statt/aufgrund + Gen.</b> У розмові часто Dativ.",
      ["В укр. «через/попри/під час/замість» — Gen. в німецькій."],
      ["wegen, trotz, während, statt, aufgrund, innerhalb, außerhalb + Gen.", "У розмові — часто Dativ."],
    ),
    exercises15: [
      { type: "mc", q: "Wegen ___ Regens bleiben wir.", options: ["der","des","dem","den"], correct: 1 },
      { type: "mc", q: "Trotz ___ Kälte gehen wir.", options: ["des","der","den","dem"], correct: 1 },
      { type: "gap", q: "Während ___ Films war es still. (der)", answer: "des" },
      { type: "gap", q: "Statt ___ Buches kaufte sie eine Zeitung. (das)", answer: "des" },
      { type: "gap", q: "Aufgrund ___ Studie ändern sie die Regel. (die)", answer: "der" },
      { type: "tf", q: "wegen у літ. мові вимагає Genitiv.", correct: true },
      { type: "tf", q: "während ніколи не вживається з Gen.", correct: false },
      { type: "match", prompt: "Prep. → значення:", pairs: [
        { left: "wegen", right: "через" }, { left: "trotz", right: "попри" },
        { left: "während", right: "під час" }, { left: "statt", right: "замість" },
        { left: "aufgrund", right: "на підставі" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "wegen den Regen",
        correct: ["wegen des Regens"] },
      { type: "correct", prompt: "Виправ:", wrong: "trotz dem Wetter",
        correct: ["trotz des Wetters"] },
      { type: "multi", q: "Які форми правильні (літ.)?",
        options: ["wegen des Regens","wegen dem Regen","trotz der Kälte","trotz die Kälte","während des Films"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["wegen","Regens","Hause","des","wir","zu","bleiben"],
        correct: ["wegen","des","Regens","bleiben","wir","zu","Hause"] },
      { type: "translate", prompt: "Переклади:", uk: "Попри погану погоду, ми вийшли.",
        de: ["Trotz des schlechten Wetters gingen wir raus.","Trotz des schlechten Wetters sind wir rausgegangen."] },
      { type: "translate", prompt: "Переклади:", uk: "Під час концерту телефони були вимкнені.",
        de: ["Während des Konzerts waren die Handys aus."] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними prep. Gen.",
        sample: "Wegen der Pandemie blieben wir lange zu Hause. Trotz des Regens machten wir einen Spaziergang. Während der Pause trinke ich immer Kaffee." },
    ],
  },

  "genitiv-namen": {
    lesson: {
      slug: "genitiv-namen", level: "B1", category: CAT,
      titleDe: "Genitiv bei Eigennamen", titleUk: "Genitiv з власними іменами",
      goal: "Правильно утворювати присвійні форми з власних імен — Annas Buch, Peters Auto.",
      explanation: [
        "З власними іменами Genitiv утворюється <b>без артикля</b>, а -s додається <b>безпосередньо до імені</b> й <b>стоїть перед іменником</b>: <i>Annas Buch, Peters Auto</i>.",
        "Якщо ім'я закінчується на <b>s, ß, x, z</b>, замість -s ставиться <b>апостроф</b>: <i>Max' Auto, Klaus' Haus</i>.",
        "Аналогічна форма для <b>родини</b>: <i>Schmidts Haus</i> = «дім Шмідтів» (Pl. за контекстом).",
        "Альтернатива з артиклем: <b>von + Dativ</b>: <i>das Auto von Peter</i> — нейтральна, розмовна.",
      ],
      examples: [
        { de: "Das ist Annas Buch.", uk: "Це книга Анни." },
        { de: "Peters Auto ist neu.", uk: "Машина Петра нова." },
        { de: "Max' Bruder studiert.", uk: "Брат Макса вчиться." },
        { de: "Klaus' Hund ist freundlich.", uk: "Собака Клауса дружній." },
        { de: "Schmidts Haus liegt am See.", uk: "Дім Шмідтів — біля озера." },
        { de: "Das Auto von Peter steht da.", uk: "Машина Петра стоїть там." },
        { de: "Marias Mutter wohnt in Wien.", uk: "Мама Марії живе у Відні." },
        { de: "Ich kenne Annas Schwester.", uk: "Я знаю сестру Анни." },
      ],
      tip: "Власне ім'я + <b>-s</b> (без артикля) перед іменником. <b>s/ß/x/z</b> → апостроф.",
      mistakes: [
        { wrong: "das Buch Annas", right: "Annas Buch" },
        { wrong: "Maxs Auto", right: "Max' Auto" },
      ],
      exercises: {}, prevSlug: "praep-genitiv-b1", nextSlug: "genitiv-vs-von",
    },
    extras: baseExtras(
      "Власні імена: <b>ім'я+s + іменник</b> (без артикля). На -s/-ß/-x/-z — апостроф.",
      ["Українське «Аннина книга» = Annas Buch.", "Альтернатива: <i>das Buch von Anna</i>."],
      ["Annas Buch.", "Max' Auto.", "Альт.: von + Dativ."],
    ),
    exercises15: [
      { type: "mc", q: "Книга Анни:", options: ["das Buch Annas","Annas Buch","Anna's Buch","Anna Buch"], correct: 1 },
      { type: "mc", q: "Машина Макса:", options: ["Maxs Auto","Max's Auto","Max' Auto","Max Auto"], correct: 2 },
      { type: "gap", q: "___ Mutter wohnt in Wien. (Maria)", answer: "Marias" },
      { type: "gap", q: "___ Hund ist freundlich. (Klaus)", answer: "Klaus'" },
      { type: "tf", q: "Якщо ім'я закінчується на -s, додаємо -s без апострофа.", correct: false },
      { type: "tf", q: "Genitiv від <i>Anna</i> = <i>Annas</i>.", correct: true },
      { type: "match", prompt: "Ім'я → Genitiv:", pairs: [
        { left: "Anna", right: "Annas" }, { left: "Peter", right: "Peters" },
        { left: "Max", right: "Max'" }, { left: "Klaus", right: "Klaus'" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Maxs Auto", correct: ["Max' Auto"] },
      { type: "correct", prompt: "Виправ:", wrong: "das Buch Annas", correct: ["Annas Buch"] },
      { type: "multi", q: "Які форми правильні?",
        options: ["Annas Buch","Anna's Buch","Peters Auto","Peter Auto","Max' Hund","Maxs Hund"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "сестра Анни", de: ["Annas Schwester"] },
      { type: "translate", prompt: "Переклади:", uk: "дім Шмідтів", de: ["Schmidts Haus"] },
      { type: "translate", prompt: "Переклади (розмовно):", uk: "машина Петра",
        de: ["das Auto von Peter","Peters Auto"] },
      { type: "tf", q: "<i>Schmidts Haus</i> може означати «дім родини Шмідтів».", correct: true },
      { type: "gap", q: "Ich kenne ___ Bruder. (Max)", answer: "Max'" },
      { type: "writeFree", prompt: "Напиши 3 речення з присвійними іменами.",
        sample: "Annas Buch liegt auf dem Tisch. Peters Auto ist neu. Max' Hund ist sehr lieb." },
    ],
  },

  "genitiv-vs-von": {
    lesson: {
      slug: "genitiv-vs-von", level: "B1", category: CAT,
      titleDe: "Genitiv oder von + Dativ?", titleUk: "Genitiv чи von + Dativ?",
      goal: "Розуміти, коли краще Genitiv, а коли — конструкція з <i>von + Dativ</i>.",
      explanation: [
        "Обидві структури виражають належність. <b>Genitiv</b> — типовий для <b>письмових</b> і <b>офіційних</b> текстів. <b>von + Dativ</b> — типовий для <b>розмови</b>.",
        "Genitiv <b>обов'язковий</b> у деяких контекстах: фіксовані вирази (<i>Tag der Arbeit, Mitglied des Vereins</i>), офіційні документи, заголовки.",
        "<b>von + Dativ</b> уживається: 1) у розмові; 2) з власними іменами без артикля (<i>das Auto von Peter</i>); 3) коли без артикля незрозуміло (<i>Bilder von Picasso</i>).",
        "Перед іменником без артикля у множині часто використовують <i>von</i>: <i>das Wachstum von Bäumen</i>.",
      ],
      table: {
        headers: ["Контекст", "Краще", "Приклад"],
        rows: [
          ["офіційно, текст", "Genitiv", "das Auto des Direktors"],
          ["розмова", "von + Dativ", "das Auto vom Direktor"],
          ["власне ім'я + іменник", "Apostrof / von", "Peters Auto / das Auto von Peter"],
          ["без артикля (Pl.)", "von", "die Hilfe von Freunden"],
        ],
      },
      examples: [
        { de: "Das Auto des Direktors steht hier.", uk: "Машина директора стоїть тут.", tag: "Gen." },
        { de: "Das ist das Auto vom Direktor.", uk: "Це машина директора.", tag: "розмовно" },
        { de: "Wegen des Regens bleiben wir.", uk: "Через дощ ми лишаємося.", tag: "Gen. (fest)" },
        { de: "Die Hilfe von Freunden ist wichtig.", uk: "Допомога друзів — важлива." },
        { de: "Tag der Arbeit", uk: "День праці", tag: "сталий вираз" },
        { de: "Bilder von Picasso", uk: "Картини Пікассо" },
        { de: "Petra ist die Schwester von Anna.", uk: "Петра — сестра Анни." },
        { de: "Die Meinung des Präsidenten", uk: "Думка президента", tag: "Gen. формально" },
      ],
      tip: "Текст / офіц. → Gen. Розмова → <i>von + Dativ</i>. Без артикля (Pl.) → von.",
      mistakes: [
        { wrong: "das Auto vom Direktor (in einem offiziellen Bericht)", right: "das Auto des Direktors" },
        { wrong: "Bilder Picassos", right: "Bilder von Picasso" },
      ],
      exercises: {}, prevSlug: "genitiv-namen",
    },
    extras: baseExtras(
      "Gen. — формально/письмово. <i>von+Dat.</i> — розмовно. Без артикля Pl. → von.",
      ["Українське «X-а Y» = і Gen., і von + Dat.", "У ділових документах — лише Gen."],
      ["Gen. для тексту/офіц.", "von+Dat. для розмови.", "Без артикля (Pl.) → von."],
    ),
    exercises15: [
      { type: "mc", q: "Найкраще для офіційного тексту:",
        options: ["das Auto vom Direktor","das Auto des Direktors","das Auto von Direktor","Direktor Auto"], correct: 1 },
      { type: "mc", q: "У розмові: машина директора:",
        options: ["das Auto des Direktors","das Auto vom Direktor","Direktors Auto","das Auto Direktor"], correct: 1 },
      { type: "gap", q: "Die Hilfe ___ Freunden ist wichtig.", answer: "von" },
      { type: "gap", q: "Tag ___ Arbeit (сталий вираз)", answer: "der" },
      { type: "tf", q: "У ділових документах допускається лише von+Dat.", correct: false },
      { type: "tf", q: "У множині без артикля краще von.", correct: true },
      { type: "match", prompt: "Контекст → перевага:", pairs: [
        { left: "офіційно", right: "Genitiv" }, { left: "розмовно", right: "von + Dativ" },
        { left: "Pl. без артикля", right: "von" }, { left: "власне ім'я", right: "Apostrof / von" },
      ]},
      { type: "correct", prompt: "Виправ (офіц. контекст):", wrong: "Die Meinung vom Präsidenten",
        correct: ["Die Meinung des Präsidenten"] },
      { type: "correct", prompt: "Виправ:", wrong: "Bilder Picassos", correct: ["Bilder von Picasso"] },
      { type: "multi", q: "Які варіанти прийнятні в розмові?",
        options: ["das Auto vom Direktor","das Auto des Direktors","Annas Buch","das Buch von Anna","Bilder Picassos"], correct: [0,1,2,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["das","Direktors","Auto","des","ist","neu"],
        correct: ["das","Auto","des","Direktors","ist","neu"] },
      { type: "translate", prompt: "Переклади формально:", uk: "Думка міністра.",
        de: ["Die Meinung des Ministers."] },
      { type: "translate", prompt: "Переклади розмовно:", uk: "Це машина мого брата.",
        de: ["Das ist das Auto von meinem Bruder.","Das ist das Auto meines Bruders."] },
      { type: "tf", q: "<i>Schmidts Haus</i> — типова для розмови форма.", correct: true },
      { type: "writeFree", prompt: "Напиши 2 речення: одне у Gen., одне з von+Dat.",
        sample: "Die Entscheidung des Vorstands wurde verkündet. Das ist das Fahrrad von meinem Freund." },
      { type: "mc", q: "<i>die Hilfe ___ Freunden</i> — що ставимо?", options: ["der","des","von","dem"], correct: 2 },
    ],
  },
};
