// B1 · Konjunktionen — 10 повних уроків.
import type { B1Map } from "./_helpers";
const CAT = "Сполучники";

const baseExtras = (rule: string, tips: string[], summary: string[]) => ({
  duration: 14, premium: true,
  ruleBox: { rule }, ukrainianTips: tips, summary,
});

export const konjunktionenB1: B1Map = {
  "hauptsatz-konjunktionen-b1": {
    lesson: {
      slug: "hauptsatz-konjunktionen-b1", level: "B1", category: CAT,
      titleDe: "Hauptsatz-Konjunktionen — und, aber, oder, denn, sondern",
      titleUk: "Сурядні сполучники und/aber/oder/denn/sondern",
      goal: "Поєднувати два головних речення сполучниками й розуміти різницю між <i>aber</i> і <i>sondern</i>.",
      explanation: [
        "<b>Сурядні сполучники</b> (Hauptsatz-Konjunktionen): <i>und, aber, oder, denn, sondern</i>. Вони з'єднують <b>два головних речення</b> й <b>не змінюють порядок слів</b> — дієслово після сполучника лишається на 2 позиції.",
        "<b>denn</b> = «бо, оскільки» — пояснює причину; підрядне не утворюється.",
        "<b>sondern</b> вживається <b>тільки після заперечення</b>: <i>nicht … sondern …</i> = «не …, а …». Після <i>aber</i> цього обмеження немає.",
        "Перед <i>und</i> та <i>oder</i> кома зазвичай не ставиться, перед <i>aber, denn, sondern</i> — ставиться.",
      ],
      table: {
        headers: ["Сполучник", "Функція", "Приклад"],
        rows: [
          ["und", "перерахування", "Ich lerne, und er arbeitet."],
          ["aber", "протиставлення", "Es regnet, aber ich gehe spazieren."],
          ["oder", "альтернатива", "Wir bleiben, oder wir gehen."],
          ["denn", "причина (= weil, але без зміни порядку)", "Ich bleibe, denn ich bin müde."],
          ["sondern", "після заперечення «а»", "Das ist nicht klein, sondern groß."],
        ],
      },
      examples: [
        { de: "Ich trinke Tee, und er trinkt Kaffee.", uk: "Я п'ю чай, а він каву." },
        { de: "Es ist kalt, aber sonnig.", uk: "Холодно, але сонячно." },
        { de: "Kommst du, oder bleibst du?", uk: "Ти прийдеш чи лишишся?" },
        { de: "Ich gehe ins Bett, denn ich bin müde.", uk: "Я йду спати, бо я втомився(лася)." },
        { de: "Das Buch ist nicht teuer, sondern billig.", uk: "Книга не дорога, а дешева." },
        { de: "Er spricht Deutsch und Englisch.", uk: "Він говорить німецькою й англійською." },
        { de: "Ich kann heute nicht, aber morgen ja.", uk: "Сьогодні не можу, але завтра — так." },
        { de: "Sie lernt nicht Französisch, sondern Spanisch.", uk: "Вона вчить не французьку, а іспанську." },
      ],
      tip: "Запам'ятай як «ADUSO»: <b>aber, denn, und, sondern, oder</b> — після них <b>порядок слів не змінюється</b>.",
      mistakes: [
        { wrong: "Ich bin müde, denn gehe ich ins Bett.", right: "Ich bin müde, denn ich gehe ins Bett." },
        { wrong: "Es ist nicht kalt, aber heiß.", right: "Es ist nicht kalt, sondern heiß." },
      ],
      exercises: {}, nextSlug: "weil-da",
    },
    extras: baseExtras(
      "<b>ADUSO</b>: aber, denn, und, sondern, oder. Дієслово залишається на 2 місці.",
      ["denn = weil + Hauptsatz-порядок.", "sondern — тільки після заперечення."],
      ["und/oder без коми; aber/denn/sondern — з комою.", "sondern після nicht/kein."],
    ),
    exercises15: [
      { type: "mc", q: "Ich bin müde, ___ ich gehe ins Bett.", options: ["weil","denn","aber","sondern"], correct: 1 },
      { type: "mc", q: "Das ist nicht klein, ___ groß.", options: ["aber","sondern","oder","denn"], correct: 1 },
      { type: "mc", q: "Kommst du, ___ bleibst du?", options: ["und","aber","oder","denn"], correct: 2 },
      { type: "gap", q: "Ich bin müde, ___ ich arbeite weiter.", answer: "aber" },
      { type: "gap", q: "Sie lernt nicht Italienisch, ___ Spanisch.", answer: "sondern" },
      { type: "gap", q: "Wir bleiben, ___ wir sind krank.", answer: "denn" },
      { type: "tf", q: "Після denn порядок слів змінюється на «дієслово в кінець».", correct: false },
      { type: "tf", q: "sondern вживається лише після nicht/kein.", correct: true },
      { type: "match", prompt: "Сполучник → функція:", pairs: [
        { left: "und", right: "перерахування" }, { left: "aber", right: "протиставлення" },
        { left: "oder", right: "альтернатива" }, { left: "denn", right: "причина" },
        { left: "sondern", right: "після заперечення" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich bin müde, denn gehe ich ins Bett.",
        correct: ["Ich bin müde, denn ich gehe ins Bett."] },
      { type: "correct", prompt: "Виправ:", wrong: "Es ist nicht kalt, aber heiß.",
        correct: ["Es ist nicht kalt, sondern heiß."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich lerne und er arbeitet.","Ich lerne, und arbeitet er.","Es regnet, aber wir gehen raus.","Sie ist nicht müde, aber wach."],
        correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["denn","ich","müde","bin","schlafe","ich"], correct: ["ich","schlafe","denn","ich","bin","müde"] },
      { type: "translate", prompt: "Переклади:", uk: "Це не велике, а маленьке.",
        de: ["Das ist nicht groß, sondern klein."] },
      { type: "translate", prompt: "Переклади з denn:", uk: "Я лишаюся вдома, бо хворий(а).",
        de: ["Ich bleibe zu Hause, denn ich bin krank."] },
      { type: "writeFree", prompt: "Напиши 3 речення з aber, denn, sondern.",
        sample: "Ich gehe heute nicht ins Kino, denn ich bin müde. Morgen will ich nicht arbeiten, sondern entspannen. Es regnet, aber ich nehme keinen Regenschirm." },
    ],
  },

  "weil-da": {
    lesson: {
      slug: "weil-da", level: "B1", category: CAT,
      titleDe: "weil / da — Nebensätze der Ursache",
      titleUk: "Підрядні причини: weil і da",
      goal: "Будувати підрядні причини зі сполучниками <i>weil</i> та <i>da</i> і знати різницю між ними.",
      explanation: [
        "Підрядні причини відповідають на питання <b>Warum?</b> і починаються зі сполучника <b>weil</b> або <b>da</b>. У підрядному реченні <b>дієслово стоїть у кінці</b>.",
        "<b>weil</b> — найчастіше; нова, важлива причина: <i>Ich bleibe zu Hause, weil ich krank bin.</i>",
        "<b>da</b> — причина, <b>відома</b> співрозмовнику; часто стоїть на <b>початку</b> речення: <i>Da es regnet, bleiben wir hier.</i>",
        "Якщо підрядне на початку, головне починається з дієслова (інверсія).",
      ],
      table: {
        headers: ["", "weil", "da"],
        rows: [
          ["частота", "дуже часто", "рідше, формально"],
          ["позиція", "після головного", "часто перед головним"],
          ["інформація", "нова причина", "відома, передумова"],
        ],
      },
      examples: [
        { de: "Ich bleibe zu Hause, weil ich krank bin.", uk: "Я залишаюся вдома, бо я хворий(а)." },
        { de: "Da es regnet, nehmen wir den Regenschirm.", uk: "Оскільки йде дощ, ми беремо парасолю." },
        { de: "Sie lernt Deutsch, weil sie in Berlin studieren möchte.", uk: "Вона вчить німецьку, бо хоче навчатися в Берліні." },
        { de: "Wir können nicht kommen, weil wir keine Zeit haben.", uk: "Ми не можемо прийти, бо не маємо часу." },
        { de: "Da du müde bist, geh ins Bett.", uk: "Раз ти втомлений, лягай спати." },
        { de: "Ich rufe an, weil ich eine Frage habe.", uk: "Я телефоную, бо маю запитання." },
        { de: "Er fährt mit dem Rad, weil das Auto kaputt ist.", uk: "Він їде велосипедом, бо машина зламана." },
        { de: "Da das Wetter schön war, machten wir einen Spaziergang.", uk: "Оскільки погода була гарною, ми вирушили на прогулянку." },
      ],
      tip: "Підрядне з weil/da — дієслово в <b>кінець</b>. Якщо підрядне попереду — у головному <b>інверсія</b>.",
      mistakes: [
        { wrong: "Ich bleibe zu Hause, weil ich bin krank.", right: "Ich bleibe zu Hause, weil ich krank bin." },
        { wrong: "Da es regnet, wir bleiben hier.", right: "Da es regnet, bleiben wir hier." },
      ],
      exercises: {}, prevSlug: "hauptsatz-konjunktionen-b1", nextSlug: "dass-ob",
    },
    extras: baseExtras(
      "<b>weil</b> / <b>da</b> — підрядне причини. Дієслово в кінець. <i>da</i> — для відомої причини, часто на початку.",
      ["Українське «бо/тому що» = weil; «оскільки» = da.", "Якщо підрядне попереду — головне починається з дієслова."],
      ["weil + дієслово в кінці.", "da частіше на початку.", "Інверсія в головному після підрядного."],
    ),
    exercises15: [
      { type: "mc", q: "Ich bleibe zu Hause, ___ ich krank bin.", options: ["denn","weil","aber","da"], correct: 1 },
      { type: "mc", q: "___ es regnet, bleiben wir drinnen.", options: ["Weil","Da","Denn","Und"], correct: 1 },
      { type: "gap", q: "Sie lernt Deutsch, weil sie in Wien arbeiten ___. (möchten)", answer: "möchte" },
      { type: "gap", q: "Wir kommen nicht, weil wir keine Zeit ___. (haben)", answer: "haben" },
      { type: "tf", q: "У підрядному з weil дієслово стоїть на 2 місці.", correct: false },
      { type: "tf", q: "Після підрядного на початку — інверсія в головному.", correct: true },
      { type: "match", prompt: "Сполучник → характеристика:", pairs: [
        { left: "weil", right: "нова причина" }, { left: "da", right: "відома причина" },
        { left: "denn", right: "Hauptsatz, без інверсії" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich bleibe zu Hause, weil ich bin krank.",
        correct: ["Ich bleibe zu Hause, weil ich krank bin."] },
      { type: "correct", prompt: "Виправ:", wrong: "Da es regnet, wir bleiben drinnen.",
        correct: ["Da es regnet, bleiben wir drinnen."] },
      { type: "multi", q: "Виділи правильні речення:", options: [
        "Ich lerne, weil ich Prüfung habe.","Ich lerne, weil ich habe Prüfung.","Da er müde ist, schläft er.","Da er müde ist, er schläft."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["weil","bin","ich","müde","schlafe","ich"], correct: ["ich","schlafe","weil","ich","müde","bin"] },
      { type: "order", prompt: "Склади речення (підрядне на початку):",
        words: ["regnet","es","wir","bleiben","da","zu","Hause"], correct: ["da","es","regnet","bleiben","wir","zu","Hause"] },
      { type: "translate", prompt: "Переклади з weil:", uk: "Я не можу прийти, бо я працюю.",
        de: ["Ich kann nicht kommen, weil ich arbeite."] },
      { type: "translate", prompt: "Переклади з da:", uk: "Оскільки ти втомлений, лягай спати.",
        de: ["Da du müde bist, geh ins Bett.","Da du müde bist, schlaf!"] },
      { type: "writeFree", prompt: "Напиши 3 речення з weil/da про сьогодні.",
        sample: "Heute bleibe ich zu Hause, weil ich krank bin. Da das Wetter schlecht ist, treffe ich meine Freunde online. Ich trinke viel Tee, weil das gut für den Hals ist." },
      { type: "mc", q: "Wo steht das Verb im Nebensatz mit weil?",
        options: ["Position 1","Position 2","am Ende","irgendwo"], correct: 2 },
    ],
  },

  "dass-ob": {
    lesson: {
      slug: "dass-ob", level: "B1", category: CAT,
      titleDe: "dass / ob — Ergänzungssätze",
      titleUk: "Підрядні з'ясувальні: dass і ob",
      goal: "Будувати з'ясувальні підрядні з <i>dass</i> (факт) і <i>ob</i> (питання так/ні).",
      explanation: [
        "Сполучник <b>dass</b> вводить підрядне-факт: <i>Ich weiß, dass er kommt.</i>",
        "Сполучник <b>ob</b> вводить непряме <b>Ja/Nein-питання</b>: <i>Ich weiß nicht, ob er kommt.</i>",
        "У підрядному <b>дієслово в кінці</b>.",
        "Після виразів <i>denken, wissen, glauben, hoffen, sagen, fragen, sich freuen + dass/ob</i>.",
      ],
      examples: [
        { de: "Ich weiß, dass er heute kommt.", uk: "Я знаю, що він сьогодні прийде." },
        { de: "Ich weiß nicht, ob er heute kommt.", uk: "Я не знаю, чи він сьогодні прийде." },
        { de: "Sie sagt, dass sie müde ist.", uk: "Вона каже, що (вона) втомлена." },
        { de: "Frag, ob noch Plätze frei sind.", uk: "Запитай, чи є ще вільні місця." },
        { de: "Ich hoffe, dass du gesund wirst.", uk: "Я сподіваюся, що ти видужаєш." },
        { de: "Wir freuen uns, dass ihr da seid.", uk: "Ми раді, що ви тут." },
        { de: "Es ist wichtig, dass du pünktlich bist.", uk: "Важливо, щоб ти був(ла) вчасно." },
        { de: "Ich weiß nicht, ob das stimmt.", uk: "Не знаю, чи це правда." },
      ],
      tip: "<b>dass</b> = «що» (факт). <b>ob</b> = «чи» (Ja/Nein).",
      mistakes: [
        { wrong: "Ich weiß, dass er kommt heute.", right: "Ich weiß, dass er heute kommt." },
        { wrong: "Ich weiß nicht, dass er kommt (Ja oder Nein).", right: "Ich weiß nicht, ob er kommt." },
      ],
      exercises: {}, prevSlug: "weil-da", nextSlug: "wenn-als-b1",
    },
    extras: baseExtras(
      "<b>dass</b> = факт; <b>ob</b> = непряме Ja/Nein-питання. Дієслово в кінці.",
      ["Українське «що» = dass; «чи» = ob.", "Після <i>fragen</i> майже завжди ob."],
      ["dass = факт.", "ob = непряме Ja/Nein.", "Дієслово в кінець."],
    ),
    exercises15: [
      { type: "mc", q: "Ich weiß, ___ er heute kommt.", options: ["ob","dass","weil","wenn"], correct: 1 },
      { type: "mc", q: "Ich weiß nicht, ___ er heute kommt.", options: ["ob","dass","weil","als"], correct: 0 },
      { type: "gap", q: "Frag ihn, ___ er Zeit hat.", answer: "ob" },
      { type: "gap", q: "Ich hoffe, ___ alles gut wird.", answer: "dass" },
      { type: "gap", q: "Sie sagt, dass sie krank ___. (sein)", answer: "ist" },
      { type: "tf", q: "<i>ob</i> вживається для з'ясувального з відомою відповіддю.", correct: false },
      { type: "tf", q: "У підрядному з dass дієслово в кінці.", correct: true },
      { type: "match", prompt: "Сполучник → значення:", pairs: [
        { left: "dass", right: "що (факт)" }, { left: "ob", right: "чи (питання)" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich weiß, dass er kommt heute.",
        correct: ["Ich weiß, dass er heute kommt."] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich frage, dass du kommst.",
        correct: ["Ich frage, ob du kommst."] },
      { type: "multi", q: "Які речення з ob?", options: [
        "Ich weiß nicht, ob es regnet.","Ich weiß, ob es regnet.","Frag, ob er kommt.","Sag, ob du Zeit hast.","Ich glaube, ob er kommt."], correct: [0,2,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["dass","weiß","kommt","ich","er","heute"], correct: ["ich","weiß","dass","er","heute","kommt"] },
      { type: "translate", prompt: "Переклади:", uk: "Я не знаю, чи він прийде.",
        de: ["Ich weiß nicht, ob er kommt."] },
      { type: "translate", prompt: "Переклади:", uk: "Я сподіваюся, що ти видужаєш.",
        de: ["Ich hoffe, dass du gesund wirst.","Ich hoffe, dass du wieder gesund wirst."] },
      { type: "writeFree", prompt: "Напиши 2 речення з dass і 1 з ob.",
        sample: "Ich glaube, dass das Wetter morgen besser wird. Es ist schön, dass du gekommen bist. Ich weiß nicht, ob der Bus pünktlich kommt." },
      { type: "mc", q: "Sie fragt, ___ ich Zeit habe.", options: ["dass","ob","weil","wenn"], correct: 1 },
    ],
  },

  "wenn-als-b1": {
    lesson: {
      slug: "wenn-als-b1", level: "B1", category: CAT,
      titleDe: "wenn / als — Temporalsätze",
      titleUk: "Часові підрядні: wenn / als",
      goal: "Розрізняти <i>wenn</i> і <i>als</i> у часових підрядних і коректно вживати в різних часах.",
      explanation: [
        "<b>als</b> — для <b>одноразової дії в минулому</b>: <i>Als ich klein war, …</i>",
        "<b>wenn</b> — для <b>теперішнього, майбутнього</b> та <b>повторюваних</b> дій у минулому: <i>Immer wenn ich kam, …</i>",
        "У питанні «коли?» (питальне слово) — <b>wann</b>: <i>Wann kommst du?</i>",
        "У підрядному дієслово — в кінці.",
      ],
      table: {
        headers: ["Час", "Один раз", "Часто/повторно"],
        rows: [
          ["минуле", "als", "wenn (+ immer)"],
          ["теп./майб.", "wenn", "wenn"],
        ],
      },
      examples: [
        { de: "Als ich Kind war, wohnte ich in Lwiw.", uk: "Коли я був(ла) дитиною, я жив(ла) у Львові." },
        { de: "Wenn ich Zeit habe, lese ich Bücher.", uk: "Коли я маю час, я читаю книги." },
        { de: "Immer wenn er kam, brachte er Blumen.", uk: "Щоразу, коли він приходив, приносив квіти." },
        { de: "Als die Sonne aufging, fuhren wir los.", uk: "Коли зійшло сонце, ми вирушили." },
        { de: "Wenn du fragst, helfe ich gern.", uk: "Якщо ти запитаєш, я з радістю допоможу." },
        { de: "Wann kommst du nach Hause?", uk: "Коли ти прийдеш додому?" },
        { de: "Als ich gestern aufwachte, war es schon spät.", uk: "Коли я вчора прокинувся, було вже пізно." },
        { de: "Ruf mich an, wenn du Zeit hast.", uk: "Подзвони мені, коли матимеш час." },
      ],
      tip: "Минуле, одноразова дія → <b>als</b>. Усе інше → <b>wenn</b>. Питання — <b>wann</b>.",
      mistakes: [
        { wrong: "Wenn ich Kind war, …", right: "Als ich Kind war, …" },
        { wrong: "Wann ich Zeit habe, …", right: "Wenn ich Zeit habe, …" },
      ],
      exercises: {}, prevSlug: "dass-ob", nextSlug: "nachdem-bevor-waehrend",
    },
    extras: baseExtras(
      "Минуле один раз → <b>als</b>. Повтор/теп./майб. → <b>wenn</b>. Питання → <b>wann</b>.",
      ["В укр. «коли» = і wenn, і als, і wann — у нім. розділяємо."],
      ["als — однократне минуле.", "wenn — повтор/тепер/майбутнє.", "wann — питання."],
    ),
    exercises15: [
      { type: "mc", q: "___ ich Kind war, wohnte ich am Meer.", options: ["Wenn","Als","Wann","Während"], correct: 1 },
      { type: "mc", q: "___ ich Zeit habe, gehe ich joggen.", options: ["Wenn","Als","Wann","Da"], correct: 0 },
      { type: "mc", q: "___ kommst du nach Hause?", options: ["Als","Wenn","Wann","Da"], correct: 2 },
      { type: "gap", q: "Immer ___ er kam, brachte er Blumen.", answer: "wenn" },
      { type: "gap", q: "___ ich gestern aufwachte, regnete es.", answer: "Als" },
      { type: "tf", q: "Для повторюваних дій у минулому використовуємо als.", correct: false },
      { type: "tf", q: "wann — питальне слово, не сполучник підрядного часу.", correct: true },
      { type: "match", prompt: "Контекст → сполучник:", pairs: [
        { left: "одноразово в минулому", right: "als" },
        { left: "повторно або тепер", right: "wenn" },
        { left: "пряме питання", right: "wann" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Wenn ich Kind war, lebte ich in Kiew.",
        correct: ["Als ich Kind war, lebte ich in Kiew."] },
      { type: "correct", prompt: "Виправ:", wrong: "Wann ich Zeit habe, helfe ich.",
        correct: ["Wenn ich Zeit habe, helfe ich."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Als ich klein war, …","Wenn ich klein war, …","Wenn ich morgen Zeit habe, …","Wann hast du Zeit?"], correct: [0,2,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["als","klein","ich","war","wohnte","Lwiw","ich","in"],
        correct: ["als","ich","klein","war","wohnte","ich","in","Lwiw"] },
      { type: "translate", prompt: "Переклади:", uk: "Коли я був(ла) дитиною, ми мали собаку.",
        de: ["Als ich Kind war, hatten wir einen Hund."] },
      { type: "translate", prompt: "Переклади:", uk: "Коли матимеш час, подзвони мені.",
        de: ["Wenn du Zeit hast, ruf mich an.","Ruf mich an, wenn du Zeit hast."] },
      { type: "writeFree", prompt: "Напиши 2 речення з als і 1 з wenn (майбутнє).",
        sample: "Als ich 10 war, lernte ich schwimmen. Als wir nach Berlin zogen, war ich aufgeregt. Wenn ich nächsten Monat Urlaub habe, fliege ich nach Wien." },
      { type: "mc", q: "Was bedeutet 'wann'?", options: ["якщо","коли (питання)","оскільки","поки"], correct: 1 },
    ],
  },

  "nachdem-bevor-waehrend": {
    lesson: {
      slug: "nachdem-bevor-waehrend", level: "B1", category: CAT,
      titleDe: "nachdem, bevor, während — Zeitfolge",
      titleUk: "Часова послідовність: nachdem / bevor / während",
      goal: "Виражати часові відношення між подіями: «після того як», «перед тим як», «під час».",
      explanation: [
        "<b>nachdem</b> = «після того як» — підрядне у <b>попередньому часі</b>: якщо головне Präteritum → підрядне Plusquamperfekt; якщо головне Präsens/Perfekt → підрядне Perfekt.",
        "<b>bevor</b> = «перед тим як». Обидва речення у тому самому часі: <i>Bevor ich gehe, esse ich.</i>",
        "<b>während</b> = «поки, під час того як» — одночасні дії: <i>Während ich kochte, las er.</i>",
        "У підрядному дієслово — в кінці. При підрядному на початку — інверсія в головному.",
      ],
      table: {
        headers: ["Сполучник", "Часова логіка", "Приклад"],
        rows: [
          ["nachdem", "підрядне → раніше", "Nachdem ich gegessen hatte, ging ich los."],
          ["bevor", "підрядне → пізніше", "Bevor ich gehe, esse ich."],
          ["während", "одночасно", "Während ich kochte, telefonierte er."],
        ],
      },
      examples: [
        { de: "Nachdem ich gegessen hatte, ging ich spazieren.", uk: "Після того, як я поїв(ла), я пішов(ла) гуляти." },
        { de: "Bevor du gehst, mach das Licht aus.", uk: "Перед тим, як піти, вимкни світло." },
        { de: "Während er arbeitete, hörte er Musik.", uk: "Поки він працював, він слухав музику." },
        { de: "Nachdem die Kinder ins Bett gegangen waren, las ich.", uk: "Після того, як діти лягли спати, я читав(ла)." },
        { de: "Bevor wir essen, waschen wir die Hände.", uk: "Перед їжею ми миємо руки." },
        { de: "Während ich studierte, jobbte ich in einem Café.", uk: "Поки я навчав(ла)ся, я підробляв(ла) у кафе." },
        { de: "Nachdem er angekommen ist, ruft er an.", uk: "Після того, як він приїде, він зателефонує." },
        { de: "Bevor du anrufst, lies bitte die E-Mail.", uk: "Перед тим, як телефонувати, прочитай, будь ласка, лист." },
      ],
      tip: "<b>nachdem</b> = підрядне раніше → <b>Plusquamperfekt/Perfekt</b>. <b>bevor/während</b> = той самий час.",
      mistakes: [
        { wrong: "Nachdem ich aß, ging ich los.", right: "Nachdem ich gegessen hatte, ging ich los." },
        { wrong: "Bevor ich werde gehen, esse ich.", right: "Bevor ich gehe, esse ich." },
      ],
      exercises: {}, prevSlug: "wenn-als-b1", nextSlug: "obwohl-trotzdem",
    },
    extras: baseExtras(
      "<b>nachdem</b> — підрядне в попередньому часі. <b>bevor</b>/<b>während</b> — той самий час.",
      ["Українське «після того як» = nachdem; «перед тим як» = bevor; «поки» = während."],
      ["nachdem: Plusquamperfekt/Perfekt.", "bevor: однаковий час.", "während: одночасні дії."],
    ),
    exercises15: [
      { type: "mc", q: "___ ich gegessen hatte, ging ich los.", options: ["Bevor","Nachdem","Während","Als"], correct: 1 },
      { type: "mc", q: "___ du gehst, mach das Licht aus.", options: ["Bevor","Nachdem","Während","Da"], correct: 0 },
      { type: "mc", q: "___ ich kochte, hörte ich Musik.", options: ["Bevor","Nachdem","Während","Wenn"], correct: 2 },
      { type: "gap", q: "Nachdem die Kinder ins Bett ___ waren, las ich. (gehen)", answer: "gegangen" },
      { type: "gap", q: "Bevor ich ___, esse ich Frühstück.", answer: "gehe" },
      { type: "tf", q: "Після nachdem часто Plusquamperfekt.", correct: true },
      { type: "tf", q: "Bevor вимагає різного часу в реченнях.", correct: false },
      { type: "match", prompt: "Сполучник → значення:", pairs: [
        { left: "nachdem", right: "після того як" }, { left: "bevor", right: "перед тим як" },
        { left: "während", right: "поки" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Nachdem ich aß, ging ich los.",
        correct: ["Nachdem ich gegessen hatte, ging ich los."] },
      { type: "correct", prompt: "Виправ:", wrong: "Bevor ich werde gehen, esse ich.",
        correct: ["Bevor ich gehe, esse ich."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Nachdem er kam, gingen wir.","Nachdem er gekommen war, gingen wir.",
        "Bevor du isst, wasch die Hände.","Während ich schlief, las er."], correct: [1,2,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["nachdem","gegessen","ich","hatte","ging","spazieren","ich"],
        correct: ["nachdem","ich","gegessen","hatte","ging","ich","spazieren"] },
      { type: "translate", prompt: "Переклади:", uk: "Поки я готувала, він читав.",
        de: ["Während ich kochte, las er.","Während ich gekocht habe, hat er gelesen."] },
      { type: "translate", prompt: "Переклади:", uk: "Перед тим, як вийти, перевір документи.",
        de: ["Bevor du gehst, prüfe die Dokumente.","Bevor du losgehst, prüf die Dokumente."] },
      { type: "writeFree", prompt: "Напиши 3 речення з nachdem/bevor/während.",
        sample: "Nachdem ich gefrühstückt hatte, fuhr ich ins Büro. Bevor ich nach Hause ging, kaufte ich noch Brot. Während ich aß, sah ich die Nachrichten." },
      { type: "mc", q: "Was ist gleichzeitig?", options: ["nachdem","bevor","während","weil"], correct: 2 },
    ],
  },

  "obwohl-trotzdem": {
    lesson: {
      slug: "obwohl-trotzdem", level: "B1", category: CAT,
      titleDe: "obwohl / trotzdem — Konzessivsätze",
      titleUk: "Допустовість: obwohl / trotzdem",
      goal: "Виражати протиріччя очікуванням за допомогою <i>obwohl</i> (підрядне) і <i>trotzdem</i> (головне).",
      explanation: [
        "<b>obwohl</b> = «хоча» — вводить підрядне; дієслово в кінці: <i>Obwohl es regnet, gehe ich raus.</i>",
        "<b>trotzdem</b> = «попри це» — прислівник, що стоїть у головному реченні. Дієслово зразу після нього (інверсія): <i>Es regnet. Trotzdem gehe ich raus.</i>",
        "Синонім obwohl — <b>obgleich, obschon</b> (формально). <b>Trotz + Gen.</b> — прийменник з тим самим значенням.",
      ],
      examples: [
        { de: "Obwohl es regnet, gehe ich spazieren.", uk: "Хоча йде дощ, я іду гуляти." },
        { de: "Es ist kalt. Trotzdem trage ich kein Jacke.", uk: "Холодно. Попри це я не вдягаю куртку." },
        { de: "Obwohl er müde war, arbeitete er weiter.", uk: "Хоча він був втомленим, продовжував працювати." },
        { de: "Sie hat keine Zeit. Trotzdem hilft sie mir.", uk: "Вона не має часу. Попри це вона мені допомагає." },
        { de: "Obwohl wir verloren haben, sind wir stolz.", uk: "Хоча ми програли, ми пишаємося." },
        { de: "Er ist krank. Trotzdem geht er zur Arbeit.", uk: "Він хворий. Попри це йде на роботу." },
        { de: "Obwohl ich Hunger habe, esse ich nichts.", uk: "Хоча я голодний, нічого не їм." },
        { de: "Es war teuer. Trotzdem habe ich es gekauft.", uk: "Це було дорого. Попри це я це купив(ла)." },
      ],
      tip: "<b>obwohl</b> + Nebensatz (дієслово в кінець). <b>trotzdem</b> + Hauptsatz (інверсія).",
      mistakes: [
        { wrong: "Obwohl es regnet, ich gehe raus.", right: "Obwohl es regnet, gehe ich raus." },
        { wrong: "Trotzdem ich bin müde, arbeite ich.", right: "Trotzdem arbeite ich. (або: Obwohl ich müde bin, arbeite ich.)" },
      ],
      exercises: {}, prevSlug: "nachdem-bevor-waehrend", nextSlug: "damit-um-zu",
    },
    extras: baseExtras(
      "<b>obwohl</b> — підрядне (дієсл. в кінець). <b>trotzdem</b> — у головному (інверсія).",
      ["Українське «хоча» = obwohl; «попри це» = trotzdem.", "Обидва — про протиріччя очікуванням."],
      ["obwohl + Nebensatz.", "trotzdem + Hauptsatz (інверсія).", "trotz + Gen. — прийменник."],
    ),
    exercises15: [
      { type: "mc", q: "___ es regnet, gehe ich raus.", options: ["Trotzdem","Obwohl","Weil","Wenn"], correct: 1 },
      { type: "mc", q: "Es ist kalt. ___ trage ich keine Jacke.", options: ["Obwohl","Trotzdem","Aber","Weil"], correct: 1 },
      { type: "gap", q: "Obwohl er müde ___, arbeitet er. (sein)", answer: "ist" },
      { type: "gap", q: "Es war teuer. ___ habe ich es gekauft.", answer: "Trotzdem" },
      { type: "tf", q: "Після obwohl дієслово на 2 місці.", correct: false },
      { type: "tf", q: "trotzdem викликає інверсію у головному реченні.", correct: true },
      { type: "match", prompt: "Сполучник/слово → позиція:", pairs: [
        { left: "obwohl", right: "Nebensatz" }, { left: "trotzdem", right: "Hauptsatz" },
        { left: "trotz", right: "Präposition + Genitiv" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Obwohl es regnet, ich gehe raus.",
        correct: ["Obwohl es regnet, gehe ich raus."] },
      { type: "correct", prompt: "Виправ:", wrong: "Trotzdem ich müde bin, arbeite ich.",
        correct: ["Obwohl ich müde bin, arbeite ich.","Ich bin müde. Trotzdem arbeite ich."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Obwohl er krank ist, arbeitet er.","Obwohl er krank ist, er arbeitet.",
        "Es regnet. Trotzdem gehe ich raus.","Es regnet. Trotzdem ich gehe raus."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["obwohl","müde","ich","bin","weiter","arbeite","ich"],
        correct: ["obwohl","ich","müde","bin","arbeite","ich","weiter"] },
      { type: "translate", prompt: "Переклади:", uk: "Хоча йде дощ, я йду гуляти.",
        de: ["Obwohl es regnet, gehe ich spazieren."] },
      { type: "translate", prompt: "Переклади:", uk: "Він хворий. Попри це йде на роботу.",
        de: ["Er ist krank. Trotzdem geht er zur Arbeit."] },
      { type: "writeFree", prompt: "Напиши 2 речення з obwohl/trotzdem.",
        sample: "Obwohl ich heute keine Lust hatte, bin ich zum Sport gegangen. Es war anstrengend. Trotzdem fühle ich mich jetzt gut." },
      { type: "mc", q: "Was ist <i>trotz</i>?", options: ["Konjunktion","Adverb","Präposition","Verb"], correct: 2 },
    ],
  },

  "damit-um-zu": {
    lesson: {
      slug: "damit-um-zu", level: "B1", category: CAT,
      titleDe: "damit / um … zu — Finalsätze",
      titleUk: "Підрядні мети: damit / um … zu",
      goal: "Розрізняти й правильно вживати <i>damit</i> і <i>um … zu</i> для виразу мети.",
      explanation: [
        "<b>um … zu + Infinitiv</b> — якщо підмет головного й мети <b>той самий</b>: <i>Ich lerne, um zu reisen.</i>",
        "<b>damit</b> + Nebensatz — якщо підмети <b>різні</b>: <i>Ich erkläre es, damit du es verstehst.</i>",
        "У підрядному з damit дієслово — в кінці.",
        "Замість Modalverb <i>können/sollen</i> у damit-реченні — часто Konjunktiv не потрібен, тільки Indikativ.",
      ],
      examples: [
        { de: "Ich lerne Deutsch, um in Berlin zu studieren.", uk: "Я вчу німецьку, щоб навчатися в Берліні." },
        { de: "Ich erkläre es, damit du es verstehst.", uk: "Я пояснюю, щоб ти зрозумів(ла)." },
        { de: "Wir sparen Geld, um ein Haus zu kaufen.", uk: "Ми збираємо гроші, щоб купити будинок." },
        { de: "Eltern arbeiten, damit ihre Kinder ein gutes Leben haben.", uk: "Батьки працюють, щоб у їхніх дітей було добре життя." },
        { de: "Er trainiert, um fit zu bleiben.", uk: "Він тренується, щоб бути у формі." },
        { de: "Ich helfe dir, damit du Zeit hast.", uk: "Я допомагаю тобі, щоб ти мав(ла) час." },
        { de: "Sie spricht laut, damit alle es hören.", uk: "Вона говорить голосно, щоб усі чули." },
        { de: "Wozu lernst du? — Um Karriere zu machen.", uk: "Навіщо ти вчишся? — Щоб робити кар'єру." },
      ],
      tip: "Той самий підмет → <b>um…zu</b>. Різні → <b>damit</b>.",
      mistakes: [
        { wrong: "Ich lerne Deutsch, um ich kann reisen.", right: "Ich lerne Deutsch, um reisen zu können." },
        { wrong: "Ich helfe dir, damit du hast Zeit.", right: "Ich helfe dir, damit du Zeit hast." },
      ],
      exercises: {}, prevSlug: "obwohl-trotzdem", nextSlug: "sodass",
    },
    extras: baseExtras(
      "<b>um … zu</b> — той самий підмет. <b>damit</b> — різні підмети; дієслово в кінець.",
      ["Українське «щоб» = um…zu / damit залежно від підмета."],
      ["um…zu — однакові підмети.", "damit — різні.", "Дієслово в кінець у damit-Nebensatz."],
    ),
    exercises15: [
      { type: "mc", q: "Ich lerne, ___ in Wien zu arbeiten.", options: ["damit","um","weil","ohne"], correct: 1 },
      { type: "mc", q: "Ich helfe dir, ___ du Zeit hast.", options: ["damit","um","weil","wenn"], correct: 0 },
      { type: "gap", q: "Wir sparen, ___ ein Haus ___ kaufen.", answer: "um zu" },
      { type: "gap", q: "Sie spricht laut, ___ alle es hören.", answer: "damit" },
      { type: "gap", q: "Ich erkläre es, damit du es ___. (verstehen)", answer: "verstehst" },
      { type: "tf", q: "Якщо підмети однакові, обов'язково um…zu.", correct: true },
      { type: "tf", q: "Після damit дієслово на 2 місці.", correct: false },
      { type: "match", prompt: "Підмети → конструкція:", pairs: [
        { left: "однакові", right: "um … zu" }, { left: "різні", right: "damit" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich lerne, um ich Karriere mache.",
        correct: ["Ich lerne, um Karriere zu machen."] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich helfe dir, damit du hast Zeit.",
        correct: ["Ich helfe dir, damit du Zeit hast."] },
      { type: "multi", q: "Виділи правильні речення:", options: [
        "Er spart, um ein Auto zu kaufen.","Er spart, damit er ein Auto zu kaufen.",
        "Ich spreche langsam, damit du verstehst.","Ich spreche langsam, um du verstehst."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["damit","verstehst","du","ich","erkläre","es","es"],
        correct: ["ich","erkläre","es","damit","du","es","verstehst"] },
      { type: "translate", prompt: "Переклади (той самий підмет):", uk: "Я тренуюся, щоб бути у формі.",
        de: ["Ich trainiere, um fit zu bleiben."] },
      { type: "translate", prompt: "Переклади (різні підмети):", uk: "Я пишу повільно, щоб ти все зрозумів(ла).",
        de: ["Ich schreibe langsam, damit du alles verstehst."] },
      { type: "writeFree", prompt: "Напиши 1 речення з um…zu і 1 з damit.",
        sample: "Ich lerne jeden Tag, um die Prüfung zu bestehen. Meine Mutter erklärt mir alles geduldig, damit ich keine Angst vor dem Test habe." },
      { type: "mc", q: "Wozu nutzt man <i>damit</i>?",
        options: ["для протиставлення","для мети з різними підметами","для причини","для часу"], correct: 1 },
    ],
  },

  sodass: {
    lesson: {
      slug: "sodass", level: "B1", category: CAT,
      titleDe: "sodass — Konsekutivsätze",
      titleUk: "Підрядні наслідку: sodass / so … dass",
      goal: "Виражати наслідок за допомогою <i>sodass</i> та конструкції <i>so + Adj. + dass</i>.",
      explanation: [
        "<b>sodass</b> (часто пишеться <i>so dass</i>) = «так що» — вводить наслідок попереднього речення: <i>Es regnet stark, sodass wir nicht gehen.</i>",
        "Альтернатива: <b>so + Adj./Adv. + dass</b>: <i>Es war so kalt, dass wir froren.</i>",
        "У підрядному дієслово — в кінці.",
        "<i>sodass</i> описує <b>фактичний</b> наслідок (без оцінки); порівняй з <i>damit</i> (мета).",
      ],
      examples: [
        { de: "Es regnete stark, sodass wir zu Hause blieben.", uk: "Сильно йшов дощ, так що ми лишилися вдома." },
        { de: "Er sprach leise, sodass ich nichts verstand.", uk: "Він говорив тихо, так що я нічого не зрозумів(ла)." },
        { de: "Es war so kalt, dass die Seen zufroren.", uk: "Було так холодно, що озера замерзли." },
        { de: "Sie ist so müde, dass sie schläft.", uk: "Вона така втомлена, що засинає." },
        { de: "Der Zug hatte Verspätung, sodass wir den Anschluss verpassten.", uk: "Поїзд затримався, так що ми не встигли на пересадку." },
        { de: "Das Wetter war so schön, dass wir am See picknickten.", uk: "Погода була такою чудовою, що ми влаштували пікнік біля озера." },
        { de: "Er erklärte alles langsam, sodass wir folgen konnten.", uk: "Він усе пояснював повільно, так що ми могли стежити." },
        { de: "Es war so laut, dass man kaum reden konnte.", uk: "Було так гучно, що ледь можна було говорити." },
      ],
      tip: "<b>sodass</b> = «так що» (наслідок). Не плутай з <b>damit</b> = «щоб» (мета).",
      mistakes: [
        { wrong: "Es war kalt, damit wir froren.", right: "Es war so kalt, dass wir froren." },
        { wrong: "Er sprach leise, sodass ich verstand nichts.", right: "Er sprach leise, sodass ich nichts verstand." },
      ],
      exercises: {}, prevSlug: "damit-um-zu", nextSlug: "je-desto",
    },
    extras: baseExtras(
      "<b>sodass</b> / <b>so … dass</b> = наслідок. Не плутай з мети (damit).",
      ["Українське «так що» = sodass; «такий, що» = so … dass."],
      ["sodass = фактичний наслідок.", "so + Adj. + dass — інтенсивність.", "Дієслово в кінці."],
    ),
    exercises15: [
      { type: "mc", q: "Es regnete stark, ___ wir blieben.", options: ["damit","sodass","weil","obwohl"], correct: 1 },
      { type: "mc", q: "Es war ___ kalt, dass die Seen zufroren.", options: ["sehr","so","viel","ganz"], correct: 1 },
      { type: "gap", q: "Er sprach leise, sodass ich nichts ___. (verstehen, Prät.)", answer: "verstand" },
      { type: "gap", q: "Sie ist so müde, ___ sie schläft.", answer: "dass" },
      { type: "tf", q: "sodass виражає мету.", correct: false },
      { type: "tf", q: "<i>so + Adj. + dass</i> — варіант наслідкового речення.", correct: true },
      { type: "match", prompt: "Сполучник → значення:", pairs: [
        { left: "sodass", right: "наслідок" }, { left: "damit", right: "мета" },
        { left: "weil", right: "причина" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Es war kalt, damit wir froren.",
        correct: ["Es war so kalt, dass wir froren.","Es war kalt, sodass wir froren."] },
      { type: "correct", prompt: "Виправ:", wrong: "Er sprach leise, sodass ich verstand nichts.",
        correct: ["Er sprach leise, sodass ich nichts verstand."] },
      { type: "multi", q: "Які речення з sodass?", options: [
        "Es war kalt, sodass wir froren.","Es war kalt, damit wir froren.",
        "Sie ist müde, sodass sie schläft.","Sie schläft, damit sie müde ist."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["sodass","wir","blieben","Hause","zu","es","stark","regnete"],
        correct: ["es","regnete","stark","sodass","wir","zu","Hause","blieben"] },
      { type: "translate", prompt: "Переклади:", uk: "Було так пізно, що всі вже спали.",
        de: ["Es war so spät, dass alle schon schliefen.","Es war so spät, dass alle schon geschlafen haben."] },
      { type: "translate", prompt: "Переклади:", uk: "Він говорив тихо, так що я нічого не зрозумів(ла).",
        de: ["Er sprach leise, sodass ich nichts verstand.","Er sprach so leise, dass ich nichts verstand."] },
      { type: "writeFree", prompt: "Напиши 2 речення з sodass / so…dass.",
        sample: "Der Film war so spannend, dass wir bis spät in die Nacht zuschauten. Es schneite stark, sodass alle Züge Verspätung hatten." },
      { type: "mc", q: "sodass = ?", options: ["щоб","так що","хоча","коли"], correct: 1 },
    ],
  },

  "je-desto": {
    lesson: {
      slug: "je-desto", level: "B1", category: CAT,
      titleDe: "je … desto / je … umso",
      titleUk: "Пропорційність: je … desto",
      goal: "Будувати конструкції пропорційного зростання типу «чим …, тим …».",
      explanation: [
        "<b>je + Komparativ … , desto/umso + Komparativ …</b> виражає взаємну залежність двох величин.",
        "Перша частина — <b>підрядне</b>: дієслово <b>в кінці</b>. Друга — <b>головне</b>: дієслово <b>після desto/umso</b> (Position 2 у новій частині).",
        "<i>desto</i> і <i>umso</i> — синоніми.",
      ],
      examples: [
        { de: "Je mehr du übst, desto besser wirst du.", uk: "Чим більше ти вправляєшся, тим краще ти стаєш." },
        { de: "Je älter er wird, umso ruhiger wird er.", uk: "Чим старшим він стає, тим спокійнішим стає." },
        { de: "Je früher wir losfahren, desto schneller sind wir da.", uk: "Чим раніше виїдемо, тим швидше будемо там." },
        { de: "Je weniger Zucker, desto besser für die Gesundheit.", uk: "Чим менше цукру, тим краще для здоров'я." },
        { de: "Je länger ich lerne, umso mehr verstehe ich.", uk: "Чим довше я вчу, тим більше розумію." },
        { de: "Je teurer das Hotel, desto besser der Service.", uk: "Чим дорожче готель, тим кращий сервіс." },
        { de: "Je kälter es ist, desto wärmer ziehe ich mich an.", uk: "Чим холодніше, тим тепліше я одягаюся." },
        { de: "Je müder ich bin, umso schneller schlafe ich ein.", uk: "Чим я втомленіший, тим швидше засинаю." },
      ],
      tip: "<b>Je</b> + Komparativ … , <b>desto</b> + Komparativ + дієслово (2 поз. у головному).",
      mistakes: [
        { wrong: "Je mehr du übst, desto du wirst besser.", right: "Je mehr du übst, desto besser wirst du." },
        { wrong: "Je viel du lernst, desto viel du weißt.", right: "Je mehr du lernst, desto mehr weißt du." },
      ],
      exercises: {}, prevSlug: "sodass", nextSlug: "zweiteilige-konjunktionen",
    },
    extras: baseExtras(
      "<b>Je + Komparativ + … (Verb am Ende), desto/umso + Komparativ + Verb …</b>",
      ["Українське «чим …, тим …» = je … desto.", "Завжди — Komparativ!"],
      ["Підрядне з je: дієсл. в кінець.", "Головне починається з desto/umso.", "desto = umso."],
    ),
    exercises15: [
      { type: "mc", q: "Je mehr du übst, ___ besser wirst du.", options: ["desto","damit","weil","so"], correct: 0 },
      { type: "mc", q: "___ älter er wird, umso ruhiger wird er.", options: ["Wenn","Je","So","Als"], correct: 1 },
      { type: "gap", q: "Je früher wir losfahren, ___ schneller sind wir da.", answer: "desto" },
      { type: "gap", q: "Je länger ich lerne, ___ mehr verstehe ich.", answer: "umso" },
      { type: "tf", q: "Після je та desto обов'язковий Komparativ.", correct: true },
      { type: "tf", q: "<i>umso</i> має інше значення, ніж <i>desto</i>.", correct: false },
      { type: "match", prompt: "Початок → продовження:", pairs: [
        { left: "Je mehr du übst,", right: "desto besser wirst du." },
        { left: "Je älter er wird,", right: "umso ruhiger wird er." },
        { left: "Je früher du kommst,", right: "desto besser." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Je mehr du übst, desto du wirst besser.",
        correct: ["Je mehr du übst, desto besser wirst du."] },
      { type: "correct", prompt: "Виправ:", wrong: "Je viel du lernst, desto viel du weißt.",
        correct: ["Je mehr du lernst, desto mehr weißt du."] },
      { type: "multi", q: "Виділи правильні речення:", options: [
        "Je mehr, desto besser.","Je viel, desto viel.","Je früher, umso besser.","Je gut, desto gut."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["je","mehr","du","übst","wirst","besser","du","desto"],
        correct: ["je","mehr","du","übst","desto","besser","wirst","du"] },
      { type: "translate", prompt: "Переклади:", uk: "Чим довше я навчаюся, тим більше знаю.",
        de: ["Je länger ich lerne, desto mehr weiß ich.","Je länger ich lerne, umso mehr weiß ich."] },
      { type: "translate", prompt: "Переклади:", uk: "Чим холодніше, тим тепліше я одягаюся.",
        de: ["Je kälter es ist, desto wärmer ziehe ich mich an."] },
      { type: "writeFree", prompt: "Напиши 2 речення з je … desto.",
        sample: "Je mehr Sprachen ich lerne, desto leichter fällt mir die nächste. Je früher man aufsteht, umso produktiver wird der Tag." },
      { type: "mc", q: "Je <b>...</b> du übst, desto besser.", options: ["viel","mehr","sehr","ganz"], correct: 1 },
    ],
  },

  "zweiteilige-konjunktionen": {
    lesson: {
      slug: "zweiteilige-konjunktionen", level: "B1", category: CAT,
      titleDe: "Zweiteilige Konjunktionen",
      titleUk: "Двочленні сполучники",
      goal: "Уживати парні сполучники <i>entweder…oder, weder…noch, sowohl…als auch, nicht nur…sondern auch, zwar…aber</i>.",
      explanation: [
        "<b>entweder … oder</b> — або …, або …: <i>Entweder kommst du, oder du rufst an.</i>",
        "<b>weder … noch</b> — ні …, ні … (заперечення без nicht/kein): <i>Er trinkt weder Kaffee noch Tee.</i>",
        "<b>sowohl … als auch</b> — як …, так і …: <i>Sie spricht sowohl Deutsch als auch Englisch.</i>",
        "<b>nicht nur … sondern auch</b> — не лише …, а й …: <i>Ich lerne nicht nur Deutsch, sondern auch Spanisch.</i>",
        "<b>zwar … aber</b> — хоч і …, але …: <i>Es ist zwar teuer, aber sehr gut.</i>",
      ],
      table: {
        headers: ["Сполучник", "Значення", "Приклад"],
        rows: [
          ["entweder … oder", "або … або", "Entweder du oder ich."],
          ["weder … noch", "ні … ні", "Weder er noch sie."],
          ["sowohl … als auch", "і … і", "Sowohl X als auch Y."],
          ["nicht nur … sondern auch", "не тільки … а й", "Nicht nur Deutsch, sondern auch Englisch."],
          ["zwar … aber", "хоч і … але", "Zwar teuer, aber gut."],
        ],
      },
      examples: [
        { de: "Entweder kommst du, oder du rufst an.", uk: "Або ти приходиш, або дзвониш." },
        { de: "Er trinkt weder Kaffee noch Tee.", uk: "Він не п'є ні кави, ні чаю." },
        { de: "Sie spricht sowohl Deutsch als auch Englisch.", uk: "Вона говорить і німецькою, і англійською." },
        { de: "Ich lerne nicht nur Deutsch, sondern auch Spanisch.", uk: "Я вчу не лише німецьку, а й іспанську." },
        { de: "Das Auto ist zwar alt, aber zuverlässig.", uk: "Машина хоч і стара, але надійна." },
        { de: "Weder ich noch er war dabei.", uk: "Ні я, ні він не були при цьому." },
        { de: "Entweder du hilfst mir, oder ich mache es allein.", uk: "Або ти мені допомагаєш, або я роблю сам(а)." },
        { de: "Sowohl der Film als auch das Buch waren gut.", uk: "І фільм, і книга були гарні." },
      ],
      tip: "<b>weder … noch</b> уже містить заперечення — <b>не додавай</b> <i>nicht</i> або <i>kein</i>!",
      mistakes: [
        { wrong: "Er trinkt nicht weder Kaffee noch Tee.", right: "Er trinkt weder Kaffee noch Tee." },
        { wrong: "Sowohl Deutsch wie Englisch.", right: "Sowohl Deutsch als auch Englisch." },
      ],
      exercises: {}, prevSlug: "je-desto",
    },
    extras: baseExtras(
      "Парні сполучники: <b>entweder/oder, weder/noch, sowohl/als auch, nicht nur/sondern auch, zwar/aber</b>.",
      ["<i>weder…noch</i> — без додаткового nicht.", "<i>sowohl…als auch</i> — не «wie», саме «als auch»."],
      ["entweder…oder — вибір.", "weder…noch — заперечення обох.", "sowohl…als auch — і… і.", "nicht nur…sondern auch — додатково.", "zwar…aber — поступка."],
    ),
    exercises15: [
      { type: "mc", q: "Er trinkt ___ Kaffee ___ Tee.", options: ["sowohl…als auch","weder…noch","entweder…oder","zwar…aber"], correct: 1 },
      { type: "mc", q: "___ du kommst, ___ du rufst an.", options: ["Entweder…oder","Weder…noch","Sowohl…als auch","Zwar…aber"], correct: 0 },
      { type: "gap", q: "Sie spricht sowohl Deutsch ___ ___ Englisch.", answer: "als auch" },
      { type: "gap", q: "Ich lerne nicht nur Deutsch, ___ ___ Spanisch.", answer: "sondern auch" },
      { type: "gap", q: "Das Auto ist ___ alt, ___ zuverlässig.", answer: "zwar aber" },
      { type: "tf", q: "<i>weder…noch</i> вимагає додаткового nicht.", correct: false },
      { type: "tf", q: "<i>sowohl … als auch</i> — і … і.", correct: true },
      { type: "match", prompt: "Парний сполучник → значення:", pairs: [
        { left: "entweder…oder", right: "або…або" }, { left: "weder…noch", right: "ні…ні" },
        { left: "sowohl…als auch", right: "і…і" }, { left: "zwar…aber", right: "хоч і…але" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Er trinkt nicht weder Kaffee noch Tee.",
        correct: ["Er trinkt weder Kaffee noch Tee."] },
      { type: "correct", prompt: "Виправ:", wrong: "Sowohl Deutsch wie Englisch.",
        correct: ["Sowohl Deutsch als auch Englisch."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Weder er noch sie war da.","Weder er noch sie nicht war da.",
        "Sowohl X als auch Y.","Sowohl X wie auch Y."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["entweder","kommst","oder","an","du","rufst","du"],
        correct: ["entweder","kommst","du","oder","du","rufst","an"] },
      { type: "translate", prompt: "Переклади:", uk: "Я вчу не тільки німецьку, а й іспанську.",
        de: ["Ich lerne nicht nur Deutsch, sondern auch Spanisch."] },
      { type: "translate", prompt: "Переклади:", uk: "Він не п'є ні кави, ні чаю.",
        de: ["Er trinkt weder Kaffee noch Tee."] },
      { type: "writeFree", prompt: "Напиши 3 речення з різними парними сполучниками.",
        sample: "Sowohl meine Schwester als auch ich lernen Deutsch. Wir essen am Wochenende entweder zu Hause oder im Restaurant. Weder mein Vater noch meine Mutter spricht Französisch." },
    ],
  },
};
