// B1 · Verben — 13 повних уроків.
import type { B1Map } from "./_helpers";
const CAT = "Дієслова";

export const verbenB1: B1Map = {
  praeteritum: {
    lesson: {
      slug: "praeteritum", level: "B1", category: CAT,
      titleDe: "Präteritum häufiger Verben", titleUk: "Präteritum поширених дієслів",
      goal: "Утворювати й розпізнавати Präteritum у письмових текстах і розповідях.",
      explanation: [
        "<b>Präteritum</b> — простий минулий час. Основне поле вживання — <b>письмові тексти</b>: новини, оповідання, біографії. В усному мовленні замість нього зазвичай Perfekt — крім <i>sein, haben</i> і модальних.",
        "Слабкі дієслова: основа + <b>-te-</b> + закінчення: <i>machen → machte, machtest, machte, machten…</i>",
        "Сильні дієслова: <b>чергування голосної</b> (Ablaut) + закінчення без -te-: <i>gehen → ging, gingst, ging, gingen…</i> У 1 і 3 ос. однини закінчення немає.",
        "Мішані дієслова поєднують Ablaut + -te-: <i>bringen → brachte, denken → dachte, wissen → wusste</i>.",
      ],
      table: {
        headers: ["", "machen", "gehen", "kommen", "sehen", "bringen"],
        rows: [
          ["ich", "machte", "ging", "kam", "sah", "brachte"],
          ["du", "machtest", "gingst", "kamst", "sahst", "brachtest"],
          ["er/sie/es", "machte", "ging", "kam", "sah", "brachte"],
          ["wir", "machten", "gingen", "kamen", "sahen", "brachten"],
          ["ihr", "machtet", "gingt", "kamt", "saht", "brachtet"],
          ["sie/Sie", "machten", "gingen", "kamen", "sahen", "brachten"],
        ],
      },
      examples: [
        { de: "Gestern arbeitete ich bis 20 Uhr.", uk: "Учора я працював(ла) до 20:00." },
        { de: "Er ging schnell nach Hause.", uk: "Він швидко пішов додому." },
        { de: "Wir sahen einen interessanten Film.", uk: "Ми подивилися цікавий фільм." },
        { de: "Sie kam pünktlich zum Termin.", uk: "Вона прийшла вчасно на зустріч." },
        { de: "Der Zug fuhr um 7 Uhr ab.", uk: "Потяг від'їхав о 7-й." },
        { de: "Ich brachte meiner Mutter Blumen.", uk: "Я приніс(ла) мамі квіти." },
        { de: "Plötzlich klingelte das Telefon.", uk: "Раптом задзвонив телефон." },
        { de: "Die Kinder spielten im Garten.", uk: "Діти бавилися в саду." },
      ],
      tip: "Слабкі = <b>-te-</b>, сильні = <b>зміна голосної</b>. У 1 і 3 ос. однини сильних — <b>немає закінчення</b>.",
      mistakes: [
        { wrong: "Ich gingte nach Hause.", right: "Ich ging nach Hause." },
        { wrong: "Er machtete das Frühstück.", right: "Er machte das Frühstück." },
        { wrong: "Sie bringte Blumen.", right: "Sie brachte Blumen." },
      ],
      exercises: {}, nextSlug: "futur1",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["утворювати Präteritum слабких і сильних дієслів", "знати найважливіші форми Ablaut", "розрізняти Präteritum і Perfekt за стилем"],
      ruleBox: { rule: "Слабкі: <b>-te-</b> + закінчення. Сильні: <b>Ablaut</b> без -te-. 1/3 ос. одн. сильних — без закінчення." },
      ukrainianTips: [
        "В українській один минулий час — у німецькій вибір <i>Präteritum чи Perfekt</i> залежить від <b>стилю</b>, а не від виду.",
        "Сильні форми треба вивчати таблицями (3 форми: Inf. – Prät. – P II).",
      ],
      languageComparison: {
        commons: ["Обидві мови виражають минуле."],
        diffs: ["У німецькій два минулих часи з різними сферами вжитку."],
        traps: ["Не плутати слабке machte (machen) і сильне macht (Präsens 3 ос.)."],
      },
      summary: ["Слабкі: -te-.", "Сильні: Ablaut.", "Мішані: Ablaut + -te-.", "Письмові тексти → Präteritum.", "Усне мовлення → Perfekt (крім sein/haben/Modalverben)."],
    },
    exercises15: [
      { type: "mc", q: "Präteritum від <i>gehen</i> (ich):", options: ["gehte","ging","gang","gegangen"], correct: 1 },
      { type: "mc", q: "Präteritum від <i>machen</i> (er):", options: ["macht","machte","machtete","gemacht"], correct: 1 },
      { type: "mc", q: "Präteritum від <i>bringen</i> (sie, Sg.):", options: ["bringte","brang","brachte","gebracht"], correct: 2 },
      { type: "mc", q: "Präteritum від <i>kommen</i> (wir):", options: ["kommten","kamen","kommen","kommten"], correct: 1 },
      { type: "gap", q: "Er ___ (sehen) den Film.", answer: "sah" },
      { type: "gap", q: "Wir ___ (arbeiten) bis spät.", answer: "arbeiteten", hint: "Слабке з основою на -t → arbeitete-." },
      { type: "gap", q: "Sie ___ (denken) lange nach.", answer: "dachte", hint: "Мішане." },
      { type: "gap", q: "Ich ___ (fahren) nach Berlin.", answer: "fuhr" },
      { type: "tf", q: "Сильні дієслова в Präteritum мають -te-.", correct: false },
      { type: "tf", q: "У 1 і 3 ос. однини сильних — нульове закінчення.", correct: true },
      { type: "match", prompt: "Інфінітив → Präteritum (3 Sg.):", pairs: [
        { left: "gehen", right: "ging" }, { left: "sehen", right: "sah" },
        { left: "kommen", right: "kam" }, { left: "machen", right: "machte" },
        { left: "bringen", right: "brachte" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich gingte ins Kino.", correct: ["Ich ging ins Kino."] },
      { type: "multi", q: "Які форми — Präteritum?",
        options: ["machte","mache","gemacht","ging","geht","kam"], correct: [0,3,5] },
      { type: "order", prompt: "Склади речення:",
        words: ["Hause","ging","ich","spät","nach"], correct: ["ich","ging","spät","nach","Hause"] },
      { type: "translate", prompt: "Переклади у Präteritum:", uk: "Він прийшов додому й подивився фільм.",
        de: ["Er kam nach Hause und sah einen Film.","Er kam nach Hause und sah einen Film an."] },
      { type: "writeFree", prompt: "Напиши 3 речення у Präteritum про вчорашній день.",
        sample: "Gestern stand ich früh auf. Ich fuhr ins Büro und arbeitete bis 18 Uhr. Am Abend traf ich Freunde.",
        explain: "Перевір: слабкі → -te-, сильні → Ablaut." },
    ],
  },

  futur1: {
    lesson: {
      slug: "futur1", level: "B1", category: CAT,
      titleDe: "Futur I", titleUk: "Майбутній час Futur I",
      goal: "Утворювати Futur I і свідомо обирати його замість Präsens для прогнозу й намірів.",
      explanation: [
        "<b>Futur I = werden (на 2 місці) + Infinitiv (в кінці)</b>. Уживається для <b>прогнозів</b>, <b>передбачень</b>, <b>намірів</b> і <b>обіцянок</b>.",
        "У повсякденній мові для майбутнього часто достатньо <b>Präsens + обставина часу</b>: <i>Morgen fahre ich nach Wien</i>.",
        "Futur I = акцент на <b>впевненості / припущенні</b>, особливо з модальними словами <i>wohl, sicher, bestimmt, vielleicht</i>.",
        "Інша функція — <b>припущення про теперішнє</b>: <i>Er wird jetzt im Büro sein</i> = «Напевно, він зараз в офісі».",
      ],
      table: {
        headers: ["", "werden + Infinitiv"],
        rows: [
          ["ich", "werde lernen"], ["du", "wirst lernen"], ["er/sie/es", "wird lernen"],
          ["wir", "werden lernen"], ["ihr", "werdet lernen"], ["sie/Sie", "werden lernen"],
        ],
      },
      examples: [
        { de: "Ich werde nächstes Jahr Deutsch lernen.", uk: "Наступного року я вчитиму німецьку." },
        { de: "Es wird morgen regnen.", uk: "Завтра йтиме дощ." },
        { de: "Wir werden uns bestimmt wiedersehen.", uk: "Ми обов'язково ще побачимося." },
        { de: "Er wird wohl krank sein.", uk: "Він, певно, хворий." },
        { de: "Sie wird das schaffen.", uk: "Вона з цим упорається." },
        { de: "Ich werde dir helfen.", uk: "Я тобі допоможу." },
        { de: "Bald werden wir umziehen.", uk: "Невдовзі ми переїдемо." },
        { de: "Du wirst sehen, alles wird gut.", uk: "Побачиш, усе буде добре." },
      ],
      tip: "Запам'ятай: <b>werde / wirst / wird / werden / werdet / werden</b> + інфінітив у кінці.",
      mistakes: [
        { wrong: "Ich werde lerne Deutsch.", right: "Ich werde Deutsch lernen." },
        { wrong: "Morgen ich werde kommen.", right: "Morgen werde ich kommen." },
      ],
      exercises: {}, prevSlug: "praeteritum", nextSlug: "verben-praep",
    },
    extras: {
      duration: 15, premium: true,
      learningGoals: ["утворювати Futur I у всіх особах", "розрізняти Futur I і Präsens для майбутнього", "розуміти Futur I як припущення"],
      ruleBox: { rule: "<b>werden + Infinitiv</b> у кінці речення. werden — на 2 місці." },
      ukrainianTips: [
        "Українське «буду робити» / «зроблю» — обидва варіанти можуть бути Futur I, але частіше — Präsens.",
        "Якщо є «напевно/мабуть» — обирай Futur I із <i>wohl/sicher</i>.",
      ],
      languageComparison: {
        commons: ["Обидві мови виражають майбутнє."],
        diffs: ["Німецька частіше використовує Präsens для майбутнього."],
        traps: ["Інфінітив <b>у кінці</b> — не біля werden."],
      },
      summary: ["werden + Infinitiv.", "Прогноз, намір, обіцянка.", "Припущення: wird wohl + Inf.", "Альтернатива: Präsens + час."],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ morgen kommen.", options: ["werde","wirst","wird","werden"], correct: 0 },
      { type: "mc", q: "Er ___ uns helfen.", options: ["werde","wirst","wird","werden"], correct: 2 },
      { type: "gap", q: "Wir ___ nächstes Jahr nach Berlin ziehen. (werden)", answer: "werden" },
      { type: "gap", q: "Du ___ das schaffen. (werden)", answer: "wirst" },
      { type: "tf", q: "Інфінітив у Futur I стоїть у кінці речення.", correct: true },
      { type: "tf", q: "Для майбутнього в розмові завжди треба Futur I.", correct: false },
      { type: "mc", q: "Який варіант — припущення про теперішнє?",
        options: ["Er wird morgen kommen.","Er wird jetzt im Büro sein.","Er kommt morgen.","Er ist im Büro."], correct: 1 },
      { type: "match", prompt: "Особа → форма werden:", pairs: [
        { left: "ich", right: "werde" }, { left: "du", right: "wirst" },
        { left: "er", right: "wird" }, { left: "wir", right: "werden" },
        { left: "ihr", right: "werdet" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich werde lerne Deutsch.", correct: ["Ich werde Deutsch lernen."] },
      { type: "multi", q: "Які речення — у Futur I?", options: [
        "Ich werde es machen.","Ich mache es.","Sie wird kommen.","Sie kam.","Wir werden helfen."], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["werde","helfen","ich","dir","morgen"], correct: ["ich","werde","dir","morgen","helfen"] },
      { type: "translate", prompt: "Переклади у Futur I:", uk: "Завтра я тобі зателефоную.",
        de: ["Ich werde dich morgen anrufen.","Morgen werde ich dich anrufen."] },
      { type: "translate", prompt: "Переклади як припущення (Futur I):", uk: "Він, мабуть, удома.",
        de: ["Er wird wohl zu Hause sein."], explain: "wird + wohl + sein." },
      { type: "writeFree", prompt: "Напиши 2 речення про свої плани (Futur I).",
        sample: "Nächstes Jahr werde ich eine Reise nach Berlin machen. Ich werde dort meine Deutschkenntnisse verbessern." },
      { type: "mc", q: "Es ___ heute Abend regnen.", options: ["wird","werde","werdet","sind"], correct: 0 },
    ],
  },

  "verben-praep": {
    lesson: {
      slug: "verben-praep", level: "B1", category: CAT,
      titleDe: "Verben mit Präpositionen", titleUk: "Дієслова з прийменниками",
      goal: "Вивчити сталі сполучення «дієслово + прийменник» і правильно керувати відмінком.",
      explanation: [
        "Багато німецьких дієслів сполучаються з певним прийменником, який <b>визначає відмінок</b> наступного іменника: <i>warten <b>auf</b> + Akk., denken <b>an</b> + Akk., sprechen <b>über</b> + Akk., helfen <b>bei</b> + Dat.</i>",
        "Такі сполучення треба <b>вивчати разом</b>: дієслово + прийменник + відмінок.",
        "У питанні і в анафорі замість іменника використовуємо <b>pronominaladverbien</b>: <i>worauf? – darauf, woran? – daran, worüber? – darüber</i>.",
        "Якщо йдеться про <b>особу</b>, вживаємо <i>prep + Pron.</i>: <i>auf wen? – auf ihn, an wen? – an sie</i>.",
      ],
      table: {
        headers: ["Дієслово", "Прийменник", "Відмінок", "Приклад"],
        rows: [
          ["warten", "auf", "Akk.", "auf den Bus warten"],
          ["denken", "an", "Akk.", "an die Familie denken"],
          ["sprechen", "über", "Akk.", "über das Wetter sprechen"],
          ["sich freuen", "über / auf", "Akk.", "über/auf das Geschenk"],
          ["helfen", "bei", "Dat.", "bei der Arbeit helfen"],
          ["träumen", "von", "Dat.", "von einer Reise träumen"],
          ["sich interessieren", "für", "Akk.", "für Musik"],
          ["Angst haben", "vor", "Dat.", "vor dem Hund"],
        ],
      },
      examples: [
        { de: "Ich warte auf den Bus.", uk: "Я чекаю на автобус." },
        { de: "Sie denkt oft an ihre Familie.", uk: "Вона часто думає про свою сім'ю." },
        { de: "Wir sprechen über das Projekt.", uk: "Ми говоримо про проєкт." },
        { de: "Er hilft mir bei den Hausaufgaben.", uk: "Він допомагає мені з домашніми завданнями." },
        { de: "Ich freue mich auf das Wochenende.", uk: "Я з нетерпінням чекаю вихідних." },
        { de: "Sie träumt von einer Weltreise.", uk: "Вона мріє про подорож світом." },
        { de: "Wofür interessierst du dich?", uk: "Чим ти цікавишся?" },
        { de: "Ich habe Angst vor Spinnen.", uk: "Я боюся павуків." },
      ],
      tip: "Учи дієслово в «трикутнику»: <b>дієслово + прийменник + відмінок</b>. Наприклад: <i>warten + auf + Akk.</i>",
      mistakes: [
        { wrong: "Ich warte für den Bus.", right: "Ich warte auf den Bus." },
        { wrong: "Sie freut sich über das Wochenende (=in der Zukunft).", right: "Sie freut sich auf das Wochenende." },
        { wrong: "Ich denke über meine Familie.", right: "Ich denke an meine Familie." },
      ],
      exercises: {}, prevSlug: "futur1", nextSlug: "konjunktiv2-wuensche",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["знати найважливіші сполучення verb+prep", "правильно вибирати відмінок", "будувати питання з wo(r)+prep"],
      ruleBox: { rule: "Прийменник після дієслова — <b>сталий</b>, і він керує відмінком. Учити трійками: <i>verb + prep + Kasus</i>." },
      ukrainianTips: [
        "Українські відповідники прийменників часто <b>інші</b>: «думати про» → an + Akk., а не über.",
        "<i>sich freuen über</i> — радіти з приводу (минулого), <i>sich freuen auf</i> — чекати з радістю (майбутнє).",
      ],
      languageComparison: {
        commons: ["Обидві мови мають сталі дієслово-прийменникові сполучення."],
        diffs: ["Прийменники між мовами рідко збігаються — не перекладай дослівно."],
        traps: ["warten <b>auf</b>, не <i>für</i>; denken <b>an</b>, не <i>über</i>."],
      },
      summary: ["verb + prep + Kasus = одне ціле.", "Pronominaladverb: wo(r)+prep, da(r)+prep.", "Pro особу: prep + Pronomen."],
    },
    exercises15: [
      { type: "mc", q: "Ich warte ___ den Bus.", options: ["für","auf","an","über"], correct: 1 },
      { type: "mc", q: "Sie denkt oft ___ ihre Familie.", options: ["über","auf","an","von"], correct: 2 },
      { type: "mc", q: "Wir sprechen ___ das Projekt.", options: ["von","an","über","auf"], correct: 2 },
      { type: "mc", q: "Er hilft mir ___ den Hausaufgaben.", options: ["mit","bei","an","für"], correct: 1 },
      { type: "gap", q: "Ich freue mich ___ das Wochenende. (майбутнє)", answer: "auf" },
      { type: "gap", q: "Sie träumt ___ einer Reise.", answer: "von" },
      { type: "gap", q: "Wofür interessierst du ___?", answer: "dich" },
      { type: "gap", q: "Ich habe Angst ___ Spinnen.", answer: "vor" },
      { type: "tf", q: "<i>warten auf</i> вимагає Akkusativ.", correct: true },
      { type: "tf", q: "<i>helfen bei</i> вимагає Akkusativ.", correct: false, explain: "bei + Dativ." },
      { type: "match", prompt: "Дієслово → прийменник:", pairs: [
        { left: "warten", right: "auf" }, { left: "denken", right: "an" },
        { left: "träumen", right: "von" }, { left: "helfen", right: "bei" },
        { left: "Angst haben", right: "vor" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich denke über meine Familie.", correct: ["Ich denke an meine Familie."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich warte auf dich.","Ich warte für dich.","Sie spricht über die Arbeit.","Sie spricht an die Arbeit.","Er träumt von Urlaub."], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["denke","ich","oft","dich","an"], correct: ["ich","denke","oft","an","dich"] },
      { type: "translate", prompt: "Переклади:", uk: "Я цікавлюся музикою.",
        de: ["Ich interessiere mich für Musik."] },
    ],
  },

  "konjunktiv2-wuensche": {
    lesson: {
      slug: "konjunktiv2-wuensche", level: "B1", category: CAT,
      titleDe: "Konjunktiv II: Wünsche und Höflichkeit", titleUk: "Konjunktiv II для бажань і ввічливості",
      goal: "Висловлювати ввічливі прохання, поради та бажання за допомогою Konjunktiv II.",
      explanation: [
        "<b>Konjunktiv II</b> — це форма для нереального: бажань, ввічливих прохань, порад, припущень.",
        "Основні форми: <b>sein → wäre</b>, <b>haben → hätte</b>, <b>werden → würde</b>, модальні: <b>könnte, müsste, sollte, dürfte, möchte</b>.",
        "Для інших дієслів частіше беремо <b>würde + Infinitiv</b>: <i>Ich würde gern kommen</i>.",
        "Типові структури: <i>Ich hätte gern …</i>, <i>Ich möchte …</i>, <i>Könnten Sie …?</i>, <i>An deiner Stelle würde ich …</i>, <i>Ich wünschte, ich hätte …</i>.",
      ],
      table: {
        headers: ["Інфінітив", "Konjunktiv II"],
        rows: [
          ["sein", "wäre, wärst, wäre, wären, wärt, wären"],
          ["haben", "hätte, hättest, hätte, hätten, hättet, hätten"],
          ["werden", "würde, würdest, würde, würden, würdet, würden"],
          ["können", "könnte, könntest, könnte, könnten, könntet, könnten"],
          ["sollen", "sollte, solltest, sollte, sollten, solltet, sollten"],
          ["mögen", "möchte, möchtest, möchte, möchten, möchtet, möchten"],
        ],
      },
      examples: [
        { de: "Ich hätte gern einen Kaffee.", uk: "Я б хотів(ла) кави." },
        { de: "Könnten Sie mir helfen?", uk: "Чи могли б Ви мені допомогти?" },
        { de: "An deiner Stelle würde ich mehr lernen.", uk: "На твоєму місці я б більше вчив(ла)." },
        { de: "Wir hätten gern die Rechnung.", uk: "Ми б хотіли рахунок." },
        { de: "Es wäre toll, dich zu sehen.", uk: "Було б чудово тебе побачити." },
        { de: "Ich würde gern mehr reisen.", uk: "Я б хотів(ла) більше подорожувати." },
        { de: "Du solltest mehr schlafen.", uk: "Тобі варто більше спати." },
        { de: "Wenn ich Zeit hätte, würde ich kommen.", uk: "Якби я мав(ла) час, я б прийшов(ла)." },
      ],
      tip: "Ввічливо? Бажання? Порада? — бери <b>hätte / wäre / würde + Infinitiv</b> або модальне у K.II.",
      mistakes: [
        { wrong: "Ich hatte gern einen Kaffee.", right: "Ich hätte gern einen Kaffee." },
        { wrong: "Können Sie mir helfen, bitte? (грубо)", right: "Könnten Sie mir helfen, bitte?" },
      ],
      exercises: {}, prevSlug: "verben-praep", nextSlug: "konjunktiv2-irreal",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["утворювати hätte/wäre/würde + Inf.", "будувати ввічливі прохання", "висловлювати бажання й поради"],
      ruleBox: { rule: "Konjunktiv II = нереальне/ввічливе. <b>hätte, wäre, würde, könnte, möchte, sollte</b>." },
      ukrainianTips: ["Українське «я б хотів» = <b>ich hätte gern / ich möchte</b>.", "Для ввічливості завжди обираймо K.II замість Indikativ."],
      languageComparison: {
        commons: ["Обидві мови мають форми для ввічливості."],
        diffs: ["У німецькій це окрема морфологічна форма."],
        traps: ["Не плутай <b>hatte</b> (Prät.) і <b>hätte</b> (K.II)."],
      },
      summary: ["hätte/wäre/würde + Inf.", "Модальні: könnte, möchte, sollte.", "Ввічливо, бажання, порада."],
    },
    exercises15: [
      { type: "mc", q: "Ввічливо: ___ Sie mir helfen?", options: ["Können","Könnten","Konnten","Kannst"], correct: 1 },
      { type: "mc", q: "Ich ___ gern einen Tee.", options: ["habe","hatte","hätte","hätten"], correct: 2 },
      { type: "mc", q: "Es ___ schön, dich zu sehen.", options: ["war","wäre","ist","wird"], correct: 1 },
      { type: "gap", q: "Du ___ mehr schlafen. (sollen, K.II)", answer: "solltest" },
      { type: "gap", q: "An deiner Stelle ___ ich nicht gehen. (werden, K.II)", answer: "würde" },
      { type: "gap", q: "Wenn ich Zeit ___, käme ich. (haben, K.II)", answer: "hätte" },
      { type: "tf", q: "<i>möchte</i> — це Konjunktiv II від mögen.", correct: true },
      { type: "tf", q: "<i>hatte</i> = ввічлива форма.", correct: false, explain: "Hatte = Prät.; ввічливо — hätte." },
      { type: "match", prompt: "Інфінітив → K.II (3 Sg.):", pairs: [
        { left: "sein", right: "wäre" }, { left: "haben", right: "hätte" },
        { left: "werden", right: "würde" }, { left: "können", right: "könnte" },
        { left: "sollen", right: "sollte" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich hatte gern Wasser.", correct: ["Ich hätte gern Wasser."] },
      { type: "multi", q: "Які речення — ввічливі?", options: [
        "Gib mir das!","Könnten Sie mir das geben?","Ich hätte gern das.","Ich will das.","Würden Sie mir helfen?"], correct: [1,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["gern","hätte","ich","Kaffee","einen"], correct: ["ich","hätte","gern","einen","Kaffee"] },
      { type: "translate", prompt: "Переклади ввічливо:", uk: "Чи могли б Ви говорити повільніше?",
        de: ["Könnten Sie bitte langsamer sprechen?","Könnten Sie langsamer sprechen, bitte?"] },
      { type: "translate", prompt: "Переклади порадою:", uk: "Тобі варто більше відпочивати.",
        de: ["Du solltest dich mehr ausruhen.","Du solltest mehr ruhen."] },
      { type: "writeFree", prompt: "Напиши 2 ввічливих прохання офіціантові.",
        sample: "Könnten Sie mir bitte die Speisekarte bringen? Ich hätte gern noch ein Glas Wasser." },
    ],
  },

  "konjunktiv2-irreal": {
    lesson: {
      slug: "konjunktiv2-irreal", level: "B1", category: CAT,
      titleDe: "Konjunktiv II: irreale Situationen", titleUk: "Konjunktiv II для нереальних ситуацій",
      goal: "Будувати умовні речення нереального типу: «якби … тоді б …».",
      explanation: [
        "Нереальні умовні речення мають структуру: <b>Wenn + Konj. II, …, Konj. II</b> або «<i>Wenn ich Zeit hätte, würde ich kommen</i>».",
        "Друга частина (Hauptsatz) часто з <b>würde + Infinitiv</b>; з <i>sein/haben/Modalverben</i> — звичайна форма K.II.",
        "Можна опустити «wenn» — тоді дієслово на 1 місці: <i>Hätte ich Zeit, würde ich kommen</i>.",
        "Для <b>нереального минулого</b> — окремий урок (Konjunktiv II der Vergangenheit на B2).",
      ],
      table: {
        headers: ["Тип", "Приклад"],
        rows: [
          ["реальна умова (Indikativ)", "Wenn ich Zeit habe, komme ich."],
          ["нереальна умова (K.II)", "Wenn ich Zeit hätte, würde ich kommen."],
          ["без wenn (інверсія)", "Hätte ich Zeit, würde ich kommen."],
          ["бажання", "Ich wünschte, ich hätte mehr Zeit."],
          ["порада", "An deiner Stelle würde ich gehen."],
        ],
      },
      examples: [
        { de: "Wenn ich reich wäre, würde ich eine Insel kaufen.", uk: "Якби я був(ла) багатим(ою), я б купив(ла) острів." },
        { de: "Wenn er hier wäre, könnte er uns helfen.", uk: "Якби він був тут, він міг би нам допомогти." },
        { de: "Hätte ich mehr Zeit, würde ich Sport machen.", uk: "Якби я мав(ла) більше часу, я б займав(ла)ся спортом." },
        { de: "Ich wünschte, ich könnte Deutsch fließend sprechen.", uk: "Я б хотів(ла) вільно говорити німецькою." },
        { de: "Wenn das Wetter besser wäre, gingen wir spazieren.", uk: "Якби погода була кращою, ми б пішли гуляти." },
        { de: "An ihrer Stelle würde ich es ihm sagen.", uk: "На її місці я б йому сказав(ла)." },
        { de: "Wenn du fragen würdest, würde ich antworten.", uk: "Якби ти запитав(ла), я б відповів(ла)." },
        { de: "Es wäre schön, wenn du kommen könntest.", uk: "Було б добре, якби ти зміг(ла) прийти." },
      ],
      tip: "Шаблон: <b>Wenn … hätte/wäre/würde, würde … Infinitiv.</b>",
      mistakes: [
        { wrong: "Wenn ich hätte Zeit, ich würde kommen.", right: "Wenn ich Zeit hätte, würde ich kommen." },
        { wrong: "Wenn ich reich wäre, ich kaufe ein Haus.", right: "Wenn ich reich wäre, würde ich ein Haus kaufen." },
      ],
      exercises: {}, prevSlug: "konjunktiv2-wuensche", nextSlug: "passiv-praesens",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["будувати wenn-речення в K.II", "уживати würde + Inf. правильно", "розуміти інверсію без wenn"],
      ruleBox: { rule: "<b>Wenn + K.II, würde + Inf.</b> — нереальна умова теперішнього/майбутнього." },
      ukrainianTips: ["Українське «якби … тоді б …» = <b>Wenn … K.II, würde … Inf.</b>", "Пам'ятай: у обох частинах <b>K.II</b>."],
      languageComparison: {
        commons: ["Обидві мови мають умовний спосіб."],
        diffs: ["У німецькій два дієслова в K.II — у головному і в підрядному."],
        traps: ["Не змішуй з Indikativ: «Wenn ich Zeit habe» = реальне."],
      },
      summary: ["Нереально → K.II у обох частинах.", "Часто würde + Inf. у головному.", "Без wenn → інверсія."],
    },
    exercises15: [
      { type: "mc", q: "Wenn ich Zeit ___, würde ich kommen.", options: ["habe","hatte","hätte","haben"], correct: 2 },
      { type: "mc", q: "Wenn er hier ___, könnte er helfen.", options: ["ist","wäre","war","sei"], correct: 1 },
      { type: "gap", q: "Wenn du fragen ___, würde ich antworten. (werden)", answer: "würdest" },
      { type: "gap", q: "Ich ___, ich hätte mehr Zeit. (wünschen, K.II)", answer: "wünschte" },
      { type: "gap", q: "___ ich reich, würde ich reisen. (без wenn — wäre)", answer: "Wäre" },
      { type: "tf", q: "У нереальних умовних реченнях обидві частини у K.II.", correct: true },
      { type: "tf", q: "Без <i>wenn</i> дієслово опиняється на 1 місці.", correct: true },
      { type: "match", prompt: "Wenn-частина → головна частина:", pairs: [
        { left: "Wenn ich Zeit hätte,", right: "würde ich kommen." },
        { left: "Wenn er hier wäre,", right: "könnte er helfen." },
        { left: "Wenn du fleißiger wärst,", right: "würdest du es schaffen." },
        { left: "Wenn ich du wäre,", right: "würde ich gehen." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Wenn ich hätte Zeit, würde ich kommen.",
        correct: ["Wenn ich Zeit hätte, würde ich kommen."] },
      { type: "correct", prompt: "Виправ:", wrong: "Wenn ich reich wäre, ich kaufe ein Haus.",
        correct: ["Wenn ich reich wäre, würde ich ein Haus kaufen."] },
      { type: "multi", q: "Виділи K.II-форми:",
        options: ["hätte","habe","wäre","war","würde","wird","könnte"], correct: [0,2,4,6] },
      { type: "order", prompt: "Склади умовне речення:",
        words: ["wäre","reich","ich","wenn","Insel","kaufen","würde","eine","ich"],
        correct: ["wenn","ich","reich","wäre","würde","ich","eine","Insel","kaufen"] },
      { type: "translate", prompt: "Переклади:", uk: "Якби я мав(ла) гроші, я б купив(ла) машину.",
        de: ["Wenn ich Geld hätte, würde ich ein Auto kaufen.","Hätte ich Geld, würde ich ein Auto kaufen."] },
      { type: "translate", prompt: "Переклади:", uk: "На твоєму місці я б йому подзвонив(ла).",
        de: ["An deiner Stelle würde ich ihn anrufen."] },
      { type: "writeFree", prompt: "Напиши 2 нереальні бажання у K.II.",
        sample: "Wenn ich mehr Zeit hätte, würde ich ein Buch schreiben. Wenn das Wetter besser wäre, würden wir an den See fahren." },
    ],
  },

  "passiv-praesens": {
    lesson: {
      slug: "passiv-praesens", level: "B1", category: CAT,
      titleDe: "Passiv Präsens", titleUk: "Пасив у Präsens",
      goal: "Утворювати й уживати Passiv у теперішньому часі для опису процесів.",
      explanation: [
        "<b>Passiv Präsens = werden (на 2 місці) + Partizip II (в кінці)</b>.",
        "Уживається, коли важлива <b>дія</b>, а не <b>виконавець</b>: <i>Das Haus wird gebaut</i>.",
        "Виконавець (Agens) при бажанні додається з <b>von + Dat.</b> (виконавець-особа) або <b>durch + Akk.</b> (засіб/причина).",
        "Перетворення з Aktiv: <i>Akkusativ-Objekt</i> стає <i>Subjekt</i>; дієслово → werden + P II.",
      ],
      table: {
        headers: ["", "werden + P II"],
        rows: [
          ["ich", "werde gefragt"], ["du", "wirst gefragt"], ["er/sie/es", "wird gefragt"],
          ["wir", "werden gefragt"], ["ihr", "werdet gefragt"], ["sie/Sie", "werden gefragt"],
        ],
      },
      examples: [
        { de: "Das Haus wird gebaut.", uk: "Будинок будують." },
        { de: "Der Brief wird geschrieben.", uk: "Лист пишуть." },
        { de: "Die Kinder werden gefragt.", uk: "Дітей запитують." },
        { de: "Hier wird Deutsch gesprochen.", uk: "Тут розмовляють німецькою." },
        { de: "Das Auto wird von dem Mechaniker repariert.", uk: "Машину ремонтує механік." },
        { de: "Die Stadt wird durch ein Erdbeben zerstört.", uk: "Місто руйнується землетрусом." },
        { de: "Werden Sie informiert?", uk: "Вас інформують?" },
        { de: "Das Buch wird gerade gelesen.", uk: "Книгу зараз читають." },
      ],
      tip: "Aktiv: <i>Der Mann baut das Haus.</i> → Passiv: <i>Das Haus wird (vom Mann) gebaut.</i>",
      mistakes: [
        { wrong: "Das Haus ist gebaut.", right: "Das Haus wird gebaut." },
        { wrong: "Der Brief wird schreiben.", right: "Der Brief wird geschrieben." },
      ],
      exercises: {}, prevSlug: "konjunktiv2-irreal", nextSlug: "passiv-praeteritum",
    },
    extras: {
      duration: 18, premium: true,
      learningGoals: ["утворювати Passiv Präsens", "перетворювати Aktiv → Passiv", "уживати von/durch"],
      ruleBox: { rule: "Passiv = <b>werden + Partizip II</b>. Akk. в Aktiv → Subjekt у Passiv." },
      ukrainianTips: ["Українське безособове «будують, ремонтують» = німецький Passiv.", "<b>von</b> — для особи; <b>durch</b> — для причини/інструмента."],
      languageComparison: {
        commons: ["Обидві мови мають пасив."],
        diffs: ["У німецькій — окрема структура з werden, а не «-ся»."],
        traps: ["Не плутай <i>wird gebaut</i> (Passiv) із <i>ist gebaut</i> (Zustandspassiv = стан)."],
      },
      summary: ["Passiv = werden + P II.", "Akk-Objekt → Subjekt.", "von (особа), durch (причина)."],
    },
    exercises15: [
      { type: "mc", q: "Das Haus ___ gebaut.", options: ["ist","wird","hat","hatte"], correct: 1 },
      { type: "mc", q: "Wir ___ informiert.", options: ["sind","werden","haben","hatten"], correct: 1 },
      { type: "gap", q: "Der Brief ___ geschrieben. (er, werden)", answer: "wird" },
      { type: "gap", q: "Die Kinder ___ gefragt. (sie, werden)", answer: "werden" },
      { type: "gap", q: "Das Auto wird ___ dem Mechaniker repariert.", answer: "von" },
      { type: "gap", q: "Die Stadt wird ___ einen Sturm zerstört.", answer: "durch" },
      { type: "tf", q: "Passiv = haben + Partizip II.", correct: false, explain: "werden + P II." },
      { type: "tf", q: "У Passiv важлива дія, а не хто її виконує.", correct: true },
      { type: "match", prompt: "Aktiv → Passiv:", pairs: [
        { left: "Man baut das Haus.", right: "Das Haus wird gebaut." },
        { left: "Man liest das Buch.", right: "Das Buch wird gelesen." },
        { left: "Man fragt die Kinder.", right: "Die Kinder werden gefragt." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das Haus ist gebaut (= процес).",
        correct: ["Das Haus wird gebaut."] },
      { type: "multi", q: "Які речення — Passiv Präsens?", options: [
        "Das Haus wird gebaut.","Das Haus ist gebaut.","Wir werden gefragt.","Wir sind gefragt.","Der Brief wird geschrieben."], correct: [0,2,4] },
      { type: "order", prompt: "Склади Passiv-речення:",
        words: ["gebaut","wird","Haus","das","schnell"], correct: ["das","Haus","wird","schnell","gebaut"] },
      { type: "translate", prompt: "Переклади у Passiv:", uk: "Тут розмовляють німецькою.",
        de: ["Hier wird Deutsch gesprochen."] },
      { type: "translate", prompt: "Переклади у Passiv:", uk: "Машину ремонтує механік.",
        de: ["Das Auto wird von dem Mechaniker repariert.","Das Auto wird vom Mechaniker repariert."] },
      { type: "writeFree", prompt: "Опиши 2 щоденні процеси у Passiv (наприклад, у пекарні).",
        sample: "In der Bäckerei wird jeden Morgen frisches Brot gebacken. Die Brötchen werden um 6 Uhr verkauft." },
    ],
  },

  "passiv-praeteritum": {
    lesson: {
      slug: "passiv-praeteritum", level: "B1", category: CAT,
      titleDe: "Passiv Präteritum", titleUk: "Пасив у Präteritum",
      goal: "Утворювати Passiv у простому минулому часі для описів подій і процесів у минулому.",
      explanation: [
        "<b>Passiv Präteritum = wurde + Partizip II</b>.",
        "Уживається в письмових текстах: новини, історичні факти, інструкції.",
        "Виконавець (опційно): <b>von + Dat.</b> або <b>durch + Akk.</b>",
        "Якщо потрібна <b>розмовна форма</b>, частіше беремо <b>Passiv Perfekt</b>: <i>ist gebaut worden</i>.",
      ],
      table: {
        headers: ["", "wurde + P II"],
        rows: [
          ["ich", "wurde gefragt"], ["du", "wurdest gefragt"], ["er/sie/es", "wurde gefragt"],
          ["wir", "wurden gefragt"], ["ihr", "wurdet gefragt"], ["sie/Sie", "wurden gefragt"],
        ],
      },
      examples: [
        { de: "Das Haus wurde 1990 gebaut.", uk: "Будинок збудували у 1990 році." },
        { de: "Der Brief wurde gestern geschrieben.", uk: "Лист написали вчора." },
        { de: "Die Kinder wurden vom Lehrer gelobt.", uk: "Дітей похвалив учитель." },
        { de: "Die Tür wurde geöffnet.", uk: "Двері відчинили." },
        { de: "Das Buch wurde von Goethe geschrieben.", uk: "Книгу написав Гете." },
        { de: "Die Stadt wurde durch einen Krieg zerstört.", uk: "Місто було зруйноване війною." },
        { de: "Wir wurden gestern informiert.", uk: "Нас учора повідомили." },
        { de: "Wurdest du gefragt?", uk: "Тебе питали?" },
      ],
      tip: "<b>wurde / wurdest / wurde / wurden / wurdet / wurden</b> + Partizip II.",
      mistakes: [
        { wrong: "Das Haus war gebaut 1990.", right: "Das Haus wurde 1990 gebaut." },
        { wrong: "Der Brief wurde geschrieben von Anna gestern.", right: "Der Brief wurde gestern von Anna geschrieben." },
      ],
      exercises: {}, prevSlug: "passiv-praesens", nextSlug: "infinitiv-mit-zu",
    },
    extras: {
      duration: 15, premium: true,
      learningGoals: ["утворювати Passiv Präteritum", "розрізняти von/durch", "перетворювати Aktiv → Passiv у минулому"],
      ruleBox: { rule: "<b>wurde + Partizip II</b>. Akk-Objekt → Subjekt." },
      ukrainianTips: ["Українське «був(ла) збудований(а)/збудовано» = німецький Passiv Präteritum."],
      languageComparison: {
        commons: ["Обидві мови виражають пасивне значення в минулому."],
        diffs: ["У німецькій — окрема форма (wurde + P II)."],
        traps: ["Не плутати <i>wurde gebaut</i> (процес) і <i>war gebaut</i> (стан)."],
      },
      summary: ["Passiv Prät. = wurde + P II.", "Часто в письмових текстах.", "Виконавець — von/durch (опційно)."],
    },
    exercises15: [
      { type: "mc", q: "Das Haus ___ 1990 gebaut.", options: ["war","wurde","ist","wird"], correct: 1 },
      { type: "mc", q: "Wir ___ gestern informiert.", options: ["sind","wurden","wären","werden"], correct: 1 },
      { type: "gap", q: "Der Brief ___ geschrieben. (er, wurde)", answer: "wurde" },
      { type: "gap", q: "Die Tür ___ geöffnet.", answer: "wurde" },
      { type: "gap", q: "Die Kinder wurden ___ Lehrer gelobt.", answer: "vom" },
      { type: "gap", q: "Die Stadt wurde ___ einen Krieg zerstört.", answer: "durch" },
      { type: "tf", q: "Passiv Präteritum = wurde + Infinitiv.", correct: false, explain: "wurde + Partizip II." },
      { type: "tf", q: "<i>wurde</i> — це Präteritum дієслова werden.", correct: true },
      { type: "match", prompt: "Aktiv → Passiv Prät.:", pairs: [
        { left: "Goethe schrieb das Buch.", right: "Das Buch wurde von Goethe geschrieben." },
        { left: "Man baute das Haus.", right: "Das Haus wurde gebaut." },
        { left: "Der Lehrer lobte die Kinder.", right: "Die Kinder wurden vom Lehrer gelobt." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das Haus war 1990 gebaut.",
        correct: ["Das Haus wurde 1990 gebaut."] },
      { type: "multi", q: "Які речення — Passiv Präteritum?", options: [
        "Das Haus wurde gebaut.","Das Haus war gebaut.","Wir wurden gefragt.","Wir waren gefragt.","Der Brief wurde geschrieben."], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["1990","wurde","Haus","das","gebaut"], correct: ["das","Haus","wurde","1990","gebaut"] },
      { type: "translate", prompt: "Переклади:", uk: "Лист написали вчора.",
        de: ["Der Brief wurde gestern geschrieben.","Gestern wurde der Brief geschrieben."] },
      { type: "translate", prompt: "Переклади:", uk: "Місто було зруйноване війною.",
        de: ["Die Stadt wurde durch einen Krieg zerstört."] },
      { type: "writeFree", prompt: "Опиши 2 події з історії свого міста у Passiv Präteritum.",
        sample: "Die Kirche wurde im 15. Jahrhundert gebaut. Das alte Theater wurde 1944 zerstört." },
    ],
  },

  "infinitiv-mit-zu": {
    lesson: {
      slug: "infinitiv-mit-zu", level: "B1", category: CAT,
      titleDe: "Infinitiv mit zu", titleUk: "Інфінітив із zu",
      goal: "Правильно вживати конструкцію <i>zu + Infinitiv</i> після певних дієслів, іменників і прикметників.",
      explanation: [
        "Після багатьох дієслів, прикметників і виразів вживається <b>zu + Infinitiv</b>, який стоїть у кінці: <i>Ich versuche, Deutsch zu lernen.</i>",
        "Після <b>модальних</b>, <i>werden, sehen, hören, lassen, gehen, bleiben</i> вживається <b>чистий інфінітив</b> (без zu).",
        "Якщо дієслово <b>відокремлюване</b>, zu стоїть <b>між префіксом і основою</b>: <i>einzukaufen, anzurufen</i>.",
        "Часто перед zu-Inf. ставиться кома, якщо речення довге або є додаткові слова: <i>Ich habe vor, morgen ins Kino zu gehen.</i>",
      ],
      table: {
        headers: ["Уживається після", "Приклад"],
        rows: [
          ["versuchen, beginnen, vergessen", "Ich versuche, Deutsch zu lernen."],
          ["es ist + Adj.", "Es ist wichtig, viel zu üben."],
          ["haben + Lust/Zeit/Angst", "Ich habe keine Zeit, zu kommen."],
          ["vorhaben, planen", "Wir planen, nach Wien zu fahren."],
          ["aufhören, anfangen", "Hör auf zu rauchen!"],
        ],
      },
      examples: [
        { de: "Ich versuche, Deutsch zu lernen.", uk: "Я намагаюся вчити німецьку." },
        { de: "Es ist wichtig, jeden Tag zu üben.", uk: "Важливо вправлятися щодня." },
        { de: "Ich habe vor, morgen einzukaufen.", uk: "Я планую завтра закупитися." },
        { de: "Sie hat Angst, allein zu reisen.", uk: "Вона боїться подорожувати сама." },
        { de: "Wir planen, nach Wien zu fahren.", uk: "Ми плануємо поїхати до Відня." },
        { de: "Hör auf, so laut zu sprechen!", uk: "Перестань так голосно говорити!" },
        { de: "Es macht Spaß, mit Freunden zu kochen.", uk: "Готувати з друзями — задоволення." },
        { de: "Vergiss nicht, den Schlüssel mitzunehmen!", uk: "Не забудь узяти ключ!" },
      ],
      tip: "Відокремлювані: zu — <b>всередині</b>: <i>ein<u>zu</u>kaufen</i>, <i>auf<u>zu</u>stehen</i>, <i>an<u>zu</u>rufen</i>.",
      mistakes: [
        { wrong: "Ich versuche zu Deutsch lernen.", right: "Ich versuche, Deutsch zu lernen." },
        { wrong: "Ich habe vor zu einkaufen.", right: "Ich habe vor, einzukaufen." },
        { wrong: "Ich kann zu kommen.", right: "Ich kann kommen." },
      ],
      exercises: {}, prevSlug: "passiv-praeteritum", nextSlug: "um-zu",
    },
    extras: {
      duration: 18, premium: true,
      learningGoals: ["знати, коли потрібний zu, а коли — ні", "правильно ставити zu у відокремлюваних дієсловах", "будувати zu-Inf. після виразів і прикметників"],
      ruleBox: { rule: "<b>zu + Infinitiv</b> у кінці. Без zu — після Modalverben, werden, sehen, hören, lassen, gehen, bleiben. Відокремлювані: <b>префікс + zu + основа</b>." },
      ukrainianTips: ["Українське «що робити» — «X zu machen»: <i>важливо вчитися</i> → <i>es ist wichtig, zu lernen</i>."],
      languageComparison: {
        commons: ["Обидві мови мають інфінітивні звороти."],
        diffs: ["У німецькій zu стоїть <b>перед</b> інфінітивом і всередині відокремлюваних."],
        traps: ["Після модальних — без zu!"],
      },
      summary: ["zu + Inf. — у кінці.", "Modalverben → без zu.", "Trennbar: aufzustehen, einzukaufen.", "Часто з комою."],
    },
    exercises15: [
      { type: "mc", q: "Ich versuche, Deutsch ___ lernen.", options: ["—","zu","für","an"], correct: 1 },
      { type: "mc", q: "Ich kann ___ kommen.", options: ["zu","—","für","mit"], correct: 1, explain: "Після Modalverb — без zu." },
      { type: "gap", q: "Ich habe vor, morgen ___ (einkaufen).", answer: "einzukaufen" },
      { type: "gap", q: "Hör auf ___ rauchen!", answer: "zu" },
      { type: "gap", q: "Es ist wichtig, jeden Tag ___ üben.", answer: "zu" },
      { type: "gap", q: "Vergiss nicht, den Schlüssel ___ (mitnehmen).", answer: "mitzunehmen" },
      { type: "tf", q: "Після <i>können, müssen</i> треба zu.", correct: false },
      { type: "tf", q: "У відокремлюваних дієсловах <b>zu</b> стоїть між префіксом і основою.", correct: true },
      { type: "match", prompt: "Дієслово → форма з zu:", pairs: [
        { left: "einkaufen", right: "einzukaufen" }, { left: "aufstehen", right: "aufzustehen" },
        { left: "anrufen", right: "anzurufen" }, { left: "lernen", right: "zu lernen" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich kann zu kommen.", correct: ["Ich kann kommen."] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe vor zu einkaufen.", correct: ["Ich habe vor einzukaufen.","Ich habe vor, einzukaufen."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich versuche zu lernen.","Ich versuche lernen.","Ich muss arbeiten.","Ich muss zu arbeiten.","Es ist toll, zu reisen."], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["versuche","zu","ich","lernen","Deutsch"], correct: ["ich","versuche","Deutsch","zu","lernen"] },
      { type: "translate", prompt: "Переклади:", uk: "Я планую поїхати до Берліна.",
        de: ["Ich habe vor, nach Berlin zu fahren.","Ich plane, nach Berlin zu fahren."] },
      { type: "translate", prompt: "Переклади:", uk: "Не забудь зателефонувати мамі!",
        de: ["Vergiss nicht, deine Mutter anzurufen!","Vergiss nicht, die Mutter anzurufen!"] },
      { type: "writeFree", prompt: "Напиши 2 речення про свої плани з zu-Inf.",
        sample: "Ich habe vor, morgen früh aufzustehen. Es ist wichtig, jeden Tag etwas Neues zu lernen." },
    ],
  },

  "um-zu": {
    lesson: {
      slug: "um-zu", level: "B1", category: CAT,
      titleDe: "um … zu + Infinitiv", titleUk: "Конструкція um … zu",
      goal: "Виражати мету за допомогою <i>um … zu + Infinitiv</i> і знати, коли вживати <i>damit</i>.",
      explanation: [
        "<b>um … zu + Infinitiv</b> виражає мету («щоб»). Підмет головного й залежного речення — <b>той самий</b>: <i>Ich lerne Deutsch, um in Deutschland zu studieren.</i>",
        "Якщо підмети <b>різні</b>, замість um…zu — <b>damit</b> + Nebensatz: <i>Ich erkläre es, damit du es verstehst.</i>",
        "Як і інші zu-Infinitiv-структури, um…zu ставиться <b>в кінець</b> підрядного. Кома перед <i>um</i> обов'язкова.",
      ],
      table: {
        headers: ["Спосіб", "Приклад"],
        rows: [
          ["um … zu (той самий підмет)", "Ich lerne, um die Prüfung zu bestehen."],
          ["damit (різні підмети)", "Ich helfe dir, damit du Zeit hast."],
          ["для запитання Wozu?", "Wozu lernst du? — Um Karriere zu machen."],
        ],
      },
      examples: [
        { de: "Ich lerne Deutsch, um in Deutschland zu studieren.", uk: "Я вчу німецьку, щоб навчатися в Німеччині." },
        { de: "Wir sparen Geld, um ein Haus zu kaufen.", uk: "Ми збираємо гроші, щоб купити будинок." },
        { de: "Er trainiert hart, um fit zu bleiben.", uk: "Він тренується наполегливо, щоб бути у формі." },
        { de: "Sie steht früh auf, um pünktlich zu sein.", uk: "Вона рано встає, щоб бути вчасно." },
        { de: "Ich helfe dir, damit du fertig wirst.", uk: "Я допомагаю тобі, щоб ти впорався/-лась." },
        { de: "Wozu lernst du Deutsch? — Um in Wien zu arbeiten.", uk: "Навіщо ти вчиш німецьку? — Щоб працювати у Відні." },
        { de: "Sie geht zum Arzt, um sich untersuchen zu lassen.", uk: "Вона йде до лікаря, щоб оглянутися." },
        { de: "Wir reisen, um neue Länder kennenzulernen.", uk: "Ми подорожуємо, щоб знайомитися з новими країнами." },
      ],
      tip: "<b>Підмети однакові</b> → um…zu. <b>Різні</b> → damit.",
      mistakes: [
        { wrong: "Ich lerne Deutsch, um ich kann reisen.", right: "Ich lerne Deutsch, um reisen zu können." },
        { wrong: "Ich erkläre es um du verstehst.", right: "Ich erkläre es, damit du es verstehst." },
      ],
      exercises: {}, prevSlug: "infinitiv-mit-zu", nextSlug: "ohne-zu",
    },
    extras: {
      duration: 15, premium: true,
      learningGoals: ["виражати мету з um…zu", "відрізняти um…zu від damit", "правильно ставити zu у trennbare"],
      ruleBox: { rule: "<b>um + … + zu + Infinitiv</b> = мета (підмети однакові). <b>damit</b> = мета (підмети різні)." },
      ukrainianTips: ["Українське «щоб» = um…zu або damit — залежить від підмета."],
      languageComparison: {
        commons: ["Обидві мови виражають мету окремою конструкцією."],
        diffs: ["У німецькій um…zu — лише з одним підметом."],
        traps: ["Без коми перед um — помилка."],
      },
      summary: ["Підмет той самий → um…zu.", "Різні → damit + Nebensatz.", "Кома обов'язкова."],
    },
    exercises15: [
      { type: "mc", q: "Ich lerne Deutsch, ___ in Berlin zu studieren.", options: ["zu","um","damit","für"], correct: 1 },
      { type: "mc", q: "Ich erkläre es, ___ du es verstehst.", options: ["um","damit","zu","für"], correct: 1 },
      { type: "gap", q: "Wir sparen, ___ ein Haus ___ kaufen.", answer: "um zu", hint: "um … zu" },
      { type: "gap", q: "Sie steht früh auf, um pünktlich ___ sein.", answer: "zu" },
      { type: "tf", q: "um…zu вживається лише, коли підмет той самий.", correct: true },
      { type: "tf", q: "damit вимагає того самого підмета.", correct: false },
      { type: "match", prompt: "Підмети → конструкція:", pairs: [
        { left: "однакові", right: "um … zu" }, { left: "різні", right: "damit" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich lerne, um ich die Prüfung bestehe.",
        correct: ["Ich lerne, um die Prüfung zu bestehen."] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich helfe dir um du fertig wirst.",
        correct: ["Ich helfe dir, damit du fertig wirst."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Ich lerne, um zu reisen.","Ich lerne um reisen.","Ich helfe dir, damit du es schaffst.","Ich helfe dir, um du es schaffst."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["um","fit","trainiert","er","bleiben","zu"], correct: ["er","trainiert","um","fit","zu","bleiben"] },
      { type: "translate", prompt: "Переклади:", uk: "Я працюю, щоб заробляти гроші.",
        de: ["Ich arbeite, um Geld zu verdienen."] },
      { type: "translate", prompt: "Переклади (різні підмети):", uk: "Я говорю повільно, щоб ти зрозумів(ла).",
        de: ["Ich spreche langsam, damit du es verstehst.","Ich spreche langsam, damit du verstehst."] },
      { type: "writeFree", prompt: "Напиши 2 цілі з um…zu.",
        sample: "Ich lerne Deutsch, um in Österreich zu arbeiten. Ich treibe Sport, um gesund zu bleiben." },
      { type: "mc", q: "Wozu sparst du? — ___ ein Auto zu kaufen.", options: ["Damit","Um","Zu","Für"], correct: 1 },
    ],
  },

  "ohne-zu": {
    lesson: {
      slug: "ohne-zu", level: "B1", category: CAT,
      titleDe: "ohne … zu + Infinitiv", titleUk: "Конструкція ohne … zu",
      goal: "Виражати супутню обставину з відсутньою дією за допомогою <i>ohne … zu</i>.",
      explanation: [
        "<b>ohne … zu + Infinitiv</b> = «не роблячи чого-небудь», «без того, щоб». Підмет — <b>той самий</b>.",
        "Якщо підмет різний — <b>ohne dass</b>: <i>Er ging, ohne dass ich es merkte.</i>",
        "Ставимо в кінець, кома перед ohne — обов'язкова.",
      ],
      examples: [
        { de: "Er ging weg, ohne sich zu verabschieden.", uk: "Він пішов, не попрощавшись." },
        { de: "Sie antwortete, ohne nachzudenken.", uk: "Вона відповіла, не подумавши." },
        { de: "Ich fuhr ab, ohne den Schlüssel mitzunehmen.", uk: "Я поїхав(ла), не взявши ключ." },
        { de: "Er lernt Deutsch, ohne einen Kurs zu besuchen.", uk: "Він учить німецьку, не відвідуючи курсів." },
        { de: "Sie hat geholfen, ohne etwas zu sagen.", uk: "Вона допомогла, нічого не сказавши." },
        { de: "Wir aßen, ohne ein Wort zu sprechen.", uk: "Ми їли, не промовивши ні слова." },
        { de: "Sie kam ins Zimmer, ohne anzuklopfen.", uk: "Вона зайшла в кімнату, не постукавши." },
        { de: "Er ging weg, ohne dass jemand es bemerkte.", uk: "Він пішов так, що ніхто цього не помітив." },
      ],
      tip: "Той самий підмет → <b>ohne…zu</b>. Різні → <b>ohne dass</b>.",
      mistakes: [
        { wrong: "Er ging ohne sich verabschieden.", right: "Er ging, ohne sich zu verabschieden." },
        { wrong: "Sie antwortete ohne zu nachdenken.", right: "Sie antwortete, ohne nachzudenken." },
      ],
      exercises: {}, prevSlug: "um-zu", nextSlug: "statt-zu",
    },
    extras: {
      duration: 12, premium: true,
      learningGoals: ["будувати ohne…zu", "відрізняти ohne dass", "уживати у відокремлюваних дієсловах"],
      ruleBox: { rule: "<b>ohne + … + zu + Inf.</b> (той самий підмет). <b>ohne dass</b> — різні." },
      ukrainianTips: ["Українські дієприслівники «не зробивши, не сказавши» → ohne…zu."],
      languageComparison: { traps: ["Без коми перед ohne — помилка."], diffs: ["В укр. — дієприслівник, у нім. — інфінітивна конструкція."] },
      summary: ["ohne…zu — той самий підмет.", "ohne dass — різні підмети.", "zu всередині trennbar: anzuklopfen."],
    },
    exercises15: [
      { type: "mc", q: "Er ging, ___ sich zu verabschieden.", options: ["um","ohne","damit","statt"], correct: 1 },
      { type: "gap", q: "Sie antwortete, ohne ___ (nachdenken).", answer: "nachzudenken" },
      { type: "gap", q: "Er kam, ohne ___ (anklopfen).", answer: "anzuklopfen" },
      { type: "gap", q: "Wir aßen, ohne ein Wort ___ sprechen.", answer: "zu" },
      { type: "tf", q: "ohne…zu вимагає того самого підмета.", correct: true },
      { type: "tf", q: "Для різних підметів вживаємо <i>ohne dass</i>.", correct: true },
      { type: "match", prompt: "Підмети → конструкція:", pairs: [
        { left: "однакові", right: "ohne … zu" }, { left: "різні", right: "ohne dass" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Er ging ohne sich verabschieden.",
        correct: ["Er ging, ohne sich zu verabschieden."] },
      { type: "correct", prompt: "Виправ:", wrong: "Sie kam ins Zimmer ohne zu anklopfen.",
        correct: ["Sie kam ins Zimmer, ohne anzuklopfen."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Er ging, ohne zu fragen.","Er ging ohne fragen.","Sie kam, ohne anzurufen.","Sie kam, ohne anrufen zu."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["ohne","Wort","sagen","sie","ein","zu","ging"],
        correct: ["sie","ging","ohne","ein","Wort","zu","sagen"] },
      { type: "translate", prompt: "Переклади:", uk: "Він пішов, нічого не сказавши.",
        de: ["Er ging, ohne etwas zu sagen.","Er ging weg, ohne etwas zu sagen."] },
      { type: "translate", prompt: "Переклади:", uk: "Вона зайшла, не постукавши.",
        de: ["Sie kam herein, ohne anzuklopfen.","Sie kam ins Zimmer, ohne anzuklopfen."] },
      { type: "writeFree", prompt: "Напиши 2 речення з ohne…zu про повсякдення.",
        sample: "Ich verließ das Haus, ohne den Herd auszuschalten. Er antwortete mir, ohne mich anzusehen." },
      { type: "mc", q: "Er ging, ___ dass jemand es bemerkte.", options: ["um","ohne","statt","damit"], correct: 1 },
    ],
  },

  "statt-zu": {
    lesson: {
      slug: "statt-zu", level: "B1", category: CAT,
      titleDe: "statt … zu + Infinitiv", titleUk: "Конструкція statt … zu (anstatt … zu)",
      goal: "Виражати альтернативу/заміну однієї дії іншою за допомогою <i>statt … zu</i>.",
      explanation: [
        "<b>statt … zu + Infinitiv</b> (синонім: <i>anstatt … zu</i>) = «замість того, щоб». Підмет — той самий.",
        "При різних підметах — <b>statt dass</b>: <i>Statt dass er hilft, schaut er fern.</i>",
        "Як і інші zu-Inf., ставиться в кінець; кома перед statt — обов'язкова.",
      ],
      examples: [
        { de: "Statt zu lernen, schaute er fern.", uk: "Замість того, щоб учитися, він дивився телевізор." },
        { de: "Statt zu Hause zu bleiben, gingen wir ins Café.", uk: "Замість того, щоб лишатися вдома, ми пішли в кафе." },
        { de: "Anstatt zu arbeiten, surft er im Internet.", uk: "Замість того, щоб працювати, він сидить в інтернеті." },
        { de: "Sie aß einen Apfel, statt Schokolade zu essen.", uk: "Вона з'їла яблуко замість шоколаду." },
        { de: "Statt mich anzurufen, schrieb er eine E-Mail.", uk: "Замість того, щоб подзвонити мені, він написав email." },
        { de: "Wir fahren mit dem Rad, statt das Auto zu nehmen.", uk: "Ми їдемо велосипедом замість того, щоб брати машину." },
        { de: "Statt zu schlafen, las er bis spät.", uk: "Замість того, щоб спати, він читав допізна." },
        { de: "Statt dass er hilft, beschwert er sich.", uk: "Замість того, щоб допомагати, він скаржиться." },
      ],
      tip: "Той самий підмет → <b>statt…zu</b>. Різні → <b>statt dass</b>.",
      mistakes: [
        { wrong: "Statt lernen, er schaut fern.", right: "Statt zu lernen, schaute er fern." },
        { wrong: "Statt zu mich anrufen, schrieb er.", right: "Statt mich anzurufen, schrieb er." },
      ],
      exercises: {}, prevSlug: "ohne-zu", nextSlug: "reflexive-praep",
    },
    extras: {
      duration: 12, premium: true,
      learningGoals: ["будувати statt…zu", "вживати statt dass", "правильно ставити zu у trennbar"],
      ruleBox: { rule: "<b>statt + … + zu + Inf.</b> = «замість того, щоб». <b>statt dass</b> — різні підмети." },
      ukrainianTips: ["Українське «замість того, щоб» = <i>statt … zu</i>."],
      languageComparison: { commons: ["Обидві мови мають конструкцію заміни."], traps: ["Не плутати <b>statt</b> (sat) і <b>satt</b> (ситий)."] },
      summary: ["statt…zu — той самий підмет.", "statt dass — різні.", "Кома перед statt."],
    },
    exercises15: [
      { type: "mc", q: "___ zu lernen, schaute er fern.", options: ["Um","Statt","Ohne","Damit"], correct: 1 },
      { type: "gap", q: "Statt mich ___ (anrufen), schrieb er.", answer: "anzurufen" },
      { type: "gap", q: "Statt zu Hause ___ bleiben, gingen wir aus.", answer: "zu" },
      { type: "gap", q: "Wir fahren Rad, ___ das Auto zu nehmen.", answer: "statt" },
      { type: "tf", q: "statt…zu вимагає того самого підмета.", correct: true },
      { type: "tf", q: "<i>anstatt</i> — синонім <i>statt</i>.", correct: true },
      { type: "match", prompt: "Підмети → конструкція:", pairs: [
        { left: "однакові", right: "statt … zu" }, { left: "різні", right: "statt dass" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Statt lernen, er schaut fern.",
        correct: ["Statt zu lernen, schaute er fern.","Statt zu lernen, schaut er fern."] },
      { type: "correct", prompt: "Виправ:", wrong: "Statt zu mich anrufen, schrieb er.",
        correct: ["Statt mich anzurufen, schrieb er."] },
      { type: "multi", q: "Які речення правильні?", options: [
        "Statt zu arbeiten, surft er.","Statt arbeiten, er surft.","Statt zu helfen, schaut sie zu.","Statt helfen, sie schaut."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["statt","Schokolade","essen","sie","aß","Apfel","einen","zu"],
        correct: ["sie","aß","einen","Apfel","statt","Schokolade","zu","essen"] },
      { type: "translate", prompt: "Переклади:", uk: "Замість того, щоб працювати, він спить.",
        de: ["Statt zu arbeiten, schläft er.","Anstatt zu arbeiten, schläft er."] },
      { type: "translate", prompt: "Переклади:", uk: "Замість того, щоб подзвонити, він написав.",
        de: ["Statt anzurufen, schrieb er.","Anstatt anzurufen, schrieb er."] },
      { type: "writeFree", prompt: "Напиши 2 контрасти з statt…zu.",
        sample: "Statt fernzusehen, lese ich abends ein Buch. Statt mit dem Auto zu fahren, nehme ich oft das Fahrrad." },
      { type: "mc", q: "___ dass er hilft, beschwert er sich.", options: ["Um","Statt","Ohne","Damit"], correct: 1 },
    ],
  },

  "reflexive-praep": {
    lesson: {
      slug: "reflexive-praep", level: "B1", category: CAT,
      titleDe: "Reflexive Verben mit Präpositionen", titleUk: "Зворотні дієслова з прийменниками",
      goal: "Знати найважливіші зворотні дієслова зі сталими прийменниками й правильно їх вживати.",
      explanation: [
        "Багато зворотних дієслів мають <b>сталий прийменник</b>: <i>sich freuen <b>über/auf</b>, sich interessieren <b>für</b>, sich erinnern <b>an</b>, sich kümmern <b>um</b></i>.",
        "Зворотний займенник у Akk.: <b>mich, dich, sich, uns, euch, sich</b>. Деякі дієслова — у Dat.: <i>sich (Dat.) etwas vorstellen, sich (Dat.) etwas merken</i>.",
        "Як і з verb+prep, відмінок задає прийменник: <i>sich freuen über + Akk., sich erinnern an + Akk., sich beschäftigen mit + Dat.</i>",
      ],
      table: {
        headers: ["Дієслово", "Прийменник", "Відмінок"],
        rows: [
          ["sich freuen", "über / auf", "Akk."],
          ["sich interessieren", "für", "Akk."],
          ["sich erinnern", "an", "Akk."],
          ["sich kümmern", "um", "Akk."],
          ["sich beschäftigen", "mit", "Dat."],
          ["sich verlieben", "in", "Akk."],
          ["sich entscheiden", "für / gegen", "Akk."],
          ["sich ärgern", "über", "Akk."],
        ],
      },
      examples: [
        { de: "Ich freue mich über das Geschenk.", uk: "Я радію подарунку." },
        { de: "Ich freue mich auf das Wochenende.", uk: "Я з нетерпінням чекаю вихідних." },
        { de: "Sie interessiert sich für Kunst.", uk: "Вона цікавиться мистецтвом." },
        { de: "Erinnerst du dich an unsere Reise?", uk: "Ти пам'ятаєш нашу подорож?" },
        { de: "Er kümmert sich um die Kinder.", uk: "Він піклується про дітей." },
        { de: "Wir beschäftigen uns mit Sprachen.", uk: "Ми займаємося мовами." },
        { de: "Sie hat sich in ihn verliebt.", uk: "Вона закохалася в нього." },
        { de: "Ich ärgere mich über das Wetter.", uk: "Я серджуся через погоду." },
      ],
      tip: "Учи трикутником: <b>sich + verb + prep + Kasus</b>.",
      mistakes: [
        { wrong: "Ich interessiere mich an Musik.", right: "Ich interessiere mich für Musik." },
        { wrong: "Sie erinnert sich von der Reise.", right: "Sie erinnert sich an die Reise." },
      ],
      exercises: {}, prevSlug: "statt-zu", nextSlug: "lassen",
    },
    extras: {
      duration: 18, premium: true,
      learningGoals: ["знати найважливіші refl. verb + prep", "правильно вибирати prep і відмінок", "розрізняти über/auf при <i>sich freuen</i>"],
      ruleBox: { rule: "<b>sich + verb + prep + Kasus</b> — стала структура. <i>auf</i> = майбутнє, <i>über</i> = тепер/минуле." },
      ukrainianTips: ["Українське «цікавитися» — Instr., у нім. <i>für + Akk.</i>", "Українське «пам'ятати про» — Acc., у нім. <i>an + Akk.</i>"],
      languageComparison: { traps: ["Прийменники не збігаються — не перекладай дослівно."] },
      summary: ["sich freuen über/auf", "sich interessieren für", "sich erinnern an", "sich kümmern um", "sich beschäftigen mit"],
    },
    exercises15: [
      { type: "mc", q: "Ich interessiere mich ___ Musik.", options: ["an","für","auf","über"], correct: 1 },
      { type: "mc", q: "Sie freut sich ___ den Urlaub (наступного тижня).", options: ["über","auf","für","an"], correct: 1 },
      { type: "mc", q: "Er kümmert sich ___ die Kinder.", options: ["für","um","an","über"], correct: 1 },
      { type: "gap", q: "Erinnerst du ___ an unsere Reise?", answer: "dich" },
      { type: "gap", q: "Ich freue ___ über das Geschenk.", answer: "mich" },
      { type: "gap", q: "Wir beschäftigen uns ___ Sprachen.", answer: "mit" },
      { type: "gap", q: "Sie verliebt sich ___ ihn.", answer: "in" },
      { type: "tf", q: "<i>sich freuen über</i> = подія в майбутньому.", correct: false, explain: "über — тепер/минуле; auf — майбутнє." },
      { type: "tf", q: "<i>sich beschäftigen mit</i> вимагає Dativ.", correct: true },
      { type: "match", prompt: "Дієслово → прийменник:", pairs: [
        { left: "sich interessieren", right: "für" },
        { left: "sich erinnern", right: "an" },
        { left: "sich kümmern", right: "um" },
        { left: "sich beschäftigen", right: "mit" },
        { left: "sich verlieben", right: "in" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich interessiere mich an Musik.",
        correct: ["Ich interessiere mich für Musik."] },
      { type: "multi", q: "Виділи правильні речення:", options: [
        "Ich erinnere mich an die Reise.","Ich erinnere mich von der Reise.","Sie freut sich auf das Treffen.","Sie freut sich für das Treffen."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["interessiere","mich","ich","Kunst","für"], correct: ["ich","interessiere","mich","für","Kunst"] },
      { type: "translate", prompt: "Переклади:", uk: "Я серджуся через погоду.",
        de: ["Ich ärgere mich über das Wetter."] },
      { type: "writeFree", prompt: "Напиши 2 речення про свої інтереси з refl. verb + prep.",
        sample: "Ich interessiere mich für Geschichte und beschäftige mich oft mit alten Dokumenten. Außerdem freue ich mich auf den nächsten Urlaub in Wien." },
    ],
  },

  lassen: {
    lesson: {
      slug: "lassen", level: "B1", category: CAT,
      titleDe: "lassen", titleUk: "Дієслово lassen",
      goal: "Розрізняти три основні значення дієслова <i>lassen</i> і правильно його вживати.",
      explanation: [
        "Дієслово <b>lassen</b> має три основні значення: 1) <b>залишати</b> (etwas an einem Ort), 2) <b>дозволяти</b> (jemandem etwas erlauben), 3) <b>доручати/наказати</b> зробити щось (etwas machen lassen).",
        "Граматично як модальне: <b>lassen + Infinitiv</b> у кінці. У Perfekt: <i>habe … lassen</i> (Ersatzinfinitiv, а не gelassen).",
        "<i>sich lassen + Infinitiv</i> має <b>пасивне</b> значення (часто можливості): <i>Das lässt sich machen</i> = «Це можна зробити».",
        "Форми Präsens: <i>ich lasse, du lässt, er lässt, wir lassen, ihr lasst, sie lassen.</i> Präteritum: <i>ließ</i>. P II: <i>gelassen</i> або <i>lassen</i> (як Modalverb).",
      ],
      table: {
        headers: ["Значення", "Приклад", "Переклад"],
        rows: [
          ["залишати", "Ich lasse das Buch zu Hause.", "Я залишаю книгу вдома."],
          ["дозволяти", "Lass mich schlafen!", "Дай мені поспати!"],
          ["доручати", "Ich lasse das Auto reparieren.", "Я віддаю машину в ремонт."],
          ["sich lassen (пасив)", "Das lässt sich machen.", "Це можна зробити."],
        ],
      },
      examples: [
        { de: "Ich lasse die Tasche im Auto.", uk: "Я залишаю сумку в машині." },
        { de: "Lass mich in Ruhe!", uk: "Дай мені спокій!" },
        { de: "Ich lasse mir die Haare schneiden.", uk: "Я стрижуся (мене стрижуть)." },
        { de: "Sie lässt das Auto reparieren.", uk: "Вона віддає машину в ремонт." },
        { de: "Die Tür lässt sich nicht öffnen.", uk: "Двері не відчиняються." },
        { de: "Lass uns ins Kino gehen!", uk: "Ходімо в кіно!" },
        { de: "Er hat mich warten lassen.", uk: "Він змусив мене чекати." },
        { de: "Das Problem lässt sich lösen.", uk: "Проблему можна вирішити." },
      ],
      tip: "Perfekt: <b>habe + Inf. + lassen</b> (Ersatzinfinitiv), а не <i>gelassen</i>: <i>Ich habe das Auto reparieren <b>lassen</b>.</i>",
      mistakes: [
        { wrong: "Ich habe das Auto reparieren gelassen.", right: "Ich habe das Auto reparieren lassen." },
        { wrong: "Lass mich zu schlafen.", right: "Lass mich schlafen." },
      ],
      exercises: {}, prevSlug: "reflexive-praep",
    },
    extras: {
      duration: 18, premium: true,
      learningGoals: ["знати 3 значення lassen", "уживати sich lassen у пасивному значенні", "правильно утворювати Perfekt з Ersatzinfinitiv"],
      ruleBox: { rule: "<b>lassen + Infinitiv</b> у кінці. Perfekt → Ersatzinfinitiv: <i>habe … lassen</i>. <i>sich lassen + Inf.</i> = «можна»." },
      ukrainianTips: ["Українське «дати + інфінітив» (дай поспати) = lassen + Inf.", "«Можна зробити» → <i>lässt sich machen</i>."],
      languageComparison: { diffs: ["В укр. немає каузативу через одне дієслово."], traps: ["Perfekt без <i>gelassen</i> — <b>lassen</b>!"] },
      summary: ["залишити / дозволити / доручити.", "Perfekt: habe + Inf. + lassen.", "sich lassen + Inf. = можна."],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ mir die Haare schneiden.", options: ["lasse","lasst","lässt","lassen"], correct: 0 },
      { type: "mc", q: "Du ___ mich in Ruhe!", options: ["lassen","lässt","lasst","lass"], correct: 3, explain: "Imperativ 2.Sg.: Lass!" },
      { type: "gap", q: "Sie ___ das Auto reparieren. (lassen, sie Sg.)", answer: "lässt" },
      { type: "gap", q: "Ich habe das Auto reparieren ___. (lassen, P II)", answer: "lassen", hint: "Ersatzinfinitiv." },
      { type: "gap", q: "Das Problem ___ sich lösen.", answer: "lässt" },
      { type: "tf", q: "У Perfekt беремо <i>gelassen</i>, коли lassen — модальне.", correct: false },
      { type: "tf", q: "<i>sich lassen + Inf.</i> має пасивне значення (можливість).", correct: true },
      { type: "match", prompt: "Речення → значення:", pairs: [
        { left: "Ich lasse das Buch zu Hause.", right: "залишати" },
        { left: "Lass mich schlafen!", right: "дозволяти" },
        { left: "Ich lasse das Auto reparieren.", right: "доручати" },
        { left: "Das lässt sich machen.", right: "пасив (можна)" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe das Auto reparieren gelassen.",
        correct: ["Ich habe das Auto reparieren lassen."] },
      { type: "multi", q: "Виділи речення зі значенням «доручати»:", options: [
        "Ich lasse das Auto waschen.","Lass mich gehen!","Ich lasse das Buch hier.","Ich lasse mir einen Anzug machen."], correct: [0,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["lassen","ich","Auto","reparieren","das"], correct: ["ich","lasse","das","Auto","reparieren"] },
      { type: "translate", prompt: "Переклади:", uk: "Я залишаю гроші вдома.",
        de: ["Ich lasse das Geld zu Hause."] },
      { type: "translate", prompt: "Переклади:", uk: "Дай мені поспати!",
        de: ["Lass mich schlafen!"] },
      { type: "translate", prompt: "Переклади (пасив-можливість):", uk: "Ці двері не відчиняються.",
        de: ["Diese Tür lässt sich nicht öffnen.","Die Tür lässt sich nicht öffnen."] },
      { type: "writeFree", prompt: "Напиши 2 речення з lassen у різних значеннях.",
        sample: "Am Wochenende lasse ich mein Auto in der Werkstatt reparieren. Meine Eltern lassen mich oft alleine entscheiden." },
    ],
  },
};
