// B1 · Wortbildung — 9 повних уроків.
import type { B1Map } from "./_helpers";
const CAT = "Словотвір";

const baseExtras = (rule: string, tips: string[], summary: string[]) => ({
  duration: 14, premium: true, ruleBox: { rule }, ukrainianTips: tips, summary,
});

export const wortbildungB1: B1Map = {
  "nomen-suffixe": {
    lesson: {
      slug: "nomen-suffixe", level: "B1", category: CAT,
      titleDe: "Nomensuffixe — -ung, -heit, -keit, -schaft, -tum",
      titleUk: "Суфікси іменників",
      goal: "Розпізнавати й утворювати іменники за допомогою найважливіших суфіксів.",
      explanation: [
        "Суфікс задає <b>рід іменника</b> й часто значення.",
        "<b>-ung</b> (від дієслова) → дія/результат, <i>die</i>: <i>lösen → die Lösung</i>.",
        "<b>-heit / -keit</b> (від прикметника) → абстрактна якість, <i>die</i>: <i>frei → die Freiheit</i>, <i>möglich → die Möglichkeit</i>.",
        "<b>-schaft</b> → колектив, стан, <i>die</i>: <i>Freund → die Freundschaft</i>.",
        "<b>-tum</b> → стан, область, <i>das/der</i>: <i>das Eigentum, der Reichtum</i>.",
        "<b>-er</b> (від дієслова) → виконавець, <i>der</i>: <i>lehren → der Lehrer</i>.",
      ],
      table: {
        headers: ["Суфікс", "База", "Рід", "Приклад"],
        rows: [
          ["-ung", "Verb", "die", "die Lösung, die Übung, die Meinung"],
          ["-heit", "Adj.", "die", "die Freiheit, die Krankheit"],
          ["-keit", "Adj. (-ig, -lich, -bar)", "die", "die Möglichkeit, die Schwierigkeit"],
          ["-schaft", "Nomen/Adj.", "die", "die Freundschaft, die Mannschaft"],
          ["-tum", "—", "das/der", "das Eigentum, der Reichtum"],
          ["-er", "Verb", "der", "der Lehrer, der Sprecher"],
        ],
      },
      examples: [
        { de: "Die Lösung ist einfach.", uk: "Розв'язок простий." },
        { de: "Die Freiheit ist ein Grundrecht.", uk: "Свобода — основне право." },
        { de: "Die Möglichkeit existiert.", uk: "Можливість існує." },
        { de: "Unsere Freundschaft ist alt.", uk: "Наша дружба давня." },
        { de: "Das Eigentum gehört uns.", uk: "Власність належить нам." },
        { de: "Der Lehrer erklärt gut.", uk: "Учитель добре пояснює." },
        { de: "Die Übung macht den Meister.", uk: "Тренування робить майстра." },
        { de: "Die Schönheit liegt im Detail.", uk: "Краса — у деталях." },
      ],
      tip: "Усі іменники на <b>-ung, -heit, -keit, -schaft</b> — <b>die</b>. На <b>-er</b> від дієслова — <b>der</b>.",
      mistakes: [
        { wrong: "der Lösung", right: "die Lösung" },
        { wrong: "die Lehrer (im Sg.)", right: "der Lehrer" },
      ],
      exercises: {}, nextSlug: "verb-suffixe",
    },
    extras: baseExtras(
      "<b>-ung/-heit/-keit/-schaft → die</b>; <b>-tum → das/der</b>; <b>-er (Verb) → der</b>.",
      ["Українські «-ння, -ість, -ство» часто = -ung/-heit/-keit/-schaft."],
      ["-ung/-heit/-keit/-schaft = die.", "-tum = das/der.", "-er від дієслова = der."],
    ),
    exercises15: [
      { type: "mc", q: "Який рід у <i>Lösung</i>?", options: ["der","die","das","—"], correct: 1 },
      { type: "mc", q: "Який рід у <i>Freiheit</i>?", options: ["der","die","das","—"], correct: 1 },
      { type: "mc", q: "Який рід у <i>Eigentum</i>?", options: ["der","die","das","—"], correct: 2 },
      { type: "gap", q: "Іменник від <i>lösen</i> з -ung:", answer: "Lösung" },
      { type: "gap", q: "Іменник від <i>frei</i> з -heit:", answer: "Freiheit" },
      { type: "gap", q: "Іменник від <i>möglich</i> з -keit:", answer: "Möglichkeit" },
      { type: "gap", q: "Іменник від <i>Freund</i> з -schaft:", answer: "Freundschaft" },
      { type: "tf", q: "Усі іменники на -ung — жіночого роду.", correct: true },
      { type: "match", prompt: "База → іменник:", pairs: [
        { left: "lehren", right: "der Lehrer" },
        { left: "frei", right: "die Freiheit" },
        { left: "lösen", right: "die Lösung" },
        { left: "freund", right: "die Freundschaft" },
        { left: "möglich", right: "die Möglichkeit" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "der Lösung", correct: ["die Lösung"] },
      { type: "multi", q: "Які слова з суфіксами на -ung/-heit/-keit?",
        options: ["die Übung","der Sprecher","die Krankheit","das Eigentum","die Schwierigkeit"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "складність",
        de: ["die Schwierigkeit"] },
      { type: "translate", prompt: "Переклади:", uk: "багатство",
        de: ["der Reichtum"] },
      { type: "tf", q: "<i>-er</i> від дієслова часто означає виконавця дії.", correct: true },
      { type: "writeFree", prompt: "Утвори 3 іменники з різними суфіксами.",
        sample: "die Übung (від üben), die Sicherheit (від sicher), die Mannschaft (від Mann)." },
    ],
  },

  "verb-suffixe": {
    lesson: {
      slug: "verb-suffixe", level: "B1", category: CAT,
      titleDe: "Verbsuffixe — -ieren, -eln, -igen",
      titleUk: "Утворення дієслів",
      goal: "Утворювати й розпізнавати дієслова з типовими суфіксами.",
      explanation: [
        "<b>-ieren</b> — інтернаціональні дієслова (з латини/грецької/англ.): <i>studieren, telefonieren, fotografieren, organisieren</i>. У Perfekt — <b>без ge-</b>: <i>studiert</i>.",
        "<b>-eln</b> — часто «маленька / повторювана» дія: <i>lächeln, klingeln, sammeln, basteln</i>. У ich-формі часто випадає -e-: <i>ich sammle</i>.",
        "<b>-igen</b> — утворюють дієслова від прикметників/іменників: <i>reinigen (rein), beschäftigen (Beschäftigung), beruhigen</i>.",
      ],
      table: {
        headers: ["Суфікс", "Приклад", "Особливість"],
        rows: [
          ["-ieren", "studieren", "Perfekt без ge-: studiert"],
          ["-eln", "lächeln", "ich lächle (без -e-)"],
          ["-igen", "beruhigen", "часто від Adj./Nomen"],
        ],
      },
      examples: [
        { de: "Ich studiere an der Uni.", uk: "Я навчаюся в універі." },
        { de: "Sie telefoniert oft.", uk: "Вона часто розмовляє телефоном." },
        { de: "Er lächelt freundlich.", uk: "Він дружньо посміхається." },
        { de: "Das Telefon klingelt.", uk: "Телефон дзвонить." },
        { de: "Sie reinigt die Wohnung.", uk: "Вона прибирає квартиру." },
        { de: "Ich sammle Briefmarken.", uk: "Я колекціоную марки." },
        { de: "Beruhig dich!", uk: "Заспокойся!" },
        { de: "Ich habe gestern lange telefoniert.", uk: "Я вчора довго телефонував(ла)." },
      ],
      tip: "Дієслова на <b>-ieren</b> у Perfekt — <b>без ge-</b>: <i>studiert, telefoniert</i>.",
      mistakes: [
        { wrong: "Ich habe gestudiert.", right: "Ich habe studiert." },
        { wrong: "ich sammele", right: "ich sammle" },
      ],
      exercises: {}, prevSlug: "nomen-suffixe", nextSlug: "adjektiv-suffixe",
    },
    extras: baseExtras(
      "<b>-ieren</b> (Perfekt без ge-), <b>-eln</b> (ich-форма без -e-), <b>-igen</b> (від Adj./Nomen).",
      ["Українське «-увати» часто = -ieren.", "Звуження -eln у 1 особі: sammle, lächle."],
      ["-ieren: без ge- у Perfekt.", "-eln: ich-форма без -e-.", "-igen: від основ."],
    ),
    exercises15: [
      { type: "mc", q: "Partizip II від <i>studieren</i>:",
        options: ["gestudiert","studiert","studieren","gestudieren"], correct: 1 },
      { type: "mc", q: "Форма 1 ос. одн. від <i>sammeln</i>:",
        options: ["ich sammele","ich sammle","ich samme","ich sammel"], correct: 1 },
      { type: "gap", q: "Сила «робити чистим» (-igen): rein → ___", answer: "reinigen" },
      { type: "gap", q: "P II від telefonieren:", answer: "telefoniert" },
      { type: "tf", q: "Дієслова на -ieren мають ge- у Perfekt.", correct: false },
      { type: "tf", q: "У дієсловах на -eln у формі ich -e- зазвичай випадає.", correct: true },
      { type: "match", prompt: "Дієслово → P II:", pairs: [
        { left: "studieren", right: "studiert" },
        { left: "lächeln", right: "gelächelt" },
        { left: "reinigen", right: "gereinigt" },
        { left: "klingeln", right: "geklingelt" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe gestudiert.",
        correct: ["Ich habe studiert."] },
      { type: "correct", prompt: "Виправ:", wrong: "ich sammele Briefmarken",
        correct: ["ich sammle Briefmarken"] },
      { type: "multi", q: "Які дієслова закінчуються на -ieren?",
        options: ["studieren","sammeln","fotografieren","reinigen","organisieren"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "Я фотографую людей.",
        de: ["Ich fotografiere Menschen."] },
      { type: "translate", prompt: "Переклади:", uk: "Я колекціоную марки.",
        de: ["Ich sammle Briefmarken."] },
      { type: "translate", prompt: "Переклади:", uk: "Заспокойся!", de: ["Beruhig dich!","Beruhige dich!"] },
      { type: "gap", q: "Sie ___ am Telefon. (klingeln, 3 Sg.)", answer: "klingelt" },
      { type: "writeFree", prompt: "Утвори 3 речення з дієсловами на -ieren / -eln / -igen.",
        sample: "Ich studiere Informatik in Wien. Mein Sohn lächelt, wenn er Musik hört. Wir reinigen das Auto jeden Samstag." },
    ],
  },

  "adjektiv-suffixe": {
    lesson: {
      slug: "adjektiv-suffixe", level: "B1", category: CAT,
      titleDe: "Adjektivsuffixe — -ig, -lich, -isch, -bar, -los, -voll",
      titleUk: "Суфікси прикметників",
      goal: "Утворювати прикметники з типовими суфіксами й розуміти їхнє значення.",
      explanation: [
        "<b>-ig</b> — наявність якості: <i>sonn-ig, ruh-ig</i>.",
        "<b>-lich</b> — належність/характер: <i>freund-lich, monatlich</i>.",
        "<b>-isch</b> — походження/належність: <i>englisch, kindisch</i>.",
        "<b>-bar</b> (від дієслова) — «можливий»: <i>essbar, lesbar, machbar</i>.",
        "<b>-los</b> — відсутність: <i>arbeitslos, hilflos, sinnlos</i>.",
        "<b>-voll</b> — повнота: <i>liebevoll, sinnvoll, wertvoll</i>.",
      ],
      table: {
        headers: ["Суфікс", "Значення", "Приклад"],
        rows: [
          ["-ig", "наявність", "sonnig, ruhig"],
          ["-lich", "характер", "freundlich, monatlich"],
          ["-isch", "походження", "englisch, kindisch"],
          ["-bar", "можливо (від Verb)", "essbar, lesbar"],
          ["-los", "без…", "arbeitslos, hilflos"],
          ["-voll", "повний", "wertvoll, liebevoll"],
        ],
      },
      examples: [
        { de: "Heute ist es sonnig.", uk: "Сьогодні сонячно." },
        { de: "Er ist sehr freundlich.", uk: "Він дуже привітний." },
        { de: "Sie spricht englisch.", uk: "Вона розмовляє англійською." },
        { de: "Diese Pilze sind essbar.", uk: "Ці гриби їстівні." },
        { de: "Er ist seit Jahren arbeitslos.", uk: "Він уже роками безробітний." },
        { de: "Das war ein wertvoller Tipp.", uk: "Це була цінна порада." },
        { de: "Die Antwort war sinnlos.", uk: "Відповідь була безглуздою." },
        { de: "Eine liebevolle Mutter.", uk: "Любляча мама." },
      ],
      tip: "<b>-bar</b> = «можливо зробити»: <i>essbar = можна їсти</i>. <b>-los</b> = «без…», <b>-voll</b> = «повний…».",
      mistakes: [
        { wrong: "Diese Pilze sind essen.", right: "Diese Pilze sind essbar." },
        { wrong: "Er ist hilfslos.", right: "Er ist hilflos." },
      ],
      exercises: {}, prevSlug: "verb-suffixe", nextSlug: "untrennbare-praefixe",
    },
    extras: baseExtras(
      "<b>-ig/-lich/-isch/-bar/-los/-voll</b> — найчастіші суфікси прикметників.",
      ["Українське «-ний/-ський» часто = -ig/-lich/-isch.", "<i>essbar</i> = «їстівний», аналог укр. -ний."],
      ["6 суфіксів: -ig, -lich, -isch, -bar, -los, -voll."],
    ),
    exercises15: [
      { type: "mc", q: "Прикметник від <i>Sonne</i>:",
        options: ["sonnen","sonnig","sönnlich","sonnvoll"], correct: 1 },
      { type: "mc", q: "Прикметник від <i>Wert</i> (зі значенням «цінний»):",
        options: ["wertig","wertlos","wertvoll","wertbar"], correct: 2 },
      { type: "gap", q: "Прикметник від <i>essen</i> зі значенням «можна їсти»:", answer: "essbar" },
      { type: "gap", q: "Прикметник від <i>Arbeit</i> зі значенням «без роботи»:", answer: "arbeitslos" },
      { type: "tf", q: "Суфікс -bar утворює прикметники від дієслів.", correct: true },
      { type: "tf", q: "-los означає «дуже багато».", correct: false },
      { type: "match", prompt: "Прикметник → значення:", pairs: [
        { left: "essbar", right: "можна їсти" },
        { left: "hilflos", right: "без допомоги" },
        { left: "wertvoll", right: "цінний" },
        { left: "freundlich", right: "привітний" },
        { left: "englisch", right: "англійський" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "hilfslos", correct: ["hilflos"] },
      { type: "multi", q: "Які прикметники мають -bar?",
        options: ["essbar","hilflos","lesbar","sinnvoll","machbar"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "цінний", de: ["wertvoll"] },
      { type: "translate", prompt: "Переклади:", uk: "беззмістовний", de: ["sinnlos"] },
      { type: "translate", prompt: "Переклади:", uk: "щомісячний", de: ["monatlich"] },
      { type: "gap", q: "Слово «безсилий» → ___los", answer: "kraft" },
      { type: "writeFree", prompt: "Утвори 3 прикметники з різними суфіксами.",
        sample: "Das Wetter ist sonnig. Diese Aufgabe ist machbar. Der Lehrer ist sehr geduldig und freundlich." },
    ],
  },

  "untrennbare-praefixe": {
    lesson: {
      slug: "untrennbare-praefixe", level: "B1", category: CAT,
      titleDe: "Untrennbare Präfixe — be-, ge-, er-, ver-, zer-, ent-, miss-",
      titleUk: "Невідокремлювані префікси",
      goal: "Розпізнавати невідокремлювані префікси й знати їхні типові значення.",
      explanation: [
        "<b>Невідокремлювані префікси</b> завжди залишаються при дієслові й <b>не мають наголосу</b>. У Perfekt — <b>без ge-</b>: <i>besucht, verstanden, erklärt</i>.",
        "Найважливіші: <b>be-, ge-, er-, ver-, zer-, ent-, miss-</b>.",
        "Значення (приблизно): <b>be-</b> — спрямованість на об'єкт (besuchen, bekommen), <b>er-</b> — досягнення/початок (erreichen, erkennen), <b>ver-</b> — зміна/помилка (verstehen, verlieren), <b>zer-</b> — руйнування (zerbrechen), <b>ent-</b> — позбавлення/початок (entfernen, entstehen), <b>miss-</b> — невдача (misslingen, missverstehen).",
      ],
      table: {
        headers: ["Префікс", "Значення", "Приклад"],
        rows: [
          ["be-", "об'єкт стає в Akk.", "besuchen, bekommen"],
          ["ge-", "стале", "gehören, gefallen"],
          ["er-", "досягнення / початок", "erkennen, erreichen"],
          ["ver-", "зміна / помилка", "verstehen, verlieren"],
          ["zer-", "руйнування", "zerbrechen, zerstören"],
          ["ent-", "позбавлення / початок", "entfernen, entstehen"],
          ["miss-", "невдача", "misslingen, missverstehen"],
        ],
      },
      examples: [
        { de: "Ich besuche meine Oma.", uk: "Я відвідую бабусю." },
        { de: "Er hat das Buch bekommen.", uk: "Він отримав книгу." },
        { de: "Sie hat alles verstanden.", uk: "Вона все зрозуміла." },
        { de: "Wir haben den Schlüssel verloren.", uk: "Ми загубили ключ." },
        { de: "Das Glas ist zerbrochen.", uk: "Склянка розбита." },
        { de: "Ich habe das Problem erkannt.", uk: "Я розпізнав проблему." },
        { de: "Wir sind angekommen.", uk: "Ми приїхали." },
        { de: "Er hat mich missverstanden.", uk: "Він мене неправильно зрозумів." },
      ],
      tip: "Невідокремлювані: <b>немає ge-</b> у Perfekt і немає наголосу на префіксі.",
      mistakes: [
        { wrong: "Ich habe gebesucht.", right: "Ich habe besucht." },
        { wrong: "Er hat versteht.", right: "Er hat verstanden." },
      ],
      exercises: {}, prevSlug: "adjektiv-suffixe", nextSlug: "trennbare-praefixe-b1",
    },
    extras: baseExtras(
      "Не відокремлюються, <b>без ge-</b> у Perfekt, <b>без наголосу</b>.",
      ["Українські відповідники часто з префіксами «при-, від-, з-».", "У <i>verstehen</i> наголос на <i>steh-</i>, не на <i>ver-</i>."],
      ["be/ge/er/ver/zer/ent/miss.", "Без ge- у P II.", "Не відокремлюються в Hauptsatz."],
    ),
    exercises15: [
      { type: "mc", q: "P II від <i>besuchen</i>:",
        options: ["gebesucht","besucht","besuchen","gebesuchen"], correct: 1 },
      { type: "mc", q: "P II від <i>verstehen</i>:",
        options: ["gestanden","verstanden","verstand","versteht"], correct: 1 },
      { type: "gap", q: "P II від <i>erklären</i>:", answer: "erklärt" },
      { type: "gap", q: "P II від <i>zerstören</i>:", answer: "zerstört" },
      { type: "tf", q: "Невідокремлювані префікси у Perfekt мають ge-.", correct: false },
      { type: "tf", q: "<i>miss-</i> часто має значення «невдача».", correct: true },
      { type: "match", prompt: "Префікс → значення:", pairs: [
        { left: "be-", right: "спрямованість на об'єкт" },
        { left: "er-", right: "досягнення" },
        { left: "ver-", right: "зміна" },
        { left: "zer-", right: "руйнування" },
        { left: "miss-", right: "невдача" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe gebesucht.",
        correct: ["Ich habe besucht."] },
      { type: "multi", q: "Які дієслова з невідокремлюваним префіксом?",
        options: ["besuchen","aufstehen","verstehen","einkaufen","erkennen","ankommen"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "Я зрозумів(ла) все.",
        de: ["Ich habe alles verstanden."] },
      { type: "translate", prompt: "Переклади:", uk: "Ми загубили ключ.",
        de: ["Wir haben den Schlüssel verloren."] },
      { type: "gap", q: "Vase ist zer___. (від zerbrechen)", answer: "brochen" },
      { type: "tf", q: "<i>verstehen</i> має наголос на ver-.", correct: false },
      { type: "writeFree", prompt: "Утвори 3 речення з невідокремлюваними префіксами.",
        sample: "Ich besuche jeden Sonntag meine Großeltern. Wir haben den Bus verpasst. Er hat seinen Schlüssel zerbrochen." },
    ],
  },

  "trennbare-praefixe-b1": {
    lesson: {
      slug: "trennbare-praefixe-b1", level: "B1", category: CAT,
      titleDe: "Trennbare Präfixe", titleUk: "Відокремлювані префікси",
      goal: "Уживати найважливіші відокремлювані префікси й розуміти, де префікс стоїть у різних типах речень.",
      explanation: [
        "<b>Відокремлювані префікси</b> мають <b>наголос</b>. У Präsens/Präteritum у головному реченні префікс <b>відокремлюється і йде в кінець</b>: <i>Ich stehe um 7 auf.</i>",
        "У підрядному з дієсловом у кінці префікс <b>не відокремлюється</b>: <i>…, weil ich um 7 aufstehe.</i>",
        "У Perfekt префікс <b>зливається</b> з Partizip II через <b>ge-</b>: <i>auf-ge-standen</i>, <i>ein-ge-kauft</i>.",
        "З <b>zu + Infinitiv</b>: <b>префікс + zu + основа</b>: <i>aufzustehen, einzukaufen</i>.",
        "Найчастіші: <b>auf-, an-, aus-, ein-, mit-, vor-, zu-, weg-, ab-, los-, hin-/her-</b>.",
      ],
      table: {
        headers: ["Структура", "Приклад"],
        rows: [
          ["Hauptsatz Präsens", "Ich stehe um 7 auf."],
          ["Nebensatz", "…, weil ich um 7 aufstehe."],
          ["Perfekt", "Ich bin um 7 aufgestanden."],
          ["zu + Inf.", "Ich versuche, früh aufzustehen."],
        ],
      },
      examples: [
        { de: "Ich stehe um 7 auf.", uk: "Я встаю о 7." },
        { de: "Wir kaufen im Supermarkt ein.", uk: "Ми робимо закупи в супермаркеті." },
        { de: "Ruf mich morgen an!", uk: "Подзвони мені завтра!" },
        { de: "Sie nimmt das Geschenk mit.", uk: "Вона бере подарунок із собою." },
        { de: "Er ist gestern angekommen.", uk: "Він приїхав учора." },
        { de: "Bitte mach die Tür zu.", uk: "Будь ласка, зачини двері." },
        { de: "Wir bereiten das Essen vor.", uk: "Ми готуємо їжу заздалегідь." },
        { de: "Ich habe vor, früh aufzustehen.", uk: "Я планую рано встати." },
      ],
      tip: "<b>Hauptsatz</b>: префікс у кінець. <b>Nebensatz / zu-Inf. / Perfekt</b>: префікс <b>злиплий</b>.",
      mistakes: [
        { wrong: "Ich aufstehe um 7.", right: "Ich stehe um 7 auf." },
        { wrong: "Ich habe aufgestand.", right: "Ich bin aufgestanden." },
      ],
      exercises: {}, prevSlug: "untrennbare-praefixe", nextSlug: "negationspraefixe",
    },
    extras: baseExtras(
      "Hauptsatz → префікс у кінець. Nebensatz/Perfekt/zu-Inf. → разом.",
      ["Українські «при-, ви-, до-, з-» — часто = відокремлювані префікси."],
      ["Відокремлюваний = наголос.", "Hauptsatz: на кінець.", "Perfekt: -ge- усередині."],
    ),
    exercises15: [
      { type: "mc", q: "Ich ___ um 7 ___. (aufstehen)",
        options: ["stehe…auf","aufstehe…—","auf…stehe","stehe auf…—"], correct: 0 },
      { type: "mc", q: "P II від <i>einkaufen</i>:",
        options: ["eingekauft","einkauft","gekauft ein","einkauft ge-"], correct: 0 },
      { type: "gap", q: "Ich rufe dich morgen ___. (anrufen)", answer: "an" },
      { type: "gap", q: "Перетвори у zu-Inf.: einkaufen → ___", answer: "einzukaufen" },
      { type: "gap", q: "Sie nimmt das Geschenk ___. (mitnehmen)", answer: "mit" },
      { type: "tf", q: "У Nebensatz префікс відокремлюється.", correct: false },
      { type: "tf", q: "У Perfekt -ge- стоїть між префіксом і основою.", correct: true },
      { type: "match", prompt: "Дієслово → P II:", pairs: [
        { left: "aufstehen", right: "aufgestanden" },
        { left: "einkaufen", right: "eingekauft" },
        { left: "anrufen", right: "angerufen" },
        { left: "mitnehmen", right: "mitgenommen" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich aufstehe um 7.",
        correct: ["Ich stehe um 7 auf."] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe aufgestand.",
        correct: ["Ich bin aufgestanden."] },
      { type: "multi", q: "Які дієслова — відокремлювані?",
        options: ["aufstehen","verstehen","einkaufen","besuchen","mitnehmen"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["um","auf","stehe","7","ich"], correct: ["ich","stehe","um","7","auf"] },
      { type: "translate", prompt: "Переклади:", uk: "Подзвони мені завтра!",
        de: ["Ruf mich morgen an!","Ruf mich bitte morgen an!"] },
      { type: "translate", prompt: "Переклади у Perfekt:", uk: "Ми вчора закупилися.",
        de: ["Wir haben gestern eingekauft.","Gestern haben wir eingekauft."] },
      { type: "writeFree", prompt: "Напиши 2 речення з відокремлюваними префіксами в Präsens і Perfekt.",
        sample: "Ich stehe jeden Morgen um 6 Uhr auf. Gestern bin ich um 5 Uhr aufgestanden und habe schon viel erledigt." },
    ],
  },

  "negationspraefixe": {
    lesson: {
      slug: "negationspraefixe", level: "B1", category: CAT,
      titleDe: "Negationspräfixe — un-, miss-, in-/il-/ir-, non-",
      titleUk: "Префікси заперечення",
      goal: "Утворювати слова з протилежним значенням за допомогою префіксів заперечення.",
      explanation: [
        "<b>un-</b> — найчастіший префікс заперечення прикметників і дієприкметників: <i>glücklich → unglücklich, freundlich → unfreundlich, sichtbar → unsichtbar</i>.",
        "<b>miss-</b> — невдалий результат, неправильність: <i>verstehen → missverstehen, Erfolg → Misserfolg</i>.",
        "<b>in-/il-/im-/ir-</b> — у запозичених словах: <i>international ↔ inkorrekt, illegal, immoralisch, irrelevant</i>.",
        "<b>non-</b> — рідко, переважно у спеціальній/науковій лексиці: <i>nonverbal, Nonstop</i>.",
      ],
      table: {
        headers: ["Префікс", "База", "Приклад"],
        rows: [
          ["un-", "Adj./Partizip", "unglücklich, unmöglich"],
          ["miss-", "Verb/Nomen", "missverstehen, Misserfolg"],
          ["in- / il-", "запозичення", "inkorrekt, illegal"],
          ["im- / ir-", "запозичення", "immoralisch, irrelevant"],
          ["non-", "запозичення", "nonverbal"],
        ],
      },
      examples: [
        { de: "Er war unglücklich.", uk: "Він був нещасливий." },
        { de: "Das ist unmöglich.", uk: "Це неможливо." },
        { de: "Es war ein großer Misserfolg.", uk: "Це був великий провал." },
        { de: "Du hast mich missverstanden.", uk: "Ти мене неправильно зрозумів(ла)." },
        { de: "Diese Information ist irrelevant.", uk: "Ця інформація нерелевантна." },
        { de: "Sein Verhalten war unfreundlich.", uk: "Його поведінка була непривітною." },
        { de: "Das ist illegal.", uk: "Це нелегально." },
        { de: "Nonverbale Kommunikation ist wichtig.", uk: "Невербальна комунікація важлива." },
      ],
      tip: "<b>un-</b> — для більшості німецьких прикметників. <b>in-/il-/im-/ir-</b> — для запозичень.",
      mistakes: [
        { wrong: "inglücklich", right: "unglücklich" },
        { wrong: "unkorrekt", right: "inkorrekt" },
      ],
      exercises: {}, prevSlug: "trennbare-praefixe-b1", nextSlug: "komposita-nomen",
    },
    extras: baseExtras(
      "<b>un-</b>: німецькі основи. <b>in-/il-/im-/ir-</b>: запозичені. <b>miss-</b>: невдача.",
      ["Українські «не-/без-» часто = un-.", "Префікс <i>in-</i> асимілюється: il- (l), im- (m, p), ir- (r)."],
      ["un- стандарт.", "in-/il-/im-/ir- для запозичень.", "miss- = невдача."],
    ),
    exercises15: [
      { type: "mc", q: "Заперечення від <i>glücklich</i>:",
        options: ["inglücklich","unglücklich","missglücklich","ilglücklich"], correct: 1 },
      { type: "mc", q: "Заперечення від <i>korrekt</i>:",
        options: ["unkorrekt","inkorrekt","misskorrekt","ilkorrekt"], correct: 1 },
      { type: "gap", q: "Заперечення від <i>legal</i>:", answer: "illegal" },
      { type: "gap", q: "Заперечення від <i>relevant</i>:", answer: "irrelevant" },
      { type: "tf", q: "<i>un-</i> вживається з німецькими основами.", correct: true },
      { type: "tf", q: "<i>miss-</i> означає «успішно».", correct: false },
      { type: "match", prompt: "База → заперечення:", pairs: [
        { left: "möglich", right: "unmöglich" }, { left: "moralisch", right: "immoralisch" },
        { left: "relevant", right: "irrelevant" }, { left: "Erfolg", right: "Misserfolg" },
        { left: "legal", right: "illegal" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "inglücklich", correct: ["unglücklich"] },
      { type: "correct", prompt: "Виправ:", wrong: "unkorrekt", correct: ["inkorrekt"] },
      { type: "multi", q: "Які слова з <i>un-</i>?",
        options: ["unmöglich","inkorrekt","unfreundlich","illegal","unsichtbar"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "Це неможливо.", de: ["Das ist unmöglich."] },
      { type: "translate", prompt: "Переклади:", uk: "Це нелегально.", de: ["Das ist illegal."] },
      { type: "translate", prompt: "Переклади:", uk: "Ти мене неправильно зрозумів(ла).",
        de: ["Du hast mich missverstanden."] },
      { type: "tf", q: "<i>il-</i> стоїть перед основою на <b>l</b>.", correct: true },
      { type: "writeFree", prompt: "Утвори 3 слова з різними префіксами заперечення.",
        sample: "Diese Antwort ist irrelevant. Sein Plan war unmöglich. Ich habe ihn missverstanden." },
    ],
  },

  "komposita-nomen": {
    lesson: {
      slug: "komposita-nomen", level: "B1", category: CAT,
      titleDe: "Nomenkomposita", titleUk: "Складні іменники",
      goal: "Утворювати й розуміти німецькі складні іменники (Komposita).",
      explanation: [
        "Німецька любить <b>складні іменники</b>: <i>Haustür, Schreibtisch, Sommerferien</i>.",
        "<b>Останнє слово</b> визначає <b>рід і число</b>: <i>der Tisch → der Schreibtisch, die Tür → die Haustür</i>.",
        "Перший компонент може бути <b>іменником, дієсловом, прикметником</b>: <i>Schwimm-bad, Hoch-haus, Auto-bahn</i>.",
        "Часто між компонентами стоїть <b>з'єднувальний елемент</b> (Fugenelement): -s-, -n-, -en-, -es-, -er-.",
      ],
      table: {
        headers: ["Складене", "Перший + останній", "Рід"],
        rows: [
          ["Haustür", "Haus + Tür", "die"],
          ["Schreibtisch", "schreib + Tisch", "der"],
          ["Sommerferien", "Sommer + Ferien", "die (Pl.)"],
          ["Geburtstag", "Geburt + s + Tag", "der"],
          ["Familienname", "Familie + n + Name", "der"],
          ["Kinderzimmer", "Kinder + Zimmer", "das"],
        ],
      },
      examples: [
        { de: "Der Schreibtisch ist neu.", uk: "Письмовий стіл новий." },
        { de: "Die Haustür ist offen.", uk: "Вхідні двері відчинені." },
        { de: "Wann ist dein Geburtstag?", uk: "Коли в тебе день народження?" },
        { de: "Die Sommerferien beginnen bald.", uk: "Літні канікули скоро починаються." },
        { de: "Das Kinderzimmer ist klein.", uk: "Дитяча кімната маленька." },
        { de: "Wie ist Ihr Familienname?", uk: "Як Ваше прізвище?" },
        { de: "Das Hochhaus hat 30 Stockwerke.", uk: "У висотці 30 поверхів." },
        { de: "Die Autobahn ist gesperrt.", uk: "Автобан перекрито." },
      ],
      tip: "Рід складного іменника = рід <b>останнього</b> компонента.",
      mistakes: [
        { wrong: "die Schreibtisch", right: "der Schreibtisch" },
        { wrong: "Familiename", right: "Familienname" },
      ],
      exercises: {}, prevSlug: "negationspraefixe", nextSlug: "komposita-fugen",
    },
    extras: baseExtras(
      "Komposita: рід = рід <b>останнього</b> слова. Часто з'єднувальний елемент.",
      ["В укр. — два слова або через дефіс; у нім. — одне довге слово.", "Не бійся довжини: <i>Donaudampfschifffahrtsgesellschaft</i>."],
      ["Рід — за останнім словом.", "З'єднувальні: -s-, -n-, -en-, -er-.", "Перше слово може бути будь-якою частиною мови."],
    ),
    exercises15: [
      { type: "mc", q: "Який рід у <i>Schreibtisch</i>?", options: ["der","die","das","—"], correct: 0 },
      { type: "mc", q: "Який рід у <i>Haustür</i>?", options: ["der","die","das","—"], correct: 1 },
      { type: "mc", q: "Який рід у <i>Kinderzimmer</i>?", options: ["der","die","das","—"], correct: 2 },
      { type: "gap", q: "<i>Geburt + … + Tag</i>:", answer: "s" },
      { type: "gap", q: "<i>Familie + … + Name</i>:", answer: "n" },
      { type: "tf", q: "Рід складного іменника визначає перше слово.", correct: false },
      { type: "tf", q: "Між компонентами може бути -s-, -n-, -en- тощо.", correct: true },
      { type: "match", prompt: "Слова → Kompositum:", pairs: [
        { left: "Haus + Tür", right: "die Haustür" },
        { left: "schreiben + Tisch", right: "der Schreibtisch" },
        { left: "Sommer + Ferien", right: "die Sommerferien" },
        { left: "Kind + Zimmer", right: "das Kinderzimmer" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "die Schreibtisch", correct: ["der Schreibtisch"] },
      { type: "correct", prompt: "Виправ:", wrong: "Familiename", correct: ["Familienname"] },
      { type: "multi", q: "Які слова — Komposita?",
        options: ["Haustür","Tisch","Schreibtisch","Auto","Autobahn"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "день народження", de: ["Geburtstag","der Geburtstag"] },
      { type: "translate", prompt: "Переклади:", uk: "дитяча кімната", de: ["Kinderzimmer","das Kinderzimmer"] },
      { type: "translate", prompt: "Переклади:", uk: "літні канікули", de: ["Sommerferien","die Sommerferien"] },
      { type: "writeFree", prompt: "Утвори 3 нові Komposita зі слів: Wochen, Ende, Haus, Tür, Sport, Schuhe.",
        sample: "das Wochenende, die Haustür, die Sportschuhe." },
    ],
  },

  "komposita-fugen": {
    lesson: {
      slug: "komposita-fugen", level: "B1", category: CAT,
      titleDe: "Fugenelemente — -s-, -n-, -en-, -es-, -er-",
      titleUk: "З'єднувальні елементи в Komposita",
      goal: "Знати найважливіші з'єднувальні елементи й правильно складати Komposita.",
      explanation: [
        "<b>Fugenelement</b> з'являється між двома компонентами Kompositum.",
        "<b>-s-</b> — після іменників з -ung, -heit, -keit, -schaft, -ion, -tum, а також після іменників-чоловічого/середнього роду: <i>Arbeit-s-platz, Lieblings-buch, Geburt-s-tag</i>.",
        "<b>-n-/-en-</b> — після слабких іменників і деяких на -e: <i>Familie-n-name, Schule-n-bau (рідк.), Student-en-werk</i>.",
        "<b>-er-</b> — у деяких іменників із множиною на -er: <i>Kind-er-garten, Bild-er-buch</i>.",
        "Деколи <b>з'єднання немає</b>: <i>Haustür, Schreibtisch, Lehrbuch</i>.",
      ],
      table: {
        headers: ["Fuge", "Приклад", "Походження"],
        rows: [
          ["-s-", "Geburtstag, Arbeitsplatz", "після -ung/-heit/-keit + ін."],
          ["-n-", "Familienname, Sonnenuntergang", "слабкі/на -e"],
          ["-en-", "Studentenwerk, Menschenrechte", "n-Deklination/Pl."],
          ["-er-", "Kindergarten, Bilderbuch", "Pl. на -er"],
          ["—", "Haustür, Schreibtisch", "без Fuge"],
        ],
      },
      examples: [
        { de: "Mein Arbeitsplatz ist im Büro.", uk: "Моє робоче місце — в офісі." },
        { de: "Wie ist Ihr Familienname?", uk: "Як Ваше прізвище?" },
        { de: "Der Kindergarten beginnt um 8.", uk: "Дитсадок починається о 8." },
        { de: "Das Studentenwerk hilft bei Wohnung.", uk: "Студентська спілка допомагає з житлом." },
        { de: "Sie liest ein Bilderbuch.", uk: "Вона читає книгу з малюнками." },
        { de: "Sein Geburtstag ist im Mai.", uk: "Його день народження у травні." },
        { de: "Ich kaufe das im Sportgeschäft.", uk: "Я це куплю в спортивному магазині." },
        { de: "Die Haustür schließt automatisch.", uk: "Вхідні двері зачиняються автоматично." },
      ],
      tip: "Якщо база на -ung/-heit/-keit/-schaft/-ion — <b>-s-</b>. Слабкі іменники й на -e — <b>-n-/-en-</b>. Множина на -er — <b>-er-</b>.",
      mistakes: [
        { wrong: "Geburttag", right: "Geburtstag" },
        { wrong: "Familiename", right: "Familienname" },
      ],
      exercises: {}, prevSlug: "komposita-nomen", nextSlug: "adjektiv-komposita",
    },
    extras: baseExtras(
      "Fuge: <b>-s-/-n-/-en-/-er-</b> або без неї. Залежить від основи.",
      ["Не існує універсального правила — найважливіші слова треба запам'ятати."],
      ["-s- після -ung/-heit/-keit/-schaft.", "-n-/-en- слабкі.", "-er- Pl. на -er."],
    ),
    exercises15: [
      { type: "mc", q: "Geburt + ? + Tag:", options: ["—","-s-","-n-","-er-"], correct: 1 },
      { type: "mc", q: "Familie + ? + Name:", options: ["—","-s-","-n-","-er-"], correct: 2 },
      { type: "mc", q: "Kind + ? + Garten:", options: ["—","-s-","-n-","-er-"], correct: 3 },
      { type: "gap", q: "Arbeit + ___ + Platz", answer: "s" },
      { type: "gap", q: "Bild + ___ + Buch", answer: "er" },
      { type: "tf", q: "Усі Komposita обов'язково мають з'єднувальний елемент.", correct: false },
      { type: "tf", q: "Після -ung часто з'являється -s-.", correct: true },
      { type: "match", prompt: "Слово → Fuge:", pairs: [
        { left: "Geburtstag", right: "-s-" },
        { left: "Familienname", right: "-n-" },
        { left: "Studentenwerk", right: "-en-" },
        { left: "Kindergarten", right: "-er-" },
        { left: "Haustür", right: "—" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Geburttag", correct: ["Geburtstag"] },
      { type: "correct", prompt: "Виправ:", wrong: "Familiename", correct: ["Familienname"] },
      { type: "multi", q: "Які слова з -s- Fuge?",
        options: ["Geburtstag","Familienname","Arbeitsplatz","Kindergarten","Lieblingsbuch"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "робоче місце", de: ["der Arbeitsplatz","Arbeitsplatz"] },
      { type: "translate", prompt: "Переклади:", uk: "права людей", de: ["Menschenrechte","die Menschenrechte"] },
      { type: "tf", q: "<i>Sonnenuntergang</i> має Fuge -n-.", correct: true },
      { type: "writeFree", prompt: "Утвори 3 Komposita з різними Fugen.",
        sample: "Geburtstagsfeier, Familienname, Kinderbuch." },
      { type: "mc", q: "Sonne + ? + Brille:", options: ["—","-n-","-s-","-er-"], correct: 1 },
    ],
  },

  "adjektiv-komposita": {
    lesson: {
      slug: "adjektiv-komposita", level: "B1", category: CAT,
      titleDe: "Adjektivkomposita", titleUk: "Складні прикметники",
      goal: "Утворювати й розуміти складні прикметники: <i>dunkelblau, eiskalt, hellwach</i>.",
      explanation: [
        "Складні прикметники зазвичай мають структуру <b>підсилювач + прикметник</b>.",
        "Типові «підсилювачі»: <b>dunkel-, hell-, eis-, glas-, super-, mega-, hoch-, tief-, blut-, kerzen-, stein-, stock-, top-</b>.",
        "Часто означають «дуже» або уточнюють колір: <i>dunkelblau, hellgrün, eiskalt, hellwach, blutleer, steinhart, stockdunkel</i>.",
        "Можуть бути також з іменником у першій частині: <i>kinderleicht (= дуже легкий), eiskalt</i>.",
      ],
      table: {
        headers: ["Кomposita", "Значення"],
        rows: [
          ["dunkelblau", "темно-синій"],
          ["hellgrün", "світло-зелений"],
          ["eiskalt", "крижаний"],
          ["hellwach", "повністю прокинутий"],
          ["steinhart", "твердий як камінь"],
          ["kinderleicht", "дуже легкий"],
          ["stockdunkel", "хоч в око стрель"],
          ["bildhübsch", "дуже гарний"],
        ],
      },
      examples: [
        { de: "Sie hat dunkelblaue Augen.", uk: "У неї темно-сині очі." },
        { de: "Das Wasser ist eiskalt.", uk: "Вода крижана." },
        { de: "Er ist um 5 Uhr hellwach.", uk: "О 5-й він уже повністю не сонний." },
        { de: "Das Brot ist steinhart.", uk: "Хліб твердий як камінь." },
        { de: "Diese Aufgabe ist kinderleicht.", uk: "Це завдання дуже легке." },
        { de: "Im Keller war es stockdunkel.", uk: "У підвалі було тьма-тьменна." },
        { de: "Sie ist bildhübsch.", uk: "Вона надзвичайно красива." },
        { de: "Ich trage ein hellgrünes T-Shirt.", uk: "Я в світло-зеленій футболці." },
      ],
      tip: "Перша частина «підсилює» — <i>eis-, stein-, kerzen-</i> = «дуже». Кольори: <i>dunkel-, hell-</i> уточнюють відтінок.",
      mistakes: [
        { wrong: "eis kalt", right: "eiskalt" },
        { wrong: "kinder leichte Aufgabe", right: "kinderleichte Aufgabe" },
      ],
      exercises: {}, prevSlug: "komposita-fugen",
    },
    extras: baseExtras(
      "Adjektivkomposita: підсилювач/іменник + прикметник пишуться разом.",
      ["Українське «темно-синій» → dunkelblau (без дефіса).", "<i>kinderleicht</i> = «дуже легкий», а не «дитячий»."],
      ["Підсилювачі: eis-, stein-, kerzen-, stock-…", "Кольори: dunkel-/hell-.", "Пишуться разом."],
    ),
    exercises15: [
      { type: "mc", q: "Як буде «темно-синій»?",
        options: ["dunkel blau","dunkel-blau","dunkelblau","blau dunkel"], correct: 2 },
      { type: "mc", q: "«крижаний»:", options: ["eis kalt","eiskalt","kaltes Eis","eisig"], correct: 1 },
      { type: "gap", q: "Sie hat ___ Augen. (темно-зелені)", answer: "dunkelgrüne" },
      { type: "gap", q: "Diese Aufgabe ist ___. (дуже легке)", answer: "kinderleicht" },
      { type: "tf", q: "Adjektivkomposita пишуться через дефіс.", correct: false },
      { type: "tf", q: "<i>hellwach</i> = «дуже прокинутий».", correct: true },
      { type: "match", prompt: "Слово → значення:", pairs: [
        { left: "eiskalt", right: "крижаний" },
        { left: "steinhart", right: "як камінь" },
        { left: "kinderleicht", right: "дуже легкий" },
        { left: "bildhübsch", right: "дуже гарний" },
        { left: "stockdunkel", right: "повна темрява" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "eis kalt", correct: ["eiskalt"] },
      { type: "correct", prompt: "Виправ:", wrong: "kinder leichte Aufgabe",
        correct: ["kinderleichte Aufgabe"] },
      { type: "multi", q: "Які слова — Adjektivkomposita?",
        options: ["eiskalt","kalt","dunkelblau","blau","kinderleicht"], correct: [0,2,4] },
      { type: "translate", prompt: "Переклади:", uk: "світло-зелений", de: ["hellgrün"] },
      { type: "translate", prompt: "Переклади:", uk: "темно-червоний", de: ["dunkelrot"] },
      { type: "translate", prompt: "Переклади:", uk: "твердий як камінь", de: ["steinhart"] },
      { type: "translate", prompt: "Переклади:", uk: "дуже гарна", de: ["bildhübsch"] },
      { type: "writeFree", prompt: "Утвори 3 Adjektivkomposita й використай їх у реченнях.",
        sample: "Im Winter ist das Wasser im See eiskalt. Sie hat dunkelblaue Augen und bildhübsche Hände. Die neue App ist kinderleicht zu bedienen." },
    ],
  },
};
