// B1 · Zeiten — 8 повних уроків.
import type { B1Map } from "./_helpers";
const CAT = "Часи";

const baseExtras = (rule: string, tips: string[], summary: string[]) => ({
  duration: 16, premium: true, ruleBox: { rule }, ukrainianTips: tips, summary,
});

export const zeitenB1: B1Map = {
  "zeiten-uebersicht": {
    lesson: {
      slug: "zeiten-uebersicht", level: "B1", category: CAT,
      titleDe: "Tempora — Übersicht", titleUk: "Огляд німецьких часів",
      goal: "Зорієнтуватися в системі шести часів німецької мови та правильно обирати їх за контекстом.",
      explanation: [
        "Німецька має <b>6 основних часових форм</b>: Präsens, Perfekt, Präteritum, Plusquamperfekt, Futur I, Futur II.",
        "<b>Präsens</b> — теперішнє й часто майбутнє з обставиною часу.",
        "<b>Perfekt</b> — розмовний минулий час.",
        "<b>Präteritum</b> — письмовий минулий (плюс <i>sein, haben, Modalverben</i> — і в розмові).",
        "<b>Plusquamperfekt</b> — передминулий час, для опису того, що сталося <b>раніше</b> іншої минулої дії.",
        "<b>Futur I</b> — намір/прогноз/припущення про теперішнє.",
        "<b>Futur II</b> — припущення про минуле або завершеність у майбутньому: <i>Bis Mai werde ich das Buch gelesen haben.</i>",
      ],
      table: {
        headers: ["Час", "Допоміжне", "Приклад"],
        rows: [
          ["Präsens", "—", "Ich lerne Deutsch."],
          ["Perfekt", "haben/sein + P II", "Ich habe gelernt."],
          ["Präteritum", "—", "Ich lernte."],
          ["Plusquamperfekt", "hatte/war + P II", "Ich hatte gelernt."],
          ["Futur I", "werde + Inf.", "Ich werde lernen."],
          ["Futur II", "werde + P II + haben/sein", "Ich werde gelernt haben."],
        ],
      },
      examples: [
        { de: "Ich lerne jeden Tag.", uk: "Я вчуся щодня.", tag: "Präsens" },
        { de: "Gestern habe ich gelernt.", uk: "Учора я вчив(ла)ся.", tag: "Perfekt" },
        { de: "Damals lernte ich viel.", uk: "Тоді я багато вчив(ла)ся.", tag: "Präteritum" },
        { de: "Bevor er kam, hatte ich schon gegessen.", uk: "Перш ніж він прийшов, я вже поїв(ла).", tag: "Plusqu." },
        { de: "Morgen werde ich lernen.", uk: "Завтра я буду вчитися.", tag: "Futur I" },
        { de: "Bis morgen werde ich es geschafft haben.", uk: "До завтра я це зроблю.", tag: "Futur II" },
        { de: "Er wird wohl zu Hause sein.", uk: "Він, мабуть, удома.", tag: "Futur I (припущ.)" },
        { de: "Sie wird das Buch gelesen haben.", uk: "Вона, певно, вже прочитала книгу.", tag: "Futur II (припущ.)" },
      ],
      tip: "Розмова → <b>Perfekt</b>; письмо → <b>Präteritum</b>; раніше за минуле → <b>Plusquamperfekt</b>.",
      mistakes: [
        { wrong: "Ich habe gestern gelernen.", right: "Ich habe gestern gelernt." },
        { wrong: "Bevor er kam, ich habe gegessen.", right: "Bevor er kam, hatte ich schon gegessen." },
      ],
      exercises: {}, nextSlug: "praesens-b1",
    },
    extras: baseExtras(
      "6 часів: Präsens, Perfekt, Präteritum, Plusquamperfekt, Futur I, Futur II.",
      ["Усе теперішнє + майбутнє в розмові — часто Präsens.", "Минуле в розмові — Perfekt, у тексті — Präteritum."],
      ["Präsens — основа.", "Perfekt — розмова.", "Präteritum — текст.", "Plusquamperfekt — раніше за минуле.", "Futur I/II — майбутнє/припущення."],
    ),
    exercises15: [
      { type: "mc", q: "Який час: <i>Ich habe gelernt</i>?", options: ["Präsens","Perfekt","Präteritum","Futur"], correct: 1 },
      { type: "mc", q: "Який час: <i>Ich hatte gelernt</i>?", options: ["Perfekt","Plusquamperfekt","Präteritum","Futur II"], correct: 1 },
      { type: "mc", q: "Який час: <i>Ich werde gelernt haben</i>?", options: ["Futur I","Futur II","Perfekt","Plusqu."], correct: 1 },
      { type: "gap", q: "Bevor er kam, ___ ich schon ___. (essen, Plusqu.)", answer: "hatte gegessen" },
      { type: "gap", q: "Morgen ___ ich kommen. (Futur I, werden)", answer: "werde" },
      { type: "tf", q: "Plusquamperfekt = hatte/war + Partizip II.", correct: true },
      { type: "tf", q: "У розмові частіше Präteritum.", correct: false },
      { type: "match", prompt: "Час → формула:", pairs: [
        { left: "Perfekt", right: "haben/sein + P II" },
        { left: "Plusquamperfekt", right: "hatte/war + P II" },
        { left: "Futur I", right: "werden + Inf." },
        { left: "Futur II", right: "werden + P II + haben/sein" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Bevor er kam, ich habe gegessen.",
        correct: ["Bevor er kam, hatte ich gegessen.","Bevor er kam, hatte ich schon gegessen."] },
      { type: "multi", q: "Які речення — у Perfekt?", options: [
        "Ich habe gelernt.","Ich lernte.","Wir sind gefahren.","Wir fuhren.","Sie haben gegessen."], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення Futur II:",
        words: ["bis","werde","gelernt","haben","morgen","alles","ich"],
        correct: ["bis","morgen","werde","ich","alles","gelernt","haben"] },
      { type: "translate", prompt: "Переклади у Perfekt:", uk: "Учора я подивився фільм.",
        de: ["Gestern habe ich einen Film gesehen.","Ich habe gestern einen Film gesehen."] },
      { type: "translate", prompt: "Переклади у Plusquamperfekt:", uk: "Я вже поїв, перш ніж він прийшов.",
        de: ["Ich hatte schon gegessen, bevor er kam."] },
      { type: "tf", q: "Futur I можна замінити Präsens із обставиною часу.", correct: true },
      { type: "writeFree", prompt: "Напиши 3 речення в різних часах про свій тиждень.",
        sample: "Heute lerne ich Deutsch (Präsens). Gestern habe ich einen Test geschrieben (Perfekt). Morgen werde ich mit Freunden Pizza essen (Futur I)." },
    ],
  },

  "praesens-b1": {
    lesson: {
      slug: "praesens-b1", level: "B1", category: CAT,
      titleDe: "Präsens (B1)", titleUk: "Präsens — функції на B1",
      goal: "Розширити функції Präsens: для майбутнього, для загальних правил, в історичному оповіданні.",
      explanation: [
        "Präsens описує: 1) <b>зараз</b>, 2) <b>звички</b>, 3) <b>загальні факти</b>, 4) <b>майбутнє</b> з обставиною часу, 5) <b>історичне теперішнє</b> (живе оповідання).",
        "У повсякденній мові майбутнє <b>частіше</b> в Präsens, ніж у Futur I.",
        "Стилістично Präsens робить текст <b>динамічним</b>.",
      ],
      examples: [
        { de: "Morgen fahre ich nach Wien.", uk: "Завтра я їду до Відня.", tag: "майбутнє" },
        { de: "Wasser kocht bei 100 Grad.", uk: "Вода кипить при 100°.", tag: "факт" },
        { de: "Ich stehe jeden Tag um 7 auf.", uk: "Я встаю щодня о 7.", tag: "звичка" },
        { de: "Da kommt der Bus!", uk: "Ось і автобус!", tag: "тепер" },
        { de: "1989 fällt die Mauer.", uk: "У 1989-му падає стіна.", tag: "істор. Präsens" },
        { de: "Nächste Woche habe ich Urlaub.", uk: "Наступного тижня в мене відпустка." },
        { de: "Er arbeitet bei Siemens.", uk: "Він працює в Siemens." },
        { de: "Bald sehen wir uns.", uk: "Скоро побачимося." },
      ],
      tip: "Якщо є обставина часу (morgen, bald, nächste Woche) — Präsens достатньо для майбутнього.",
      mistakes: [
        { wrong: "Morgen ich werde fahren.", right: "Morgen fahre ich." },
        { wrong: "Wasser kochen bei 100 Grad.", right: "Wasser kocht bei 100 Grad." },
      ],
      exercises: {}, prevSlug: "zeiten-uebersicht", nextSlug: "perfekt-b1",
    },
    extras: baseExtras(
      "Präsens = тепер, звички, факти, <b>майбутнє з часовою обставиною</b>, історичне.",
      ["Українське майбутнє «їду» — і в нім. Präsens.", "Не плутати з <i>werden</i>-конструкцією."],
      ["5 функцій Präsens.", "Майбутнє: Präsens + час.", "Історичне Präsens — для оповідання."],
    ),
    exercises15: [
      { type: "mc", q: "Яка функція Präsens у <i>Morgen fahre ich nach Wien</i>?",
        options: ["звичка","факт","майбутнє","історія"], correct: 2 },
      { type: "mc", q: "<i>Wasser kocht bei 100 Grad.</i>", options: ["звичка","факт","майбутнє","зараз"], correct: 1 },
      { type: "gap", q: "Nächste Woche ___ ich Urlaub. (haben)", answer: "habe" },
      { type: "gap", q: "Er ___ bei BMW. (arbeiten)", answer: "arbeitet" },
      { type: "tf", q: "Майбутнє в розмові завжди Futur I.", correct: false },
      { type: "tf", q: "Präsens може описувати загальні факти.", correct: true },
      { type: "match", prompt: "Речення → функція:", pairs: [
        { left: "Ich gehe jeden Tag joggen.", right: "звичка" },
        { left: "Bald komme ich.", right: "майбутнє" },
        { left: "Wasser ist nass.", right: "факт" },
        { left: "1492 entdeckt Kolumbus Amerika.", right: "істор. Präsens" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Morgen ich werde fahren.",
        correct: ["Morgen fahre ich.","Ich fahre morgen.","Morgen werde ich fahren."] },
      { type: "multi", q: "У яких реченнях Präsens описує майбутнє?",
        options: ["Morgen fahre ich.","Ich arbeite immer.","Bald komme ich.","Wasser kocht bei 100."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["fahre","nach","ich","morgen","Wien"], correct: ["morgen","fahre","ich","nach","Wien"] },
      { type: "translate", prompt: "Переклади:", uk: "Завтра я починаю нову роботу.",
        de: ["Morgen beginne ich eine neue Arbeit.","Morgen fange ich eine neue Arbeit an."] },
      { type: "tf", q: "Präsens — найпоширеніший час у німецькій.", correct: true },
      { type: "gap", q: "Da ___ der Zug! (kommen)", answer: "kommt" },
      { type: "translate", prompt: "Переклади:", uk: "Я щодня встаю о 7.", de: ["Ich stehe jeden Tag um 7 auf."] },
      { type: "writeFree", prompt: "Напиши 3 Präsens-речення з різними функціями.",
        sample: "Ich arbeite jeden Tag von 9 bis 18 Uhr. Nächsten Sommer mache ich Urlaub in Italien. Die Erde dreht sich um die Sonne." },
    ],
  },

  "perfekt-b1": {
    lesson: {
      slug: "perfekt-b1", level: "B1", category: CAT,
      titleDe: "Perfekt (B1)", titleUk: "Perfekt — розмовний минулий",
      goal: "Упевнено вживати Perfekt у розмові й листуванні; добирати haben/sein і правильні форми Partizip II.",
      explanation: [
        "<b>Perfekt = haben/sein + Partizip II</b>. Це основна форма минулого <b>в розмові</b> й у листах.",
        "<b>sein</b> — рух і зміна стану: <i>gehen, fahren, kommen, fliegen, schwimmen, aufstehen, einschlafen, sterben, werden, sein, bleiben, passieren</i>.",
        "Інше → <b>haben</b>.",
        "Слабкі: <i>ge-…-t</i>. Сильні: <i>ge-…-en</i> з можливою зміною голосної. -ieren: без ge-.",
      ],
      examples: [
        { de: "Ich habe Deutsch gelernt.", uk: "Я вивчив(ла) німецьку." },
        { de: "Wir sind nach Wien gefahren.", uk: "Ми поїхали до Відня." },
        { de: "Sie hat einen Brief geschrieben.", uk: "Вона написала листа." },
        { de: "Hast du das Buch gelesen?", uk: "Ти прочитав(ла) книгу?" },
        { de: "Er ist um 7 aufgestanden.", uk: "Він устав о 7." },
        { de: "Wir haben gefrühstückt.", uk: "Ми поснідали." },
        { de: "Sie sind in Berlin geblieben.", uk: "Вони лишилися в Берліні." },
        { de: "Was ist passiert?", uk: "Що сталося?" },
      ],
      tip: "Рух / зміна стану / sein, bleiben, passieren → <b>sein</b>. Усе решта → <b>haben</b>.",
      mistakes: [
        { wrong: "Ich habe nach Hause gegangen.", right: "Ich bin nach Hause gegangen." },
        { wrong: "Sie hat aufgestanden.", right: "Sie ist aufgestanden." },
      ],
      exercises: {}, prevSlug: "praesens-b1", nextSlug: "praeteritum-b1",
    },
    extras: baseExtras(
      "<b>haben/sein + Partizip II</b>. sein — рух/зміна стану; інакше — haben.",
      ["Українському доконаному виду найчастіше відповідає Perfekt."],
      ["Розмова → Perfekt.", "sein: gehen, fahren, kommen, aufstehen…", "Partizip II в кінці."],
    ),
    exercises15: [
      { type: "mc", q: "Ich ___ Deutsch gelernt.", options: ["bin","habe","war","wurde"], correct: 1 },
      { type: "mc", q: "Wir ___ nach Wien gefahren.", options: ["haben","sind","waren","werden"], correct: 1 },
      { type: "mc", q: "Sie ___ aufgestanden.", options: ["hat","ist","war","wurde"], correct: 1 },
      { type: "gap", q: "Ich ___ einen Brief ___. (schreiben)", answer: "habe geschrieben" },
      { type: "gap", q: "Er ___ in Berlin ___. (bleiben)", answer: "ist geblieben" },
      { type: "gap", q: "Wir ___ ___. (frühstücken)", answer: "haben gefrühstückt" },
      { type: "tf", q: "<i>passieren</i> утворює Perfekt з haben.", correct: false },
      { type: "tf", q: "Дієслова на -ieren мають ge-.", correct: false },
      { type: "match", prompt: "Інфінітив → Partizip II:", pairs: [
        { left: "gehen", right: "gegangen" }, { left: "lesen", right: "gelesen" },
        { left: "machen", right: "gemacht" }, { left: "fahren", right: "gefahren" },
        { left: "studieren", right: "studiert" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe nach Hause gegangen.",
        correct: ["Ich bin nach Hause gegangen."] },
      { type: "multi", q: "Які дієслова з sein?",
        options: ["gehen","essen","aufstehen","arbeiten","kommen","bleiben"], correct: [0,2,4,5] },
      { type: "order", prompt: "Склади речення:",
        words: ["gelernt","habe","Deutsch","ich"], correct: ["ich","habe","Deutsch","gelernt"] },
      { type: "translate", prompt: "Переклади у Perfekt:", uk: "Учора я приготував піцу.",
        de: ["Gestern habe ich eine Pizza gemacht.","Ich habe gestern eine Pizza gemacht."] },
      { type: "translate", prompt: "Переклади:", uk: "Ми поїхали до Берліна.",
        de: ["Wir sind nach Berlin gefahren."] },
      { type: "writeFree", prompt: "Напиши 3 речення про вихідні у Perfekt.",
        sample: "Am Samstag bin ich spät aufgestanden. Ich habe Freunde getroffen und wir haben zusammen gegessen. Am Sonntag bin ich an den See gefahren." },
    ],
  },

  "praeteritum-b1": {
    lesson: {
      slug: "praeteritum-b1", level: "B1", category: CAT,
      titleDe: "Präteritum (B1)", titleUk: "Präteritum — письмовий минулий",
      goal: "Уживати Präteritum у письмових текстах, новинах, оповіданнях.",
      explanation: [
        "<b>Präteritum</b> — простий минулий час, типовий для письмових текстів. В усному мовленні з нього лишаються переважно <b>sein, haben, Modalverben</b> та деякі поширені дієслова.",
        "Слабкі: основа + <b>-te-</b> + закінчення.",
        "Сильні: <b>Ablaut</b> (зміна голосної) + закінчення без -te-. 1 і 3 ос. однини — без закінчення.",
        "Мішані: Ablaut + -te- (<i>denken → dachte, bringen → brachte, wissen → wusste</i>).",
      ],
      examples: [
        { de: "Er ging schnell nach Hause.", uk: "Він швидко пішов додому." },
        { de: "Wir arbeiteten bis 20 Uhr.", uk: "Ми працювали до 20:00." },
        { de: "Sie las ein interessantes Buch.", uk: "Вона читала цікаву книгу." },
        { de: "Ich dachte oft an dich.", uk: "Я часто думав(ла) про тебе." },
        { de: "Der Zug fuhr pünktlich ab.", uk: "Поїзд від'їхав вчасно." },
        { de: "Plötzlich klingelte das Telefon.", uk: "Раптом задзвонив телефон." },
        { de: "Die Kinder spielten draußen.", uk: "Діти гралися на вулиці." },
        { de: "Es war einmal ein König.", uk: "Жив-був одного разу король." },
      ],
      tip: "Для розповіді/новин/казок — <b>Präteritum</b>. Для побутової розмови про минуле — <b>Perfekt</b>.",
      mistakes: [
        { wrong: "Ich gingte nach Hause.", right: "Ich ging nach Hause." },
        { wrong: "Er machtete das.", right: "Er machte das." },
      ],
      exercises: {}, prevSlug: "perfekt-b1", nextSlug: "plusquamperfekt",
    },
    extras: baseExtras(
      "Слабкі: -te-. Сильні: Ablaut. Мішані: Ablaut + -te-. У 1/3 ос. одн. сильних — нуль.",
      ["Українські форми «йшов / читав» можуть бути і Perfekt, і Präteritum — за стилем."],
      ["Письмо → Präteritum.", "Розмова → Perfekt + (sein/haben/Modal в Prät.).", "Сильні без -te-."],
    ),
    exercises15: [
      { type: "mc", q: "Präteritum від gehen (er):", options: ["geht","gehte","ging","gegangen"], correct: 2 },
      { type: "mc", q: "Präteritum від bringen (er):", options: ["brachte","brangte","brangt","gebracht"], correct: 0 },
      { type: "gap", q: "Wir ___ bis spät. (arbeiten)", answer: "arbeiteten" },
      { type: "gap", q: "Sie ___ ein Buch. (lesen)", answer: "las" },
      { type: "gap", q: "Er ___ schnell. (denken)", answer: "dachte" },
      { type: "tf", q: "У 1 і 3 ос. однини сильних дієслів немає закінчення.", correct: true },
      { type: "tf", q: "Розмова в німецькій вимагає Präteritum.", correct: false },
      { type: "match", prompt: "Дієслово → Prät. (3 Sg.):", pairs: [
        { left: "gehen", right: "ging" }, { left: "sehen", right: "sah" },
        { left: "machen", right: "machte" }, { left: "denken", right: "dachte" },
        { left: "kommen", right: "kam" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich gingte nach Hause.",
        correct: ["Ich ging nach Hause."] },
      { type: "multi", q: "Які форми — Präteritum?",
        options: ["machte","mache","ging","geht","sah","sieht"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["ging","nach","ich","Hause","spät"], correct: ["ich","ging","spät","nach","Hause"] },
      { type: "translate", prompt: "Переклади у Präteritum:", uk: "Раптом задзвонив телефон.",
        de: ["Plötzlich klingelte das Telefon."] },
      { type: "translate", prompt: "Переклади:", uk: "Він читав книгу й слухав музику.",
        de: ["Er las ein Buch und hörte Musik."] },
      { type: "tf", q: "<i>war/hatte</i> часті й у розмові.", correct: true },
      { type: "writeFree", prompt: "Напиши 3 речення у Präteritum про вчора (як у щоденнику).",
        sample: "Gestern stand ich früh auf. Ich fuhr ins Büro und arbeitete bis spät am Abend. Danach traf ich Freunde im Café." },
    ],
  },

  plusquamperfekt: {
    lesson: {
      slug: "plusquamperfekt", level: "B1", category: CAT,
      titleDe: "Plusquamperfekt", titleUk: "Plusquamperfekt — передминулий час",
      goal: "Уживати Plusquamperfekt, щоб показати дію, яка відбулася <b>раніше</b> іншої минулої дії.",
      explanation: [
        "<b>Plusquamperfekt = hatte/war (Präteritum допоміжного) + Partizip II</b>.",
        "Описує дію, що <b>передує іншій минулій</b>. Часто з <b>nachdem, bevor, als</b>.",
        "Типова схема: <i>Nachdem ich gegessen <b>hatte</b>, ging ich los.</i> (Plusquamperfekt → Präteritum)",
        "Вибір hatte/war — як у Perfekt: рух/зміна стану → war; інше → hatte.",
      ],
      table: {
        headers: ["", "hatte + P II", "war + P II"],
        rows: [
          ["ich", "hatte gelernt", "war gegangen"],
          ["du", "hattest gelernt", "warst gegangen"],
          ["er/sie/es", "hatte gelernt", "war gegangen"],
          ["wir", "hatten gelernt", "waren gegangen"],
          ["ihr", "hattet gelernt", "wart gegangen"],
          ["sie/Sie", "hatten gelernt", "waren gegangen"],
        ],
      },
      examples: [
        { de: "Nachdem ich gegessen hatte, ging ich spazieren.", uk: "Після того, як я поїв(ла), я пішов(ла) гуляти." },
        { de: "Als wir ankamen, war der Film schon zu Ende.", uk: "Коли ми приїхали, фільм уже закінчився." },
        { de: "Bevor er die Antwort gab, hatte er lange überlegt.", uk: "Перш ніж дати відповідь, він довго думав." },
        { de: "Sie war müde, weil sie wenig geschlafen hatte.", uk: "Вона була втомлена, бо мало спала." },
        { de: "Wir hatten alles vorbereitet, bevor die Gäste kamen.", uk: "Ми все підготували, перш ніж прийшли гості." },
        { de: "Nachdem die Kinder eingeschlafen waren, las ich.", uk: "Коли діти заснули, я почав(ла) читати." },
        { de: "Er hatte das Buch schon zweimal gelesen.", uk: "Він уже двічі читав цю книгу." },
        { de: "Wir waren bereits losgefahren, als sie anrief.", uk: "Ми вже виїхали, коли вона подзвонила." },
      ],
      tip: "Plusquamperfekt = <b>раніше за минуле</b>. Часто з <i>nachdem</i> + головне Präteritum.",
      mistakes: [
        { wrong: "Nachdem ich gegessen habe, ging ich los.", right: "Nachdem ich gegessen hatte, ging ich los." },
        { wrong: "Sie hatte gegangen.", right: "Sie war gegangen." },
      ],
      exercises: {}, prevSlug: "praeteritum-b1", nextSlug: "futur1-zeiten",
    },
    extras: baseExtras(
      "<b>hatte/war + Partizip II</b>. Дія раніше за іншу минулу.",
      ["Українське «уже зробив, перш ніж…» = Plusquamperfekt.", "З <i>nachdem</i> майже завжди Plusquamperfekt у підрядному."],
      ["Plusqu. = hatte/war + P II.", "Часто з nachdem/bevor/als.", "Головне зазвичай Präteritum."],
    ),
    exercises15: [
      { type: "mc", q: "Plusquamperfekt від gehen (er):", options: ["ist gegangen","war gegangen","hatte gegangen","ging"], correct: 1 },
      { type: "mc", q: "Plusqu. від lernen (ich):", options: ["habe gelernt","hatte gelernt","lernte","werde gelernt haben"], correct: 1 },
      { type: "gap", q: "Nachdem ich ___ ___ , ging ich los. (essen)", answer: "gegessen hatte" },
      { type: "gap", q: "Als wir ankamen, ___ der Film schon zu Ende ___. (sein)", answer: "war gewesen", hint: "war + gewesen" },
      { type: "gap", q: "Sie war müde, weil sie wenig ___ ___. (schlafen)", answer: "geschlafen hatte" },
      { type: "tf", q: "Plusquamperfekt використовується для майбутніх дій.", correct: false },
      { type: "tf", q: "Plusquamperfekt описує дію, яка сталася раніше за іншу минулу.", correct: true },
      { type: "match", prompt: "Дієслово → Plusqu. (3 Sg.):", pairs: [
        { left: "gehen", right: "war gegangen" }, { left: "essen", right: "hatte gegessen" },
        { left: "kommen", right: "war gekommen" }, { left: "lernen", right: "hatte gelernt" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Nachdem ich gegessen habe, ging ich los.",
        correct: ["Nachdem ich gegessen hatte, ging ich los."] },
      { type: "correct", prompt: "Виправ:", wrong: "Sie hatte gegangen.",
        correct: ["Sie war gegangen."] },
      { type: "multi", q: "Які речення — у Plusqu.?",
        options: ["Ich hatte gelernt.","Ich habe gelernt.","Wir waren gefahren.","Wir sind gefahren."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["nachdem","gegessen","ich","hatte","ging","spazieren","ich"],
        correct: ["nachdem","ich","gegessen","hatte","ging","ich","spazieren"] },
      { type: "translate", prompt: "Переклади:", uk: "Коли ми приїхали, фільм уже закінчився.",
        de: ["Als wir ankamen, war der Film schon zu Ende."] },
      { type: "translate", prompt: "Переклади:", uk: "Я вже все підготував, перш ніж прийшли гості.",
        de: ["Ich hatte schon alles vorbereitet, bevor die Gäste kamen."] },
      { type: "writeFree", prompt: "Напиши 2 речення з Plusqu. + Prät.",
        sample: "Nachdem ich gefrühstückt hatte, fuhr ich ins Büro. Als ich ankam, hatten die Kollegen schon das Meeting begonnen." },
    ],
  },

  "futur1-zeiten": {
    lesson: {
      slug: "futur1-zeiten", level: "B1", category: CAT,
      titleDe: "Futur I", titleUk: "Futur I — намір, прогноз, припущення",
      goal: "Розуміти всі функції Futur I і обирати між ним і Präsens.",
      explanation: [
        "<b>Futur I = werden + Infinitiv</b>.",
        "Функції: 1) <b>намір/обіцянка</b>: <i>Ich werde dir helfen</i>; 2) <b>прогноз</b>: <i>Es wird regnen</i>; 3) <b>припущення про теперішнє</b>: <i>Er wird wohl zu Hause sein</i>.",
        "Для майбутнього з обставиною часу часто Präsens замість Futur I: <i>Morgen fahre ich</i>.",
        "<b>wohl/sicher/bestimmt/wahrscheinlich</b> + Futur I підсилюють припущення.",
      ],
      examples: [
        { de: "Ich werde dir morgen helfen.", uk: "Я тобі завтра допоможу." },
        { de: "Es wird bald regnen.", uk: "Незабаром піде дощ." },
        { de: "Er wird wohl im Büro sein.", uk: "Він, мабуть, в офісі." },
        { de: "Wir werden uns wiedersehen.", uk: "Ми ще побачимося." },
        { de: "Sie wird sicher kommen.", uk: "Вона напевно прийде." },
        { de: "Das werden wir schaffen.", uk: "Ми це здолаємо." },
        { de: "Du wirst es bestimmt schaffen.", uk: "Ти точно впораєшся." },
        { de: "In zehn Jahren werden wir alle Elektroautos fahren.", uk: "За десять років усі їздитимуть на електроавто." },
      ],
      tip: "Намір + обіцянка → <b>Futur I</b>. Просте майбутнє → <b>Präsens + час</b>.",
      mistakes: [
        { wrong: "Ich werde helfe dir.", right: "Ich werde dir helfen." },
        { wrong: "Morgen ich werde kommen.", right: "Morgen werde ich kommen." },
      ],
      exercises: {}, prevSlug: "plusquamperfekt", nextSlug: "futur2",
    },
    extras: baseExtras(
      "<b>werden + Infinitiv</b> у кінці. Намір/прогноз/припущення.",
      ["Українське «я зроблю / я буду робити» — обидва часто Präsens.", "«Напевно/мабуть» → Futur I + wohl."],
      ["werden + Inf.", "Альтернатива: Präsens + час.", "Припущення: wird wohl + Inf."],
    ),
    exercises15: [
      { type: "mc", q: "Ich ___ dir helfen.", options: ["werde","wirst","wird","werden"], correct: 0 },
      { type: "mc", q: "Es ___ regnen.", options: ["werde","wirst","wird","werden"], correct: 2 },
      { type: "gap", q: "Wir ___ uns wiedersehen. (werden)", answer: "werden" },
      { type: "gap", q: "Du ___ es schaffen. (werden)", answer: "wirst" },
      { type: "tf", q: "Інфінітив у Futur I стоїть на 2 місці.", correct: false },
      { type: "tf", q: "Futur I + wohl = припущення.", correct: true },
      { type: "match", prompt: "Особа → werden:", pairs: [
        { left: "ich", right: "werde" }, { left: "du", right: "wirst" },
        { left: "er", right: "wird" }, { left: "wir", right: "werden" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Morgen ich werde kommen.",
        correct: ["Morgen werde ich kommen.","Morgen komme ich."] },
      { type: "multi", q: "Які речення — Futur I?",
        options: ["Ich werde lernen.","Ich lerne.","Sie wird kommen.","Sie kam.","Wir werden helfen."], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["werde","ich","helfen","dir","morgen"], correct: ["ich","werde","dir","morgen","helfen"] },
      { type: "translate", prompt: "Переклади:", uk: "Я тобі завтра подзвоню.",
        de: ["Ich werde dich morgen anrufen.","Morgen werde ich dich anrufen."] },
      { type: "translate", prompt: "Переклади як припущення:", uk: "Він, мабуть, удома.",
        de: ["Er wird wohl zu Hause sein."] },
      { type: "tf", q: "Futur I — обов'язково для будь-якого майбутнього.", correct: false },
      { type: "mc", q: "Es ___ bald schneien.", options: ["wird","werde","werdet","sind"], correct: 0 },
      { type: "gap", q: "Sie ___ sicher kommen.", answer: "wird" },
      { type: "writeFree", prompt: "Напиши 2 обіцянки у Futur I.",
        sample: "Ich werde dir morgen mit den Hausaufgaben helfen. Ich werde nie wieder zu spät kommen." },
    ],
  },

  futur2: {
    lesson: {
      slug: "futur2", level: "B1", category: CAT,
      titleDe: "Futur II", titleUk: "Futur II — завершеність / припущення про минуле",
      goal: "Виражати завершену дію у майбутньому або припущення про минуле за допомогою Futur II.",
      explanation: [
        "<b>Futur II = werden + Partizip II + haben/sein</b>.",
        "Дві функції: 1) <b>завершеність у майбутньому</b>: <i>Bis Mai werde ich das Buch gelesen haben.</i>; 2) <b>припущення про минуле</b>: <i>Sie wird das Buch schon gelesen haben.</i>",
        "Часто з <i>wohl, sicher, bestimmt, vermutlich</i>.",
        "Допоміжне дієслово (haben/sein) обирається як у Perfekt.",
      ],
      examples: [
        { de: "Bis morgen werde ich alles erledigt haben.", uk: "До завтра я все зроблю." },
        { de: "Sie wird das Buch schon gelesen haben.", uk: "Вона, певно, вже прочитала книгу." },
        { de: "Er wird nach Hause gegangen sein.", uk: "Він, мабуть, уже пішов додому." },
        { de: "Bis nächste Woche werden wir den Bericht geschrieben haben.", uk: "До наступного тижня ми напишемо звіт." },
        { de: "Du wirst wohl müde gewesen sein.", uk: "Ти, певно, був(ла) втомлений(а)." },
        { de: "Sie werden bestimmt angekommen sein.", uk: "Вони точно вже приїхали." },
        { de: "Bis 2030 wird sich vieles geändert haben.", uk: "До 2030-го багато чого зміниться." },
        { de: "Bis dahin wirst du es geschafft haben.", uk: "До того часу ти впораєшся." },
      ],
      tip: "Допоміжне дієслово (haben/sein) — як у Perfekt. <b>werden</b> на 2 місці; <i>P II + haben/sein</i> у кінці.",
      mistakes: [
        { wrong: "Ich werde gelernt haben gestern.", right: "Ich werde wohl gestern gelernt haben." },
        { wrong: "Er wird gegangen haben.", right: "Er wird gegangen sein." },
      ],
      exercises: {}, prevSlug: "futur1-zeiten", nextSlug: "zeitfolge",
    },
    extras: baseExtras(
      "<b>werden + Partizip II + haben/sein</b>. Завершеність у майбутньому або припущення про минуле.",
      ["В укр. «уже зроблю/зробив» — нім. Futur II.", "Часто з wohl/bestimmt/sicher."],
      ["Futur II = werden + P II + haben/sein.", "Завершеність / припущення про минуле."],
    ),
    exercises15: [
      { type: "mc", q: "Futur II від lernen (ich):",
        options: ["werde lernen","werde gelernt haben","habe gelernt","hatte gelernt"], correct: 1 },
      { type: "mc", q: "Futur II від gehen (er):",
        options: ["wird gehen","wird gegangen sein","ist gegangen","war gegangen"], correct: 1 },
      { type: "gap", q: "Bis morgen ___ ich alles ___ ___. (erledigen)", answer: "werde erledigt haben" },
      { type: "gap", q: "Sie ___ wohl angekommen ___. (sein)", answer: "wird sein" },
      { type: "tf", q: "Futur II = werden + Infinitiv.", correct: false, explain: "+ P II + haben/sein." },
      { type: "tf", q: "Futur II може виражати припущення про минуле.", correct: true },
      { type: "match", prompt: "Дієслово → Futur II (3 Sg.):", pairs: [
        { left: "lernen", right: "wird gelernt haben" },
        { left: "kommen", right: "wird gekommen sein" },
        { left: "essen", right: "wird gegessen haben" },
        { left: "fahren", right: "wird gefahren sein" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Er wird gegangen haben.",
        correct: ["Er wird gegangen sein."] },
      { type: "multi", q: "Які речення — Futur II?",
        options: ["Ich werde gelernt haben.","Ich habe gelernt.","Er wird angekommen sein.","Er ist angekommen."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["bis","ich","alles","morgen","haben","erledigt","werde"],
        correct: ["bis","morgen","werde","ich","alles","erledigt","haben"] },
      { type: "translate", prompt: "Переклади:", uk: "Вона, мабуть, уже вдома (припущ. про минуле).",
        de: ["Sie wird wohl schon zu Hause angekommen sein.","Sie wird schon zu Hause sein."] },
      { type: "translate", prompt: "Переклади:", uk: "До п'ятниці ми завершимо проєкт.",
        de: ["Bis Freitag werden wir das Projekt beendet haben.","Bis Freitag werden wir das Projekt abgeschlossen haben."] },
      { type: "tf", q: "Допоміжне (haben/sein) у Futur II обирається як у Perfekt.", correct: true },
      { type: "writeFree", prompt: "Напиши 2 речення у Futur II.",
        sample: "Bis zum Sommer werde ich die B1-Prüfung bestanden haben. Sie wird wohl gestern lange gearbeitet haben." },
      { type: "mc", q: "Du ___ wohl müde gewesen sein.", options: ["wirst","werdest","wird","bist"], correct: 0 },
      { type: "gap", q: "Bis 2030 ___ sich vieles ___ ___. (ändern)", answer: "wird geändert haben" },
    ],
  },

  zeitfolge: {
    lesson: {
      slug: "zeitfolge", level: "B1", category: CAT,
      titleDe: "Zeitfolge — Consecutio temporum", titleUk: "Узгодження часів",
      goal: "Правильно поєднувати часи у складних реченнях і непрямій мові.",
      explanation: [
        "У німецькій <b>немає жорсткої «consecutio temporum»</b>, як, наприклад, у латинській, але є типові комбінації.",
        "<b>Plusquamperfekt + Präteritum</b> — для послідовності в минулому (часто з nachdem).",
        "<b>Präteritum + Präteritum/Perfekt</b> — для одночасних або послідовних минулих подій.",
        "<b>Präsens + Futur I</b> — для майбутньої послідовності: <i>Wenn ich komme, werden wir reden.</i>",
        "У <b>непрямій мові</b>: минуле в прямій → Konjunktiv I Perfekt (<i>habe/sei + P II</i>) незалежно від того, який саме минулий був.",
      ],
      table: {
        headers: ["Послідовність", "Часова комбінація"],
        rows: [
          ["раніше + минуле", "Plusquamperfekt + Präteritum"],
          ["одночасно у минулому", "Prät. + Prät. (während)"],
          ["майбутня послідовність", "Präsens + Futur I"],
          ["непряма мова про минуле", "K.I Perfekt (habe/sei + P II)"],
        ],
      },
      examples: [
        { de: "Nachdem er gegessen hatte, ging er ins Bett.", uk: "Після того, як він поїв, він ліг спати." },
        { de: "Während ich kochte, las er Zeitung.", uk: "Поки я готував(ла), він читав газету." },
        { de: "Wenn du kommst, werden wir reden.", uk: "Коли прийдеш, ми поговоримо." },
        { de: "Sie sagte, sie habe das Buch gelesen.", uk: "Вона сказала, що прочитала книгу." },
        { de: "Bevor wir gingen, hatten wir alles geprüft.", uk: "Перш ніж піти, ми все перевірили." },
        { de: "Sobald ich es weiß, sage ich Bescheid.", uk: "Як тільки знатиму, скажу." },
        { de: "Er erklärte, er sei gestern in Wien gewesen.", uk: "Він пояснив, що вчора був у Відні." },
        { de: "Bis ich zurückkomme, wirst du gegessen haben.", uk: "До мого повернення ти вже поїси." },
      ],
      tip: "Раніше за минуле → <b>Plusquamperfekt</b>. Майбутнє після Präsens-підрядного → <b>Futur I/Präsens</b>.",
      mistakes: [
        { wrong: "Nachdem ich gegessen habe, ich ging ins Bett.", right: "Nachdem ich gegessen hatte, ging ich ins Bett." },
        { wrong: "Wenn ich werde kommen, …", right: "Wenn ich komme, …" },
      ],
      exercises: {}, prevSlug: "futur2",
    },
    extras: baseExtras(
      "Раніше за минуле → Plusquamperfekt. Майбутнє у wenn-Nebensatz → Präsens.",
      ["У підрядних після <i>wenn</i> ніколи не werden — лише Präsens.", "Непряма мова: минуле → habe/sei + P II (K.I)."],
      ["Plusqu. + Prät.", "Prät. одночасно.", "Präsens + Futur I.", "K.I Perfekt у непрямій мові."],
    ),
    exercises15: [
      { type: "mc", q: "Nachdem ich gegessen ___, ging ich los.",
        options: ["habe","hatte","werde haben","bin"], correct: 1 },
      { type: "mc", q: "Wenn ich morgen ___, werden wir reden.",
        options: ["komme","werde kommen","kam","gekommen bin"], correct: 0 },
      { type: "gap", q: "Während ich ___, las er. (kochen, Prät.)", answer: "kochte" },
      { type: "gap", q: "Bis ich zurückkomme, ___ du gegessen haben. (werden)", answer: "wirst" },
      { type: "tf", q: "У підрядному з wenn про майбутнє вживається Präsens.", correct: true },
      { type: "tf", q: "У непрямій мові минуле передається через Plusquamperfekt.", correct: false, explain: "Через K.I Perfekt." },
      { type: "match", prompt: "Послідовність → часи:", pairs: [
        { left: "раніше за минуле", right: "Plusqu. + Prät." },
        { left: "майбутня послідовність", right: "Präsens + Futur I" },
        { left: "одночасно", right: "Prät. + Prät." },
        { left: "непряма мова про минуле", right: "habe/sei + P II" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Wenn ich werde kommen, sagen wir Hallo.",
        correct: ["Wenn ich komme, sagen wir Hallo.","Wenn ich komme, werden wir Hallo sagen."] },
      { type: "correct", prompt: "Виправ:", wrong: "Nachdem ich gegessen habe, ging ich los.",
        correct: ["Nachdem ich gegessen hatte, ging ich los."] },
      { type: "multi", q: "Які речення коректні?", options: [
        "Wenn ich morgen Zeit habe, rufe ich an.","Wenn ich morgen Zeit werde haben, rufe ich an.",
        "Nachdem er kam, gingen wir.","Nachdem er gekommen war, gingen wir."], correct: [0,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["nachdem","gegessen","ich","hatte","ging","ins","Bett","ich"],
        correct: ["nachdem","ich","gegessen","hatte","ging","ich","ins","Bett"] },
      { type: "translate", prompt: "Переклади:", uk: "Поки я навчав(ла)ся, він готував.",
        de: ["Während ich lernte, kochte er."] },
      { type: "translate", prompt: "Переклади у непрямій мові:", uk: "Він сказав, що був у Відні.",
        de: ["Er sagte, er sei in Wien gewesen.","Er sagte, dass er in Wien gewesen sei."] },
      { type: "tf", q: "<i>sobald</i> часто йде з Präsens (для майбутнього).", correct: true },
      { type: "writeFree", prompt: "Напиши 2 речення з різними часовими комбінаціями.",
        sample: "Nachdem ich die Prüfung bestanden hatte, feierte ich mit Freunden. Sobald ich morgen ankomme, werde ich dich anrufen." },
    ],
  },
};
