// B2 · Verben — 12 повних уроків (просунуті дієслівні конструкції).
import type { B2Map } from "./_helpers";
const CAT = "Дієслова";

export const verbenB2: B2Map = {
  "konjunktiv2-vergangenheit": {
    lesson: {
      slug: "konjunktiv2-vergangenheit", level: "B2", category: CAT,
      titleDe: "Konjunktiv II der Vergangenheit", titleUk: "Konjunktiv II у минулому — нереальні події",
      goal: "Виражати нереальні, гіпотетичні або пропущені події в минулому.",
      explanation: [
        "<b>Konjunktiv II der Vergangenheit</b> = <b>hätte / wäre + Partizip II</b>. Це форма для того, чого <b>не сталося</b>, для докорів, шкодування та нереальних умов у минулому.",
        "Вибір <i>hätte</i> чи <i>wäre</i> залежить від того, як дієслово будує Perfekt: <i>haben-дієслова → hätte + P II</i>, <i>sein-дієслова (рух/зміна стану) → wäre + P II</i>.",
        "У складнопідрядному з <i>wenn</i> порядок такий самий, як у Perfekt: <i>Wenn ich Zeit gehabt hätte, wäre ich gekommen</i>. У головному реченні <i>hätte/wäre</i> стоїть на 2 місці, <i>P II</i> — в кінці.",
        "З <b>модальними дієсловами</b> в минулому діє «подвійний інфінітив»: <i>Ich hätte kommen können</i> = «Я міг би прийти (але не прийшов)».",
      ],
      table: {
        headers: ["Тип", "Приклад", "Переклад"],
        rows: [
          ["haben-дієслово", "Ich hätte das gemacht.", "Я б це зробив(ла)."],
          ["sein-дієслово", "Ich wäre früher gekommen.", "Я б прийшов(ла) раніше."],
          ["з модальним", "Er hätte kommen können.", "Він міг би прийти."],
          ["з wenn", "Wenn du gefragt hättest, hätte ich geholfen.", "Якби ти запитав, я б допоміг."],
          ["докір", "Das hättest du nicht sagen sollen.", "Ти не мав цього казати."],
        ],
      },
      examples: [
        { de: "Wenn ich gewusst hätte, wäre ich gekommen.", uk: "Якби я знав, я б прийшов." },
        { de: "Sie hätte den Zug fast verpasst.", uk: "Вона мало не спізнилася на потяг." },
        { de: "Ich wäre gerne mit euch gefahren.", uk: "Я б із задоволенням поїхав із вами." },
        { de: "Du hättest mich anrufen sollen.", uk: "Ти мав би мені зателефонувати." },
        { de: "Wir hätten das nicht tun dürfen.", uk: "Нам не можна було цього робити." },
        { de: "Ohne deine Hilfe wäre ich verloren gewesen.", uk: "Без твоєї допомоги я б пропав." },
        { de: "Er hätte fast einen Unfall gehabt.", uk: "Він мало не потрапив в аварію." },
        { de: "Ich hätte lieber Tee getrunken.", uk: "Я б краще випив чаю." },
      ],
      tip: "Формула: <b>hätte/wäre</b> (на 2 місці) + <b>Partizip II</b> (в кінці). З модальним — <b>hätte + Infinitiv + Modal-Infinitiv</b>.",
      mistakes: [
        { wrong: "Wenn ich gewusst würde, wäre ich gekommen.", right: "Wenn ich gewusst hätte, wäre ich gekommen." },
        { wrong: "Er hätte gekommen können.", right: "Er hätte kommen können." },
        { wrong: "Ich wäre das gemacht.", right: "Ich hätte das gemacht." },
      ],
      exercises: {}, nextSlug: "passiv-zeiten",
    },
    extras: {
      duration: 25, premium: true,
      learningGoals: [
        "утворювати Konjunktiv II минулого з hätte/wäre + P II",
        "правильно вживати «подвійний інфінітив» із модальними",
        "будувати нереальні умови у wenn-реченнях у минулому",
        "виражати докір, шкодування, ледь-не-подію",
      ],
      ruleBox: {
        rule: "<b>Konjunktiv II Vergangenheit = hätte/wäre + Partizip II</b>. З модальним у минулому — <b>hätte + Infinitiv + Modal-Infinitiv</b> (без ge-).",
        examples: [
          { de: "Ich hätte das nicht gesagt.", uk: "Я б цього не сказав(ла)." },
          { de: "Sie hätte kommen müssen.", uk: "Їй треба було прийти." },
        ],
      },
      ukrainianTips: [
        "Українське «я б зробив» = <i>ich würde machen</i> (теперішнє/майбутнє), але «я б був зробив» = <b>ich hätte gemacht</b> — саме про минуле.",
        "«Мало не...» німецькою — <b>fast + Konjunktiv II Vergangenheit</b>: <i>Ich hätte fast vergessen…</i>",
        "Докір «треба було» / «не треба було» = <b>hätte(n) + Infinitiv + sollen/dürfen</b>.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають форму нереальності («якби»)."],
        diffs: [
          "У німецькій нереальність у минулому — <b>окрема аналітична форма</b> (hätte/wäre + P II), у не проста частка «б».",
          "З модальними діє «подвійний інфінітив»: <i>hätte kommen können</i>, а не <i>hätte gekonnt kommen</i>.",
        ],
        traps: [
          "Не «wäre gemacht» — це пасив; для активного минулого потрібне <b>hätte gemacht</b>.",
          "У wenn-реченні <i>wenn</i> можна опустити, тоді дієслово на 1 місці: <i>Hätte ich Zeit gehabt, wäre ich gekommen</i>.",
        ],
      },
      summary: [
        "K.II Vergangenheit = <b>hätte/wäre + Partizip II</b>.",
        "haben-дієслова → hätte; sein-дієслова руху/зміни → wäre.",
        "З модальним — <b>hätte + Infinitiv + Modal-Infinitiv</b>.",
        "Функції: нереальна умова, докір, шкодування, «мало не».",
        "У wenn-реченні дієслово в кінці; у головному — на 2 місці.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ das nicht gemacht.", options: ["wäre","hätte","würde","habe"], correct: 1, explain: "machen → haben-дієслово." },
      { type: "mc", q: "Sie ___ früher gekommen.", options: ["hätte","wäre","würde","hatte"], correct: 1, explain: "kommen → sein-дієслово." },
      { type: "mc", q: "Er hätte kommen ___.", options: ["gekonnt","können","konnte","kann"], correct: 1, explain: "Подвійний інфінітив із модальним." },
      { type: "mc", q: "Wenn ich Zeit ___, wäre ich gekommen.", options: ["gehabt hätte","hätte","hatte","hätte gehabt"], correct: 0, explain: "У підрядному K.II Verg.: P II + hätte в кінці." },
      { type: "gap", q: "Du ___ mich anrufen sollen.", answer: "hättest", hint: "2 ос. одн. від haben у K.II." },
      { type: "gap", q: "Ich ___ fast vergessen! (haben)", answer: "hätte" },
      { type: "gap", q: "Wir ___ nicht so lange bleiben dürfen.", answer: "hätten" },
      { type: "gap", q: "Ohne dich ___ ich verloren gewesen. (sein)", answer: "wäre" },
      { type: "tf", q: "«kommen» у K.II Vergangenheit → <i>hätte gekommen</i>.", correct: false, explain: "sein-дієслово: <b>wäre gekommen</b>." },
      { type: "tf", q: "З модальним у минулому — «подвійний інфінітив».", correct: true },
      { type: "match", prompt: "Дієслово → допоміжне у K.II Vergangenheit:", pairs: [
        { left: "machen", right: "hätte" }, { left: "gehen", right: "wäre" },
        { left: "essen", right: "hätte" }, { left: "fahren", right: "wäre" },
        { left: "bleiben", right: "wäre" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Er hätte gekommen können.", correct: ["Er hätte kommen können."], explain: "Подвійний інфінітив без ge-." },
      { type: "multi", q: "Виділи форми K.II Vergangenheit:",
        options: ["hätte gemacht","würde machen","wäre gekommen","hätte kommen können","hatte gemacht","käme"], correct: [0,2,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["hätte","gewusst","ich","wenn","das"], correct: ["wenn","ich","das","gewusst","hätte"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Якби ти запитав, я б тобі допоміг.",
        de: ["Wenn du gefragt hättest, hätte ich dir geholfen.","Hättest du gefragt, hätte ich dir geholfen."] },
    ],
  },

  "passiv-zeiten": {
    lesson: {
      slug: "passiv-zeiten", level: "B2", category: CAT,
      titleDe: "Passiv in verschiedenen Zeitformen", titleUk: "Пасив у різних часових формах",
      goal: "Утворювати і впізнавати Vorgangspassiv у Präsens, Präteritum, Perfekt, Plusquamperfekt і Futur.",
      explanation: [
        "<b>Vorgangspassiv</b> (пасив дії) = <b>werden + Partizip II</b>. Змінюється лише <i>werden</i> — за часом і особою.",
        "У Perfekt і Plusquamperfekt Passiv <b>werden</b> перетворюється на <b>worden</b> (без ge-): <i>Das Haus ist gebaut worden</i>.",
        "Аґенс (виконавець) вводиться прийменником <b>von + Dat.</b> (особа/діяч) або <b>durch + Akk.</b> (засіб/причина): <i>Der Text wurde von dem Autor geschrieben / durch einen Sturm zerstört</i>.",
        "У Futur I Passiv — три компоненти: <b>werden (фін.) + P II + werden (Infinitiv)</b>: <i>Das Projekt wird abgeschlossen werden</i>.",
      ],
      table: {
        headers: ["Zeit", "Aktiv", "Passiv"],
        rows: [
          ["Präsens", "Man baut das Haus.", "Das Haus wird gebaut."],
          ["Präteritum", "Man baute das Haus.", "Das Haus wurde gebaut."],
          ["Perfekt", "Man hat gebaut.", "Das Haus ist gebaut worden."],
          ["Plusquamperfekt", "Man hatte gebaut.", "Das Haus war gebaut worden."],
          ["Futur I", "Man wird bauen.", "Das Haus wird gebaut werden."],
        ],
      },
      examples: [
        { de: "Der Brief wird geschrieben.", uk: "Лист пишеться." },
        { de: "Der Brief wurde gestern geschrieben.", uk: "Лист написали вчора." },
        { de: "Der Brief ist geschrieben worden.", uk: "Лист (уже) написали." },
        { de: "Der Brief war schon geschrieben worden, als ich kam.", uk: "Лист уже був написаний, коли я прийшов." },
        { de: "Der Brief wird morgen geschrieben werden.", uk: "Лист напишуть завтра." },
        { de: "Das Fenster wurde von einem Kind zerbrochen.", uk: "Вікно розбила дитина." },
        { de: "Die Straße wurde durch das Hochwasser beschädigt.", uk: "Дорогу пошкодило повінню." },
        { de: "Hier wird nicht geraucht.", uk: "Тут не курять." },
      ],
      tip: "Головне: <b>werden + P II</b>. У Perfekt/Plusq. — <b>worden</b> замість geworden. von = хто, durch = чим.",
      mistakes: [
        { wrong: "Das Haus ist gebaut geworden.", right: "Das Haus ist gebaut worden." },
        { wrong: "Der Brief wird von den Sturm zerstört.", right: "Der Brief wird durch den Sturm zerstört." },
        { wrong: "Das Buch wurde geschrieben von der Autorin.", right: "Das Buch wurde von der Autorin geschrieben." },
      ],
      exercises: {}, prevSlug: "konjunktiv2-vergangenheit", nextSlug: "passiv-modalverben",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["утворювати Passiv в усіх основних часах", "розрізняти von і durch", "розпізнавати worden у Perfekt Passiv", "будувати Futur Passiv (з двома werden)"],
      ruleBox: {
        rule: "<b>Passiv = werden + Partizip II</b>. У Perfekt/Plusq.: <b>sein + P II + worden</b>. Futur: <b>werden + P II + werden</b>.",
        examples: [
          { de: "Das Auto wird repariert.", uk: "Машину ремонтують." },
          { de: "Das Auto ist repariert worden.", uk: "Машину відремонтували." },
        ],
      },
      ukrainianTips: [
        "Українською пасив часто передається через «-ся» або невизначено-особову форму («лист написали»).",
        "«von» = «ким» (жива особа/автор), «durch» = «через/чим» (причина, засіб).",
        "У Perfekt Passiv допоміжне завжди <b>sein</b>, навіть якщо основне дієслово в активі йде з haben.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають пасивні конструкції для акценту на об'єкті."],
        diffs: [
          "Німецька має чіткий морфологічний пасив (werden + P II), українська обходиться суфіксами -ся/-но.",
          "У Futur Passiv два <i>werden</i> — це нормально й обов'язково.",
        ],
        traps: [
          "Не «ist gebaut geworden» — тільки <b>worden</b> у пасиві.",
          "Аґенс без прийменника — це помилка: <i>*wurde ein Kind zerbrochen</i>.",
        ],
      },
      summary: [
        "Präsens: <i>wird + P II</i>.", "Präteritum: <i>wurde + P II</i>.",
        "Perfekt: <i>ist + P II + worden</i>.", "Plusq.: <i>war + P II + worden</i>.",
        "Futur: <i>wird + P II + werden</i>. Аґенс: von (хто) / durch (чим).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Präsens Passiv від «bauen»:", options: ["ist gebaut","wird gebaut","hat gebaut","wurde gebaut"], correct: 1 },
      { type: "mc", q: "Perfekt Passiv:", options: ["ist gebaut worden","hat gebaut","ist gebaut geworden","wurde gebaut"], correct: 0 },
      { type: "mc", q: "«Дорогу пошкодило повінню» — прийменник:", options: ["von","durch","mit","für"], correct: 1, explain: "Стихія → durch." },
      { type: "mc", q: "Futur I Passiv:", options: ["wird gebaut","wird bauen","wird gebaut werden","ist gebaut worden"], correct: 2 },
      { type: "gap", q: "Der Text ___ (schreiben, Präs. Passiv).", answer: "wird geschrieben" },
      { type: "gap", q: "Das Haus ___ 1990 ___ ___. (bauen — Perfekt Passiv)", answer: "ist gebaut worden" },
      { type: "gap", q: "Der Brief wurde ___ meiner Mutter geschrieben.", answer: "von" },
      { type: "gap", q: "Die Stadt wurde ___ den Krieg zerstört.", answer: "durch" },
      { type: "tf", q: "У Perfekt Passiv потрібна форма «worden», не «geworden».", correct: true },
      { type: "tf", q: "У Futur Passiv є два «werden».", correct: true },
      { type: "match", prompt: "Час → форма Passiv «machen»:", pairs: [
        { left: "Präs.", right: "wird gemacht" },
        { left: "Prät.", right: "wurde gemacht" },
        { left: "Perf.", right: "ist gemacht worden" },
        { left: "Plusq.", right: "war gemacht worden" },
        { left: "Futur", right: "wird gemacht werden" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das Haus ist gebaut geworden.", correct: ["Das Haus ist gebaut worden."] },
      { type: "multi", q: "Виділи форми Passiv:",
        options: ["wird gebaut","hat gebaut","wurde geschrieben","ist gefahren","ist gebaut worden","geht"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення (Perfekt Passiv):",
        words: ["worden","der","ist","geschrieben","Brief"], correct: ["der","Brief","ist","geschrieben","worden"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Тут не курять.", de: ["Hier wird nicht geraucht."] },
    ],
  },

  "passiv-modalverben": {
    lesson: {
      slug: "passiv-modalverben", level: "B2", category: CAT,
      titleDe: "Passiv mit Modalverben", titleUk: "Пасив із модальними дієсловами",
      goal: "Будувати пасив з модальними дієсловами в різних часах.",
      explanation: [
        "Формула: <b>Modalverb + Partizip II + werden (Infinitiv)</b>. Модальне змінюється, <i>werden</i> у кінці — в інфінітиві.",
        "У Präteritum усе просто: модальне в Präteritum + P II + werden: <i>Das musste gemacht werden</i>.",
        "У Perfekt із модальним працює <b>подвійний інфінітив</b>: <b>haben + P II + werden + Modal-Infinitiv</b>. Наприклад: <i>Das hat gemacht werden müssen</i>.",
        "У підрядному з подвійним інфінітивом <i>hat/hatte</i> йде <b>перед</b> усім блоком: <i>…, weil das <b>hat</b> gemacht werden müssen</i>.",
      ],
      table: {
        headers: ["Zeit", "Приклад"],
        rows: [
          ["Präsens", "Das muss gemacht werden."],
          ["Präteritum", "Das musste gemacht werden."],
          ["Perfekt", "Das hat gemacht werden müssen."],
          ["Plusquamperfekt", "Das hatte gemacht werden müssen."],
          ["K.II Verg.", "Das hätte gemacht werden müssen."],
        ],
      },
      examples: [
        { de: "Die Arbeit muss bis morgen erledigt werden.", uk: "Роботу треба виконати до завтра." },
        { de: "Das Auto konnte nicht repariert werden.", uk: "Машину не вдалося відремонтувати." },
        { de: "Hier darf nicht geparkt werden.", uk: "Тут паркуватися заборонено." },
        { de: "Die Regeln sollten eingehalten werden.", uk: "Правил слід дотримуватися." },
        { de: "Das Formular musste sofort ausgefüllt werden.", uk: "Анкету треба було одразу заповнити." },
        { de: "Der Fehler hätte vermieden werden können.", uk: "Помилки можна було уникнути." },
        { de: "Es hat entschieden werden müssen.", uk: "Це треба було вирішити." },
        { de: "Die Wohnung sollte renoviert werden.", uk: "Квартиру мали б відремонтувати." },
      ],
      tip: "Скелет: <b>[Modal] … [P II] werden</b>. У Perfekt додається <b>haben</b> і подвійний інфінітив у кінці.",
      mistakes: [
        { wrong: "Das muss gemacht sein.", right: "Das muss gemacht werden." },
        { wrong: "Das hat gemacht werden gemusst.", right: "Das hat gemacht werden müssen." },
        { wrong: "Hier darf man nicht parken werden.", right: "Hier darf nicht geparkt werden." },
      ],
      exercises: {}, prevSlug: "passiv-zeiten", nextSlug: "passiversatz-basis",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["будувати Passiv + Modalverb у Präsens/Prät.", "розуміти подвійний інфінітив у Perfekt Passiv", "правильно ставити haben у підрядному", "виражати заборону, обов'язок, можливість у пасиві"],
      ruleBox: {
        rule: "<b>Modal + P II + werden</b>. У Perfekt: <b>haben + P II + werden + Modal-Infinitiv</b>.",
        examples: [
          { de: "Das muss gemacht werden.", uk: "Це треба зробити." },
          { de: "Das hat gemacht werden müssen.", uk: "Це треба було зробити." },
        ],
      },
      ukrainianTips: [
        "«Треба зробити» / «Слід зробити» / «Можна зробити» — усе це пасив із модальним: <i>muss/soll/kann + P II + werden</i>.",
        "Українською часто говоримо просто «треба…», але в німецькій потрібне повне пасивне речення з <i>werden</i>.",
        "Заборона: <i>darf nicht + P II + werden</i>.",
      ],
      languageComparison: {
        commons: ["І в німецькій, і в українській модальність поєднується з пасивом."],
        diffs: ["Німецька має чітку триступеневу структуру: модальне + Partizip II + werden."],
        traps: ["Не «gemacht sein» (це стан), а «gemacht werden» (дія).", "У Perfekt — тільки <b>haben</b>, ніколи sein."],
      },
      summary: [
        "Präs./Prät.: Modal + P II + werden.",
        "Perfekt: haben + P II + werden + Modal-Inf.",
        "K.II Verg.: hätte + P II + werden + Modal-Inf.",
        "У підрядному haben/hatte йде перед блоком.",
        "Заборона: darf nicht + P II + werden.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das ___ (müssen) heute gemacht werden.", options: ["muss","musst","müssen","musste"], correct: 0 },
      { type: "mc", q: "Perfekt: Das hat gemacht werden ___.", options: ["müssen","gemusst","müsst","musste"], correct: 0 },
      { type: "mc", q: "Заборона паркуватися:", options: ["Hier wird nicht geparkt.","Hier darf nicht geparkt werden.","Hier ist nicht geparkt.","Hier soll parken."], correct: 1 },
      { type: "mc", q: "Prät.: Das ___ repariert werden.", options: ["konnte","kann","können","gekonnt"], correct: 0 },
      { type: "gap", q: "Der Bericht ___ heute noch geschrieben werden. (müssen, Präs.)", answer: "muss" },
      { type: "gap", q: "Die Fehler hätten vermieden ___ ___. (werden + können)", answer: "werden können" },
      { type: "gap", q: "Das Fenster ___ nicht geöffnet werden. (können, Prät.)", answer: "konnte" },
      { type: "gap", q: "Hier ___ nicht geraucht werden. (dürfen, Präs.)", answer: "darf" },
      { type: "tf", q: "У Perfekt Passiv + модальне допоміжне — sein.", correct: false, explain: "Тільки haben." },
      { type: "tf", q: "«muss gemacht werden» — Präsens Passiv із модальним.", correct: true },
      { type: "match", prompt: "Значення → модальне:", pairs: [
        { left: "обов'язок", right: "müssen" }, { left: "заборона", right: "dürfen (nicht)" },
        { left: "порада", right: "sollen" }, { left: "можливість", right: "können" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das hat gemacht werden gemusst.",
        correct: ["Das hat gemacht werden müssen."], explain: "Подвійний інфінітив: müssen, не gemusst." },
      { type: "multi", q: "Які речення — Passiv із модальним?",
        options: ["Das muss gemacht werden.","Das muss man machen.","Hier darf nicht geraucht werden.","Er kann kommen.","Es soll geprüft werden."], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["werden","muss","gemacht","das","sofort"], correct: ["das","muss","sofort","gemacht","werden"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Це треба було зробити вчора.",
        de: ["Das hätte gestern gemacht werden müssen.","Das musste gestern gemacht werden."] },
    ],
  },

  "passiversatz-basis": {
    lesson: {
      slug: "passiversatz-basis", level: "B2", category: CAT,
      titleDe: "Passiversatzformen: Grundlagen", titleUk: "Основи альтернатив до пасиву",
      goal: "Замінювати класичний пасив компактнішими конструкціями (<i>man</i>, <i>sich lassen</i>, <i>sein + zu + Inf.</i>, прикметники на -bar).",
      explanation: [
        "У німецькій пасив часто <b>замінюють</b> активними конструкціями, які звучать природніше або коротше.",
        "<b>1) man + Aktiv</b>: <i>Das macht man so</i> = «Так роблять». Найпоширеніша заміна в розмовній мові.",
        "<b>2) sich lassen + Infinitiv</b> = «можна зробити»: <i>Das lässt sich reparieren</i> = «Це можна відремонтувати» = <i>Das kann repariert werden</i>.",
        "<b>3) sein + zu + Infinitiv</b> = обов'язок або можливість: <i>Der Brief ist heute zu schreiben</i> = «Лист треба написати сьогодні»; <i>Das ist zu verstehen</i> = «Це можна зрозуміти».",
        "<b>4) Прикметники на -bar / -lich</b>: <i>lesbar</i> = «читабельний, який можна прочитати», <i>machbar, verständlich</i>.",
      ],
      table: {
        headers: ["Пасив", "Альтернатива", "Значення"],
        rows: [
          ["Das kann gemacht werden.", "Das lässt sich machen.", "можливість"],
          ["Das muss gemacht werden.", "Das ist zu machen.", "обов'язок"],
          ["Das kann gelesen werden.", "Das ist lesbar.", "-bar-прикметник"],
          ["Das wird oft gesagt.", "Das sagt man oft.", "man + Aktiv"],
          ["Das kann verstanden werden.", "Das ist verständlich.", "-lich-прикметник"],
        ],
      },
      examples: [
        { de: "Diese Aufgabe lässt sich leicht lösen.", uk: "Це завдання легко вирішити." },
        { de: "Das Problem ist zu lösen.", uk: "Проблему треба (можна) вирішити." },
        { de: "Der Text ist gut lesbar.", uk: "Текст добре читається." },
        { de: "Das macht man in Deutschland nicht.", uk: "У Німеччині так не роблять." },
        { de: "Die Tür lässt sich nicht öffnen.", uk: "Двері не відчиняються." },
        { de: "Der Fehler ist noch zu korrigieren.", uk: "Помилку ще треба виправити." },
        { de: "Die Regel ist verständlich.", uk: "Правило зрозуміле." },
        { de: "Solche Probleme sind lösbar.", uk: "Такі проблеми можна вирішити." },
      ],
      tip: "Пам'ятай трійку заміни: <b>sich lassen</b> (можна), <b>sein + zu + Inf.</b> (треба/можна), <b>-bar</b> (можна що зробити).",
      mistakes: [
        { wrong: "Das lässt reparieren.", right: "Das lässt sich reparieren." },
        { wrong: "Der Brief ist zu geschrieben.", right: "Der Brief ist zu schreiben." },
        { wrong: "Das ist machen.", right: "Das ist zu machen." },
      ],
      exercises: {}, prevSlug: "passiv-modalverben", nextSlug: "verben-feste-praep",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: [
        "заміняти <i>kann/muss + P II + werden</i> компактнішими формами",
        "правильно вживати <i>sich lassen + Inf.</i>",
        "будувати <i>sein + zu + Inf.</i>",
        "утворювати прикметники на -bar",
      ],
      ruleBox: {
        rule: "<b>sich lassen + Inf.</b> = kann … werden. <b>sein + zu + Inf.</b> = muss/kann … werden. <b>-bar</b> = kann … werden.",
        examples: [
          { de: "Das lässt sich machen. = Das kann gemacht werden.", uk: "Це можна зробити." },
          { de: "Das ist zu machen. = Das muss/kann gemacht werden.", uk: "Це треба/можна зробити." },
        ],
      },
      ukrainianTips: [
        "Українське «двері не відчиняються» → німецькою природньо <i>Die Tür lässt sich nicht öffnen</i>.",
        "«Це реально зробити» → <i>Das lässt sich machen / ist machbar</i>.",
        "Прикметники на -bar завжди мають значення пасивної можливості.",
      ],
      languageComparison: {
        commons: ["І українська, і німецька уникають повторення пасиву через словотвір і безособові форми."],
        diffs: ["Німецькі -bar-прикметники дуже продуктивні; в українській переклад залежить від контексту («придатний до…», «можливий»)."],
        traps: ["<i>sich lassen</i> без <b>sich</b> — груба помилка.", "Забувають <b>zu</b> в конструкції <i>sein + zu + Inf.</i>."],
      },
      summary: [
        "man + Aktiv — найпростіша заміна.",
        "sich lassen + Inf. = «можна зробити».",
        "sein + zu + Inf. = «треба/можна».",
        "-bar/-lich = «можна що зробити».",
        "Усі ці форми — <b>активні за формою, пасивні за значенням</b>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "«Це можна зробити» найкоротше:", options: ["Das kann gemacht werden.","Das lässt sich machen.","Das wird gemacht.","Das ist gemacht."], correct: 1 },
      { type: "mc", q: "«Лист треба написати»:", options: ["Der Brief ist zu schreiben.","Der Brief schreibt.","Der Brief ist geschrieben.","Der Brief hat schreiben."], correct: 0 },
      { type: "mc", q: "«Читабельний»:", options: ["lesend","lesbar","gelesen","leslich"], correct: 1 },
      { type: "mc", q: "«Двері не відчиняються» природньо:", options: ["Die Tür öffnet nicht.","Die Tür lässt sich nicht öffnen.","Die Tür ist nicht öffnen.","Die Tür wird nicht."], correct: 1 },
      { type: "gap", q: "Das Problem ___ ___ lösen. (sich lassen)", answer: "lässt sich" },
      { type: "gap", q: "Der Fehler ist noch zu ___.", answer: "korrigieren" },
      { type: "gap", q: "Der Text ist gut ___ (можна читати).", answer: "lesbar" },
      { type: "gap", q: "So ___ man das nicht.", answer: "macht" },
      { type: "tf", q: "«Das ist zu machen» = «Das muss/kann gemacht werden».", correct: true },
      { type: "tf", q: "«sich lassen» можна вживати без «sich».", correct: false },
      { type: "match", prompt: "Пасив → заміна:", pairs: [
        { left: "Das kann verstanden werden.", right: "Das ist verständlich." },
        { left: "Das kann gemacht werden.", right: "Das lässt sich machen." },
        { left: "Das muss gemacht werden.", right: "Das ist zu machen." },
        { left: "Das wird oft gesagt.", right: "Das sagt man oft." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das lässt reparieren.", correct: ["Das lässt sich reparieren."] },
      { type: "multi", q: "Виділи Passiversatz-форми:",
        options: ["lässt sich machen","wird gemacht","ist zu machen","macht","machbar","hat gemacht"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["Aufgabe","lösen","sich","die","lässt","leicht"], correct: ["die","Aufgabe","lässt","sich","leicht","lösen"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Це можна легко зробити.",
        de: ["Das lässt sich leicht machen.","Das ist leicht zu machen.","Das ist leicht machbar."] },
    ],
  },

  "verben-feste-praep": {
    lesson: {
      slug: "verben-feste-praep", level: "B2", category: CAT,
      titleDe: "Verben mit festen Präpositionen", titleUk: "Дієслова зі сталими прийменниками",
      goal: "Вивчити основні пари «дієслово + прийменник» і правильно вибирати відмінок.",
      explanation: [
        "Багато німецьких дієслів вимагають <b>певного прийменника</b>, а разом із ним — <b>певного відмінка</b>. Це треба вчити напам'ять як лексичну одиницю.",
        "Найважливіші приклади: <b>warten auf + Akk.</b>, <b>denken an + Akk.</b>, <b>sich freuen auf/über + Akk.</b>, <b>sich interessieren für + Akk.</b>, <b>bitten um + Akk.</b>, <b>sprechen über/von + Dat.</b>, <b>träumen von + Dat.</b>, <b>teilnehmen an + Dat.</b>.",
        "Якщо йдеться про <b>річ</b>, ми часто використовуємо <b>da(r)-компонент</b>: <i>Ich denke daran</i>, <i>Ich warte darauf</i>. Про <b>людину</b> — <b>an/auf + займенник у відмінку</b>: <i>Ich denke an dich</i>.",
        "У запитаннях про річ: <b>wo(r)- + прийменник</b>: <i>Worauf wartest du? / Woran denkst du?</i> Про людину: <b>Präp. + wen/wem</b>: <i>Auf wen wartest du?</i>",
      ],
      table: {
        headers: ["Verb", "Präp. + Fall", "Приклад"],
        rows: [
          ["warten", "auf + Akk.", "Ich warte auf den Bus."],
          ["denken", "an + Akk.", "Ich denke an dich."],
          ["sich freuen", "auf + Akk. (майбутнє)", "Ich freue mich auf den Urlaub."],
          ["sich freuen", "über + Akk. (те, що вже є)", "Ich freue mich über das Geschenk."],
          ["sich interessieren", "für + Akk.", "Er interessiert sich für Musik."],
          ["bitten", "um + Akk.", "Sie bittet um Hilfe."],
          ["teilnehmen", "an + Dat.", "Wir nehmen an dem Kurs teil."],
          ["träumen", "von + Dat.", "Ich träume von einer Reise."],
        ],
      },
      examples: [
        { de: "Ich warte seit einer Stunde auf den Bus.", uk: "Я вже годину чекаю на автобус." },
        { de: "Sie denkt oft an ihre Familie.", uk: "Вона часто думає про сім'ю." },
        { de: "Wir freuen uns auf das Wochenende.", uk: "Ми чекаємо на вихідні." },
        { de: "Er interessiert sich für Politik.", uk: "Він цікавиться політикою." },
        { de: "Sie bittet ihre Freundin um Rat.", uk: "Вона просить у подруги поради." },
        { de: "Woran denkst du gerade?", uk: "Про що ти зараз думаєш?" },
        { de: "Ich freue mich darüber, dass du kommst.", uk: "Я радий, що ти прийдеш." },
        { de: "Auf wen wartet ihr?", uk: "Кого ви чекаєте?" },
      ],
      tip: "Пара <b>дієслово + прийменник</b> = один запис у зошиті. Річ → <b>da(r)-</b>, людина → <b>Präp. + займенник</b>.",
      mistakes: [
        { wrong: "Ich warte auf dem Bus.", right: "Ich warte auf den Bus." },
        { wrong: "Ich denke über dich.", right: "Ich denke an dich." },
        { wrong: "Ich interessiere mich in Musik.", right: "Ich interessiere mich für Musik." },
      ],
      exercises: {}, prevSlug: "passiversatz-basis", nextSlug: "infinitivkonstruktionen",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["знати 15–20 базових пар V+Präp.", "правильно вибирати Akk. чи Dat.", "будувати da(r)- і wo(r)-форми", "уникати кальок із української"],
      ruleBox: {
        rule: "Вчи <b>дієслово + прийменник + відмінок</b> як одне ціле. Річ → <b>daran/darauf/davon</b>; людина → <b>Präp. + Personalpronomen</b>.",
        examples: [
          { de: "Ich denke an dich.", uk: "Я думаю про тебе." },
          { de: "Ich denke daran.", uk: "Я думаю про це." },
        ],
      },
      ukrainianTips: [
        "Українське «чекати на» = німецьке <b>warten auf + Akk.</b> (не Dat.!).",
        "«Думати про» = <b>denken an + Akk.</b>, не «über».",
        "«Цікавитися чимось» = <b>sich interessieren für + Akk.</b>, не «in» / «mit».",
      ],
      languageComparison: {
        commons: ["Обидві мови мають дієслівне керування."],
        diffs: ["Німецька частіше вимагає прийменника там, де українська обходиться відмінком, і навпаки."],
        traps: ["Sich freuen auf (майбутнє) vs. über (актуальне) — не змішувати."],
      },
      summary: [
        "V+Präp = одна лексична одиниця.",
        "Auf/an/über/für — часто з Akk.",
        "Von/mit/zu/aus/an (місце) — з Dat.",
        "Річ → daran; людина → an ihn/sie.",
        "Питання: worauf/woran vs. auf wen/an wen.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich warte ___ den Bus.", options: ["auf","an","für","über"], correct: 0 },
      { type: "mc", q: "Sie interessiert sich ___ Musik.", options: ["in","mit","für","an"], correct: 2 },
      { type: "mc", q: "Wir freuen uns ___ das Wochenende (майбутнє).", options: ["über","auf","für","an"], correct: 1 },
      { type: "mc", q: "Er denkt oft ___ seine Familie.", options: ["über","an","auf","für"], correct: 1 },
      { type: "gap", q: "Sie bittet ihre Mutter ___ Hilfe.", answer: "um" },
      { type: "gap", q: "Wir nehmen ___ dem Deutschkurs teil.", answer: "an" },
      { type: "gap", q: "Er träumt ___ einem Haus am Meer.", answer: "von" },
      { type: "gap", q: "___ denkst du? (про що)", answer: "Woran" },
      { type: "tf", q: "«warten auf» вимагає Dativ.", correct: false, explain: "Akkusativ." },
      { type: "tf", q: "Про річ використовуємо da(r)-форму: daran, darauf.", correct: true },
      { type: "match", prompt: "Verb → Präp.:", pairs: [
        { left: "warten", right: "auf + Akk." }, { left: "denken", right: "an + Akk." },
        { left: "bitten", right: "um + Akk." }, { left: "träumen", right: "von + Dat." },
        { left: "teilnehmen", right: "an + Dat." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich interessiere mich in Sport.", correct: ["Ich interessiere mich für Sport."] },
      { type: "multi", q: "Правильні пари:",
        options: ["warten auf + Akk.","denken an + Akk.","freuen mit","bitten um + Akk.","träumen mit","teilnehmen an + Dat."], correct: [0,1,3,5] },
      { type: "order", prompt: "Склади речення:",
        words: ["auf","Bus","warte","den","ich"], correct: ["ich","warte","auf","den","Bus"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я думаю про тебе.", de: ["Ich denke an dich."] },
    ],
  },

  infinitivkonstruktionen: {
    lesson: {
      slug: "infinitivkonstruktionen", level: "B2", category: CAT,
      titleDe: "Infinitivkonstruktionen", titleUk: "Інфінітивні конструкції",
      goal: "Використовувати основні інфінітивні звороти: zu + Inf., um zu, ohne zu, statt zu, anstatt … zu.",
      explanation: [
        "Більшість дієслів у німецькій вимагає <b>zu + Infinitiv</b>, коли за ними йде інше дієслово: <i>Ich versuche, früher zu kommen</i>.",
        "<b>um … zu + Inf.</b> = мета («щоб»): <i>Ich lerne Deutsch, um in Berlin zu arbeiten</i>. Обов'язкова умова: <b>суб'єкт головного і підрядного речення однаковий</b>, інакше — <i>damit</i>.",
        "<b>ohne … zu + Inf.</b> = «не роблячи чогось»: <i>Er ging, ohne zu grüßen</i>.",
        "<b>(an)statt … zu + Inf.</b> = «замість того, щоб»: <i>Statt zu lernen, spielt er</i>.",
        "Після <b>Modalverben, sehen, hören, lassen, gehen (у складі виразів)</b> — <b>інфінітив без zu</b>: <i>Ich muss gehen / Ich höre ihn singen</i>.",
      ],
      table: {
        headers: ["Конструкція", "Значення", "Приклад"],
        rows: [
          ["zu + Inf.", "залежний інфінітив", "Ich hoffe, dich zu sehen."],
          ["um zu + Inf.", "мета", "Ich lerne, um zu bestehen."],
          ["ohne zu + Inf.", "заперечення дії", "Er ging, ohne zu bezahlen."],
          ["statt zu + Inf.", "заміна", "Statt zu lernen, schläft er."],
          ["без zu", "після Modalverben, sehen, hören, lassen", "Ich muss gehen."],
        ],
      },
      examples: [
        { de: "Ich habe vor, nächstes Jahr umzuziehen.", uk: "Я планую наступного року переїхати." },
        { de: "Sie kam, um mir zu helfen.", uk: "Вона прийшла, щоб мені допомогти." },
        { de: "Er verließ das Zimmer, ohne ein Wort zu sagen.", uk: "Він вийшов з кімнати, не сказавши ні слова." },
        { de: "Statt zu arbeiten, schaut er fern.", uk: "Замість того, щоб працювати, він дивиться телевізор." },
        { de: "Es ist wichtig, jeden Tag zu üben.", uk: "Важливо тренуватися щодня." },
        { de: "Ich lasse mein Auto reparieren.", uk: "Я віддаю машину в ремонт." },
        { de: "Ich höre die Kinder lachen.", uk: "Я чую, як діти сміються." },
        { de: "Vergiss nicht, das Fenster zuzumachen.", uk: "Не забудь зачинити вікно." },
      ],
      tip: "Роздільні дієслова: <b>zu ставиться між префіксом і основою</b>: <i>aufzustehen, mitzunehmen</i>.",
      mistakes: [
        { wrong: "Ich versuche kommen früher.", right: "Ich versuche, früher zu kommen." },
        { wrong: "Ich muss zu gehen.", right: "Ich muss gehen." },
        { wrong: "Er ging ohne zu bezahlen nicht.", right: "Er ging, ohne zu bezahlen." },
      ],
      exercises: {}, prevSlug: "verben-feste-praep", nextSlug: "funktionsverbgefuege-basis",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["правильно ставити zu (у т.ч. з роздільними дієсловами)", "використовувати um/ohne/statt zu", "розрізняти um zu vs. damit", "знати винятки без zu"],
      ruleBox: {
        rule: "<b>um zu</b> — мета при однаковому суб'єкті; <b>damit</b> — коли суб'єкти різні. Після Modalverben — <b>без zu</b>.",
        examples: [
          { de: "Ich lerne, um zu bestehen.", uk: "(один суб'єкт) — um zu." },
          { de: "Ich helfe dir, damit du bestehst.", uk: "(різні суб'єкти) — damit." },
        ],
      },
      ukrainianTips: [
        "Українське «щоб» без займенника → <b>um … zu</b> (той самий суб'єкт).",
        "«щоб він…» → <b>damit</b>.",
        "«не сказавши» = <b>ohne … zu sagen</b>, а не «ohne sagen».",
      ],
      languageComparison: {
        commons: ["Обидві мови мають цільові й наслідкові підрядні."],
        diffs: ["Німецька розрізняє інфінітивну (um zu) і повну (damit) конструкції за суб'єктом."],
        traps: ["Не забувати кому перед <i>um</i>, <i>ohne</i>, <i>statt</i>."],
      },
      summary: [
        "zu + Inf. — базовий залежний інфінітив.",
        "um zu — мета (один суб'єкт).",
        "ohne zu — заперечення дії.",
        "statt zu — заміна.",
        "Modalverben, sehen, hören, lassen → без zu.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe vor, nach Berlin ___.", options: ["fahren","zu fahren","gefahren","fahre"], correct: 1 },
      { type: "mc", q: "Ich lerne Deutsch, ___ in Berlin zu arbeiten.", options: ["damit","um","für","ohne"], correct: 1 },
      { type: "mc", q: "«без zu» після якого дієслова?", options: ["versuchen","können","hoffen","planen"], correct: 1 },
      { type: "mc", q: "Er ging, ___ zu grüßen.", options: ["um","ohne","statt","damit"], correct: 1 },
      { type: "gap", q: "Es ist wichtig, jeden Tag ___ üben.", answer: "zu" },
      { type: "gap", q: "Vergiss nicht, ___ (aufstehen) früh!", answer: "aufzustehen" },
      { type: "gap", q: "Ich helfe dir, ___ du die Prüfung bestehst.", answer: "damit" },
      { type: "gap", q: "Er ging weg, ohne ein Wort ___ sagen.", answer: "zu" },
      { type: "tf", q: "«um zu» вживається, коли суб'єкти головного і підрядного однакові.", correct: true },
      { type: "tf", q: "Після Modalverben ставимо «zu» перед інфінітивом.", correct: false },
      { type: "match", prompt: "Функція → конструкція:", pairs: [
        { left: "мета", right: "um zu" }, { left: "без певної дії", right: "ohne zu" },
        { left: "замість", right: "statt zu" }, { left: "різні суб'єкти", right: "damit" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich muss zu gehen.", correct: ["Ich muss gehen."] },
      { type: "multi", q: "Які інфінітиви вимагають «zu»?",
        options: ["hoffen","müssen","versuchen","können","planen","sehen"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["zu","um","fahren","Berlin","lerne","nach","Deutsch","ich"],
        correct: ["ich","lerne","Deutsch","um","nach","Berlin","zu","fahren"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Він пішов, нічого не сказавши.",
        de: ["Er ging, ohne etwas zu sagen.","Er ging weg, ohne etwas zu sagen."] },
    ],
  },

  "funktionsverbgefuege-basis": {
    lesson: {
      slug: "funktionsverbgefuege-basis", level: "B2", category: CAT,
      titleDe: "Funktionsverbgefüge: Grundlagen", titleUk: "Основи Funktionsverbgefüge",
      goal: "Розпізнавати й вживати найпоширеніші сталі дієслівно-іменникові пари офіційного стилю.",
      explanation: [
        "<b>Funktionsverbgefüge (FVG)</b> — сталі сполуки типу <i>дієслово + (Präp.) + іменник</i>, де основне значення несе <b>іменник</b>, а дієслово (Funktionsverb) виконує лише граматичну роль.",
        "Часто FVG замінюється одним дієсловом, але <b>звучить формальніше</b> й типове для офіційного, юридичного, наукового стилю.",
        "Приклади дієслів у FVG: <b>bringen, kommen, stellen, geben, nehmen, treffen, ziehen, stehen</b>.",
        "Основні патерни: <i>zur Sprache bringen</i> (порушити тему) = <i>ansprechen</i>; <i>eine Entscheidung treffen</i> = <i>entscheiden</i>; <i>in Kraft treten</i> = <i>gelten</i>; <i>zur Verfügung stellen</i> = <i>bereitstellen</i>.",
      ],
      table: {
        headers: ["FVG", "Одиничне дієслово", "Значення"],
        rows: [
          ["eine Entscheidung treffen", "entscheiden", "прийняти рішення"],
          ["in Betracht ziehen", "erwägen", "розглянути"],
          ["zur Verfügung stellen", "bereitstellen", "надати в розпорядження"],
          ["in Kraft treten", "gelten", "набути чинності"],
          ["zur Sprache bringen", "ansprechen", "порушити (тему)"],
          ["Rücksicht nehmen (auf)", "berücksichtigen", "враховувати"],
          ["Hilfe leisten", "helfen", "надавати допомогу"],
          ["in Frage kommen", "möglich sein", "бути можливим варіантом"],
        ],
      },
      examples: [
        { de: "Wir müssen eine Entscheidung treffen.", uk: "Ми повинні прийняти рішення." },
        { de: "Das Gesetz tritt am 1. Januar in Kraft.", uk: "Закон набуває чинності 1 січня." },
        { de: "Wir stellen Ihnen die Räume zur Verfügung.", uk: "Ми надаємо вам приміщення." },
        { de: "Diese Möglichkeit kommt nicht in Frage.", uk: "Цей варіант неможливий." },
        { de: "Er hat das Thema zur Sprache gebracht.", uk: "Він порушив цю тему." },
        { de: "Bitte nehmen Sie darauf Rücksicht.", uk: "Будь ласка, зважте на це." },
        { de: "Wir müssen alle Faktoren in Betracht ziehen.", uk: "Ми маємо розглянути всі фактори." },
        { de: "Die Feuerwehr leistete schnell Hilfe.", uk: "Пожежники швидко надали допомогу." },
      ],
      tip: "FVG вчи <b>цілими блоками</b>. Дієслово в FVG зазвичай <b>не має свого повного значення</b> — його не можна перекладати окремо.",
      mistakes: [
        { wrong: "Wir machen eine Entscheidung.", right: "Wir treffen eine Entscheidung." },
        { wrong: "Das Gesetz kommt in Kraft.", right: "Das Gesetz tritt in Kraft." },
        { wrong: "Ich stelle dir zur Verfügung das Auto.", right: "Ich stelle dir das Auto zur Verfügung." },
      ],
      exercises: {}, prevSlug: "infinitivkonstruktionen", nextSlug: "nominalisierung",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["впізнавати FVG у тексті", "правильно добирати Funktionsverb", "заміняти FVG одиничним дієсловом і навпаки", "розуміти стилістичну функцію FVG"],
      ruleBox: {
        rule: "У FVG значення несе <b>іменник</b>, дієслово — <b>граматичне</b>. Часто виражає початок, стан або зміну стану.",
        examples: [
          { de: "in Kraft treten", uk: "набувати чинності (стан)" },
          { de: "eine Frage stellen", uk: "поставити питання (дія)" },
        ],
      },
      ukrainianTips: [
        "Українською часто перекладається дієсловом («вирішити», «допомогти»), а не буквально.",
        "«Прийняти рішення» = <b>eine Entscheidung treffen</b>, не «nehmen» і не «machen».",
        "«Надати допомогу» = <b>Hilfe leisten</b>, а не «geben».",
      ],
      languageComparison: {
        commons: ["Українська теж має «прийняти рішення», «надати допомогу» — типово канцелярський стиль."],
        diffs: ["У німецькій набір фіксованих дієслів (treffen, leisten, stellen, ziehen) — треба вивчити напам'ять."],
        traps: ["Не «Entscheidung machen» — це англіцизм."],
      },
      summary: [
        "FVG = Funktionsverb + іменник(+Präp.).",
        "Значення — в іменнику; дієслово — «порожнє».",
        "Стиль — офіційний, формальний.",
        "Ключові дієслова: treffen, leisten, stellen, ziehen, treten, kommen.",
        "Часто = одне дієслово: <i>entscheiden, helfen, bereitstellen…</i>",
      ],
    },
    exercises15: [
      { type: "mc", q: "«Прийняти рішення»:", options: ["Entscheidung machen","Entscheidung nehmen","Entscheidung treffen","Entscheidung geben"], correct: 2 },
      { type: "mc", q: "«Набути чинності»:", options: ["in Kraft kommen","in Kraft treten","in Kraft sein","zu Kraft gehen"], correct: 1 },
      { type: "mc", q: "«Надати допомогу»:", options: ["Hilfe geben","Hilfe leisten","Hilfe machen","Hilfe tun"], correct: 1 },
      { type: "mc", q: "«Врахувати щось»:", options: ["Rücksicht nehmen auf","Rücksicht machen","Rücksicht leisten","Rücksicht geben"], correct: 0 },
      { type: "gap", q: "Wir müssen die Faktoren in ___ ziehen.", answer: "Betracht" },
      { type: "gap", q: "Das Gesetz ___ am 1. Januar in Kraft.", answer: "tritt" },
      { type: "gap", q: "Wir stellen Ihnen das Auto zur ___.", answer: "Verfügung" },
      { type: "gap", q: "Er hat das Thema zur Sprache ___.", answer: "gebracht" },
      { type: "tf", q: "У FVG значення несе саме дієслово.", correct: false },
      { type: "tf", q: "FVG типові для офіційного стилю.", correct: true },
      { type: "match", prompt: "FVG → одиничне дієслово:", pairs: [
        { left: "eine Entscheidung treffen", right: "entscheiden" },
        { left: "in Betracht ziehen", right: "erwägen" },
        { left: "in Kraft treten", right: "gelten" },
        { left: "zur Verfügung stellen", right: "bereitstellen" },
        { left: "Rücksicht nehmen", right: "berücksichtigen" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Wir machen eine Entscheidung.", correct: ["Wir treffen eine Entscheidung."] },
      { type: "multi", q: "Виділи Funktionsverben:",
        options: ["treffen","kaufen","leisten","stellen","essen","ziehen"], correct: [0,2,3,5] },
      { type: "order", prompt: "Склади речення:",
        words: ["Entscheidung","müssen","treffen","wir","eine"], correct: ["wir","müssen","eine","Entscheidung","treffen"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Ми повинні розглянути всі можливості.",
        de: ["Wir müssen alle Möglichkeiten in Betracht ziehen."] },
    ],
  },

  nominalisierung: {
    lesson: {
      slug: "nominalisierung", level: "B2", category: CAT,
      titleDe: "Nominalisierung von Verben", titleUk: "Номіналізація дієслів",
      goal: "Перетворювати дієслова на іменники, писати з великої літери, обирати правильний артикль і суфікс.",
      explanation: [
        "<b>Номіналізація</b> = перетворення дієслова на іменник. У німецькій це дуже поширений спосіб побудови формальних та наукових речень.",
        "<b>1) Інфінітив як іменник</b>: артикль <b>das</b>, з великої літери: <i>das Lernen, das Schreiben, das Kochen</i>.",
        "<b>2) Суфікс -ung</b>: <i>bilden → die Bildung, entwickeln → die Entwicklung</i>. Завжди <b>жіночий рід</b>.",
        "<b>3) Без суфікса (Wurzelnomen)</b>: <i>der Kauf, der Gang, der Schrei, der Blick</i>. Часто чоловічий рід.",
        "Номіналізовані форми зазвичай ідуть з прийменником: <i>bei der Arbeit, nach dem Essen, durch das Lesen, wegen der Verspätung</i>.",
      ],
      table: {
        headers: ["Verb", "Nominalisierung", "Артикль"],
        rows: [
          ["lernen", "das Lernen / die Lernung", "das (Inf.), die (-ung)"],
          ["bilden", "die Bildung", "die"],
          ["kaufen", "der Kauf", "der (без суфікса)"],
          ["arbeiten", "die Arbeit", "die"],
          ["schlafen", "der Schlaf / das Schlafen", "der / das"],
          ["entscheiden", "die Entscheidung", "die"],
          ["ankommen", "die Ankunft", "die"],
          ["schreiben", "das Schreiben", "das (Inf.)"],
        ],
      },
      examples: [
        { de: "Das Lernen macht mir Spaß.", uk: "Мені подобається вчитися." },
        { de: "Nach dem Essen gehen wir spazieren.", uk: "Після їжі ми йдемо на прогулянку." },
        { de: "Die Entwicklung des Projekts dauert Monate.", uk: "Розвиток проєкту триває місяцями." },
        { de: "Beim Lesen entspanne ich mich.", uk: "Читаючи, я розслабляюся." },
        { de: "Durch das viele Üben ist er besser geworden.", uk: "Завдяки численним тренуванням він став кращим." },
        { de: "Der Kauf des Autos war ein Fehler.", uk: "Купівля автомобіля була помилкою." },
        { de: "Wegen der Verspätung verpasste ich den Anschluss.", uk: "Через запізнення я пропустив пересадку." },
        { de: "Nach dem Aufstehen trinke ich Kaffee.", uk: "Після пробудження я п'ю каву." },
      ],
      tip: "Іменник з інфінітива → <b>das</b> і з великої: <i>das Kochen, das Schreiben</i>. Суфікс <b>-ung</b> → <b>die</b>.",
      mistakes: [
        { wrong: "Das lernen macht Spaß.", right: "Das Lernen macht Spaß." },
        { wrong: "die Bildungen des Kindes", right: "die Bildung des Kindes" },
        { wrong: "Der Ankunft war spät.", right: "Die Ankunft war spät." },
      ],
      exercises: {}, prevSlug: "funktionsverbgefuege-basis", nextSlug: "partizip-adjektive",
    },
    extras: {
      duration: 18, premium: true,
      learningGoals: ["перетворювати дієслово на іменник", "правильно обирати артикль", "писати номіналізації з великої", "розуміти стилістичне навантаження"],
      ruleBox: {
        rule: "Інфінітив-іменник = <b>das + Infinitiv</b>. -ung-іменник = <b>die</b>. Wurzelnomen (без суфікса) — часто <b>der</b>.",
      },
      ukrainianTips: [
        "У німецькій формальному тексті іменник часто <b>витісняє</b> дієслово: замість <i>«коли вивчаємо…»</i> — <i>«beim Lernen»</i>.",
        "Не забувай велику літеру — це маркер номіналізації.",
        "«вивчення чогось» = <b>das Lernen von + Dat.</b> або <b>Gen.</b>: <i>das Lernen der Sprache</i>.",
      ],
      languageComparison: {
        commons: ["Українська теж має віддієслівні іменники: «вивчення», «побудова»."],
        diffs: ["Німецька дуже часто вживає інфінітив-іменник — в українській це рідкість."],
        traps: ["Не «das Aufstehung», а <b>das Aufstehen</b> або <b>die Aufstehung</b> зустрічається у релігійному контексті."],
      },
      summary: [
        "das + Infinitiv (велика літера).",
        "-ung → die.",
        "Wurzelnomen (der Kauf, der Blick) — вчити з артиклем.",
        "Часто з прийменниками (bei, nach, durch, wegen).",
        "Формальний, компактний, дуже поширений у B2/C1 текстах.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Артикль інфінітива-іменника:", options: ["der","die","das","die (Pl.)"], correct: 2 },
      { type: "mc", q: "Артикль слова «Entwicklung»:", options: ["der","die","das","kein"], correct: 1, explain: "-ung → die." },
      { type: "mc", q: "«Купівля» = ", options: ["das Kaufen","der Kauf","die Kaufung","der Käufer"], correct: 1 },
      { type: "mc", q: "Правильно:", options: ["das lernen","Das Lernen","der Lernen","die Lernen"], correct: 1 },
      { type: "gap", q: "Nach ___ Essen. (артикль)", answer: "dem" },
      { type: "gap", q: "Beim ___ (lesen) entspanne ich mich.", answer: "Lesen" },
      { type: "gap", q: "Die ___ (entscheiden) war schwierig.", answer: "Entscheidung" },
      { type: "gap", q: "Wegen der ___ (verspäten) verpasste ich den Zug.", answer: "Verspätung" },
      { type: "tf", q: "Іменник з інфінітива завжди пишеться з великої.", correct: true },
      { type: "tf", q: "-ung-іменники — чоловічого роду.", correct: false },
      { type: "match", prompt: "Verb → Nomen:", pairs: [
        { left: "lernen", right: "das Lernen" },
        { left: "entwickeln", right: "die Entwicklung" },
        { left: "kaufen", right: "der Kauf" },
        { left: "arbeiten", right: "die Arbeit" },
        { left: "ankommen", right: "die Ankunft" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das lernen macht Spaß.", correct: ["Das Lernen macht Spaß."] },
      { type: "multi", q: "Виділи правильні номіналізації:",
        options: ["das Lernen","der Kauf","die Bildung","das Arbeit","die Kaufung","die Ankunft"], correct: [0,1,2,5] },
      { type: "order", prompt: "Склади речення:",
        words: ["Spaß","macht","das","mir","Lernen"], correct: ["das","Lernen","macht","mir","Spaß"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Після їжі ми йдемо гуляти.",
        de: ["Nach dem Essen gehen wir spazieren."] },
    ],
  },

  "partizip-adjektive": {
    lesson: {
      slug: "partizip-adjektive", level: "B2", category: CAT,
      titleDe: "Partizip I und II als Adjektive", titleUk: "Partizip I та II як прикметники",
      goal: "Використовувати Partizip I і II як прикметники перед іменником.",
      explanation: [
        "<b>Partizip I</b> = <i>Infinitiv + -d</i>: <i>lachen → lachend, schlafen → schlafend</i>. Значення — <b>активне, одночасне</b>: «той, що робить».",
        "<b>Partizip II</b> = звична 3-я форма (ge…-t / ge…-en): <i>gekocht, geschrieben, geöffnet</i>. Значення залежить від типу дієслова: у <b>перехідних</b> — <b>пасив</b> («який зроблений»), у <b>неперехідних sein-дієслів</b> — <b>завершена дія</b> («що прийшов»).",
        "Як прикметник обидва Partizip <b>відмінюються</b> як звичайні прикметники: <i>der lachende Mann, das gekochte Ei, die angekommenen Gäste</i>.",
        "Ланцюжки з розширеннями (erweiterte Partizipialattribute) — типова риса писемного стилю: <i>der gestern angekommene Zug</i>, <i>ein von allen gelesenes Buch</i>.",
      ],
      table: {
        headers: ["Форма", "Значення", "Приклад"],
        rows: [
          ["Partizip I", "активне, одночасне", "das schlafende Kind"],
          ["Partizip II (перех.)", "пасивне", "das gekochte Ei"],
          ["Partizip II (sein-Verb)", "завершене", "der angekommene Zug"],
          ["з розширенням", "розгорнутий атрибут", "der gestern angekommene Zug"],
        ],
      },
      examples: [
        { de: "Das schlafende Kind sieht friedlich aus.", uk: "Дитина, що спить, виглядає мирно." },
        { de: "Die singende Frau ist meine Schwester.", uk: "Жінка, що співає, — моя сестра." },
        { de: "Das gekochte Ei schmeckt lecker.", uk: "Зварене яйце смачне." },
        { de: "Der geöffnete Brief lag auf dem Tisch.", uk: "Відкритий лист лежав на столі." },
        { de: "Die angekommenen Gäste warten im Foyer.", uk: "Гості, що приїхали, чекають у фоє." },
        { de: "Ein von allen gelesenes Buch.", uk: "Книга, яку всі прочитали." },
        { de: "Der lachende Junge ist mein Neffe.", uk: "Хлопчик, що сміється, — мій племінник." },
        { de: "Die gut vorbereitete Präsentation hat allen gefallen.", uk: "Добре підготовлена презентація всім сподобалася." },
      ],
      tip: "P I = <b>-d</b> (активне зараз). P II = <b>ge-...-t/-en</b> (пасивне або завершене). Обидва відмінюються як прикметники.",
      mistakes: [
        { wrong: "das schlafen Kind", right: "das schlafende Kind" },
        { wrong: "die gekochten Ei", right: "das gekochte Ei" },
        { wrong: "die angekommen Gäste", right: "die angekommenen Gäste" },
      ],
      exercises: {}, prevSlug: "nominalisierung", nextSlug: "bedeutung-aehnlicher-verben",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["утворювати P I та P II", "розрізняти активне/пасивне значення", "відмінювати як прикметники", "розуміти розширені партиципіальні атрибути"],
      ruleBox: {
        rule: "P I: Inf. + <b>-d</b>. P II: звична 3-я форма. Обидва <b>відмінюються</b> як прикметники.",
        examples: [
          { de: "der spielende Hund", uk: "собака, що грає (P I)" },
          { de: "das gekaufte Buch", uk: "куплена книга (P II)" },
        ],
      },
      ukrainianTips: [
        "P I ≈ українські активні дієприкметники теперішнього часу («граючий») — але вони в українській рідкісні, тому часто перекладаємо підрядним «який грає».",
        "P II перехідних дієслів ≈ пасивні дієприкметники минулого («написаний, куплений»).",
        "P II неперехідних (kommen, gehen, sterben) описує <b>завершений стан</b>: <i>der gestorbene Dichter</i>.",
      ],
      languageComparison: {
        commons: ["Українська теж має пасивні дієприкметники: «написаний», «зроблений»."],
        diffs: ["Німецька легко будує розгорнуті партиципіальні звороти перед іменником — у B2/C1 текстах це норма."],
        traps: ["Не всі німецькі P I добре перекладаються — часто краще підрядне з <i>der/die/das</i>."],
      },
      summary: [
        "P I = Inf. + -d (активне).",
        "P II = ge-...-t/-en (пасивне/завершене).",
        "Обидва відмінюються.",
        "Розширений атрибут: <i>der gestern angekommene Zug</i>.",
        "У B2 треба впізнавати обидві форми в тексті.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Partizip I від «lachen»:", options: ["gelacht","lachend","lachte","lachender"], correct: 1 },
      { type: "mc", q: "Partizip II від «kochen»:", options: ["kochend","gekocht","kochte","kocht"], correct: 1 },
      { type: "mc", q: "«Спляча дитина»:", options: ["das geschlafene Kind","das schlafende Kind","das schlaft Kind","das Schlafen Kind"], correct: 1 },
      { type: "mc", q: "«Куплена книга»:", options: ["das kaufende Buch","das gekaufte Buch","das kaufte Buch","das Kaufen Buch"], correct: 1 },
      { type: "gap", q: "der ___ (lachen) Mann", answer: "lachende" },
      { type: "gap", q: "das ___ (öffnen) Fenster", answer: "geöffnete" },
      { type: "gap", q: "die ___ (ankommen) Gäste", answer: "angekommenen" },
      { type: "gap", q: "ein ___ (lesen) Buch (яке читає) — Partizip I", answer: "lesendes" },
      { type: "tf", q: "Partizip I означає активну одночасну дію.", correct: true },
      { type: "tf", q: "Partizip II перехідних дієслів має пасивне значення як атрибут.", correct: true },
      { type: "match", prompt: "Форма → значення:", pairs: [
        { left: "lachend", right: "той, що сміється (актив.)" },
        { left: "gelacht", right: "той, з якого сміялися (не типово)" },
        { left: "gekocht", right: "зварений (пас.)" },
        { left: "angekommen", right: "той, що прибув (заверш.)" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "das schlafen Kind", correct: ["das schlafende Kind"] },
      { type: "multi", q: "Виділи правильні атрибути:",
        options: ["das schlafende Kind","das gekochte Ei","die angekommen Gäste","der lachende Mann","das kochend Ei","das kaufte Buch"], correct: [0,1,3] },
      { type: "order", prompt: "Склади речення:",
        words: ["schmeckt","Ei","das","gekochte","lecker"], correct: ["das","gekochte","Ei","schmeckt","lecker"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Дитина, що спить, виглядає мирно.",
        de: ["Das schlafende Kind sieht friedlich aus."] },
    ],
  },

  "bedeutung-aehnlicher-verben": {
    lesson: {
      slug: "bedeutung-aehnlicher-verben", level: "B2", category: CAT,
      titleDe: "Bedeutungsunterschiede ähnlicher Verben", titleUk: "Значеннєві відмінності схожих дієслів",
      goal: "Розрізняти пари/трійки схожих дієслів і не змішувати їх у вживанні.",
      explanation: [
        "У німецькій багато дієслів звучать схоже або перекладаються одним українським — але мають <b>різне вживання</b>.",
        "<b>legen (класти) — liegen (лежати)</b>: перше — куди (Akk.), друге — де (Dat.). Так само <b>stellen — stehen</b>, <b>setzen — sitzen</b>, <b>hängen — hängen</b> (слабке / сильне).",
        "<b>kennen — wissen — können</b>: <i>kennen</i> — знати особисто; <i>wissen</i> — знати факт; <i>können</i> — вміти / могти.",
        "<b>lernen — studieren</b>: <i>lernen</i> — вчити (взагалі, у школі); <i>studieren</i> — навчатися в університеті.",
        "<b>sprechen — reden — sagen — erzählen</b>: sprechen (говорити мовою, розмовляти), reden (виступати, балакати), sagen (сказати щось конкретне), erzählen (розповідати історію).",
      ],
      table: {
        headers: ["Пара", "Приклад", "Відмінність"],
        rows: [
          ["legen / liegen", "Ich lege das Buch auf den Tisch. / Es liegt auf dem Tisch.", "куди Akk. / де Dat."],
          ["stellen / stehen", "Ich stelle die Vase. / Sie steht.", "куди / де"],
          ["kennen / wissen", "Ich kenne ihn. / Ich weiß, wo er wohnt.", "особу / факт"],
          ["lernen / studieren", "Ich lerne Deutsch. / Sie studiert Medizin.", "мову/навичку / у виші"],
          ["sagen / erzählen", "Sag mir die Wahrheit. / Erzähl mir eine Geschichte.", "коротко / розлого"],
          ["hören / zuhören", "Ich höre Musik. / Ich höre dir zu.", "загалом / уважно"],
        ],
      },
      examples: [
        { de: "Kennst du Anna? – Ja, ich weiß auch, wo sie arbeitet.", uk: "Ти знаєш Анну? – Так, я знаю й де вона працює." },
        { de: "Ich lege den Brief auf den Tisch. Jetzt liegt er dort.", uk: "Я кладу лист на стіл. Тепер він там лежить." },
        { de: "Sie studiert an der Uni Wien Jura.", uk: "Вона вчить право у Віденському університеті." },
        { de: "Wir lernen Vokabeln.", uk: "Ми вчимо слова." },
        { de: "Er redet zu viel.", uk: "Він забагато балакає." },
        { de: "Sprich lauter, bitte!", uk: "Говори голосніше, будь ласка!" },
        { de: "Erzähl mir von deiner Reise.", uk: "Розкажи мені про подорож." },
        { de: "Hör mir bitte zu.", uk: "Послухай мене, будь ласка." },
      ],
      tip: "Пари куди/де → <b>Akk. / Dat.</b>. Знати особу = <b>kennen</b>, знати факт = <b>wissen</b>.",
      mistakes: [
        { wrong: "Ich lege auf dem Bett.", right: "Ich liege auf dem Bett." },
        { wrong: "Ich kenne, wo er wohnt.", right: "Ich weiß, wo er wohnt." },
        { wrong: "Sie lernt an der Uni Medizin.", right: "Sie studiert an der Uni Medizin." },
      ],
      exercises: {}, prevSlug: "partizip-adjektive", nextSlug: "verben-vorsilben",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["не змішувати legen/liegen, stellen/stehen, setzen/sitzen", "правильно вибирати kennen vs wissen", "розрізняти lernen vs studieren", "точно вживати sagen/erzählen/reden/sprechen"],
      ruleBox: {
        rule: "<b>Куди?</b> → перехідні (legen, stellen, setzen, hängen — слабк.) + Akk. <b>Де?</b> → неперехідні (liegen, stehen, sitzen, hängen — сильн.) + Dat.",
      },
      ukrainianTips: [
        "«знати» — це <b>дві</b> різні німецькі дієслівні ідеї: <i>kennen</i> (бути знайомим) і <i>wissen</i> (знати щось).",
        "«вчити» дуже широке — у німецькій розділяється: <i>lernen</i> (набувати навичку) vs. <i>studieren</i> (у ВНЗ) vs. <i>üben</i> (тренуватися).",
        "«говорити» → sprechen; «розказувати» → erzählen; «сказати щось» → sagen; «балакати» → reden.",
      ],
      languageComparison: {
        commons: ["Українська теж має «класти/лежати», «ставити/стояти», але не завжди чітко."],
        diffs: ["Німецька <b>послідовно</b> розрізняє напрямок vs. місце — і граматично, і лексично."],
        traps: ["Не «Ich stehe die Vase» — <b>Ich stelle die Vase</b>."],
      },
      summary: [
        "legen/stellen/setzen + Akk. — куди.",
        "liegen/stehen/sitzen + Dat. — де.",
        "kennen — особа/місце; wissen — факт.",
        "studieren = ВНЗ; lernen = набувати навички.",
        "sagen vs. erzählen vs. reden vs. sprechen — за контекстом.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ das Buch auf den Tisch.", options: ["liege","lege","stehe","sitze"], correct: 1 },
      { type: "mc", q: "Das Buch ___ auf dem Tisch.", options: ["legt","liegt","stellt","setzt"], correct: 1 },
      { type: "mc", q: "«Знати факт»:", options: ["kennen","wissen","können","erkennen"], correct: 1 },
      { type: "mc", q: "«Навчатися в університеті»:", options: ["lernen","studieren","üben","kennenlernen"], correct: 1 },
      { type: "gap", q: "Ich ___ Anna, aber ich ___ nicht, wo sie wohnt.", answer: "kenne / weiß" },
      { type: "gap", q: "___ mir eine Geschichte, bitte!", answer: "Erzähl" },
      { type: "gap", q: "Er ___ Deutsch schon zwei Jahre.", answer: "lernt" },
      { type: "gap", q: "Die Vase ___ auf dem Tisch. (де)", answer: "steht" },
      { type: "tf", q: "«liegen» вимагає Akkusativ.", correct: false },
      { type: "tf", q: "«wissen» використовується перед підрядним з фактом.", correct: true },
      { type: "match", prompt: "Значення → дієслово:", pairs: [
        { left: "покласти", right: "legen" }, { left: "лежати", right: "liegen" },
        { left: "поставити", right: "stellen" }, { left: "стояти", right: "stehen" },
        { left: "знати особу", right: "kennen" }, { left: "знати факт", right: "wissen" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich weiß Anna.", correct: ["Ich kenne Anna."] },
      { type: "multi", q: "Які дієслова означають «куди?»",
        options: ["legen","liegen","stellen","stehen","setzen","sitzen"], correct: [0,2,4] },
      { type: "order", prompt: "Склади речення:",
        words: ["ich","Tisch","lege","Buch","den","auf","das"], correct: ["ich","lege","das","Buch","auf","den","Tisch"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я знаю його, але не знаю, де він живе.",
        de: ["Ich kenne ihn, aber ich weiß nicht, wo er wohnt."] },
    ],
  },

  "verben-vorsilben": {
    lesson: {
      slug: "verben-vorsilben", level: "B2", category: CAT,
      titleDe: "Verben mit mehreren Vorsilben", titleUk: "Дієслова з різними префіксами",
      goal: "Розуміти, як префікс змінює значення дієслова; розрізняти роздільні та нероздільні префікси.",
      explanation: [
        "Одне й те саме дієслово з різними префіксами часто має <b>зовсім інше значення</b>: <i>kommen — ankommen, bekommen, mitkommen, umkommen</i>.",
        "<b>Роздільні префікси</b> (trennbar): <i>an-, auf-, aus-, ein-, mit-, nach-, vor-, zu-, weg-, ab-, zurück-, mit-</i>. Наголос падає на префікс. У Präsens/Prät. префікс відходить у кінець: <i>Ich stehe früh auf</i>.",
        "<b>Нероздільні</b> (untrennbar): <i>be-, emp-, ent-, er-, ge-, miss-, ver-, zer-</i>. Наголос на корені. Ніколи не відділяються: <i>Ich verstehe dich</i>.",
        "<b>Змішані</b> (durch-, über-, um-, unter-, wider-, wieder-): можуть бути і роздільними, і нероздільними — від значення. <i>umfahren</i> (роздільне, наголос um-) = «збити»; <i>umfahren</i> (нероздільне, наголос -fahren) = «об'їхати».",
      ],
      table: {
        headers: ["Verb", "+ Vorsilbe", "Значення"],
        rows: [
          ["kommen", "ankommen", "прибувати"],
          ["kommen", "bekommen", "отримувати"],
          ["kommen", "mitkommen", "піти з кимось"],
          ["kommen", "umkommen", "загинути"],
          ["stehen", "aufstehen", "вставати"],
          ["stehen", "verstehen", "розуміти"],
          ["stehen", "bestehen", "витримати (іспит)"],
          ["gehen", "vergehen", "минати (час)"],
        ],
      },
      examples: [
        { de: "Der Zug kommt um 10 Uhr an.", uk: "Потяг прибуває о 10-й." },
        { de: "Ich bekomme ein Paket.", uk: "Я отримую посилку." },
        { de: "Kommst du mit?", uk: "Ти йдеш зі мною?" },
        { de: "Ich verstehe dich nicht.", uk: "Я тебе не розумію." },
        { de: "Er hat die Prüfung bestanden.", uk: "Він склав іспит." },
        { de: "Die Zeit vergeht schnell.", uk: "Час швидко минає." },
        { de: "Wir umfahren die Stadt.", uk: "Ми об'їжджаємо місто." },
        { de: "Achtung, fahr das Kind nicht um!", uk: "Обережно, не збий дитину!" },
      ],
      tip: "Роздільні → наголос на <b>префіксі</b>, відділяються. Нероздільні → наголос на <b>корені</b>, не відділяються.",
      mistakes: [
        { wrong: "Ich aufstehe früh.", right: "Ich stehe früh auf." },
        { wrong: "Er ver-steht mich nicht (як «Ver steht»).", right: "Er versteht mich nicht." },
        { wrong: "Ich habe die Prüfung gebestanden.", right: "Ich habe die Prüfung bestanden." },
      ],
      exercises: {}, prevSlug: "bedeutung-aehnlicher-verben", nextSlug: "sich-lassen-infinitiv",
    },
    extras: {
      duration: 22, premium: true,
      learningGoals: ["впізнавати роздільні / нероздільні префікси", "правильно ставити префікс у реченні", "утворювати Partizip II з префіксом", "розуміти зміну значення"],
      ruleBox: {
        rule: "Роздільні: <b>an-, auf-, aus-, ein-, mit-, nach-, vor-, zu-, ab-, zurück-, weg-</b>. Нероздільні: <b>be-, emp-, ent-, er-, ge-, miss-, ver-, zer-</b>. Partizip II нероздільних — <b>без ge-</b>.",
        examples: [
          { de: "Ich stehe früh auf. → aufgestanden.", uk: "з ge- всередині" },
          { de: "Ich verstehe. → verstanden.", uk: "без ge-" },
        ],
      },
      ukrainianTips: [
        "Українські префікси (при-, ви-, за-, у-) працюють схоже, але у німецькій ще й <b>граматично</b> визначають словопорядок.",
        "Найкорисніша стратегія — вчити дієслова у <b>трьох формах</b>: інфінітив, Präsens 3 Sg., Partizip II.",
        "У повсякденні найважливіші: aufstehen, ankommen, mitkommen, verstehen, bekommen, gehören, benutzen.",
      ],
      languageComparison: {
        commons: ["Українська й німецька активно використовують префікси для творення нових значень."],
        diffs: ["У німецькій роздільні префікси <b>фізично рухаються в реченні</b> — це унікально."],
        traps: ["<i>um-, über-, durch-</i> — двозначні: значення змінюється залежно від того, роздільне воно чи ні."],
      },
      summary: [
        "Роздільні: наголос на префіксі, відділяються.",
        "Нероздільні: наголос на корені, не відділяються, P II без ge-.",
        "Змішані: залежить від значення.",
        "Префікс змінює значення радикально.",
        "Вчи трійками: Inf. – Präs. 3 Sg. – P II.",
      ],
    },
    exercises15: [
      { type: "mc", q: "«Отримати» = ", options: ["ankommen","bekommen","mitkommen","umkommen"], correct: 1 },
      { type: "mc", q: "«Вставати» = ", options: ["verstehen","aufstehen","bestehen","gestehen"], correct: 1 },
      { type: "mc", q: "Partizip II від «verstehen»:", options: ["geverstanden","verstanden","verstehte","verstand"], correct: 1 },
      { type: "mc", q: "Роздільний префікс:", options: ["ver-","be-","auf-","ent-"], correct: 2 },
      { type: "gap", q: "Ich stehe früh ___.", answer: "auf" },
      { type: "gap", q: "Er hat die Prüfung ___. (bestehen, P II)", answer: "bestanden" },
      { type: "gap", q: "Der Zug ___ um 10 Uhr ___. (ankommen)", answer: "kommt / an" },
      { type: "gap", q: "Ich ___ dich nicht. (verstehen)", answer: "verstehe" },
      { type: "tf", q: "Нероздільні префікси мають наголос на корені.", correct: true },
      { type: "tf", q: "Partizip II від «bekommen» — «gebekommen».", correct: false, explain: "«bekommen» (be- нероздільний)." },
      { type: "match", prompt: "Verb → значення:", pairs: [
        { left: "ankommen", right: "прибувати" }, { left: "bekommen", right: "отримувати" },
        { left: "aufstehen", right: "вставати" }, { left: "verstehen", right: "розуміти" },
        { left: "bestehen", right: "витримати іспит" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich aufstehe um 7 Uhr.", correct: ["Ich stehe um 7 Uhr auf."] },
      { type: "multi", q: "Які префікси — нероздільні?",
        options: ["be-","auf-","ver-","mit-","ent-","zer-"], correct: [0,2,4,5] },
      { type: "order", prompt: "Склади речення:",
        words: ["stehe","um","auf","ich","7","Uhr"], correct: ["ich","stehe","um","7","Uhr","auf"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я тебе не розумію.", de: ["Ich verstehe dich nicht."] },
    ],
  },

  "sich-lassen-infinitiv": {
    lesson: {
      slug: "sich-lassen-infinitiv", level: "B2", category: CAT,
      titleDe: "sich lassen + Infinitiv", titleUk: "Конструкція sich lassen + Infinitiv",
      goal: "Використовувати sich lassen + Inf. для вираження можливості (замість пасиву) та каузативності.",
      explanation: [
        "<b>sich lassen + Infinitiv</b> має два основні значення.",
        "<b>1) Можливість (Passiversatz)</b>: <i>Das lässt sich leicht machen</i> = <i>Das kann leicht gemacht werden</i>. Форма активна, значення пасивне. Дуже поширена в B2.",
        "<b>2) Каузативне значення (без sich)</b>: <i>Ich lasse mein Auto reparieren</i> = «Я віддаю машину в ремонт» — не сам ремонтую, а даю комусь зробити.",
        "У Perfekt працює <b>подвійний інфінітив</b>: <i>Das hat sich leicht machen lassen</i>, <i>Ich habe mein Auto reparieren lassen</i> — без ge-.",
        "У підрядному <i>hat/hatte</i> йде <b>перед</b> блоком: <i>…, weil es sich leicht hat machen lassen</i>.",
      ],
      table: {
        headers: ["Конструкція", "Значення", "Заміна"],
        rows: [
          ["Das lässt sich machen.", "можливість", "= kann gemacht werden"],
          ["Das lässt sich nicht ändern.", "неможливість", "= kann nicht geändert werden"],
          ["Ich lasse mein Auto reparieren.", "каузатив", "хтось інший ремонтує"],
          ["Ich lasse mir die Haare schneiden.", "каузатив із дативом", "мені стрижуть волосся"],
          ["Perfekt (можл.)", "hat sich machen lassen", "подвійний Inf."],
          ["Perfekt (каузат.)", "hat reparieren lassen", "без ge-"],
        ],
      },
      examples: [
        { de: "Diese Tür lässt sich nicht öffnen.", uk: "Ці двері не відчиняються." },
        { de: "Das Problem lässt sich leicht lösen.", uk: "Проблему легко розв'язати." },
        { de: "Ich lasse mir einen Kaffee bringen.", uk: "Я замовляю (собі) каву." },
        { de: "Er lässt sich die Haare schneiden.", uk: "Він стрижеться (в перукаря)." },
        { de: "Wir haben unser Auto reparieren lassen.", uk: "Ми віддали машину в ремонт." },
        { de: "Das hat sich nicht vermeiden lassen.", uk: "Цього не вдалося уникнути." },
        { de: "Der Text lässt sich gut lesen.", uk: "Текст добре читається." },
        { de: "Ich lasse dich nicht allein.", uk: "Я тебе не залишаю самого." },
      ],
      tip: "Формула: <b>lassen + sich + Inf.</b> = можливість. <b>lassen + (jdn) + Inf.</b> = каузатив («доручити»).",
      mistakes: [
        { wrong: "Das lässt machen leicht.", right: "Das lässt sich leicht machen." },
        { wrong: "Ich habe mein Auto reparieren gelassen.", right: "Ich habe mein Auto reparieren lassen." },
        { wrong: "Er lässt schneiden die Haare.", right: "Er lässt sich die Haare schneiden." },
      ],
      exercises: {}, prevSlug: "verben-vorsilben",
    },
    extras: {
      duration: 20, premium: true,
      learningGoals: ["утворювати sich lassen + Inf. для можливості", "розуміти каузативне значення", "правильно будувати Perfekt із подвійним інфінітивом", "уникати кальок із української"],
      ruleBox: {
        rule: "<b>sich lassen + Inf.</b> = «можна…» (замість пасиву). <b>lassen (без sich) + Inf.</b> = «дати комусь зробити» (каузатив). Perfekt — подвійний інфінітив без ge-.",
        examples: [
          { de: "Das lässt sich machen.", uk: "Це можна зробити." },
          { de: "Ich lasse das Auto reparieren.", uk: "Я віддаю машину в ремонт." },
        ],
      },
      ukrainianTips: [
        "«Двері не відчиняються» → <b>Die Tür lässt sich nicht öffnen</b>.",
        "«Постригтися» = <b>sich die Haare schneiden lassen</b> — з дативом «sich» (собі).",
        "«Я відремонтував машину» (сам) = <i>Ich habe mein Auto repariert</i>; але «Я віддав у ремонт» = <b>Ich habe mein Auto reparieren lassen</b>.",
      ],
      languageComparison: {
        commons: ["Українська має «дати зробити», «замовити», «постригтися» — концепт близький."],
        diffs: ["Німецька виражає обидва значення через одне дієслово <b>lassen</b>."],
        traps: [
          "Не забувай <b>sich</b> у значенні можливості.",
          "У Perfekt — тільки <b>lassen</b>, ніколи <i>gelassen</i>.",
        ],
      },
      summary: [
        "sich lassen + Inf. = «можна зробити» (Passiversatz).",
        "lassen + Inf. = каузатив («доручити»).",
        "sich lassen + Dat. + Inf. = «дати собі щось зробити».",
        "Perfekt: haben + Inf. + lassen (без ge-).",
        "Компактніше й природніше за пасив.",
      ],
    },
    exercises15: [
      { type: "mc", q: "«Це можна зробити» найприродніше:", options: ["Das ist gemacht.","Das lässt sich machen.","Das lässt machen.","Das macht sich."], correct: 1 },
      { type: "mc", q: "Perfekt від «Das lässt sich machen»:", options: ["Das hat sich machen gelassen.","Das hat sich machen lassen.","Das ist sich gemacht.","Das hat sich gemacht."], correct: 1 },
      { type: "mc", q: "«Я віддаю машину в ремонт»:", options: ["Ich repariere mein Auto.","Ich lasse mein Auto repariert.","Ich lasse mein Auto reparieren.","Ich habe mein Auto reparieren."], correct: 2 },
      { type: "mc", q: "«Він стрижеться»:", options: ["Er schneidet die Haare.","Er lässt sich die Haare schneiden.","Er wird die Haare geschnitten.","Er hat sich die Haare."], correct: 1 },
      { type: "gap", q: "Das Problem ___ sich leicht lösen.", answer: "lässt" },
      { type: "gap", q: "Ich ___ mir einen Kaffee bringen.", answer: "lasse" },
      { type: "gap", q: "Wir haben das Auto reparieren ___.", answer: "lassen" },
      { type: "gap", q: "Die Tür lässt ___ nicht öffnen.", answer: "sich" },
      { type: "tf", q: "У значенні можливості потрібне «sich».", correct: true },
      { type: "tf", q: "У Perfekt форма — «gelassen».", correct: false, explain: "Подвійний інфінітив: «machen lassen»." },
      { type: "match", prompt: "Речення → значення:", pairs: [
        { left: "Das lässt sich machen.", right: "можливість" },
        { left: "Ich lasse das Auto reparieren.", right: "каузатив" },
        { left: "Ich lasse dich nicht.", right: "не залишаю" },
        { left: "Er lässt sich die Haare schneiden.", right: "каузатив + Dat." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe mein Auto reparieren gelassen.",
        correct: ["Ich habe mein Auto reparieren lassen."] },
      { type: "multi", q: "Які речення = Passiversatz (можливість)?",
        options: ["Das lässt sich machen.","Ich lasse das Auto reparieren.","Das lässt sich nicht ändern.","Er lässt sich stören.","Ich lasse dich gehen."], correct: [0,2] },
      { type: "order", prompt: "Склади речення:",
        words: ["Tür","lässt","die","öffnen","sich","nicht"],
        correct: ["die","Tür","lässt","sich","nicht","öffnen"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Ми віддали машину в ремонт.",
        de: ["Wir haben das Auto reparieren lassen.","Wir haben unser Auto reparieren lassen."] },
    ],
  },
};
