// A2 · Прикметники — 8 повних уроків.
// adjektivdeklination-bestimmter і komparativ-superlativ уже є в lessons.ts → лише extras + 15 вправ.
// Решта 6 — повні нові уроки.

import type { A2Map } from "./_helpers";

const CAT = "Прикметники";

export const adjektiveA2: A2Map = {
  // ===================================================================
  "adjektive-praedikativ-attributiv": {
    lesson: {
      slug: "adjektive-praedikativ-attributiv",
      level: "A2",
      category: CAT,
      titleDe: "Prädikativ vs. attributiv",
      titleUk: "Присудкові vs. означальні прикметники",
      goal: "Розуміти, коли прикметник змінюється, а коли — ні. Відрізняти присудкову позицію від означальної.",
      explanation: [
        "<b>Присудковий прикметник</b> (prädikativ) стоїть <i>після</i> дієслів <b>sein, werden, bleiben</b>. У цій позиції він <b>НІКОЛИ не змінюється</b>: <i>«Das Auto ist <b>schnell</b>.»</i>",
        "<b>Означальний прикметник</b> (attributiv) стоїть <i>перед</i> іменником і <b>завжди має закінчення</b>: <i>«ein <b>schnelles</b> Auto»</i>.",
        "Просте правило: <b>після іменника / після sein → без закінчення</b>; <b>перед іменником → із закінченням</b>.",
        "Прислівник (Adverb) формою збігається з прикметником, але описує <b>дію</b>, не іменник: <i>«Er fährt <b>schnell</b>.»</i> Як і присудковий — без закінчення.",
      ],
      table: {
        headers: ["Позиція", "Приклад", "Закінчення?"],
        rows: [
          ["prädikativ (після sein)", "Das Auto ist schnell.", "❌ ні"],
          ["prädikativ (після werden)", "Das Wetter wird kalt.", "❌ ні"],
          ["prädikativ (після bleiben)", "Sie bleibt gesund.", "❌ ні"],
          ["attributiv (перед іменником)", "ein schnelles Auto", "✅ так"],
          ["Adverb (опис дії)", "Er fährt schnell.", "❌ ні"],
        ],
      },
      examples: [
        { de: "Das Buch ist interessant.", uk: "Книга цікава.", tag: "prädikativ" },
        { de: "Ich lese ein interessantes Buch.", uk: "Я читаю цікаву книгу.", tag: "attributiv" },
        { de: "Anna ist müde.", uk: "Анна втомлена." },
        { de: "Die müde Anna geht ins Bett.", uk: "Втомлена Анна йде спати." },
        { de: "Der Kaffee ist heiß.", uk: "Кава гаряча." },
        { de: "Ich trinke heißen Kaffee.", uk: "Я п'ю гарячу каву." },
        { de: "Sie spricht laut.", uk: "Вона говорить голосно.", tag: "Adverb" },
        { de: "Sie hat eine laute Stimme.", uk: "У неї гучний голос.", tag: "attributiv" },
      ],
      tip: "Тест: можеш поставити слово <b>перед</b> іменником? Тоді треба закінчення. <b>Після</b> sein/werden/bleiben — ніколи.",
      mistakes: [
        { wrong: "Das Auto ist schnelles.", right: "Das Auto ist schnell." },
        { wrong: "Ich lese ein interessant Buch.", right: "Ich lese ein interessantes Buch." },
        { wrong: "Er fährt schnelles.", right: "Er fährt schnell." },
      ],
      exercises: {},
      nextSlug: "adjektivdeklination-bestimmter",
    },
    extras: {
      duration: 10,
      premium: false,
      learningGoals: [
        "відрізняти присудкову і означальну позицію",
        "ніколи не додавати закінчення після sein/werden/bleiben",
        "впізнавати прислівник у формі прикметника",
      ],
      ruleBox: {
        rule: "<b>Після sein/werden/bleiben → без закінчення</b>. <b>Перед іменником → із закінченням</b>.",
      },
      ukrainianTips: [
        "Українська «книга <b>цікава</b>» / «<b>цікаву</b> книгу» — теж змінюється. У німецькій після sein <i>навіть не змінюється</i>.",
        "Не плутай <b>schnell</b> (швидкий / швидко) — німецький прикметник і прислівник часто <b>однакові</b>.",
        "Якщо слово стоїть <i>само по собі</i> після дієслова — це або присудок, або прислівник, без закінчення.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають присудкову і означальну функції."],
        diffs: ["Українська завжди узгоджує прикметник; німецька — лише в атрибутивній позиції."],
        traps: ["Помилка: «das Auto ist schnelles» — закінчення зайве."],
      },
      summary: [
        "<b>prädikativ</b> = після sein/werden/bleiben → без закінчення.",
        "<b>attributiv</b> = перед іменником → із закінченням.",
        "<b>Adverb</b> = опис дії → без закінчення.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das Auto ist ___.", options: ["schnell","schnelles","schnellen","schneller"], correct: 0 },
      { type: "mc", q: "Ich lese ein ___ Buch.", options: ["interessant","interessantes","interessanten","interessante"], correct: 1 },
      { type: "mc", q: "Anna ist sehr ___.", options: ["müde","müdes","müden","müder"], correct: 0 },
      { type: "mc", q: "Sie spricht ___.", options: ["laute","lautes","laut","lauten"], correct: 2, explain: "Adverb — без закінчення." },
      { type: "gap", q: "Der Kaffee ist ___. (heiß)", answer: "heiß" },
      { type: "gap", q: "Ich trinke einen ___ Kaffee. (heiß)", answer: "heißen" },
      { type: "gap", q: "Das Wetter wird ___. (kalt)", answer: "kalt" },
      { type: "gap", q: "Sie hat eine ___ Stimme. (laut)", answer: "laute" },
      { type: "tf", q: "Після sein прикметник ніколи не має закінчення.", correct: true },
      { type: "tf", q: "«Das Auto ist schnelles» — правильно.", correct: false, explain: "Без закінчення: schnell." },
      { type: "match", prompt: "Речення → позиція:", pairs: [
        { left: "Das Buch ist neu.", right: "prädikativ" },
        { left: "ein neues Buch", right: "attributiv" },
        { left: "Er fährt schnell.", right: "Adverb" },
        { left: "die alte Frau", right: "attributiv" },
      ]},
      { type: "multi", q: "У яких випадках прикметник <b>без</b> закінчення?",
        options: ["після sein","перед іменником","після werden","як Adverb","після Artikel + Subst."], correct: [0,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich lese ein interessant Buch.",
        correct: ["Ich lese ein interessantes Buch."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Машина швидка. — Я бачу швидку машину.",
        de: ["Das Auto ist schnell. Ich sehe ein schnelles Auto.","Das Auto ist schnell. — Ich sehe ein schnelles Auto."] },
      { type: "writeFree", prompt: "По одному реченню: prädikativ, attributiv, Adverb.",
        sample: "Der Hund ist klein. Ich habe einen kleinen Hund. Er läuft schnell." },
    ],
  },

  // ===================================================================
  "adjektivdeklination-bestimmter": {
    extras: {
      duration: 18,
      premium: false,
      learningGoals: [
        "розуміти принцип «слабкої» відміни після der/die/das",
        "впевнено обирати між -e і -en",
        "не забувати, що в Plural завжди -en",
      ],
      ruleBox: {
        rule: "Після <b>der/die/das/diese/jene/alle</b> прикметник = <b>-e</b> або <b>-en</b>. <b>-e</b>: Nom. однини + Akk. жін./сер. У всіх інших випадках — <b>-en</b>.",
        examples: [
          { de: "der kleine Hund", uk: "маленький собака (Nom.)" },
          { de: "den kleinen Hund", uk: "маленького собаку (Akk.)" },
        ],
      },
      ukrainianTips: [
        "Артикль уже несе інформацію про рід/число/відмінок, тому прикметник майже «німий» — лише -e або -en.",
        "У Plural <b>завжди</b> -en після die — без винятків.",
        "Не плутай: <i>der nette Mann</i> (Nom.) → <i>den netten Mann</i> (Akk.).",
      ],
      languageComparison: {
        commons: ["Узгодження прикметника з іменником."],
        diffs: ["Українська має багато різних закінчень; німецька — лише два після означеного артикля."],
        traps: ["Помилка: «die kleine Kinder» замість «die kleinen Kinder»."],
      },
      summary: [
        "Після der/die/das: тільки -e або -en.",
        "<b>-e</b>: Nom. одн. усіх родів + Akk. ж./с.",
        "<b>-en</b>: усе інше + ВЕСЬ Plural.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich sehe den ___ Hund.", options: ["klein","kleine","kleinen","kleines"], correct: 2 },
      { type: "mc", q: "Die ___ Kinder spielen.", options: ["klein","kleine","kleinen","kleines"], correct: 2, explain: "Plural → завжди -en." },
      { type: "mc", q: "Der ___ Mann arbeitet.", options: ["nette","netten","netter","nett"], correct: 0 },
      { type: "mc", q: "Das ___ Auto ist schnell.", options: ["neue","neuen","neuer","neu"], correct: 0 },
      { type: "gap", q: "Die ___ Frau wartet. (jung)", answer: "junge" },
      { type: "gap", q: "Ich helfe dem ___ Kind. (klein, Dat.)", answer: "kleinen" },
      { type: "gap", q: "Wir besuchen die ___ Stadt. (alt, Akk. f)", answer: "alte" },
      { type: "gap", q: "Das Buch des ___ Mannes. (jung, Gen.)", answer: "jungen" },
      { type: "tf", q: "У Plural після die завжди -en.", correct: true },
      { type: "tf", q: "Nom. одн. чол.: der nette Mann.", correct: true },
      { type: "match", prompt: "Артикль/відмінок → закінчення:", pairs: [
        { left: "der __ Mann (Nom.)", right: "-e" },
        { left: "den __ Mann (Akk.)", right: "-en" },
        { left: "die __ Frau (Nom.)", right: "-e" },
        { left: "die __ Kinder (Pl)", right: "-en" },
        { left: "dem __ Kind (Dat.)", right: "-en" },
      ]},
      { type: "multi", q: "Де буде -en?",
        options: ["der __ Mann (Nom.)","den __ Mann (Akk.)","die __ Kinder","dem __ Mann","das __ Auto (Nom.)"], correct: [1,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "die kleine Kinder",
        correct: ["die kleinen Kinder"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я бачу маленького собаку.",
        de: ["Ich sehe den kleinen Hund."] },
      { type: "writeFree", prompt: "3 речення з der/die/das + прикметник у різних відмінках.",
        sample: "Der alte Mann liest die neue Zeitung. Ich helfe dem kleinen Kind. Die jungen Studenten lernen Deutsch." },
    ],
  },

  // ===================================================================
  "adjektivdeklination-unbestimmter": {
    lesson: {
      slug: "adjektivdeklination-unbestimmter",
      level: "A2",
      category: CAT,
      titleDe: "Adjektivdeklination nach unbestimmtem Artikel",
      titleUk: "Відмінювання прикметників після неозначеного артикля",
      goal: "Правильно ставити закінчення після ein/eine — це т.зв. «змішана» відміна.",
      explanation: [
        "Після неозначеного артикля <b>ein/eine</b> прикметник «допомагає» артиклю показати рід — тому закінчення тут <b>сильніше</b>, ніж після der/die/das.",
        "У 3 формах Nom. і Akk., де <b>ein</b> не має закінчення, прикметник бере на себе закінчення: <b>-er (m), -es (n)</b>.",
        "У всіх інших випадках — <b>-en</b>.",
        "Та сама схема діє після <b>kein, mein, dein, sein, ihr, unser, euer, Ihr</b> (negativ + possessiv).",
      ],
      table: {
        headers: ["Відмінок", "m", "f", "n", "Pl (без артикля)"],
        rows: [
          ["Nom.", "ein netter Mann", "eine nette Frau", "ein nettes Kind", "nette Kinder"],
          ["Akk.", "einen netten Mann", "eine nette Frau", "ein nettes Kind", "nette Kinder"],
          ["Dat.", "einem netten Mann", "einer netten Frau", "einem netten Kind", "netten Kindern"],
          ["Gen.", "eines netten Mannes", "einer netten Frau", "eines netten Kindes", "netter Kinder"],
        ],
      },
      examples: [
        { de: "Ein netter Mann hilft mir.", uk: "Один добрий чоловік мені допомагає." },
        { de: "Ich habe ein neues Auto.", uk: "У мене нова машина." },
        { de: "Ich sehe einen großen Hund.", uk: "Я бачу великого собаку." },
        { de: "Mein bester Freund kommt.", uk: "Мій найкращий друг приходить." },
        { de: "Sie trägt eine rote Jacke.", uk: "Вона носить червону куртку." },
        { de: "Kein neues Buch liegt hier.", uk: "Жодної нової книги тут не лежить." },
        { de: "Wir helfen einer jungen Frau.", uk: "Ми допомагаємо молодій жінці." },
        { de: "Das ist das Auto eines reichen Mannes.", uk: "Це машина багатого чоловіка." },
      ],
      tip: "Якщо <b>ein</b> має закінчення (einen, einem, einer, eines) — прикметник бере <b>-en</b>. Якщо <b>ein</b> без закінчення (Nom.m, Nom.n, Akk.n) — прикметник «договорює» рід: <b>-er, -es</b>.",
      mistakes: [
        { wrong: "Ein nett Mann hilft mir.", right: "Ein netter Mann hilft mir." },
        { wrong: "Ich habe ein neuer Auto.", right: "Ich habe ein neues Auto." },
        { wrong: "Ich sehe einen groß Hund.", right: "Ich sehe einen großen Hund." },
      ],
      exercises: {},
      prevSlug: "adjektivdeklination-bestimmter",
      nextSlug: "adjektivdeklination-nullartikel",
    },
    extras: {
      duration: 18,
      premium: false,
      learningGoals: [
        "застосовувати «змішану» відміну після ein/kein/mein",
        "виводити закінчення з форми артикля",
        "правильно поводитися з Plural без артикля",
      ],
      ruleBox: {
        rule: "<b>ein без закінчення → прикметник бере закінчення роду (-er/-es)</b>. ein із закінченням → прикметник -en.",
      },
      ukrainianTips: [
        "Українській «новий стіл / нову книгу» = «ein <b>neuer</b> Tisch / ein <b>neues</b> Buch».",
        "Той же шаблон — після <b>mein, dein, sein, ihr, unser, euer, kein</b>.",
        "У Plural без артикля прикметник бере на себе всю інформацію → <i>nette Kinder</i> (Nom.), <i>netter Kinder</i> (Gen.).",
      ],
      languageComparison: {
        commons: ["Як і в українській, прикметник узгоджується з іменником."],
        diffs: ["У німецькій тип відміни залежить від артикля."],
        traps: ["Помилка: «ein nett Mann» — без закінчення взагалі."],
      },
      summary: [
        "<b>Nom. m</b>: ein nett<b>er</b> Mann.",
        "<b>Nom./Akk. n</b>: ein nett<b>es</b> Kind.",
        "<b>Nom./Akk. f</b>: eine nett<b>e</b> Frau.",
        "<b>Akk. m</b>: einen nett<b>en</b> Mann.",
        "<b>Dat./Gen.</b> — всюди <b>-en</b>.",
        "Те ж саме після kein/mein/dein/sein/ihr/unser/euer.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ein ___ Mann hilft mir.", options: ["nett","nette","netter","netten"], correct: 2 },
      { type: "mc", q: "Ich habe ein ___ Auto.", options: ["neu","neue","neuer","neues"], correct: 3 },
      { type: "mc", q: "Ich sehe einen ___ Hund.", options: ["groß","großer","großen","großes"], correct: 2 },
      { type: "mc", q: "Sie trägt eine ___ Jacke.", options: ["rot","rote","roten","roter"], correct: 1 },
      { type: "gap", q: "Mein ___ Freund kommt. (best)", answer: "bester" },
      { type: "gap", q: "Wir helfen einer ___ Frau. (jung)", answer: "jungen" },
      { type: "gap", q: "Kein ___ Buch liegt hier. (neu)", answer: "neues" },
      { type: "gap", q: "Das ist das Auto eines ___ Mannes. (reich)", answer: "reichen" },
      { type: "tf", q: "Після ein у Nom. m прикметник має -er.", correct: true },
      { type: "tf", q: "Після einem прикметник має -es.", correct: false, explain: "Після einem — завжди -en." },
      { type: "match", prompt: "Артикль → закінчення прикметника:", pairs: [
        { left: "ein __ Mann (Nom. m)", right: "-er" },
        { left: "ein __ Kind (Nom. n)", right: "-es" },
        { left: "eine __ Frau (Nom. f)", right: "-e" },
        { left: "einen __ Mann (Akk. m)", right: "-en" },
        { left: "einem __ Mann (Dat.)", right: "-en" },
      ]},
      { type: "multi", q: "Після яких слів діє «змішана» відміна?",
        options: ["ein","der","kein","mein","die","unser"], correct: [0,2,3,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe ein neuer Auto.",
        correct: ["Ich habe ein neues Auto."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я бачу великого чорного собаку.",
        de: ["Ich sehe einen großen schwarzen Hund."] },
      { type: "writeFree", prompt: "3 речення з ein/mein + прикметник.",
        sample: "Ich habe einen netten Bruder. Meine kleine Schwester spielt. Wir wohnen in einem alten Haus." },
    ],
  },

  // ===================================================================
  "adjektivdeklination-nullartikel": {
    lesson: {
      slug: "adjektivdeklination-nullartikel",
      level: "A2",
      category: CAT,
      titleDe: "Adjektivdeklination ohne Artikel (Nullartikel)",
      titleUk: "Відмінювання без артикля (Nullartikel)",
      goal: "Знати «сильну» відміну прикметників — коли артикля немає взагалі.",
      explanation: [
        "Якщо перед прикметником <b>немає артикля</b> (Nullartikel), прикметник бере на себе <b>повний</b> набір закінчень — як це робив би артикль.",
        "Це часто буває з: <b>речовинами</b> (Wasser, Brot, Bier), <b>абстрактними поняттями</b> (Liebe, Hoffnung) і в <b>Plural без артикля</b>.",
        "Закінчення фактично копіюють форму означеного артикля: <b>m -er, f -e, n -es, Pl -e (Nom./Akk.)</b>.",
        "Виняток — <b>Gen. m/n</b>: тут прикметник бере <b>-en</b>, бо рід уже показує закінчення -s самого іменника.",
      ],
      table: {
        headers: ["Відмінок", "m (kalt-)", "f (frisch-)", "n (gut-)", "Pl (nett-)"],
        rows: [
          ["Nom.", "kalter Kaffee", "frische Milch", "gutes Brot", "nette Leute"],
          ["Akk.", "kalten Kaffee", "frische Milch", "gutes Brot", "nette Leute"],
          ["Dat.", "kaltem Kaffee", "frischer Milch", "gutem Brot", "netten Leuten"],
          ["Gen.", "kalten Kaffees", "frischer Milch", "guten Brotes", "netter Leute"],
        ],
      },
      examples: [
        { de: "Ich trinke kalten Kaffee.", uk: "Я п'ю холодну каву." },
        { de: "Wir haben frisches Brot gekauft.", uk: "Ми купили свіжий хліб." },
        { de: "Nette Leute helfen gern.", uk: "Приємні люди радо допомагають." },
        { de: "Mit kaltem Wasser kann man Hände waschen.", uk: "Холодною водою можна мити руки." },
        { de: "Sie liebt heiße Schokolade.", uk: "Вона любить гарячий шоколад." },
        { de: "Deutsche Studenten lernen viel.", uk: "Німецькі студенти багато вчаться." },
        { de: "Trotz schlechten Wetters gehen wir spazieren.", uk: "Незважаючи на погану погоду, ми йдемо гуляти." },
        { de: "Bei gutem Wetter spielen wir Fußball.", uk: "За гарної погоди ми граємо у футбол." },
      ],
      tip: "Без артикля прикметник «озвучує» рід сам: <b>der Kaffee → kalt<i>er</i> Kaffee</b>, <b>das Brot → gut<i>es</i> Brot</b>. Закінчення = такі ж, як в артиклі der/das.",
      mistakes: [
        { wrong: "Ich trinke kalt Kaffee.", right: "Ich trinke kalten Kaffee." },
        { wrong: "Nette Leuten helfen.", right: "Nette Leute helfen." },
        { wrong: "Bei gutes Wetter.", right: "Bei gutem Wetter." },
      ],
      exercises: {},
      prevSlug: "adjektivdeklination-unbestimmter",
      nextSlug: "komparativ-superlativ",
    },
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "впізнавати ситуації без артикля",
        "переносити закінчення з артикля на прикметник",
        "правильно поводитися з Plural і Stoffnamen",
      ],
      ruleBox: {
        rule: "Без артикля → прикметник копіює закінчення артикля (m -er, f -e, n -es, Pl -e). Gen. m/n → -en.",
      },
      ukrainianTips: [
        "В українській «гарного дня!» = «<b>schönen Tag!</b>» — без артикля, з повним закінченням.",
        "Речовини й матеріали часто вживаються без артикля: <i>kalter Kaffee, gutes Brot, frische Milch</i>.",
        "У Plural без артикля: <b>nette Leute, deutsche Studenten</b>.",
      ],
      languageComparison: {
        commons: ["Прикметник узгоджується з іменником."],
        diffs: ["У німецькій без артикля закінчення прикметника стає максимально повним."],
        traps: ["Помилка: «mit kaltes Wasser» (треба <i>kaltem</i>)."],
      },
      summary: [
        "Без артикля → «сильна» відміна.",
        "Nom.: m -er, f -e, n -es, Pl -e.",
        "Akk.: m -en, f -e, n -es, Pl -e.",
        "Dat.: m/n -em, f -er, Pl -en.",
        "Gen. m/n → -en (виняток).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich trinke ___ Kaffee.", options: ["kalt","kalter","kalten","kaltes"], correct: 2 },
      { type: "mc", q: "Wir essen ___ Brot.", options: ["gut","guten","gutes","guter"], correct: 2 },
      { type: "mc", q: "Sie trinkt ___ Milch.", options: ["frisch","frischer","frische","frischen"], correct: 2, explain: "f Akk. → -e." },
      { type: "mc", q: "___ Leute helfen gern.", options: ["Nette","Netter","Netten","Nettes"], correct: 0 },
      { type: "gap", q: "Bei ___ Wetter spielen wir Fußball. (gut, Dat. n)", answer: "gutem" },
      { type: "gap", q: "Mit ___ Wasser. (kalt, Dat. n)", answer: "kaltem" },
      { type: "gap", q: "Mit ___ Milch. (frisch, Dat. f)", answer: "frischer" },
      { type: "gap", q: "Trotz ___ Wetters. (schlecht, Gen. n)", answer: "schlechten" },
      { type: "tf", q: "Без артикля прикметник бере закінчення артикля.", correct: true },
      { type: "tf", q: "У Plural без артикля Nom. = -en.", correct: false, explain: "Nom. Pl без артикля = -e (nette Leute)." },
      { type: "match", prompt: "Іменник без артикля → форма (Nom.):", pairs: [
        { left: "Kaffee (m)", right: "kalter" },
        { left: "Milch (f)", right: "frische" },
        { left: "Brot (n)", right: "gutes" },
        { left: "Leute (Pl)", right: "nette" },
      ]},
      { type: "multi", q: "Де -em?",
        options: ["bei gut__ Wetter","mit kalt__ Wasser","mit frisch__ Milch","auf hoh__ Berg"], correct: [0,1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich trinke kalt Kaffee.",
        correct: ["Ich trinke kalten Kaffee."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я люблю свіжий хліб.",
        de: ["Ich mag frisches Brot.","Ich liebe frisches Brot."] },
      { type: "writeFree", prompt: "3 речення з прикметниками без артикля (їжа, погода, люди).",
        sample: "Ich trinke gern heißen Tee. Bei schönem Wetter gehe ich spazieren. Nette Leute machen das Leben besser." },
    ],
  },

  // ===================================================================
  "komparativ-superlativ": {
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "утворювати Komparativ (-er) і Superlativ (am -sten)",
        "ставити умляут у коротких прикметниках",
        "правильно вживати als і wie",
      ],
      ruleBox: {
        rule: "<b>Komparativ</b>: прикметник + <b>-er</b> (+ умляут у коротких односкладових). <b>Superlativ</b>: <b>am</b> + прикметник + <b>-sten</b>.",
        examples: [
          { de: "klein → kleiner → am kleinsten", uk: "малий → менший → найменший" },
          { de: "alt → älter → am ältesten", uk: "старий → старший → найстарший" },
        ],
      },
      ukrainianTips: [
        "Українській «менший / найменший» = німецьке «kleiner / am kleinsten».",
        "Після Komparativ — <b>als</b> (ніж): <i>«größer als ich»</i>. Після «такий же, як» — <b>so … wie</b>: <i>«so groß wie ich»</i>.",
        "Багато коротких прикметників отримують <b>умляут</b>: alt→älter, jung→jünger, groß→größer, kurz→kürzer.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають 3 ступені порівняння."],
        diffs: ["У німецькій Superlativ перед іменником вимагає артикля: <i>der schnellste Wagen</i>."],
        traps: ["Помилка: «größer wie ich» (треба <i>als</i>)."],
      },
      summary: [
        "Komparativ: -er (+ умляут у коротких).",
        "Superlativ: <b>am -sten</b> (або <i>der/die/das -ste</i> перед іменником).",
        "Прикметники на -d/-t/-s/-ß/-z → <b>-esten</b>: am ältesten, am heißesten.",
        "Після Komparativ — <b>als</b>; рівність — <b>so … wie</b>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "klein → ___", options: ["kleiner","kleinster","mehr klein","am kleiner"], correct: 0 },
      { type: "mc", q: "alt → ___", options: ["alter","älter","altester","am alt"], correct: 1 },
      { type: "mc", q: "schnell (Superlativ)", options: ["am schnellste","am schnellsten","der schnellsten","schnellster"], correct: 1 },
      { type: "mc", q: "Mein Bruder ist größer ___ ich.", options: ["wie","als","wenn","so"], correct: 1 },
      { type: "gap", q: "Anna ist so groß ___ ihre Schwester.", answer: "wie" },
      { type: "gap", q: "Berlin ist ___ als München. (groß)", answer: "größer" },
      { type: "gap", q: "Im Sommer ist es am ___. (heiß)", answer: "heißesten" },
      { type: "gap", q: "Mein Auto ist das ___ Auto hier. (schnell)", answer: "schnellste" },
      { type: "tf", q: "Після Komparativ вживаємо als.", correct: true },
      { type: "tf", q: "alt → alter — правильно.", correct: false, explain: "Правильно: älter (умляут)." },
      { type: "match", prompt: "Позитив → Komparativ:", pairs: [
        { left: "jung", right: "jünger" },
        { left: "groß", right: "größer" },
        { left: "kurz", right: "kürzer" },
        { left: "klug", right: "klüger" },
      ]},
      { type: "multi", q: "Які прикметники отримують умляут?",
        options: ["alt","schnell","jung","schön","kurz","groß"], correct: [0,2,4,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Mein Bruder ist größer wie ich.",
        correct: ["Mein Bruder ist größer als ich."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Берлін більший за Гамбург.",
        de: ["Berlin ist größer als Hamburg."] },
      { type: "writeFree", prompt: "3 порівняння: рівність, Komparativ, Superlativ.",
        sample: "Anna ist so alt wie ich. Mein Bruder ist älter als ich. Mein Opa ist am ältesten." },
    ],
  },

  // ===================================================================
  "komparativ-unregelmaessig": {
    lesson: {
      slug: "komparativ-unregelmaessig",
      level: "A2",
      category: CAT,
      titleDe: "Unregelmäßige Steigerung",
      titleUk: "Нерегулярні ступені порівняння",
      goal: "Запам'ятати 5 ключових нерегулярних прикметників/прислівників: gut, viel, gern, hoch, nah.",
      explanation: [
        "Невелика група прикметників і прислівників має <b>повністю нерегулярні</b> форми ступенів — їх просто треба вивчити.",
        "<b>gut → besser → am besten</b> (добрий)",
        "<b>viel → mehr → am meisten</b> (багато)",
        "<b>gern → lieber → am liebsten</b> (охоче)",
        "<b>hoch → höher → am höchsten</b> (-c- зникає в Komparativ)",
        "<b>nah → näher → am nächsten</b> (умляут + -ch- → -chs-)",
        "<b>gern</b> — особливий: це прислівник, але утворює ступені; вживається з дієсловом: <i>«Ich trinke <b>lieber</b> Tee als Kaffee.»</i>",
      ],
      table: {
        headers: ["Positiv", "Komparativ", "Superlativ"],
        rows: [
          ["gut", "besser", "am besten / der beste"],
          ["viel", "mehr", "am meisten / die meisten"],
          ["gern", "lieber", "am liebsten"],
          ["hoch", "höher", "am höchsten / der höchste"],
          ["nah", "näher", "am nächsten / der nächste"],
        ],
      },
      examples: [
        { de: "Anna spricht besser Deutsch als ich.", uk: "Анна говорить німецькою краще за мене." },
        { de: "Sie hat die meisten Bücher.", uk: "У неї найбільше книг." },
        { de: "Ich trinke lieber Tee als Kaffee.", uk: "Я охочіше п'ю чай, ніж каву." },
        { de: "Mein Lieblingsessen ist Pizza — am liebsten esse ich Margherita.", uk: "Моя улюблена їжа — піца, найохочіше я їм маргариту." },
        { de: "Der Berg ist höher als der andere.", uk: "Ця гора вища за іншу." },
        { de: "Mein Haus ist näher zum Bahnhof.", uk: "Мій будинок ближче до вокзалу." },
        { de: "Wer kommt am nächsten?", uk: "Хто прийде наступним?" },
        { de: "Das ist mein bester Freund.", uk: "Це мій найкращий друг." },
      ],
      tip: "Запам'ятай 5 пар як «скоромовку»: <b>gut/besser/best · viel/mehr/meist · gern/lieber/liebst · hoch/höher/höchst · nah/näher/nächst</b>.",
      mistakes: [
        { wrong: "Ich spreche guter Deutsch als du.", right: "Ich spreche besser Deutsch als du." },
        { wrong: "Sie hat vieler Geld.", right: "Sie hat mehr Geld." },
        { wrong: "Ich esse gerner Pizza.", right: "Ich esse lieber Pizza." },
      ],
      exercises: {},
      prevSlug: "komparativ-superlativ",
      nextSlug: "adjektive-als-nomen",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "знати 5 нерегулярних ступенів напам'ять",
        "правильно вживати lieber з дієсловом",
        "розрізняти am besten / der beste",
      ],
      ruleBox: {
        rule: "gut→besser→am besten · viel→mehr→am meisten · gern→lieber→am liebsten · hoch→höher→am höchsten · nah→näher→am nächsten.",
      },
      ukrainianTips: [
        "Українській «краще» = <b>besser</b>, «більше» = <b>mehr</b>, «охочіше» = <b>lieber</b>.",
        "«am liebsten» = «найбільше люблю / найохочіше».",
        "У <b>näher / nächste</b> -ch- залишається, у <b>höher</b> — -c- зникає.",
      ],
      languageComparison: {
        commons: ["Українська теж має нерегулярні: добрий → кращий → найкращий."],
        diffs: ["Німецький набір нерегулярних значно менший — лише 5."],
        traps: ["Помилка: «mehrer» / «gerner» — таких форм немає."],
      },
      summary: [
        "5 нерегулярних: gut, viel, gern, hoch, nah.",
        "<b>gern</b> — прислівник з дієсловом: ich esse <b>lieber</b> Pizza.",
        "<b>hoch</b>: -c- зникає → höher; перед іменником повертається: der <b>hohe</b> Berg.",
      ],
    },
    exercises15: [
      { type: "mc", q: "gut → ___ → am besten", options: ["guter","besser","mehr","höher"], correct: 1 },
      { type: "mc", q: "viel → ___", options: ["vieler","mehr","mehrer","meiste"], correct: 1 },
      { type: "mc", q: "gern → ___", options: ["gerner","mehr gern","lieber","am gern"], correct: 2 },
      { type: "mc", q: "hoch → ___", options: ["hocher","höher","hocher","hohher"], correct: 1 },
      { type: "gap", q: "Anna spricht ___ Deutsch als ich. (gut, Komp.)", answer: "besser" },
      { type: "gap", q: "Ich trinke ___ Tee als Kaffee. (gern, Komp.)", answer: "lieber" },
      { type: "gap", q: "Sie hat die ___ Bücher. (viel, Sup.)", answer: "meisten" },
      { type: "gap", q: "Der Berg ist am ___. (hoch, Sup.)", answer: "höchsten" },
      { type: "tf", q: "lieber — Komparativ від gern.", correct: true },
      { type: "tf", q: "mehrer — правильна форма.", correct: false, explain: "Правильно: mehr." },
      { type: "match", prompt: "Positiv → Superlativ:", pairs: [
        { left: "gut", right: "am besten" },
        { left: "viel", right: "am meisten" },
        { left: "gern", right: "am liebsten" },
        { left: "hoch", right: "am höchsten" },
        { left: "nah", right: "am nächsten" },
      ]},
      { type: "multi", q: "Які форми правильні?",
        options: ["besser","gerner","mehr","höher","vieler","näher"], correct: [0,2,3,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich esse gerner Pizza.",
        correct: ["Ich esse lieber Pizza."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я найбільше люблю шоколад.",
        de: ["Am liebsten esse ich Schokolade.","Ich esse am liebsten Schokolade."] },
      { type: "writeFree", prompt: "3 речення з besser / lieber / am liebsten.",
        sample: "Mein Bruder kocht besser als ich. Ich trinke lieber Tee. Am liebsten esse ich Pizza." },
    ],
  },

  // ===================================================================
  "adjektive-als-nomen": {
    lesson: {
      slug: "adjektive-als-nomen",
      level: "A2",
      category: CAT,
      titleDe: "Adjektive als Nomen",
      titleUk: "Субстантивовані прикметники",
      goal: "Перетворювати прикметник на іменник і відмінювати його за тими самими правилами Adjektivdeklination.",
      explanation: [
        "Будь-який прикметник можна перетворити на <b>іменник</b>, написавши з великої літери: <i>deutsch → der Deutsche</i> (німець), <i>bekannt → ein Bekannter</i> (знайомий).",
        "Закінчення такого «прикметника-іменника» — <b>такі ж, як у звичайного прикметника перед іменником</b>: залежать від артикля.",
        "Жіночий рід: <b>die Deutsche, eine Deutsche</b>. Множина: <b>die Deutschen, Deutsche</b>.",
        "Часті: <b>der/die Deutsche, der/die Bekannte, der/die Angestellte, der/die Verwandte, der/die Erwachsene, der/die Reisende, der/die Kranke, der Beamte</b>.",
        "Нейтральні поняття: <b>das Gute, das Schöne, etwas Neues, nichts Besonderes</b> — теж із закінченнями за відмінком.",
      ],
      table: {
        headers: ["Артикль", "m", "f", "Pl"],
        rows: [
          ["der/die", "der Deutsche", "die Deutsche", "die Deutschen"],
          ["ein/eine", "ein Deutscher", "eine Deutsche", "Deutsche"],
          ["Akk. (der/die)", "den Deutschen", "die Deutsche", "die Deutschen"],
          ["Dat.", "dem Deutschen", "der Deutschen", "den Deutschen"],
        ],
      },
      examples: [
        { de: "Der Deutsche heißt Hans.", uk: "Цього німця звати Ганс." },
        { de: "Ich kenne eine Deutsche.", uk: "Я знаю одну німкеню." },
        { de: "Viele Deutsche reisen gern.", uk: "Багато німців люблять подорожувати." },
        { de: "Ein Bekannter hat mir geholfen.", uk: "Один знайомий мені допоміг." },
        { de: "Die Angestellten arbeiten viel.", uk: "Працівники багато працюють." },
        { de: "Ich wünsche dir alles Gute!", uk: "Бажаю тобі всього найкращого!" },
        { de: "Etwas Neues ist passiert.", uk: "Сталося щось нове." },
        { de: "Nichts Besonderes.", uk: "Нічого особливого." },
      ],
      tip: "Після <b>etwas, nichts, viel, wenig, alles</b> — субстантивований прикметник у середньому роді з великої літери: <i>etwas Schönes, nichts Neues, alles Gute</i>.",
      mistakes: [
        { wrong: "Ich kenne ein Deutsche.", right: "Ich kenne einen Deutschen." },
        { wrong: "etwas neues", right: "etwas Neues" },
        { wrong: "der Deutsch", right: "der Deutsche" },
      ],
      exercises: {},
      prevSlug: "komparativ-unregelmaessig",
      nextSlug: "farben-adjektive",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "перетворювати прикметник на іменник з великої літери",
        "відмінювати його як звичайний прикметник",
        "знати конструкції з etwas/nichts/alles + -es",
      ],
      ruleBox: {
        rule: "Прикметник-іменник = <b>з великої літери</b>, закінчення за Adjektivdeklination. Після etwas/nichts/alles → -es.",
      },
      ukrainianTips: [
        "Українській «знайомий / знайома» = <b>der/die Bekannte</b>.",
        "«Нічого нового» = <b>nichts Neues</b>, «щось гарне» = <b>etwas Schönes</b>.",
        "Не пиши таке слово з малої літери — буде помилка.",
      ],
      languageComparison: {
        commons: ["В обох мовах прикметник може ставати іменником."],
        diffs: ["У німецькій він зберігає всі закінчення прикметника + завжди з великої літери."],
        traps: ["Помилка: «ein Deutsche» (m) — треба <i>ein Deutscher</i>."],
      },
      summary: [
        "З великої літери + закінчення за артиклем.",
        "der Deutsche / ein Deutscher / Deutsche (Pl).",
        "Після etwas/nichts/alles → <b>-es</b>: etwas Neues.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich kenne ___ Deutsche.", options: ["ein","eine","einer","einen"], correct: 1, explain: "f Akk. → eine + Deutsche." },
      { type: "mc", q: "___ Deutsche heißt Hans.", options: ["Der","Den","Dem","Ein"], correct: 0 },
      { type: "mc", q: "Ein ___ hat mir geholfen.", options: ["Bekannte","Bekannter","Bekannten","Bekanntes"], correct: 1 },
      { type: "mc", q: "Etwas ___ ist passiert.", options: ["neu","neues","Neue","Neues"], correct: 3 },
      { type: "gap", q: "Ich wünsche dir alles ___. (gut)", answer: "Gute" },
      { type: "gap", q: "Die ___ arbeiten viel. (Angestellten, Nom. Pl.)", answer: "Angestellten" },
      { type: "gap", q: "Nichts ___. (besonder-)", answer: "Besonderes" },
      { type: "gap", q: "Ich helfe einem ___. (Verwandt-, Dat. m)", answer: "Verwandten" },
      { type: "tf", q: "Субстантивовані прикметники пишуть з малої літери.", correct: false, explain: "Завжди з великої." },
      { type: "tf", q: "Після etwas прикметник-іменник = -es.", correct: true },
      { type: "match", prompt: "Прикметник → іменник:", pairs: [
        { left: "deutsch", right: "der Deutsche" },
        { left: "bekannt", right: "der Bekannte" },
        { left: "krank", right: "der Kranke" },
        { left: "reisend", right: "der Reisende" },
      ]},
      { type: "multi", q: "Які форми правильні?",
        options: ["etwas Neues","etwas neues","alles Gute","alles gut","nichts Besonderes"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich kenne ein Deutsche.",
        correct: ["Ich kenne einen Deutschen."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я бажаю тобі всього найкращого.",
        de: ["Ich wünsche dir alles Gute."] },
      { type: "writeFree", prompt: "3 речення з субстантивованими прикметниками.",
        sample: "Mein Bekannter wohnt in Berlin. Die Angestellten haben heute frei. Ich wünsche dir alles Gute." },
    ],
  },

  // ===================================================================
  "farben-adjektive": {
    lesson: {
      slug: "farben-adjektive",
      level: "A2",
      category: CAT,
      titleDe: "Farben als Adjektive",
      titleUk: "Кольори як прикметники",
      goal: "Знати основні кольори, правильно відмінювати їх і користуватися винятками (rosa, lila, beige).",
      explanation: [
        "Кольори в німецькій — звичайні прикметники: <b>rot, blau, grün, gelb, schwarz, weiß, grau, braun, orange</b>. Відмінюються за загальними правилами Adjektivdeklination.",
        "Винятки — кольори іншомовного походження: <b>rosa, lila, beige</b>. Вони <b>НЕ змінюються</b>: <i>«eine <b>rosa</b> Jacke»</i>, не <i>«rosae»</i>.",
        "У присудковій позиції — як завжди без закінчення: <i>«Das Auto ist <b>rot</b>.»</i>",
        "Для відтінків додають префікси: <b>hell-</b> (світло-), <b>dunkel-</b> (темно-). Пишуться разом: <b>hellblau, dunkelgrün</b>.",
        "Кольори як іменники → з великої літери, середній рід: <b>das Rot, das Blau</b>.",
      ],
      table: {
        headers: ["Колір", "DE", "UK", "Приклад"],
        rows: [
          ["🔴", "rot", "червоний", "ein rotes Auto"],
          ["🔵", "blau", "синій", "der blaue Himmel"],
          ["🟢", "grün", "зелений", "das grüne Gras"],
          ["🟡", "gelb", "жовтий", "eine gelbe Banane"],
          ["⚫", "schwarz", "чорний", "die schwarze Katze"],
          ["⚪", "weiß", "білий", "ein weißes Hemd"],
          ["🩷", "rosa", "рожевий", "eine rosa Jacke (без зміни!)"],
          ["🟣", "lila", "фіолетовий", "ein lila Kleid (без зміни!)"],
        ],
      },
      examples: [
        { de: "Das Auto ist rot.", uk: "Машина червона." },
        { de: "Ich habe ein rotes Auto.", uk: "У мене червона машина." },
        { de: "Sie trägt eine rosa Jacke.", uk: "Вона носить рожеву куртку.", tag: "без зміни" },
        { de: "Wir kaufen ein lila Kleid.", uk: "Ми купуємо фіолетову сукню.", tag: "без зміни" },
        { de: "Der Himmel wird dunkelblau.", uk: "Небо стає темно-синім." },
        { de: "Sie hat helle Augen.", uk: "У неї світлі очі." },
        { de: "Das Rot dieser Blume ist intensiv.", uk: "Червоний колір цієї квітки яскравий.", tag: "як іменник" },
        { de: "Hellblau ist meine Lieblingsfarbe.", uk: "Світло-синій — мій улюблений колір." },
      ],
      tip: "<b>rosa, lila, beige</b> — НІКОЛИ не отримують закінчення. Хочеш «правильніше»? Скажи: <i>eine rosafarbene Jacke</i>.",
      mistakes: [
        { wrong: "eine rosae Jacke", right: "eine rosa Jacke" },
        { wrong: "ein blau Auto", right: "ein blaues Auto" },
        { wrong: "die schwarz Katze", right: "die schwarze Katze" },
      ],
      exercises: {},
      prevSlug: "adjektive-als-nomen",
    },
    extras: {
      duration: 10,
      premium: false,
      learningGoals: [
        "знати топ-10 кольорів напам'ять",
        "правильно відмінювати кольори за артиклем",
        "не змінювати rosa/lila/beige",
      ],
      ruleBox: {
        rule: "Звичайні кольори → як прикметники. <b>rosa, lila, beige</b> → без закінчення.",
      },
      ukrainianTips: [
        "Українській «червона машина» = <b>ein rotes Auto</b> (Akk.) / <b>das rote Auto</b> (Nom. n).",
        "Не намагайся «правильно» закінчити rosa/lila — це помилка.",
        "<b>hell-</b> і <b>dunkel-</b> пишуться <b>разом</b> з кольором: hellblau, dunkelgrün.",
      ],
      languageComparison: {
        commons: ["Кольори в обох мовах — прикметники."],
        diffs: ["Українська змінює всі кольори; німецька — крім rosa/lila/beige."],
        traps: ["Помилка: «eine rosae Jacke»."],
      },
      summary: [
        "Звичайні кольори: rot, blau, grün, gelb, schwarz, weiß, grau, braun.",
        "Без зміни: <b>rosa, lila, beige</b>.",
        "<b>hell- / dunkel-</b> → разом.",
        "Як іменник → з великої літери, середній рід.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe ein ___ Auto.", options: ["rot","rote","roten","rotes"], correct: 3 },
      { type: "mc", q: "Sie trägt eine ___ Jacke. (рожева)", options: ["rosa","rose","rosae","rosen"], correct: 0 },
      { type: "mc", q: "Die ___ Katze schläft.", options: ["schwarz","schwarze","schwarzen","schwarzes"], correct: 1 },
      { type: "mc", q: "Das Auto ist ___.", options: ["rot","rotes","roten","rote"], correct: 0, explain: "prädikativ → без закінчення." },
      { type: "gap", q: "Wir kaufen ein ___ Kleid. (lila)", answer: "lila", hint: "без закінчення!" },
      { type: "gap", q: "Der ___ Himmel. (blau, Nom. m)", answer: "blaue" },
      { type: "gap", q: "Ein ___ Hemd. (weiß, Nom. n)", answer: "weißes" },
      { type: "gap", q: "Sie hat ___ Augen. (hell, Pl.)", answer: "helle" },
      { type: "tf", q: "rosa отримує закінчення -e в Nom. f.", correct: false },
      { type: "tf", q: "hell- і dunkel- пишуться разом з кольором.", correct: true },
      { type: "match", prompt: "DE → UK:", pairs: [
        { left: "rot", right: "червоний" },
        { left: "blau", right: "синій" },
        { left: "grün", right: "зелений" },
        { left: "gelb", right: "жовтий" },
        { left: "schwarz", right: "чорний" },
        { left: "weiß", right: "білий" },
      ]},
      { type: "multi", q: "Які кольори НЕ змінюються?",
        options: ["rosa","blau","lila","grün","beige","rot"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "eine rosae Jacke",
        correct: ["eine rosa Jacke"] },
      { type: "translate", prompt: "Переклади:",
        uk: "У мене червоний светр і чорні штани.",
        de: ["Ich habe einen roten Pullover und eine schwarze Hose.","Ich habe einen roten Pulli und eine schwarze Hose."] },
      { type: "writeFree", prompt: "Опиши свій одяг 3 реченнями з кольорами.",
        sample: "Heute trage ich eine blaue Jeans. Mein Pullover ist grau. Ich habe auch eine rosa Mütze." },
    ],
  },
};
