// A2 · Прислівники — 8 повних уроків.
import type { A2Map } from "./_helpers";

const CAT = "Прислівники";

export const adverbienA2: A2Map = {
  // ===================================================================
  lokaladverbien: {
    lesson: {
      slug: "lokaladverbien",
      level: "A2",
      category: CAT,
      titleDe: "Lokaladverbien",
      titleUk: "Прислівники місця",
      goal: "Відповідати на питання Wo? Wohin? Woher? за допомогою коротких прислівників.",
      explanation: [
        "<b>Lokaladverbien</b> — прислівники місця. Вони не змінюються і відповідають на три питання: <b>Wo? (де)</b>, <b>Wohin? (куди)</b>, <b>Woher? (звідки)</b>.",
        "Найважливіші: <b>hier, da, dort, oben, unten, links, rechts, vorn, hinten, drinnen, draußen, überall, nirgends</b>.",
        "Для напряму додаємо <b>-hin</b> (туди) або <b>-her</b> (сюди): <i>dorthin (туди), dorther (звідти), hierhin (сюди), woher (звідки)</i>.",
        "<b>hier</b> — близько до мовця, <b>da</b> — нейтрально (тут/там залежно від контексту), <b>dort</b> — далеко.",
      ],
      table: {
        headers: ["Wo? (де)", "Wohin? (куди)", "Woher? (звідки)"],
        rows: [
          ["hier", "hierhin / her", "von hier"],
          ["da / dort", "dahin / dorthin", "von da / von dort"],
          ["oben", "nach oben", "von oben"],
          ["unten", "nach unten", "von unten"],
          ["links", "nach links", "von links"],
          ["rechts", "nach rechts", "von rechts"],
          ["drinnen", "hinein / rein", "von drinnen"],
          ["draußen", "hinaus / raus", "von draußen"],
        ],
      },
      examples: [
        { de: "Ich wohne hier.", uk: "Я живу тут." },
        { de: "Komm her!", uk: "Іди сюди!" },
        { de: "Geh dorthin!", uk: "Іди туди!" },
        { de: "Das Buch liegt oben.", uk: "Книга лежить угорі." },
        { de: "Bitte nach links!", uk: "Будь ласка, ліворуч!" },
        { de: "Wir gehen nach draußen.", uk: "Ми йдемо надвір." },
        { de: "Woher kommst du?", uk: "Звідки ти?" },
        { de: "Überall sind Touristen.", uk: "Скрізь туристи." },
      ],
      tip: "Просте правило: <b>her</b> = до мовця (сюди), <b>hin</b> = від мовця (туди). <i>«Komm her!»</i> vs <i>«Geh hin!»</i>",
      mistakes: [
        { wrong: "Komm hin!", right: "Komm her!" },
        { wrong: "Ich wohne in hier.", right: "Ich wohne hier." },
        { wrong: "Das ist oberhalb.", right: "Das ist oben." },
      ],
      exercises: {},
      nextSlug: "temporaladverbien",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "розрізняти Wo? / Wohin? / Woher?",
        "правильно вживати her (сюди) і hin (туди)",
        "знати топ-10 прислівників місця",
      ],
      ruleBox: {
        rule: "<b>her</b> = до мовця · <b>hin</b> = від мовця. Lokaladverbien <b>не змінюються</b>.",
      },
      ukrainianTips: [
        "Українські «сюди / туди / звідси / звідти» = <b>hierhin / dorthin / von hier / von dort</b>.",
        "«Йди сюди» = <i>Komm her!</i> (а не «komm hier!»).",
        "<b>links / rechts</b> без артикля: <i>nach links</i>, не <i>nach dem links</i>.",
      ],
      languageComparison: {
        commons: ["Обидві мови розрізняють «де» і «куди»."],
        diffs: ["Німецька має окреме <b>woher?</b> для «звідки», де українська вживає «звідки»."],
        traps: ["Помилка: вживати «hier» замість «her» зі словами руху."],
      },
      summary: [
        "Wo? → hier / da / dort / oben / unten / links / rechts.",
        "Wohin? → +hin / nach +напрям.",
        "Woher? → +her / von +напрям.",
        "Lokaladverbien не змінюються.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich wohne ___.", options: ["hier","her","hin","hierhin"], correct: 0 },
      { type: "mc", q: "Komm ___! (сюди)", options: ["hin","her","hier","da"], correct: 1 },
      { type: "mc", q: "Geh ___! (туди)", options: ["her","hin","hier","dorther"], correct: 1 },
      { type: "mc", q: "Bitte nach ___! (ліворуч)", options: ["link","links","linke","linken"], correct: 1 },
      { type: "gap", q: "Wir gehen nach ___. (надвір)", answer: "draußen" },
      { type: "gap", q: "Das Buch liegt ___. (угорі)", answer: "oben" },
      { type: "gap", q: "___ kommst du? (звідки)", answer: "Woher" },
      { type: "gap", q: "Geh ___! (туди)", answer: "dorthin" },
      { type: "tf", q: "Lokaladverbien змінюються за родами.", correct: false },
      { type: "tf", q: "her = до мовця.", correct: true },
      { type: "match", prompt: "Питання → відповідь:", pairs: [
        { left: "Wo?", right: "hier" },
        { left: "Wohin?", right: "dorthin" },
        { left: "Woher?", right: "von dort" },
        { left: "Wo? (всюди)", right: "überall" },
      ]},
      { type: "multi", q: "Які слова — Lokaladverbien?",
        options: ["hier","heute","oben","gern","links","oft"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Komm hin!", correct: ["Komm her!"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Звідки ти? — Я звідти.",
        de: ["Woher kommst du? — Ich komme von dort.","Woher bist du? — Ich bin von dort."] },
      { type: "writeFree", prompt: "3 речення з Lokaladverbien.",
        sample: "Hier wohne ich. Mein Bruder wohnt dort. Komm bitte her!" },
    ],
  },

  // ===================================================================
  temporaladverbien: {
    lesson: {
      slug: "temporaladverbien",
      level: "A2",
      category: CAT,
      titleDe: "Temporaladverbien",
      titleUk: "Прислівники часу",
      goal: "Будувати речення з чіткою часовою прив'язкою — Wann? Wie oft? Wie lange? Seit wann?",
      explanation: [
        "<b>Temporaladverbien</b> відповідають на питання <b>Wann? (коли)</b>, <b>Wie oft? (як часто)</b>, <b>Wie lange? (як довго)</b>, <b>Seit wann? (відколи)</b>.",
        "Точка часу: <b>heute, gestern, morgen, vorgestern, übermorgen, jetzt, gleich, sofort, bald, später, früher, damals, neulich</b>.",
        "Тривалість: <b>lange, kurz, immer, stundenlang</b>.",
        "Послідовність: <b>zuerst, dann, danach, später, schließlich, endlich</b>.",
        "Часовий прислівник часто стоїть на <b>1 місці</b> (тоді субʼєкт іде після дієслова) або після дієслова: <i>«Morgen fahre ich…» / «Ich fahre morgen…»</i>.",
      ],
      table: {
        headers: ["Тип", "Слова", "Приклад"],
        rows: [
          ["точка часу", "heute, gestern, morgen, jetzt, bald", "Ich komme bald."],
          ["тривалість", "lange, kurz, immer", "Wir warten lange."],
          ["послідовність", "zuerst, dann, danach, schließlich", "Zuerst esse ich, dann lerne ich."],
          ["частота", "immer, oft, manchmal, selten, nie", "Er kommt nie zu spät."],
        ],
      },
      examples: [
        { de: "Morgen fahre ich nach Berlin.", uk: "Завтра я їду до Берліна." },
        { de: "Ich habe heute viel gelernt.", uk: "Сьогодні я багато вчив(ла)." },
        { de: "Bald sind Ferien.", uk: "Скоро канікули." },
        { de: "Früher habe ich in Wien gewohnt.", uk: "Раніше я жив(ла) у Відні." },
        { de: "Zuerst frühstücke ich, dann gehe ich zur Arbeit.", uk: "Спершу я снідаю, потім іду на роботу." },
        { de: "Wir warten schon lange.", uk: "Ми чекаємо вже довго." },
        { de: "Jetzt habe ich keine Zeit.", uk: "Зараз у мене немає часу." },
        { de: "Endlich bist du da!", uk: "Нарешті ти тут!" },
      ],
      tip: "Запам'ятай ланцюжок послідовності: <b>zuerst → dann → danach → schließlich</b>. З ним легко розповідати про порядок дій.",
      mistakes: [
        { wrong: "Ich morgen fahre nach Berlin.", right: "Morgen fahre ich nach Berlin." },
        { wrong: "Endlich du bist da!", right: "Endlich bist du da!" },
        { wrong: "Ich habe immer Zeit nicht.", right: "Ich habe nie Zeit." },
      ],
      exercises: {},
      prevSlug: "lokaladverbien",
      nextSlug: "modaladverbien",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "розрізняти 4 типи Temporaladverbien",
        "правильно ставити час на 1 місці",
        "знати ланцюжок zuerst/dann/danach/schließlich",
      ],
      ruleBox: {
        rule: "Temporaladverbien — не змінюються. Часто на 1 місці → дієслово на 2 місці, субʼєкт після нього.",
      },
      ukrainianTips: [
        "Українська «завтра я їду» = німецьке <b>Morgen fahre ich</b> — порядок змінюється!",
        "Не плутай: <b>nie</b> = ніколи, <b>noch nicht</b> = ще не.",
        "<b>früher</b> ≠ «швидше»; тут — «раніше / колись давно».",
      ],
      languageComparison: {
        commons: ["Обидві мови мають широкий набір прислівників часу."],
        diffs: ["У німецькій 1-ша позиція переставляє дієслово."],
        traps: ["Помилка: «Ich morgen fahre» (треба «Morgen fahre ich»)."],
      },
      summary: [
        "Wann? → heute, morgen, jetzt, bald, später.",
        "Wie oft? → immer, oft, manchmal, selten, nie.",
        "Послідовність: zuerst → dann → danach → schließlich.",
        "Час на 1 місці → дієслово на 2 місці.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Виправ порядок: «Ich morgen fahre.»",
        options: ["Ich morgen fahre.","Morgen ich fahre.","Morgen fahre ich.","Fahre ich morgen."], correct: 2 },
      { type: "mc", q: "Ми ще довго чекаємо. — Wir warten ___.", options: ["schon lange","lange schon","seit lang","langes"], correct: 0 },
      { type: "mc", q: "Скоро канікули. — ___ sind Ferien.", options: ["Bald","Spät","Endlich","Damals"], correct: 0 },
      { type: "mc", q: "Я ніколи не запізнююсь.", options: ["Ich komme immer zu spät.","Ich komme nie zu spät.","Ich komme oft zu spät.","Ich komme noch zu spät."], correct: 1 },
      { type: "gap", q: "___ fahre ich nach Berlin. (завтра)", answer: "Morgen" },
      { type: "gap", q: "___ frühstücke ich, dann gehe ich. (спершу)", answer: "Zuerst" },
      { type: "gap", q: "___ bist du da! (нарешті)", answer: "Endlich" },
      { type: "gap", q: "___ habe ich in Wien gewohnt. (раніше)", answer: "Früher" },
      { type: "tf", q: "Якщо час на 1 місці, субʼєкт іде після дієслова.", correct: true },
      { type: "tf", q: "nie = ніколи.", correct: true },
      { type: "match", prompt: "Слово → переклад:", pairs: [
        { left: "heute", right: "сьогодні" },
        { left: "morgen", right: "завтра" },
        { left: "gestern", right: "вчора" },
        { left: "bald", right: "скоро" },
        { left: "später", right: "пізніше" },
      ]},
      { type: "order", prompt: "Склади:",
        words: ["nach Berlin","ich","morgen","fahre"],
        correct: ["morgen","fahre","ich","nach Berlin"] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich heute viel gelernt habe.",
        correct: ["Heute habe ich viel gelernt.","Ich habe heute viel gelernt."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Спершу я снідаю, потім іду на роботу.",
        de: ["Zuerst frühstücke ich, dann gehe ich zur Arbeit."] },
      { type: "writeFree", prompt: "3 речення про твій день з zuerst / dann / später.",
        sample: "Zuerst trinke ich Kaffee. Dann lerne ich Deutsch. Später treffe ich meine Freunde." },
    ],
  },

  // ===================================================================
  modaladverbien: {
    lesson: {
      slug: "modaladverbien",
      level: "A2",
      category: CAT,
      titleDe: "Modaladverbien",
      titleUk: "Прислівники способу та ставлення",
      goal: "Виражати ставлення мовця та обставини дії: gern, leider, hoffentlich, vielleicht…",
      explanation: [
        "<b>Modaladverbien</b> описують спосіб дії або <b>ставлення мовця</b> до неї: упевненість, надію, шкоду, можливість.",
        "Основні: <b>gern, ungern, leider, hoffentlich, vielleicht, sicher, bestimmt, wahrscheinlich, glücklicherweise, natürlich, eigentlich</b>.",
        "<b>gern</b> вживається з дієсловом, означає «охоче / люблю робити»: <i>«Ich trinke gern Kaffee»</i>.",
        "Прислівники ставлення (leider, hoffentlich, vielleicht) часто стоять на <b>1 місці</b>: <i>«Leider habe ich keine Zeit»</i>.",
      ],
      table: {
        headers: ["Слово", "Значення", "Приклад"],
        rows: [
          ["gern", "охоче, люблю", "Ich lese gern."],
          ["leider", "на жаль", "Leider regnet es."],
          ["hoffentlich", "сподіваюся", "Hoffentlich kommt er."],
          ["vielleicht", "можливо", "Vielleicht hat sie Recht."],
          ["sicher / bestimmt", "напевно, обов'язково", "Er kommt sicher."],
          ["wahrscheinlich", "ймовірно", "Wahrscheinlich regnet es morgen."],
          ["natürlich", "звичайно", "Natürlich helfe ich dir."],
          ["eigentlich", "власне кажучи", "Eigentlich bin ich müde."],
        ],
      },
      examples: [
        { de: "Ich trinke gern Tee.", uk: "Я люблю чай (охоче п'ю)." },
        { de: "Leider habe ich keine Zeit.", uk: "На жаль, у мене немає часу." },
        { de: "Hoffentlich wird es nicht regnen.", uk: "Сподіваюся, не буде дощу." },
        { de: "Vielleicht kommt sie später.", uk: "Можливо, вона прийде пізніше." },
        { de: "Natürlich helfe ich dir.", uk: "Звичайно, я тобі допоможу." },
        { de: "Er kommt sicher um 8.", uk: "Він точно прийде о 8-й." },
        { de: "Eigentlich wollte ich heute Sport machen.", uk: "Власне, я хотів(ла) сьогодні поспортувати." },
        { de: "Wahrscheinlich bin ich krank.", uk: "Ймовірно, я хворий(а)." },
      ],
      tip: "Запам'ятай: ступені <b>gern</b> неправильні: <i>gern → lieber → am liebsten</i>. Із дієсловом — без артикля, без закінчення.",
      mistakes: [
        { wrong: "Ich gern trinke Tee.", right: "Ich trinke gern Tee." },
        { wrong: "Leider ich habe keine Zeit.", right: "Leider habe ich keine Zeit." },
        { wrong: "Ich trinke gerne als Kaffee.", right: "Ich trinke lieber Tee als Kaffee." },
      ],
      exercises: {},
      prevSlug: "temporaladverbien",
      nextSlug: "kausaladverbien",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "виражати свої уподобання через gern / lieber",
        "ставити leider / hoffentlich / vielleicht на 1 місце",
        "розрізняти sicher (напевно) і vielleicht (можливо)",
      ],
      ruleBox: {
        rule: "Modaladverbien часто на 1 місці; <b>gern</b> — з дієсловом, без артикля.",
      },
      ukrainianTips: [
        "Українській «я люблю каву» (як уподобання) = <b>Ich trinke gern Kaffee</b>, не <i>ich liebe</i>.",
        "<b>leider</b> = «на жаль» (а не «леді»!).",
        "<b>hoffentlich</b> часто заміняє ціле підрядне з «сподіваюсь, що».",
      ],
      languageComparison: {
        commons: ["Обидві мови мають прислівники ставлення."],
        diffs: ["У німецькій вони стають на 1 місце й переставляють дієслово."],
        traps: ["Помилка: «leider ich habe» (треба «leider habe ich»)."],
      },
      summary: [
        "gern → з дієсловом («охоче»).",
        "leider / hoffentlich / vielleicht — часто на 1 місці.",
        "sicher / bestimmt = впевненість, wahrscheinlich = ймовірно.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Я охоче п'ю чай.", options: ["Ich trinke Tee gern.","Ich gern Tee trinke.","Ich trinke gern Tee.","Gern ich trinke Tee."], correct: 2 },
      { type: "mc", q: "На жаль, у мене немає часу.",
        options: ["Leider ich habe keine Zeit.","Leider habe ich keine Zeit.","Ich leider habe keine Zeit.","Habe ich leider keine Zeit."], correct: 1 },
      { type: "mc", q: "Сподіваюся, прийде. — ___ kommt er.", options: ["Vielleicht","Natürlich","Hoffentlich","Eigentlich"], correct: 2 },
      { type: "mc", q: "Звичайно, я допоможу. — ___ helfe ich dir.", options: ["Eigentlich","Natürlich","Vielleicht","Leider"], correct: 1 },
      { type: "gap", q: "___ regnet es morgen. (ймовірно)", answer: "Wahrscheinlich" },
      { type: "gap", q: "___ habe ich keine Zeit. (на жаль)", answer: "Leider" },
      { type: "gap", q: "Ich trinke ___ Kaffee. (охоче)", answer: "gern" },
      { type: "gap", q: "Er kommt ___ um 8. (напевно)", answer: "sicher" },
      { type: "tf", q: "gern означає «охоче / люблю».", correct: true },
      { type: "tf", q: "Leider стоїть тільки в кінці речення.", correct: false, explain: "Часто на 1 місці." },
      { type: "match", prompt: "DE → UK:", pairs: [
        { left: "gern", right: "охоче" },
        { left: "leider", right: "на жаль" },
        { left: "hoffentlich", right: "сподіваюсь" },
        { left: "vielleicht", right: "можливо" },
        { left: "natürlich", right: "звичайно" },
      ]},
      { type: "order", prompt: "Склади:",
        words: ["keine Zeit","habe","ich","leider"],
        correct: ["leider","habe","ich","keine Zeit"] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich gern trinke Tee.",
        correct: ["Ich trinke gern Tee."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Можливо, вона прийде пізніше.",
        de: ["Vielleicht kommt sie später.","Sie kommt vielleicht später."] },
      { type: "writeFree", prompt: "3 речення з gern / leider / hoffentlich.",
        sample: "Ich lese gern Bücher. Leider habe ich heute keine Zeit. Hoffentlich treffen wir uns bald." },
    ],
  },

  // ===================================================================
  kausaladverbien: {
    lesson: {
      slug: "kausaladverbien",
      level: "A2",
      category: CAT,
      titleDe: "Kausaladverbien",
      titleUk: "Прислівники причини та наслідку",
      goal: "Зʼєднувати два речення через причину/наслідок: deshalb, deswegen, darum, daher, trotzdem.",
      explanation: [
        "<b>Kausaladverbien</b> показують <b>наслідок</b> попереднього речення: <i>«Es regnet. <b>Deshalb</b> bleibe ich zu Hause.»</i>",
        "Найважливіші: <b>deshalb, deswegen, darum, daher</b> — всі означають «тому». <b>trotzdem</b> — «незважаючи на це», <b>also</b> — «отже».",
        "Це <b>прислівники</b>, а не сполучники: вони займають <b>1 місце</b>, тому дієслово стоїть на 2 місці, а субʼєкт — після нього.",
        "Не плутай із сполучником <b>weil</b>: <i>«Ich bleibe zu Hause, weil es regnet»</i> (підрядне) vs <i>«Es regnet, deshalb bleibe ich zu Hause»</i> (два головних).",
      ],
      table: {
        headers: ["Слово", "Значення", "Приклад"],
        rows: [
          ["deshalb / deswegen / darum / daher", "тому", "Es regnet, deshalb bleibe ich zu Hause."],
          ["trotzdem", "незважаючи на це", "Es regnet, trotzdem gehe ich spazieren."],
          ["also", "отже", "Du lernst viel, also bestehst du."],
          ["sonst", "інакше", "Beeil dich, sonst kommen wir zu spät."],
        ],
      },
      examples: [
        { de: "Es regnet, deshalb bleibe ich zu Hause.", uk: "Іде дощ, тому я залишаюсь удома." },
        { de: "Ich bin müde, deswegen gehe ich ins Bett.", uk: "Я втомлений, тому йду спати." },
        { de: "Er ist krank, trotzdem arbeitet er.", uk: "Він хворий, незважаючи на це, працює." },
        { de: "Du musst lernen, sonst fällst du durch.", uk: "Маєш вчити, інакше провалиш." },
        { de: "Ich habe Hunger, also esse ich.", uk: "Я голодний, отже їм." },
        { de: "Anna hat verschlafen, darum kam sie zu spät.", uk: "Анна проспала, тому запізнилась." },
        { de: "Es ist kalt, daher trage ich einen Mantel.", uk: "Холодно, тому я ношу пальто." },
        { de: "Trotzdem mache ich weiter.", uk: "Все одно я продовжую." },
      ],
      tip: "Тест: після <b>deshalb / trotzdem</b> дієслово на <b>2 місці</b>; після <b>weil</b> — у <b>кінці</b>. Це різні граматичні «звірі».",
      mistakes: [
        { wrong: "Es regnet, deshalb ich bleibe zu Hause.", right: "Es regnet, deshalb bleibe ich zu Hause." },
        { wrong: "Ich bin krank, trotzdem ich arbeite.", right: "Ich bin krank, trotzdem arbeite ich." },
        { wrong: "Es regnet, weil bleibe ich zu Hause.", right: "Ich bleibe zu Hause, weil es regnet." },
      ],
      exercises: {},
      prevSlug: "modaladverbien",
      nextSlug: "haeufigkeitsadverbien",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "вживати deshalb/deswegen/darum/daher як синоніми",
        "не плутати з weil (підрядне)",
        "розуміти trotzdem і sonst",
      ],
      ruleBox: {
        rule: "Прислівник на 1 місці → дієслово на 2 → субʼєкт після. <b>weil</b> ≠ <b>deshalb</b>.",
      },
      ukrainianTips: [
        "Українській «тому» = всі чотири: <b>deshalb / deswegen / darum / daher</b>. Можна обирати будь-яке.",
        "Українській «незважаючи на це» = <b>trotzdem</b>.",
        "Не змішуй: «<i>… weil ich krank bin</i>» — дієслово в кінці; «<i>…, deshalb bleibe ich</i>» — на 2 місці.",
      ],
      languageComparison: {
        commons: ["Обидві мови виражають причину/наслідок прислівниками."],
        diffs: ["У німецькій після Kausaladverb обовʼязкова інверсія."],
        traps: ["Помилка: «deshalb ich bleibe» замість «deshalb bleibe ich»."],
      },
      summary: [
        "deshalb / deswegen / darum / daher = тому.",
        "trotzdem = незважаючи на це.",
        "sonst = інакше.",
        "Після них — інверсія: V2 + S.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Es regnet, deshalb ___ ich zu Hause.", options: ["bleibe","ich bleibe","bleibe ich","ich bleibe nicht"], correct: 0 },
      { type: "mc", q: "Ich bin müde, ___ gehe ich ins Bett.", options: ["weil","deshalb","obwohl","aber"], correct: 1 },
      { type: "mc", q: "Er ist krank, ___ arbeitet er.", options: ["deshalb","trotzdem","also","sonst"], correct: 1 },
      { type: "mc", q: "Beeil dich, ___ kommen wir zu spät.", options: ["also","sonst","trotzdem","deshalb"], correct: 1 },
      { type: "gap", q: "Ich habe Hunger, ___ esse ich. (отже)", answer: "also" },
      { type: "gap", q: "Es ist kalt, ___ trage ich einen Mantel. (тому)", answer: "deshalb", hint: "або deswegen / darum / daher" },
      { type: "gap", q: "Anna hat verschlafen, ___ kam sie zu spät. (тому)", answer: "darum", hint: "будь-який синонім" },
      { type: "gap", q: "Es ist spät, ___ gehe ich noch aus. (незважаючи на це)", answer: "trotzdem" },
      { type: "tf", q: "Після deshalb дієслово на 2 місці.", correct: true },
      { type: "tf", q: "weil і deshalb — це те саме граматично.", correct: false, explain: "weil — сполучник (V в кінці), deshalb — прислівник (V на 2 місці)." },
      { type: "match", prompt: "DE → UK:", pairs: [
        { left: "deshalb", right: "тому" },
        { left: "trotzdem", right: "незважаючи на це" },
        { left: "also", right: "отже" },
        { left: "sonst", right: "інакше" },
      ]},
      { type: "order", prompt: "Склади:",
        words: ["zu Hause","bleibe","deshalb","ich"],
        correct: ["deshalb","bleibe","ich","zu Hause"] },
      { type: "correct", prompt: "Виправ:", wrong: "Es regnet, deshalb ich bleibe zu Hause.",
        correct: ["Es regnet, deshalb bleibe ich zu Hause."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Він втомлений, тому йде спати.",
        de: ["Er ist müde, deshalb geht er ins Bett.","Er ist müde, deswegen geht er ins Bett."] },
      { type: "writeFree", prompt: "3 ланцюжки «причина → наслідок» з deshalb / trotzdem / sonst.",
        sample: "Es ist kalt, deshalb trage ich einen Mantel. Ich bin müde, trotzdem lerne ich. Beeil dich, sonst verpassen wir den Zug." },
    ],
  },

  // ===================================================================
  haeufigkeitsadverbien: {
    lesson: {
      slug: "haeufigkeitsadverbien",
      level: "A2",
      category: CAT,
      titleDe: "Häufigkeitsadverbien",
      titleUk: "Прислівники частоти",
      goal: "Точно описувати, як часто щось відбувається — від nie до immer.",
      explanation: [
        "<b>Häufigkeitsadverbien</b> відповідають на питання <b>Wie oft? (як часто)</b>.",
        "Шкала від 100% до 0%: <b>immer (завжди) → fast immer → meistens → oft → manchmal → selten → fast nie → nie (ніколи)</b>.",
        "Стоять зазвичай <b>після відмінюваного дієслова</b> або <b>на 1 місці</b> з інверсією.",
        "З частотою <b>nie</b> уже саме слово робить речення заперечним — додаткове <b>nicht</b> не потрібне.",
      ],
      table: {
        headers: ["%", "DE", "UK"],
        rows: [
          ["100", "immer", "завжди"],
          ["~90", "fast immer / meistens", "майже завжди / переважно"],
          ["~70", "oft", "часто"],
          ["~50", "manchmal", "іноді"],
          ["~30", "selten", "рідко"],
          ["~5", "fast nie / kaum", "майже ніколи / ледь"],
          ["0", "nie / niemals", "ніколи"],
        ],
      },
      examples: [
        { de: "Ich trinke immer Kaffee am Morgen.", uk: "Я завжди п'ю каву зранку." },
        { de: "Meistens lerne ich abends Deutsch.", uk: "Переважно вчу німецьку ввечері." },
        { de: "Wir gehen oft ins Kino.", uk: "Ми часто ходимо в кіно." },
        { de: "Manchmal koche ich italienisch.", uk: "Іноді я готую італійську кухню." },
        { de: "Er ist selten zu Hause.", uk: "Він рідко вдома." },
        { de: "Ich rauche nie.", uk: "Я ніколи не курю." },
        { de: "Wie oft machst du Sport?", uk: "Як часто займаєшся спортом?" },
        { de: "Sie kommt fast immer pünktlich.", uk: "Вона майже завжди приходить вчасно." },
      ],
      tip: "Запам'ятай шкалу як «сходи»: <b>immer → meistens → oft → manchmal → selten → nie</b>. Знай свою «середню» точку — це <b>manchmal</b>.",
      mistakes: [
        { wrong: "Ich nie rauche nicht.", right: "Ich rauche nie." },
        { wrong: "Manchmal ich koche italienisch.", right: "Manchmal koche ich italienisch." },
        { wrong: "Er ist selten nicht zu Hause.", right: "Er ist selten zu Hause." },
      ],
      exercises: {},
      prevSlug: "kausaladverbien",
      nextSlug: "graduierungsadverbien",
    },
    extras: {
      duration: 10,
      premium: false,
      learningGoals: [
        "знати шкалу частоти від nie до immer",
        "не дублювати nicht із nie",
        "правильно ставити прислівник у реченні",
      ],
      ruleBox: {
        rule: "Шкала: immer → meistens → oft → manchmal → selten → nie. <b>nie</b> уже = заперечення.",
      },
      ukrainianTips: [
        "Українській «ніколи не» = просто <b>nie</b> (без додаткового <i>nicht</i>).",
        "<b>oft</b> = часто, <b>manchmal</b> = іноді, <b>selten</b> = рідко — найуживаніші.",
        "<b>Wie oft?</b> — стандартне питання, варто завчити.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають градацію частоти."],
        diffs: ["В українській «ніколи не…», у німецькій — лише <i>nie</i>."],
        traps: ["Помилка: «Ich nie rauche nicht»."],
      },
      summary: [
        "immer (100%) → nie (0%).",
        "nie заміняє nicht.",
        "Прислівник зазвичай після дієслова або на 1 місці.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich trinke ___ Kaffee am Morgen. (завжди)", options: ["nie","immer","selten","manchmal"], correct: 1 },
      { type: "mc", q: "Wir gehen ___ ins Kino. (часто)", options: ["oft","selten","kaum","nie"], correct: 0 },
      { type: "mc", q: "Я ніколи не курю.", options: ["Ich rauche nicht nie.","Ich nie rauche.","Ich rauche nie.","Ich rauche immer nicht."], correct: 2 },
      { type: "mc", q: "Виправ: «Manchmal ich koche.»",
        options: ["Ich manchmal koche.","Manchmal koche ich.","Manchmal ich koche.","Ich koche manchmal nicht."], correct: 1 },
      { type: "gap", q: "Sie kommt ___ pünktlich. (майже завжди)", answer: "fast immer" },
      { type: "gap", q: "Er ist ___ zu Hause. (рідко)", answer: "selten" },
      { type: "gap", q: "Ich gehe ___ ins Theater. (іноді)", answer: "manchmal" },
      { type: "gap", q: "Wir lernen ___ am Abend. (переважно)", answer: "meistens" },
      { type: "tf", q: "З nie не треба ще одного nicht.", correct: true },
      { type: "tf", q: "selten = часто.", correct: false, explain: "selten = рідко." },
      { type: "match", prompt: "DE → UK:", pairs: [
        { left: "immer", right: "завжди" },
        { left: "meistens", right: "переважно" },
        { left: "oft", right: "часто" },
        { left: "manchmal", right: "іноді" },
        { left: "selten", right: "рідко" },
        { left: "nie", right: "ніколи" },
      ]},
      { type: "multi", q: "Які слова — Häufigkeitsadverbien?",
        options: ["immer","hier","oft","gut","manchmal","nie"], correct: [0,2,4,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich nie rauche nicht.",
        correct: ["Ich rauche nie."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я часто ходжу в спортзал, але іноді залишаюсь удома.",
        de: ["Ich gehe oft ins Fitnessstudio, aber manchmal bleibe ich zu Hause."] },
      { type: "writeFree", prompt: "3 речення про твої звички з immer / oft / manchmal / selten / nie.",
        sample: "Ich trinke immer Kaffee am Morgen. Manchmal gehe ich joggen. Ich esse nie Fleisch." },
    ],
  },

  // ===================================================================
  graduierungsadverbien: {
    lesson: {
      slug: "graduierungsadverbien",
      level: "A2",
      category: CAT,
      titleDe: "Gradadverbien",
      titleUk: "Прислівники інтенсивності (градації)",
      goal: "Підсилювати й послаблювати прикметники: sehr, ziemlich, ganz, zu, kaum, etwas, fast.",
      explanation: [
        "<b>Gradadverbien</b> змінюють <b>силу</b> прикметника або прислівника. Стоять <b>перед</b> ним.",
        "Шкала підсилення (від слабкого до сильного): <b>kaum → etwas → ein bisschen → ziemlich → ganz → sehr → wirklich → total / völlig</b>.",
        "<b>zu</b> = «занадто» (негативний відтінок): <i>«Das ist zu teuer.»</i>",
        "<b>ganz</b> має <b>два значення</b>: «досить» (<i>ganz gut</i> = непогано) і «зовсім» (<i>ganz neu</i> = зовсім новий) — залежить від наголосу й контексту.",
        "<b>fast</b> = «майже»: <i>fast fertig</i>.",
      ],
      table: {
        headers: ["Слово", "Сила", "Приклад"],
        rows: [
          ["kaum", "ледь", "Ich bin kaum müde."],
          ["etwas / ein bisschen", "трохи", "Ich bin etwas müde."],
          ["ziemlich", "досить", "Es ist ziemlich kalt."],
          ["ganz", "досить / зовсім", "Das ist ganz gut."],
          ["sehr", "дуже", "Ich bin sehr müde."],
          ["wirklich", "справді", "Das ist wirklich schön."],
          ["zu", "занадто (−)", "Das ist zu teuer."],
          ["total / völlig", "повністю", "Ich bin total kaputt."],
        ],
      },
      examples: [
        { de: "Das Wetter ist sehr schön.", uk: "Погода дуже гарна." },
        { de: "Es ist ziemlich kalt heute.", uk: "Сьогодні досить холодно." },
        { de: "Der Film war ganz interessant.", uk: "Фільм був досить цікавий." },
        { de: "Das ist zu teuer für mich.", uk: "Це для мене занадто дорого." },
        { de: "Ich bin etwas nervös.", uk: "Я трохи нервую." },
        { de: "Sie ist fast fertig.", uk: "Вона майже готова." },
        { de: "Wirklich? Das ist toll!", uk: "Справді? Це чудово!" },
        { de: "Ich bin total müde.", uk: "Я повністю виснажений(а)." },
      ],
      tip: "Не плутай <b>sehr</b> і <b>zu</b>: <i>«sehr gut»</i> — позитивно («дуже добре»), <i>«zu gut»</i> — занадто (з негативним відтінком).",
      mistakes: [
        { wrong: "Das ist sehr zu teuer.", right: "Das ist zu teuer." },
        { wrong: "Ich bin müde sehr.", right: "Ich bin sehr müde." },
        { wrong: "Ich liebe sehr dich.", right: "Ich liebe dich sehr." },
      ],
      exercises: {},
      prevSlug: "haeufigkeitsadverbien",
      nextSlug: "adverbien-position",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "знати шкалу від kaum до total",
        "розрізняти sehr / zu / ziemlich / ganz",
        "правильно ставити Gradadverb перед прикметником",
      ],
      ruleBox: {
        rule: "Gradadverb <b>перед</b> прикметником. <b>zu</b> = занадто (−). <b>sehr</b> = дуже (+).",
      },
      ukrainianTips: [
        "Українській «занадто» = німецьке <b>zu</b>, а не <i>sehr</i>.",
        "Українській «трохи» = <b>etwas / ein bisschen</b>.",
        "З дієсловом <b>sehr</b> стоїть у кінці: <i>«Ich liebe dich <b>sehr</b>»</i>, а з прикметником — попереду: <i>«Es ist <b>sehr</b> schön»</i>.",
      ],
      languageComparison: {
        commons: ["В обох мовах є шкала інтенсивності."],
        diffs: ["У німецькій <b>zu</b> = «занадто», а в українській «надто/занадто» — окреме слово."],
        traps: ["Помилка: «sehr zu teuer» — не комбінують."],
      },
      summary: [
        "Шкала: kaum → etwas → ziemlich → ganz → sehr → total.",
        "<b>zu</b> = занадто (з негативом).",
        "Gradadverb перед прикметником.",
        "З дієсловом <b>sehr</b> зазвичай у кінці.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das Wetter ist ___ schön. (дуже)", options: ["zu","sehr","kaum","etwas"], correct: 1 },
      { type: "mc", q: "Das ist ___ teuer für mich. (занадто)", options: ["sehr","ganz","zu","ziemlich"], correct: 2 },
      { type: "mc", q: "Es ist ___ kalt. (досить)", options: ["ziemlich","kaum","total","wirklich"], correct: 0 },
      { type: "mc", q: "Ich bin ___ fertig. (майже)", options: ["fast","sehr","zu","ganz"], correct: 0 },
      { type: "gap", q: "Ich bin ___ müde. (трохи)", answer: "etwas", hint: "або ein bisschen" },
      { type: "gap", q: "Das ist ___ schön. (справді)", answer: "wirklich" },
      { type: "gap", q: "Ich bin ___ kaputt. (повністю)", answer: "total" },
      { type: "gap", q: "Ich bin ___ müde. (ледь)", answer: "kaum" },
      { type: "tf", q: "sehr і zu — синоніми.", correct: false, explain: "sehr = дуже (+); zu = занадто (−)." },
      { type: "tf", q: "Gradadverb стоїть перед прикметником.", correct: true },
      { type: "match", prompt: "Сила → слово:", pairs: [
        { left: "100% (повністю)", right: "total" },
        { left: "80% (дуже)", right: "sehr" },
        { left: "60% (досить)", right: "ziemlich" },
        { left: "20% (трохи)", right: "etwas" },
        { left: "5% (ледь)", right: "kaum" },
      ]},
      { type: "multi", q: "Які підсилення позитивні?",
        options: ["sehr","zu","wirklich","ganz","kaum"], correct: [0,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich liebe sehr dich.",
        correct: ["Ich liebe dich sehr."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Це занадто дорого і не дуже гарно.",
        de: ["Das ist zu teuer und nicht sehr schön."] },
      { type: "writeFree", prompt: "3 речення з різними Gradadverbien.",
        sample: "Heute bin ich sehr müde. Das Buch ist ziemlich interessant. Der Kaffee ist zu heiß." },
    ],
  },

  // ===================================================================
  "adverbien-position": {
    lesson: {
      slug: "adverbien-position",
      level: "A2",
      category: CAT,
      titleDe: "Position der Adverbien im Satz (TeKaMoLo)",
      titleUk: "Порядок прислівників у реченні (Te-Ka-Mo-Lo)",
      goal: "Завжди правильно ставити прислівники в правильному порядку: час → причина → спосіб → місце.",
      explanation: [
        "У німецькому реченні з кількома прислівниками діє золоте правило <b>Te-Ka-Mo-Lo</b>:",
        "<b>Te</b>mporal (час) → <b>Ka</b>usal (причина) → <b>Mo</b>dal (спосіб) → <b>Lo</b>kal (місце).",
        "Приклад: <i>«Ich fahre <b>morgen</b> (Te) <b>wegen der Arbeit</b> (Ka) <b>schnell</b> (Mo) <b>nach Berlin</b> (Lo).»</i>",
        "Якщо один із елементів виходить на <b>1 місце</b> для акценту, решта зберігає той же порядок: <i>«Morgen fahre ich wegen der Arbeit schnell nach Berlin.»</i>",
        "У реченні з Perfekt Partizip залишається в кінці: <i>«Ich bin gestern mit dem Auto nach Berlin <b>gefahren</b>.»</i>",
      ],
      table: {
        headers: ["Te", "Ka", "Mo", "Lo"],
        rows: [
          ["час", "причина", "спосіб", "місце"],
          ["heute", "wegen…", "schnell", "nach Berlin"],
          ["um 8 Uhr", "aus Müdigkeit", "mit dem Bus", "in die Stadt"],
          ["letzte Woche", "wegen Krankheit", "leider", "zu Hause"],
        ],
      },
      examples: [
        { de: "Ich gehe heute schnell ins Büro.", uk: "Я йду сьогодні швидко в офіс." },
        { de: "Wir fahren morgen mit dem Auto nach Hause.", uk: "Ми їдемо завтра машиною додому." },
        { de: "Anna kam gestern wegen einer Erkältung nicht zur Arbeit.", uk: "Анна вчора через застуду не прийшла на роботу." },
        { de: "Er hat gestern fleißig zu Hause gelernt.", uk: "Він вчора старанно вчився вдома." },
        { de: "Morgen fahre ich mit dem Zug nach München.", uk: "Завтра я їду поїздом до Мюнхена." },
        { de: "Sie ist heute aus Müdigkeit früh ins Bett gegangen.", uk: "Вона сьогодні через втому рано лягла спати." },
        { de: "Wir treffen uns heute Abend im Café.", uk: "Зустрічаємось сьогодні ввечері в кафе." },
        { de: "Ich habe gestern lange am Computer gearbeitet.", uk: "Я вчора довго працював за компʼютером." },
      ],
      tip: "Мнемо: <b>Te-Ka-Mo-Lo</b> = «<i>Текамоло</i>». Завчи як слово — і ніколи не помилишся в порядку.",
      mistakes: [
        { wrong: "Ich gehe ins Büro heute schnell.", right: "Ich gehe heute schnell ins Büro." },
        { wrong: "Wir fahren nach Hause morgen mit dem Auto.", right: "Wir fahren morgen mit dem Auto nach Hause." },
        { wrong: "Ich habe lange gestern gearbeitet.", right: "Ich habe gestern lange gearbeitet." },
      ],
      exercises: {},
      prevSlug: "graduierungsadverbien",
      nextSlug: "pronominaladverbien",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "запам'ятати ланцюжок Te-Ka-Mo-Lo",
        "розставляти прислівники в правильному порядку",
        "переносити будь-який елемент на 1 місце без ламання порядку",
      ],
      ruleBox: {
        rule: "<b>Te</b>mporal → <b>Ka</b>usal → <b>Mo</b>dal → <b>Lo</b>kal.",
      },
      ukrainianTips: [
        "В українській порядок вільний — у німецькій <b>суворо</b> TeKaMoLo.",
        "Якщо є лише два елементи (час + місце), все одно: час іде <b>перед</b> місцем.",
        "Partizip II / Infinitiv завжди в кінці — після всього TeKaMoLo.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають час, причину, спосіб, місце."],
        diffs: ["Німецька жорстко фіксує порядок; українська — ні."],
        traps: ["Помилка: ставити місце перед часом."],
      },
      summary: [
        "Te → Ka → Mo → Lo.",
        "Будь-який елемент може бути на 1 місці.",
        "Partizip / Infinitiv — у самому кінці.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Правильний порядок:",
        options: ["Ich gehe ins Büro heute schnell.","Ich gehe heute schnell ins Büro.","Ich gehe schnell heute ins Büro.","Heute ich gehe schnell ins Büro."], correct: 1 },
      { type: "mc", q: "Правильний порядок:",
        options: ["Wir fahren nach Hause morgen mit dem Auto.","Wir fahren morgen nach Hause mit dem Auto.","Wir fahren morgen mit dem Auto nach Hause.","Morgen wir fahren nach Hause."], correct: 2 },
      { type: "mc", q: "Що означає TeKaMoLo?",
        options: ["Time-Kause-Mode-Location","Temporal-Kausal-Modal-Lokal","Tag-Karte-Monat-Lohn","Test-Kind-Modus-Lokal"], correct: 1 },
      { type: "mc", q: "Який порядок?",
        options: ["час → місце → спосіб → причина","час → причина → спосіб → місце","місце → час → спосіб → причина","спосіб → час → причина → місце"], correct: 1 },
      { type: "gap", q: "Розстав: «Ich fahre [nach Berlin] [morgen] [mit dem Zug]» →",
        answer: "Ich fahre morgen mit dem Zug nach Berlin." },
      { type: "gap", q: "Розстав: «Wir treffen uns [im Café] [heute Abend]» →",
        answer: "Wir treffen uns heute Abend im Café." },
      { type: "tf", q: "Місце завжди в кінці.", correct: true },
      { type: "tf", q: "Час може бути на 1 місці.", correct: true },
      { type: "tf", q: "Спосіб іде перед часом.", correct: false, explain: "Te перед Mo." },
      { type: "order", prompt: "Склади:",
        words: ["nach Berlin","morgen","ich","mit dem Auto","fahre"],
        correct: ["ich","fahre","morgen","mit dem Auto","nach Berlin"] },
      { type: "order", prompt: "Склади:",
        words: ["im Büro","fleißig","gestern","hat","gearbeitet","er"],
        correct: ["er","hat","gestern","fleißig","im Büro","gearbeitet"] },
      { type: "match", prompt: "Слово → категорія:", pairs: [
        { left: "morgen", right: "Te" },
        { left: "wegen der Arbeit", right: "Ka" },
        { left: "schnell", right: "Mo" },
        { left: "nach Berlin", right: "Lo" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe lange gestern gearbeitet.",
        correct: ["Ich habe gestern lange gearbeitet."] },
      { type: "translate", prompt: "Переклади (зверни увагу на TeKaMoLo):",
        uk: "Завтра я їду машиною до Берліна.",
        de: ["Morgen fahre ich mit dem Auto nach Berlin.","Ich fahre morgen mit dem Auto nach Berlin."] },
      { type: "writeFree", prompt: "3 речення з усіма 4 елементами TeKaMoLo.",
        sample: "Heute gehe ich wegen des Wetters langsam ins Büro. Morgen fahre ich aus Spaß mit dem Fahrrad in die Stadt. Gestern bin ich wegen Müdigkeit früh nach Hause gegangen." },
    ],
  },

  // ===================================================================
  pronominaladverbien: {
    lesson: {
      slug: "pronominaladverbien",
      level: "A2",
      category: CAT,
      titleDe: "Pronominaladverbien",
      titleUk: "Займенникові прислівники (da- / wo-)",
      goal: "Замінювати «прийменник + він/вона/воно» компактними формами da(r)- та wo(r)-.",
      explanation: [
        "Коли в реченні треба сказати <b>«про це / з цим / на цьому»</b>, у німецькій <b>НЕ</b> кажуть <i>«über es / mit es / auf es»</i>. Замість цього використовують <b>da- + прийменник</b>: <b>darüber, damit, darauf, davon, dafür, dazu, dagegen</b>.",
        "Якщо прийменник починається з голосної, додається <b>-r-</b>: da + an = <b>daran</b>; da + auf = <b>darauf</b>; da + über = <b>darüber</b>.",
        "У питаннях та підрядних діє та сама схема, але з <b>wo-</b>: <b>worüber, womit, worauf, wovon, wofür, wozu, wogegen</b>. Це <b>не</b> для людей: для них — <i>über wen?</i>, <i>mit wem?</i>",
        "Pronominaladverbien не вживаються для людей: <i>«Ich denke <b>an meinen Vater</b>»</i> → <i>«Ich denke <b>an ihn</b>»</i> (не <i>daran</i>). Для речей: <i>«Ich denke an die Arbeit»</i> → <i>«Ich denke <b>daran</b>»</i>.",
      ],
      table: {
        headers: ["Präposition", "da-форма", "wo-форма (питання)"],
        rows: [
          ["über", "darüber", "worüber"],
          ["mit", "damit", "womit"],
          ["auf", "darauf", "worauf"],
          ["von", "davon", "wovon"],
          ["für", "dafür", "wofür"],
          ["an", "daran", "woran"],
          ["zu", "dazu", "wozu"],
          ["gegen", "dagegen", "wogegen"],
        ],
      },
      examples: [
        { de: "Wir sprechen über das Wetter. → Wir sprechen darüber.", uk: "Ми говоримо про погоду. → Ми говоримо про це." },
        { de: "Ich denke an die Prüfung. → Ich denke daran.", uk: "Я думаю про іспит. → Я думаю про це." },
        { de: "Sie wartet auf den Bus. → Sie wartet darauf.", uk: "Вона чекає на автобус. → Вона на нього чекає." },
        { de: "Ich freue mich auf den Urlaub. → Ich freue mich darauf.", uk: "Я тішусь відпустці. → Я тішусь цьому." },
        { de: "Womit kann ich helfen?", uk: "Чим я можу допомогти?" },
        { de: "Worüber sprecht ihr?", uk: "Про що ви говорите?" },
        { de: "Wofür ist das gut?", uk: "Для чого це?" },
        { de: "Ich bin dagegen.", uk: "Я проти цього." },
      ],
      tip: "Для <b>людей</b> завжди <b>Präposition + займенник</b> (über ihn, mit ihr, auf sie). Для <b>речей / абстракцій</b> — <b>da(r)-</b>.",
      mistakes: [
        { wrong: "Ich denke an es.", right: "Ich denke daran." },
        { wrong: "Ich freue mich auf es.", right: "Ich freue mich darauf." },
        { wrong: "Daran meinen Vater.", right: "An meinen Vater." },
      ],
      exercises: {},
      prevSlug: "adverbien-position",
    },
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "будувати da-/wo-форми з будь-якого прийменника",
        "пам'ятати про -r- перед голосною",
        "не вживати da-форми для людей",
      ],
      ruleBox: {
        rule: "Речі/абстракції → <b>da(r)-</b> + Präp. Питання → <b>wo(r)-</b>. Перед голосною → <b>-r-</b>. Люди → Präp + займенник.",
      },
      ukrainianTips: [
        "Українській «про це / на це / з цим» = німецьке <b>darüber / darauf / damit</b>.",
        "Українській «про що / на що / з чим?» = <b>worüber / worauf / womit</b>.",
        "Для людей не вживай darüber! <i>«Я думаю про неї»</i> = <i>«Ich denke <b>an sie</b>»</i>.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають компактні форми «про це / з цим»."],
        diffs: ["У німецькій це окремі сполуки, у яких ще додається -r- перед голосною."],
        traps: ["Помилка: «ich freue mich auf es» (треба <i>darauf</i>)."],
      },
      summary: [
        "<b>da- + Präp.</b> для речей.",
        "<b>wo- + Präp.</b> для питань.",
        "Голосна → <b>-r-</b>: darüber, woran.",
        "Для людей — Präp + займенник (über ihn).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Wir sprechen über das Wetter. → Wir sprechen ___.", options: ["über es","damit","darüber","worüber"], correct: 2 },
      { type: "mc", q: "Ich warte auf den Bus. → Ich warte ___.", options: ["auf ihn","darauf","worauf","daran"], correct: 1 },
      { type: "mc", q: "Ich denke an meine Mutter. → Ich denke ___.", options: ["daran","an sie","worauf","damit"], correct: 1, explain: "Людина → an sie, не daran." },
      { type: "mc", q: "___ kann ich helfen? (Чим)", options: ["Womit","Worauf","Wofür","Wovon"], correct: 0 },
      { type: "gap", q: "Sie freut sich auf den Urlaub. → Sie freut sich ___.", answer: "darauf" },
      { type: "gap", q: "Wir reden von dem Problem. → Wir reden ___.", answer: "davon" },
      { type: "gap", q: "___ sprecht ihr? (Про що)", answer: "Worüber" },
      { type: "gap", q: "Ich bin gegen den Plan. → Ich bin ___.", answer: "dagegen" },
      { type: "tf", q: "Перед голосною додається -r-: daran, darauf.", correct: true },
      { type: "tf", q: "Для людей вживаємо da-форму.", correct: false, explain: "Тільки для речей." },
      { type: "match", prompt: "Präp → da-/wo-форма:", pairs: [
        { left: "über", right: "darüber / worüber" },
        { left: "mit", right: "damit / womit" },
        { left: "auf", right: "darauf / worauf" },
        { left: "von", right: "davon / wovon" },
        { left: "für", right: "dafür / wofür" },
      ]},
      { type: "multi", q: "Які форми правильні?",
        options: ["darüber","überdas","damit","mitda","darauf","aufda"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich freue mich auf es.",
        correct: ["Ich freue mich darauf."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Про що ви говорите? — Про погоду.",
        de: ["Worüber sprecht ihr? — Über das Wetter.","Worüber redet ihr? — Über das Wetter."] },
      { type: "writeFree", prompt: "3 пари речень: повне з прийменником → стисле з da-формою.",
        sample: "Ich denke an die Arbeit. → Ich denke daran. Wir warten auf den Bus. → Wir warten darauf. Sie spricht über das Problem. → Sie spricht darüber." },
    ],
  },
};
