// A2 · Dativ — 8 повних уроків.
import type { A2Map } from "./_helpers";

const CAT = "Відмінки · Dativ";

export const dativA2: A2Map = {
  // ===================================================================
  "was-ist-dativ": {
    lesson: {
      slug: "was-ist-dativ",
      level: "A2",
      category: CAT,
      titleDe: "Was ist der Dativ?",
      titleUk: "Що таке Dativ (давальний)?",
      goal: "Зрозуміти, що таке Dativ, на яке питання відповідає й коли вживається.",
      explanation: [
        "<b>Dativ</b> — це давальний відмінок. Відповідає на питання <b>Wem?</b> (Кому?) та <b>Wo?</b> (Де?).",
        "Dativ показує <b>адресата дії</b> (кому щось дають, говорять, допомагають) або <b>місце</b> (де хтось/щось перебуває).",
        "Часто є <b>непрямим</b> додатком, тоді як прямий додаток стоїть у Akkusativ:<br><i>Ich gebe <u>dem Kind</u> (Dat.) <u>das Buch</u> (Akk.).</i>",
        "Dativ обов'язковий після певних дієслів, прийменників, прикметників.",
      ],
      table: {
        headers: ["Питання", "Приклад", "Переклад"],
        rows: [
          ["Wem?", "Ich helfe dem Vater.", "Я допомагаю батькові."],
          ["Wem?", "Das Buch gehört mir.", "Книга належить мені."],
          ["Wo?", "Ich bin im Park.", "Я в парку."],
          ["Wem?", "Wir danken den Lehrern.", "Ми дякуємо вчителям."],
        ],
      },
      examples: [
        { de: "Ich helfe meiner Mutter.", uk: "Я допомагаю своїй матері." },
        { de: "Wem gehört dieses Auto?", uk: "Кому належить ця машина?" },
        { de: "Das Geschenk gefällt dem Kind.", uk: "Подарунок подобається дитині." },
        { de: "Er antwortet dem Lehrer.", uk: "Він відповідає вчителю." },
        { de: "Wir wohnen bei den Großeltern.", uk: "Ми живемо в дідуся з бабусею." },
        { de: "Das Kleid passt der Frau gut.", uk: "Сукня добре пасує жінці." },
        { de: "Sie schenkt ihrem Bruder ein Buch.", uk: "Вона дарує своєму братові книгу." },
        { de: "Der Schlüssel liegt auf dem Tisch.", uk: "Ключ лежить на столі." },
      ],
      tip: "Якщо питаєш «<b>кому?</b>» — це Dativ. Якщо «<b>кого/що?</b>» — Akkusativ.",
      mistakes: [
        { wrong: "Ich helfe den Vater.", right: "Ich helfe dem Vater." },
        { wrong: "Das Buch gehört mich.", right: "Das Buch gehört mir." },
        { wrong: "Ich danke der Lehrer.", right: "Ich danke dem Lehrer." },
      ],
      exercises: {},
      nextSlug: "artikel-im-dativ",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "розрізняти Dativ і Akkusativ за питанням",
        "знати, що Dativ = «кому?»",
        "впізнавати Dativ у простих реченнях",
      ],
      ruleBox: {
        rule: "<b>Dativ</b> відповідає на питання <b>Wem?</b> (кому?). Це непрямий додаток або місце (Wo?).",
      },
      ukrainianTips: [
        "Українське «кому?» = німецьке <b>Wem?</b> — це найпростіша підказка.",
        "Українське «де?» теж може бути Dativ після прийменника (<i>im Park, auf dem Tisch</i>).",
        "Деякі дієслова в українській керують Acc., а в німецькій — Dat. (<i>helfen + Dat.</i>).",
      ],
      languageComparison: {
        commons: ["Обидві мови мають давальний відмінок і питання «кому?»."],
        diffs: ["У німецькій Dativ має чіткі форми артикля (dem/der/dem/den+n)."],
        traps: ["<i>helfen, danken, gehören</i> — Dativ, хоча в українській часто «допомагати кого»."],
      },
      summary: [
        "Dativ — відмінок «кому/чому».",
        "Питання: Wem? Wo?",
        "Часто непрямий додаток.",
        "Багато дієслів і всі прийменники з Dat. вимагають Dativ.",
      ],
    },
    exercises15: [
      { type: "mc", q: "На яке питання відповідає Dativ?", options: ["Wen?","Was?","Wem?","Wessen?"], correct: 2 },
      { type: "mc", q: "Ich helfe ___ Vater.", options: ["den","dem","der","das"], correct: 1 },
      { type: "mc", q: "Das Buch gehört ___.", options: ["ich","mich","mir","mein"], correct: 2 },
      { type: "mc", q: "Wir danken ___ Lehrer.", options: ["der","den","dem","das"], correct: 2 },
      { type: "mc", q: "Який рядок — Dativ?", options: ["der Mann","den Mann","dem Mann","des Mannes"], correct: 2 },
      { type: "gap", q: "Ich antworte ___ Lehrerin. (die)", answer: "der" },
      { type: "gap", q: "Das Geschenk gefällt ___ Kind. (das)", answer: "dem" },
      { type: "gap", q: "Wir helfen ___ Eltern. (die, Pl.)", answer: "den" },
      { type: "gap", q: "Das Auto gehört ___ Bruder. (der)", answer: "dem" },
      { type: "tf", q: "«Wem?» — це питання Dativ.", correct: true },
      { type: "tf", q: "Dativ ніколи не позначає місце.", correct: false },
      { type: "match", prompt: "Дієслово → відмінок:", pairs: [
        { left: "helfen", right: "Dativ" },
        { left: "sehen", right: "Akkusativ" },
        { left: "gehören", right: "Dativ" },
        { left: "kaufen", right: "Akkusativ" },
      ]},
      { type: "multi", q: "Які речення стоять у Dativ?", options: [
        "Ich helfe dem Mann.",
        "Ich sehe den Mann.",
        "Das gehört mir.",
        "Wir danken dem Lehrer.",
      ], correct: [0,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich helfe den Vater.", correct: ["Ich helfe dem Vater."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я допомагаю мамі.",
        de: ["Ich helfe der Mutter.","Ich helfe meiner Mutter."] },
    ],
  },

  // ===================================================================
  "artikel-im-dativ": {
    lesson: {
      slug: "artikel-im-dativ",
      level: "A2",
      category: CAT,
      titleDe: "Artikel im Dativ",
      titleUk: "Артиклі в Dativ (dem / der / dem / den + n)",
      goal: "Запам'ятати форми означеного і неозначеного артикля в Dativ.",
      explanation: [
        "У Dativ артиклі змінюються так:<br><b>der → dem, die → der, das → dem, die (Pl.) → den</b>.",
        "У <b>множині</b> до іменника додається <b>-n</b> (якщо його там ще немає): <i>den Kindern, den Männern, den Frauen</i>.",
        "Неозначений артикль: <b>ein → einem, eine → einer, ein → einem</b>. Заперечний: <b>kein → keinem/keiner/keinem/keinen</b>.",
        "Присвійні (mein, dein…) і <i>kein</i> мають ті самі закінчення: <b>-em, -er, -em, -en</b>.",
      ],
      table: {
        headers: ["Рід", "Nom.", "Dat. (der)", "Dat. (ein)", "Dat. (mein)"],
        rows: [
          ["m", "der Mann", "dem Mann", "einem Mann", "meinem Mann"],
          ["f", "die Frau", "der Frau", "einer Frau", "meiner Frau"],
          ["n", "das Kind", "dem Kind", "einem Kind", "meinem Kind"],
          ["Pl.", "die Kinder", "den Kindern", "— (keinen) Kindern", "meinen Kindern"],
        ],
      },
      examples: [
        { de: "Ich gebe dem Mann das Buch.", uk: "Я даю чоловіку книгу." },
        { de: "Sie hilft der Frau.", uk: "Вона допомагає жінці." },
        { de: "Wir spielen mit dem Kind.", uk: "Ми граємо з дитиною." },
        { de: "Er erzählt den Kindern eine Geschichte.", uk: "Він розповідає дітям історію." },
        { de: "Das Buch gehört einem Freund.", uk: "Книга належить (одному) другові." },
        { de: "Ich danke meiner Schwester.", uk: "Я дякую своїй сестрі." },
        { de: "Sie wohnt bei ihren Eltern.", uk: "Вона живе у своїх батьків." },
        { de: "Das passt keinem Mitarbeiter.", uk: "Це не підходить жодному працівнику." },
      ],
      tip: "Запам'ятай мнемоніку: <b>m/n → -em, f → -er, Pl. → -en (+n)</b>.",
      mistakes: [
        { wrong: "Ich gebe der Mann das Buch.", right: "Ich gebe dem Mann das Buch." },
        { wrong: "Er erzählt den Kinder eine Geschichte.", right: "Er erzählt den Kindern eine Geschichte." },
        { wrong: "Sie hilft die Frau.", right: "Sie hilft der Frau." },
      ],
      exercises: {},
      prevSlug: "was-ist-dativ",
      nextSlug: "personalpron-dativ",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "автоматично визначати dem/der/dem/den",
        "додавати -n у Pl.",
        "застосовувати einem/einer та meinem/meiner",
      ],
      ruleBox: {
        rule: "<b>Артиклі у Dat.:</b> m → dem, f → der, n → dem, Pl. → den + іменник на -n.",
      },
      ukrainianTips: [
        "У множині <b>обов'язково</b> -n: den Kindern, den Männern, den Frauen.",
        "Слова на -s, -n уже в Pl. (Autos, Frauen) — -n не додаємо: <i>den Autos, den Frauen</i>.",
        "kein/mein/dein/sein/ihr/unser/euer/Ihr — однакові закінчення з ein у Dat.",
      ],
      languageComparison: {
        commons: ["І в українській артикль-займенник міняється за відмінком (мій → моєму)."],
        diffs: ["У німецькій артикль обов'язковий і несе всю інформацію про відмінок."],
        traps: ["Pl. -n: <i>mit den Freunden</i>, не <s>mit den Freunde</s>."],
      },
      summary: [
        "m/n → dem, f → der, Pl. → den + -n.",
        "ein → einem/einer/einem.",
        "mein/kein/dein — як ein.",
        "У Pl. завжди додаємо -n до іменника.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Dativ від «der Mann» — це…", options: ["den Mann","des Mannes","dem Mann","der Mann"], correct: 2 },
      { type: "mc", q: "Dativ від «die Frau» — це…", options: ["die Frau","der Frau","den Frau","dem Frau"], correct: 1 },
      { type: "mc", q: "Dativ від «das Kind» — це…", options: ["dem Kind","den Kind","der Kind","das Kind"], correct: 0 },
      { type: "mc", q: "Dativ Pl. від «die Kinder» — це…", options: ["die Kinder","den Kinder","den Kindern","der Kinder"], correct: 2 },
      { type: "mc", q: "Ich helfe ___ Freund. (ein)", options: ["einen","einem","einer","ein"], correct: 1 },
      { type: "gap", q: "Ich gebe ___ Mann das Buch. (der)", answer: "dem" },
      { type: "gap", q: "Sie hilft ___ Frau. (die)", answer: "der" },
      { type: "gap", q: "Er spielt mit ___ Kind. (das)", answer: "dem" },
      { type: "gap", q: "Wir helfen ___ Kindern. (die, Pl.)", answer: "den" },
      { type: "gap", q: "Das gehört ___ Schwester. (meine)", answer: "meiner" },
      { type: "tf", q: "У множині в Dat. до іменника додається -n.", correct: true },
      { type: "tf", q: "Dativ від «die Frau» — «die Frau».", correct: false },
      { type: "match", prompt: "Nom. → Dat.:", pairs: [
        { left: "der Mann", right: "dem Mann" },
        { left: "die Frau", right: "der Frau" },
        { left: "das Kind", right: "dem Kind" },
        { left: "die Kinder", right: "den Kindern" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Er erzählt den Kinder eine Geschichte.", correct: ["Er erzählt den Kindern eine Geschichte."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я допомагаю одному другові.",
        de: ["Ich helfe einem Freund."] },
    ],
  },

  // ===================================================================
  "personalpron-dativ": {
    lesson: {
      slug: "personalpron-dativ",
      level: "A2",
      category: CAT,
      titleDe: "Personalpronomen im Dativ",
      titleUk: "Особові займенники в Dativ (mir, dir, ihm…)",
      goal: "Запам'ятати всі форми особових займенників у Dativ і вільно їх вживати.",
      explanation: [
        "Особові займенники в Dativ: <b>mir, dir, ihm, ihr, ihm, uns, euch, ihnen / Ihnen</b>.",
        "Вживаються після дієслів з Dat. (<i>helfen, danken, gehören, gefallen…</i>) і після прийменників з Dat.",
        "<b>Порядок:</b> у реченні з двома додатками <b>займенник іде перед іменником</b>:<br><i>Ich gebe <u>ihm</u> das Buch.</i> / <i>Ich gebe <u>es</u> dem Mann.</i>",
        "Ввічливе <b>Ihnen</b> завжди пишеться з великої літери.",
      ],
      table: {
        headers: ["Nom.", "Akk.", "Dat."],
        rows: [
          ["ich", "mich", "mir"],
          ["du", "dich", "dir"],
          ["er", "ihn", "ihm"],
          ["sie (вона)", "sie", "ihr"],
          ["es", "es", "ihm"],
          ["wir", "uns", "uns"],
          ["ihr", "euch", "euch"],
          ["sie/Sie", "sie/Sie", "ihnen / Ihnen"],
        ],
      },
      examples: [
        { de: "Kannst du mir helfen?", uk: "Можеш мені допомогти?" },
        { de: "Ich danke dir.", uk: "Я тобі дякую." },
        { de: "Das Buch gehört ihm.", uk: "Книга належить йому." },
        { de: "Wie geht es Ihnen?", uk: "Як у вас справи?" },
        { de: "Das gefällt uns sehr.", uk: "Нам це дуже подобається." },
        { de: "Ich schenke euch Blumen.", uk: "Я дарую вам квіти." },
        { de: "Sag ihr die Wahrheit!", uk: "Скажи їй правду!" },
        { de: "Ich glaube ihnen nicht.", uk: "Я їм не вірю." },
      ],
      tip: "Фраза «Wie geht es <b>dir/Ihnen</b>?» — класична Dativ-конструкція. Запам'ятай разом.",
      mistakes: [
        { wrong: "Kannst du mich helfen?", right: "Kannst du mir helfen?" },
        { wrong: "Ich danke dich.", right: "Ich danke dir." },
        { wrong: "Das gehört ihn.", right: "Das gehört ihm." },
      ],
      exercises: {},
      prevSlug: "artikel-im-dativ",
      nextSlug: "possessiv-dativ",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "знати напам'ять mir/dir/ihm/ihr/uns/euch/ihnen",
        "відрізняти Akk. (mich) від Dat. (mir)",
        "правильно вживати Ihnen",
      ],
      ruleBox: {
        rule: "<b>Dat. займенники:</b> mir · dir · ihm · ihr · ihm · uns · euch · ihnen / Ihnen.",
      },
      ukrainianTips: [
        "<b>mir/dir</b> = мені/тобі. <b>ihm/ihr</b> = йому/їй.",
        "Після <i>helfen, danken, gehören, gefallen, antworten</i> — завжди Dativ.",
        "<i>Wie geht es dir?</i> — це фактично «Як йдеться тобі?».",
      ],
      languageComparison: {
        commons: ["Українські займенники теж мають форму Dat. (мені, тобі, йому)."],
        diffs: ["У німецькій <i>er</i> → <i>ihm</i> (а не <i>ihn</i>, яке є Akk.)."],
        traps: ["<i>helfen + Dat.</i>: <s>helfen mich</s> → <b>helfen mir</b>."],
      },
      summary: [
        "Dat: mir, dir, ihm, ihr, ihm, uns, euch, ihnen/Ihnen.",
        "Ihnen — ввічливе, з великої.",
        "Займенник у Dat. іде перед іменником-Akk.",
        "Wie geht es dir? — фразеологізм з Dat.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Dat. від «ich» — це…", options: ["mich","mir","mein","meiner"], correct: 1 },
      { type: "mc", q: "Dat. від «du» — це…", options: ["dich","dir","dein","du"], correct: 1 },
      { type: "mc", q: "Dat. від «er» — це…", options: ["ihn","ihm","sein","er"], correct: 1 },
      { type: "mc", q: "Dat. від «sie» (вона) — це…", options: ["sie","ihr","ihn","ihm"], correct: 1 },
      { type: "mc", q: "Dat. від «sie» (вони) — це…", options: ["sie","ihnen","ihren","ihr"], correct: 1 },
      { type: "gap", q: "Kannst du ___ helfen? (ich)", answer: "mir" },
      { type: "gap", q: "Wie geht es ___? (du)", answer: "dir" },
      { type: "gap", q: "Das Buch gehört ___. (er)", answer: "ihm" },
      { type: "gap", q: "Ich schenke ___ Blumen. (ihr — ви)", answer: "euch" },
      { type: "gap", q: "Wie geht es ___? (Sie ввічл.)", answer: "Ihnen" },
      { type: "tf", q: "«mich» — це Dat.", correct: false },
      { type: "tf", q: "«Ihnen» завжди пишеться з великої літери.", correct: true },
      { type: "match", prompt: "Nom. → Dat.:", pairs: [
        { left: "ich", right: "mir" },
        { left: "du", right: "dir" },
        { left: "er", right: "ihm" },
        { left: "sie (Pl.)", right: "ihnen" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich danke dich.", correct: ["Ich danke dir."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Можеш мені допомогти?",
        de: ["Kannst du mir helfen?","Könntest du mir helfen?"] },
    ],
  },

  // ===================================================================
  "possessiv-dativ": {
    lesson: {
      slug: "possessiv-dativ",
      level: "A2",
      category: CAT,
      titleDe: "Possessivpronomen im Dativ",
      titleUk: "Присвійні займенники в Dativ (meinem, meiner, meinen…)",
      goal: "Вживати mein/dein/sein/ihr/unser/euer/Ihr у Dativ із правильними закінченнями.",
      explanation: [
        "Присвійні займенники мають <b>ті самі закінчення</b>, що й <i>ein/kein</i>.",
        "У Dativ: <b>m → -em, f → -er, n → -em, Pl. → -en</b> (+ -n до іменника в Pl.).",
        "Основи: <b>mein, dein, sein, ihr, sein, unser, euer, ihr / Ihr</b>.",
        "<i>euer</i> у формі з закінченням втрачає -e-: <b>eurem, eurer, eurem, euren</b>.",
      ],
      table: {
        headers: ["Особа", "m (Dat.)", "f (Dat.)", "n (Dat.)", "Pl. (Dat.)"],
        rows: [
          ["ich → mein", "meinem Mann", "meiner Frau", "meinem Kind", "meinen Kindern"],
          ["du → dein", "deinem Mann", "deiner Frau", "deinem Kind", "deinen Kindern"],
          ["er → sein", "seinem", "seiner", "seinem", "seinen"],
          ["sie → ihr", "ihrem", "ihrer", "ihrem", "ihren"],
          ["wir → unser", "unserem", "unserer", "unserem", "unseren"],
          ["ihr → euer", "eurem", "eurer", "eurem", "euren"],
          ["sie/Sie → ihr/Ihr", "ihrem/Ihrem", "ihrer/Ihrer", "ihrem/Ihrem", "ihren/Ihren"],
        ],
      },
      examples: [
        { de: "Ich helfe meinem Bruder.", uk: "Я допомагаю своєму брату." },
        { de: "Sie spielt mit ihrer Tochter.", uk: "Вона грає зі своєю донькою." },
        { de: "Wir danken unseren Eltern.", uk: "Ми дякуємо своїм батькам." },
        { de: "Er wohnt bei seinem Onkel.", uk: "Він живе у свого дядька." },
        { de: "Sprich mit deiner Lehrerin!", uk: "Поговори зі своєю вчителькою!" },
        { de: "Das gehört eurem Freund.", uk: "Це належить вашому другові." },
        { de: "Ich schreibe Ihrem Chef eine E-Mail.", uk: "Я пишу вашому шефу e-mail." },
        { de: "Sie kommt mit ihren Kindern.", uk: "Вона приходить зі своїми дітьми." },
      ],
      tip: "<b>euer</b> у відмінкових формах втрачає -e-: <i>euer Vater → mit eurem Vater</i>.",
      mistakes: [
        { wrong: "Ich helfe mein Bruder.", right: "Ich helfe meinem Bruder." },
        { wrong: "mit eueren Eltern", right: "mit euren Eltern" },
        { wrong: "Sie kommt mit ihre Kinder.", right: "Sie kommt mit ihren Kindern." },
      ],
      exercises: {},
      prevSlug: "personalpron-dativ",
      nextSlug: "verben-mit-dativ",
    },
    extras: {
      duration: 13,
      premium: false,
      learningGoals: [
        "будувати meinem/meiner/meinem/meinen",
        "запам'ятати випадання -e- у euer",
        "додавати -n у Pl.",
      ],
      ruleBox: {
        rule: "<b>Possessiv у Dat.:</b> m → -em, f → -er, n → -em, Pl. → -en (+ -n на іменнику).",
      },
      ukrainianTips: [
        "Окрема форма — <i>Ihr/Ihnen</i> (ввічливе) — з великої.",
        "<i>ihr</i> = «її» або «їхній» — контекст вирішує.",
        "<i>unser/euer</i> довші, але закінчення такі самі.",
      ],
      languageComparison: {
        commons: ["Українські «мій/моя/моє» теж змінюються за відмінками."],
        diffs: ["У німецькій форма залежить від <i>роду іменника</i>, а не від мовця."],
        traps: ["<i>euer</i> → у формах <i>eurem/eurer/euren</i>, не <s>eueren</s>."],
      },
      summary: [
        "Закінчення = як у ein/kein.",
        "m/n → -em, f → -er, Pl. → -en.",
        "Pl.: іменник теж на -n.",
        "euer → eur- у відмінкових формах.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich helfe ___ Bruder. (mein)", options: ["meinen","meinem","meiner","mein"], correct: 1 },
      { type: "mc", q: "Sie spielt mit ___ Tochter. (ihr)", options: ["ihrem","ihrer","ihren","ihr"], correct: 1 },
      { type: "mc", q: "Wir danken ___ Eltern. (unser)", options: ["unseren","unserem","unserer","unsere"], correct: 0 },
      { type: "mc", q: "Er wohnt bei ___ Onkel. (sein)", options: ["seinen","seinem","seiner","sein"], correct: 1 },
      { type: "mc", q: "Sprich mit ___ Lehrerin! (dein)", options: ["deiner","deinem","deinen","dein"], correct: 0 },
      { type: "gap", q: "Das gehört ___ Freund. (euer)", answer: "eurem" },
      { type: "gap", q: "Ich schreibe ___ Chef eine E-Mail. (Ihr ввічл.)", answer: "Ihrem" },
      { type: "gap", q: "Sie kommt mit ___ Kindern. (ihr)", answer: "ihren" },
      { type: "gap", q: "Ich gebe ___ Mutter Blumen. (mein)", answer: "meiner" },
      { type: "gap", q: "Wir helfen ___ Nachbarn. (unser, Pl.)", answer: "unseren" },
      { type: "tf", q: "«euer» у відмінкових формах втрачає -e-.", correct: true },
      { type: "tf", q: "У Pl. -n до іменника не додається.", correct: false },
      { type: "match", prompt: "Особа → Dat. (m):", pairs: [
        { left: "ich", right: "meinem" },
        { left: "du", right: "deinem" },
        { left: "wir", right: "unserem" },
        { left: "ihr", right: "eurem" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Sie kommt mit ihre Kinder.", correct: ["Sie kommt mit ihren Kindern."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я допомагаю своєму братові.",
        de: ["Ich helfe meinem Bruder."] },
    ],
  },

  // ===================================================================
  "verben-mit-dativ-a2": {
    lesson: {
      slug: "verben-mit-dativ-a2",
      level: "A2",
      category: CAT,
      titleDe: "Verben mit Dativ",
      titleUk: "Дієслова з Dativ (helfen, danken, gehören…)",
      goal: "Запам'ятати ТОП-дієслова, які вимагають Dativ, і вживати їх правильно.",
      explanation: [
        "Деякі дієслова <b>завжди</b> вимагають Dativ — без прийменника.",
        "ТОП-список: <b>helfen, danken, gehören, gefallen, antworten, glauben, passen, schmecken, gratulieren, fehlen, folgen, begegnen, raten</b>.",
        "Логіка: ці дієслова часто описують <b>звернення до когось</b> або <b>стан, що стосується когось</b>.",
        "Будова: <b>Subjekt (Nom.) + Verb + Person (Dat.)</b>.",
      ],
      table: {
        headers: ["Дієслово", "Приклад", "Переклад"],
        rows: [
          ["helfen", "Ich helfe dir.", "Я допомагаю тобі."],
          ["danken", "Wir danken dem Lehrer.", "Ми дякуємо вчителю."],
          ["gehören", "Das Auto gehört mir.", "Машина належить мені."],
          ["gefallen", "Das Bild gefällt mir.", "Картина мені подобається."],
          ["antworten", "Er antwortet der Mutter.", "Він відповідає мамі."],
          ["passen", "Die Hose passt dir gut.", "Штани тобі добре пасують."],
          ["schmecken", "Der Kuchen schmeckt den Kindern.", "Торт подобається дітям (на смак)."],
          ["gratulieren", "Ich gratuliere dir!", "Я тебе вітаю!"],
        ],
      },
      examples: [
        { de: "Hilf mir bitte!", uk: "Допоможи мені, будь ласка!" },
        { de: "Ich danke Ihnen herzlich.", uk: "Щиро вам дякую." },
        { de: "Das Haus gehört meinen Eltern.", uk: "Будинок належить моїм батькам." },
        { de: "Wie gefällt dir der Film?", uk: "Як тобі фільм?" },
        { de: "Sie antwortet ihrem Chef.", uk: "Вона відповідає своєму шефу." },
        { de: "Ich glaube dir nicht.", uk: "Я тобі не вірю." },
        { de: "Die Schuhe passen mir nicht.", uk: "Туфлі мені не пасують." },
        { de: "Wir gratulieren euch zur Hochzeit!", uk: "Вітаємо вас з весіллям!" },
      ],
      tip: "Вивчай дієслова <b>разом із прикладом у Dat.</b>: <i>helfen + Dat., danken + Dat.</i>",
      mistakes: [
        { wrong: "Ich helfe dich.", right: "Ich helfe dir." },
        { wrong: "Ich danke den Lehrer.", right: "Ich danke dem Lehrer." },
        { wrong: "Das gehört mich.", right: "Das gehört mir." },
      ],
      exercises: {},
      prevSlug: "possessiv-dativ",
      nextSlug: "verben-akk-dat-a2",
    },
    extras: {
      duration: 13,
      premium: false,
      learningGoals: [
        "знати ТОП-12 дієслів з Dat.",
        "автоматично ставити особу в Dat.",
        "не плутати з Akk.",
      ],
      ruleBox: {
        rule: "<b>Verben + Dat.:</b> helfen, danken, gehören, gefallen, antworten, glauben, passen, schmecken, gratulieren, fehlen, folgen, begegnen, raten.",
      },
      ukrainianTips: [
        "В українській «допомагати кому», «дякувати кому» — теж Dat. Це збігається.",
        "<i>gehören</i> = «належати» — особа завжди в Dat.",
        "<i>gefallen</i> працює «навпаки» від укр.: <b>хто подобається</b> — Nom., <b>кому</b> — Dat.",
      ],
      languageComparison: {
        commons: ["Багато дієслів керують Dat. в обох мовах (допомагати, дякувати)."],
        diffs: ["«помагати», «дякувати» в укр. ще можуть бути з Acc., у нім. — лише Dat."],
        traps: ["<i>fragen</i> — Acc.! <i>antworten</i> — Dat. Не плутай."],
      },
      summary: [
        "Verben + Dat. без прийменника.",
        "ТОП: helfen, danken, gehören, gefallen…",
        "Особа завжди в Dat.",
        "fragen ≠ antworten щодо відмінка.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich helfe ___.", options: ["dich","dir","du","deiner"], correct: 1 },
      { type: "mc", q: "Wir danken ___ Lehrer.", options: ["den","dem","der","das"], correct: 1 },
      { type: "mc", q: "Das Auto gehört ___.", options: ["mich","mein","mir","meinen"], correct: 2 },
      { type: "mc", q: "Wie gefällt ___ der Film? (du)", options: ["dich","dir","dein","du"], correct: 1 },
      { type: "mc", q: "Ich gratuliere ___ zum Geburtstag! (du)", options: ["dich","dir","dein","du"], correct: 1 },
      { type: "gap", q: "Ich glaube ___ nicht. (du)", answer: "dir" },
      { type: "gap", q: "Die Schuhe passen ___ nicht. (ich)", answer: "mir" },
      { type: "gap", q: "Sie antwortet ___ Chef. (der)", answer: "dem" },
      { type: "gap", q: "Der Kuchen schmeckt ___ Kindern. (die)", answer: "den" },
      { type: "gap", q: "Wir helfen ___ Eltern. (unser, Pl.)", answer: "unseren" },
      { type: "tf", q: "Після <i>helfen</i> вживається Akk.", correct: false },
      { type: "tf", q: "Після <i>antworten</i> вживається Dat.", correct: true },
      { type: "match", prompt: "Дієслово → переклад:", pairs: [
        { left: "helfen", right: "допомагати" },
        { left: "danken", right: "дякувати" },
        { left: "gehören", right: "належати" },
        { left: "gefallen", right: "подобатись" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Das gehört mich.", correct: ["Das gehört mir."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Картина мені дуже подобається.",
        de: ["Das Bild gefällt mir sehr.","Mir gefällt das Bild sehr."] },
    ],
  },

  // ===================================================================
  "verben-akk-dat-a2": {
    lesson: {
      slug: "verben-akk-dat-a2",
      level: "A2",
      category: CAT,
      titleDe: "Verben mit Akkusativ und Dativ",
      titleUk: "Дієслова з Akk. + Dat. (geben, schenken, zeigen…)",
      goal: "Правильно вживати дієслова, які мають <b>дві</b> доповнення: Dat. (кому) + Akk. (що).",
      explanation: [
        "Класичні дієслова з двома додатками: <b>geben, schenken, zeigen, erklären, schicken, bringen, kaufen, leihen, empfehlen, erzählen, sagen, antworten</b>.",
        "Будова: <b>Subjekt + Verb + Dat. (кому) + Akk. (що).</b><br><i>Ich gebe <u>dem Kind</u> (Dat.) <u>das Buch</u> (Akk.).</i>",
        "<b>Порядок змінюється</b>, якщо один з додатків — <b>займенник</b>:<br>· два іменники: <b>Dat. + Akk.</b><br>· займенник + іменник: <b>займенник (будь-який) → перед іменником</b><br>· два займенники: <b>Akk. + Dat.</b><br><i>Ich gebe es ihm.</i>",
        "Якщо щось можна випустити — частіше випадає Dat.: <i>Ich gebe das Buch.</i>",
      ],
      table: {
        headers: ["Дієслово", "Структура", "Приклад"],
        rows: [
          ["geben", "j-m + etw.", "Ich gebe dir das Buch."],
          ["schenken", "j-m + etw.", "Er schenkt ihr Blumen."],
          ["zeigen", "j-m + etw.", "Sie zeigt uns die Stadt."],
          ["erklären", "j-m + etw.", "Der Lehrer erklärt den Schülern die Regel."],
          ["schicken", "j-m + etw.", "Ich schicke dir eine SMS."],
          ["empfehlen", "j-m + etw.", "Ich empfehle Ihnen den Wein."],
        ],
      },
      examples: [
        { de: "Ich gebe meinem Bruder das Buch.", uk: "Я даю своєму братові книгу." },
        { de: "Er schenkt seiner Freundin Blumen.", uk: "Він дарує своїй подрузі квіти." },
        { de: "Zeig mir das Foto!", uk: "Покажи мені фото!" },
        { de: "Der Lehrer erklärt uns die Regel.", uk: "Учитель пояснює нам правило." },
        { de: "Ich schicke dir eine E-Mail.", uk: "Я надішлю тобі мейл." },
        { de: "Kannst du mir das Salz reichen?", uk: "Можеш подати мені сіль?" },
        { de: "Ich kaufe meinem Kind ein Eis.", uk: "Я куплю своїй дитині морозиво." },
        { de: "Sie erzählt den Kindern eine Geschichte.", uk: "Вона розповідає дітям історію." },
        { de: "Ich gebe es ihm morgen.", uk: "Я дам це йому завтра." },
      ],
      tip: "Запам'ятай: <b>два іменники → Dat. + Akk.; два займенники → Akk. + Dat.; mix → займенник попереду</b>.",
      mistakes: [
        { wrong: "Ich gebe das Buch dem Kind.", right: "Ich gebe dem Kind das Buch." },
        { wrong: "Ich gebe ihm es.", right: "Ich gebe es ihm." },
        { wrong: "Er schenkt seine Freundin Blumen.", right: "Er schenkt seiner Freundin Blumen." },
      ],
      exercises: {},
      prevSlug: "verben-mit-dativ-a2",
      nextSlug: "praep-mit-dativ-a2",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "будувати «Subj. + V + Dat. + Akk.»",
        "правильно розставляти займенники",
        "знати ТОП-дієслова з двома додатками",
      ],
      ruleBox: {
        rule: "<b>Два іменники:</b> Dat. + Akk. <b>Два займенники:</b> Akk. + Dat. <b>Mix:</b> займенник попереду.",
      },
      ukrainianTips: [
        "В укр. теж: «Я даю братові книгу» (Dat. + Acc.).",
        "<i>schenken, geben, zeigen</i> — найчастіші. Вивчай блоками.",
        "Займенник «es» майже завжди стоїть першим після дієслова.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають структуру «дати кому що»."],
        diffs: ["У німецькій порядок змінюється від типу додатка (іменник чи займенник)."],
        traps: ["<s>Ich gebe ihm es.</s> → правильно <b>Ich gebe es ihm.</b>"],
      },
      summary: [
        "Два додатки: Dat. (кому) + Akk. (що).",
        "Іменники: Dat. перед Akk.",
        "Займенники: Akk. перед Dat.",
        "Mix: займенник попереду.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Правильний порядок (два іменники):",
        options: ["Ich gebe das Buch dem Kind.","Ich gebe dem Kind das Buch.","Ich gebe Kind Buch.","Ich dem Kind gebe Buch."], correct: 1 },
      { type: "mc", q: "Правильний порядок (два займенники):",
        options: ["Ich gebe ihm es.","Ich gebe es ihm.","Ich es ihm gebe.","Ich ihm es gebe."], correct: 1 },
      { type: "mc", q: "Er schenkt ___ Freundin Blumen. (sein)",
        options: ["seine","seiner","seinem","seinen"], correct: 1 },
      { type: "mc", q: "Zeig ___ das Foto! (ich)",
        options: ["mich","mir","mein","meiner"], correct: 1 },
      { type: "mc", q: "Der Lehrer erklärt ___ Schülern die Regel.",
        options: ["die","dem","der","den"], correct: 3 },
      { type: "gap", q: "Ich schicke ___ eine SMS. (du)", answer: "dir" },
      { type: "gap", q: "Sie erzählt ___ Kindern eine Geschichte. (die)", answer: "den" },
      { type: "gap", q: "Ich gebe ___ das Buch. (mein Bruder → Dat.)", answer: "meinem Bruder" },
      { type: "gap", q: "Ich gebe es ___. (er)", answer: "ihm" },
      { type: "gap", q: "Kannst du ___ das Salz reichen? (ich)", answer: "mir" },
      { type: "tf", q: "Якщо обидва додатки — займенники, Dat. іде перед Akk.", correct: false },
      { type: "tf", q: "Займенник стоїть перед іменником, незалежно від відмінка.", correct: true },
      { type: "match", prompt: "Дієслово → переклад:", pairs: [
        { left: "geben", right: "давати" },
        { left: "schenken", right: "дарувати" },
        { left: "zeigen", right: "показувати" },
        { left: "erklären", right: "пояснювати" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich gebe ihm es.", correct: ["Ich gebe es ihm."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я дарую мамі квіти.",
        de: ["Ich schenke meiner Mutter Blumen.","Ich schenke der Mutter Blumen."] },
    ],
  },

  // ===================================================================
  "praep-mit-dativ-a2": {
    lesson: {
      slug: "praep-mit-dativ-a2",
      level: "A2",
      category: CAT,
      titleDe: "Präpositionen mit Dativ",
      titleUk: "Прийменники з Dativ (aus, bei, mit, nach, seit, von, zu, gegenüber)",
      goal: "Запам'ятати ТОП-прийменники з Dat. і автоматично ставити іменник у Dativ.",
      explanation: [
        "Завжди вимагають Dativ: <b>aus, außer, bei, mit, nach, seit, von, zu, gegenüber</b>.",
        "Мнемоніка-римівка: <b>«aus – bei – mit – nach – seit – von – zu»</b>.",
        "<b>Verschmelzungen:</b> <i>bei dem → beim, von dem → vom, zu dem → zum, zu der → zur</i>.",
        "<b>gegenüber</b> часто стоїть <i>після</i> іменника: <i>dem Bahnhof gegenüber</i>.",
      ],
      table: {
        headers: ["Prep.", "Значення", "Приклад"],
        rows: [
          ["aus", "з (звідки/матеріал)", "Ich komme aus der Ukraine."],
          ["bei", "у (когось), при", "Ich wohne bei meinen Eltern."],
          ["mit", "з (разом, чим)", "Ich fahre mit dem Bus."],
          ["nach", "після / до (країни)", "Nach dem Essen / nach Berlin."],
          ["seit", "з (часу)", "Seit einem Jahr lerne ich Deutsch."],
          ["von", "від, з, про", "Das ist ein Geschenk von meinem Bruder."],
          ["zu", "до (когось/місця)", "Ich gehe zu meiner Freundin."],
          ["gegenüber", "навпроти", "Das Café liegt der Bank gegenüber."],
        ],
      },
      examples: [
        { de: "Ich komme aus der Ukraine.", uk: "Я з України." },
        { de: "Sie wohnt bei ihren Eltern.", uk: "Вона живе у своїх батьків." },
        { de: "Wir fahren mit dem Zug nach München.", uk: "Ми їдемо потягом у Мюнхен." },
        { de: "Nach der Arbeit gehe ich ins Fitnessstudio.", uk: "Після роботи я йду в спортзал." },
        { de: "Seit drei Jahren wohne ich in Wien.", uk: "Три роки я живу у Відні." },
        { de: "Das ist ein Brief von meinem Freund.", uk: "Це лист від мого друга." },
        { de: "Ich gehe zum Arzt.", uk: "Я йду до лікаря." },
        { de: "Das Hotel liegt dem Bahnhof gegenüber.", uk: "Готель розташований навпроти вокзалу." },
      ],
      tip: "Складна частина — <b>nach</b>: «до країни/міста» БЕЗ артикля (<i>nach Berlin</i>); але «після» — з Dat. (<i>nach der Arbeit</i>).",
      mistakes: [
        { wrong: "Ich komme aus die Ukraine.", right: "Ich komme aus der Ukraine." },
        { wrong: "Ich fahre mit den Bus.", right: "Ich fahre mit dem Bus." },
        { wrong: "Ich gehe zu der Arzt.", right: "Ich gehe zum Arzt." },
      ],
      exercises: {},
      prevSlug: "verben-akk-dat-a2",
      nextSlug: "dativ-position",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "знати напам'ять список Dat.-прийменників",
        "застосовувати Verschmelzungen (beim, vom, zum, zur)",
        "не плутати <i>nach</i> у двох значеннях",
      ],
      ruleBox: {
        rule: "<b>Dat.-Prep:</b> aus, außer, bei, mit, nach, seit, von, zu, gegenüber. Verschmelzungen: beim, vom, zum, zur.",
      },
      ukrainianTips: [
        "<i>seit</i> = «(вже) з/протягом» — часто з Präsens у нім.: <i>Seit 2020 lerne ich…</i>",
        "<i>bei</i> ≠ <i>mit</i>: <b>bei</b> = у когось (місце), <b>mit</b> = разом з / чим.",
        "<i>zu</i> + людина/заклад: <b>zum Arzt, zur Schule</b>.",
      ],
      languageComparison: {
        commons: ["Українські «з, у, до, після» теж керують відмінками."],
        diffs: ["У німецькій ці прийменники <b>фіксовано</b> з Dat., незалежно від значення."],
        traps: ["<i>nach Hause</i> — фразеологізм (без артикля)."],
      },
      summary: [
        "aus, außer, bei, mit, nach, seit, von, zu, gegenüber → Dat.",
        "Verschmelzungen: beim, vom, zum, zur.",
        "gegenüber часто після іменника.",
        "nach + країна/місто — без артикля.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Який прийменник НЕ керує Dat.?", options: ["mit","für","bei","seit"], correct: 1 },
      { type: "mc", q: "Ich komme aus ___ Ukraine.", options: ["die","der","den","das"], correct: 1 },
      { type: "mc", q: "Ich fahre mit ___ Bus.", options: ["den","dem","der","das"], correct: 1 },
      { type: "mc", q: "Ich gehe ___ Arzt.", options: ["zu der","zur","zum","zu den"], correct: 2 },
      { type: "mc", q: "Seit ___ Jahr lerne ich Deutsch. (ein)", options: ["einen","einem","einer","ein"], correct: 1 },
      { type: "gap", q: "Sie wohnt bei ___ Eltern. (ihre, Pl.)", answer: "ihren" },
      { type: "gap", q: "Nach ___ Arbeit gehe ich nach Hause. (die)", answer: "der" },
      { type: "gap", q: "Das ist ein Geschenk von ___ Bruder. (mein)", answer: "meinem" },
      { type: "gap", q: "Wir fahren mit ___ Zug. (der)", answer: "dem" },
      { type: "gap", q: "Ich gehe ___ Schule. (zu+die)", answer: "zur" },
      { type: "tf", q: "<i>seit</i> керує Dat.", correct: true },
      { type: "tf", q: "<i>für</i> — прийменник з Dat.", correct: false },
      { type: "match", prompt: "Verschmelzung:", pairs: [
        { left: "bei + dem", right: "beim" },
        { left: "von + dem", right: "vom" },
        { left: "zu + dem", right: "zum" },
        { left: "zu + der", right: "zur" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich fahre mit den Bus.", correct: ["Ich fahre mit dem Bus."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я живу зі своїми батьками вже три роки.",
        de: ["Ich wohne seit drei Jahren bei meinen Eltern.","Seit drei Jahren wohne ich bei meinen Eltern."] },
    ],
  },

  // ===================================================================
  "dativ-position": {
    lesson: {
      slug: "dativ-position",
      level: "A2",
      category: CAT,
      titleDe: "Position: Dativ und Akkusativ im Satz",
      titleUk: "Порядок Dativ і Akkusativ у реченні",
      goal: "Опанувати правила порядку Dat./Akk. — особливо із займенниками.",
      explanation: [
        "<b>Правило 1 — два іменники:</b> <i>Dat. перед Akk.</i><br><i>Ich gebe <u>dem Kind</u> <u>das Buch</u>.</i>",
        "<b>Правило 2 — займенник + іменник:</b> <i>займенник попереду</i> (незалежно від відмінка).<br><i>Ich gebe <u>es</u> dem Kind.</i> / <i>Ich gebe <u>ihm</u> das Buch.</i>",
        "<b>Правило 3 — два займенники:</b> <i>Akk. перед Dat.</i><br><i>Ich gebe <u>es</u> <u>ihm</u>.</i>",
        "Te-Ka-Mo-Lo з додатками: додатки зазвичай ідуть <b>після обставини часу</b>, але <b>перед обставиною місця</b>.",
      ],
      table: {
        headers: ["Випадок", "Порядок", "Приклад"],
        rows: [
          ["Іменник + іменник", "Dat. → Akk.", "Ich gebe dem Mann das Buch."],
          ["Займенник + іменник", "Pron. → Nomen", "Ich gebe ihm das Buch. / Ich gebe es dem Mann."],
          ["Займенник + займенник", "Akk. → Dat.", "Ich gebe es ihm."],
          ["З обставиною часу", "Zeit → Pron. → Nomen", "Ich gebe ihm morgen das Buch."],
        ],
      },
      examples: [
        { de: "Ich schenke meiner Mutter Blumen.", uk: "Я дарую мамі квіти." },
        { de: "Ich schenke ihr Blumen.", uk: "Я дарую їй квіти." },
        { de: "Ich schenke sie meiner Mutter.", uk: "Я дарую їх (квіти) мамі." },
        { de: "Ich schenke sie ihr.", uk: "Я дарую їх їй." },
        { de: "Morgen bringe ich dir die Bücher.", uk: "Завтра я принесу тобі книги." },
        { de: "Er erklärt es uns langsam.", uk: "Він пояснює це нам повільно." },
        { de: "Kannst du mir das Salz reichen?", uk: "Можеш подати мені сіль?" },
        { de: "Sie zeigt es ihren Eltern.", uk: "Вона показує це своїм батькам." },
      ],
      tip: "Швидке правило: <b>«Займенник раніше, ніж іменник»</b>. Якщо обидва — займенники, <b>«es» іде перед усіма</b>.",
      mistakes: [
        { wrong: "Ich gebe das Buch dem Kind.", right: "Ich gebe dem Kind das Buch." },
        { wrong: "Ich gebe ihm es.", right: "Ich gebe es ihm." },
        { wrong: "Ich gebe morgen ihm das Buch.", right: "Ich gebe ihm morgen das Buch." },
      ],
      exercises: {},
      prevSlug: "praep-mit-dativ-a2",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "автоматично визначати порядок Dat./Akk.",
        "ставити займенник перед іменником",
        "ставити Akk.-pron. перед Dat.-pron.",
      ],
      ruleBox: {
        rule: "<b>2 іменники:</b> Dat. → Akk. <b>2 займенники:</b> Akk. → Dat. <b>Mix:</b> займенник попереду.",
      },
      ukrainianTips: [
        "В українській порядок вільніший — у німецькій правила жорсткі.",
        "<i>es</i> — найменший і найшвидший — стоїть якомога раніше.",
        "Обставина часу зазвичай <b>перед</b> займенниками-додатками.",
      ],
      languageComparison: {
        commons: ["Логіка «кому → що» працює в обох мовах."],
        diffs: ["У німецькій порядок змінюється від форми (Nomen чи Pron.)."],
        traps: ["<s>Ich gebe morgen ihm das Buch.</s> → <b>Ich gebe ihm morgen das Buch.</b>"],
      },
      summary: [
        "2 іменники → Dat. + Akk.",
        "2 займенники → Akk. + Dat.",
        "Mix → займенник попереду.",
        "Pron. зазвичай після Verb, перед обставинами.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Правильний порядок:", options: [
        "Ich gebe das Buch dem Kind.",
        "Ich gebe dem Kind das Buch.",
        "Ich dem Kind gebe das Buch.",
        "Ich gebe Kind Buch.",
      ], correct: 1 },
      { type: "mc", q: "Правильний порядок (займенники):", options: [
        "Ich gebe ihm es.",
        "Ich gebe es ihm.",
        "Ich es ihm gebe.",
        "Ich ihm gebe es.",
      ], correct: 1 },
      { type: "mc", q: "Правильний порядок (mix):", options: [
        "Ich gebe das Buch ihm.",
        "Ich gebe ihm das Buch.",
        "Ich ihm gebe das Buch.",
        "Ich das Buch gebe ihm.",
      ], correct: 1 },
      { type: "mc", q: "Правильний порядок (з часом):", options: [
        "Ich gebe morgen ihm das Buch.",
        "Ich gebe ihm morgen das Buch.",
        "Morgen ich gebe ihm das Buch.",
        "Ich ihm morgen gebe das Buch.",
      ], correct: 1 },
      { type: "mc", q: "Ich zeige ___ ___.", options: [
        "es ihr","ihr es","sie ihr","ihr sie",
      ], correct: 0 },
      { type: "gap", q: "Ich gebe ___ (Dat. mein Bruder) das Buch.", answer: "meinem Bruder" },
      { type: "gap", q: "Ich gebe es ___ (er).", answer: "ihm" },
      { type: "gap", q: "Ich schenke ___ (sie/вона) Blumen.", answer: "ihr" },
      { type: "gap", q: "Sie erklärt ___ (wir) das.", answer: "uns" },
      { type: "gap", q: "Morgen bringe ich ___ (du) die Bücher.", answer: "dir" },
      { type: "tf", q: "Два займенники: Dat. іде перед Akk.", correct: false },
      { type: "tf", q: "Займенник іде перед іменником.", correct: true },
      { type: "match", prompt: "Випадок → порядок:", pairs: [
        { left: "Nomen + Nomen", right: "Dat. → Akk." },
        { left: "Pron. + Nomen", right: "Pron. → Nomen" },
        { left: "Pron. + Pron.", right: "Akk. → Dat." },
        { left: "З часом", right: "Zeit → Pron." },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich gebe ihm es.", correct: ["Ich gebe es ihm."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я дарую їх їй.",
        de: ["Ich schenke sie ihr."] },
    ],
  },
};
