// A2 · Прийменники — 8 повних уроків.
import type { A2Map } from "./_helpers";

const CAT = "Прийменники";

export const praepositionenA2: A2Map = {
  // ===================================================================
  "praep-akkusativ": {
    lesson: {
      slug: "praep-akkusativ",
      level: "A2",
      category: CAT,
      titleDe: "Präpositionen mit Akkusativ",
      titleUk: "Прийменники з Akkusativ",
      goal: "Запам'ятати 7 прийменників, що завжди вимагають Akkusativ, і правильно вживати їх у реченнях.",
      explanation: [
        "Є <b>7 прийменників</b>, які <b>завжди</b> керують Akkusativ: <b>durch, für, gegen, ohne, um, bis, entlang</b>.",
        "Мнемоніка: <b>«DOGFUBE»</b> або фраза <i>«durch · für · gegen · ohne · um · bis · entlang»</i>.",
        "<b>durch</b> — крізь, через; <b>für</b> — для, за; <b>gegen</b> — проти, близько (часу); <b>ohne</b> — без; <b>um</b> — о (часі), навколо; <b>bis</b> — до (часу/місця); <b>entlang</b> — уздовж (стоїть <b>після</b> іменника!).",
        "Після цих прийменників артикль/займенник іде в Akkusativ: <i>der → den, ein → einen, ich → mich, er → ihn</i>.",
      ],
      table: {
        headers: ["Präp.", "Значення", "Приклад"],
        rows: [
          ["durch", "крізь, через", "Wir gehen durch den Park."],
          ["für", "для, за", "Das Geschenk ist für dich."],
          ["gegen", "проти; близько (час)", "Ich bin gegen den Plan. / gegen 8 Uhr."],
          ["ohne", "без", "Ich trinke Kaffee ohne Zucker."],
          ["um", "о; навколо", "Um 9 Uhr. / Um den Tisch."],
          ["bis", "до (часу/місця)", "Bis morgen! / Bis Berlin."],
          ["entlang", "уздовж (після ім.)", "Ich gehe den Fluss entlang."],
        ],
      },
      examples: [
        { de: "Wir laufen durch den Wald.", uk: "Ми йдемо через ліс." },
        { de: "Diese Blumen sind für meine Mutter.", uk: "Ці квіти для моєї мами." },
        { de: "Ich habe nichts gegen ihn.", uk: "Я нічого не маю проти нього." },
        { de: "Ohne dich ist es langweilig.", uk: "Без тебе нудно." },
        { de: "Der Film beginnt um 20 Uhr.", uk: "Фільм починається о 20-й." },
        { de: "Bis nächste Woche!", uk: "До наступного тижня!" },
        { de: "Wir fahren die Straße entlang.", uk: "Ми їдемо вздовж вулиці." },
        { de: "Gegen 7 Uhr bin ich zu Hause.", uk: "Близько 7-ї я вдома." },
      ],
      tip: "<b>entlang</b> — єдиний з цієї сімки, що стоїть <i>після</i> іменника: <i>den Fluss <b>entlang</b></i>, а не <i>entlang den Fluss</i>.",
      mistakes: [
        { wrong: "für mir", right: "für mich" },
        { wrong: "ohne mein Buch (Dat.)", right: "ohne mein Buch (Akk.)" },
        { wrong: "entlang die Straße", right: "die Straße entlang" },
      ],
      exercises: {},
      nextSlug: "praep-dativ",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "знати всі 7 прийменників з Akkusativ напам'ять",
        "правильно змінювати артикль і займенник на Akk.",
        "розуміти спеціальне місце слова entlang",
      ],
      ruleBox: {
        rule: "<b>durch · für · gegen · ohne · um · bis · entlang</b> → <b>Akkusativ</b>. <b>entlang</b> стоїть <b>після</b> іменника.",
      },
      ukrainianTips: [
        "Українське «для мене» = <b>für mich</b> (не <i>für mir</i>).",
        "<b>gegen</b> має два значення: «проти» і «близько» (час).",
        "<b>bis</b> часто вживається без артикля: <i>bis Montag, bis Wien</i>.",
      ],
      languageComparison: {
        commons: ["В обох мовах прийменник стоїть перед іменником (крім entlang)."],
        diffs: ["У німецькій після цих 7 — завжди Akkusativ, навіть якщо в українській інший відмінок."],
        traps: ["Помилка: казати «für mir» замість «für mich»."],
      },
      summary: [
        "7 прийменників з Akk.: durch, für, gegen, ohne, um, bis, entlang.",
        "Артикль/займенник → Akkusativ.",
        "entlang ставимо після іменника.",
        "Мнемоніка: DOGFUBE або «für · gegen · ohne · um …».",
      ],
    },
    exercises15: [
      { type: "mc", q: "Das Geschenk ist ___ dich.", options: ["für","von","mit","zu"], correct: 0 },
      { type: "mc", q: "Wir gehen ___ den Park.", options: ["durch","bei","aus","seit"], correct: 0 },
      { type: "mc", q: "Ich trinke Kaffee ___ Zucker.", options: ["mit","ohne","für","gegen"], correct: 1 },
      { type: "mc", q: "Der Kurs beginnt ___ 9 Uhr.", options: ["am","im","um","an"], correct: 2 },
      { type: "mc", q: "Ich habe nichts ___ ihn.", options: ["für","gegen","ohne","um"], correct: 1 },
      { type: "gap", q: "Wir fahren die Straße ___. (уздовж)", answer: "entlang" },
      { type: "gap", q: "___ morgen! (до завтра)", answer: "Bis" },
      { type: "gap", q: "Das ist ein Geschenk für ___. (мене)", answer: "mich" },
      { type: "gap", q: "Wir sitzen ___ den Tisch. (навколо)", answer: "um" },
      { type: "tf", q: "Прийменник «für» вимагає Dativ.", correct: false },
      { type: "tf", q: "«entlang» ставиться після іменника.", correct: true },
      { type: "match", prompt: "Прийменник → значення:", pairs: [
        { left: "durch", right: "крізь" },
        { left: "für", right: "для" },
        { left: "ohne", right: "без" },
        { left: "bis", right: "до" },
      ]},
      { type: "multi", q: "Які прийменники вимагають Akkusativ?",
        options: ["für","mit","durch","aus","ohne","seit"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Das ist für mir.", correct: ["Das ist für mich."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я нічого не маю проти тебе.",
        de: ["Ich habe nichts gegen dich."] },
    ],
  },

  // ===================================================================
  "praep-dativ": {
    lesson: {
      slug: "praep-dativ",
      level: "A2",
      category: CAT,
      titleDe: "Präpositionen mit Dativ",
      titleUk: "Прийменники з Dativ",
      goal: "Запам'ятати 9 прийменників, що завжди керують Dativ, і вживати правильні форми артиклів та займенників.",
      explanation: [
        "<b>9 прийменників завжди вимагають Dativ</b>: <b>aus, bei, mit, nach, seit, von, zu, gegenüber, außer</b>.",
        "Класична мнемоніка: <i>«aus, bei, mit, nach, seit, von, zu»</i> (співається на мелодію).",
        "Артикль → Dativ: <i>der/das → dem, die → der, die (Pl.) → den + n</i>. Займенники: <i>ich → mir, du → dir, er → ihm, sie → ihr, wir → uns, ihr → euch, sie/Sie → ihnen/Ihnen</i>.",
        "<b>gegenüber</b> може стояти до або <b>після</b> іменника: <i>gegenüber dem Park</i> або <i>dem Park gegenüber</i>.",
      ],
      table: {
        headers: ["Präp.", "Значення", "Приклад"],
        rows: [
          ["aus", "з (зсередини, походження)", "Ich komme aus der Ukraine."],
          ["bei", "у (когось), при, біля", "Ich wohne bei meinen Eltern."],
          ["mit", "з (разом), за допомогою", "Ich fahre mit dem Bus."],
          ["nach", "після; до (країни/міста без артикля)", "Nach der Arbeit. / Nach Berlin."],
          ["seit", "з (часу)", "Seit einem Jahr."],
          ["von", "від, від (когось)", "Ein Brief von meiner Oma."],
          ["zu", "до (когось/кудись)", "Ich gehe zum Arzt."],
          ["gegenüber", "навпроти", "Gegenüber dem Bahnhof."],
          ["außer", "крім", "Außer mir war niemand da."],
        ],
      },
      examples: [
        { de: "Ich komme aus der Schweiz.", uk: "Я зі Швейцарії." },
        { de: "Wir arbeiten bei Siemens.", uk: "Ми працюємо в Siemens." },
        { de: "Sie spielt mit ihrem Bruder.", uk: "Вона грає зі своїм братом." },
        { de: "Nach dem Essen gehen wir spazieren.", uk: "Після їжі ми йдемо гуляти." },
        { de: "Seit drei Monaten lerne ich Deutsch.", uk: "Я вивчаю німецьку три місяці." },
        { de: "Das ist ein Geschenk von mir.", uk: "Це подарунок від мене." },
        { de: "Ich fahre zu meiner Tante.", uk: "Я їду до тітки." },
        { de: "Gegenüber der Schule ist ein Café.", uk: "Навпроти школи є кафе." },
      ],
      tip: "Запам'ятай ритм: <i>«aus-bei-mit-nach-seit-von-zu»</i>. Це сім головних — додай <b>gegenüber</b> й <b>außer</b>, і знаєш усі.",
      mistakes: [
        { wrong: "mit mich", right: "mit mir" },
        { wrong: "zu der Arzt", right: "zum Arzt" },
        { wrong: "nach den Essen", right: "nach dem Essen" },
      ],
      exercises: {},
      prevSlug: "praep-akkusativ",
      nextSlug: "wechselpraepositionen",
    },
    extras: {
      duration: 15,
      premium: false,
      learningGoals: [
        "знати всі 9 прийменників з Dativ напам'ять",
        "правильно змінювати артикль і займенник на Dat.",
        "розрізняти aus / von і nach / zu",
      ],
      ruleBox: {
        rule: "<b>aus, bei, mit, nach, seit, von, zu, gegenüber, außer</b> → <b>Dativ</b>.",
      },
      ukrainianTips: [
        "<b>aus</b> — походження (з країни / зсередини); <b>von</b> — від когось/чогось.",
        "<b>nach</b> — до країни/міста <i>без артикля</i>; <b>zu</b> — до людини/закладу.",
        "<b>seit</b> = «вже стільки часу», в українській — теперішній час: <i>seit 3 Jahren = вже 3 роки</i>.",
      ],
      languageComparison: {
        commons: ["Обидві мови розрізняють «з кимось» і «з якогось місця»."],
        diffs: ["Німецька строго ділить nach (місто) і zu (людина/заклад)."],
        traps: ["Помилка: «zu Berlin» замість «nach Berlin»."],
      },
      summary: [
        "9 прийменників з Dat.: aus, bei, mit, nach, seit, von, zu, gegenüber, außer.",
        "Артикль: dem / der / dem / den+n.",
        "Займенники: mir, dir, ihm, ihr, uns, euch, ihnen.",
        "nach + місто/країна; zu + людина/заклад.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich komme ___ der Ukraine.", options: ["aus","von","zu","bei"], correct: 0 },
      { type: "mc", q: "Ich fahre ___ dem Bus.", options: ["bei","mit","von","aus"], correct: 1 },
      { type: "mc", q: "Wir gehen ___ Arzt.", options: ["zur","zum","nach","aus"], correct: 1 },
      { type: "mc", q: "___ einem Jahr lerne ich Deutsch.", options: ["Seit","Für","Vor","Bis"], correct: 0 },
      { type: "mc", q: "Ich fahre ___ Berlin.", options: ["zu","nach","bei","aus"], correct: 1 },
      { type: "gap", q: "Das Geschenk ist von ___. (мене)", answer: "mir" },
      { type: "gap", q: "Ich wohne bei ___ Eltern.", answer: "meinen" },
      { type: "gap", q: "Nach ___ Essen gehe ich spazieren. (артикль до das Essen)", answer: "dem" },
      { type: "gap", q: "Sie spielt mit ___ Bruder. (її)", answer: "ihrem" },
      { type: "tf", q: "Прийменник «seit» вимагає Akkusativ.", correct: false },
      { type: "tf", q: "Перед країною/містом без артикля вживається «nach».", correct: true },
      { type: "match", prompt: "Прийменник → значення:", pairs: [
        { left: "aus", right: "з (звідки)" },
        { left: "mit", right: "з (разом)" },
        { left: "seit", right: "відколи" },
        { left: "gegenüber", right: "навпроти" },
      ]},
      { type: "multi", q: "Які прийменники вимагають Dativ?",
        options: ["mit","durch","aus","ohne","seit","für"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich fahre zu Berlin.", correct: ["Ich fahre nach Berlin."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я живу в моїх батьків уже три роки.",
        de: ["Ich wohne seit drei Jahren bei meinen Eltern."] },
    ],
  },

  // ===================================================================
  wechselpraepositionen: {
    lesson: {
      slug: "wechselpraepositionen",
      level: "A2",
      category: CAT,
      titleDe: "Wechselpräpositionen (Akk./Dat.)",
      titleUk: "Прийменники подвійного керування",
      goal: "Розрізняти Wo? (Dativ) і Wohin? (Akkusativ) з 9 прийменниками місця.",
      explanation: [
        "<b>9 Wechselpräpositionen</b>: <b>an, auf, hinter, in, neben, über, unter, vor, zwischen</b>.",
        "Правило просте: <b>Wohin? (рух) → Akkusativ</b>; <b>Wo? (місце) → Dativ</b>.",
        "Питання-підказка: якщо можна спитати <i>«куди?»</i> — Akk., якщо <i>«де?»</i> — Dat.",
        "Дієслова руху: <i>stellen, legen, hängen, setzen, gehen, fahren</i> → Akk. Дієслова стану: <i>stehen, liegen, hängen, sitzen, sein</i> → Dat.",
      ],
      table: {
        headers: ["Wohin? (Akk.)", "Wo? (Dat.)", "Український аналог"],
        rows: [
          ["in den Park", "im Park", "у парк / у парку"],
          ["auf den Tisch", "auf dem Tisch", "на стіл / на столі"],
          ["an die Wand", "an der Wand", "на стіну / на стіні"],
          ["unter das Bett", "unter dem Bett", "під ліжко / під ліжком"],
          ["zwischen die Bücher", "zwischen den Büchern", "між книги / між книгами"],
        ],
      },
      examples: [
        { de: "Ich gehe in die Schule. (Wohin?)", uk: "Я йду до школи." },
        { de: "Ich bin in der Schule. (Wo?)", uk: "Я в школі." },
        { de: "Stell die Tasse auf den Tisch!", uk: "Постав чашку на стіл!" },
        { de: "Die Tasse steht auf dem Tisch.", uk: "Чашка стоїть на столі." },
        { de: "Häng das Bild an die Wand!", uk: "Повісь картину на стіну!" },
        { de: "Das Bild hängt an der Wand.", uk: "Картина висить на стіні." },
        { de: "Der Hund läuft unter das Bett.", uk: "Собака біжить під ліжко." },
        { de: "Der Hund liegt unter dem Bett.", uk: "Собака лежить під ліжком." },
      ],
      tip: "Пара дієслів: <b>stellen / stehen</b>, <b>legen / liegen</b>, <b>hängen / hängen</b>, <b>setzen / sitzen</b>. Перше — рух (Akk.), друге — стан (Dat.).",
      mistakes: [
        { wrong: "Ich gehe in der Schule.", right: "Ich gehe in die Schule." },
        { wrong: "Das Buch liegt auf den Tisch.", right: "Das Buch liegt auf dem Tisch." },
        { wrong: "Ich hänge das Bild an der Wand.", right: "Ich hänge das Bild an die Wand." },
      ],
      exercises: {},
      prevSlug: "praep-dativ",
      nextSlug: "praep-genitiv",
    },
    extras: {
      duration: 18,
      premium: false,
      learningGoals: [
        "знати всі 9 Wechselpräpositionen",
        "автоматично визначати Wo? чи Wohin?",
        "розрізняти пари stellen/stehen, legen/liegen тощо",
      ],
      ruleBox: {
        rule: "<b>Wohin? → Akkusativ</b> (рух). <b>Wo? → Dativ</b> (місце).",
      },
      ukrainianTips: [
        "Українське «в школу» (куди) ≠ «в школі» (де). У німецькій те саме: <i>in die Schule / in der Schule</i>.",
        "Дієслова <i>stehen, liegen, sitzen, hängen (висіти)</i> — завжди Dativ.",
        "Дієслова <i>stellen, legen, setzen, hängen (вішати)</i> — завжди Akkusativ.",
      ],
      languageComparison: {
        commons: ["Обидві мови розрізняють напрям і місце."],
        diffs: ["У німецькій це передається відмінком, а не іншим прийменником."],
        traps: ["Помилка: «in der Park gehen» замість «in den Park»."],
      },
      summary: [
        "9 Wechselpräpositionen: an, auf, hinter, in, neben, über, unter, vor, zwischen.",
        "Wohin? → Akk. (рух).",
        "Wo? → Dat. (місце).",
        "Пари дієслів: stellen/stehen, legen/liegen, setzen/sitzen.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich gehe ___ Park. (Wohin?)", options: ["in dem","in den","im","ins"], correct: 1 },
      { type: "mc", q: "Ich bin ___ Park. (Wo?)", options: ["in den","in das","im","ins"], correct: 2 },
      { type: "mc", q: "Stell die Vase ___ Tisch!", options: ["auf den","auf dem","an dem","im"], correct: 0 },
      { type: "mc", q: "Die Vase steht ___ Tisch.", options: ["auf den","auf dem","auf das","an den"], correct: 1 },
      { type: "mc", q: "Häng das Bild ___ Wand!", options: ["an der","an die","auf der","unter der"], correct: 1 },
      { type: "gap", q: "Der Hund liegt unter ___ Bett. (Wo?)", answer: "dem" },
      { type: "gap", q: "Die Katze springt auf ___ Sofa. (Wohin?)", answer: "das" },
      { type: "gap", q: "Wir sitzen ___ dem Tisch. (за)", answer: "an" },
      { type: "gap", q: "Stell die Lampe ___ das Fenster. (поруч)", answer: "neben" },
      { type: "tf", q: "stehen — це дієслово руху і вимагає Akk.", correct: false },
      { type: "tf", q: "Wohin? → Akkusativ.", correct: true },
      { type: "match", prompt: "Питання → відмінок:", pairs: [
        { left: "Wohin?", right: "Akkusativ" },
        { left: "Wo?", right: "Dativ" },
        { left: "stellen", right: "Akkusativ" },
        { left: "stehen", right: "Dativ" },
      ]},
      { type: "multi", q: "Які з цих — Wechselpräpositionen?",
        options: ["an","mit","auf","aus","unter","seit"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich gehe in der Schule.", correct: ["Ich gehe in die Schule."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Картина висить на стіні, а лампа стоїть на столі.",
        de: ["Das Bild hängt an der Wand, und die Lampe steht auf dem Tisch."] },
    ],
  },

  // ===================================================================
  "praep-genitiv": {
    lesson: {
      slug: "praep-genitiv",
      level: "A2",
      category: CAT,
      titleDe: "Präpositionen mit Genitiv",
      titleUk: "Прийменники з Genitiv",
      goal: "Познайомитися з 4 базовими прийменниками Genitiv і вживати їх у простих реченнях.",
      explanation: [
        "На рівні A2 достатньо знати <b>4 базові прийменники Genitiv</b>: <b>wegen, trotz, während, (an)statt</b>.",
        "Genitiv-артиклі: <b>des / der / des / der</b>; маск./нейтр. іменник отримує <b>-s</b> або <b>-es</b>: <i>des Mannes, des Kindes</i>.",
        "У розмовній мові часто замість Genitiv вживають Dativ: <i>«wegen dem Wetter»</i> — допустимо, але <i>«wegen des Wetters»</i> — стандарт.",
        "<b>während</b> = під час; <b>wegen</b> = через (причина); <b>trotz</b> = незважаючи на; <b>statt</b> = замість.",
      ],
      table: {
        headers: ["Präp.", "Значення", "Приклад (Genitiv)"],
        rows: [
          ["wegen", "через (причина)", "wegen des Wetters"],
          ["trotz", "незважаючи на", "trotz des Regens"],
          ["während", "під час", "während der Pause"],
          ["statt / anstatt", "замість", "statt des Kaffees"],
        ],
      },
      examples: [
        { de: "Wegen des Wetters bleiben wir zu Hause.", uk: "Через погоду ми залишаємось удома." },
        { de: "Trotz des Regens spielen die Kinder draußen.", uk: "Незважаючи на дощ, діти граються надворі." },
        { de: "Während der Pause trinke ich Kaffee.", uk: "Під час перерви я п'ю каву." },
        { de: "Statt eines Buches kaufe ich ein Hörbuch.", uk: "Замість книги я купую аудіокнигу." },
        { de: "Wegen meiner Erkältung gehe ich nicht zur Arbeit.", uk: "Через застуду я не йду на роботу." },
        { de: "Während des Films war es still.", uk: "Під час фільму було тихо." },
        { de: "Trotz der Kälte trägt er kein Jackett.", uk: "Незважаючи на холод, він не носить піджак." },
        { de: "Anstatt des Saftes nehme ich Wasser.", uk: "Замість соку я візьму воду." },
      ],
      tip: "Запам'ятай мнемоніку: <b>«WTWS»</b> — <i>wegen, trotz, während, statt</i>. У розмовній мові часто з Dativ — це не помилка, але іспит хоче Genitiv.",
      mistakes: [
        { wrong: "wegen das Wetter", right: "wegen des Wetters" },
        { wrong: "während der Pause (без -s у нейтр.)", right: "während des Konzerts" },
        { wrong: "trotz dem Regen (письмово)", right: "trotz des Regens" },
      ],
      exercises: {},
      prevSlug: "wechselpraepositionen",
      nextSlug: "temporale-praepositionen",
    },
    extras: {
      duration: 13,
      premium: false,
      learningGoals: [
        "знати 4 базові прийменники Genitiv",
        "правильно утворювати Genitiv-артикль і -s",
        "розуміти різницю між письмовим Genitiv і розмовним Dativ",
      ],
      ruleBox: {
        rule: "<b>wegen, trotz, während, statt</b> → <b>Genitiv</b>. Артиклі: <b>des / der / des / der</b>; мaск./нейтр. + <b>-s/-es</b>.",
      },
      ukrainianTips: [
        "Українське «через дощ» = <b>wegen des Regens</b> (а не «durch»).",
        "<b>während</b> у часовому значенні — лише «під час», не «поки» (це <i>während</i> як сполучник з підрядним).",
        "У живому мовленні німці часто кажуть «wegen dem Wetter» — це Dativ, прийнятно у спілкуванні.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають окремий «родовий» зміст."],
        diffs: ["У німецькій Genitiv після прийменників, а не саме закінчення іменника як ознака."],
        traps: ["Помилка: ставити Akkusativ після «wegen»."],
      },
      summary: [
        "4 прийменники Genitiv: wegen, trotz, während, statt.",
        "Артиклі: des / der / des / der.",
        "Маск./нейтр. ім.: + -s або -es.",
        "Розмовно — часто Dativ.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ des Wetters bleiben wir zu Hause.", options: ["Trotz","Wegen","Während","Statt"], correct: 1 },
      { type: "mc", q: "Wir gehen ___ des Regens spazieren.", options: ["wegen","trotz","während","statt"], correct: 1 },
      { type: "mc", q: "___ der Pause trinke ich Kaffee.", options: ["Wegen","Trotz","Während","Statt"], correct: 2 },
      { type: "mc", q: "Ich nehme Tee ___ Kaffees.", options: ["statt des","statt dem","statt der","statt den"], correct: 0 },
      { type: "gap", q: "Wegen ___ Erkältung bleibe ich zu Hause. (моя — Gen. fem.)", answer: "meiner" },
      { type: "gap", q: "Während des ___ war es still. (Film → Gen.)", answer: "Films" },
      { type: "gap", q: "Trotz ___ Kälte spielt er Tennis. (артикль fem.)", answer: "der" },
      { type: "gap", q: "Statt ___ Buches kaufe ich ein Hörbuch. (артикль neutr.)", answer: "eines" },
      { type: "tf", q: "Прийменник «wegen» формально вимагає Genitiv.", correct: true },
      { type: "tf", q: "Genitiv-артикль для жіночого роду — «des».", correct: false },
      { type: "match", prompt: "Прийменник → значення:", pairs: [
        { left: "wegen", right: "через" },
        { left: "trotz", right: "незважаючи на" },
        { left: "während", right: "під час" },
        { left: "statt", right: "замість" },
      ]},
      { type: "multi", q: "Які прийменники вимагають Genitiv (формально)?",
        options: ["wegen","mit","trotz","aus","während","seit"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "wegen das Wetter", correct: ["wegen des Wetters"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Незважаючи на дощ, ми йдемо гуляти.",
        de: ["Trotz des Regens gehen wir spazieren."] },
      { type: "writeFree", prompt: "2 речення з «wegen» та «während».",
        sample: "Wegen der Kälte trage ich eine Jacke. Während der Pause lese ich ein Buch." },
    ],
  },

  // ===================================================================
  "temporale-praepositionen": {
    lesson: {
      slug: "temporale-praepositionen",
      level: "A2",
      category: CAT,
      titleDe: "Temporale Präpositionen",
      titleUk: "Часові прийменники",
      goal: "Знати, який прийменник уживати з годинами, днями, місяцями, роками й тривалістю.",
      explanation: [
        "<b>um</b> — точний час: <i>um 8 Uhr</i>.",
        "<b>am</b> (an+dem) — дні тижня й частини доби: <i>am Montag, am Morgen, am Wochenende</i>.",
        "<b>im</b> (in+dem) — місяці, пори року, роки з «Jahr»: <i>im Mai, im Sommer, im Jahr 2024</i>.",
        "<b>vor</b> = до (минуле): <i>vor zwei Tagen</i>; <b>nach</b> = після: <i>nach dem Essen</i>.",
        "<b>seit</b> = відколи (триває досі): <i>seit einem Monat</i>; <b>bis</b> = до (моменту): <i>bis Freitag</i>; <b>von … bis …</b>: <i>von Montag bis Freitag</i>.",
        "<b>in</b> + Dat. = через (майбутнє): <i>in zwei Wochen</i>.",
        "Винятки без прийменника: <i>nächste Woche, letztes Jahr, heute Abend</i>.",
      ],
      table: {
        headers: ["Коли?", "Прийменник", "Приклад"],
        rows: [
          ["година", "um", "um 7 Uhr"],
          ["день / частина дня", "am", "am Freitag, am Abend"],
          ["місяць / сезон / рік", "im", "im Juli, im Winter"],
          ["минуле", "vor", "vor drei Tagen"],
          ["майбутнє", "in", "in einer Stunde"],
          ["триває", "seit", "seit 2020"],
          ["від — до", "von … bis …", "von 9 bis 17 Uhr"],
        ],
      },
      examples: [
        { de: "Der Kurs beginnt um 9 Uhr.", uk: "Курс починається о 9-й." },
        { de: "Am Sonntag schlafe ich lange.", uk: "У неділю я довго сплю." },
        { de: "Im August fahren wir nach Italien.", uk: "У серпні ми їдемо в Італію." },
        { de: "Vor einer Woche war ich in Wien.", uk: "Тиждень тому я був(ла) у Відні." },
        { de: "In zwei Stunden bin ich zurück.", uk: "Через дві години я повернусь." },
        { de: "Seit drei Jahren wohne ich hier.", uk: "Я живу тут уже 3 роки." },
        { de: "Wir arbeiten von 9 bis 17 Uhr.", uk: "Ми працюємо з 9 до 17." },
        { de: "Nach dem Essen trinken wir Kaffee.", uk: "Після їжі ми п'ємо каву." },
      ],
      tip: "Просте правило: <b>am</b> — дні; <b>im</b> — місяці/сезони; <b>um</b> — години. <i>«am Montag im Mai um 8»</i>.",
      mistakes: [
        { wrong: "in Montag", right: "am Montag" },
        { wrong: "am Mai", right: "im Mai" },
        { wrong: "seit zwei Tage (Akk.)", right: "seit zwei Tagen (Dat.)" },
      ],
      exercises: {},
      prevSlug: "praep-genitiv",
      nextSlug: "lokale-praepositionen",
    },
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "вибирати am / im / um правильно",
        "розрізняти vor / seit / in (час)",
        "будувати конструкцію von … bis …",
      ],
      ruleBox: {
        rule: "<b>um</b> = год.; <b>am</b> = день/частина дня; <b>im</b> = місяць/сезон/рік.",
      },
      ukrainianTips: [
        "«У понеділок» = <b>am Montag</b>, не <i>in Montag</i>.",
        "«У травні» = <b>im Mai</b>, не <i>am Mai</i>.",
        "«Через тиждень» (майбутнє) = <b>in einer Woche</b>; «тиждень тому» = <b>vor einer Woche</b>.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають «у понеділок», «у травні», але прийменник різний."],
        diffs: ["Німецька суворо ділить am / im / um, а українська — один прийменник «у»."],
        traps: ["Помилка: «in 2024» — правильно «im Jahr 2024» або просто «2024»."],
      },
      summary: [
        "um — година.",
        "am — день / частина дня.",
        "im — місяць / сезон / рік.",
        "vor — минуле; in — майбутнє; seit — триває.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Der Kurs beginnt ___ 9 Uhr.", options: ["am","im","um","an"], correct: 2 },
      { type: "mc", q: "___ Montag habe ich frei.", options: ["Im","Am","Um","In"], correct: 1 },
      { type: "mc", q: "___ Mai fahren wir weg.", options: ["Am","Im","Um","An"], correct: 1 },
      { type: "mc", q: "___ einer Stunde bin ich da. (через)", options: ["Vor","In","Seit","Nach"], correct: 1 },
      { type: "mc", q: "___ einer Woche war ich krank. (тиждень тому)", options: ["In","Seit","Vor","Bis"], correct: 2 },
      { type: "gap", q: "Ich wohne ___ 2019 in Berlin. (відколи)", answer: "seit" },
      { type: "gap", q: "Wir arbeiten ___ 9 ___ 17 Uhr.", answer: "von" },
      { type: "gap", q: "___ Wochenende schlafe ich lange.", answer: "Am" },
      { type: "gap", q: "___ Winter fahren wir Ski.", answer: "Im" },
      { type: "tf", q: "Перед годиною вживаємо «am».", correct: false },
      { type: "tf", q: "«Через 2 дні» = «in zwei Tagen».", correct: true },
      { type: "match", prompt: "Час → прийменник:", pairs: [
        { left: "8 Uhr", right: "um" },
        { left: "Montag", right: "am" },
        { left: "Juli", right: "im" },
        { left: "2 Tage (минуле)", right: "vor" },
      ]},
      { type: "multi", q: "Які прийменники часові?",
        options: ["um","durch","am","für","seit","ohne"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich komme in Montag.", correct: ["Ich komme am Montag."] },
      { type: "translate", prompt: "Переклади:",
        uk: "У неділю о 10 годині я граю в теніс.",
        de: ["Am Sonntag um 10 Uhr spiele ich Tennis."] },
    ],
  },

  // ===================================================================
  "lokale-praepositionen": {
    lesson: {
      slug: "lokale-praepositionen",
      level: "A2",
      category: CAT,
      titleDe: "Lokale Präpositionen",
      titleUk: "Прийменники місця",
      goal: "Правильно описувати місцезнаходження й напрямок руху німецькою.",
      explanation: [
        "<b>Місце (Wo?)</b> — Dativ: <i>in der Stadt, bei meinen Eltern, auf dem Tisch, zwischen den Häusern</i>.",
        "<b>Напрямок (Wohin?)</b> — залежно від мети: <b>nach</b> + місто/країна без артикля (nach Berlin, nach Italien), <b>in</b> + Akk. (in die Schweiz — країна з артиклем, in den Park), <b>zu</b> + Dat. (zu Maria, zum Arzt), <b>auf</b> + Akk. (auf den Markt).",
        "<b>Походження (Woher?)</b>: <b>aus</b> + Dat. (aus Deutschland, aus dem Haus), <b>von</b> + Dat. (von Maria, vom Arzt).",
        "Запам'ятай ключі: <b>nach</b> — міста/країни без артикля; <b>in</b> — країни з артиклем (die Schweiz, die USA, die Türkei) і всередину; <b>zu</b> — до людини або закладу.",
      ],
      table: {
        headers: ["Wohin?", "Wo?", "Woher?"],
        rows: [
          ["nach Berlin", "in Berlin", "aus Berlin"],
          ["in die Schweiz", "in der Schweiz", "aus der Schweiz"],
          ["zu Maria", "bei Maria", "von Maria"],
          ["zum Arzt", "beim Arzt", "vom Arzt"],
          ["auf den Markt", "auf dem Markt", "vom Markt"],
        ],
      },
      examples: [
        { de: "Ich fahre nach Wien.", uk: "Я їду до Відня." },
        { de: "Ich bin in Wien.", uk: "Я у Відні." },
        { de: "Wir fliegen in die USA.", uk: "Ми летимо до США." },
        { de: "Wir sind in den USA.", uk: "Ми у США." },
        { de: "Ich gehe zu Anna.", uk: "Я йду до Анни." },
        { de: "Ich bin bei Anna.", uk: "Я в Анни." },
        { de: "Ich komme aus der Ukraine.", uk: "Я з України." },
        { de: "Sie kommt vom Arzt.", uk: "Вона йде від лікаря." },
      ],
      tip: "Просте правило: <b>nach</b> — міста/країни <i>без</i> артикля, <b>in</b> + Akk. — країни <i>з</i> артиклем (die Schweiz, die Türkei, die USA, der Iran).",
      mistakes: [
        { wrong: "Ich fahre in Berlin.", right: "Ich fahre nach Berlin." },
        { wrong: "Ich fahre nach die Schweiz.", right: "Ich fahre in die Schweiz." },
        { wrong: "Ich gehe zu Markt.", right: "Ich gehe auf den Markt." },
      ],
      exercises: {},
      prevSlug: "temporale-praepositionen",
      nextSlug: "verschmelzungen",
    },
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "розрізняти Wohin / Wo / Woher",
        "правильно вибирати nach / in / zu / auf",
        "знати країни з артиклем (die Schweiz, die USA…)",
      ],
      ruleBox: {
        rule: "<b>nach</b> — місто/країна без артикля; <b>in</b> + Akk. — країна з артиклем або всередину; <b>zu</b> — людина/заклад.",
      },
      ukrainianTips: [
        "«До України» = <b>in die Ukraine</b> (бо <i>die Ukraine</i>); але «з України» = <b>aus der Ukraine</b>.",
        "«До бабусі» = <b>zu Oma</b>, а «у бабусі» = <b>bei Oma</b>.",
        "«Йти на ринок» = <b>auf den Markt gehen</b>.",
      ],
      languageComparison: {
        commons: ["Обидві мови розрізняють «куди / де / звідки»."],
        diffs: ["Німецька використовує різні прийменники, а не лише відмінок."],
        traps: ["Помилка: «in Berlin fahren» (правильно «nach Berlin fahren»)."],
      },
      summary: [
        "Wohin: nach / in+Akk / zu / auf+Akk.",
        "Wo: in+Dat / bei / auf+Dat.",
        "Woher: aus / von.",
        "Країни з артиклем → in + Akk.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich fahre ___ Berlin.", options: ["in","nach","zu","auf"], correct: 1 },
      { type: "mc", q: "Wir fliegen ___ Schweiz.", options: ["nach der","in die","zu der","auf die"], correct: 1 },
      { type: "mc", q: "Ich gehe ___ Anna.", options: ["nach","zu","in","bei"], correct: 1 },
      { type: "mc", q: "Ich komme ___ Ukraine.", options: ["aus der","von der","aus","von"], correct: 0 },
      { type: "mc", q: "Wir gehen ___ Markt.", options: ["zu dem","auf den","in den","nach dem"], correct: 1 },
      { type: "gap", q: "Ich bin ___ Anna. (у Анни)", answer: "bei" },
      { type: "gap", q: "Sie kommt ___ Arzt. (від лікаря, von+dem)", answer: "vom" },
      { type: "gap", q: "Wir fahren ___ Italien. (без артикля)", answer: "nach" },
      { type: "gap", q: "Ich wohne ___ Wien. (Wo?)", answer: "in" },
      { type: "tf", q: "«nach» уживається з країнами з артиклем.", correct: false },
      { type: "tf", q: "«Я з лікаря» = «vom Arzt».", correct: true },
      { type: "match", prompt: "Куди → прийменник:", pairs: [
        { left: "Berlin", right: "nach" },
        { left: "die Schweiz", right: "in (Akk.)" },
        { left: "Anna", right: "zu" },
        { left: "Markt", right: "auf (Akk.)" },
      ]},
      { type: "multi", q: "Які варіанти правильні?",
        options: ["nach Berlin","in Berlin (Wohin)","in die USA","zu Maria","nach die Schweiz"], correct: [0,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich fahre nach die Türkei.", correct: ["Ich fahre in die Türkei."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я їду до Швейцарії, а мій брат — до Берліна.",
        de: ["Ich fahre in die Schweiz, und mein Bruder fährt nach Berlin."] },
    ],
  },

  // ===================================================================
  verschmelzungen: {
    lesson: {
      slug: "verschmelzungen",
      level: "A2",
      category: CAT,
      titleDe: "Verschmelzungen (am, im, zum…)",
      titleUk: "Злиття прийменника з артиклем",
      goal: "Знати всі обов'язкові злиття прийменника з артиклем і вживати їх правильно.",
      explanation: [
        "Деякі прийменники зливаються з артиклем у <b>одну форму</b>. Це не скорочення — це норма мови.",
        "<b>Обов'язкові злиття</b>: <b>am</b> (an+dem), <b>im</b> (in+dem), <b>ans</b> (an+das), <b>ins</b> (in+das), <b>beim</b> (bei+dem), <b>vom</b> (von+dem), <b>zum</b> (zu+dem), <b>zur</b> (zu+der).",
        "Менш частотні, переважно розмовно: <b>aufs</b> (auf+das), <b>fürs</b> (für+das), <b>ums</b> (um+das), <b>durchs</b> (durch+das), <b>unterm/überm/hinterm/vorm</b> (розмовно).",
        "Якщо артикль наголошений (<i>«саме цей»</i>), злиття НЕ роблять: <i>«Ich gehe zu <b>dem</b> Arzt, den du empfohlen hast.»</i>",
      ],
      table: {
        headers: ["Повна форма", "Злиття", "Приклад"],
        rows: [
          ["an dem", "am", "am Tisch, am Montag"],
          ["in dem", "im", "im Park, im Mai"],
          ["an das", "ans", "ans Fenster"],
          ["in das", "ins", "ins Kino"],
          ["bei dem", "beim", "beim Arzt"],
          ["von dem", "vom", "vom Bahnhof"],
          ["zu dem", "zum", "zum Bahnhof"],
          ["zu der", "zur", "zur Schule"],
        ],
      },
      examples: [
        { de: "Ich gehe ins Kino.", uk: "Я йду в кіно." },
        { de: "Wir sind im Park.", uk: "Ми в парку." },
        { de: "Sie geht zur Arbeit.", uk: "Вона йде на роботу." },
        { de: "Ich komme vom Markt.", uk: "Я йду з ринку." },
        { de: "Am Montag arbeite ich.", uk: "У понеділок я працюю." },
        { de: "Setz dich ans Fenster!", uk: "Сядь біля вікна!" },
        { de: "Beim Essen sprechen wir nicht.", uk: "Під час їжі ми не говоримо." },
        { de: "Wir fahren zum Bahnhof.", uk: "Ми їдемо до вокзалу." },
      ],
      tip: "Запам'ятай 8 ключових злиттів — <b>am, im, ans, ins, beim, vom, zum, zur</b> — і твоя мова одразу звучить природно.",
      mistakes: [
        { wrong: "Ich gehe in das Kino. (без причини)", right: "Ich gehe ins Kino." },
        { wrong: "Ich komme von dem Markt.", right: "Ich komme vom Markt." },
        { wrong: "zu der Schule", right: "zur Schule" },
      ],
      exercises: {},
      prevSlug: "lokale-praepositionen",
      nextSlug: "praep-feste-wendungen",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "знати 8 обов'язкових злиттів",
        "не зливати, коли артикль наголошений",
        "автоматично вживати ins/im/am/zur/zum у мовленні",
      ],
      ruleBox: {
        rule: "<b>am · im · ans · ins · beim · vom · zum · zur</b> — стандартні злиття.",
      },
      ukrainianTips: [
        "Українською немає таких злиттів — це особливість німецької.",
        "<b>zur</b> — це <i>zu + der</i> (жіночий рід, Dativ).",
        "Розмовні форми типу <i>«aufm Tisch»</i> існують, але в письмі їх НЕ використовуй.",
      ],
      languageComparison: {
        commons: ["Прийменник + артикль є в обох мовах, але злиття — лише в німецькій."],
        diffs: ["В українській артикля немає, тож порівнювати немає що."],
        traps: ["Не злиття, коли потрібно підкреслити «саме цей»."],
      },
      summary: [
        "8 ключових злиттів: am, im, ans, ins, beim, vom, zum, zur.",
        "Це норма, а не скорочення.",
        "Не зливати при наголошеному артиклі.",
        "zum = zu+dem; zur = zu+der.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich gehe ___ Kino. (in+das)", options: ["in das","ins","im","ans"], correct: 1 },
      { type: "mc", q: "Wir sind ___ Park. (in+dem)", options: ["in dem","im","ins","am"], correct: 1 },
      { type: "mc", q: "Sie geht ___ Arbeit. (zu+der)", options: ["zu der","zum","zur","zu die"], correct: 2 },
      { type: "mc", q: "Ich komme ___ Markt. (von+dem)", options: ["von dem","vom","von der","beim"], correct: 1 },
      { type: "mc", q: "___ Montag arbeite ich.", options: ["An dem","Am","Im","Um"], correct: 1 },
      { type: "gap", q: "Setz dich ___ Fenster! (an+das)", answer: "ans" },
      { type: "gap", q: "Wir fahren ___ Bahnhof. (zu+dem)", answer: "zum" },
      { type: "gap", q: "___ Essen sprechen wir nicht. (bei+dem)", answer: "Beim" },
      { type: "gap", q: "Sie geht ___ Schule. (zu+der)", answer: "zur" },
      { type: "tf", q: "«im» = in+dem.", correct: true },
      { type: "tf", q: "«zur» = zu+das.", correct: false },
      { type: "match", prompt: "Злиття → повна форма:", pairs: [
        { left: "am", right: "an dem" },
        { left: "ins", right: "in das" },
        { left: "zum", right: "zu dem" },
        { left: "zur", right: "zu der" },
      ]},
      { type: "multi", q: "Які злиття стандартні (обов'язкові)?",
        options: ["am","im","aufm","beim","unterm","zum"], correct: [0,1,3,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich gehe zu der Schule.", correct: ["Ich gehe zur Schule."] },
      { type: "translate", prompt: "Переклади:",
        uk: "У понеділок я йду до лікаря, а потім у кіно.",
        de: ["Am Montag gehe ich zum Arzt und dann ins Kino."] },
    ],
  },

  // ===================================================================
  "praep-feste-wendungen": {
    lesson: {
      slug: "praep-feste-wendungen",
      level: "A2",
      category: CAT,
      titleDe: "Feste Wendungen mit Präpositionen",
      titleUk: "Сталі вирази з прийменниками",
      goal: "Запам'ятати найчастіші сталі вирази з прийменниками для повсякденного спілкування.",
      explanation: [
        "Сталі вирази треба <b>заучувати цілісно</b> — у них прийменник вибирати не за правилом.",
        "Транспорт: <b>mit dem Auto / Bus / Zug / Fahrrad / Flugzeug</b>, але <b>zu Fuß</b> (без артикля!).",
        "Час: <b>am Wochenende, in der Nacht, am Abend, um Mitternacht, im Urlaub</b>.",
        "Місце: <b>zu Hause</b> (де?) — <b>nach Hause</b> (куди?); <b>auf der Arbeit</b> (де), <b>zur Arbeit</b> (куди); <b>in die Stadt / in der Stadt</b>.",
        "Діяльність: <b>auf Deutsch sprechen, ins Bett gehen, beim Frühstück, am Telefon, im Internet, an der Universität studieren</b>.",
      ],
      table: {
        headers: ["Тема", "Вираз", "Переклад"],
        rows: [
          ["транспорт", "mit dem Bus / zu Fuß", "автобусом / пішки"],
          ["дім", "zu Hause / nach Hause", "вдома / додому"],
          ["робота", "auf der Arbeit / zur Arbeit", "на роботі / на роботу"],
          ["час", "am Wochenende / in der Nacht", "на вихідних / уночі"],
          ["мова", "auf Deutsch / auf Englisch", "німецькою / англійською"],
          ["навчання", "an der Uni / in der Schule", "в універі / у школі"],
        ],
      },
      examples: [
        { de: "Ich fahre mit dem Bus zur Arbeit.", uk: "Я їду автобусом на роботу." },
        { de: "Am Wochenende gehe ich zu Fuß.", uk: "На вихідних я ходжу пішки." },
        { de: "Ich bin zu Hause.", uk: "Я вдома." },
        { de: "Ich gehe nach Hause.", uk: "Я йду додому." },
        { de: "Wir sprechen auf Deutsch.", uk: "Ми говоримо німецькою." },
        { de: "In der Nacht schlafe ich tief.", uk: "Уночі я міцно сплю." },
        { de: "Ich studiere an der Universität Wien.", uk: "Я навчаюсь у Віденському університеті." },
        { de: "Beim Frühstück lese ich die Nachrichten.", uk: "За сніданком я читаю новини." },
      ],
      tip: "Найважча пара: <b>zu Hause</b> (де?) ↔ <b>nach Hause</b> (куди?). <i>«Ich bin <b>zu</b> Hause» / «Ich gehe <b>nach</b> Hause»</i>.",
      mistakes: [
        { wrong: "in Fuß", right: "zu Fuß" },
        { wrong: "Ich gehe zu Hause. (куди?)", right: "Ich gehe nach Hause." },
        { wrong: "in Deutsch sprechen", right: "auf Deutsch sprechen" },
      ],
      exercises: {},
      prevSlug: "verschmelzungen",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "знати ТОП-15 сталих виразів",
        "не плутати zu Hause / nach Hause",
        "автоматично казати mit dem Bus, zu Fuß, auf Deutsch",
      ],
      ruleBox: {
        rule: "Сталі вирази — заучуй цілісно: <i>zu Fuß, zu Hause, nach Hause, mit dem Bus, auf Deutsch, am Wochenende</i>.",
      },
      ukrainianTips: [
        "«Пішки» = <b>zu Fuß</b> (без артикля).",
        "«Додому» = <b>nach Hause</b>, «вдома» = <b>zu Hause</b>.",
        "«Німецькою» = <b>auf Deutsch</b>, а не <i>in Deutsch</i>.",
      ],
      languageComparison: {
        commons: ["В обох мовах є сталі вирази, які не перекладаються дослівно."],
        diffs: ["В українській «вдома/додому» — одне коріння; у німецькій — різні прийменники."],
        traps: ["Помилка: дослівний переклад «in Deutsch»."],
      },
      summary: [
        "Транспорт: mit dem + Dat. / zu Fuß.",
        "Дім: zu Hause (де) / nach Hause (куди).",
        "Мова: auf + Sprache.",
        "Час: am Wochenende, in der Nacht.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich fahre ___ Bus.", options: ["mit dem","mit der","mit","zu"], correct: 0 },
      { type: "mc", q: "Ich gehe ___ Fuß.", options: ["mit","zu","in","auf"], correct: 1 },
      { type: "mc", q: "Ich bin ___ Hause.", options: ["nach","zu","in","bei"], correct: 1 },
      { type: "mc", q: "Ich gehe ___ Hause.", options: ["zu","nach","in","auf"], correct: 1 },
      { type: "mc", q: "Wir sprechen ___ Deutsch.", options: ["in","mit","auf","an"], correct: 2 },
      { type: "gap", q: "___ Wochenende schlafe ich lange.", answer: "Am" },
      { type: "gap", q: "Ich fahre ___ Auto zur Arbeit.", answer: "mit dem" },
      { type: "gap", q: "___ Nacht ist es still.", answer: "In der" },
      { type: "gap", q: "Ich studiere ___ Universität.", answer: "an der" },
      { type: "tf", q: "«zu Fuß» — це сталий вираз без артикля.", correct: true },
      { type: "tf", q: "«Я йду додому» = «Ich gehe zu Hause».", correct: false },
      { type: "match", prompt: "Вираз → переклад:", pairs: [
        { left: "zu Hause", right: "вдома" },
        { left: "nach Hause", right: "додому" },
        { left: "auf Deutsch", right: "німецькою" },
        { left: "zu Fuß", right: "пішки" },
      ]},
      { type: "multi", q: "Які вирази правильні?",
        options: ["mit dem Bus","zu Fuß","in Deutsch","am Wochenende","zu Hause gehen"], correct: [0,1,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich gehe zu Hause.", correct: ["Ich gehe nach Hause."] },
      { type: "translate", prompt: "Переклади:",
        uk: "На вихідних я їду автобусом додому.",
        de: ["Am Wochenende fahre ich mit dem Bus nach Hause."] },
    ],
  },
};
