// A2 · Будова речення — 8 повних уроків.
import type { A2Map } from "./_helpers";

const CAT = "Будова речення";

export const satzbauA2: A2Map = {
  // ===================================================================
  "satz-grundregel": {
    lesson: {
      slug: "satz-grundregel",
      level: "A2",
      category: CAT,
      titleDe: "Verb auf Position 2",
      titleUk: "Дієслово завжди на 2-му місці",
      goal: "Засвоїти головне правило німецького розповідного речення: фінітне дієслово стоїть на 2-й позиції.",
      explanation: [
        "У <b>розповідному реченні</b> фінітне (особове) дієслово завжди стоїть на <b>2-й позиції</b>, що б не стояло на 1-й.",
        "Позиція 1 — це <b>один елемент</b>: підмет, обставина часу/місця або інша частина.",
        "Якщо ти ставиш на 1-шу позицію не підмет, то підмет іде <b>відразу після дієслова</b> (інверсія).",
        "Приклади:<br>1. <i>Ich</i> | <b>fahre</b> | morgen nach Berlin.<br>2. <i>Morgen</i> | <b>fahre</b> | <i>ich</i> nach Berlin.<br>3. <i>Nach Berlin</i> | <b>fahre</b> | <i>ich</i> morgen.",
      ],
      table: {
        headers: ["Pos. 1", "Pos. 2 (Verb)", "Решта"],
        rows: [
          ["Ich", "lerne", "heute Deutsch."],
          ["Heute", "lerne", "ich Deutsch."],
          ["Deutsch", "lerne", "ich heute."],
          ["In der Schule", "lerne", "ich Deutsch."],
        ],
      },
      examples: [
        { de: "Ich trinke morgens Kaffee.", uk: "Я п'ю вранці каву." },
        { de: "Morgens trinke ich Kaffee.", uk: "Вранці я п'ю каву." },
        { de: "Kaffee trinke ich morgens.", uk: "Каву я п'ю вранці." },
        { de: "Am Wochenende bleibe ich zu Hause.", uk: "На вихідних я залишаюсь удома." },
        { de: "Heute Abend gehen wir ins Kino.", uk: "Сьогодні ввечері ми йдемо в кіно." },
        { de: "Im Sommer fahren wir nach Italien.", uk: "Влітку ми їдемо в Італію." },
        { de: "Mit dem Bus komme ich schneller.", uk: "Автобусом я доберусь швидше." },
        { de: "Leider kann ich nicht kommen.", uk: "На жаль, я не можу прийти." },
      ],
      tip: "Правило «Verb-2» — святе. Якщо обставина займає 1-шу позицію, підмет «стрибає» за дієслово. Це називається <b>інверсія</b>.",
      mistakes: [
        { wrong: "Morgen ich fahre nach Berlin.", right: "Morgen fahre ich nach Berlin." },
        { wrong: "Heute Abend wir gehen ins Kino.", right: "Heute Abend gehen wir ins Kino." },
        { wrong: "Leider ich kann nicht kommen.", right: "Leider kann ich nicht kommen." },
      ],
      exercises: {},
      nextSlug: "satz-fragen",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "автоматично ставити дієслово на 2-гу позицію",
        "робити інверсію після обставини",
        "розуміти, що Pos. 1 — це один елемент, а не одне слово",
      ],
      ruleBox: {
        rule: "<b>Verb-2:</b> фінітне дієслово завжди на 2-й позиції. Підмет — або на 1-й, або відразу після дієслова.",
      },
      ukrainianTips: [
        "Українське «Завтра я їду…» = німецьке <b>«Morgen fahre ich…»</b> — порядок змінюється!",
        "Pos. 1 може бути цілою фразою: <i>«Am nächsten Montag fahre ich…»</i>",
        "Після «leider, vielleicht, hoffentlich, deshalb, dann» теж робиться інверсія.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають вільний порядок щодо обставин."],
        diffs: ["У німецькій дієслово прибите до 2-ї позиції; в українській — вільне."],
        traps: ["Найчастіша помилка — поставити підмет після обставини, без інверсії."],
      },
      summary: [
        "Verb-2 — фінітне дієслово завжди на 2-му місці.",
        "Pos. 1 — один елемент (слово або фраза).",
        "Не підмет на Pos. 1 → інверсія.",
        "leider, heute, deshalb… теж тягнуть інверсію.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Який порядок правильний?",
        options: ["Morgen ich fahre nach Wien.","Morgen fahre ich nach Wien.","Ich morgen fahre nach Wien.","Fahre morgen ich nach Wien."], correct: 1 },
      { type: "mc", q: "Heute Abend ___ wir ins Kino.",
        options: ["wir gehen","gehen","gehen wir","wir gehen wir"], correct: 2 },
      { type: "mc", q: "Leider ___ ich nicht kommen.",
        options: ["ich kann","kann","kann ich","ich kann ich"], correct: 2 },
      { type: "mc", q: "Im Sommer ___ wir nach Italien.",
        options: ["wir fahren","fahren wir","fahren","fahre wir"], correct: 1 },
      { type: "mc", q: "На якій позиції стоїть фінітне дієслово в розповідному реченні?",
        options: ["1","2","останній","перед підметом"], correct: 1 },
      { type: "gap", q: "Morgen ___ ich nach Berlin. (fahren)", answer: "fahre" },
      { type: "gap", q: "Am Wochenende ___ wir lange. (schlafen)", answer: "schlafen" },
      { type: "gap", q: "Deutsch ___ ich seit zwei Jahren. (lernen)", answer: "lerne" },
      { type: "gap", q: "Leider ___ ich keine Zeit. (haben)", answer: "habe" },
      { type: "tf", q: "Якщо речення починається з обставини, підмет іде перед дієсловом.", correct: false },
      { type: "tf", q: "Pos. 1 може бути цілою фразою з кількох слів.", correct: true },
      { type: "match", prompt: "Початок → продовження:", pairs: [
        { left: "Morgen", right: "fahre ich nach Berlin." },
        { left: "Ich", right: "fahre morgen nach Berlin." },
        { left: "Leider", right: "kann ich nicht kommen." },
        { left: "Im Mai", right: "haben wir Urlaub." },
      ]},
      { type: "multi", q: "Які речення правильні?",
        options: ["Heute ich lerne Deutsch.","Heute lerne ich Deutsch.","Ich lerne heute Deutsch.","Lerne heute ich Deutsch."], correct: [1,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Morgen ich gehe ins Kino.", correct: ["Morgen gehe ich ins Kino."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Сьогодні ввечері я залишаюсь удома.",
        de: ["Heute Abend bleibe ich zu Hause.","Ich bleibe heute Abend zu Hause."] },
    ],
  },

  // ===================================================================
  "satz-fragen": {
    lesson: {
      slug: "satz-fragen",
      level: "A2",
      category: CAT,
      titleDe: "Fragesätze (W-Fragen & Ja/Nein-Fragen)",
      titleUk: "Питальні речення",
      goal: "Будувати W-питання й Ja/Nein-питання з правильним порядком слів.",
      explanation: [
        "<b>W-питання</b>: питальне слово на 1-й позиції, дієслово — на 2-й, підмет — на 3-й.<br><i>Wann | <b>kommst</b> | du?</i>",
        "<b>Ja/Nein-питання</b>: дієслово стрибає на 1-шу позицію, підмет іде на 2-гу.<br><i><b>Kommst</b> | du | morgen?</i>",
        "Найважливіші W-слова: <b>Wer? Was? Wann? Wo? Wohin? Woher? Wie? Warum? Wie viel(e)? Welcher/welche/welches? Wessen?</b>",
        "Питальне слово може бути <b>фразою</b>: <i>«Um wie viel Uhr kommst du?»</i> — але дієслово все одно на 2-й.",
      ],
      table: {
        headers: ["Тип", "Pos. 1", "Pos. 2 (Verb)", "Pos. 3+"],
        rows: [
          ["W-Frage", "Wann", "kommst", "du?"],
          ["W-Frage", "Wo", "wohnst", "du?"],
          ["W-Frage", "Warum", "lernst", "du Deutsch?"],
          ["Ja/Nein", "—", "Kommst", "du morgen?"],
          ["Ja/Nein", "—", "Hast", "du Zeit?"],
        ],
      },
      examples: [
        { de: "Wie heißt du?", uk: "Як тебе звати?" },
        { de: "Wo wohnst du?", uk: "Де ти живеш?" },
        { de: "Wann beginnt der Kurs?", uk: "Коли починається курс?" },
        { de: "Warum lernst du Deutsch?", uk: "Чому ти вивчаєш німецьку?" },
        { de: "Hast du morgen Zeit?", uk: "У тебе є завтра час?" },
        { de: "Kommst du mit?", uk: "Підеш зі мною?" },
        { de: "Wie viel kostet das Buch?", uk: "Скільки коштує книга?" },
        { de: "Welche Farbe magst du?", uk: "Який колір тобі подобається?" },
      ],
      tip: "Просте правило: <b>W-Frage → Verb-2; Ja/Nein-Frage → Verb-1</b>. Інтонація в Ja/Nein-питанні підвищується в кінці.",
      mistakes: [
        { wrong: "Wo du wohnst?", right: "Wo wohnst du?" },
        { wrong: "Du hast Zeit? (як питання)", right: "Hast du Zeit?" },
        { wrong: "Warum du Deutsch lernst?", right: "Warum lernst du Deutsch?" },
      ],
      exercises: {},
      prevSlug: "satz-grundregel",
      nextSlug: "satz-tekamolo",
    },
    extras: {
      duration: 13,
      premium: false,
      learningGoals: [
        "знати ТОП-10 W-слів",
        "будувати W-Frage з Verb-2",
        "будувати Ja/Nein-Frage з Verb-1",
      ],
      ruleBox: {
        rule: "<b>W-Frage:</b> W-Wort + Verb + Subjekt. <b>Ja/Nein-Frage:</b> Verb + Subjekt + …",
      },
      ukrainianTips: [
        "В українській питання робиться інтонацією; у німецькій — порядком слів.",
        "<b>Wo?</b> — де (місце); <b>Wohin?</b> — куди; <b>Woher?</b> — звідки.",
        "Після Ja/Nein-питання відповідають <b>ja / nein / doch</b>. <i>«Doch»</i> — якщо питання заперечне: <i>«Hast du keine Zeit?» → «Doch!»</i>",
      ],
      languageComparison: {
        commons: ["Питальне слово в обох мовах на початку."],
        diffs: ["Німецька жорстко вимагає порядок V-S."],
        traps: ["Помилка: робити питання як в українській, тільки з інтонацією."],
      },
      summary: [
        "W-Frage: W-Wort + V + S.",
        "Ja/Nein: V + S.",
        "doch — у відповідь на заперечне питання.",
        "Питальне слово може бути фразою.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Як правильно?",
        options: ["Wo du wohnst?","Wo wohnst du?","Du wo wohnst?","Wohnst wo du?"], correct: 1 },
      { type: "mc", q: "Як спитати «У тебе є час?»",
        options: ["Du hast Zeit?","Hast du Zeit?","Zeit du hast?","Hast Zeit du?"], correct: 1 },
      { type: "mc", q: "___ kommst du?",
        options: ["Wer","Wann","Wo","Wie viel"], correct: 1 },
      { type: "mc", q: "___ heißt du?",
        options: ["Wie","Was","Wer","Warum"], correct: 0 },
      { type: "mc", q: "Відповідь «Doch!» вживається на яке питання?",
        options: ["Hast du Zeit?","Hast du keine Zeit?","Wo bist du?","Wer ist das?"], correct: 1 },
      { type: "gap", q: "___ wohnst du? (де)", answer: "Wo" },
      { type: "gap", q: "___ kommst du? (звідки)", answer: "Woher" },
      { type: "gap", q: "___ lernst du Deutsch? (чому)", answer: "Warum" },
      { type: "gap", q: "___ kostet das? (скільки)", answer: "Wie viel" },
      { type: "tf", q: "У Ja/Nein-питанні дієслово стоїть на 1-й позиції.", correct: true },
      { type: "tf", q: "У W-питанні підмет стоїть перед дієсловом.", correct: false },
      { type: "match", prompt: "W-слово → значення:", pairs: [
        { left: "Wer?", right: "Хто?" },
        { left: "Was?", right: "Що?" },
        { left: "Wann?", right: "Коли?" },
        { left: "Warum?", right: "Чому?" },
      ]},
      { type: "multi", q: "Які речення — правильні питання?",
        options: ["Hast du Zeit?","Du hast Zeit?","Wo wohnst du?","Wo du wohnst?"], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Warum du Deutsch lernst?", correct: ["Warum lernst du Deutsch?"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Коли починається курс?",
        de: ["Wann beginnt der Kurs?"] },
    ],
  },

  // ===================================================================
  "satz-tekamolo": {
    lesson: {
      slug: "satz-tekamolo",
      level: "A2",
      category: CAT,
      titleDe: "Te-Ka-Mo-Lo",
      titleUk: "Порядок обставин: Te-Ka-Mo-Lo",
      goal: "Правильно розташовувати кілька обставин у реченні за порядком Temporal–Kausal–Modal–Lokal.",
      explanation: [
        "Якщо в реченні кілька обставин, їх ставлять у порядку <b>Te-Ka-Mo-Lo</b>: <b>Temporal (коли) → Kausal (чому) → Modal (як) → Lokal (де/куди)</b>.",
        "<i>Ich fahre <b>morgen</b> (Te) <b>wegen der Arbeit</b> (Ka) <b>mit dem Zug</b> (Mo) <b>nach Berlin</b> (Lo).</i>",
        "Правило діє в <b>середньому полі</b> — між дієсловом і кінцем речення.",
        "Будь-яку обставину можна <b>винести на 1-шу позицію</b> для підкреслення (тоді інверсія).",
      ],
      table: {
        headers: ["Te", "Ka", "Mo", "Lo"],
        rows: [
          ["morgen", "wegen der Arbeit", "mit dem Zug", "nach Berlin"],
          ["am Abend", "aus Müdigkeit", "schnell", "ins Bett"],
          ["heute", "—", "zu Fuß", "in die Schule"],
        ],
      },
      examples: [
        { de: "Ich gehe heute zu Fuß in die Schule.", uk: "Я йду сьогодні пішки до школи." },
        { de: "Wir fahren morgen mit dem Auto nach Wien.", uk: "Ми їдемо завтра машиною до Відня." },
        { de: "Er kommt am Abend müde nach Hause.", uk: "Він приходить увечері втомлений додому." },
        { de: "Sie arbeitet seit Januar wegen des Geldes hart in einer Firma.", uk: "Вона працює з січня заради грошей наполегливо у фірмі." },
        { de: "Ich fahre wegen des Wetters langsam.", uk: "Я їду через погоду повільно." },
        { de: "Wir essen heute zu Hause.", uk: "Ми їмо сьогодні вдома." },
        { de: "Morgen fahre ich mit dem Bus zur Arbeit.", uk: "Завтра я їду автобусом на роботу." },
        { de: "Aus Müdigkeit gehe ich früh ins Bett.", uk: "Від втоми я рано йду спати." },
      ],
      tip: "Запам'ятай: <b>Te-Ka-Mo-Lo</b> = «Тебе кохаю молоко» (жарт). Послідовність: <i>коли → чому → як → де</i>.",
      mistakes: [
        { wrong: "Ich fahre nach Berlin morgen.", right: "Ich fahre morgen nach Berlin." },
        { wrong: "Wir gehen in die Schule heute zu Fuß.", right: "Wir gehen heute zu Fuß in die Schule." },
        { wrong: "Er kommt müde am Abend nach Hause.", right: "Er kommt am Abend müde nach Hause." },
      ],
      exercises: {},
      prevSlug: "satz-fragen",
      nextSlug: "satz-negation",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "знати порядок Te-Ka-Mo-Lo",
        "ставити час перед місцем",
        "виносити обставину на 1-шу позицію",
      ],
      ruleBox: {
        rule: "<b>Te → Ka → Mo → Lo</b>: коли → чому → як → де/куди.",
      },
      ukrainianTips: [
        "В українській порядок вільний; у німецькій Te-Ka-Mo-Lo допомагає звучати природно.",
        "Місце <b>завжди в кінці</b>, навіть якщо короткі обставини.",
        "Виносячи обставину на Pos. 1, не забудь інверсію.",
      ],
      languageComparison: {
        commons: ["В обох мовах обставини можна переставляти."],
        diffs: ["Німецька має сувору рекомендацію Te-Ka-Mo-Lo."],
        traps: ["Помилка: ставити «nach Berlin» перед «morgen»."],
      },
      summary: [
        "Te = коли (heute, morgen…).",
        "Ka = чому (wegen…, aus…).",
        "Mo = як (mit dem Bus, schnell…).",
        "Lo = де/куди (nach Berlin, ins Bett).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Який порядок правильний?",
        options: [
          "Ich fahre nach Berlin morgen mit dem Zug.",
          "Ich fahre morgen mit dem Zug nach Berlin.",
          "Ich fahre mit dem Zug morgen nach Berlin.",
          "Ich morgen fahre nach Berlin mit dem Zug."
        ], correct: 1 },
      { type: "mc", q: "Що йде в Te-Ka-Mo-Lo після «Ka»?",
        options: ["Te","Mo","Lo","Verb"], correct: 1 },
      { type: "mc", q: "Куди ставиться «nach Hause»?",
        options: ["на початок","після дієслова","в кінці (Lo)","перед часом"], correct: 2 },
      { type: "mc", q: "Який порядок правильний?",
        options: [
          "Er kommt müde am Abend nach Hause.",
          "Er kommt am Abend müde nach Hause.",
          "Er kommt nach Hause am Abend müde.",
          "Am Abend er kommt müde nach Hause."
        ], correct: 1 },
      { type: "gap", q: "Ich fahre ___ ___ ___ ___. (morgen / mit dem Bus / nach Wien) — заповни перший: ", answer: "morgen" },
      { type: "gap", q: "У Te-Ka-Mo-Lo Lo = ___?", answer: "Lokal" },
      { type: "gap", q: "У Te-Ka-Mo-Lo Te = ___?", answer: "Temporal" },
      { type: "gap", q: "Wir gehen heute ___ ___ in die Schule. (Mo: пішки)", answer: "zu Fuß" },
      { type: "tf", q: "У німецькій місце ставлять перед часом.", correct: false },
      { type: "tf", q: "Te-Ka-Mo-Lo діє в середньому полі речення.", correct: true },
      { type: "match", prompt: "Обставина → тип:", pairs: [
        { left: "morgen", right: "Temporal" },
        { left: "wegen des Wetters", right: "Kausal" },
        { left: "mit dem Bus", right: "Modal" },
        { left: "nach Berlin", right: "Lokal" },
      ]},
      { type: "multi", q: "Які речення дотримуються Te-Ka-Mo-Lo?",
        options: [
          "Ich fahre morgen mit dem Auto nach Wien.",
          "Ich fahre nach Wien morgen mit dem Auto.",
          "Wir gehen heute zu Fuß in die Schule.",
          "Wir gehen in die Schule heute zu Fuß."
        ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich fahre nach Berlin morgen.", correct: ["Ich fahre morgen nach Berlin."] },
      { type: "translate", prompt: "Переклади (з Te-Ka-Mo-Lo):",
        uk: "Завтра я їду автобусом на роботу.",
        de: ["Morgen fahre ich mit dem Bus zur Arbeit.","Ich fahre morgen mit dem Bus zur Arbeit."] },
      { type: "writeFree", prompt: "1 речення з усіма 4 обставинами (Te, Ka, Mo, Lo).",
        sample: "Ich fahre morgen wegen der Arbeit mit dem Zug nach Berlin." },
    ],
  },

  // ===================================================================
  "satz-negation": {
    lesson: {
      slug: "satz-negation",
      level: "A2",
      category: CAT,
      titleDe: "Negation: nicht & kein",
      titleUk: "Заперечення: nicht і kein",
      goal: "Правильно вибирати між <b>nicht</b> і <b>kein</b> і ставити їх у правильному місці.",
      explanation: [
        "<b>kein</b> заперечує <b>іменник з неозначеним артиклем або без артикля</b>: <i>ein Buch → kein Buch; Milch → keine Milch</i>.",
        "<b>nicht</b> — у всіх інших випадках: заперечує дієслово, прикметник, прислівник або іменник з означеним артиклем/займенником.",
        "<b>Місце nicht</b>:<br>• перед прикметником/прислівником: <i>Das ist <b>nicht</b> teuer.</i><br>• перед другим дієсловом (Inf./Part. II) / відокремлюваним префіксом: <i>Ich kann <b>nicht</b> kommen.</i><br>• перед іменником з означеним артиклем: <i>Ich kenne <b>nicht</b> den Mann dort.</i><br>• у кінці, якщо заперечує дієслово взагалі: <i>Ich arbeite heute <b>nicht</b>.</i>",
        "<b>kein</b> відмінюється як <b>ein</b>: kein/keine/kein, keinen/keine/kein, keinem/keiner/keinem, keiner/keiner/keiner (мн. keine/keinen).",
      ],
      table: {
        headers: ["Питання", "Заперечення", "Приклад"],
        rows: [
          ["Іменник з ein/без артикля", "kein", "Ich habe kein Auto."],
          ["Іменник з der/die/das", "nicht", "Ich kenne den Mann nicht."],
          ["Дієслово", "nicht (часто в кінці)", "Ich komme heute nicht."],
          ["Прикметник/прислівник", "nicht (перед ним)", "Das ist nicht teuer."],
        ],
      },
      examples: [
        { de: "Ich habe kein Geld.", uk: "У мене немає грошей." },
        { de: "Sie trinkt keinen Kaffee.", uk: "Вона не п'є каву." },
        { de: "Ich kenne den Film nicht.", uk: "Я не знаю цей фільм." },
        { de: "Das Essen ist nicht gut.", uk: "Їжа не смачна." },
        { de: "Ich komme heute nicht.", uk: "Я сьогодні не прийду." },
        { de: "Er kann nicht schwimmen.", uk: "Він не вміє плавати." },
        { de: "Wir haben keine Zeit.", uk: "У нас немає часу." },
        { de: "Ich gehe nicht ins Kino.", uk: "Я не йду в кіно." },
      ],
      tip: "Просте правило: <b>є артикль ein / нема артикля → kein; усе інше → nicht</b>.",
      mistakes: [
        { wrong: "Ich habe nicht Geld.", right: "Ich habe kein Geld." },
        { wrong: "Ich kenne kein den Mann.", right: "Ich kenne den Mann nicht." },
        { wrong: "Ich komme nicht heute.", right: "Ich komme heute nicht." },
      ],
      exercises: {},
      prevSlug: "satz-tekamolo",
      nextSlug: "satz-konjunktionen",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "обирати між nicht і kein",
        "правильно ставити nicht",
        "відмінювати kein як ein",
      ],
      ruleBox: {
        rule: "<b>kein</b> = ein/без артикля; <b>nicht</b> = усе інше. nicht зазвичай у <b>кінці</b> або перед тим, що заперечуєш.",
      },
      ukrainianTips: [
        "Українське «немає» = <b>kein/keine</b>: «у мене немає машини» = <i>Ich habe kein Auto</i>.",
        "Українське «не» перед дієсловом = німецьке <b>nicht</b> у кінці.",
        "<b>nicht</b> завжди перед прикметником/прислівником: <i>nicht teuer, nicht oft</i>.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають окреме слово для «немає» (kein)."],
        diffs: ["Місце «nicht» — у кінці, на відміну від укр. «не» перед дієсловом."],
        traps: ["Помилка: «Ich nicht arbeite heute» — правильно «Ich arbeite heute nicht»."],
      },
      summary: [
        "kein — для іменників з ein або без артикля.",
        "nicht — для всього іншого.",
        "nicht часто в кінці речення.",
        "nicht перед прикметником/прислівником.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich habe ___ Auto.",
        options: ["nicht","kein","keinen","keine"], correct: 1 },
      { type: "mc", q: "Sie trinkt ___ Kaffee.",
        options: ["kein","keinen","keine","nicht"], correct: 1 },
      { type: "mc", q: "Ich kenne den Mann ___.",
        options: ["kein","nicht","keinen","keine"], correct: 1 },
      { type: "mc", q: "Das Essen ist ___ gut.",
        options: ["kein","keine","nicht","keinen"], correct: 2 },
      { type: "mc", q: "Wir haben ___ Zeit.",
        options: ["kein","keinen","keine","nicht"], correct: 2 },
      { type: "gap", q: "Ich habe ___ Geld. (заперечення)", answer: "kein" },
      { type: "gap", q: "Er kommt heute ___.", answer: "nicht" },
      { type: "gap", q: "Das ist ___ teuer. (запереч. прикм.)", answer: "nicht" },
      { type: "gap", q: "Sie hat ___ Bruder. (запереч.)", answer: "keinen" },
      { type: "tf", q: "Перед іменником з der/die/das пишемо «kein».", correct: false },
      { type: "tf", q: "nicht зазвичай стоїть у кінці речення.", correct: true },
      { type: "match", prompt: "Ситуація → заперечення:", pairs: [
        { left: "ein Buch", right: "kein Buch" },
        { left: "Milch", right: "keine Milch" },
        { left: "der Mann", right: "den Mann nicht" },
        { left: "arbeiten", right: "nicht arbeiten" },
      ]},
      { type: "multi", q: "Які речення правильні?",
        options: ["Ich habe kein Geld.","Ich habe nicht Geld.","Ich komme heute nicht.","Ich nicht komme heute."], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe nicht Zeit.", correct: ["Ich habe keine Zeit."] },
      { type: "translate", prompt: "Переклади:",
        uk: "У мене немає грошей, і я не йду в кіно.",
        de: ["Ich habe kein Geld und ich gehe nicht ins Kino.","Ich habe kein Geld, und ich gehe nicht ins Kino."] },
    ],
  },

  // ===================================================================
  "satz-konjunktionen": {
    lesson: {
      slug: "satz-konjunktionen",
      level: "A2",
      category: CAT,
      titleDe: "Hauptsatz-Konjunktionen (und, aber, oder, denn, sondern)",
      titleUk: "Сурядні сполучники: und, aber, oder, denn, sondern",
      goal: "З'єднувати два головні речення без зміни порядку слів.",
      explanation: [
        "<b>Сурядні сполучники</b> <i>und, aber, oder, denn, sondern</i> з'єднують <b>два головні речення</b>. Порядок слів <b>НЕ змінюється</b> — дієслово залишається на 2-й позиції.",
        "Мнемоніка: <b>«ADUSO»</b> = aber, denn, und, sondern, oder.",
        "<b>und</b> = і; <b>aber</b> = але; <b>oder</b> = або; <b>denn</b> = бо (причина); <b>sondern</b> = а (після заперечення).",
        "Перед <b>aber, denn, sondern</b> зазвичай ставлять <b>кому</b>. Перед <b>und, oder</b> кома не обов'язкова.",
      ],
      table: {
        headers: ["Сполучник", "Значення", "Приклад"],
        rows: [
          ["und", "і", "Ich lerne Deutsch und ich arbeite."],
          ["aber", "але", "Ich lerne Deutsch, aber es ist schwer."],
          ["oder", "або", "Trinkst du Tee oder trinkst du Kaffee?"],
          ["denn", "бо (причина)", "Ich bleibe zu Hause, denn ich bin krank."],
          ["sondern", "а (після не…)", "Das ist nicht Tee, sondern Kaffee."],
        ],
      },
      examples: [
        { de: "Ich lerne Deutsch und ich höre Musik.", uk: "Я вчу німецьку і слухаю музику." },
        { de: "Ich möchte kommen, aber ich habe keine Zeit.", uk: "Я хочу прийти, але не маю часу." },
        { de: "Möchtest du Tee oder Kaffee?", uk: "Ти хочеш чай чи каву?" },
        { de: "Ich bleibe zu Hause, denn ich bin müde.", uk: "Я залишаюсь удома, бо я втомлений(на)." },
        { de: "Er ist kein Lehrer, sondern Arzt.", uk: "Він не вчитель, а лікар." },
        { de: "Wir essen Pizza und trinken Cola.", uk: "Ми їмо піцу і п'ємо колу." },
        { de: "Anna lernt fleißig, aber sie ist müde.", uk: "Анна старанно вчиться, але вона втомлена." },
        { de: "Ich gehe heute nicht ins Kino, sondern ins Theater.", uk: "Я йду сьогодні не в кіно, а в театр." },
      ],
      tip: "<b>sondern vs aber</b>: <b>sondern</b> уживають тільки <i>після заперечення</i> (nicht/kein) і означає протиставлення. Інакше — <b>aber</b>.",
      mistakes: [
        { wrong: "Ich lerne Deutsch, und ich arbeite. (з зайвою комою)", right: "Ich lerne Deutsch und ich arbeite." },
        { wrong: "Das ist nicht Tee, aber Kaffee.", right: "Das ist nicht Tee, sondern Kaffee." },
        { wrong: "Ich bleibe zu Hause, denn bin ich krank.", right: "Ich bleibe zu Hause, denn ich bin krank." },
      ],
      exercises: {},
      prevSlug: "satz-negation",
      nextSlug: "satz-weil-dass",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "знати 5 ADUSO-сполучників",
        "не міняти порядок слів",
        "розрізняти sondern і aber",
      ],
      ruleBox: {
        rule: "<b>ADUSO</b> (aber, denn, und, sondern, oder) — порядок слів <b>не змінюється</b>.",
      },
      ukrainianTips: [
        "«А» після заперечення = <b>sondern</b>; «але» = <b>aber</b>.",
        "«Бо» = <b>denn</b> (порядок слів НЕ змінюється — на відміну від <i>weil</i>).",
        "<b>oder</b> = «або» (вибір), не плутай з «чи» в питанні.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають окремі сполучники для причини, протиставлення, вибору."],
        diffs: ["Німецька розрізняє denn (Hauptsatz) і weil (Nebensatz)."],
        traps: ["Помилка: вживати «aber» після заперечення замість «sondern»."],
      },
      summary: [
        "ADUSO: aber, denn, und, sondern, oder.",
        "Порядок слів не змінюється.",
        "sondern — лише після nicht/kein.",
        "denn = бо (V-2, не як weil).",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich lerne Deutsch ___ ich arbeite.",
        options: ["und","aber","denn","sondern"], correct: 0 },
      { type: "mc", q: "Ich möchte kommen, ___ ich habe keine Zeit.",
        options: ["und","aber","oder","sondern"], correct: 1 },
      { type: "mc", q: "Trinkst du Tee ___ Kaffee?",
        options: ["und","aber","oder","denn"], correct: 2 },
      { type: "mc", q: "Ich bleibe zu Hause, ___ ich bin krank.",
        options: ["aber","denn","oder","sondern"], correct: 1 },
      { type: "mc", q: "Das ist nicht Tee, ___ Kaffee.",
        options: ["aber","denn","oder","sondern"], correct: 3 },
      { type: "gap", q: "Er ist kein Lehrer, ___ Arzt.", answer: "sondern" },
      { type: "gap", q: "Ich lerne viel, ___ ich bin müde.", answer: "aber" },
      { type: "gap", q: "Ich bleibe zu Hause, ___ ich bin krank.", answer: "denn" },
      { type: "gap", q: "Möchtest du Wasser ___ Saft?", answer: "oder" },
      { type: "tf", q: "Після ADUSO-сполучників дієслово йде в кінець.", correct: false },
      { type: "tf", q: "«sondern» уживається лише після заперечення.", correct: true },
      { type: "match", prompt: "Сполучник → значення:", pairs: [
        { left: "und", right: "і" },
        { left: "aber", right: "але" },
        { left: "denn", right: "бо" },
        { left: "sondern", right: "а (після не)" },
      ]},
      { type: "multi", q: "Які сполучники належать до ADUSO?",
        options: ["und","weil","aber","dass","denn","oder","sondern"], correct: [0,2,4,5,6] },
      { type: "correct", prompt: "Виправ:", wrong: "Das ist nicht Tee, aber Kaffee.", correct: ["Das ist nicht Tee, sondern Kaffee."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я залишаюсь удома, бо я втомлений.",
        de: ["Ich bleibe zu Hause, denn ich bin müde."] },
    ],
  },

  // ===================================================================
  "satz-weil-dass": {
    lesson: {
      slug: "satz-weil-dass",
      level: "A2",
      category: CAT,
      titleDe: "Nebensatz mit weil & dass",
      titleUk: "Підрядне з weil і dass",
      goal: "Будувати підрядні речення з <b>weil</b> (бо) і <b>dass</b> (що) — дієслово в кінець!",
      explanation: [
        "<b>Підрядний сполучник</b> переносить фінітне дієслово <b>в кінець</b> підрядного речення.",
        "<b>weil</b> = бо (причина): <i>Ich bleibe zu Hause, <b>weil</b> ich krank <b>bin</b>.</i>",
        "<b>dass</b> = що: <i>Ich glaube, <b>dass</b> er morgen <b>kommt</b>.</i>",
        "Між головним і підрядним — <b>кома</b>.",
        "Якщо підрядне стоїть <b>на початку</b>, у головному діє Verb-2 і відбувається <b>інверсія</b>:<br><i>«<b>Weil</b> ich krank bin, <b>bleibe</b> ich zu Hause.»</i> — головне починається з дієслова.",
      ],
      table: {
        headers: ["Сполучник", "Значення", "Приклад"],
        rows: [
          ["weil", "бо (причина)", "…, weil ich müde bin."],
          ["dass", "що", "…, dass er kommt."],
          ["weil + Modalverb", "Modalverb у кінець", "…, weil ich nicht kommen kann."],
          ["dass + Perfekt", "haben/sein у кінець", "…, dass ich gelernt habe."],
        ],
      },
      examples: [
        { de: "Ich bleibe zu Hause, weil ich krank bin.", uk: "Я залишаюсь удома, бо я хворий(а)." },
        { de: "Ich lerne Deutsch, weil ich in Berlin arbeiten will.", uk: "Я вчу німецьку, бо хочу працювати в Берліні." },
        { de: "Ich glaube, dass er recht hat.", uk: "Я думаю, що він має рацію." },
        { de: "Es ist gut, dass du gekommen bist.", uk: "Це добре, що ти прийшов(ла)." },
        { de: "Sie sagt, dass sie keine Zeit hat.", uk: "Вона каже, що немає часу." },
        { de: "Weil es regnet, bleibe ich zu Hause.", uk: "Оскільки йде дощ, я залишаюсь удома." },
        { de: "Ich weiß, dass du Deutsch lernst.", uk: "Я знаю, що ти вчиш німецьку." },
        { de: "Wir essen jetzt, weil wir Hunger haben.", uk: "Ми їмо зараз, бо ми голодні." },
      ],
      tip: "Запам'ятай ритм підрядного: <b>«weil/dass + Subjekt + … + Verb»</b>. Дієслово завжди <b>в самому кінці</b>.",
      mistakes: [
        { wrong: "Ich bleibe zu Hause, weil ich bin krank.", right: "Ich bleibe zu Hause, weil ich krank bin." },
        { wrong: "Ich glaube, dass er kommt morgen.", right: "Ich glaube, dass er morgen kommt." },
        { wrong: "Weil ich krank bin, ich bleibe zu Hause.", right: "Weil ich krank bin, bleibe ich zu Hause." },
      ],
      exercises: {},
      prevSlug: "satz-konjunktionen",
      nextSlug: "satz-modalverben-position",
    },
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "ставити дієслово в кінець підрядного",
        "робити інверсію в головному після підрядного",
        "розрізняти denn (V-2) і weil (V-кінець)",
      ],
      ruleBox: {
        rule: "<b>weil / dass → Verb в кінець.</b> Між реченнями — кома. Підрядне на початку → інверсія в головному.",
      },
      ukrainianTips: [
        "Українське «бо я хворий» → німецьке «<b>weil ich krank bin</b>» (дієслово в кінець).",
        "<b>dass</b> ≠ <b>das</b> (артикль). Сполучник пишеться з подвійним «s».",
        "Якщо в підрядному є Modalverb або Perfekt, у кінець іде допоміжне/модальне.",
      ],
      languageComparison: {
        commons: ["В українській «бо» і «що» теж вводять підрядне."],
        diffs: ["У німецькій дієслово переходить у кінець підрядного."],
        traps: ["Помилка: залишити Verb-2 у підрядному."],
      },
      summary: [
        "weil = бо; dass = що.",
        "Verb у кінець підрядного.",
        "Кома між реченнями.",
        "Підрядне на початку → інверсія в головному.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Як правильно?",
        options: [
          "Ich bleibe zu Hause, weil ich bin krank.",
          "Ich bleibe zu Hause, weil ich krank bin.",
          "Ich bleibe zu Hause, weil krank ich bin.",
          "Ich bleibe zu Hause, weil bin ich krank."
        ], correct: 1 },
      { type: "mc", q: "Як правильно?",
        options: [
          "Ich glaube, dass er kommt morgen.",
          "Ich glaube, dass er morgen kommt.",
          "Ich glaube, dass kommt er morgen.",
          "Ich glaube, dass morgen er kommt."
        ], correct: 1 },
      { type: "mc", q: "Weil es regnet, ___ ich zu Hause.",
        options: ["ich bleibe","bleibe ich","bleibe","ich zu Hause bleibe"], correct: 1 },
      { type: "mc", q: "У підрядному з Modalverb де стоїть Modalverb?",
        options: ["на 1-й позиції","на 2-й позиції","в кінці","перед підметом"], correct: 2 },
      { type: "mc", q: "Сполучник, що зберігає Verb-2:",
        options: ["weil","dass","denn","obwohl"], correct: 2 },
      { type: "gap", q: "Ich lerne Deutsch, weil ich in Berlin arbeiten ___. (will/wollen)", answer: "will" },
      { type: "gap", q: "Es ist gut, dass du ___ bist. (gekommen)", answer: "gekommen" },
      { type: "gap", q: "Wir essen, weil wir Hunger ___. (haben)", answer: "haben" },
      { type: "gap", q: "Ich glaube, ___ er recht hat.", answer: "dass" },
      { type: "tf", q: "У підрядному з weil дієслово залишається на 2-й позиції.", correct: false },
      { type: "tf", q: "Якщо підрядне на початку, у головному є інверсія.", correct: true },
      { type: "match", prompt: "Сполучник → тип:", pairs: [
        { left: "weil", right: "Nebensatz (Verb-кінець)" },
        { left: "dass", right: "Nebensatz (Verb-кінець)" },
        { left: "denn", right: "Hauptsatz (Verb-2)" },
        { left: "und", right: "Hauptsatz (Verb-2)" },
      ]},
      { type: "multi", q: "Які речення правильні?",
        options: [
          "Ich glaube, dass er morgen kommt.",
          "Ich glaube, dass er kommt morgen.",
          "Weil ich krank bin, bleibe ich zu Hause.",
          "Weil ich krank bin, ich bleibe zu Hause."
        ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Weil ich krank bin, ich bleibe zu Hause.", correct: ["Weil ich krank bin, bleibe ich zu Hause."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я думаю, що він завтра прийде.",
        de: ["Ich glaube, dass er morgen kommt.","Ich denke, dass er morgen kommt."] },
    ],
  },

  // ===================================================================
  "satz-modalverben-position": {
    lesson: {
      slug: "satz-modalverben-position",
      level: "A2",
      category: CAT,
      titleDe: "Satzklammer mit Modalverben & Perfekt",
      titleUk: "Рамкова конструкція (Satzklammer)",
      goal: "Будувати речення з модальним дієсловом і Perfekt за принципом рамки: фінітне на 2-й, інфінітив/Partizip II — у кінці.",
      explanation: [
        "<b>Satzklammer</b> («рамка речення») — характерна риса німецької: фінітне дієслово на 2-й позиції, а друга частина (Inf., Part. II, відокремлюваний префікс) — у самому <b>кінці</b>.",
        "<b>Modalverb</b>: <i>Ich <b>muss</b> heute viel <b>arbeiten</b>.</i>",
        "<b>Perfekt</b>: <i>Ich <b>habe</b> gestern Deutsch <b>gelernt</b>.</i>",
        "<b>Відокремлювані префікси</b>: <i>Ich <b>stehe</b> um 7 Uhr <b>auf</b>.</i>",
        "Усе між першим і другим дієсловом — це <b>середнє поле</b>, де діє Te-Ka-Mo-Lo.",
      ],
      table: {
        headers: ["Pos. 1", "V1 (фінітне)", "Mittelfeld", "V2 (кінець)"],
        rows: [
          ["Ich", "muss", "heute viel", "arbeiten."],
          ["Wir", "haben", "gestern Pizza", "gegessen."],
          ["Er", "kann", "gut Deutsch", "sprechen."],
          ["Sie", "steht", "um 7 Uhr", "auf."],
          ["Morgen", "möchte", "ich nach Wien", "fahren."],
        ],
      },
      examples: [
        { de: "Ich kann gut Deutsch sprechen.", uk: "Я добре розмовляю німецькою." },
        { de: "Wir müssen morgen früh aufstehen.", uk: "Завтра нам треба рано встати." },
        { de: "Sie hat das Buch gelesen.", uk: "Вона прочитала книгу." },
        { de: "Ich bin gestern ins Kino gegangen.", uk: "Я вчора ходив(ла) у кіно." },
        { de: "Er möchte einen Kaffee trinken.", uk: "Він хотів би випити кави." },
        { de: "Ich rufe dich morgen an.", uk: "Я зателефоную тобі завтра." },
        { de: "Wir haben am Wochenende viel gearbeitet.", uk: "Ми на вихідних багато працювали." },
        { de: "Du sollst mehr lernen.", uk: "Ти повинен(на) більше вчитися." },
      ],
      tip: "Уяви <b>рамку</b>: на 2-й позиції — відкриваюча дужка, в кінці — закриваюча. Усе важливе живе всередині.",
      mistakes: [
        { wrong: "Ich kann sprechen gut Deutsch.", right: "Ich kann gut Deutsch sprechen." },
        { wrong: "Wir haben gegessen gestern Pizza.", right: "Wir haben gestern Pizza gegessen." },
        { wrong: "Ich aufstehe um 7 Uhr.", right: "Ich stehe um 7 Uhr auf." },
      ],
      exercises: {},
      prevSlug: "satz-weil-dass",
      nextSlug: "satz-temporale-nebensaetze",
    },
    extras: {
      duration: 15,
      premium: false,
      learningGoals: [
        "будувати рамку з Modalverb",
        "будувати рамку з Perfekt",
        "правильно відокремлювати префікс",
      ],
      ruleBox: {
        rule: "<b>Satzklammer:</b> V1 на Pos. 2, V2 (Inf./Part. II/Präfix) — у <b>кінці</b>.",
      },
      ukrainianTips: [
        "В українській «я хочу пити каву» — все підряд; у німецькій інфінітив — у кінець.",
        "Префікси: <i>aufstehen → stehe … auf; einkaufen → kaufe … ein</i>.",
        "Perfekt: <i>haben/sein</i> на 2-й, <i>Partizip II</i> в кінець.",
      ],
      languageComparison: {
        commons: ["Обидві мови вживають допоміжне дієслово в Perfekt."],
        diffs: ["Німецька виносить Partizip II і інфінітив у кінець речення."],
        traps: ["Помилка: ставити Partizip II одразу після haben/sein."],
      },
      summary: [
        "Satzklammer: V1 на Pos. 2, V2 — у кінець.",
        "Modalverb + Infinitiv.",
        "Perfekt: haben/sein + Partizip II.",
        "Відокремлювані префікси — у кінець.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Як правильно?",
        options: [
          "Ich kann sprechen gut Deutsch.",
          "Ich kann gut Deutsch sprechen.",
          "Ich gut Deutsch sprechen kann.",
          "Sprechen ich kann gut Deutsch."
        ], correct: 1 },
      { type: "mc", q: "Як правильно (Perfekt)?",
        options: [
          "Wir gegessen haben Pizza gestern.",
          "Wir haben gegessen gestern Pizza.",
          "Wir haben gestern Pizza gegessen.",
          "Gestern wir haben Pizza gegessen."
        ], correct: 2 },
      { type: "mc", q: "Префікс «auf» у «aufstehen» стоїть…",
        options: ["на 1-й позиції","перед дієсловом","в кінці речення","разом з дієсловом"], correct: 2 },
      { type: "mc", q: "У Satzklammer на 2-й позиції стоїть:",
        options: ["Infinitiv","Partizip II","фінітне дієслово","префікс"], correct: 2 },
      { type: "mc", q: "Я завтра тобі зателефоную = ?",
        options: [
          "Ich anrufe dich morgen.",
          "Ich rufe morgen an dich.",
          "Ich rufe dich morgen an.",
          "Ich rufe an dich morgen."
        ], correct: 2 },
      { type: "gap", q: "Wir müssen morgen früh ___. (aufstehen)", answer: "aufstehen" },
      { type: "gap", q: "Sie hat das Buch ___. (lesen, Part. II)", answer: "gelesen" },
      { type: "gap", q: "Ich bin gestern ins Kino ___. (gehen, Part. II)", answer: "gegangen" },
      { type: "gap", q: "Ich rufe dich morgen ___. (an)", answer: "an" },
      { type: "tf", q: "У Perfekt Partizip II стоїть у кінці речення.", correct: true },
      { type: "tf", q: "У реченні з Modalverb інфінітив стоїть одразу після Modalverb.", correct: false },
      { type: "match", prompt: "Конструкція → V2 (в кінці):", pairs: [
        { left: "Ich muss …", right: "arbeiten" },
        { left: "Ich habe …", right: "gearbeitet" },
        { left: "Ich stehe … …", right: "auf" },
        { left: "Ich möchte …", right: "trinken" },
      ]},
      { type: "multi", q: "Які речення правильні?",
        options: [
          "Ich kann gut Deutsch sprechen.",
          "Ich gut Deutsch sprechen kann.",
          "Wir haben gestern Pizza gegessen.",
          "Wir haben gegessen Pizza gestern."
        ], correct: [0,2] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich aufstehe um 7 Uhr.", correct: ["Ich stehe um 7 Uhr auf."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я хочу завтра поїхати до Берліна.",
        de: ["Ich möchte morgen nach Berlin fahren.","Morgen möchte ich nach Berlin fahren."] },
    ],
  },

  // ===================================================================
  "satz-temporale-nebensaetze": {
    lesson: {
      slug: "satz-temporale-nebensaetze",
      level: "A2",
      category: CAT,
      titleDe: "Temporale Nebensätze: wenn, als, bevor, nachdem, während",
      titleUk: "Підрядні часу",
      goal: "Розрізняти часові сполучники і правильно будувати підрядні часу.",
      explanation: [
        "<b>wenn</b> — теперішнє/майбутнє або повторювані події в минулому (= щоразу коли): <i>Wenn ich Zeit habe, lese ich.</i>",
        "<b>als</b> — <b>одноразова</b> подія в минулому: <i>Als ich klein war, wohnte ich in Kyjiw.</i>",
        "<b>bevor</b> — перед тим як: <i>Bevor ich gehe, putze ich die Zähne.</i>",
        "<b>nachdem</b> — після того як (підрядне в Perfekt, головне в Präsens; або підр. Plusquamperfekt + Präteritum).",
        "<b>während</b> — поки, у той час як: <i>Während ich koche, hört er Musik.</i>",
        "Усі вони — <b>підрядні сполучники</b> → дієслово в кінець!",
      ],
      table: {
        headers: ["Сполучник", "Коли вживати", "Приклад"],
        rows: [
          ["wenn", "теперішнє/майбутнє, повторюване минуле", "Wenn es regnet, bleibe ich zu Hause."],
          ["als", "одноразова подія в минулому", "Als ich 10 war, lernte ich Klavier."],
          ["bevor", "перед тим як", "Bevor ich esse, wasche ich die Hände."],
          ["nachdem", "після того як", "Nachdem ich gegessen habe, gehe ich spazieren."],
          ["während", "поки, у той час як", "Während du schläfst, arbeite ich."],
        ],
      },
      examples: [
        { de: "Wenn ich Zeit habe, rufe ich dich an.", uk: "Коли в мене буде час, я тобі зателефоную." },
        { de: "Als ich Kind war, spielte ich viel draußen.", uk: "Коли я був(ла) дитиною, я багато грав(ла)сь надворі." },
        { de: "Bevor ich schlafe, lese ich ein Buch.", uk: "Перед сном я читаю книгу." },
        { de: "Nachdem ich gefrühstückt habe, gehe ich zur Arbeit.", uk: "Після сніданку я йду на роботу." },
        { de: "Während er kocht, deckt sie den Tisch.", uk: "Поки він готує, вона накриває стіл." },
        { de: "Wenn die Sonne scheint, gehen wir spazieren.", uk: "Коли світить сонце, ми йдемо гуляти." },
        { de: "Als ich in Berlin war, besuchte ich ein Museum.", uk: "Коли я був(ла) у Берліні, я відвідав(ла) музей." },
        { de: "Nachdem wir gegessen hatten, sahen wir einen Film.", uk: "Після того як ми поїли, ми подивились фільм." },
      ],
      tip: "Класичне правило <b>als/wenn</b>: <i>«Immer wenn, einmal als»</i> — «завжди коли — wenn, один раз коли — als».",
      mistakes: [
        { wrong: "Als ich Zeit habe, lese ich. (теперішнє)", right: "Wenn ich Zeit habe, lese ich." },
        { wrong: "Wenn ich klein war, wohnte ich in Kyjiw. (одноразово)", right: "Als ich klein war, wohnte ich in Kyjiw." },
        { wrong: "Bevor ich esse, ich wasche die Hände.", right: "Bevor ich esse, wasche ich die Hände." },
      ],
      exercises: {},
      prevSlug: "satz-modalverben-position",
    },
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "розрізняти als і wenn",
        "правильно вживати bevor / nachdem / während",
        "ставити дієслово в кінець підрядного часу",
      ],
      ruleBox: {
        rule: "<b>als</b> = одноразово в минулому; <b>wenn</b> = теперішнє/майбутнє або повторюване минуле.",
      },
      ukrainianTips: [
        "Українське «коли» = і <b>wenn</b>, і <b>als</b> — обирай за змістом.",
        "<b>nachdem</b> вимагає узгодження часів: <i>підрядне Perfekt → головне Präsens</i>.",
        "<b>während</b> часто перекладається як «поки», «у той час як».",
      ],
      languageComparison: {
        commons: ["Обидві мови мають окремі сполучники для часу."],
        diffs: ["Німецька розрізняє als/wenn там, де українська каже «коли»."],
        traps: ["Помилка: «Als ich Zeit habe» — правильно «Wenn ich Zeit habe»."],
      },
      summary: [
        "wenn — теп./майб./повтор. минуле.",
        "als — один раз у минулому.",
        "bevor — перед; nachdem — після; während — поки.",
        "Verb у кінець підрядного.",
      ],
    },
    exercises15: [
      { type: "mc", q: "___ ich Zeit habe, lese ich.",
        options: ["Als","Wenn","Bevor","Nachdem"], correct: 1 },
      { type: "mc", q: "___ ich klein war, wohnte ich in Kyjiw.",
        options: ["Wenn","Als","Während","Bevor"], correct: 1 },
      { type: "mc", q: "___ ich schlafe, putze ich die Zähne.",
        options: ["Nachdem","Während","Bevor","Als"], correct: 2 },
      { type: "mc", q: "___ ich gegessen habe, gehe ich spazieren.",
        options: ["Bevor","Nachdem","Wenn","Als"], correct: 1 },
      { type: "mc", q: "___ er kocht, deckt sie den Tisch.",
        options: ["Bevor","Nachdem","Während","Als"], correct: 2 },
      { type: "gap", q: "___ ich in Berlin war, besuchte ich ein Museum.", answer: "Als" },
      { type: "gap", q: "___ die Sonne scheint, gehen wir spazieren.", answer: "Wenn" },
      { type: "gap", q: "Bevor ich esse, ___ ich die Hände. (waschen)", answer: "wasche" },
      { type: "gap", q: "Nachdem wir gegessen ___, sahen wir einen Film. (Plusquamperfekt: hatten)", answer: "hatten" },
      { type: "tf", q: "«als» уживають для повторюваних дій у теперішньому.", correct: false },
      { type: "tf", q: "Після «während» дієслово стоїть у кінці підрядного.", correct: true },
      { type: "match", prompt: "Сполучник → значення:", pairs: [
        { left: "wenn", right: "коли (теп./повтор.)" },
        { left: "als", right: "коли (одноразово в мин.)" },
        { left: "bevor", right: "перед тим як" },
        { left: "nachdem", right: "після того як" },
      ]},
      { type: "multi", q: "Які — підрядні сполучники часу?",
        options: ["wenn","und","als","aber","während","oder","nachdem"], correct: [0,2,4,6] },
      { type: "correct", prompt: "Виправ:", wrong: "Als ich Zeit habe, lese ich.", correct: ["Wenn ich Zeit habe, lese ich."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Коли я був(ла) у Відні, я відвідав(ла) музей.",
        de: ["Als ich in Wien war, besuchte ich ein Museum.","Als ich in Wien war, habe ich ein Museum besucht."] },
    ],
  },
};
