// A2 · Дієслова — 11 повних уроків (verben-a2 у mock.ts).
// perfekt і reflexive вже є в lessons.ts → тут лише extras + 15 вправ.
// Решта 9 slug-ів — повні нові уроки.

import type { A2Map } from "./_helpers";

const CAT = "Дієслова";

export const verbenA2: A2Map = {
  // ===================================================================
  perfekt: {
    extras: {
      duration: 18,
      premium: false,
      learningGoals: [
        "обирати між haben і sein у Perfekt",
        "правильно утворювати Partizip II слабких і сильних дієслів",
        "розрізняти дієслова на -ieren (без ge-)",
        "розповідати про вчорашній день і свій досвід",
      ],
      ruleBox: {
        rule: "<b>Perfekt = haben/sein (2 місце) + Partizip II (кінець)</b>. Слабкі: ge- + основа + -t. Сильні: ge- + (зміна голосної) + -en.",
        examples: [
          { de: "Ich habe Pizza gegessen.", uk: "Я з'їв(ла) піцу." },
          { de: "Wir sind nach Wien gefahren.", uk: "Ми поїхали до Відня." },
        ],
      },
      ukrainianTips: [
        "Український доконаний вид («з'їв», «прочитав») найчастіше = німецький Perfekt.",
        "Не плутай: <i>gehen, fahren, kommen, fliegen, schwimmen, aufstehen, einschlafen, werden, sein, bleiben, passieren</i> — завжди з <b>sein</b>.",
        "Дієслова на <b>-ieren</b> ніколи не мають <b>ge-</b>: studiert, telefoniert, fotografiert.",
        "Відокремлювані дієслова: <b>ge-</b> стоїть <i>між</i> префіксом і основою: <i>aufgestanden, eingekauft</i>.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають окремий «доконаний» минулий час."],
        diffs: ["У німецькій вибір допоміжного дієслова (haben/sein) є обовʼязковим — в українській такого розрізнення немає."],
        traps: ["Помилка: «ich habe gegangen» (треба <b>bin</b> gegangen)."],
      },
      summary: [
        "Perfekt = <b>haben/sein + P II</b>.",
        "<b>sein</b>: рух, зміна стану, sein/bleiben/passieren.",
        "Partizip II слабких: ge-…-t; сильних: ge-…-en.",
        "Дієслова на -ieren: <i>без ge-</i>.",
        "Відокремлювані: <i>auf-ge-standen</i>.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ Deutsch gelernt.", options: ["habe","bin","war","hatte"], correct: 0, explain: "lernen не рух → haben." },
      { type: "mc", q: "Wir ___ nach Berlin gefahren.", options: ["haben","sind","waren","hatten"], correct: 1, explain: "fahren = рух → sein." },
      { type: "mc", q: "Anna ___ aufgestanden.", options: ["hat","ist","war","habe"], correct: 1, explain: "aufstehen = зміна стану → sein." },
      { type: "gap", q: "Ich ___ gestern Pizza ___. (essen)", answer: "habe gegessen", hint: "P II сильного: gegessen." },
      { type: "gap", q: "Er ___ um 7 Uhr ___. (aufstehen)", answer: "ist aufgestanden" },
      { type: "gap", q: "Sie ___ in Wien ___. (studieren)", answer: "hat studiert", hint: "-ieren: без ge-." },
      { type: "tf", q: "Дієслова руху (gehen, fahren) утворюють Perfekt із sein.", correct: true },
      { type: "tf", q: "telefonieren → getelefoniert", correct: false, explain: "Правильно: telefoniert (без ge-)." },
      { type: "match", prompt: "Інфінітив → Partizip II:", pairs: [
        { left: "machen", right: "gemacht" },
        { left: "gehen", right: "gegangen" },
        { left: "lesen", right: "gelesen" },
        { left: "fahren", right: "gefahren" },
        { left: "studieren", right: "studiert" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich habe nach Hause gegangen.",
        correct: ["Ich bin nach Hause gegangen."] },
      { type: "correct", prompt: "Виправ:", wrong: "Er hat gestudiert.",
        correct: ["Er hat studiert."] },
      { type: "multi", q: "Які дієслова утворюють Perfekt із sein?",
        options: ["gehen","essen","fahren","lernen","aufstehen","trinken"], correct: [0,2,4] },
      { type: "order", prompt: "Склади Perfekt-речення:",
        words: ["gelernt","habe","Deutsch","ich","gestern"],
        correct: ["ich","habe","gestern","Deutsch","gelernt"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Учора я прочитав цікаву книгу.",
        de: ["Gestern habe ich ein interessantes Buch gelesen.","Ich habe gestern ein interessantes Buch gelesen."] },
      { type: "writeFree",
        prompt: "Напиши 3 речення у Perfekt про вчорашній день.",
        sample: "Gestern bin ich um 8 Uhr aufgestanden. Ich habe Kaffee getrunken und Brot gegessen. Am Abend habe ich einen Film gesehen.",
        explain: "Перевір: haben чи sein? Partizip II в кінці." },
    ],
  },

  // ===================================================================
  "praeteritum-sein-haben": {
    lesson: {
      slug: "praeteritum-sein-haben",
      level: "A2",
      category: CAT,
      titleDe: "Präteritum von sein und haben",
      titleUk: "Präteritum дієслів sein і haben",
      goal: "Уживати war і hatte для опису минулого стану й володіння — навіть в усному мовленні.",
      explanation: [
        "У німецькій <b>Präteritum</b> (простий минулий час) у розмові майже не вживається. Виняток — <b>sein</b> і <b>haben</b>: для них Präteritum звучить природніше за Perfekt.",
        "<b>sein → war</b>, <b>haben → hatte</b>. У 1 і 3 особі однини закінчення немає.",
        "Ці форми використовуємо для опису минулого стану (<i>ich war müde</i>), місця (<i>wir waren in Wien</i>), віку (<i>er war 5 Jahre alt</i>), володіння (<i>ich hatte Zeit</i>) та емоцій (<i>sie hatte Angst</i>).",
        "У письмовому тексті це звичайна норма; в усному — теж: <i>«Ich war gestern krank»</i>, а не <i>«Ich bin krank gewesen»</i>.",
      ],
      table: {
        headers: ["", "sein → war", "haben → hatte"],
        rows: [
          ["ich", "war", "hatte"],
          ["du", "warst", "hattest"],
          ["er/sie/es", "war", "hatte"],
          ["wir", "waren", "hatten"],
          ["ihr", "wart", "hattet"],
          ["sie/Sie", "waren", "hatten"],
        ],
      },
      examples: [
        { de: "Ich war gestern krank.", uk: "Я вчора був(ла) хворий(а)." },
        { de: "Wir waren in Berlin.", uk: "Ми були в Берліні." },
        { de: "Hattest du Zeit?", uk: "Ти мав(ла) час?" },
        { de: "Sie hatte Angst.", uk: "Вона боялась." },
        { de: "Er war 10 Jahre alt.", uk: "Йому було 10 років." },
        { de: "Wart ihr im Kino?", uk: "Ви були в кіно?" },
        { de: "Sie hatten viele Fragen.", uk: "Вони мали багато запитань." },
        { de: "Es war kalt und windig.", uk: "Було холодно й вітряно." },
      ],
      tip: "Запам'ятай як «пісню»: <b>war, warst, war, waren, wart, waren</b> / <b>hatte, hattest, hatte, hatten, hattet, hatten</b>.",
      mistakes: [
        { wrong: "Ich bin krank gewesen gestern.", right: "Ich war gestern krank." },
        { wrong: "Du warts in Wien.", right: "Du warst in Wien." },
        { wrong: "Er hatt Zeit.", right: "Er hatte Zeit." },
      ],
      exercises: {},
      prevSlug: "perfekt",
      nextSlug: "praeteritum-modalverben",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "вільно вживати war і hatte в усіх особах",
        "розповідати про минулий стан, місце, вік, емоції",
        "розрізняти, коли Präteritum, а коли Perfekt",
      ],
      ruleBox: {
        rule: "<b>sein → war</b>, <b>haben → hatte</b>. 1 і 3 ос. однини — без закінчення.",
        examples: [
          { de: "Ich war müde.", uk: "Я був(ла) втомлений(а)." },
          { de: "Sie hatte Hunger.", uk: "Вона була голодна." },
        ],
      },
      ukrainianTips: [
        "Українська не розрізняє «був» і «бував» суворо — у німецькій <b>war</b> = простий минулий стан.",
        "<i>«У мене був час»</i> = <b>«Ich hatte Zeit»</b> (а не «ich war Zeit»).",
        "У німецькій <b>war</b>/<b>hatte</b> звучать природніше за Perfekt навіть у розмові.",
      ],
      languageComparison: {
        commons: ["В обох мовах ці дієслова — серед найчастіших."],
        diffs: ["Українське «був» універсальне; у німецькій war окремий для стану, gewesen — для Perfekt."],
        traps: ["Помилка: <i>«ich bin Zeit gehabt»</i> замість <i>«ich hatte Zeit»</i>."],
      },
      summary: [
        "<b>war</b>: war, warst, war, waren, wart, waren.",
        "<b>hatte</b>: hatte, hattest, hatte, hatten, hattet, hatten.",
        "Вживаємо в розмові й тексті для стану, місця, віку, володіння.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ gestern krank.", options: ["war","bin","habe","hatte"], correct: 0 },
      { type: "mc", q: "Wir ___ in Hamburg.", options: ["war","wart","waren","hatten"], correct: 2 },
      { type: "mc", q: "Du ___ Angst.", options: ["hatte","hattest","hattet","hatten"], correct: 1 },
      { type: "mc", q: "Er ___ keine Zeit.", options: ["hat","hatte","hatten","war"], correct: 1 },
      { type: "gap", q: "Ihr ___ im Park. (sein)", answer: "wart" },
      { type: "gap", q: "Sie (вона) ___ Hunger. (haben)", answer: "hatte" },
      { type: "gap", q: "Wir ___ viele Fragen. (haben)", answer: "hatten" },
      { type: "gap", q: "Es ___ sehr kalt. (sein)", answer: "war" },
      { type: "tf", q: "У 1 ос. однини: ich war / ich hatte — без закінчення.", correct: true },
      { type: "tf", q: "Правильно: «Du warts in Wien».", correct: false, explain: "Правильно: du warst." },
      { type: "match", prompt: "Зістав форми:", pairs: [
        { left: "ich (sein)", right: "war" },
        { left: "du (haben)", right: "hattest" },
        { left: "wir (sein)", right: "waren" },
        { left: "ihr (haben)", right: "hattet" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Er hatt Zeit.", correct: ["Er hatte Zeit."] },
      { type: "order", prompt: "Склади речення:",
        words: ["krank","gestern","ich","war"],
        correct: ["ich","war","gestern","krank"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Учора в мене не було часу.",
        de: ["Gestern hatte ich keine Zeit.","Ich hatte gestern keine Zeit."] },
      { type: "writeFree",
        prompt: "Напиши 3 речення про вчорашній день з war/hatte.",
        sample: "Gestern war ich zu Hause. Ich hatte viel Arbeit. Am Abend war ich sehr müde." },
    ],
  },

  // ===================================================================
  "praeteritum-modalverben": {
    lesson: {
      slug: "praeteritum-modalverben",
      level: "A2",
      category: CAT,
      titleDe: "Präteritum der Modalverben",
      titleUk: "Präteritum модальних дієслів",
      goal: "Розповідати про минулі вміння, дозволи, обов'язки й бажання за допомогою konnte, durfte, musste, sollte, wollte, mochte.",
      explanation: [
        "Модальні дієслова в розмові вживаються переважно в <b>Präteritum</b>, а не в Perfekt. Це коротше й природніше.",
        "Утворення: основа без умляута + <b>-te-</b> + особове закінчення. Тобто умляут зникає: <i>können → konnte</i>, <i>müssen → musste</i>, <i>dürfen → durfte</i>.",
        "1 і 3 особа однини — без закінчення: <i>ich konnte / er konnte</i>.",
        "Порядок слів: модальне на 2 місці, основне дієслово (інфінітив) — у кінці: <i>«Ich musste gestern lange arbeiten.»</i>",
      ],
      table: {
        headers: ["", "können", "müssen", "dürfen", "sollen", "wollen", "mögen"],
        rows: [
          ["ich", "konnte", "musste", "durfte", "sollte", "wollte", "mochte"],
          ["du", "konntest", "musstest", "durftest", "solltest", "wolltest", "mochtest"],
          ["er/sie/es", "konnte", "musste", "durfte", "sollte", "wollte", "mochte"],
          ["wir", "konnten", "mussten", "durften", "sollten", "wollten", "mochten"],
          ["ihr", "konntet", "musstet", "durftet", "solltet", "wolltet", "mochtet"],
          ["sie/Sie", "konnten", "mussten", "durften", "sollten", "wollten", "mochten"],
        ],
      },
      examples: [
        { de: "Ich konnte gestern nicht kommen.", uk: "Я вчора не зміг(ла) прийти." },
        { de: "Wir mussten viel arbeiten.", uk: "Нам довелось багато працювати." },
        { de: "Du durftest nicht rauchen.", uk: "Тобі не можна було курити." },
        { de: "Er wollte ein Eis essen.", uk: "Він хотів з'їсти морозиво." },
        { de: "Sie sollte um 8 da sein.", uk: "Вона мала бути там о 8-й." },
        { de: "Als Kind mochte ich keinen Kaffee.", uk: "У дитинстві я не любив(ла) каву." },
        { de: "Ihr konntet sehr gut Deutsch.", uk: "Ви добре знали німецьку." },
        { de: "Wir wollten ins Kino gehen.", uk: "Ми хотіли піти в кіно." },
      ],
      tip: "Усі модальні в Präteritum <b>втрачають умляут</b>: ö/ü/ä → o/u/a. Винятки немає.",
      mistakes: [
        { wrong: "Ich könnte nicht kommen.", right: "Ich konnte nicht kommen." },
        { wrong: "Er müsste arbeiten gestern.", right: "Er musste gestern arbeiten." },
        { wrong: "Wir wollten gehen ins Kino.", right: "Wir wollten ins Kino gehen." },
      ],
      exercises: {},
      prevSlug: "praeteritum-sein-haben",
      nextSlug: "reflexive",
    },
    extras: {
      duration: 15,
      premium: false,
      learningGoals: [
        "правильно утворювати Präteritum усіх 6 модальних",
        "ставити інфінітив основного дієслова в кінець",
        "не плутати konnte (минуле) з könnte (умовний)",
      ],
      ruleBox: {
        rule: "Модальне без умляута + <b>-te-</b> + закінчення. Інфінітив — у кінці.",
        examples: [
          { de: "Ich konnte nicht kommen.", uk: "Я не зміг(ла) прийти." },
          { de: "Sie musste lange warten.", uk: "Їй довелось довго чекати." },
        ],
      },
      ukrainianTips: [
        "Українська «мусив / міг / хотів» — точно те ж, що musste / konnte / wollte.",
        "Не плутай <b>konnte</b> (минуле, «міг») і <b>könnte</b> (умовне, «міг би»).",
        "У німецькій з модальним <b>обов'язково</b> ставити основне дієслово в інфінітиві в кінець.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають окремі модальні дієслова для бажання, можливості, обов'язку."],
        diffs: ["Українська вільно ставить інфінітив де завгодно; німецька — суворо в кінець."],
        traps: ["Помилка: «ich konnte nicht zu kommen» (без <i>zu</i>!)."],
      },
      summary: [
        "Усі модальні втрачають умляут у Präteritum.",
        "1 і 3 ос. одн. — без закінчення.",
        "Інфінітив основного дієслова — у кінці.",
        "У розмові — частіше Präteritum, ніж Perfekt.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ gestern nicht kommen.", options: ["kann","konnte","könnte","kannte"], correct: 1 },
      { type: "mc", q: "Wir ___ viel arbeiten.", options: ["müssen","mussten","müssten","müsste"], correct: 1 },
      { type: "mc", q: "Er ___ ein Eis essen.", options: ["will","wollte","wollten","wolltest"], correct: 1 },
      { type: "mc", q: "Als Kind ___ ich keinen Kaffee.", options: ["mag","mochte","möchte","möchten"], correct: 1 },
      { type: "gap", q: "Du ___ hier nicht rauchen. (dürfen)", answer: "durftest" },
      { type: "gap", q: "Sie (вони) ___ ins Kino. (wollen)", answer: "wollten" },
      { type: "gap", q: "Ihr ___ pünktlich sein. (sollen)", answer: "solltet" },
      { type: "gap", q: "Wir ___ lange warten. (müssen)", answer: "mussten" },
      { type: "tf", q: "Модальні в Präteritum зберігають умляут.", correct: false, explain: "Усі втрачають: müssen → musste." },
      { type: "tf", q: "Інфінітив у реченні з модальним стоїть у кінці.", correct: true },
      { type: "match", prompt: "Інфінітив → Präteritum (ich):", pairs: [
        { left: "können", right: "konnte" },
        { left: "müssen", right: "musste" },
        { left: "dürfen", right: "durfte" },
        { left: "mögen", right: "mochte" },
        { left: "wollen", right: "wollte" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Ich könnte gestern nicht kommen.",
        correct: ["Ich konnte gestern nicht kommen."], explain: "könnte = умовне; тут треба konnte." },
      { type: "order", prompt: "Склади речення:",
        words: ["arbeiten","musste","ich","lange","gestern"],
        correct: ["ich","musste","gestern","lange","arbeiten"] },
      { type: "translate", prompt: "Переклади:",
        uk: "Ми хотіли піти в кіно.",
        de: ["Wir wollten ins Kino gehen."] },
      { type: "writeFree", prompt: "3 речення про обов'язки минулого тижня з musste/sollte/konnte.",
        sample: "Letzte Woche musste ich viel lernen. Am Freitag konnte ich endlich ausgehen. Ich sollte um 22 Uhr zu Hause sein." },
    ],
  },

  // ===================================================================
  reflexive: {
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "розпізнавати reflexive Verben (sich + дієслово)",
        "правильно вживати рефлексивний займенник в Akkusativ і Dativ",
        "запам'ятати найважливіші зворотні дієслова повсякдення",
      ],
      ruleBox: {
        rule: "Reflexive Verben: дія повертається на самого суб'єкта. Загальна форма: <b>sich + дієслово</b>. Akk-форми: mich, dich, sich, uns, euch, sich.",
        examples: [
          { de: "Ich wasche mich.", uk: "Я вмиваюся." },
          { de: "Wir freuen uns.", uk: "Ми радіємо." },
        ],
      },
      ukrainianTips: [
        "Українській «-ся» (вмиваюся, радію) часто відповідає німецьке <b>sich</b>: <i>sich waschen, sich freuen, sich erinnern</i>.",
        "Якщо в реченні є <b>прямий додаток</b> (Akk-об'єкт), займенник стає Dativ: <i>ich wasche <b>mir</b> die Hände</i>.",
        "У німецькій рефлексивний займенник <b>обов'язковий</b>: <i>«ich freue»</i> — НЕправильно.",
      ],
      languageComparison: {
        commons: ["В обох мовах є категорія зворотних дієслів."],
        diffs: ["В українській «-ся» прикріплюється до дієслова; у німецькій — окреме слово, що змінюється за особами."],
        traps: ["Помилка: «ich wasche sich» (треба <i>mich</i>)."],
      },
      summary: [
        "Reflexivpronomen Akk.: mich/dich/sich/uns/euch/sich.",
        "Reflexivpronomen Dat.: mir/dir/sich/uns/euch/sich.",
        "Akk → без іншого додатку (<i>ich wasche mich</i>). Dat → з додатком (<i>ich wasche mir die Hände</i>).",
        "Топ-дієслова A2: sich freuen, sich interessieren, sich erinnern, sich entscheiden, sich treffen.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich freue ___ auf das Wochenende.", options: ["mir","mich","sich","dich"], correct: 1 },
      { type: "mc", q: "Wir treffen ___ um 18 Uhr.", options: ["sich","uns","euch","mich"], correct: 1 },
      { type: "mc", q: "Sie (вона) interessiert ___ für Musik.", options: ["sich","mich","dich","ihr"], correct: 0 },
      { type: "mc", q: "Ich wasche ___ die Hände.", options: ["mich","mir","sich","dich"], correct: 1, explain: "Є додаток → Dat: mir." },
      { type: "gap", q: "Du erinnerst ___ an mich. (Reflexiv Akk.)", answer: "dich" },
      { type: "gap", q: "Wir entscheiden ___ für Pizza. (Reflexiv Akk.)", answer: "uns" },
      { type: "gap", q: "Er kauft ___ ein neues Auto. (Reflexiv Dat.)", answer: "sich" },
      { type: "gap", q: "Ihr setzt ___ an den Tisch. (Reflexiv Akk.)", answer: "euch" },
      { type: "tf", q: "У реченні «ich wasche mir die Hände» займенник — Dativ.", correct: true },
      { type: "tf", q: "«Ich freue» — правильне речення.", correct: false, explain: "Reflexivpronomen обов'язковий: mich." },
      { type: "match", prompt: "Особа → Reflexivpronomen Akk.:", pairs: [
        { left: "ich", right: "mich" },
        { left: "du", right: "dich" },
        { left: "er/sie/es", right: "sich" },
        { left: "wir", right: "uns" },
        { left: "ihr", right: "euch" },
      ]},
      { type: "multi", q: "Які дієслова є зворотними?",
        options: ["sich freuen","gehen","sich interessieren","essen","sich erinnern"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich wasche sich.",
        correct: ["Ich wasche mich."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я радію вихідним.",
        de: ["Ich freue mich auf das Wochenende."] },
      { type: "writeFree", prompt: "Опиши свій ранок 3-ма реченнями зі зворотними дієсловами.",
        sample: "Ich stehe um 7 Uhr auf. Dann wasche ich mich und putze mir die Zähne. Danach ziehe ich mich an." },
    ],
  },

  // ===================================================================
  "verben-akkusativ": {
    lesson: {
      slug: "verben-akkusativ",
      level: "A2",
      category: CAT,
      titleDe: "Verben mit Akkusativ",
      titleUk: "Дієслова зі знахідним відмінком",
      goal: "Розпізнавати дієслова, які вимагають прямого додатка в Akkusativ, і правильно змінювати артикль.",
      explanation: [
        "<b>Akkusativ-додаток</b> — це об'єкт дії, на який вона безпосередньо спрямована: «Я бачу <i>будинок</i>».",
        "Більшість перехідних дієслів керують Akkusativ: <b>haben, sehen, kaufen, brauchen, essen, trinken, lesen, lieben, suchen, finden, fragen, treffen, besuchen, kennen, verstehen</b>.",
        "У Akkusativ змінюється <b>тільки чоловічий рід</b>: <i>der → den, ein → einen, mein → meinen, kein → keinen</i>. Жіночий, середній і множина — без змін.",
        "Порядок слів: <i>Subjekt + Verb + Akk-Objekt</i>. <i>«Ich kaufe einen Apfel.»</i>",
      ],
      table: {
        headers: ["Рід", "Nominativ", "Akkusativ"],
        rows: [
          ["m", "der/ein Mann", "den/einen Mann"],
          ["f", "die/eine Frau", "die/eine Frau"],
          ["n", "das/ein Kind", "das/ein Kind"],
          ["Pl", "die Leute", "die Leute"],
        ],
      },
      examples: [
        { de: "Ich sehe den Hund.", uk: "Я бачу собаку." },
        { de: "Wir kaufen einen Apfel.", uk: "Ми купуємо яблуко." },
        { de: "Sie liest ein Buch.", uk: "Вона читає книгу." },
        { de: "Er sucht die Schlüssel.", uk: "Він шукає ключі." },
        { de: "Ich brauche einen Stift.", uk: "Мені потрібна ручка." },
        { de: "Wir besuchen unsere Oma.", uk: "Ми відвідуємо нашу бабусю." },
        { de: "Verstehst du die Frage?", uk: "Ти розумієш питання?" },
        { de: "Anna trifft ihren Freund.", uk: "Анна зустрічає свого друга." },
      ],
      tip: "Питання до Akkusativ: <b>Wen? Was?</b> (Кого? Що?). Якщо відповідь — об'єкт дії, ставимо Akkusativ.",
      mistakes: [
        { wrong: "Ich sehe der Hund.", right: "Ich sehe den Hund." },
        { wrong: "Wir kaufen ein Apfel.", right: "Wir kaufen einen Apfel." },
        { wrong: "Er sucht den Schlüssel die Tasche.", right: "Er sucht den Schlüssel in der Tasche." },
      ],
      exercises: {},
      prevSlug: "reflexive",
      nextSlug: "verben-dativ",
    },
    extras: {
      duration: 15,
      premium: false,
      learningGoals: [
        "запам'ятати топ-15 дієслів з Akkusativ",
        "правильно змінювати der → den, ein → einen",
        "не плутати Akkusativ із Nominativ у чоловічому роді",
      ],
      ruleBox: {
        rule: "Akkusativ-Frage: <b>Wen? Was?</b> Тільки <b>der → den, ein → einen</b> у чоловічому роді.",
      },
      ukrainianTips: [
        "Український знахідний (бачу <i>кого/що</i>) майже завжди = німецький Akkusativ.",
        "Українське «купую сир» = «ich kaufe Käse» (без артикля для невизначеної кількості).",
        "У жіночому й середньому роді форма така сама, як у Nominativ — це спрощує життя.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають знахідний відмінок для прямого об'єкта."],
        diffs: ["В українській змінюються всі роди; у німецькій — лише чоловічий."],
        traps: ["Помилка: «ich brauche ein Stift» замість «einen Stift»."],
      },
      summary: [
        "Більшість перехідних дієслів керують Akkusativ.",
        "Чоловічий рід: der → den, ein → einen.",
        "Жін./сер./Pl — без змін.",
        "Питання: Wen? Was?",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich sehe ___ Hund.", options: ["der","den","dem","ein"], correct: 1 },
      { type: "mc", q: "Wir kaufen ___ Apfel.", options: ["ein","einen","einem","eine"], correct: 1 },
      { type: "mc", q: "Sie liest ___ Buch.", options: ["ein","einen","das","den"], correct: 0, explain: "Buch = n → без змін." },
      { type: "mc", q: "Er sucht ___ Schlüssel.", options: ["die","den","das","dem"], correct: 1 },
      { type: "gap", q: "Anna besucht ___ Oma. (її)", answer: "ihre" },
      { type: "gap", q: "Ich brauche ___ Stift. (неозн.)", answer: "einen" },
      { type: "gap", q: "Wir treffen ___ Freund. (нашого)", answer: "unseren" },
      { type: "gap", q: "Verstehst du ___ Frage? (озн.)", answer: "die" },
      { type: "tf", q: "Питання до Akkusativ: Wen? Was?", correct: true },
      { type: "tf", q: "У жіночому роді Akkusativ = Nominativ.", correct: true },
      { type: "match", prompt: "Nom → Akk:", pairs: [
        { left: "der Mann", right: "den Mann" },
        { left: "ein Apfel", right: "einen Apfel" },
        { left: "die Frau", right: "die Frau" },
        { left: "das Kind", right: "das Kind" },
      ]},
      { type: "multi", q: "Які дієслова керують Akkusativ?",
        options: ["sehen","helfen","kaufen","danken","brauchen","gehören"], correct: [0,2,4] },
      { type: "correct", prompt: "Виправ:", wrong: "Wir kaufen ein Apfel.",
        correct: ["Wir kaufen einen Apfel."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я бачу хлопчика.",
        de: ["Ich sehe einen Jungen.","Ich sehe den Jungen."] },
      { type: "writeFree", prompt: "3 речення з різними дієсловами + Akkusativ.",
        sample: "Ich kaufe einen Kaffee. Wir lesen ein Buch. Sie besucht ihre Freundin." },
    ],
  },

  // ===================================================================
  "verben-dativ": {
    lesson: {
      slug: "verben-dativ",
      level: "A2",
      category: CAT,
      titleDe: "Verben mit Dativ",
      titleUk: "Дієслова з давальним відмінком",
      goal: "Запам'ятати ключові дієслова, які керують Dativ, і правильно змінювати артикль.",
      explanation: [
        "<b>Dativ</b> — відмінок «адресата»: <i>«Я допомагаю <b>другові</b>»</i>. Питання: <b>Wem?</b> (Кому?).",
        "Найважливіші Dativ-дієслова A2: <b>helfen, danken, gehören, antworten, gefallen, schmecken, glauben, gratulieren, passen, gehören</b>.",
        "У Dativ змінюються <b>всі роди</b>: <i>der → dem, die → der, das → dem, die (Pl) → den</i> (+ -n до іменника в Pl: den Kindern).",
        "Неозначені: <i>ein → einem (m/n), eine → einer (f), keine → keinen (Pl)</i>.",
      ],
      table: {
        headers: ["Рід", "Nominativ", "Dativ"],
        rows: [
          ["m", "der/ein Mann", "dem/einem Mann"],
          ["f", "die/eine Frau", "der/einer Frau"],
          ["n", "das/ein Kind", "dem/einem Kind"],
          ["Pl", "die Kinder", "den Kindern"],
        ],
      },
      examples: [
        { de: "Ich helfe meiner Mutter.", uk: "Я допомагаю мамі." },
        { de: "Das Buch gehört dem Lehrer.", uk: "Книга належить вчителю." },
        { de: "Wir danken den Eltern.", uk: "Ми дякуємо батькам." },
        { de: "Der Film gefällt mir.", uk: "Фільм мені подобається." },
        { de: "Schmeckt euch die Suppe?", uk: "Вам смакує суп?" },
        { de: "Sie antwortet dem Kind.", uk: "Вона відповідає дитині." },
        { de: "Ich gratuliere dir zum Geburtstag.", uk: "Вітаю тебе з днем народження." },
        { de: "Das Hemd passt ihm gut.", uk: "Сорочка йому добре пасує." },
      ],
      tip: "Класичний список «Dativ-дієслів» варто завчити напам'ять: <i>helfen, danken, gehören, gefallen, schmecken, antworten, glauben, gratulieren, passen</i>.",
      mistakes: [
        { wrong: "Ich helfe meine Mutter.", right: "Ich helfe meiner Mutter." },
        { wrong: "Das Buch gehört der Lehrer.", right: "Das Buch gehört dem Lehrer." },
        { wrong: "Wir danken die Eltern.", right: "Wir danken den Eltern." },
      ],
      exercises: {},
      prevSlug: "verben-akkusativ",
      nextSlug: "verben-akk-dat",
    },
    extras: {
      duration: 15,
      premium: false,
      learningGoals: [
        "знати топ-10 Dativ-дієслів напам'ять",
        "правильно вживати dem/der/dem/den (+n у Pl)",
        "не плутати Dativ з Akkusativ",
      ],
      ruleBox: {
        rule: "<b>Wem?</b> = Dativ. der→dem, die→der, das→dem, die (Pl)→den + -n.",
      },
      ukrainianTips: [
        "Український давальний (кому?) майже завжди = німецький Dativ.",
        "Українській «допомагати <i>другові</i>» = <i>helfen <b>dem Freund</b></i> — не Akkusativ!",
        "У множині Dativ додає -n до іменника: <i>den Kindern, den Männern</i>.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають давальний для адресата."],
        diffs: ["Українські дієслова часто керують іншим відмінком, ніж їх німецькі еквіваленти."],
        traps: ["Помилка: «ich danke <b>den</b> Vater» (треба <i>dem</i>)."],
      },
      summary: [
        "Питання Dativ: <b>Wem?</b>",
        "Артиклі: dem / der / dem / den (+n).",
        "Топ-дієслова: helfen, danken, gehören, gefallen, schmecken.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich helfe ___ Mutter.", options: ["meine","meiner","meinen","mein"], correct: 1 },
      { type: "mc", q: "Das Buch gehört ___ Lehrer.", options: ["den","dem","der","das"], correct: 1 },
      { type: "mc", q: "Wir danken ___ Eltern.", options: ["die","den","der","dem"], correct: 1 },
      { type: "mc", q: "Der Film gefällt ___.", options: ["mich","mir","ich","mein"], correct: 1 },
      { type: "gap", q: "Sie antwortet ___ Kind. (озн., Dat.)", answer: "dem" },
      { type: "gap", q: "Ich gratuliere ___ zum Geburtstag. (тобі)", answer: "dir" },
      { type: "gap", q: "Schmeckt ___ die Suppe? (вам)", answer: "euch" },
      { type: "gap", q: "Wir helfen ___ Kindern. (озн., Dat. Pl)", answer: "den" },
      { type: "tf", q: "У Dativ Pl до іменника додається -n.", correct: true },
      { type: "tf", q: "helfen керує Akkusativ.", correct: false, explain: "helfen + Dativ." },
      { type: "match", prompt: "Дієслово → відмінок:", pairs: [
        { left: "helfen", right: "Dativ" },
        { left: "danken", right: "Dativ" },
        { left: "sehen", right: "Akkusativ" },
        { left: "kaufen", right: "Akkusativ" },
        { left: "gefallen", right: "Dativ" },
      ]},
      { type: "multi", q: "Які дієслова керують Dativ?",
        options: ["helfen","sehen","gefallen","kaufen","danken","gratulieren"], correct: [0,2,4,5] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich helfe meine Mutter.",
        correct: ["Ich helfe meiner Mutter."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я дякую вчителю.",
        de: ["Ich danke dem Lehrer."] },
      { type: "writeFree", prompt: "3 речення з різними Dativ-дієсловами.",
        sample: "Ich helfe meinem Bruder. Das Geschenk gefällt meiner Mutter. Wir danken den Lehrern." },
    ],
  },

  // ===================================================================
  "verben-akk-dat": {
    lesson: {
      slug: "verben-akk-dat",
      level: "A2",
      category: CAT,
      titleDe: "Verben mit Akkusativ und Dativ",
      titleUk: "Дієслова з Akkusativ і Dativ",
      goal: "Правильно вживати дієслова, які мають одночасно прямий (що?) і непрямий (кому?) додаток.",
      explanation: [
        "Деякі дієслова приймають <b>обидва</b> об'єкти: <i>geben, schenken, zeigen, bringen, schicken, kaufen, erklären, sagen, empfehlen, leihen, schreiben, antworten</i>.",
        "Формула: <b>Wem? + Was?</b> — особа стоїть у <b>Dativ</b>, річ — у <b>Akkusativ</b>.",
        "Класичний порядок: <i>Subjekt + Verb + Dativ-Person + Akkusativ-Sache</i>. <i>«Ich schenke <b>meiner Mutter</b> <b>einen Blumenstrauß</b>.»</i>",
        "Якщо обидва об'єкти — займенники, порядок <b>міняється</b>: <b>Akk перед Dat</b>: <i>«Ich schenke <b>ihn ihr</b>.»</i>",
      ],
      table: {
        headers: ["Тип", "Порядок", "Приклад"],
        rows: [
          ["іменник + іменник", "Dat → Akk", "Ich gebe dem Kind den Ball."],
          ["займ. + іменник", "Dat → Akk", "Ich gebe ihm den Ball."],
          ["іменник + займ.", "Akk → Dat", "Ich gebe ihn dem Kind."],
          ["займ. + займ.", "Akk → Dat", "Ich gebe ihn ihm."],
        ],
      },
      examples: [
        { de: "Ich schenke meiner Mutter Blumen.", uk: "Я дарую мамі квіти." },
        { de: "Er zeigt dem Touristen den Weg.", uk: "Він показує туристу дорогу." },
        { de: "Anna schreibt ihrem Freund einen Brief.", uk: "Анна пише другові листа." },
        { de: "Wir bringen euch den Kuchen.", uk: "Ми принесемо вам торт." },
        { de: "Der Lehrer erklärt den Schülern die Regel.", uk: "Учитель пояснює учням правило." },
        { de: "Ich leihe dir mein Buch.", uk: "Я позичу тобі свою книгу." },
        { de: "Sie empfiehlt uns ein Restaurant.", uk: "Вона радить нам ресторан." },
        { de: "Ich schenke es ihr.", uk: "Я дарую це їй.", tag: "обидва займенники" },
      ],
      tip: "Просте мнемо: <b>«Особа перед річчю»</b>. Виняток: коли річ — займенник (ihn/sie/es), він іде попереду.",
      mistakes: [
        { wrong: "Ich gebe das Buch dem Kind.", right: "Ich gebe dem Kind das Buch." },
        { wrong: "Ich gebe ihm es.", right: "Ich gebe es ihm." },
        { wrong: "Er zeigt der Tourist den Weg.", right: "Er zeigt dem Touristen den Weg." },
      ],
      exercises: {},
      prevSlug: "verben-dativ",
      nextSlug: "verben-praep-basis",
    },
    extras: {
      duration: 16,
      premium: false,
      learningGoals: [
        "впізнавати дієслова з двома об'єктами",
        "ставити Dativ-особу перед Akkusativ-річчю",
        "перевертати порядок, коли об'єкт — займенник",
      ],
      ruleBox: {
        rule: "<b>Dativ (кому) + Akkusativ (що)</b>. Займенник-річ — <b>попереду</b> Dativ-особи.",
      },
      ukrainianTips: [
        "Українське «я дарую <i>мамі квіти</i>» — той самий порядок: спершу кому, потім що.",
        "У німецькій «ihn/sie/es» (займенник-річ) ОБОВ'ЯЗКОВО йде попереду: <i>ich schenke <b>es ihr</b></i>.",
        "Не плутай: <i>der Lehrer erklärt <b>dem Schüler die Regel</b></i> — особа в Dativ, не Akkusativ!",
      ],
      languageComparison: {
        commons: ["Обидві мови розрізняють «кому» і «що»."],
        diffs: ["У німецькій порядок об'єктів суворіший і залежить від типу слова (іменник чи займенник)."],
        traps: ["Помилка: «ich gebe ihm es» (треба <i>ich gebe es ihm</i>)."],
      },
      summary: [
        "Двооб'єктні дієслова: <i>geben, schenken, zeigen, schreiben, erklären</i>.",
        "Базовий порядок: <b>Dat → Akk</b> (особа → річ).",
        "Якщо річ — займенник: <b>Akk → Dat</b>.",
        "Особа в Dativ, річ у Akkusativ.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich schenke ___ Blumen.", options: ["meine Mutter","meiner Mutter","mein Mutter","meinen Mutter"], correct: 1 },
      { type: "mc", q: "Er zeigt ___ den Weg.", options: ["den Touristen","dem Touristen","der Tourist","die Touristen"], correct: 1 },
      { type: "mc", q: "Правильний порядок:", options: ["Ich gebe das Buch dem Kind.","Ich gebe dem Kind das Buch.","Ich gebe es dem Kind.","Обидва правильні"], correct: 3 },
      { type: "mc", q: "Ich schenke ___.", options: ["ihr es","es ihr","sie es","es sie"], correct: 1, explain: "Займ.-річ перед Dat." },
      { type: "gap", q: "Wir bringen ___ den Kuchen. (вам)", answer: "euch" },
      { type: "gap", q: "Sie schreibt ___ Freund einen Brief. (своєму)", answer: "ihrem" },
      { type: "gap", q: "Der Lehrer erklärt ___ die Regel. (учням, озн.)", answer: "den Schülern" },
      { type: "gap", q: "Ich leihe ___ mein Buch. (тобі)", answer: "dir" },
      { type: "tf", q: "Базовий порядок: іменник-особа (Dat) перед іменником-річчю (Akk).", correct: true },
      { type: "tf", q: "«Ich gebe ihm es» — правильно.", correct: false, explain: "Має бути: ich gebe es ihm." },
      { type: "match", prompt: "Дієслово → переклад:", pairs: [
        { left: "schenken", right: "дарувати" },
        { left: "zeigen", right: "показувати" },
        { left: "leihen", right: "позичати" },
        { left: "empfehlen", right: "радити" },
      ]},
      { type: "order", prompt: "Склади речення:",
        words: ["meiner Mutter","schenke","ich","Blumen"],
        correct: ["ich","schenke","meiner Mutter","Blumen"] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich gebe ihm es.",
        correct: ["Ich gebe es ihm."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я даю мамі квіти.",
        de: ["Ich gebe meiner Mutter Blumen.","Ich schenke meiner Mutter Blumen."] },
      { type: "writeFree", prompt: "3 речення з дієсловами Dat+Akk (geben, schenken, zeigen).",
        sample: "Ich schenke meinem Vater eine Uhr. Anna zeigt ihrer Freundin die Stadt. Der Lehrer gibt den Kindern Hausaufgaben." },
    ],
  },

  // ===================================================================
  "verben-praep-basis": {
    lesson: {
      slug: "verben-praep-basis",
      level: "A2",
      category: CAT,
      titleDe: "Verben mit Präpositionen: Grundlagen",
      titleUk: "Основи дієслів із прийменниками",
      goal: "Розуміти, що дієслова з прийменниками — це сталі сполуки, які треба вчити цілими, разом з відмінком.",
      explanation: [
        "У німецькій багато дієслів утворюють сталу пару з прийменником: <b>warten <i>auf</i> + Akk., denken <i>an</i> + Akk., sprechen <i>über</i> + Akk., helfen <i>bei</i> + Dat.</b>",
        "Прийменник — <b>не перекладається</b> окремо. Треба запам'ятовувати дієслово + прийменник + відмінок як один блок.",
        "У реченні прийменник стоїть <b>перед об'єктом</b>: <i>«Ich warte auf den Bus.»</i>",
        "Найчастіші пари A2: <b>warten auf, sprechen über, denken an, sich freuen auf/über, sich interessieren für, helfen bei, fragen nach, antworten auf</b>.",
      ],
      table: {
        headers: ["Дієслово", "Präposition + відмінок", "Приклад"],
        rows: [
          ["warten", "auf + Akk.", "Ich warte auf den Bus."],
          ["denken", "an + Akk.", "Ich denke an dich."],
          ["sprechen", "über + Akk.", "Wir sprechen über die Arbeit."],
          ["sich freuen", "auf + Akk. (майбутнє)", "Ich freue mich auf den Urlaub."],
          ["sich freuen", "über + Akk. (теперішнє)", "Ich freue mich über das Geschenk."],
          ["sich interessieren", "für + Akk.", "Sie interessiert sich für Musik."],
          ["helfen", "bei + Dat.", "Er hilft mir bei der Arbeit."],
          ["fragen", "nach + Dat.", "Sie fragt nach dem Weg."],
        ],
      },
      examples: [
        { de: "Ich warte auf den Bus.", uk: "Я чекаю на автобус." },
        { de: "Wir sprechen über das Wetter.", uk: "Ми говоримо про погоду." },
        { de: "Er denkt oft an seine Familie.", uk: "Він часто думає про сім'ю." },
        { de: "Anna freut sich auf den Urlaub.", uk: "Анна радіє відпустці (попереду)." },
        { de: "Ich freue mich über deinen Brief.", uk: "Я радий твоєму листу (вже отримав)." },
        { de: "Sie interessiert sich für Geschichte.", uk: "Вона цікавиться історією." },
        { de: "Der Lehrer hilft den Schülern bei der Aufgabe.", uk: "Учитель допомагає учням із завданням." },
        { de: "Ich frage nach dem Preis.", uk: "Я запитую про ціну." },
      ],
      tip: "Учи дієслово <b>разом</b> з прийменником і відмінком: «warten + auf + Akk.» — як одне слово.",
      mistakes: [
        { wrong: "Ich warte für den Bus.", right: "Ich warte auf den Bus." },
        { wrong: "Sie interessiert sich auf Musik.", right: "Sie interessiert sich für Musik." },
        { wrong: "Er denkt über dich.", right: "Er denkt an dich." },
      ],
      exercises: {},
      prevSlug: "verben-akk-dat",
      nextSlug: "futur-praesens",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "запам'ятати топ-8 дієслів із прийменниками",
        "відрізняти sich freuen auf від sich freuen über",
        "не перекладати прийменник дослівно з української",
      ],
      ruleBox: {
        rule: "Дієслово + прийменник + відмінок — <b>один блок</b>. Учи разом.",
      },
      ukrainianTips: [
        "Українське «думати про» = німецьке <b>denken <i>an</i> + Akk.</b>, а не <i>über</i>.",
        "Українське «чекати на» = німецьке <b>warten <i>auf</i> + Akk.</b>.",
        "Українське «цікавитися чимось» = німецьке <b>sich interessieren <i>für</i> + Akk.</b>",
      ],
      languageComparison: {
        commons: ["Обидві мови мають дієслова з прийменниками."],
        diffs: ["Прийменник у німецькій рідко збігається з українським — треба вчити пари."],
        traps: ["Помилка: «für den Bus warten» (треба <i>auf</i>)."],
      },
      summary: [
        "warten auf + Akk., denken an + Akk., sprechen über + Akk.",
        "sich freuen auf (попереду) / über (зараз).",
        "sich interessieren für + Akk.",
        "helfen bei + Dat., fragen nach + Dat.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich warte ___ den Bus.", options: ["für","auf","an","über"], correct: 1 },
      { type: "mc", q: "Sie interessiert sich ___ Musik.", options: ["für","auf","an","über"], correct: 0 },
      { type: "mc", q: "Wir sprechen ___ das Wetter.", options: ["an","über","auf","von"], correct: 1 },
      { type: "mc", q: "Ich denke ___ dich.", options: ["über","auf","an","für"], correct: 2 },
      { type: "gap", q: "Anna freut sich ___ den Urlaub. (попереду)", answer: "auf" },
      { type: "gap", q: "Ich freue mich ___ dein Geschenk. (вже отримав)", answer: "über" },
      { type: "gap", q: "Er hilft mir ___ der Hausaufgabe.", answer: "bei" },
      { type: "gap", q: "Sie fragt ___ dem Weg.", answer: "nach" },
      { type: "tf", q: "warten керує auf + Akkusativ.", correct: true },
      { type: "tf", q: "denken auf + Akk. — правильно.", correct: false, explain: "denken an + Akk." },
      { type: "match", prompt: "Дієслово → прийменник:", pairs: [
        { left: "warten", right: "auf" },
        { left: "denken", right: "an" },
        { left: "interessieren sich", right: "für" },
        { left: "helfen", right: "bei" },
        { left: "fragen", right: "nach" },
      ]},
      { type: "multi", q: "Які пари правильні?",
        options: ["sprechen über","warten für","denken an","interessieren für","helfen auf"], correct: [0,2,3] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich warte für den Bus.",
        correct: ["Ich warte auf den Bus."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Я цікавлюсь історією.",
        de: ["Ich interessiere mich für Geschichte."] },
      { type: "writeFree", prompt: "3 речення з дієсловами + прийменники.",
        sample: "Ich warte auf meinen Freund. Wir sprechen über die Reise. Anna freut sich auf das Wochenende." },
    ],
  },

  // ===================================================================
  "futur-praesens": {
    lesson: {
      slug: "futur-praesens",
      level: "A2",
      category: CAT,
      titleDe: "Futur mit Präsens",
      titleUk: "Майбутнє за допомогою Präsens",
      goal: "Розповідати про майбутні події найприроднішим способом — теперішнім часом з обставиною часу.",
      explanation: [
        "У німецькій <b>Präsens</b> часто означає майбутнє, якщо в реченні є чітка обставина часу: <i>morgen, nächste Woche, in zwei Tagen, am Freitag, später</i>.",
        "Це найбільш повсякденний спосіб говорити про майбутнє в усному мовленні — простіший і коротший за Futur I.",
        "Формула: <b>Subjekt + Präsens-Verb + Zeitangabe + Rest</b>. <i>«Ich fahre morgen nach Wien.»</i>",
        "Futur I (з <i>werden</i>) у розмові вживають рідше — переважно для передбачень, обіцянок або акценту на наміри.",
      ],
      table: {
        headers: ["Час", "Приклад", "Що звучить природніше"],
        rows: [
          ["Майбутнє (план)", "Ich fahre morgen nach Wien.", "✅ Präsens"],
          ["Майбутнє (передбачення)", "Es wird morgen regnen.", "✅ Futur I"],
          ["Майбутнє (обіцянка)", "Ich werde dir helfen.", "✅ Futur I"],
          ["Майбутнє (розклад)", "Der Zug fährt um 18 Uhr.", "✅ Präsens"],
        ],
      },
      examples: [
        { de: "Morgen fahre ich nach Berlin.", uk: "Завтра я їду до Берліна." },
        { de: "Nächste Woche besuche ich meine Oma.", uk: "Наступного тижня відвідую бабусю." },
        { de: "In zwei Stunden kommt der Zug.", uk: "За дві години прибуває поїзд." },
        { de: "Am Samstag spielen wir Fußball.", uk: "У суботу ми граємо у футбол." },
        { de: "Heute Abend gehen wir ins Kino.", uk: "Сьогодні ввечері йдемо в кіно." },
        { de: "Im Sommer fliegen wir nach Italien.", uk: "Влітку летимо до Італії." },
        { de: "Was machst du morgen?", uk: "Що робиш завтра?" },
        { de: "Später lerne ich noch Deutsch.", uk: "Потім ще повчу німецьку." },
      ],
      tip: "Якщо є обставина часу в майбутньому — сміливо вживай <b>Präsens</b>. Це не помилка, а норма.",
      mistakes: [
        { wrong: "Ich werde morgen Deutsch lernen werden.", right: "Morgen lerne ich Deutsch." },
        { wrong: "Ich fahre Wien morgen.", right: "Morgen fahre ich nach Wien." },
        { wrong: "Wir gehen Kino heute.", right: "Heute gehen wir ins Kino." },
      ],
      exercises: {},
      prevSlug: "verben-praep-basis",
      nextSlug: "futur1-basis",
    },
    extras: {
      duration: 10,
      premium: false,
      learningGoals: [
        "вживати Präsens для запланованих майбутніх подій",
        "правильно ставити обставину часу на 1 або 3 позицію",
        "знати, коли Futur I краще за Präsens",
      ],
      ruleBox: {
        rule: "<b>Präsens + Zeitangabe = майбутнє</b>. Дієслово завжди на 2 місці.",
      },
      ukrainianTips: [
        "Українське «завтра іду в кіно» = німецьке «morgen gehe ich ins Kino» — точно так само.",
        "Не дублюй: «ich werde fahren werde» — це не німецька мова.",
        "У німецькій <b>nach</b> + місто (без артикля): <i>nach Wien, nach Berlin</i>.",
      ],
      languageComparison: {
        commons: ["В обох мовах теперішній час може означати майбутнє."],
        diffs: ["У німецькій це навіть більш поширене, ніж в українській."],
        traps: ["Помилка: ставити обставину часу в кінець без потреби."],
      },
      summary: [
        "Präsens + час = майбутнє.",
        "Обставина часу часто на 1 місці (Morgen fahre ich…).",
        "Futur I — для передбачень/обіцянок.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Морgen ___ ich nach Berlin.", options: ["fahre","fahrte","fuhr","werde fahren"], correct: 0 },
      { type: "mc", q: "Що звучить найприродніше для розкладу?",
        options: ["Der Zug wird um 18 Uhr fahren.","Der Zug fährt um 18 Uhr.","Der Zug ist gefahren.","Der Zug fuhr um 18."], correct: 1 },
      { type: "mc", q: "Що означає «Ich gehe heute Abend ins Kino»?",
        options: ["минуле","теперішнє","майбутнє план","умовне"], correct: 2 },
      { type: "mc", q: "Виправ: «Wir gehen Kino heute.»",
        options: ["Wir gehen ins Kino heute.","Heute gehen wir ins Kino.","Heute wir gehen ins Kino.","Wir heute gehen ins Kino."], correct: 1 },
      { type: "gap", q: "Nächste Woche ___ ich meine Oma. (besuchen)", answer: "besuche" },
      { type: "gap", q: "In zwei Stunden ___ der Zug. (kommen)", answer: "kommt" },
      { type: "gap", q: "Am Samstag ___ wir Fußball. (spielen)", answer: "spielen" },
      { type: "gap", q: "Im Sommer ___ wir nach Italien. (fliegen)", answer: "fliegen" },
      { type: "tf", q: "Präsens із обставиною часу може означати майбутнє.", correct: true },
      { type: "tf", q: "У майбутньому Präsens — це помилка.", correct: false },
      { type: "match", prompt: "Час → значення:", pairs: [
        { left: "morgen", right: "завтра" },
        { left: "nächste Woche", right: "наступного тижня" },
        { left: "in zwei Stunden", right: "за дві години" },
        { left: "im Sommer", right: "влітку" },
      ]},
      { type: "order", prompt: "Склади речення:",
        words: ["fahre","nach Berlin","ich","morgen"],
        correct: ["morgen","fahre","ich","nach Berlin"] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich werde morgen Deutsch lernen werden.",
        correct: ["Morgen lerne ich Deutsch.","Ich lerne morgen Deutsch."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Завтра я зустрічаюся з другом.",
        de: ["Morgen treffe ich meinen Freund.","Ich treffe morgen meinen Freund."] },
      { type: "writeFree", prompt: "3 речення про твої плани на тиждень у Präsens.",
        sample: "Morgen lerne ich Deutsch. Am Mittwoch treffe ich meine Freundin. Am Wochenende fahre ich zu meinen Eltern." },
    ],
  },

  // ===================================================================
  "futur1-basis": {
    lesson: {
      slug: "futur1-basis",
      level: "A2",
      category: CAT,
      titleDe: "Futur I: Grundlagen",
      titleUk: "Основи Futur I",
      goal: "Утворювати Futur I (werden + Infinitiv) і знати, коли він доречніший за Präsens.",
      explanation: [
        "<b>Futur I</b> утворюється за формулою: <b>werden</b> (на 2 місці, відмінюване) + <b>Infinitiv</b> (у кінці).",
        "Відмінювання <b>werden</b>: ich werde, du wirst, er wird, wir werden, ihr werdet, sie werden.",
        "Futur I вживають коли потрібно підкреслити <b>намір</b>, <b>обіцянку</b> або <b>передбачення</b>: <i>«Ich werde dir helfen»</i>, <i>«Es wird morgen regnen»</i>.",
        "Для звичайних планів із чіткою обставиною часу німці частіше вживають <b>Präsens</b>: <i>«Morgen fahre ich»</i>, а не <i>«Ich werde morgen fahren»</i>.",
      ],
      table: {
        headers: ["", "werden + Infinitiv"],
        rows: [
          ["ich", "werde lernen"],
          ["du", "wirst lernen"],
          ["er/sie/es", "wird lernen"],
          ["wir", "werden lernen"],
          ["ihr", "werdet lernen"],
          ["sie/Sie", "werden lernen"],
        ],
      },
      examples: [
        { de: "Ich werde dir helfen.", uk: "Я тобі допоможу.", tag: "обіцянка" },
        { de: "Es wird morgen regnen.", uk: "Завтра буде дощ.", tag: "передбачення" },
        { de: "Wir werden in Berlin studieren.", uk: "Ми будемо навчатися в Берліні." },
        { de: "Sie wird die Prüfung bestehen.", uk: "Вона складе іспит." },
        { de: "Wirst du kommen?", uk: "Ти прийдеш?" },
        { de: "Ich werde nie wieder zu spät kommen.", uk: "Я ніколи більше не запізнюватимусь." },
        { de: "Das wird kein Problem sein.", uk: "Це не буде проблемою." },
        { de: "Wir werden alles schaffen.", uk: "Ми все встигнемо/осягнемо." },
      ],
      tip: "Запам'ятай: <b>werden</b> — на 2 місці, <b>Infinitiv</b> — у кінці. Між ними може стояти що завгодно.",
      mistakes: [
        { wrong: "Ich werde helfen dir.", right: "Ich werde dir helfen." },
        { wrong: "Du wirdst kommen.", right: "Du wirst kommen." },
        { wrong: "Er wird morgen kommt.", right: "Er wird morgen kommen." },
      ],
      exercises: {},
      prevSlug: "futur-praesens",
      nextSlug: "imperativ",
    },
    extras: {
      duration: 12,
      premium: false,
      learningGoals: [
        "відмінювати werden у всіх особах",
        "ставити Infinitiv у кінець речення",
        "обирати між Futur I і Präsens",
      ],
      ruleBox: {
        rule: "<b>werden (2 місце) + Infinitiv (кінець)</b>.",
        examples: [
          { de: "Ich werde dir helfen.", uk: "Я тобі допоможу." },
        ],
      },
      ukrainianTips: [
        "Українське «я допоможу» = німецьке <b>ich werde helfen</b> (Futur I), але «завтра допомагаю» = <b>morgen helfe ich</b> (Präsens).",
        "Не плутай <b>werden</b> (стати/буде) з <b>wollen</b> (хотіти).",
        "Infinitiv обов'язково в кінці: <i>helfen, kommen, lernen</i> — без закінчення.",
      ],
      languageComparison: {
        commons: ["Обидві мови мають окрему форму майбутнього часу."],
        diffs: ["У німецькій вона менш уживана за українську — у розмові часто Präsens."],
        traps: ["Помилка: «ich werde helfen dir»."],
      },
      summary: [
        "<b>werden + Infinitiv</b>.",
        "werden: werde, wirst, wird, werden, werdet, werden.",
        "Для обіцянок, передбачень, акценту на намір.",
        "Для звичайних планів — Präsens.",
      ],
    },
    exercises15: [
      { type: "mc", q: "Ich ___ dir helfen.", options: ["werde","wirst","wird","werden"], correct: 0 },
      { type: "mc", q: "Du ___ kommen.", options: ["werde","wirst","wird","werdet"], correct: 1 },
      { type: "mc", q: "Sie (вона) ___ die Prüfung bestehen.", options: ["wirst","werde","wird","werden"], correct: 2 },
      { type: "mc", q: "Wir ___ alles schaffen.", options: ["werden","wird","werde","werdet"], correct: 0 },
      { type: "gap", q: "Es ___ morgen regnen. (werden)", answer: "wird" },
      { type: "gap", q: "Ihr ___ Deutsch lernen. (werden)", answer: "werdet" },
      { type: "gap", q: "Ich werde nie wieder zu spät ___. (kommen)", answer: "kommen" },
      { type: "gap", q: "Sie (вони) ___ in Berlin studieren. (werden)", answer: "werden" },
      { type: "tf", q: "Infinitiv у Futur I стоїть у кінці.", correct: true },
      { type: "tf", q: "«Du wirdst» — правильно.", correct: false, explain: "Правильно: du wirst." },
      { type: "match", prompt: "Особа → форма werden:", pairs: [
        { left: "ich", right: "werde" },
        { left: "du", right: "wirst" },
        { left: "er", right: "wird" },
        { left: "wir", right: "werden" },
      ]},
      { type: "order", prompt: "Склади речення:",
        words: ["helfen","werde","dir","ich"],
        correct: ["ich","werde","dir","helfen"] },
      { type: "correct", prompt: "Виправ:", wrong: "Ich werde helfen dir.",
        correct: ["Ich werde dir helfen."] },
      { type: "translate", prompt: "Переклади:",
        uk: "Завтра буде дощ.",
        de: ["Es wird morgen regnen.","Morgen wird es regnen."] },
      { type: "writeFree", prompt: "3 обіцянки/передбачення у Futur I.",
        sample: "Ich werde nie wieder lügen. Es wird sicher regnen. Wir werden bald reich sein." },
    ],
  },

  // ===================================================================
  imperativ: {
    lesson: {
      slug: "imperativ",
      level: "A2",
      category: CAT,
      titleDe: "Imperativ",
      titleUk: "Наказовий спосіб",
      goal: "Утворювати наказ і ввічливе прохання у формах du / ihr / Sie і wir.",
      explanation: [
        "<b>Imperativ</b> — форма прохання, наказу, поради. У німецькій є 4 форми: <b>du, ihr, Sie, wir</b>.",
        "<b>du</b>: основа дієслова (часто без -e на кінці). Lern! Komm! Mach! У сильних e→i/ie: Sprich! Lies! Sieh!",
        "<b>ihr</b>: як 2 ос. множини Präsens, але без займенника: Lernt! Kommt! Macht!",
        "<b>Sie</b>: інфінітив + Sie: <b>Lernen Sie! Kommen Sie!</b> Завжди з <b>Sie</b>.",
        "<b>wir</b> (запрошення): як 1 ос. множини, але без займенника на початку: Gehen wir! (= ходімо).",
        "<b>sein</b> — особлива: du sei! ihr seid! Seien Sie! Seien wir!",
        "Часто додають <b>bitte</b> для ввічливості: <i>«Komm bitte!»</i> або <i>«Bitte kommen Sie!»</i>",
      ],
      table: {
        headers: ["", "machen", "kommen", "sprechen", "sein", "haben"],
        rows: [
          ["du", "Mach!", "Komm!", "Sprich!", "Sei!", "Hab!"],
          ["ihr", "Macht!", "Kommt!", "Sprecht!", "Seid!", "Habt!"],
          ["Sie", "Machen Sie!", "Kommen Sie!", "Sprechen Sie!", "Seien Sie!", "Haben Sie!"],
          ["wir", "Machen wir!", "Kommen wir!", "Sprechen wir!", "Seien wir!", "Haben wir!"],
        ],
      },
      examples: [
        { de: "Komm bitte schnell!", uk: "Прийди швидко, будь ласка!" },
        { de: "Macht eure Hausaufgaben!", uk: "Робіть свої домашні завдання!" },
        { de: "Sprechen Sie bitte langsamer.", uk: "Говоріть, будь ласка, повільніше." },
        { de: "Gehen wir ins Kino!", uk: "Ходімо в кіно!" },
        { de: "Sei nicht traurig!", uk: "Не сумуй!" },
        { de: "Lies das Buch!", uk: "Прочитай книгу!" },
        { de: "Helft mir bitte!", uk: "Допоможіть мені, будь ласка!" },
        { de: "Haben Sie keine Angst!", uk: "Не бійтеся!" },
      ],
      tip: "Запам'ятай: у <b>du</b>-формі сильні дієслова з e→i/ie <b>зберігають</b> цю зміну: <i>essen → Iss!, lesen → Lies!, sehen → Sieh!, sprechen → Sprich!</i>",
      mistakes: [
        { wrong: "Du komm!", right: "Komm!" },
        { wrong: "Spreche!", right: "Sprich!" },
        { wrong: "Sein Sie ruhig!", right: "Seien Sie ruhig!" },
      ],
      exercises: {},
      prevSlug: "futur1-basis",
    },
    extras: {
      duration: 14,
      premium: false,
      learningGoals: [
        "розрізняти 4 форми Imperativ",
        "зберігати e→i/ie у du-формі сильних дієслів",
        "правильно вживати sein у наказі",
      ],
      ruleBox: {
        rule: "du = основа · ihr = -t · Sie = Infinitiv + Sie · wir = -en + wir.",
      },
      ukrainianTips: [
        "Українське «йди / йдіть / ходімо» = німецьке Komm! / Kommt! / Gehen wir!",
        "<b>Sie</b>-форма ВСЕ ЖЕ потребує <i>Sie</i> після дієслова — на відміну від du/ihr.",
        "Не плутай <b>Sprich!</b> з <i>Spreche!</i> — у du-формі е переходить в i.",
      ],
      languageComparison: {
        commons: ["В обох мовах є наказовий спосіб з різними формами для «ти / ви»."],
        diffs: ["Німецька має ще <b>wir-Imperativ</b> («ходімо»), якого окремо в українській нема."],
        traps: ["Помилка: «Du komm!» — займенник зайвий."],
      },
      summary: [
        "du: основа (без займенника).",
        "ihr: 2 ос. мн. без займенника.",
        "Sie: Infinitiv + Sie.",
        "wir: 1 ос. мн. + wir («ходімо»).",
        "Сильні з e→i/ie зберігають зміну в du-формі.",
        "sein: Sei! / Seid! / Seien Sie! / Seien wir!",
      ],
    },
    exercises15: [
      { type: "mc", q: "(du, kommen) ___ schnell!", options: ["Kommst!","Komm!","Komme!","Kommen!"], correct: 1 },
      { type: "mc", q: "(ihr, machen) ___ eure Hausaufgaben!", options: ["Macht!","Mach!","Machen Sie!","Machen wir!"], correct: 0 },
      { type: "mc", q: "(Sie, sprechen) ___ bitte langsamer.", options: ["Sprich","Sprecht","Sprechen Sie","Sprechen wir"], correct: 2 },
      { type: "mc", q: "(wir, gehen) ___ ins Kino!", options: ["Gehen wir!","Geht!","Gehen Sie!","Geh!"], correct: 0 },
      { type: "mc", q: "(du, sein) ___ nicht traurig!", options: ["Bist","Sei","Sein","Seid"], correct: 1 },
      { type: "gap", q: "(du, lesen) ___ das Buch!", answer: "Lies" },
      { type: "gap", q: "(du, essen) ___ deine Suppe!", answer: "Iss" },
      { type: "gap", q: "(ihr, helfen) ___ mir bitte!", answer: "Helft" },
      { type: "gap", q: "(Sie, haben) ___ keine Angst!", answer: "Haben Sie" },
      { type: "tf", q: "У du-формі вживаємо «du»: «Du komm!»", correct: false, explain: "Без займенника: Komm!" },
      { type: "tf", q: "Sprich! — правильна форма Imperativ du від sprechen.", correct: true },
      { type: "match", prompt: "Особа → форма від «machen»:", pairs: [
        { left: "du", right: "Mach!" },
        { left: "ihr", right: "Macht!" },
        { left: "Sie", right: "Machen Sie!" },
        { left: "wir", right: "Machen wir!" },
      ]},
      { type: "correct", prompt: "Виправ:", wrong: "Spreche bitte langsamer!",
        correct: ["Sprich bitte langsamer!"] },
      { type: "translate", prompt: "Переклади ввічливо (Sie):",
        uk: "Заходьте, будь ласка!",
        de: ["Kommen Sie bitte herein!","Bitte kommen Sie herein!"] },
      { type: "writeFree", prompt: "Напиши 3 прохання: одне до du, одне до ihr, одне до Sie.",
        sample: "Komm bitte um 18 Uhr! Macht bitte leise! Helfen Sie mir bitte!" },
    ],
  },
};
